### ISSUE TITLE
Selecting "options/preferences" from the top right drop-down menu on the activity screen has no effect

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#100]
Selecting "options" (or is it called "preferences"?) from the top right drop-down menu on the activity screen has no effect. The user has to go back to the initial start screen and select the menu entry from there.
It's no big deal, but a little confusing...

Thanks for this great app!

**Comment by cpfeiffer** [comment]
Yes, there are multiple open issues with the Activity charts: off the top of my head:
- the preferences button
- the back and forth buttons (kind of work in 0.5, but still WIP)
- the "Test" areas below the charts
- landscape orientation
- color scheme (#99)

And this is just the issues, not counting any new features.

Help appreciated :-)

**Comment by cpfeiffer** [comment]
All those issues are pretty much done now.
