### ISSUE TITLE
FR: Adaptive icon

### ISSUE THREAD

**Issue by mueller-ma** [Freeyourgadget/Gadgetbridge#1001]
Api 26 introduced adaptive icons where background and foreground are two different images.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by ashimokawa** [comment]
@mueller-ma 
That's pretty cool, especially since we target API 27 now.

**Comment by danielegobbetti** [comment]
Unfortunately I wasn't able to keep the cast shadow in the adaptive icon, maybe someone can help...

**Comment by mueller-ma** [comment]
Did you try the wizzard in android studio 3?

**Comment by danielegobbetti** [comment]
That's what I used. The cast shadow in our svg has been eaten. The icon doesn't look too bad, but it's different than before.
