### ISSUE TITLE
Amazfitbit Cor available for wiki developing

### ISSUE THREAD

**Issue by mixpc** [Freeyourgadget/Gadgetbridge#1003]
Hello,

I have an Amazfitbit Cor around and since the wiki is not much populated, thought you might be interested in adding bits of info to it. Please, let me know how you would welcome contributions.

Regards,

**Comment by mixpc** [comment]
Good, done. Tech specs and menu options markeddown to the wiki.

Regards,

**Comment by danielegobbetti** [comment]
Thanks for your contribution, I am closing this issue.
