### ISSUE TITLE
Ignore values while Mi Band 2 isn't worn.

### ISSUE THREAD

**Issue by nazco** [Freeyourgadget/Gadgetbridge#1005]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Tonight I decided not to wear my Mi Band 2 while asleep. Instead I put it on the other side of my bed. This morning I synced the data with GB and could see that there was a graph for the pulse value at night. This is really strange and I think it is a general weakness of the optical heart rate measurement especial because the device noticed correctly that it is not worn. I would suggest to ignore data that is measured while the device says that it isn't worn.
![3f1bd0607f94d791](https://user-images.githubusercontent.com/1292551/36540589-3cc63ea0-17db-11e8-8b0b-18b80b440256.png)

#### Your wearable device is:

Mi Band 2 HW Rev. V0.16.2.2
Mi Band 2 SW Rev. 1.0.1.52

#### Your android version is:

Android 7.1.1

#### Your Gadgetbridge version is:

0.24.5 from F-Droid

**Comment by NotAFile** [comment]
Yep, I've noticed the same. The sensor can generate some very wild numbers, it's highly amusing. 

Ideally, it wouldn't measure the heart rate at all if the watch is not worn (I've sometimes been woken up from half-sleep by the brightly flashing leds), but the way it looks that might not be possible without modifying the firmware.

**Comment by danielegobbetti** [comment]
I like the idea. But I believe it makes sense to save the readings as they are received and avoid to plot them if device is not worn. What do you think?

**Comment by nazco** [comment]
Yes you can save the data but should avoid to plot it. If you want to do something further with the database export you can do that filtering easily by yourself.
