### ISSUE TITLE
Music control

### ISSUE THREAD

**Issue by prinzpiuz** [Freeyourgadget/Gadgetbridge#1009]
It will be great if can control music through mi band 2...I found some proprietary app for it in playstore

**Comment by danielegobbetti** [comment]
please use the template and the search functionality

**Comment by prinzpiuz** [comment]
I didn't get it

**Comment by Avamander** [comment]
@prinzpiuz 

When you're creating a new issue there's a whole template for you to be filled, it has a separate point in it that says 

> [ ] - I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

You ignored the template and thus missed that this request is a duplicate. Daniele probably meant one of these https://github.com/Freeyourgadget/Gadgetbridge/issues/979 or https://github.com/Freeyourgadget/Gadgetbridge/issues/741.
