### ISSUE TITLE
Deactivate 'activate display upon lift' when asleep or defined time period

### ISSUE THREAD

**Issue by brettku** [Freeyourgadget/Gadgetbridge#1013]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Please consider adding the ability to temporarily disable 'activate display upon lift' for Amazfit/miband when the device detects you are asleep or a defined time period ie. 10pm to 7am

I have had to deactivate 'activate display upon lift' as my wife gets disturbed at night when i roll over.

#### Your wearable device is:
Amazfit bip
HW V0.11.2.4
FW 0.1.0.86

#### Your android version is:
8.0.0
#### Your Gadgetbridge version is:
0.24.6

**Comment by IzzySoft** [comment]
If that's possible remotely, it would make sense for Pebbles as well I guess. Not saying I'm needing it – but if possible for others, it shouldn't be restricted to a single device :wink:

**Comment by brettku** [comment]
I believe it's possible as it's an option on the 'Notify and Fitness for Amazfit' app, but I can't comment on it's complexity. I appreciate that it would be a low priority feature for the project.

**Comment by IzzySoft** [comment]
@brettku I rather referred to whether it's possible on Pebbles (and other devices). Pebbles have the same feature (light up the display when you shake them), which can be configured on the watch. I'm just not sure if that can be configured "from remote" – though I'd assume so. And if I'm right, it would be nice to have that possibility there, too, combined with "sleep detected". If my Pebble detects me sleeping in a meeting, not lighting up the watch wouldn't hurt, but it could vibrate then (kidding with the latter, of course) :wink:

**Comment by ashimokawa** [comment]
I know how to do this for bip and mi Band 2, just did not do it because I was too lazy to do the settings stuff GUI wise.

The menus are not optimal. There is a "Mi Band" sub menu which is for Mi band 1 and 2. But the feature would be for mi band 2 , bip, cor and not for mi band 1.

I will experiment with the feature anyway.
