### ISSUE TITLE
Authenticator app for Pebble cannot be configured

### ISSUE THREAD

**Issue by ragesoss** [Freeyourgadget/Gadgetbridge#1015]
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
With the ['Authenticator' Pebble app](https://apps.getpebble.com/en_US/application/52f1a4c3c4117252f9000bb8?dev_settings=true&query=authenticator&section=watchapps), configuration does not work. Opening the `Configure` screen for the app leads to a config url that opens in the browser (pebbleauth.cpfx.ca/relaunch.html), but — unlike with the Pebble Android app — it does not recognize that the watch app is already open, so adding tokens isn't possible.

#### Your wearable device is:
Pebble Time Steel / firmware 4.3

#### Your android version is:
7.0

#### Your Gadgetbridge version is:
0.24.6

**Comment by danielegobbetti** [comment]
This is by design and we cannot fix this. In all honesty I wouldn't trust a third-party **website** with my 2FA data, the main point of 2FA is something **only** I own.

**Anyway**, as the watchapp is open source, I suggest you open an issue on its repo to motivate the developer to add a local configuration webpage (using [clay](https://github.com/pebble/clay)), the watchapp will then be configurable also from within Gadgetbridge.

**Comment by ragesoss** [comment]
Thanks, very helpful info!

**Comment by ragesoss** [comment]
Last committed was almost two years ago with https://github.com/cpfair/pTOTP/commit/203c8fb3a0e8c13ed992985f526ed7d4c8ef14eb but issues aren't open on the repo. @cpfair: any interest in maintaining Pebble Authenticator in the post-Pebble era? If so, can you enable issues? I might be up for trying to port the auth page to clay.

**Comment by cpfair** [comment]
I don't think the underlying issue has anything to do with remote vs. local config (though I don't know how GadgetBridge works, so maybe I'm wrong). If you're getting that error it means that the appcomm messages from the watch containing the list of tokens haven't arrived in the JS companion yet, so it can't populate the config page (see https://github.com/cpfair/pTOTP/blob/master/src/js/pebble-js-app.js#L73). You'd need to address that issue - whatever it is - at the same time.

**Comment by danielegobbetti** [comment]
> I don't think the underlying issue has anything to do with remote vs. local config (though I don't know how GadgetBridge works, so maybe I'm wrong).

As the external page is loaded in an external browser (whatever the user has installed / chooses to use if there are multiple) the Pebble object is not available to the opened URL. I was under the impression that your app needed an active connection while in the config page, as the OP mentioned it complained the watch wasn't connected.

@ragesoss could you try the following:
1. open the configuration page from Gadgetbridge as usual (you will get the error)
1. change the URL to ``https://pebbleauth.cpfx.ca/config.html?ver=1.1.0``
1. perform the configuration and push create token
1. (possibly you could get the "network protocol error" message, proceed as per our wiki in this case)
1. send the configuration to the pebble and see if it works
