### ISSUE TITLE
Gadgedbridge misses incoming SMS notifications

### ISSUE THREAD

**Issue by Rinzler89** [Freeyourgadget/Gadgetbridge#1019]
Hi devs,
First, thanks for the effort you are putting in this awesome app.

The issue I'm having is that incoming SMS notifications are not caught by gadgetbridge so they are not forwared to the Bip
In debug mode, the GENERIC_SMS triggers SMS notifications on the Bip though.
I've tried with enabling notifications also with screen on and same behavior.

Gadgetbridge version: 0.24.6
Android version 8.0.0 [OxygenOS 5.0.1][Oneplus 3T]
Bip FW version: 0.1.1.86

I've attached the log where I received an SMS at 21.00 but it wasn't caught to be forwarded to the Bip.

What could be the cause?

[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1794693/gadgetbridge.log)

**Comment by ashimokawa** [comment]
I wasn't able to look at the log yet, but did you grant SMS access permission when gadgetbridge asked at first start? If not you can check later in android settings.

**Comment by Rinzler89** [comment]
@ashimokawa Yes, I checked, SMS permissions are enabled

**Comment by ashimokawa** [comment]
Komisch. :P

Since you have the Bip and are do not need the phone number to answer from your watch, you should be able to disable  the SMS receiver Gadgetbridge  settings, then SMS will be handled though the generic notification receiver, which will probably work.

It is not a fix, just a workaround

**Comment by danielegobbetti** [comment]
I see nothing at all at 21:00, but some blacklisted apps mentioned. Can you please:
- tell us which app you're using for SMS (stock, third party)
- check the list of blacklisted apps

**Comment by Rinzler89** [comment]
@danielegobbetti It's the stock app and it's not blacklisted
I looked in the code and it's covered. com.mms.android
Tried also QKSMS and still nothing.
