### ISSUE TITLE
Gatgetbridge: I made the Slovak translation and added missing Czech translation

### ISSUE THREAD

**Issue by rbarat** [Freeyourgadget/Gadgetbridge#1022]
Hi,

I made Slovak translation (sk) and added missing Czech translation (cs)
Please add it to next version.

Robert

[_Gadgetbridge Sk_Cs-14.3.2018-1.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1810944/_Gadgetbridge.Sk_Cs-14.3.2018-1.zip)

**Comment by rbarat** [comment]
Thanks.

**Comment by ashimokawa** [comment]
@rbarat 

Please use Weblate for translation changes. These will be pulled in here semi-atomatic, including your authorship.

https://hosted.weblate.org/projects/freeyourgadget/gadgetbridge/

We can take the new sk translation if you don't want to import that into Weblate and commit.

However the cs translation changes you make contain a lot of reordering of lines and whitespace changes, making the diff unreadable.

**Comment by TaaviE** [comment]
I already imported the translations.

**Comment by rbarat** [comment]
Thank you much. I see my trannslates on https://hosted.weblate.org/projects/freeyourgadget/gadgetbridge/

**Comment by ashimokawa** [comment]
OK sorry, will pull therm asap
