### ISSUE TITLE
Nitrogen OS rom: SMS notification is not working

### ISSUE THREAD

**Issue by rbarat** [Freeyourgadget/Gadgetbridge#1025]
I am using Android Oreo ROM on Xiaomi Redmi Note 3SE -> My problem -> no SMS notification on Amаzfit Bip watches.
Notify & Fitness APK was the same problem, so they fixed it in the latest version.

Link to my ROM: https://forum.xda-developers.com/redmi-note-3/development/rom-nitrogen-os-11-01-2017-t3536211

**Comment by danielegobbetti** [comment]
I am using Android Oreo 8.1 and SMS notifications DO work. So I am changing the title.

**Comment by rbarat** [comment]
Yes, it is better now. It does not work with built-in SMS application.

**Comment by rbarat** [comment]
I tried Chomp SMS from the Google Playstore. Witch Chomp SMS notifications to Amazfit Bip works.
