### ISSUE TITLE
The watch does not connect automatically to Gadgetbridge after phone restart

### ISSUE THREAD

**Issue by rbarat** [Freeyourgadget/Gadgetbridge#1026]
Problem description:

- Gadgetbridge is connected to the watch
- Reboot my android phone
- Phone turns on, Bluetooth is on and Gadgetbridge starts automatically
- The watch does not connect automatically
- After I tap the watch in the control center, it connects

My wearable device is: Amazfit Bip watch
My phone is: Xiaomi Redmi Note 3 SE (Kate)
My ROM is: Android Oreo - Nitrogen ROM
My Gadgetbridge version is: 0.25.5.5

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by rbarat** [comment]
Why you closed it? This bug is not fixed.

**Comment by NotAFile** [comment]
as you can see from the tag, it is a duplicate

**Comment by TaaviE** [comment]
Duplicate of https://github.com/Freeyourgadget/Gadgetbridge/issues/693 I
assume?

**Comment by rbarat** [comment]
Hi, I understand, but the problem is not resolved in that line 693.

**Comment by danielegobbetti** [comment]
I closed your issue #1024 marking it as duplicate and **explained of which issue that one was a duplicate**.

Minutes later you opened this issue (a duplicate of the duplicate) and you expect to get an explanation?

**Comment by danielegobbetti** [comment]
BTW you did the right thing adding your comment in #693. 👍
