### ISSUE TITLE
Amazfit Cor: Some Weather items not synced correctly

### ISSUE THREAD

**Issue by derwolff** [Freeyourgadget/Gadgetbridge#1033]
Hi,
I noticed that some weather items are not correctly synced with the weather notifcation app.
- the current location name is not updated. You can still see the last location which was synced from Mi Fit app.
- sometimes you can see on the device a field "AQI0" . I think it's a Air Quality value, but it's always 0. The Mi Fit app don't send this item.

FirmwareV1.0.7.43

**Comment by ashimokawa** [comment]
@derwolff 
The reason why I decided to send AQI was that the current temperature was not displayed when I didn't do this. Will re-check. Also I did not know that we can send the location, will do research on that.

**Comment by derwolff** [comment]
Here is a picture how it‘s like on the device.
![77f40816-f36d-4e90-b63d-5a9f437aa010](https://user-images.githubusercontent.com/11608896/37820874-490a82bc-2e82-11e8-802d-d8c58981d465.jpeg)

**Comment by derwolff** [comment]
Here is a picture from the device.
![0527774f-e692-400a-89fa-7f042f1fee8d](https://user-images.githubusercontent.com/11608896/37822350-793ed286-2e86-11e8-9bdb-b5bb05b5f5b8.jpeg)

**Comment by ashimokawa** [comment]
@derwolff 
I tried to address the problems you mention, but since no one of us has a Cor, you will have to wait for the next release or compile master

**Comment by derwolff** [comment]
@ashimokawa 
I saw your code changes. I will try it when F-Droid updates the apk or is there direct download on Github?

**Comment by ashimokawa** [comment]
@derwolff
F-Droid builds and signs the apk for us, so we cannot create compatible apks beforehand

**Comment by ashimokawa** [comment]
@derwolff

0.25.1 is out on fdroid now, Plesse test ;)

**Comment by derwolff** [comment]
Location is working and the AQI symbol is removed but as you describe before the current temperature is not shown anymore. Only min and max. I remember that the Mi Fit app does it in the same way. I don‘t know if this issue could be solved, from my side it‘s ok.
There is another issue but this depends on Openweather. The Amazfit Cor can display the forecast for 4 days but Openweather could only send 3 days in the free version.

**Comment by ashimokawa** [comment]
For more forecast days you could use the lineage weather provider if you run lineage os.
Omniroms weather service is also supported
