### ISSUE TITLE
Mi Band 2 firmware

### ISSUE THREAD

**Issue by marstum** [Freeyourgadget/Gadgetbridge#1040]
My Mi Band 2 HW 0.1.3.3 and Gadgetbridge are working with FW version 1.0.1.81.

**Comment by ashimokawa** [comment]
Thank you for the feedback. I also tested it and will mark it as working.

**Comment by Nenetalo10** [comment]
hello a query, the miband2 works in Gadgetbridge if it has FW 1.0.1.81 ????
