### ISSUE TITLE
TimeStyle 7.1 is not showing weather

### ISSUE THREAD

**Issue by Gabicu** [Freeyourgadget/Gadgetbridge#1045]
Pebble classic
Android 7.0
Gadgetbridge 0.25.0

This whatcface until work to me, but now no work the weather. 
TimeStyle 7. 1

**Comment by TaaviE** [comment]
Update GadgetBridge first.

**Comment by Gabicu** [comment]
Ok.

**Comment by Gabicu** [comment]
I have now Gadgetbridge 0.25.1 and F-Droid 1.0.3
Well, don't work it

**Comment by danielegobbetti** [comment]
@Gabicu please use the issue template next time.

Are you using the weather notification app or the lineageOS/Omnirom provider?

If you are using the weather notification app, please check if the Gadgetbridge "skin" is enabled.

**Comment by Gabicu** [comment]
Sorry.
I use the weather notification app, the skin is ok.
The TrekVolle work ok.

**Comment by danielegobbetti** [comment]
If trekvolle works I tend to believe that there are issues in Timestyle javascript. Unfortunately the watchface is not being updated despite [an issue with a race condition within its JS code](https://github.com/freakified/TimeStylePebble/issues/107) with a [provided fix](https://github.com/freakified/TimeStylePebble/pull/108). And there are several other issues regarding forecasts (watchface will crash if it doesn't receive at least three days of forecast).

Further, Timestyle 7.1 works well for me currenty, this also makes me believe that the current weather data in your area is triggering some bug.

We cannot do much unfortunately, hence I'm closing this.

**Comment by Gabicu** [comment]
Ok
