### ISSUE TITLE
Mi Band 2: display custom text by writing a characteristic?

### ISSUE THREAD

**Issue by ragcsalo** [Freeyourgadget/Gadgetbridge#1049]
I'm developing magic apps which would use the **Mi Band 2** as a remote display.
I'd like to know if it would be possible to display a custom text (just a few characters) by writing a specific characteristic (with a BT LE plugin). If yes, **which characteristic** should I write to, and in what format?
Yes, I've searched the Wiki and also the issues, but no luck... I only found this, but it is only about the font format: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-2-%28HMZK%29-Font-Format
Any help would be appreciated! :-)

Wearable: Xiaomi Mi Band 2
Firmware: v1.0.1.81
Android device: Samsung Galaxy S7 Edge
Cordova plugin: https://github.com/randdusing/cordova-plugin-bluetoothle

**Comment by ashimokawa** [comment]
@ragcsalo 
This is the issue tracker of Gadgetbridge and not a community to help other developers with totally unrelated apps. Everything is in the source code, you just have to find it.

**Comment by abelduran1** [comment]
But @ashimokawa  if we know the answer, we cant turn your back. We all need help at some time.

@ragcsalo find your answer in this function:

/**
     * Send text as call to miBand
     * @param value messaje for miBand
     */
    public static void sendCall(String value){

        /*
         * mensaje = 5  // Con este no sale la verificacion por pulsacion larga 
         * llamada = 3  
         * ?       = 2  //No sale nada
         * ?       = 1  //Mensaje pero sin verificacion por pulsacion larga
         * */
    	
    	/*    Simple(0),
		    Email(1),
		    News(2),
		    IncomingCall(3),
		    MissedCall(4),
		    SMS(5),
		    VoiceMail(6),
		    Schedule(7),
		    HighPriorityAlert(8),
		    InstantMessage(9),
		    // 10-250 reserved for future use
		    // 251-255 defined by service specification
		    Any(255),
		    Custom(-1),
		    CustomHuami(-6);
	    */
    	
    	Byte incomingCall = 3;
    	Byte missedCall = 3;
    	Byte sms = 5;
    	Byte highPriorityAlert = 8;//Sale un corazon pero sin confirmación de vibrado;
    	Byte schedule = 7;//Sale un corazon pero sin confirmación de vibrado;
    	//Byte any = 255;
    	Byte custom = -1;
    	Byte customHuami = -6;
    	Byte alarmClock = 13;
    	Byte alarmClockOrdinal = 6;
    	
    	
    	
    	Byte ALERT_LEVEL_NONE = 0;
    	Byte ALERT_LEVEL_MESSAGE = 1;
    	Byte ALERT_LEVEL_PHONE_CALL = 2;
    	Byte ALERT_LEVEL_VIBRATE_ONLY = 3;
    	
    	
	   	Byte WECHAT = 0;
	   	Byte PENGUIN_1 = 1;
	   	Byte MI_CHAT_2 = 2;
	   	Byte FACEBOOK = 3;
	   	Byte TWITTER = 4;
	   	Byte MI_APP_5 = 5;
	   	Byte SNAPCHAT = 6;
	   	Byte WHATSAPP = 7;
	   	Byte RED_WHITE_FIRE_8 = 8;
	   	Byte CHINESE_9 = 9;
	   	Byte ALARM_CLOCK = 10;
	    Byte APP_11 = 11;
	    Byte INSTAGRAM = 12; //Con la llamada (3) , simbolo de llamada 
	    Byte CHAT_BLUE_13 = 13;
	    Byte COW_14 = 14;
	    Byte CHINESE_15 = 15;
	    Byte CHINESE_16 = 16;
	    Byte STAR_17 = 17;
	    Byte APP_18 = 18;
	    Byte CHINESE_19 = 19;
	    Byte CHINESE_20 = 20;
	    Byte CALENDAR = 21;
	    Byte FACEBOOK_MESSENGER = 22;
	    Byte VIBER = 23;
	    Byte LINE = 24;
	    Byte TELEGRAM = 25;
	    Byte KAKAOTALK = 26;
	    Byte SKYPE = 27;
	    Byte VKONTAKTE = 28;
	    Byte POKEMONGO = 29;
	    Byte HANGOUTS = 30;
	    Byte MI_31 = 31;
	    Byte CHINESE_32 = 32;
	    Byte CHINESE_33 = 33;
	    Byte EMAIL = 34;
	    Byte WEATHER = 35;
	    Byte HR_WARNING_36 = 36;
    	 
    	
    	byte notif        = incomingCall;
        byte alert        = MI_APP_5;

        byte[] parametros = new byte[]{notif,alert};
        byte[] bytes      = value.getBytes(StandardCharsets.US_ASCII);
        //byte[] bytes      = value.getBytes();
        
        byte[] mensaje    = unitBytes(parametros,bytes);

        BluetoothGattCharacteristic bchar = Miband.bluetoothGatt.getService(Miband.Consts.UUID_SERVICE_1811).getCharacteristic(Miband.Consts.UUID_CHARACTERISTIC_2A46);
        bchar.setValue(mensaje);
        Miband.bluetoothGatt.writeCharacteristic(bchar);

    }

**Comment by ragcsalo** [comment]
@abelduran1 Thank you VERY MUCH!!! :-) I will take a look.
@ashimokawa Please accept my apologies, I couldn't find the answer on the web, although I tried... I hope you understand.

**Comment by avcbcoder** [comment]
@ragcsalo did it work? I am trying to achieve the same thing (custom text and icon on MI BAND)... I tried every resource, nothing worked. Can you help me??

**Comment by ragcsalo** [comment]
Unfortunately I couldn't make it work... yet. Let's keep in touch and share any progress we make! :-)

**Comment by avcbcoder** [comment]
I did it ! I am able to write text on band with any one icon
(call/message). But i don't know how to render a custom icon.

**Comment by ragcsalo** [comment]
Thanks again, finally I understood that first I have to authenticate my connection with the Mi Band 2, THEN I can send notifications with text. :-)
