### ISSUE TITLE
Gadgetbridge 0.5.1 crashes with Pebble Time fw 3.3

### ISSUE THREAD

**Issue by glitchphan** [Freeyourgadget/Gadgetbridge#105]
I'm on a Nexus 5 running latest stock 5.1.1 from Google's website. I have not installed the Pebble app or much beyond F-Droid. I did root it via TWRP and SuperSU.

Gadgetbridge was able to pair with the Pebble Time (on latest 3.3 fw), but when I tap it to connect, it says "Unfortunately, Gadgetbridge has stopped." Tried rebooting, reinstalling, and enabling the experimental check boxes in Settings, but no change.

I did tell it to connect while having the log option checked, but the log doesn't seem very helpful.

19:22:55.698 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being created
19:22:55.700 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
19:22:55.708 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
19:23:03.509 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
19:23:03.530 [main] INFO  n.f.g.u.GB - Setting broadcast receivers to: false
19:23:06.820 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being created
19:23:06.822 [main] INFO  n.f.g.s.DeviceCommunicationService - no intent
19:23:15.455 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
19:23:15.460 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
19:23:23.719 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
19:23:23.720 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
19:23:24.657 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
19:23:24.671 [main] INFO  n.f.g.u.GB - Setting broadcast receivers to: false

**Comment by glitchphan** [comment]
Same behavior in 0.5.2.

**Comment by ashimokawa** [comment]
Please try to unpair you PT, and pair it again via the normal Android Bluetooth Settings (not Gadgetbridge).
I was told the PT displays two devices (one LE and one non LE), and what you say happens when trying to connect with the LE instance.
Also could you send a logcat containing the stack trace of the crash, it seems to be not included in the .log you sent.

**Comment by glitchphan** [comment]
The LE one was the issue. I had initially paired through Gadgetbridge and it only gave me one choice. Thanks!

**Comment by ashimokawa** [comment]
That's good to hear.
Anyway we should not show the LE Pebble at all.

Since we do not own a Pebble Time, please report any further issues you might find.
