### ISSUE TITLE
Notifications from Silence are not shown

### ISSUE THREAD

**Issue by xtotdam** [Freeyourgadget/Gadgetbridge#1053]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I am using [Silence](https://silence.im) for sms. Unfortunately Gadgetbridge treats its notifications as system ones and doesn't show them, as it can be seen from logs:
```
<notification from Signal>
21:29:28.701 [main] INFO  n.f.g.e.NotificationListener - Processing notification 2102545854 from source org.thoughtcrime.securesms with flags: 513
21:29:28.703 [main] INFO  n.f.g.e.NotificationListener - found wearable action: Ответить  null
21:29:28.708 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
21:29:29.658 [Thread-2] INFO  n.f.g.s.d.p.PebbleIoThread - unhandled message to endpoint 3010 (6 bytes)
<notification from Silence>
21:29:37.960 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
21:29:43.758 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
21:29:46.026 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
21:30:29.789 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
21:30:34.659 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
```
I have tried several times and it is always treated like it. 

It is a major difference from Pebble app (at least old one), which had whitelist of apps, and GB has blacklist.

#### Your wearable device is:

Pebble Steel (old one, not 2)
FW 2.9.1-bits

#### Your android version is:

8.0.0

#### Your Gadgetbridge version is:

0.25.1 (latest on f-droid at the moment)

**Comment by ashimokawa** [comment]
@xtotdam 
You have to disable SMS support in Gadgetbridge settings to fix you problem. 

The reason is that we blacklist alternative SMS Apps in the generic notification receiver since it would otherwise result in double notifications (one picked up from the Android SMS receiver, and one picked up from the actual notification)

(In your case the SMS might be encrypted, so it would not make sense to use the SMS receiver, but only the notification receiver which already contains the decrypted content)

**Comment by xtotdam** [comment]
@ashimokawa 
Thank you, this works!

Maybe this should be mentioned in the wiki or somewhere, I can't be the only one

**Comment by ashimokawa** [comment]
Adding this to the wiki would be a valuable contribution 

😇

**Comment by danielegobbetti** [comment]
I'm closing this, please @xtotdam update our wiki according to your experience, feel free to ask question here if you have doubts.

**Comment by xtotdam** [comment]
It is hard for me to write things but I tried to describe problem and solution as clearly as possible
Thanks @ashimokawa for the detailed answer 
https://github.com/Freeyourgadget/Gadgetbridge/wiki/SMS-notifications-are-lost-somewhere

**Comment by IzzySoft** [comment]
Thanks for the wiki page, @xtotdam! Somehow I miss the part of your using an alternative SMS app, and whether you disabled (or even removed) the default one. Currently it sounds like a "general issue" (even with the default app), which it is not if I understand correctly. Could you please include those details? I'm thinking of something along the lines:

> **Problem:** You're using an alternative SMS app (and have disabled/removed the default app). Now all notifications but SMS are shown …

Of course, if you didn't disable/remove the default SMS app, skip the part in parenthisis :wink:

**Comment by xtotdam** [comment]
@IzzySoft 
I have extended wiki page, thank you, this really is an important addition.
However it would be nice if someone whose mother language is English proof read the wiki page.

**Comment by IzzySoft** [comment]
Thanks a lot, @xtotdam! I'm not a native speaker either, but to me it looks perfect now! :+1:
