### ISSUE TITLE
Pebble: Support Android companion apps which use "PebbleKit Android"

### ISSUE THREAD

**Issue by ashimokawa** [Freeyourgadget/Gadgetbridge#106]
To implement this , we would have to listen for Pebble Intents and forward these to the Pebble and back. Also some connection tracking would be necessary.

This would enable software like eg. ventoo (http://www.pebblebike.com) to work with Gadgetbridge.

**Comment by ashimokawa** [comment]
This is a partially a bad hack, but it works now with the following tested apps at least:
Ventoo
Meerun

Most other apps are expected to fail because we do not support the content provider part yet which can be used to query connection state, firmware revision etc. Apps that use this feature will think no pebble is connected and won't work.

**Comment by glitchphan** [comment]
This is awesome! I just updated to 0.6.0 and I can initiate calls through Pebble Dialer! For the receiving part now just need an option like the SMS one to disregard incoming calls.

**Comment by ashimokawa** [comment]
@glitchphan
I don't know what you mean. I can think of two possibilities:

1) You want a feature for Gadgetbridge to ignore incoming calls, so that they are handled by Pebble Dialer

2) One feature of Pebble Dialer is not working that you want to have fixed.

1) would be easy for 2) I would need more detailed information. ;)

**Comment by glitchphan** [comment]
I meant the first (easy) one :)

**Comment by ashimokawa** [comment]
@glitchphan 
Ok, this will be in 0.6.1 to be released next weekend at latest.

**Comment by ashimokawa** [comment]
I am closing this, because it is implemented since 0.6.0

**Comment by glitchphan** [comment]
This has been working great and I am now answering calls with Pebble Dialer and "Phone Calls" set to Never in Gadgetbridge :).

**Comment by ashimokawa** [comment]
@glitchphan 
Great to hear.
I guess we still need support #130 for caller pictures (you don't see them, right?)

**Comment by kas70** [comment]
@ashimokawa is this there a possibility to get runnerup working the same way like you did with ventoo and meerun?

**Comment by kas70** [comment]
@ashimokawa is this there a possibility to get runnerup working the same way like you did with ventoo and meerun?
