### ISSUE TITLE
[miband2] whitelist 46048 firmware

### ISSUE THREAD

**Issue by caioau** [Freeyourgadget/Gadgetbridge#1061]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

Hi I have a miband2 (HW: V0.16.2.2) and I upgraded the firmware as instructed on the wiki to the recommended and everything worked (before it was 1.0.1.69 now is 81)

thanks , continue the great work

**Comment by danielegobbetti** [comment]
Whitelisted in 5df799419e9455eeb2e5bdf7ebd269eda55896ee
