### ISSUE TITLE
Amazfit Bip: Sometimes duplicate notifications

### ISSUE THREAD

**Issue by cni-md** [Freeyourgadget/Gadgetbridge#1062]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your wearable device is:
Amazfit BIP v0.1.1.17

#### Your android version is:
Android 7.0 MIUI 9.2

#### Your Gadgetbridge version is:
0.25.1 fdroid

I want to change the number of repetitons for notifications. At the moment I am getting all notifications  3 times. I changed the number from default 3 to 1 in the Mi Band settings but with no effect (all different types of notifications). I am still getting the notifications 3 times. 
I changed the vibration pattern ("sound") to force the change -> no change.
I reconnect the watch -> no change.

I this similar to #1007 ?

**Comment by ashimokawa** [comment]
Your issue is totally unrelated to mi band settings , they are ignored for notifications. 

Which notifications do you get 3 times?

**Comment by cni-md** [comment]
E-Mail notifications 4 times for each mail, but sms only one, "other" notifications = android spam (lock you apps with a password) or alarm messages from "gtd dtg" 3 times.

**Comment by Giant3** [comment]
I have something like this too, Android 7, Amazfit BIP  v. 0.0.9.29, Gadgetbridge V. 0.26.3

**Comment by gigawatts** [comment]
In my case, I get double notifications for SMS. I use Signal as my default SMS app, and signal messages I only get once, but SMS come through twice, once with the same icon as the signal only messages, and a second with the generic green text bubble. Also for emails, I get one from Gmail, one generic email icon.

**Comment by derBroBro** [comment]
Same for me, android 8.0.0, bip 1.0.2.0, gadgetbridge 0.27.1
For me calendar events occure 3 times (+encoding errors)

**Comment by tradej** [comment]
The SMS solution works for me (vanilla Nokia 5), but I still get double calendar notifications (from Etar) even after disabling Google Calendar. E-mail arrives only once.

Nokia 5
Android 8.1.0
Gadgetbridge 0.28.1 (F-Droid)
Bip firmware 1.1.2.05

**Comment by tradej** [comment]
Update: Slack notifications arrive twice, and are logged twice. However, the notification on the phone is shown only once. Log:

```
16:34:35.251 [main] INFO  n.f.g.e.NotificationListener - Processing notification 1126750525 from source com.slack with flags: 529
16:34:35.265 [main] INFO  n.f.g.e.NotificationListener - found wearable action: Reply  null         
16:34:35.293 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
16:34:35.295 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 16:34:35: Transaction task: new notification with 1 actions
16:34:35.296 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 16 August, 16:34: WriteAction on characteristic: 00002a46-0000-1000-8000-00805f9b34fb
16:34:35.302 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 00002a46-0000-1000-8000-00805f9b34fb: 0xfa 0x01 0x0b 0x23 0x35 0x2d 0x64 0x6f 0x63 0x75 0x6d 0x65 0x6e 0x7
16:34:35.319 [main] INFO  n.f.g.e.NotificationListener - Processing notification 1126750536 from source com.slack with flags: 17
16:34:35.320 [main] INFO  n.f.g.e.NotificationListener - found wearable action: Reply  null 
16:34:35.326 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
16:34:35.328 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 16:34:35: Transaction task: new notification with 1 actions
```

Same setup as previous comment, except I've update Gadgetbridge to version 0.29.0.

**Comment by gigawatts** [comment]
Pretty much all my notifications are stacking now. For example, I get a
SMS, I get notified on the phone and bip, but I don't dismiss it on the
phone. Later another SMS comes, I get a notification on the phone, but then
I get 2 stacked notifications on the bip, one from the first SMS, the
another right after from the second SMS. This continues to stack until I
dismiss everything on the phone. It never used to do this.

**Comment by mmuh** [comment]
I got my signal notifications to just sent one now somehow, but my gmail still sends double notifications on every mail. Very annoying.

**Comment by gigawatts** [comment]
This might vary by Android version, as my old phone (Android 5.1) that I'm
using right now doesn't have any double notifications, but my Pixel running
Android 9 stacks all un-read notifications and repeats them all everytime a
new one comes in. Any update on narrowing down this issue?

**Comment by mmuh** [comment]
Interesting. I'm running Android 8.1.0 on my N6.1 (AndroidOne).

**Comment by danielegobbetti** [comment]
Current master could fix this issue, please test if you can and send reports :-)

**Comment by danielegobbetti** [comment]
Possibly 0.31, if the changes are not reverted for unforeseen issues.

**Comment by danielegobbetti** [comment]
0.31 was tagged, contains the fixes and will be available soon. Closing.
