### ISSUE TITLE
Improvements for the Bip?

### ISSUE THREAD

**Issue by matpower64** [Freeyourgadget/Gadgetbridge#1067]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
First of all, the Bip's settings are piggybacked at the Mi Band ones, and while it works, there are a few things left to desire, the biggest one is the display settings, it only shows Mi Band-related ones instead of what's available for the Bip.

- Gadgetbridge, as you can see, it is MiBand only
- Mi Fit

Furthermore, the beta/Chinese firmware added three new features:

- ~~AliPay (Part of the display settings AFAIK)~~ **DONE in 0.26.3**
- Smart Alarms (Haven't tested it yet, but the description describes it as a smart alarm-like feature)
- Shortcuts (Basically, swiping from left on watch shows either weather or AliPay, **configurable from Mi Fit**)

Those are obviously not supported yet and they might change later, but it might be good to know about those anyway. If I am right, there's only the need for implementing the smart alarms and shortcuts. The AliPay button only shows a QR Code and requires the AliPay app to scan it.

#### Your wearable device is:

**Amazfit Bip**
**FW:** 0.1.1.29 - Whitelist 6228
**RES:** 33 - Whitelist 7746
**GPS:** 9567,8b05506,0,0,
**Mi Fit with the firmware:** 3.3.4.10, available [here](https://www.apkmirror.com/apk/anhui-huami-information-technology-co-ltd/mi-fit/mi-fit-3-3-4-10-release/)

#### Your android version is: 
Android 8.1 - LineageOS 15.1
#### Your Gadgetbridge version is: 
0.25.1 from F-Droid

**Comment by ashimokawa** [comment]
@matpower64 

I know that the settings are a mess, and we need to completely rethink this.  The "problem" was that the Bip and all the tons of new Huami devices (Cor, etc) all use the same protocol, except for some minor changes/additions, so the Mi Band 2 stuff was just working for the Bip when we first got ours.

The "displayed items" thing also started working out of nowhere with some beta firmware and in in attempt so display Alipay I bricked my Bip (see #957 for details), so yes, it scares me. The Bip is not really smart, if it crashes after boot and reboots, it does it forever instead of going to recovery (like pebble would). The command sequence that probably bricked my Bip is commented somewhere in the source code...

About smart alarm things went back and forth in firmware releases, sometimes strings regarding smart alarm where removed, sometimes new ones popped up, but it was never working in practice. I will retry now that you say it.

**Comment by ashimokawa** [comment]
@matpower64 
Tried again without luck on the beta fw you mentioned, I never had smart alarm working. Let me know if you have "proof" that it works in mi fit...

**Comment by matpower64** [comment]
Well, I tried using the smart alarm during this week and... I don't think it worked, I *might* have gotten it working on Thursday, but I was sleepy (it was like 5:30am) and it is likely I just woke up right before the alarm kicked in or it just went off at the determined time and I pressed snooze, I am not really sure. Probably just my brain playing tricks on me since I was thinking about it when I woke up.

As for the brick due to AliPay, I believe AliPay wasn't fully implemented until two or three versions ago in the 0.1.1.XX series, which might have caused the brick (It would be really nice if I could find the report or changelog for that again, I think I saw it on some subreddit). I do understand your fear of messing with it again and I wouldn't risk adding a feature that could end up bricking devices either. The Bip is just too trigger happy when you do something unexpected, and the lack of a recovery mode kills any attempt of serious modding.

**Comment by ashimokawa** [comment]
@matpower64 
Enabling and Disabling Alipay is implemented in Gadgetbridge 0.26.3 which is out on F-Droid.

About smart alarm I will try again.

Regarding Shortcuts. You tried it and it worked? If so, a Bluetooth dump when you do this would be helpful (we do not use Mi Fit).

**Comment by matpower64** [comment]
Yeah, Shortcuts are working ever since they've gotten implemented. A Bluetooth dump is this, right? gadgetbridge.log

**Comment by ashimokawa** [comment]
@matpower64 
No I mean what is mentioned here 

https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files

Section under "Android's Bluetooth Logging (BT Snoop)"

**Comment by ashimokawa** [comment]
Shortcuts are supported now.
I am closing this, please open another issue for smart alarms if you got these working with Mi Fit!
