### ISSUE TITLE
Notifications stay forever

### ISSUE THREAD

**Issue by rototom** [Freeyourgadget/Gadgetbridge#1068]
#### Before opening an issue please confirm the following:
- [x ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
**EDITED**
I get notifications on my pebble, but they stay forever, if I dont cancel them.

*In case of a bug, do not forget to attach logs!*

#### Your wearable device is:
**edited**
Pebble

*Please specify model and firmware version if possible*

#### Your Gadgetbridge version is:

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by rototom** [comment]
Sorry, but where is the problem solved? I looked for it in wiki and in the issues. Why do you simply close this?

**Comment by danielegobbetti** [comment]
@rototom your issue contains absolutely no content beside the template

**Comment by rototom** [comment]
" I get notifications on my pebble, but they stay forever, if I dont cancel them."

**Comment by danielegobbetti** [comment]
Please add the issue after the "your issue is:" line. I edited your first message.
I cannot understand what you are experiencing from the description, where do you expect the notifications to be canceled? On the android device or on the Pebble?

**Comment by rototom** [comment]
I expect the notifications on my pebble to disappear after a few minutes, and as far as I remember they did so in the past. Now they stay forever, until I cancel them on the watch.

**Comment by danielegobbetti** [comment]
99% you have the pebble in quiet mode. In this mode notifications are not auto-dismissed.

**Comment by rototom** [comment]
Unfortunatly its the 1%

**Comment by danielegobbetti** [comment]
Once the notifications reach the pebble we have no control over the way they are displayed. If you are absolutely sure that your pebble is not in quiet mode, then you probably set the notification timeout to none. All of this is local to the pebble and is nothing we can change from gadgetbridge.
