### ISSUE TITLE
Miband 2 FW 1.0.1.81

### ISSUE THREAD

**Issue by Nenetalo10** [Freeyourgadget/Gadgetbridge#1069]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*

#### Your wearable device is: MIBand2

*Please specify model and firmware version if possible*

#### Your Gadgetbridge version is: 0.25.1

hello a query, the miband2 works in Gadgetbridge if it has FW 1.0.1.81 ????

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by IzzySoft** [comment]
I see you didn't check the "I have read the wiki" checkbox. Because had you read it, you would have [found the answer](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-2-Firmware-Update). Took me 15 secs. And I have no MiBand, so I didn't know in advance either.
