### ISSUE TITLE
Compatibility of timestamp contained in the exported gpx files

### ISSUE THREAD

**Issue by Bahjesaispas** [Freeyourgadget/Gadgetbridge#1076]
I've tried to upload my .gpx files on Strava but it seems that isn't compatible (Strava error when I try to upload a file https://support.strava.com/hc/en-us/articles/216917947-Uploading-GPS-files-without-time-information).
The app notifify & fitness can do it, so I think it's possible to handle that with GB.

**Comment by danielegobbetti** [comment]
I changed the title to make it more generic.

**Comment by cpfeiffer** [comment]
We do actually have timestamps in our export, so I'm wondering what's missing here. Which version of Gadgetbridge did you use to export the gpx file?

If you can share (privately) a non-working gpx file, exported with 0.26.1, we can quickly find out what's wrong. Alternatively, can you open the gpx file with a text editor and check whether there are
`<trkpt...>` elements without a `<time>...</time>` child element, or maybe one without a proper value?

**Comment by Bahjesaispas** [comment]
A gpx file (avaible 30 days) https://ufile.io/iv917 if you want to take a look. 

GB version : 0.26.1
Android version : 8.1.0 
Amazfit bip firmware : 0.1.1.29

**Comment by danielegobbetti** [comment]
@Bahjesaispas your gpx file looks manipulated (it's formatted differently than the output of Gadgetbridge), further the heading states that it was saved with Gadgetbridge 0.26.**0**.

Can you please share a file:
- directly taken from gadgetbridge, without passing through other tools
- synchronized with version 0.26.**1** of gadgetbridge

**Comment by mbenitob** [comment]
Great to finally have access to gps records of my Amazfit bip!! Truly thanks.

Please, fix time format.
The recorded time reads
<time>2018-04-21T12:59:59+0200</time> 
and next record 
<time>2018-04-21T01:00:01+0200</time>

It should have gone to 13:00:01 instead or it should state am/pm.

Below more complete track extract:
<time>2018-04-21T12:59:59+0200</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>67</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></trkpt><trkpt lon="-0.722048" lat="37.759817"><ele>47.000000</ele><time>2018-04-21T01:00:01+0200</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>68</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></trkpt><trkpt lon="-0.722037" lat="37.759758"><ele>47.000000</ele><time>2018-04-21T01:00:03+0200</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>69</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></trkpt><trkpt lon="-0.722011" lat="37.759705"><ele>47.000000</ele><time>2018-04-21T01:00:05+0200</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>70</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></trkpt><trkpt lon="-0.721989" lat="37.759645"><ele>47.000000</ele><time>2018-04-21T01:00:07+0200</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>71</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></trkpt><trkpt lon="-0.721963" lat="37.759592">

**Comment by Bahjesaispas** [comment]
This one should work (https://ufile.io/ik3gd) 

`<gpx version="1.1" creator="nodomain.freeyourgadget.gadgetbridge.GBApplication 0.26.1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">`

Strava always give me the same error message when I try to upload.

**Comment by piggz** [comment]
I get the same error. Strangely, gpsvisualiser.com accepts the file, and allows it to be saved back to box... the saved file does then work on Strava.

**Comment by danielegobbetti** [comment]
@Bahjesaispas the file you uploaded is not taken directly from Gadgetbridge. You are using some kind of tool that (among other things) does a formatting/indentation step and possibly strips some XML elements.

@piggz can you compare the two files to see what changed?

**Comment by piggz** [comment]
From what I can tell, it doesn't contain the HR extension, doesn't contain the metadata tag, and has line breaks. I'll post the 2 files next, comparing them isn't easy without a computer, I'm on holiday with just a tablet and amazfit!

**Comment by piggz** [comment]
Original https://www.piggz.co.uk/owncloud/index.php/s/3D9e6SQaQrftMjj
Modified https://www.piggz.co.uk/owncloud/index.php/s/qt6kxHrdzccH83M

**Comment by piggz** [comment]
The only thing I changed in the original was the file name, so I could open it in an Android text editor

**Comment by Nicole1338** [comment]
I had the same problem and I figured out that Strava had a problem with UTC Timestamps without the colon.

E.g:  
- <time>2018-04-23T17:52:42+0200</time> -> not ok
- <time>2018-04-23T17:52:42+02:00</time> -> ok
- <time>2018-04-23T09:16:57Z</time> -> ok

So I added this to my code:

`public static String formatIso8601(Date date) {
	if(GBApplication.isRunningNougatOrLater()){
		return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX", Locale.US).format(date);
	} else {
		return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ") {
			@Override
			public StringBuffer format(Date date, StringBuffer toAppendTo, FieldPosition pos) {
				StringBuffer rfcFormat = super.format(date, toAppendTo, pos);
				return rfcFormat.insert(rfcFormat.length() - 2, ":");
			}
		}.format(date);
	}
}`

But I still have a problem with my Timezone. The Activity list is one hour behind but the .gpx track itself is one hour ahead.

**Comment by Bahjesaispas** [comment]
@danielegobbetti When I click on the activity on GadgetBridge, Osmand~ open it and save it automatically (and should edit it too). I tried directly on GB and I can upload it on strava without problem. I manually upload it as a file on the website. I've not edit the name of the activities, it works like a charm.

**Comment by danielegobbetti** [comment]
@piggz I also notice that the track name is in a different place, but I doubt it could be the reason.

**Comment by danielegobbetti** [comment]
I just pushed some changes, please try latest master (@Nicole1338 the change is similar to the one you used, **thanks**! ; I altered it a bit to fix our testcase/Travis as well).

The timezones weren't touched, I'm waiting for further feedback.

**Comment by danielegobbetti** [comment]
I believe the fixes are worth a minor release already, but I'd wait until this evening (cest) for a confirmation or a more detailed description of the timezone issues.

**Comment by piggz** [comment]
Ive just tested master, and it uploaded to strava fine.

**Comment by Nicole1338** [comment]
I tried to fix my issue but it's kind of weird.
The list with the activities shows the wrong time. For example 16:11 instead of 17:11 and the first trackpoint looks like:
```xml
<trkpt lat="49..." lon="11...">
<ele>335.000000</ele>
<time>2018-04-24T16:12:37+02:00</time>
<extensions>
<gpxtpx:TrackPointExtension>
<gpxtpx:hr>70</gpxtpx:hr>
</gpxtpx:TrackPointExtension>
</extensions>
</trkpt>
```
There is always one minute difference but 2018-04-24T16:12:37+02:00 is parsed to 18:12  o'Clock.

i found a FIXME in:
nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/operations/FetchSportsSummaryOperation.java

I tried to use the Gregorian calendar and added a few lines of code
// FIXME: should honor timezone we were in at that time etc
``` java
        // ...so do it like this
        // FIXME: should honor timezone we were in at that time etc
        long timestamp_start = BLETypeConversions.toUnsigned(buffer.getInt()) * 1000;
        long timestamp_end = BLETypeConversions.toUnsigned(buffer.getInt()) * 1000;
        long duration = timestamp_end - timestamp_start;
        // old stuff
//        summary.setStartTime(new Date(getLastStartTimestamp().getTimeInMillis()));
//        summary.setEndTime(new Date(getLastStartTimestamp().getTimeInMillis()+duration));

        // new stuff
        GregorianCalendar start = BLETypeConversions.createCalendar();
        start.setTimeInMillis(timestamp_start);
        Date startTime = new Date(start.getTimeInMillis());
        summary.setStartTime(startTime);

        GregorianCalendar end = BLETypeConversions.createCalendar();
        end.setTimeInMillis(timestamp_end);
        Date endTime = new Date(end.getTimeInMillis());
        summary.setEndTime(endTime);
```
The track in the list shows up correctly with this changes, but it picked up the trackdata from the next following track. So it starts with the correct time, latitude and longtitude etc. but the offset calculation is done with the wrong data. :/

``` xml
<trkpt lat="49..." lon="11...">
<ele>328.000000</ele>
<time>2018-04-24T17:12:11+02:00</time>
<extensions>
<gpxtpx:TrackPointExtension>
<gpxtpx:hr>77</gpxtpx:hr>
</gpxtpx:TrackPointExtension>
</extensions>
</trkpt>
```

I don't know why it's happening..

**Comment by danielegobbetti** [comment]
@Nicole1338 I think it depends on the fact that the summaries (the entries shown in the list) are fetched first, and the details are fetched next. The rounding difference you state is possibly triggering the fetch of the following gpx track (the start timestamp might be used as a ``>`` key for fetching the gpx track).

**Comment by danielegobbetti** [comment]
@Nicole1338 could you try changing Line 75 of ``FetchSportsDetailsOperation.java`` to:

                getSupport().getTimeBytes(sinceWhen, TimeUnit.SECONDS)));

**Comment by Nicole1338** [comment]
When I change it to TimeUnit.SECONDS than the track seem to be empty, but there wasn't an error or something special in the logcat..
"No selected activity contains a GPX track to share"

I also compared my tracks with the MiFit App and it seems that always the first few trackpoints are lost with Gadgetbridge.

**Comment by Nicole1338** [comment]
> The correct thing to do is adding this line (72) in the same file:
sinceWhen.set(Calendar.SECOND,0);

@danielegobbetti I tried this and the timestamp in the list looks fine, but it still catches the wrong .gpx data.

**Comment by danielegobbetti** [comment]
0.26.2 was published on F-droid and contains the fixes mentioned above. @Nicole1338 I suggest we use a separate issue to discuss the problem you are experiencing (which is important and which I am still working on). I will close this.
