### ISSUE TITLE
Mi Band 2 Not Connecting

### ISSUE THREAD

**Issue by fnordson** [Freeyourgadget/Gadgetbridge#1077]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Mi Band 2 won't reconnect after initial connection after peering.

So looking for device, peering, data sync afterwards worked perfect yesterday.
I disconnected the device and tried to connect again today. Didn't work.

I tried deactivating BT peering.
I downloaded the Fix-It-Something App, this one found it. Tried Gadgetbridge again. Didn't work. (I de-installed the app afterwards again)
Tried to remove and add again. Didn't work.

I uninstalled Gadgetbridge and reinstalled it.
Again it found the device, connected, sync worked perfect.
Disconnected and connection is not working. 

GPS is on (even though it seems to not be the issue since I found out about it today and it worked without it yesterday)

For some reason it's not writing a debug file now.
I have the old one pre uninstall if required: https://pastebin.com/87ibf03K

#### Your wearable device is:

Mi Band 2

HW; V0.1.3.3
FW: 1.2.1.53

#### Your android version is:

MotoG Play (retgb)
Android 7.1.1

(tried with a Samsung phone, this one couldn't find the device at all)

#### Your Gadgetbridge version is:

0.26.1

**Comment by cpfeiffer** [comment]
For some reason, the authentication with the band doesn't work (it sends 0x10,0x03,0x04). Either your band is somehow already authenticated to some other device and refuses our new request. Well, or something else.

You could try to uncheck the pairing option in Gadgetbridge's preferences. After doing that, unpair the devices and do the discovery again (with Location enabled).

**Comment by fnordson** [comment]
I had this peering option unchecked yesterday. It didn't help.
However, I got up in the morning. Pushed "connect" and it connected instantly. There is also a new log now. 
Could you have a look at it? Maybe you can see what was different. 
https://pastebin.com/fezX09sH

**Comment by adolfintel** [comment]
I can confirm I have the same issue. Same versions and everything. I also tried different firmware versions without success. I purchased this specific model because it seemed to be well supported by gadgetbridge. 
I tried pairing, unpairing, trying to make gadgetbridge discover the device in every way I could think of, I even tried inputting the BT address manually, but no luck.
__Eventually__ it connected, after pairing, unpairing, and reconnecting for over an hour. Most of the times, gadgetbridge couldn't even find the device during discovery.

My phone is a OnePlus 3T, running Lineage 15.1 (Android 8.1).

**Comment by cpfeiffer** [comment]
@adolfintel um, how did you try different firmware versions when you can't even connect?

**Comment by adolfintel** [comment]
Yes, I tried that and it didn't work.
When it was finally able to discover the device after a hour of trying, it worked perfectly, and connects almost instantly.
I should also point out that the device was never connected to the official app, only gadgetbridge.

**Comment by cpfeiffer** [comment]
@fnordson The log confirms we do pretty much the same thing. We ask the band for a random key, we get the key, we encrypt the key and send it back. And this time it accepts it. No idea why it didn't work last time. :upside_down_face:

If this happens again, please yell!

**Comment by cpfeiffer** [comment]
@adolfintel I mean, how did you change the firmware version if you were unable to connect to the device. Did you use another app? Could it be that they were both running concurrently?

**Comment by adolfintel** [comment]
Ah yes, I wasn't clear about that in my post. I tried the different versions after the device finally connected to gadgetbridge. After the update, it reconnects (automatically, or after selecting it from the list), but if I remove the device from the list it won't find it anymore and I have to start all over again.
There must be something weird going on in the pairing or in the first connection to the device.
Actually, let's go full conspiracy theorist: what if the firmware was designed explicitly to discourage the use of custom apps by having some sort of "first activation" that is performed by the proprietary app, that only allows the device to do the first connection through the app, or wait an excruciating amount of connection attempts if you're using another app?

**Comment by fnordson** [comment]
OK update on my device here:

It works...it just work. I push connect, it connects. I disconnect, reconnect. Everything works...
No idea what it was. I did not change the firmware since I didn't see the use of it (use it mostly as a pulse logger). 
In the end, I can't say how I fixed it besides what I wrote above. I guess trying on and on, unpeering and peering got it used to my phone. 
A different tip for others may have come from a fried: he had the problem that the phone itself peered with the band. He had to delete it from the BT options there before it worked with GB. @adolfintel  maybe you should check this. 
I also turn on bluetooth and GPS on before I start gadgetbridge. Since this worked once, It's now my ritual ;) 

From my side, the issue can be closed.

**Comment by adolfintel** [comment]
I had bluetooth and location turned on as well.
It must be something in the discovery and pairing process, maybe the keys they exchange are somehow incorrect.

**Comment by fnordson** [comment]
@adolfintel 
I really tried a lot times. Though now, it only takes 2-3 sec to connect.
The attempts before took quite some time and were all useless. I'd suggest unpairing it several times and pairing it again. I had also closed the app every time I started a new "cycle" of peering. 

You might also try to install that Fix-It-App https://play.google.com/store/apps/details?id=com.mc.fixitformiband2&hl=de let it look for it and uninstall it afterwards like I did. Maybe it was related. (At some point it asked me to enter the MAC, when I started entering the MAC, it filled it in automatically and was connected). Also uninstall GB and reinstall it again making no changes to it.

**Comment by thePanz** [comment]
@fnordson if that app worked to "unpair" the device, maybe (maybe) the GB should have such a feature too? wdyt? :)

**Comment by adolfintel** [comment]
Speaking of which, the automatic reconnection is wonky and might be related to the problem. If I walk away from the phone, when I come back 90% of the times it doesn't reconnect and I find gadgetbridge stuck waiting for the band to connect.
I'm not quite sure how they are supposed to discover each other?
