### ISSUE TITLE
Pebble apps like Timer won't install to Pebble 2

### ISSUE THREAD

**Issue by yaomtc** [Freeyourgadget/Gadgetbridge#1079]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*

I try to install the pbw using Gadgetbridge but the progress bar on the watch pauses around 10%, and then says Failed.

#### Your wearable device is:

*Please specify model and firmware version if possible*

Pebble 2, silk21,  v4.3

#### Your android version is:

8.0

#### Your Gadgetbridge version is:

0.26.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

![img_20180421_122400844](https://user-images.githubusercontent.com/5534045/39086528-bf11d754-4560-11e8-9f86-21937bf9387b.jpg)

![img_20180421_122406142](https://user-images.githubusercontent.com/5534045/39086535-e618a684-4560-11e8-8391-4b82a53ac2d3.jpg)

![screenshot_20180421-122418](https://user-images.githubusercontent.com/5534045/39086541-ef150b10-4560-11e8-8504-98ac5af0f7ba.png)

[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1934786/gadgetbridge.log)

**Comment by danielegobbetti** [comment]
Did you perhaps customize the MTU values?

**Comment by yaomtc** [comment]
I don't recall, but it's 23.

**Comment by yaomtc** [comment]
Thanks, removing the value and reconnecting solved the issue.
