### ISSUE TITLE
SMS displayed twice on the pebble watch when using a 3rd party SMS App

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#108]
I am using Pebble time and the SMS application https://github.com/qklabs/qksms. when I receive a SMS it is displayed twice on the watch and not marked as a SMS, just as two normal notification.

In addition to that I can not quick reply to that sms even if the application supports android wear quick replies.

Thanks

**Comment by ashimokawa** [comment]
To work around the issue with the the duplicate SMS you should set SMS notification to "never", so only the qksms notification is picked up.

Currently we do not not support android wear quick notifications. You mean it is supported by qksms?

And what do you mean by "not marked as SMS"? I do not have a Pebble Time so I can only guess what you are expecting.

**Comment by roidelapluie** [comment]
Well the logo displayed on the pebble is not the SMS logo but the "bell" generic notification logo.

**Comment by roidelapluie** [comment]
Well I see in the SMS app " Modify your preset responses to be used from your Android Wear device"

**Comment by ashimokawa** [comment]
You should receive one bell for the "generic notification" we pick up from the 3rd party SMS App and one "message in the bottle" for the SMS we pick up via Intent from Android itself.

Did you try the official Pebble Time App? Did it have support for Android wear quick replies?

Please be aware that Gadgetbridge is work in progress and you should only expect the features listed in the README to work. Everything else is work-in-progress or has not even been started.

**Comment by ashimokawa** [comment]
Duplicate SMS with QKSMS is fixed and will be in the next release.
For the rest of your bug report please refer to issue #103 which covers Interactive replies.

**Comment by roidelapluie** [comment]
Thank you very much for all your work on this project!
