### ISSUE TITLE
German short description is too long

### ISSUE THREAD

**Issue by mueller-ma** [Freeyourgadget/Gadgetbridge#1080]
Maximum char count for the short description in the play store is 80 chars (https://support.google.com/googleplay/android-developer/answer/113469?hl=en). I haven't found information about limits in f-droid, but I guess they have the same limits. The description truncated in the f-droid app.

You can write a small script validation these strings to make sure they aren't too long and run the script in travis.

**Comment by danielegobbetti** [comment]
https://gitlab.com/fdroid/fdroidclient/issues/1361
apparently f-droid also settled to 80 chars but its truncating short description at 74 already.

You can issue a PR with the shortened text if you want. The file is here: https://github.com/Freeyourgadget/Gadgetbridge/blob/master/fastlane/metadata/android/de-DE/short_description.txt

**Comment by LuccoJ** [comment]
Shouldn't this bug be filed against German?

Sorry.
