### ISSUE TITLE
Mi band hrx  issue

### ISSUE THREAD

**Issue by pradeepvarma107** [Freeyourgadget/Gadgetbridge#1084]
MI BAND HRX 

Firmware Version : 1.0.1.52

Bug

THE MI BAND HRX EDITION PEDOMETER is HIGHLY INACCURATE

lots of firmware bugs please fix this bug 
if u want to see the pedometer bug please check this website and see the below screen shots 
many users are waiting to fix this bug

Hope u will reply soon and upgrade the firmware 

Link 

http://en.miui.com/thread-951721-1-1.html

**Comment by cpfeiffer** [comment]
It is the firmware of the device that handles this, and the firmware is outside our control. In case you already flashed the latest firmware and the problem persists, you can only contact your dealer or the manufacturer.

**Comment by pradeepvarma107** [comment]
Can u give.me mi band hrx firmware flash file
