### ISSUE TITLE
Database Export in readable format

### ISSUE THREAD

**Issue by anony11** [Freeyourgadget/Gadgetbridge#1085]
Hi, I saw there's no way of exporting data in a readable way, but other apps(non-propietary) allows it, and I found this one particularly appealing.
#### Your issue is:
Exporting data to a file maybe in a spreadsheet format
#### Your wearable device is:
Mi Band 2

#### Your android version is:
Oreo
#### Your Gadgetbridge version is:
2.6

I want to set up an infographic of my heartbeat and statistics for my mom cause she is harassing me with questions about where I go and about if I eat enough(I'm Italian). Help

**Comment by danielegobbetti** [comment]
I really don't know where to start.

1. Use the issue template.
2. Check the very first two checkboxes in the issue template.
3. Find a [relevant wiki page](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Activity-Analysis) using the keyword **database**.
4. Find [several](https://github.com/Freeyourgadget/Gadgetbridge/issues/879) [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues/623) that list potential issues with the exported DB and how to find the meaning of each field.
