### ISSUE TITLE
[no issue/MiBand2]Data Export & Reuse

### ISSUE THREAD

**Issue by fnordson** [Freeyourgadget/Gadgetbridge#1091]
Do anyone have any experience with exporting the data to any other database/program so I can watch/store/work with it on a PC?

I looked at it and it's beyond me.

**Comment by x2764tech** [comment]
If you use the export data feature, you can then use DropBox/Syncthing/Google Drive to synchronize the data to a PC. 
The data itself is a Sqlite Database - there are plenty of tools around that will help you extract data from it.

**Comment by fnordson** [comment]
Perfect. SQlite.  
I'll try that. Thank you very much.

**Comment by x2764tech** [comment]
There's also a couple of links on [this thread](https://github.com/Freeyourgadget/Gadgetbridge/issues/1066#issuecomment-383543990) that might help too
