### ISSUE TITLE
Amazfit Cor - update of actual firmware failed and connection problems

### ISSUE THREAD

**Issue by FrankK1** [Freeyourgadget/Gadgetbridge#1095]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

The update of the actual firmware (MiFit 3.3.2) doesn't work. The RES-file work, the updater recognize the right version (RES 56, 31263) and can download to the band. The FW-file failed, the updater cannot recognize the version and give the feedback: file can not install, device not ready. The MiFit app update the FW after without issues. But it looks like the new FW prevent the communication with GadgetBridge.

#### Your wearable device is:

Amazfit Cor fw V1.0.7.52

#### Your android version is:

LineageOS 15.1-20180507

#### Your Gadgetbridge version is:

0.26.3

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1996601/gadgetbridge.log)

**Comment by ashimokawa** [comment]
@FrankK1 
Also please try to unpair the device once (in Android settings), then press the + button in gadgetbridge and pair the device in gadgetbridge again (wont loose any data), this is sometimes necessary after a firmware update with bip (had this once)
