### ISSUE TITLE
Need apk for older versions.

### ISSUE THREAD

**Issue by ankitisrawat** [Freeyourgadget/Gadgetbridge#1097]
Greetings.
I want to downgrade my MI 1A band from version 5.16.11.15 to 5.15.7.14.
I have sucessfully extracted the firmware file from mi fit apk.
When i tried to downgrade the firmware from file it fails.
I have tried all three version of gadgetbridge from f.droid but it fails.
Plz provide a apk link for the gadgetbridge 0.13.8

**Comment by ashimokawa** [comment]
If you enable the "F-Droid archieve" repository inside the F-Droid app you can download all versions down to 0.1.0.

That being said I doubt it will help...
