### ISSUE TITLE
Couldn't connect to pebble 2

### ISSUE THREAD

**Issue by yshui** [Freeyourgadget/Gadgetbridge#1098]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Couldn't connect to Pebble 2. Gadgetbridge says "Connecting", but never succeed. Pebble 2's bluetooth setting screen will show the phone as "connected" briefly.

The last couple lines of the log says

```
05-15 11:34:14.022 I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.ble.PebbleGATTClient(17935): Pebble requested MTU: 23
05-15 11:34:14.022 I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.ble.PebbleGATTClient(17935): onDescriptorWrite() status=0
05-15 11:34:14.023 I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.ble.PebbleGATTClient(17935): subscribing to PPoGATT read characteristic
05-15 11:34:14.122 I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.ble.PebbleGATTClient(17935): onDescriptorWrite() status=0
05-15 11:34:14.122 I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.ble.PebbleGATTClient(17935): setting MTU
05-15 11:34:14.366 I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.ble.PebbleGATTClient(17935): Pebble requested MTU: 339
05-15 11:34:14.412 I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.ble.PebbleGATTClient(17935): Pebble requested MTU: 339
05-15 11:34:19.020 I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.ble.PebbleGATTClient(17935): onCharacteristicChanged()00000005-328e-0fbb-c642-1aa6699bdada 000F0000005802
05-15 11:34:26.202 I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.ble.PebbleGATTClient(17935): onCharacteristicChanged()00000005-328e-0fbb-c642-1aa6699bdada 009F0000005802
05-15 11:35:13.623 W/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread(17935): error while connecting: connection failedjava.io.IOException: connection failed
```

#### Your wearable device is:
Pebble 2

#### Your android version is:
8.1.0

#### Your Gadgetbridge version is:
0.26.4

**Comment by yshui** [comment]
`GATT Client Only` is enabled in pebble settings

**Comment by danielegobbetti** [comment]
try this: 
- set/keepthe ``client only`` option **enabled**
- forget the Pebble (on the android device) and the android device (on the pebble)
- toggle bluetooth on both pebble and android
- add the pebble again (pressing the + button in gadgetbridge)

If you follow the steps above you should not loose anything (neither on GB or on the Pebble)

**Comment by ashimokawa** [comment]
And it seems to work more reliable when you are NOT in the Bluetooth menu on the pebble while pairing (for whatever reason)

After re-pairing the pebble for the client mode, the other (client+server) mode still works BTW.

**Comment by IzzySoft** [comment]
> * add the pebble again (pressing the + button in gadgetbridge)

And **ONLY** there (do not pair it in Android's BT dialog).

**Comment by yshui** [comment]
@danielegobbetti That works. Closing this now.

**Comment by IzzySoft** [comment]
@danielegobbetti [done](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-2-(BTLE)-specifics) and linked to [the Pebble index](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble). Proof readers (and editors) welcome :wink:

Note I've started a new page for that, covering specifics for Pebble-2 (or rather BTLE) devices. If you think this should rather go to a different place as it e.g. affects non-Pebbles, feel free to adjust.
