### ISSUE TITLE
Gadgetbridge app gets crashed.

### ISSUE THREAD

**Issue by Sammaz2** [Freeyourgadget/Gadgetbridge#1105]
### Actual behavior
I opened the Gadgetbridge opensource android app. After that I clicked on the options present on the top left corner of the page. And then I clicked on the Database management option. After that I clicked on EmptyDB option. And then I spended some time on the app. After that I got back to the database management option. And then again I clicked on EmptyDB option.

### How to reproduce

* First you need to download the app from fdroid and then install it. After that open the app.

* Click on the options present on the top left corner.

* After that click on the database management option.

* Then click on the EmptyDB option. 

* After that click on import data option( not imp).

* Click again on EmptyDB option.
Suddenly the app will crash.

https://youtu.be/bsi5FtinVTI 

* Browser: Gadgetbridge

* Version:0.26.5

* Operating system:7.1.2

* Device model: Redmi 4.

**Comment by danielegobbetti** [comment]
Thanks for the report, can you please send a log? See https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files
