### ISSUE TITLE
Add ability to mute individual apps

### ISSUE THREAD

**Issue by glitchphan** [Freeyourgadget/Gadgetbridge#111]
Some apps give notifications that you just don't need on your watch. I think the official Pebble app lets you "mute app" in the same menu on the watch where you can "dismiss" or "open on phone". Also there is a place in settings with which apps are muted and the ability to add one, etc.

**Comment by ashimokawa** [comment]
Actually this contains two feature requests.
We will implement blacklisting via settings first, since both Mi Band and Pebble would profit.

**Comment by danielegobbetti** [comment]
Wouldn't it make more sense at this point to whitelist the app one user wants?

**Comment by ashimokawa** [comment]
I am working on blacklisting right now.
For me this makes much more sense, but I can image that the opposite is true for the Mi Band.
Let's make the logic inversible later.

**Comment by cpfeiffer** [comment]
Whatever you choose, there's gonna be someone who needs it the other way round :-)

I'd not want to go through all apps and whitelist those that I'm interested in. Most of the apps in the list probably don't even have notifications, or at least I'd not know whether they have any.

So I for one would go with "Give me all notifications by default" and then have an "ignore notifications" option in Gadgetbridge, listing the previously received notifications and allowing me to selectively ignore those.

**Comment by ashimokawa** [comment]
@cpfeiffer 
Also a nice idea.
Anyway I will finish this the easy way for now. Even if going through the list is a bit painful, at least we should give people the ability to blacklist apps as soon as possible.

**Comment by ashimokawa** [comment]
I am closing this, since blacklisting apps in settings is now working in master.
@glitchphan 
For the pebble part, if you want it, open a pebble specific issue.
