### ISSUE TITLE
Transliteration appointment  problem

### ISSUE THREAD

**Issue by JackGruber** [Freeyourgadget/Gadgetbridge#1110]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
My appointments have hieroglyphics in the message, is this normal?

![watch](https://user-images.githubusercontent.com/24863925/40557218-b405b236-604f-11e8-9be2-9d588865c7cf.jpg)
![phone](https://user-images.githubusercontent.com/24863925/40557217-b3e84f34-604f-11e8-82e5-0e2893d4e7c9.png)

#### Your wearable device is:
Amazfit Bip
V0.1.1.41

#### Your android version is:
8.0.0 (OPWS27.2.2)

#### Your Gadgetbridge version is:
0.26.5

**Comment by JackGruber** [comment]
Logfiles
[logs.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/2040303/logs.zip)

**Comment by IzzySoft** [comment]
As language support for Amazfit has been improved since 0.26.5: does your problem still persist, @JackGruber – or can we close this issue as solved?

**Comment by JackGruber** [comment]
At the moment I can't test it anymore because I don't have Amazfit Bip anymore.

**Comment by IzzySoft** [comment]
OK, thanks Jack! Should it "re-surface", we can always reopen.
