### ISSUE TITLE
Polite request for a "Disabling Bluetooth" Feature Mi Band 2

### ISSUE THREAD

**Issue by lordofweed** [Freeyourgadget/Gadgetbridge#1112]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*
I (and many others http://en.miui.com/thread-383115-1-1.html) would love to have the feature to turn off bluetooth. It would reduce hf radiation andimprove battery life.

#### Your wearable device is:

Mi Band 2

#### Your Gadgetbridge version is:

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by IzzySoft** [comment]
I'm a bit puzzled: how should GB communicate with the device then? If you thought about something different an automation app like Tasker or MacroDroid would be better suited, or am I wrong?

**Comment by ashimokawa** [comment]
@lordofweed 

This project is:

> A free and cloudless replacement for your gadget vendors' closed source Android applications

The feature you requested would require quite big changes to the Mi Band 2 (firmware), which we do not change.

A new menu entry for "in-flight" mode would need to be added by Xiaomi/Huami plus the changes to actually allow to shut down the Bluetooth Radio. Even if this is possible (probably), this is now something we can do.
