### ISSUE TITLE
Mi Band 2 - Always on display [Feature Request]

### ISSUE THREAD

**Issue by daviddavidsoneq** [Freeyourgadget/Gadgetbridge#1118]
#### Your issue is:

Feature request, to have an option to always have the display be enabled (So that it can be continually showing the date/time). Obviously this will drain the battery at a significantly higher rate.

#### Your wearable device is:

Mi Band 2
FW: 1.0.1.81
HW: V0.16.2.2

#### Your android version is:

7.0 April 1 Security level

#### Your Gadgetbridge version is:

0.26.5

**Comment by danielegobbetti** [comment]
Is this option provided by the official app?

**Comment by krusic22** [comment]
If this somehow gets added please add support for other purposes too. For example displaying movement speed based on GPS...
