### ISSUE TITLE
Support for controlling other music players

### ISSUE THREAD

**Issue by harshad1** [Freeyourgadget/Gadgetbridge#112]
Would it be possible to extend gadget bridge to control other music players (such as spotify)?

**Comment by ashimokawa** [comment]
It might be possible, right now Gadgetbridge simulates pressing hardware media buttons like play, pause etc.

Does the official Pebble App support it?

**Comment by glitchphan** [comment]
I use XiiaLive, which has the option to be your main media player for use with hardware controls. This lets me start/stop from my Pebble with both Gadgetbridge and the official app. I thought Spotify had an option like that, but I just installed it and there isn't.. After a quick search, it might be a miss on Spotify's part: https://community.spotify.com/t5/Help-Android/Spotify-app-unregisters-media-button-receiver-after-a-while/td-p/471236

**Comment by harshad1** [comment]
The official pebble app + the default music app on the pebble supports Spotify just fine. I believe it works the same way... by simulating media buttons. I have a pair of BT headphones and they are ablet to control spotify too (play / pause, volume and next / previous track). 

The song and album readout works on pebble with the default app as well... I believe it uses avrcp.

**Comment by ashimokawa** [comment]
Reading spotifiy song and album metadata would be a one-liner.
But: Why is someone unsing spotify and Gadgetbridge. I mean, look at spotify's terms of usage. If you accept that, you can also accept Pebble Inc's TOS, right?

**Comment by harshad1** [comment]
@ashimokawa: I am running without the play store / services right now and spotify (unlike pebble) let's me download an official apk. 

Also, with spotify, I feel I can stop using it and switch to a different service with no lock - in. 

With the pebble app, since it's tied to hardware I own, I feel I am locked in unless I use something like gadgetbridge...

**Comment by harshad1** [comment]
Also, I was hoping a solution would be generic and not spotify-specific...

**Comment by ashimokawa** [comment]
I see... I might look into the issue at some point and see how others do it.

**Comment by harshad1** [comment]
Thank you. Let me know how I can help with this.

**Comment by ashimokawa** [comment]
@harshad1 
If you can build yourself,  please test current git with spotify.

**Comment by harshad1** [comment]
Haven't gotten a chance to try this yet. But thank you! 

You really do need to set up a donation system ... :)

**Comment by ashimokawa** [comment]
I completely changed how that works now. There is no auto detection anymore, because it did not work with most players (since we cannot get the source of an intent), but you can choose your preferred player from Preferences now, it worked with the players I tested.
