### ISSUE TITLE
Pebble Time Round: Application manager inaccuracy

### ISSUE THREAD

**Issue by Juesto** [Freeyourgadget/Gadgetbridge#1120]
#### issue is:
Unable to retrieve information about existing applications on the watch. the list acts like it was from factory. i hope that's understandable, i can expand further if required.
(i've used it with the official app before, currently i am unable to use such app again without a firmware update)

#### wearable device is:
Pebble Time Round (splading) with Firmware 3.14

####  android version is:
7.1.1
Moto E4 Plus

####  Gadgetbridge version is:
0.26.5

**Comment by IzzySoft** [comment]
I guess those apps you're missing have been installed with the "official app"?

**Comment by ashimokawa** [comment]
Quoting our wiki
"With FW 3.x Gadgetbridge cannot know anything about apps or watchfaces you've installed by other means (e.g. using the official Pebble app, or using another Android device), as this firmware offers no way to query that information: the official Pebble app manages that via the cloud."

**Comment by Juesto** [comment]
ah sorry!
