### ISSUE TITLE
Issues while obtaining Realtime step counts from Mi Band 2

### ISSUE THREAD

**Issue by ankushpatel18** [Freeyourgadget/Gadgetbridge#1121]
I am trying to fetch the realtime activities from Mi Band 2 and using Gadgetbridge.
Have obtained the heart rate successfully but having issues with fetching step counts. Here are the logs generated while obtaining step counts : 

**.service.devices.miband2.MiBand2Support: Unrecognized realtime steps value: 0x 0 0xb7 0x 1 0x 0 0x 0**

**Logcat** : 

06-12 11:12:15.299 21842-22156/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.GBApplication: getRtSteps: rtSteps = 0
06-12 11:12:15.300 21842-22156/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.activities.SanaDashboardActivity: running background process: RtSteps: 0 RtHeart: 58
06-12 11:12:15.303 21842-22058/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: 12 June, 11:12 AM: WriteAction on characteristic: 00002a39-0000-1000-8000-00805f9b34fb
06-12 11:12:15.304 21842-22058/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.actions.WriteAction: writing to characteristic: 00002a39-0000-1000-8000-00805f9b34fb: 0x15 0x 2 0x 0
06-12 11:12:15.356 21842-21842/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.activities.SanaDashboardActivity: heart gauge values: hr = 58
06-12 11:12:15.356 21842-21842/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.GBApplication: getRtSteps: rtSteps = 0
06-12 11:12:15.356 21842-21842/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.activities.SanaDashboardActivity: gauge values: steps = 0 targetSteps = 2000

Using Mi Band 2 with Android 6.0

**Versions** : 
FW : 1.0.081
HW : V0.9.3.4

**Comment by danielegobbetti** [comment]
``SanaDashboardActivity`` is not part of this project. If you want help on something you are adding to the project you should add a pointer to your repository.

**Comment by ankushpatel18** [comment]
The issue is in the **MiBand2Support**  class ,where 
the length of value should  be 13 but I am getting 5.

if (value.length == 13) {
 byte[] stepsValue = new byte[] {value[1], value[2]};
 int steps = BLETypeConversions.toUint16(stepsValue);
 if (LOG.isDebugEnabled()) {
 LOG.debug("realtime steps: " + steps);
 }
 getRealtimeSamplesSupport().setSteps(steps);
 } else {
 LOG.warn("Unrecognized realtime steps value: " + Logging.formatBytes(value));
 }

**Comment by danielegobbetti** [comment]
The *issue* you mention happens because your modification is expecting some data that is not used/handled in Gadgetbridge, I guess.
> If you want help on something you are adding to the project you should add a pointer to your repository.

Don't forget this is the issue tracker for Gadgetbridge issues. Since you are unwilling to help us help you I am closing this.
