### ISSUE TITLE
Not able to scan and reconnect after disconnecting Mi Band 2

### ISSUE THREAD

**Issue by ankushpatel18** [Freeyourgadget/Gadgetbridge#1122]
Once disconnecting the Mi Band 2 after a successful pairing.  I am not able to scan the device again.
Also.

Here is the **logcat** : 

06-12 11:55:07.205 28247-28247/com.sana.android I/com.sana.android.service.DeviceCommunicationService: Setting broadcast receivers to: true
06-12 11:55:12.659 28247-28247/com.sana.android I/com.sana.ui.discover.DiscoverBandActivity: Starting discovery: SCANNING_BT
06-12 11:55:12.662 28247-28247/com.sana.android I/com.sana.ui.discover.DiscoverBandActivity: Starting BT Discovery
06-12 11:55:12.768 28247-28247/com.sana.android I/com.sana.ui.discover.DiscoverBandActivity: Starting discovery: SCANNING_NEW_BTLE
06-12 11:55:12.771 28247-28247/com.sana.android I/com.sana.ui.discover.DiscoverBandActivity: Start New BTLE Discovery
06-12 11:55:12.772 28247-28247/com.sana.android D/BluetoothAdapter: STATE_ON
06-12 11:55:12.775 28247-28258/com.sana.android D/BluetoothLeScanner: onClientRegistered() - status=133 clientIf=0

Using Mi Band 2 with Android 6.0

Versions :
FW : 1.0.081
HW : V0.9.3.4

**Comment by danielegobbetti** [comment]
status 133 is a generic error code that comes from the underlying BT stack, there ist not much we can do unfortunately.
