### ISSUE TITLE
When using Signal as SMS client, I get duplicate notifications on my Pebble

### ISSUE THREAD

**Issue by yaomtc** [Freeyourgadget/Gadgetbridge#1125]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

When I get an SMS message, with Signal set as my SMS app, I get two notifications: one with the Signal icon, and another with the bottle-in-the-sea icon. I could disable SMS notifications, and still get Signal's notification, but that seems like a workaround. Does this happen with any other apps that handle SMS?

[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/2103519/gadgetbridge.log)

#### Your wearable device is:

Pebble 2 v4.3

#### Your android version is:

Android 8.1

#### Your Gadgetbridge version is:

0.26.5

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by danielegobbetti** [comment]
You have not searched the wiki.

**Comment by yaomtc** [comment]
I looked at the wiki. I looked through the Pebble section but didn't see anything relevant, and noticed the "SMS notifications are lost somewhere" link but didn't read it because the title is opposite to the problem I had. In hindsight I should have read it anyway.
