### ISSUE TITLE
This app requires pebble health to work

### ISSUE THREAD

**Issue by clach04** [Freeyourgadget/Gadgetbridge#1129]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### No Health information

* issues #188 indicates heath support is present but opening the builtin step counter shows the heath text (as does the builtin Kickstarter watchface)

This PTS was connected from a hard rest with GB (i.e. not used with the Pebble App and it sat in Recovery firmware  (as per https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Firmware-updates) - I was able to flash FW 4.3 (the latest)

I've not been able to get LE to work, I do NOT think this is relevant but I'd rather include as much information as possible.

I enterd in my information (height, etc.) in GB.

Sync Pebble health is enabled (and using Pebble Health activity tracker).

I've tried with and without "Force notification protocol", "Enable untested features", "always prefer BLE" (even though this is not used).

#### Your wearable device is:

Pebble Time Steel, FW 4.3

#### Your Gadgetbridge version is: 0.26.5

Installed from F-Droid.

**Comment by clach04** [comment]
I just used a different Android device with the official Pebble App on it and it popped up an "enable health" dialog, which I accepted and the PTS no longer shows the health error. I've reconnected to the device runing GB and now changes to health data yet after a 5 mins (step counts showing as zero, where as devices is showing 17)

**Comment by clach04** [comment]
this is currently a test device so I'm happy try things out for a few days (including resetting it)

**Comment by ashimokawa** [comment]
You have to activate health through Gadgebridge see:

https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-System-Apps

**Comment by clach04** [comment]
Confirmed, that was the problem here. Thanks for the quick response.

I went ahead and added an item to https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Getting-Started on this.
