### ISSUE TITLE
Calendar notification not showing up

### ISSUE THREAD

**Issue by clach04** [Freeyourgadget/Gadgetbridge#1130]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### No Calendar notifications

This PTS was connected from a hard rest with GB (i.e. not used with the Pebble App and it sat in Recovery firmware  (as per https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Firmware-updates) - I was able to flash FW 4.3 (the latest)

I've not been able to get LE to work, I do NOT think this is relevant but I'd rather include as much information as possible.

I've tried with and without "Force notification protocol", "Enable untested features", "always prefer BLE" (even though this is not used).

I've created calendar events with a 1 minute notification (also 5 and 20). The event shows up on timeline, the preview  QuickView is working and shows the event but no notifications show up.

I've configured notifications to show up always (even when screen is on). E.g. "Generic notification support:" is enabled as is "...also when screen is on" (which is not documented in https://github.com/Freeyourgadget/Gadgetbridge/wiki/Configuration ). I have no apps blacklisted and GB has notification access.

#### Your wearable device is:

Pebble Time Steel, FW 4.3 - same device as Issue #1129 

#### Your Gadgetbridge version is: 0.26.5

Installed from F-Droid.

**Comment by clach04** [comment]
this is currently a test device so I'm happy try things out for a few days (including resetting it)

**Comment by clach04** [comment]
I rebooted phone and pebble and calendar notifications are now working. Other than reboot I'm not sure what changed.

**Comment by danielegobbetti** [comment]
Calendar events will show up in the timeline even when disconnected. Events reminders are instead pushed from your android device and require an active connectio (Bluetooth).

**Comment by clach04** [comment]
@danielegobbetti I'm pretty sure BT was connected. GB showed it was connected, and the tests worked (e.g. find my device and the debug menu stuff). I also created the calendar entry on the phone and it showed up immediately on QuickView, and then a min later the alarm went off on the phone but not the pebble. The only thing different between then and now is a reboot occurred :(

**Comment by danielegobbetti** [comment]
I'm closing this. Feel free to reopen if it happens again. But please do attach logs otherwise there's little we can do.

**Comment by clach04** [comment]
I just realized the comment about notifications is incorrect for Pebble calendar entries:

> Events reminders are instead pushed from your android device and require an active connectio (Bluetooth).

This is not the case for calendar notifications, the pebble shows up reminders (with vibration and full screen notification) whether BT is on or not. Other notifications from other apps do need an active BT link.

Its not happened since, so no need to re-open.
