### ISSUE TITLE
Uncaught TypeError cannot read property 'toString' of null 

### ISSUE THREAD

**Issue by clach04** [Freeyourgadget/Gadgetbridge#1131]
#### Before opening an issue please confirm the following:
- [ ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Clay config errors

Attempting to configure two watchfaces that make use of Clay fails to configure (no web/config page comes up), issue #251 indicates this should work. Sample apps:
 * https://github.com/clach04/pebble_tz/releases/tag/v1.2
 * https://github.com/clach04/watchface_JupiterMass/releases/tag/0.7

Clicking "Open configuration website" (as per https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Watchfaces#how-do-i-manage-installed-watchfaces) results in:

    Uncaught TypeError cannot read property 'toString' of null at file://android_asset/app_config/js/gadgetbridge_boilerplate.js:138

Additionally, attempting to open configuration again results in:

    in case of "network error" after saving settings in the watchapp, copy the "network error" URL and paste it here:.

    Parse legacy app configuration.

If I toggle between watch faces configures (e.g. watch1, configure, watch2, configure) the "correct" configure screen rather than the error screen comes up.

This is currently a test device so I'm happy try things out for a few days (including resetting it)

#### Your wearable device is:

Pebble Time Steel, FW 4.3 - same device as Issue #1129 

#### Your Gadgetbridge version is: 0.26.5

Installed from F-Droid.

**Comment by danielegobbetti** [comment]
I have good news and bad news.

The good news is that configuring both your pebble apps works well for me.

I have some resemblance of unfixable issues on Lollipop. What I remember is related to CORS headers that cannot be overridden on API <=21... But it's been quite some time and I might remember wrongly.

Is it possible for you to build from master and try a few changes to some of our classes? I might provide some ready-to-test patches if you feel like doing some tests.

Thanks!

**Comment by IzzySoft** [comment]
I second @danielegobbetti here. Vaguely remember I had some such issues back when I was on LP.

**Comment by clach04** [comment]
@danielegobbetti this is turning into issue #1130 - tested again today (after reboot) and its working fine! I did wonder if it was related to the system webview but I did NOT update that.

I'm thinking we close this down, if anyone else sees this again at least they can find it in the issue tracker.
