### ISSUE TITLE
Illiterate russian translation

### ISSUE THREAD

**Issue by K0L0B0G** [Freeyourgadget/Gadgetbridge#1132]
0.26.2
Wrong:    "Готов к передачи данных"
Correctly: "Готов к передаче данных"

**Comment by ashimokawa** [comment]
Thanks!
We manage translations here:
https://hosted.weblate.org/projects/freeyourgadget/gadgetbridge/

If you don't mind please correct there, changes will automatically arrive in Gadgetbridge.

And Version 0.26.2 is outdatet, we are at 0.26.5. Any reason you use an old version?

**Comment by K0L0B0G** [comment]
Fixed.
Reason? Laziness.
