### ISSUE TITLE
Mi Band 2 doesn't connect

### ISSUE THREAD

**Issue by lucav31** [Freeyourgadget/Gadgetbridge#1133]
I just love your App. Big, big thanks for creating, I wanted an open source client for the Mi Band 2 and was so happy when I discovered Gadgetbridge.

But unfortunately, it won't connect at all. It works with the official Mi Fit app, but with Gadgetbridge it just doesn't connect. I tried uninstalling Mi Fit, no success. When I pair it again, it loads eternally at the point right after the search.
I really hope you can help me, just tell me if this isn't enough information and I'll say you anything I can.

**Comment by ashimokawa** [comment]
@lucav31 
Did you unpair the Mi Band 2 from the Android Bluetooth settings?
After that please toggle Bluetooth off and on. Then press the + Button in Gadgetbridge and tap to pair. It should connect.

**Comment by lucav31** [comment]
@ashimokawa Yes I've already tried this, but it didn't work either. Today I also tried it with other smartphones, same problem. So do you think the Mi Band is the problem? Because it works with the official app I don't think so, but I've never heard of this problem and maybe it isn't a bug in Gadgetbridge.
Thanks for replying so fast, I really appreciate your help. Another proof that Open Source community is the best :fist:

**Comment by danielegobbetti** [comment]
@lucav31 I have read somewhere that the official app has something like "make band discoverable" in the settings, perhaps you should try that.

**Comment by lucav31** [comment]
@danielegobbetti Already tried that too, didn't help. At the time I haven't installed the official app anyways.
But thank you.

**Comment by danielegobbetti** [comment]
Unpair the device from the android settings, reboot the phone and make sure you granted location access to Gadgetbridge. If you have privacy guard disable it for Gadgetbridge. Press the + button in Gadgetbridge (don't pair through android) and see if the band is detected.  Tell us what happens

**Comment by lucav31** [comment]
The Miband 2 appears, I click on it and the app opens the specific options for the Mi band 2 (Name/Alias, left or right arm and so on) , I enter my data and tap on the top left corner "go back" button. The app tries to connect, but after a really long time (15 min) still nothing happens. I hope everything is clear as I'm not a native speaker.

**Comment by danielegobbetti** [comment]
Please go to Gadgetbridge settings and fill the user info (main settings screen) and then also the miband settings. Then do the whole process again (forget the miband, toggle Bluetooth and add it again). The miband should vibrate when you select it in the "add device" screen, and you should tap it to confirm the pairing with Gadgetbridge.  Does this happen?

**Comment by lucav31** [comment]
Just to make it clear what I wanted to say, here is a screenshot of the eternal loading screen I'm stuck in. Changed the language settings but the title is still in German, I hope this is ok. 
![img-20180630-wa0000](https://user-images.githubusercontent.com/34192640/42123758-b19df822-7c57-11e8-8cb0-de52598df80b.jpg)

**Comment by lucav31** [comment]
No, this happend when I tried it with the official app, but not with Gadgetbridge. Nothing happens at all.

**Comment by lucav31** [comment]
OMG I feel so dumb now. I just scrolled trough the settings again and found the "Enable bluetooth pairing setting" with the description "Deacvtivate this if you have trouble connecting". Tried it out, worked. Thank you so much for spending your time trying to help me! I am sorry for wasting your time with such a stupid mistake.

**Comment by danielegobbetti** [comment]
Glad you solved your issue

**Comment by lucav31** [comment]
I have the exact same problem again... It worked once and now it doesn't connect again  :(  
Should I open a new issue or not? I changed the Enable bluetooth pairing setting and it worked, but after 3 or 4 times where it worked it didn't connect. Is it maybe just a hardware problem with the MiBand 2?

**Comment by UmutAlihan** [comment]
same issue here @lucav31

**Comment by ebaschiera** [comment]
Same issue here on a Pixel 2 XL, android 10. @lucav31 would you mind reopening the issue please?
