### ISSUE TITLE
Adding Russian support for Amazfit Bip firmware 1.0.1.0.0

### ISSUE THREAD

**Issue by Di1r1** [Freeyourgadget/Gadgetbridge#1145]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

Good day!

There is a problem with connecting via Gadgetbridge, the language Amazfit Bip switches to Spanish, in the firmware 1.0.1.0.0 added officially Russian, you can add an add-on in the menu for Amazfit Bip Russian language?

#### Your wearable device is:

Amazfit Bip   firmware version 1.0.1.0.0

#### Your android version is:
8.0 
#### Your Gadgetbridge version is:
0.27.1

**Comment by ashimokawa** [comment]
@Di1r1 
Oh, I tried to use russian language in the latest fw and it did not work for me. Strange.
Also did you flash the latin firmware or the normal one? (there are two firemwares now)

**Comment by Di1r1** [comment]
@ashimokawa 
Normal, updated via MiFit)

**Comment by danielegobbetti** [comment]
I can confirm russian language works in firmware 1.1.1.00 **latin** version. With this firmware only spanish and russian works, though.
