### ISSUE TITLE
Store/convert date/time to UTC/ISO 8601 in GPX file according to standard

### ISSUE THREAD

**Issue by holgis** [Freeyourgadget/Gadgetbridge#1152]
Amazfit BIP FW: 1.0.2.00, Android 8.0.0, GadgetBridge 0.27.0

The GPX files (activities synced from Amazfit BIP) use a date/time format like this:
`<time>2018-06-30T07:44:13+02:00</time>`
But GPX format just supports date/time in UTC (in ISO 8601), like this:
`<time>2018-06-30T05:44:13Z</time>`
So no offset like "+02:00" and a trailing "Z" - see http://www.topografix.com/gpx.asp for details on standard.

Because of this date/time format, 3rd party software (e.a. OsmAnd) won't display any time or duration.

**Comment by ashimokawa** [comment]
Thanks!
@cpfeiffer are you able do do/test this?

**Comment by danielegobbetti** [comment]
It seems to work correctly for me with the current codebase, see for instance: 
![image](https://user-images.githubusercontent.com/352756/43035986-8e1ced20-8cf8-11e8-9f26-b158aea51bb8.png), which is a visualization by gpxpod inside nextcloud.

How can you toggle the visibility of time/duration within Osmand~? I can do the change in the export functionality but I don't know how to test if something change in Osmand.

BTW the gpx schema 1.1 uses a normal ``dateTime`` xsd type for the ``time`` element, hence it **should** work (and validates) also with the timezone, which explains probably why gpxpod shows the details correctly.

**Comment by TaaviE** [comment]
This sounds like something that should be reported to Osmand's developers. `2004-04-12T13:20:00-05:00` seems to be totally valid value for `xsd:dateTime`.

**Comment by danielegobbetti** [comment]
I made the change locally and see no changes in what osmand~ and gpxpod show. Waiting for instructions on how to display the missing information in Osmand~ to check if something actually improved.

**Comment by holgis** [comment]
From http://www.topografix.com/GPX/1/1/gpx.xsd:

`<xsd:element name="time" type="xsd:dateTime" minOccurs="0">
<xsd:annotation>
<xsd:documentation>Creation/modification timestamp for element. Date and time in are in Univeral Coordinated Time (UTC), not local time! Conforms to ISO 8601 specification for date/time representation. Fractional seconds are allowed for millisecond timing in tracklogs</xsd:documentation>
</xsd:annotation>
</xsd:element>`

So I do not think this is an issue for OsmAnd but for Gadgetbridge.

If I do open an original file from 'Android/data/nodomain.freeyourgadget.gadgetbridge/files', i.e.
[gadgetbridge-track-2018-07-12T14-55-46-02-00.gpx](https://github.com/Freeyourgadget/Gadgetbridge/files/2216813/gadgetbridge-track-2018-07-12T14-55-46-02-00.gpx.txt)
OsmAnd displays like this (Time span 0:00, no speed): 

![screenshot_20180722-095753_osmand](https://user-images.githubusercontent.com/1913162/43043604-7fef9ee2-8d97-11e8-9f34-372891d135d6.jpg)

but if I modify the gpx file to UTC time only:
[gadgetbridge-track-2018-07-12T12-55-46Z.gpx](https://github.com/Freeyourgadget/Gadgetbridge/files/2216815/gadgetbridge-track-2018-07-12T12-55-46Z.gpx.txt)
OsmAnd displays with time span and speed:

![screenshot_20180722-100136_osmand](https://user-images.githubusercontent.com/1913162/43043626-011af46c-8d98-11e8-8971-2718b48fcb14.jpg)

My OsmAnd version is 3.0.4 from FDroid

**Comment by holgis** [comment]
> Waiting for instructions on how to display the missing information in Osmand~ to check if something actually improved.

In "Tracks" overview click on the draw sign in front of the track (red arrow)

![screenshot_20180722-102853_osmand](https://user-images.githubusercontent.com/1913162/43043775-6992171c-8d9a-11e8-912b-ff168d1962a1.jpg)

**Comment by danielegobbetti** [comment]
Please bear with me but I cannot get to the screen you posted. If I tap a workout in Gadgetbridge the track is displayed on the map and that's it. If I start a navigation I get asked if I want to follow the gpx and if I say yes I get the path with elevation etc. Perhaps I am missing some plugin?

**Comment by holgis** [comment]
OK, here is a step by step description on how to display it in OsmAnd~:
Open a file manager, go to `Android/data/nodomain.freeyourgadget.gadgetbridge/files` and copy a .gpx file to a sdcard (or internal memory) "root" folder. Due to  #1169 you might need to rename the file and replace `:` characters with `_`.
Open OsmAnd~, open "Dashboard", scroll to "Tracks" and open Link "SHOW ALL". "My Places" screen will open and tab "TRACKS" should be displayed. On the very bottom left hand side there is a `+`. Click on it to import your .gpx file. Navigate to location where you copied the .gpx file and select it.
If it was imported successfully, in OsmAnd~, "MyPlaces" tab "TRACKS" open folder "Import" and click on the draw sign in front of it.
Another way would be to select the renamed file from file manager and select to open it in OsmAnd~. If it was imported successfully, navigate to "Tracks" and select the draw sign.

**Comment by holgis** [comment]
You might need to enabled plug-in "Trip recording" in order to get "TRACKS" displayed in Dashboard.

**Comment by holgis** [comment]
:+1: Thanks a lot :smile:
