### ISSUE TITLE
Steps in GB deviate to steps on watch (Amazfit Bip)

### ISSUE THREAD

**Issue by dazzzl** [Freeyourgadget/Gadgetbridge#1154]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*

The steps in GB deviate to the step counter on the watch. The problem occurs, if the watch create for each second a new DB entry (Why and when is the watch doing this?) Usually the step values are -1 but here, we have a high number which is the cause of the deviation.... 

1531406400|1|1|6|0|112|255
1531406460|1|1|18|0|112|63
1531406500|1|1|-1|-1|1|-1
1531406501|1|1|-1|-1|1|-1
1531406502|1|1|-1|2941|1|-1
1531406503|1|1|-1|-1|1|-1
1531406504|1|1|-1|-1|1|-1
1531406505|1|1|-1|-1|1|-1
1531406506|1|1|-1|-1|1|-1
1531406507|1|1|-1|-1|1|-1
1531406508|1|1|-1|-1|1|-1

#### Your wearable device is:

*Please specify model and firmware version if possible*
Amazfit Bip
FW: 1.0.1.00
HW: V0.11.2.4

#### Your android version is:

LOS 14.1

#### Your Gadgetbridge version is:
0.27.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by dazzzl** [comment]
I think these DB entries do not make any sense. I deleted it with 
`delete from MI_BAND_ACTIVITY_SAMPLE where RAW_INTENSITY = -1;`

The step counts look now fine.. But where come these entries from? From the watch or from Gadgetbridge?

**Comment by kpiorno** [comment]
Any chance to get the accelerometer data?

**Comment by dazzzl** [comment]
What do you mean with "accelerometer data"? 

This bug is very annoying and the I think it comes from some communication issues. I have to correct the database at least one time per week. Is there any progress on this issue?

**Comment by jd1123** [comment]
I have a similar issue with the Amazfit BIP. I do not have access to the database data, but the number of steps on GB deviates from the number of steps on the watch. GB seems to be reporting more steps than the device itself. I do not know how to recreate this issue.

**Comment by dazzzl** [comment]
@jd1123 You can export the database with GB and access it with sqlite3

**Comment by cpfeiffer** [comment]
There are some potential fixes for this in current master. I also experienced *more* steps (not fewer) in Gadgetbridge than on the watch, when using the Live Activity.

**Comment by cpfeiffer** [comment]
I don't have any deviation anymore, please leave a comment if it still hapens for you.
