### ISSUE TITLE
Using vendor-code as a library

### ISSUE THREAD

**Issue by dakhnod** [Freeyourgadget/Gadgetbridge#1157]
So, i am developing a Fossil Q interface, and since the source protocoll is complicated and the code is obfuscated, my current solution is to dex2jar the dexes from the original FossilQ.apk and use them as a jar dependency.

Now, is that legally ok? Or should i think about another solution?

**Comment by TaaviE** [comment]
That isn't okay for F-Droid.

**Comment by dakhnod** [comment]
So, what would be an acceptable solution?
May i prompt the user to download the .jar additionally in order to use my module, so that it isn't directly included in the .apk?

**Comment by TaaviE** [comment]
@dakhnod Gadgetbridge does not have internet connection permission.

The acceptable solution would be implementing everything needed from scratch without looking at the original source code (black box analysis). This is legally the only safe option (though, IANAL).

**Comment by danielegobbetti** [comment]
Closing this. As @TaaviE said this is the only way that is legally **right** (while not 100% safe as it might still be subject to litigations) (I am, too, not a lawyer and this is not legal advice)

**Comment by dakhnod** [comment]
I am reopening this due to another approach.

What if i never embed any vendor-code in my application, just ask the user to install another application and then extract the needed dex from the official apk?
