### ISSUE TITLE
Amazfit Cor. Encoding is broken on second page of Notifications option on Russian localization. V1.2.1.02

### ISSUE THREAD

**Issue by davudmurtazin** [Freeyourgadget/Gadgetbridge#1158]
User reported.

Device version: V1.2.1.02
Phone version: iOS 11.4

![1 notifications](https://user-images.githubusercontent.com/22474722/42764438-25a0cc5e-8905-11e8-911e-927d6b598132.jpg)
![2 first page](https://user-images.githubusercontent.com/22474722/42764440-25c5bf3c-8905-11e8-86ba-5b383519c5cb.jpg)
![3 second page](https://user-images.githubusercontent.com/22474722/42764441-25e919fa-8905-11e8-9da1-2803dd96219b.jpg)

**Comment by ashimokawa** [comment]
@davudmurtazin 
You are reporting a firmware bug, we are not the developer of the firmware on the device itself. We are developing Gadgetbridge, an alternative App for Android, while you are using iOS.
