### ISSUE TITLE
How to read Calories and Distance count ?

### ISSUE THREAD

**Issue by Jay268** [Freeyourgadget/Gadgetbridge#1159]
Hello,

We are trying to get Calories & Distance value from UUID ` public static final UUID UUID_CHARACTERISTIC_3_CONFIGURATION = UUID.fromString("00000003-0000-3512-2118-0009af100700");`. 

We are able to get `byte[]` value in response from `onCharactristicChanged` method.

We are trying to perform this for **Mi Band 2** specifically.

But we are unable to convert that `byte[]` value and we coundn't able to get Calories count.

So the question is how we can convert that `byte[]` value to read Calories count ?

**Comment by danielegobbetti** [comment]
Please add this info in our wiki when you find out!
