### ISSUE TITLE
Add workout type to the filename of GPX exports

### ISSUE THREAD

**Issue by gajovy** [Freeyourgadget/Gadgetbridge#1161]
#### Custom name for GPX exports.
I'd like to request the ability to name GPX exports other thatn current *gadgetbridge-track- followed by the date/time*. It would be nice to be able to use some meta characters for things like date and time, but also to include the **type** of activity in the name. This could be useful with services like **tapiriik** but also for those who do several different activities and only upload them once in the night (currently one needs to know when did the bike ride or run occur to tell the difference).

#### Your wearable device is:
Amazfit BIP

#### Your android version is:
Android 8.0 Oreo

#### Your Gadgetbridge version is:
0.27.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by danielegobbetti** [comment]
This issue would be a good candidate for a first-time contribution.
