### ISSUE TITLE
Menu and messages are displayed in Spanish in Amazfit Bip

### ISSUE THREAD

**Issue by makkarpov** [Freeyourgadget/Gadgetbridge#1163]
**Steps to reproduce:**

1. Pair Amazfit Bip with Gadgetbridge (system locale is Russian)
2. Look at the menu

**Expected behaviour**

Messages should be at least in English.

**Actual behaviour**

You will see messages like "Estado", "Actividad", "Tiempo" and so on.

**Versions**

* Android 7.1
* Gadgetbridge v0.27
* Amazfit Bip FW v1.0.1.00 HW v0.11.2.4

**Comment by makkarpov** [comment]
No, it's a bug. Probably it should be English or Russian, but it's Spanish. Closing the GitHub issue does not magically remove Spanish language from the watch.

There is no such setting in the menu of Amazfit itself. I had tried to set app Amazfit setting to English and there are no changes. Official Mi Fit app correctly switches the firmware to Russian. Any pairing with Gag

**Comment by ashimokawa** [comment]
I meant the setting in Gadgetbridge not on the watch.

And I closed the band issue because I tagged Gadgetbridge 0.28.0 which has added Russian to the menu.

**Comment by makkarpov** [comment]
Ok. Anyway, the issue persist — I can't even switch it to English. Steps that I had done:

1. Reboot the watch, so it stays with a screen like "Connect to the phone" (icons of watch and phone, and arrows in between)
2. Ensure that "Settings -> Amazfit Bip -> Language" setting is set to "English"
3. Pair the watch and the phone
4. It's Spanish.

But if you reboot the watch again and pair it with Mi Fit, it's Russian.

**Comment by ashimokawa** [comment]
Interesting, can anyone confirm? Should affect anyone on that firmware.

**Comment by Di1r1** [comment]
checked, with version 0.28.0 Russian is displayed, thanks

**Comment by Di1r1** [comment]
@makkarpov поздновато вы подсуетились [https://github.com/Freeyourgadget/Gadgetbridge/issues/1145](url)
Поддержу добавили в 28

**Comment by makkarpov** [comment]
@Di1r1, тикет не читай @ сразу отвечай? Проблема в том, что на часах отображается испанский язык, несмотря на то, что в настройках английский.

For now Google Play does not offer me to update to 0.28.0, and in Releases there are no APK's for it. If you want — I can record video with this bug on version 0.27.0

**Comment by Di1r1** [comment]
@makkarpov  попробуйте 28 http://4pda.ru/forum/index.php?showtopic=845160&st=2140#entry67734885

**Comment by makkarpov** [comment]
It works with 0.28.0, thanks.

**Comment by ashimokawa** [comment]
The play store version is unofficial, we do not support it.

**Comment by ashimokawa** [comment]
Direct link to 0.28.0 (f-droid index not updated yet)

https://f-droid.org/repo/nodomain.freeyourgadget.gadgetbridge_134.apk

**Comment by gthieleb** [comment]
I can confirm this issue still exist. 
after pairing with gadgetbridge the language changes from german to spanish. 

It changes back to german using Amazfit Notify (language selected in preferences). 


![Screenshot_20190807-182202](https://user-images.githubusercontent.com/21332468/62639681-5238a400-b940-11e9-8dfa-50c1212aa6a8.png)

![DSC_0005](https://user-images.githubusercontent.com/21332468/62640095-1c47ef80-b941-11e9-9715-b2aab7055da6.JPG)

**Comment by gthieleb** [comment]
when explicitly set the language to german it seems to
be changed and hopefully persisted on amazfit.
![Screenshot_20190807-190625](https://user-images.githubusercontent.com/21332468/62642916-089f8780-b947-11e9-8368-06d9388034e1.png)

It is a missing Feature that this is not by default detected by OS language.

**Comment by crbble** [comment]
Due to this being the top hit for the spanish lanugage problem on the Bip: The latest version of the Xiaomi Health App (3.6) that included firmware files for the BIP (version 1.1.5.16) apparently has a serious firmware bug, that disables language selection via Gadgetbridge. Resetting does not help here. Installation of a newer firmware like 1.1.5.36 and up enables language selection again.
