### ISSUE TITLE
onNotification sourceAppId null

### ISSUE THREAD

**Issue by dakhnod** [Freeyourgadget/Gadgetbridge#1166]
in the AbstractBTLEDeviceSupport.onNotification() callback the sourceAppId field of the notificationSpec parameter is null, although it should be the appId of the app posting the notification.

**Comment by dakhnod** [comment]
Anything anyone can tell me?

**Comment by ashimokawa** [comment]
@dakhnod 
It should contain the source package id IF the notification came through the generic notification listener. If it came through the sms listener or pebblekit, there wont be the package id.

**Comment by danielegobbetti** [comment]
Please post logs and/or describe in more details what problem you are facing.

**Comment by dakhnod** [comment]
My implemention extends the AbstractBTLEDeviceSupport class nd Overrides the onNotification() method, which is called whenever a notification is posted.
The first parameter is a notificationSpec  object with some meta data about the posted notification.
One of the fields of this object is called sourceAppId and should contain the package name of the application which posted the Notification.
But in my case this field is null, which seems quite strange to me.

**Comment by danielegobbetti** [comment]
We can't help understanding what is wrong in code outside of the project's codebase. This issue tracker is about the Gadgetbridge project.

**Comment by dakhnod** [comment]
There is no reason to close this ticket, since the bug appears in Gadgetbrige code, not mine.

**Comment by ashimokawa** [comment]
@dakhnod 
If you say so. I will keep this open then and if I feel like it I will see if I can reproduce it.

**Comment by dakhnod** [comment]
To repeat what i have yet found:

as seen here, the sourceAppId field of the notificationSpec is not set, thus making it impossible to determine the application which posted the notification in the onNotification callback.

**Comment by danielegobbetti** [comment]
To repeat what @ashimokawa already wrote [above](https://github.com/Freeyourgadget/Gadgetbridge/issues/1166#issuecomment-406799032):
> It should contain the source package id IF the notification came through the generic notification listener. If it came through the sms listener or pebblekit, there wont be the package id.

Since it is so important for you to have this open it may remain so, I'll add the notabug label.

**Comment by dakhnod** [comment]
To shortly comment on what @ashimokawa wrote:
I am pretty sure it came through the generic notification listener, yet it does not have the field set.

**Comment by danielegobbetti** [comment]
Then please post logs, as asked many times already.

**Comment by dakhnod** [comment]
Here is the log upon the Notification post event:

```
07-22 22:39:06.246 14278-14278/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener: Processing notification -1011378471 from source org.telegram.messenger with flags: 529
07-22 22:39:06.247 14278-14278/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener: Not forwarding notification, FLAG_GROUP_SUMMARY is set and no wearable action present. Notification flags: 529
07-22 22:39:06.266 14278-14278/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener: Processing notification -1011378445 from source org.telegram.messenger with flags: 16
07-22 22:39:06.267 14278-14278/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener: found wearable action: Server 1 antworten  null
07-22 22:39:06.275 14278-14278/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
07-22 22:39:06.275 14278-14278/nodomain.freeyourgadget.gadgetbridge D/Service: notif from null
```

and here is the stacktrace:

```
07-22 22:39:06.275 14278-14278/nodomain.freeyourgadget.gadgetbridge W/System.err: java.lang.Exception
        at nodomain.freeyourgadget.gadgetbridge.service.devices.qhybrid.QHybridSupport.onNotification(QHybridSupport.java:175)
        at nodomain.freeyourgadget.gadgetbridge.service.ServiceDeviceSupport.onNotification(ServiceDeviceSupport.java:152)
        at nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService.onStartCommand(DeviceCommunicationService.java:374)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3351)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

The code can be found [here](https://github.com/dakhnod/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/qhybrid/QHybridSupport.java#L174)

**Comment by TaaviE** [comment]
@dakhnod What XPosed modules are you using and does the issue occur when you uninstall XPosed framework?

**Comment by dakhnod** [comment]
Neither of the modules i am using should affect Gadgetbridge or the state Notifications are beeing delivered to it.

As mentioned above, the issue lays in [here](https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java#L340-L350), where the sourceAppId-Field is not being set for some reason.

**Comment by dakhnod** [comment]
I managed to create a [pull request](https://github.com/Freeyourgadget/Gadgetbridge/pull/1171) to fix that problem, please be so kind to tell me what i could have done better since its my first pull request.

**Comment by danielegobbetti** [comment]
By looking at the code, I now understand what you are trying to do, and I have a question: 
If I understand your code correctly, you want to let the user configure each app (by package name / sourceAppId) notifications. What I am wondering is if you could instead use the [AppNotificationType](https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java) which is already part of the bundle and it's what is used by other devices to decide how to handle notifications.

Many thanks for the PR. I now understand your point of view that a field which is part of the notificationSpec but is not serialized in the bundle might be considered a bug, but it [really isn't](https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java#L224]. It could be considered an enhanchement, but I believe it's important to identify which strategy is best to maintain cross-gadget compatibility (in the eye of the end user): either use the ``type`` or use the ``sourceAppId`` consistently, and therefore I would like to hear from you if (why) you deem the ``type`` to be not enough for your use case.

**Comment by dakhnod** [comment]
If i got that right, there basically is a NotificationType for most common communication apps.
IMO there is no need for such a wrapper which basically only wraps the packageName.

Plus, in my implementation the user is able to define custom reactions to different packages, and i dont want to have to tell the user "sorry, this package is not supported", just because it is not listed in the AppNotificationType class.


![screenshot_20180723-192053](https://user-images.githubusercontent.com/26143255/43092491-a9a21cd0-8ead-11e8-825b-b9b228ac9a75.png)

Please enlighten me if there is any use to AppNotificationType other than to wrap the packageName.

**Comment by danielegobbetti** [comment]
I believe I might have explained myself poorly, so I'll try again:
Every other device (to date) classifies the gadget behavior (e.g. number of vibrations) by the means of the notification type. In your screenshot I see that whatsapp points up whereas telegram points right. You could let the user customize the arrows direction using the notification type (chat to the right, email to the bottom, calendar to the top, ...) **instead of** using the package ids. If you search for accessor to ``type`` you will find the use I am talking about.

Since using the ``package id`` would be an inconsistency with all other devices (that are using the ``type`` - please note that I am not judging, just stating the facts) I would like understand if you decided to use the package names for any particular reason, and it's up to you to enlighten us with a good enough one :-) .

**Comment by dakhnod** [comment]
firstly, i am trying to create an experience as close as possible to the original Fossil App.
And that fossil App lets you assign a  package, not a general type.

Secondly, i think that it is false to see all different notifications with the same notification type as equal.
I, for instance, use WhatsApp and Gmail for general messaging, while Telegram delivers Notifications from my server or my IOT network.
In that scenario i need to be able do differentiate between different notifications that would normally have the same type.

Now you could argue that i can read out the App from the NotificationType object, but then it would be quite more elegant, resource-saving and fast to simply forward the sourceAppId.

IMO the user should have the possibility to customize as much as possible, and only giving him the oppurtinity to assign a whole group of packages or limiting the list of supported apps really restricts that possibility.

P.S.: i do not see a need to only implement one of the discussed mdoels.
Why can't we simply add my idea? The developers would then be left with the choise how they want to differentiate notifications.

**Comment by dakhnod** [comment]
actually, i have rethought my argumentation.

FIrstly, I am trying to make my experience different from the official Fossil app, because it tries to limit the user in many ways.
And forcing the user to use only a selection of apps, or even better, differentiating between one of several NotificationTypes, is a limitation i am trying to avoid.

Secondly, if a user made the choice to switch Gadgetbridge instead of using the official app, if he has the know-how and motivation to install and use F-Droid, he deserves the chance to customize as much as possible IMO.

But, seeing that you have your own point of view, i am willing to offer a compromise.
When the user has to chose a package for a notification, he is at first confronted with all those notification types.
Thus, if this is enough for the user, he can simply one or more of those types, which, under the hood, includes all packages with that type.

But, if someone really wants to have per-package-settings, he can expand every of those types, getting a list of all packages with that type, giving him the oppurtunity to cherry-pick single packages.

**Comment by cpfeiffer** [comment]
Sounds great to me! Would be perfect to have that as a general control, so that it can be used in all kinds of situations where the user can make such a choice (not only specific to the Fossil Q watches).

**Comment by cpfeiffer** [comment]
I think this issue an be closed, since we now make sure the sourceAppId field is set. For the rest, we can open a new issue when it's time.
