### ISSUE TITLE
Notificaion sourceAppId not set in onNotification

### ISSUE THREAD

**Issue by dakhnod** [Freeyourgadget/Gadgetbridge#1168]
as seen [here](https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java#L340-L350), the sourceAppId field of the notificationSpec is not set, thus making it impossible to determine the application which posted the notification in the onNotification [callback](https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java#L374).

I am reopening this issue since it was closing under the false assumption the bug was in my own code.

**Comment by ashimokawa** [comment]
You did not reopen the issue you created a new one. You deleted the issue template. You did not provide logs. Closed.

**Comment by dakhnod** [comment]
Sorry for that, i am not not that experienced in github yet.
