### ISSUE TITLE
Avoid colon characters in file names of activities

### ISSUE THREAD

**Issue by holgis** [Freeyourgadget/Gadgetbridge#1169]
Amazfit BIP FW: 1.0.2.00, Android 8.0.0, GadgetBridge 0.27.0
While some Apps are able to deal with file names including `:` (colons), some do not. e.a. ES File Explorer 4.1.8.1 and OsmAnd 3.0.4. So maybe it is possible to replace the colon with another character like `_`

**Comment by danielegobbetti** [comment]
I don't have issues with the colon in filename (in osmand, I don't use ES file explorer), but perhaps files saved to fat32 formatted sdcards might not contain this character.

Could it be your problems with osmand come from the usage of the external SD?

**Comment by holgis** [comment]
Yes, OsmAnd stores on external SDcard, but with ES File Manager I do have the same issues saving on Internal memory.

**Comment by OvOwl** [comment]
+1
Would also be useful in mixed environments with Windows as Windows doesn't allow colons in filenames.
I'd suggest just dropping it like
"gb-track-20180730T191629+0200.gpx" 
(yes and also shorten the filename a little bit).

**Comment by cpfeiffer** [comment]
Thanks, this was a bug in our accepted filenames regex.
