### ISSUE TITLE
DeviceService and Activity communication

### ISSUE THREAD

**Issue by dakhnod** [Freeyourgadget/Gadgetbridge#1170]
As far as i understood the whole model, in the package nodomain.freeyourgadget.gadgetbridge.service.devices.yourdevice there must be a Class that extends for instance AbstractBTLEDeviceSupport, lets call it "QHybridSupport".

This class is somehow bound to a service, which is responsible for handling device events and delivering Queued write calls.

Now, in my Settings activity i have to somehow make a connection to that service.
Since QHybridSupport is not a child of Service, i can not provide a binder.

So, besides of static fields, os there any chance to connect to that DeviceService from an activity?

**Comment by danielegobbetti** [comment]
This is the issue tracker of Gadgetbridge project.

We can help you (as anybody else) who is helping the development of Gadgetbridge. You are free to use the projects code under the license terms but please stop asking questions without referring to your actual code, be it a pull request or some other way to contribute. 

You have the source code at your disposal, and the wiki has pages that explain how the code is structured and how to add a new device.
