### ISSUE TITLE
Mi Band 3 indicates heart rate "3" a lot of the time

### ISSUE THREAD

**Issue by LuccoJ** [Freeyourgadget/Gadgetbridge#1173]
![screenshot_20180726-001541](https://user-images.githubusercontent.com/1684791/43230739-c83eaede-9069-11e8-9ebe-a0ecd07b067b.png)

#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

I know it's only preliminary support, but can't hurt to drop the issue I guess since it's the first I find with this device. The firmware is 1.2.0.8, hardware version 0.18.3.4, and Gadgetbridge is 0.28.1.

Setting a periodic heart rate reading (I tried every minute and every 5) results in many or most of the reading being "3", while the others are plausible (and fairly accurate compared to my Bip, too, I suppose).

I think that maybe "3" is just an error code indicating it failed to take that particular reading reliably, but I'm obviously guessing.

**Comment by Dikay900** [comment]
I can confirm this, seeing this as well with Mi Band 3.
HW: V0.18.3.2
FW: 1.3.0.4

**Comment by SpaceAgeHero** [comment]
Can confirm this as well. Thought this was normal though due to non continuous measurement ...

**Comment by LuccoJ** [comment]
@SpaceAgeHero I don't think it can be called "normal" in any case, because it makes the graph pretty much unreadable when zoomed out a bit more than my (very zoomed-in) screenshot.

But if you look at the pattern, there _are_ several continguous measurements (that is, taken at one-minute distances from each other), and there is no apparent pattern to the readings that are "3", so that's why I thought it simply indicates a failure to read.

If I remember correctly, I think this is similar what happens on my Amazfit Bip, too, but only if I use the "Live Activity" view, although in that case, the readings are "0", not "3": in that case, too, I always assumed that the watch tries to read the heartrate continuously, but when it fails, it just returns "0".

![Behavior on the Bip's Live Activity screen](https://user-images.githubusercontent.com/1684791/43266102-c8c4b9b2-90ea-11e8-9400-49105b246489.png)


It makes some sense perhaps that the Mi Band 3 always operates in a mode more similar to the Bip's live activity mode, since it doesn't have an explicit activity selection on its internal menu.
