### ISSUE TITLE
Request: Support of ZeTime configuration

### ISSUE THREAD

**Issue by myxor** [Freeyourgadget/Gadgetbridge#1185]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I own a MyKronoz Zetime and it's working fine with Gadgetbridge.
Additionally i would like to see support for (some) configurations regarding this device.
I am not experienced in BLE or reverse-engeneering the protocol of the watch, though.
Maybe @SMaiz or @Lightwars who did a lot of work for supporting the ZeTime in GadgetBridge can help me out or are interested in this?

#### Your wearable device is:
MyKronoz ZeTime

#### Your android version is:
8.1

#### Your Gadgetbridge version is:
0.28.1  (fdroid)

**Comment by SMaiz** [comment]
Hello !
Currently I haven't reverse-engineered the configuration part. I need some time for this, and I'm currently quite busy. Maybe in a month or so, I'll be able to put more time into this.
What's the first configuration part you want to see implemented, in order to orient my searching ?

**Comment by myxor** [comment]
Hello @SMaiz,

thanks for helping out.

My personal ranking of configuration settings i would like to see:

1. Heartrate: automatic messurement and alarming (min, max heartrate value)

2. Do not disturb time settings

3. Inactivity alarm: This one is more complicated because of different time and day-of-week settings

**Comment by Lightwars** [comment]
I have worked out some of the features mentioned like 1. and 2. and have some others available in the settings. At the moment changing them works, but it makes more sense to me, to get the settings from the watch before changing them. So this is a to do at the moment.

**Comment by myxor** [comment]
Thanks for your effort. If i can test something i am willing to help.

**Comment by Lightwars** [comment]
@myxor 
If you want to test something go here: https://forum.xda-developers.com/android/apps-games/testing-gadgetbridge-zetime-support-t3813241

**Comment by myxor** [comment]
Very good work!
As far as i remember every setting i saw and tested was working as expected.

Are there any further steps from you?

**Comment by Lightwars** [comment]
I will improve the experince, like loading the configs from the watch before setting.
Little things can be added, then just two big things missing...
I have a idea for a setting MyKronoz has not think of.

**Comment by myxor** [comment]
I am very curious what that means :)

**Comment by Lightwars** [comment]
I have hopefully finished a pull request to have reading and writing some of the configuration from within the app.

**Comment by Lightwars** [comment]
@myxor can this be closed? Because your desired preferences had been merged.

**Comment by myxor** [comment]
Yes this is merged. Thank you.
