### ISSUE TITLE
[Miband2] How to get activities data with timestamp?

### ISSUE THREAD

**Issue by ydykevin** [Freeyourgadget/Gadgetbridge#1186]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
My work is based on Miband API in JS version: https://github.com/vshymanskyy/miband-js

I was trying to obtain user's activities data with timestamp (like determine in what time user is walking, sitting or at least know in what time user is active).

For the Gadgetbridge app, there is a fetch button (looks like a refresh iron) that will fetch data from miband2. I believe this fetch operation will grab activities data from miband2.

In order to know which characteristics it reads, writes and notifies during fetch operation. I add some print operations (to the console) to the corresponding methods in  

nodomain/freeyourgadget/gadgetbridge/service/btle/TransactionBuilder.java

And I noticed during the fetch operation, it will notify and write (no reading operations) to two characteristics:

00000004-0000-3512-2118-0009af100700
00000005-0000-3512-2118-0009af100700

According to the explanation in

nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Service.java

00000004-0000-3512-2118-0009af100700 is unknown
00000005-0000-3512-2118-0009af100700 is activity data

Therefore, I think I am on the right track.

I have tried to read value from these two characteristics directly with Miband JS API

let data = await this.char.activ.readValue();  --read from 00000005-0000-3512-2118-0009af100700

but it shows "not supported".

Now, my problems are:

1. If the activities data and timestamp are stored in these two characteristics, how do I obtain them (read them)? Is there any special operations before I can obtain them? Like write some data to them first to tell Miband2 that I am going to read the activities data.

2. If the activities data are not stored in these two characteristics, where I can obtain the activities data with corresponding timestamp?

3. If any format conversion is needed for the data, please also show me, thx!!

FYI: Activities data mean the action types (walking, running)

#### Your Gadgetbridge version is: 0.28.1

**Comment by danielegobbetti** [comment]
I appreciate you reaching out for help, but I hope you will understand that the issue tracker of Gadgetbridge is not the right place to do it.
