### ISSUE TITLE
"Database Error while syncing Calendar" when connecting with ZeTime

### ISSUE THREAD

**Issue by myxor** [Freeyourgadget/Gadgetbridge#1188]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

Each time after connecting GadgetBridge to my ZeTime i get the toast "Database Error while syncing Calendar".
From the log i got the following:

> 09:35:36.281 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
09:35:36.284 [main] INFO  n.f.g.e.CalendarReceiver - Created calendar receiver.
09:35:36.285 [main] INFO  n.f.g.e.CalendarReceiver - got calendar changed broadcast
09:35:36.307 [main] INFO  n.f.g.e.CalendarReceiver - Syncing with calendar.
09:35:36.323 [main] ERROR n.f.g.u.GB - Database Error while syncing Calendar

Full log up to the error:

[zetime calendar log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/2256486/zetime.calendar.log.txt)

Can i provide some additional or deeper logs somehow?

#### Your wearable device is:

MyKronoz ZeTime 

#### Your android version is:

8.1

#### Your Gadgetbridge version is:

0.28.1 from fdroid

(sorry for duplicate issue report, i closed the other one)

**Comment by DevelAngel** [comment]
I have the same issue.

Wearable device: MyKronoz ZeTime
Android Version: 9.0 (Lineage OS 16.0)
GadgetBridge Version: 0.36.1
