### ISSUE TITLE
What are the differences between "Notif" and "Pebble" checkboxes in Blacklist Apps screen

### ISSUE THREAD

**Issue by haidahaha** [Freeyourgadget/Gadgetbridge#1192]
#### Your issue is:
In Blacklist Apps screen, there for each app there are 2 options to check: Notif and Pebble. How are they different? I tried to look for description but could not find any. Thanks!

**Comment by danielegobbetti** [comment]
Thanks for noticing this. I added the information to the wiki:
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Configuration#general-settings

/close
