### ISSUE TITLE
Permanent low battery notification if no battery level is provided

### ISSUE THREAD

**Issue by maxirnilian** [Freeyourgadget/Gadgetbridge#1197]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
https://github.com/Freeyourgadget/Gadgetbridge/blob/dd3cbc3e3168e7b42c27f8a8d0208ce50013a22b/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/AbstractDeviceSupport.java#L326-L349

Devices providing just a battery state like "OK" or "LOW" but not a battery level (deviceEvent.level is set to GBDevice.BATTERY_UNKNOWN) will cause the notification to be permanently shown as:

> _Device name_ battery left: -1%

#### Your wearable device is:

Lenovo Watch 9, but in particular this affects every device having a battery state but not a battery level I think.

#### Your android version is:
7.1.2

#### Your Gadgetbridge version is:
master

**Comment by cpfeiffer** [comment]
I'll have a look at this soon.
