### ISSUE TITLE
Improve application persistence

### ISSUE THREAD

**Issue by harshad1** [Freeyourgadget/Gadgetbridge#12]
Right now, gadgetbridge is too easy to close (accidentally). There should be a way to disable the 'X Quit' button and have gadgetbridge restart whenever it dies. This should be accompanied by a way to actually kill the app (a menu item maybe) 

Also, is there an official donation / bounty system in place?

**Comment by ashimokawa** [comment]
I might remove the quit button from the notification and put it in the main activity.

Did you encounter any crashes? I prefer having zero bugs instead some kind of automatic restart on crash ;) So if you notice any bugs, please file an issue.

Regarding donations, there is no way to donate yet.
