### ISSUE TITLE
Pebble: Support colors in notifications

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#120]
If you have any hint for me I can try that out. I did not find anything for the moment.

**Comment by ashimokawa** [comment]
Background color goes in the attribute list, attribute id is 28, type is byte (length 1)
Color format is ARGB2222. I suggest to set alpha to 0b11
So encoding red would be
0b11110000
or yellow
0b11111100

etc

-----
buf.put((byte) 28); // background color
buf.putShort((short) 1); // length of byte
buf.put((byte) 0b00111100); // yellow

---

other notable color related ids are:
27 = primary text color
29 = secondary text color

**Comment by ashimokawa** [comment]
Tested and working on the Emulator (I do not have a pebble time)

**Comment by roidelapluie** [comment]
As you would have guessed I have one :) I will test that.
