### ISSUE TITLE
sms notification text is in chinese

### ISSUE THREAD

**Issue by UncleInf** [Freeyourgadget/Gadgetbridge#1203]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

SMS notification content is displayed in chinese.  The icon and the sender is displayed ok.
The content approximately says: "sender" received new message. Please check on the phone. 

#### Your wearable device is:

mi band 3
hw version - 0.18.3.2
fw version - 1.3.0.4

#### Your android version is:
8.0
#### Your Gadgetbridge version is:
0.28.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by RichiH** [comment]
Same here

* Mi Band 3
* FW: 1.2.0.8
* HW V0.18.3.2
* Android 9.0
* Gadgetbridge 0.28.1

**Comment by ashimokawa** [comment]
I can confirm the issue. To anyone who used mi fit: what is expected? Does the Band show message content and sender? How are they separated. Screenshots welcome ;)

**Comment by joserebelo** [comment]
@ashimokawa 
The Mi Band 3 shows the sender right after the app icon, it scrolls horizontally. Also, the messages can now span multiple pages.

Here are captures for two messages (firmware 1.4.0.6): [pcaps.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/2298005/pcaps.zip)

The first message: Test.
The second message (got trimmed, of course): Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut diam consectetur, condimentum magna eu, porta nibh. Integer massa ligula, tincidunt id sodales nec, placerat eget libero. Sed massa lorem, convallis sit amet tortor at, ornare posuere diam. Nulla auctor tincidunt arcu non ultricies.

And some photos:

| ![2018-08-17_17-29-30_fx_web_access_-_mozilla_firefox](https://user-images.githubusercontent.com/1586795/44277636-42154980-a243-11e8-957f-5f846a9676a4.png) | ![2018-08-17_17-29-41_fx_web_access_-_mozilla_firefox](https://user-images.githubusercontent.com/1586795/44277638-42154980-a243-11e8-914a-c99af6b14955.png) | ![2018-08-17_17-29-50_fx_web_access_-_mozilla_firefox](https://user-images.githubusercontent.com/1586795/44277639-42154980-a243-11e8-9df7-7909d4733cb9.png) | ![2018-08-17_17-29-56_fx_web_access_-_mozilla_firefox](https://user-images.githubusercontent.com/1586795/44277640-42ade000-a243-11e8-8ef1-63acf692c8f8.png) |
|---|---|---|---|

**Comment by ashimokawa** [comment]
@joserebelo 
Thanks!
I had this running 5 minutes again, and then it failed again, no idea what I am doing wrong now.

**Comment by spyjoshx** [comment]
Can confirm this happens for me as well.
Android 7.1 (lineageos)
Gadgetbridge (latest from fdroid)
Mi band 3 FW: 1.5.0.2
HW: 0.18.3.2

**Comment by ashimokawa** [comment]
@joserebelo 
I was just to stupid to look closely at your pcap file.
Yesterday I noticed that there is another new null terminated string at the end saying "Messenger" which is the source of the notification. Even though it is not displayed, it is necessary to send something to have the message displayed.

Anyway, resolved, thanks ;)
