### ISSUE TITLE
Help Mi band 3 

### ISSUE THREAD

**Issue by Vitorls** [Freeyourgadget/Gadgetbridge#1209]
I edited some parameters to correct and simplify the BR translation, and I only saved it using the 010 editor program. Went to install on the band presented that the Fw. was not valid, First doubt is there any compiler?
Then I reviewed the issue and started the installation.
When complete, my bracelet turned off the screen completely .. no screen or charge. I can only see bluetooth as LGV30 and MAC address. Is there any way to fully recover the FW? Restore the Band? Or have I completely lost my bracelet?
Please help me please need it to complete an engineering course work and help people with heart problems of my country who suffers greatly from corruption.

**Comment by danielegobbetti** [comment]
I'm unsure I understand what you are writing, but I don't see how it relates with this project.

If you changed the Gadgetbridge translations then you can just install the version from f-droid to get a working app. So this is not an issue of the project (BTW, our translations are managed using the awesome weblate floss web app)

If you manipulated the firmware of your wearable and bricked it by flashing, I am sorry that you lost your gadget but again this is not an issue of the project.
