### ISSUE TITLE
Pebble: Support replying to SMS

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#121]
It would be great if we could have an action 'reply' to sms.

We would have to add a ui in the app to preset a bunch of responses.

There are 2 limitations in the proprietary app that we could avoid:

* official app contains a very limited subset of replys (5 I think). would be great if we could extend that to 15 for example
* official app does not ask for a receipt confirmation.

**Comment by roidelapluie** [comment]
This issue is part of #103

**Comment by ashimokawa** [comment]
This would require a few additions things:

- adding permission for sending SMS
- ability to map a notification back to a phone number, so we would have to keep a lookup table somewhere.
- changes to PebbleProtocol (this is easy, I just didnt do because it is not useful yet)

**Comment by roidelapluie** [comment]
@ashimokawa any progress of this, in particular how we could implement it?

**Comment by ashimokawa** [comment]
@roidelapluie 
I will implement it when I feel like it

And frankly speaking, personally, I have about zero interest in having this feature.
Still, I *will* do it, for the sake of completeness.

**Comment by roidelapluie** [comment]
This is brilliant! Thank you! And it also works with emojis! :-)

**Comment by ashimokawa** [comment]
It is not very good yet.
It will always think SMS were sent out even if there are problems sending them or we cannot determine the phone number.
I will add one workaround for the case it cannot determine the phone number (eg. when Gadgetbridge was restarted before replying on the watch).
For the rest I will see... it would take some refactoring decisions.

**Comment by roidelapluie** [comment]
Okay. Is the limit of 8 a limitation of the Pebble Protocol, or could we extend that limit?

**Comment by ashimokawa** [comment]
I tried with 16, it still worked.
However, there is total limit of 512 bytes for all replies (minus 1 byte for every reply except the last one)

So:
Total allowed bytes for all replies = 512 - (reply count -1)
