### ISSUE TITLE
Liberapay issues

### ISSUE THREAD

**Issue by hughwilliams94** [Freeyourgadget/Gadgetbridge#1210]
Firstly, thank you very much for a wonderful app. I've just started using it with my Bip, and I am thrilled to be able to use a fitness tracker without the proprietary nonsense.

For this reason, I immediately tried to setup a monthly donation but liberapay is giving me this error:

"Your donation to Gadgetbridge cannot be processed right now because the account of the beneficiary isn't ready to receive money."

Perhaps you could investigate, so that I can get my money to you ASAP.

Thanks again.

**Comment by IzzySoft** [comment]
You will get the same error for many beneficiaries currently – which is due to the fact that their payment provider (Mangoo) had kicked them out. They have now setup Stripe as a new provider, but each user must first enable that and agree to Stripe's TOS.

Many (including the GB team and me) obviously haven't yet done so. While we might think the LP team will make sure of safe choices, the very fact that they also plan for PayPal (IIRC) raises some eyebrows (at least mine). I'd prefer to first being convinced I can trust their new payment processor (though admittedly they will at least be comparable to Mangoo, if not better – but proof would be better than guesses).

**Comment by hughwilliams94** [comment]
Thanks for letting me know, I will keep my eyes on this thread and set my payment up when you have something sorted out.

**Comment by IzzySoft** [comment]
Thanks @mattbk – but in the linked issue it sounds as if that still would need a Stripe account. I hope I got that wrong. Is it needed to receive SEPA payments?

**Comment by cpfeiffer** [comment]
Thanks for the pointer! We don't have a Stripe account, but we successfully initiated a SEPA transfer. Let's see if it works, but it's looking good so far :+1:

**Comment by IzzySoft** [comment]
Though this is the older one, let me close it in favor of its duplicate #1273 which is a little more generic and dealing with how to make donations. Still unsolved, though.

I wonder how @cpfeiffer successfully initiated a SEPA transfer: Yes, Liberapay supports *incoming* SEPA. But as long as the "receiver" hasn't setup either Paypal or Stripe (which Gadgetbridge has not), no withdrawal is possible and so neither is a pledge. I'm in the very same situation with my LP account, and I hammered them a bit. Answer is still "no way".

**Comment by vanous** [comment]
Hi all,

the team has decided to proceed with Librepay again, see copy/paste of the announcement posted in Matrix:

> After more than a year we bit the bullet and re-enbled donations on liberapay by complying with what had to be done to make that work. We were already almost dried up and were unable buy devices we wanted to support. To make Gadgetbridge even better please consider to donate.

>Do not want to push anyone but it was requested over and over again. And supporting new devices without having them is very time consuming ;)

So thank you very much for proceeding if you still consider supporting the project financially! 

<a href="https://liberapay.com/Gadgetbridge/donate" rel="nofollow"><img src="https://camo.githubusercontent.com/ae8af018f80649f3d379eb23dbf59acceaffa24e/68747470733a2f2f6c69626572617061792e636f6d2f6173736574732f776964676574732f646f6e6174652e737667" alt="Donate" data-canonical-src="https://liberapay.com/assets/widgets/donate.svg" style="max-width:100%;"></a>
