### ISSUE TITLE
Amazfit bip fw update compatibility reports

### ISSUE THREAD

**Issue by qwazix** [Freeyourgadget/Gadgetbridge#1214]
I just tried updating amazfit bip from 0.0.9.29 to 1.1.2.05 and the procedure finished successfully.

I am naming this issue in a generic way so that future fw compatibilty successes/failures can be reported here.

**Comment by lovenemesis** [comment]
Another confirmation of its working.

**Comment by bhavin192** [comment]
Just did yesterday with my new watch, worked fine for me too.

**Comment by nr458h** [comment]
as this is already shown in the wiki and we do have new fw updates you can propably close this issue?

**Comment by ashimokawa** [comment]
I assume  this issue was meant to be reused. No one did that, so I am closing this. Latest firmwares were ota, I will update them.
