### ISSUE TITLE
1st time with GB (24h format and contact info)

### ISSUE THREAD

**Issue by victorjagu** [Freeyourgadget/Gadgetbridge#1221]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

Hello, I'm trying GB for the 1st time, and I'm figuring some problems to find tutorials (perhaps I'm not used to this type of forum/posting information). Either way, let me apologize if I'm not in the correct place or whatever, please.

I'm writing here because I want my mi band 2 (HW v0.1.3.3) to sent me who is texting or calling me, and, I encountered two problems that i can't solve, and I don't know if my GB config is wrong...

1. My mi band 2 changed the time format from 24h to 12h. I've read that GB should take Android's time format, so is not that case. Any ideas?

2. Text notifications works pretty well, however, I'm really interested in receiving the contact name, rather than the whole text message (e.g. I would like to know that my brother has sent me a WhatsApp, rather than what he said). Is there a way to do that? I've read in this forum sth about it (the app tools and mi band does it), but I don't if it is for other devices, is still under development or what I'm doing wrong.

Thanks in advance for your support.

Btw, I don't know if it's important but I'm using my device in Spanish but GB in English, otherwise, some texts in the app can't be read (they are too long in Spanish).

#### Your wearable device is:

Mi Band 2 (without My Fit installed) (HW v0.1.3.3)

FW 1.0.1.81

*Please specify model and firmware version if possible*

#### Your android version is:

I'm using an Asus Zenfone ZE553KL running Oreo (8.0).

#### Your Gadgetbridge version is:

GB 0.29.0

Edit:
Any tutorial documents for mi band 2 (what does the icons in GB means, how to implement plugins if they are support, etc, are very welcome). Thank you!!

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by vanous** [comment]
Hello, are you still having this issue? The documentation hes been improved (https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-2 ). Please consider closing this issue if your question has been answered, thank you.

**Comment by victorjagu** [comment]
I don't use it anymore, so i can't do tests
