### ISSUE TITLE
MB3 Resources (*.res) v40 installation error

### ISSUE THREAD

**Issue by KhKirillA** [Freeyourgadget/Gadgetbridge#1223]
Recently released Mi Fit 3.4.6 contains new firmware for MB3 (1.5.0.2) and new corresponding resources v40. So, as it has size of `100159` bytes, we are not able to install it because of this code:

`if (bytes.length > 100000) { // don't know how to distinguish from Bip/Cor .res`
at `.../service/devices/huami/miband3/MiBand3FirmwareInfo.java:72`

I think we need to increase the limit of MB3 resources file or remove it completely as there is no other way to distinguish it from old (uncompressed) Cor / BIP resources.

**Comment by ashimokawa** [comment]
Where did you get that Mi fit version?

**Comment by KhKirillA** [comment]
From Play Store, it is just rolling out to all regions step by step.
