### ISSUE TITLE
Weather not syncing with Amazfit Bip

### ISSUE THREAD

**Issue by kalaee** [Freeyourgadget/Gadgetbridge#1229]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

## My issue
I have tried to follow the setup with Weather Notification and yet I cannot get weather info on my Amazfit Bip. Could the problem be related to the fact that I use the Play Store versions of Gadgetbridge and Weather Notification rather than the F-Droid versions?

## Setup
Phone: Nokia 5, stock Oreo
Amazfit Bip: 1.1.2.05
Gadgetbridge: 0.29.0.0 (Google Play Store version)
Weather Notification: 0.3.10 (Google Play Store version)

**Comment by ashimokawa** [comment]
Just use the official version.

**Comment by IzzySoft** [comment]
Pointer for you, @kalaee: the official versions are those on F-Droid. The playstore version of GB is not maintained by the GadgetBridge team, it's [a fork](https://github.com/TaaviE/Gadgetbridge) of this project. Problems with that should be reported there (but can't as the issue tracker is disabled).

@ashimokawa unfortunately the "website" link Taavi provides at playstore redirects here directly, which suggests issues with his fork could be reported here as well. It would be better @TaaviE would point that link to a page stating the details – and dealing with issues specific to his fork himself.

**Comment by TaaviE** [comment]
@IzzySoft As mentioned in the Play Store description.

> Problems with that should be reported there (but can't as the issue tracker is disabled).

The intention was that I'm e-mailed instead.

> issues specific to his fork himself.

That is to be determined, I also **heavily** doubt that, my changes to GB are minimal and do not touch the weather part of the system directly.

@kalaee I'll try and test out the two apps with my Pebble as I don't have a Bip.

**Comment by kalaee** [comment]
@IzzySoft, yes, you are right, I should have done that. Sorry.
I have now switched to the official version of both and it works perfectly!

@TaaviE, I guess this implies that there is a problem in the Play store fork (either GB or Weather Notification) that makes weather for the Bip unavailable.

**Comment by TaaviE** [comment]
@kalaee Could you please test F-Droid GB with Play Store Weather Notification?

**Comment by TaaviE** [comment]
Scratch that, the issue is fixed (works on my devices) in the latest version.

**Comment by IzzySoft** [comment]
@TaaviE 

> As mentioned in the Play Store description.

Yes, true it's there. But most people will simply click the website link first (some out of habit, and some because they don't read all details). Would be good if that link instead of simply redirecting could go to a page under your control, pointing out how to report issues (by mail, as you say) – and then also, as the description on playstore already does, point to "the origin" with some details (the first paragraph from the playstore description would fit well; that could e.g. be followed by an "report an issue here" plus a "visit the original project" links). I e.g. often check for the website first. Seeing the link points to your site I clicked it, and ended up here. Would I not know better I'd assume this is the place for reporting issues.

> That is to be determined, I also heavily doubt that, my changes to GB are minimal and do not touch the weather part of the system directly.

Please think it over. One of those minimal examples are here in this issue.

Thanks for fixing it that fast!

@kalaee and glad it's working fine for you now :tada:

**Comment by TaaviE** [comment]
> Please think it over.

**Comment by TaaviE** [comment]
> Yes, true it's there. But most people will simply click the website link first (some out of habit, and some because they don't read all details). Would be good if that link instead of simply redirecting could go to a page under your control, pointing out how to report issues (by mail, as you say) – and then also, as the description on playstore already does, point to "the origin" with some details (the first paragraph from the playstore description would fit well; that could e.g. be followed by an "report an issue here" plus a "visit the original project" links). I e.g. often check for the website first. Seeing the link points to your site I clicked it, and ended up here. Would I not know better I'd assume this is the place for reporting issues.

I'll add that to my plans.

> Please think it over. One of those minimal examples are here in this issue.

Unfortunately it's impossible to build Proguard/R8 rulesets without testing the changes out, like with every other feature.

**Comment by IzzySoft** [comment]
Thanks, @TaaviE!
