### ISSUE TITLE
Options to limit amount of notifications in X time

### ISSUE THREAD

**Issue by RichiH** [Freeyourgadget/Gadgetbridge#1230]
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

This is loosely related to https://github.com/Freeyourgadget/Gadgetbridge/issues/663, but from a different angle.

I was just in six active chats on my PC at the same time and those notifications go to my cell phone as well. Typing with consta-buzz on your wrist is annoying to say the least.

I would like to be able to limit notifications to, say 3 at max in 5 minutes time or some other numbers. This would tell me if there's more than just a single thing happening, but not become distracting.

* Mi Band 3
* FW: 1.2.0.8
* HW V0.18.3.2
* Android 9.0
* Gadgetbridge 0.28.1

**Comment by danielegobbetti** [comment]
Please use the search functionality (there is a very recent pull request that got merged)

**Comment by RichiH** [comment]
Sorry, I did search, but only in open issues as there was nothing in the 0.29.0 or the 0.29.1 changelong (I got the version wrong in the intial report, I had 0.29.0 installed).

**Comment by RichiH** [comment]
For documentation, it's https://github.com/Freeyourgadget/Gadgetbridge/pull/1222
