### ISSUE TITLE
Mi Band 1S: Doesn't recognize sleep outside night hours.

### ISSUE THREAD

**Issue by DazzyWalkman** [Freeyourgadget/Gadgetbridge#1232]
Hi, I am using Mi Band 1S.
FW: 4.16.11.15
HR:1.3.76.22
HW: 1S
Gadgetbridge from 0.28 to present (0.29.1) F-droid build.
Android 6.0.1
I come across similar issue in article
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Information
regarding Mi Band 1 (coloured LEDs)
Firmware 1.0.9.3 
> activity recognition: works well, but it doesn't seem to recognize any sleep outside of "night hours".

The band fails to recognize my sleep at noon. In the chart, same activity intensity as sleep is logged, but marked as "green normal activity". Not a big problem though, since I already know what is about.

I just wonder if there is any other working firmware version since wiki said none of known issues for a list of firmware . Thanks.

**Comment by danielegobbetti** [comment]
This is a limitation of the device. There is a setting in Gadgetbridge to shift the time a few hours (for people who work during the night and sleep during the day). There is nothing more we can do about it.
