### ISSUE TITLE
Remove "sexy" from Gadgetbridge project topics

### ISSUE THREAD

**Issue by MagicFab** [Freeyourgadget/Gadgetbridge#1235]
Somehow the project has a topic defined as "sexy".

![selection_110](https://user-images.githubusercontent.com/317514/44534357-939b5980-a6c5-11e8-9ba4-988cfd749c22.png)

I believe the project and code are as interesting and relevant as it gets, and will be even more. 

In this context using "sexy" in the topics doesn't contribute and in fact is a distraction when introducing the project to new users. I frankly don't want to research and explain this decision and its implications when I try to show this to others, get them interested in contributing, controlling their data, avoiding sexual objectification of IT, gadgets and software,  etc.

Thanks in advance for considering this request.

**Comment by TaaviE** [comment]
Gadgetbridge supports Vibratissimo devices, maybe indeed "teledildonics" tag might suit the project better and "sexy" should be replaced.

**Comment by IzzySoft** [comment]
I don't think we should have "teledildonics" as tag. "sexy" is at least ambiguous: It's sexy I have my privacy with it. That turns me on :rofl:

**Comment by ashimokawa** [comment]
"teledildonics" does not fit because we do not support internet.

Support was added more as a joke and to get press coverage (which did not work). I did this right after some (other maker) was sued by a user because their app leaked her private data. :speak_no_evil: 

I never thought the "sexy" tag could be problematic... really no idea what to do about it. But rest assure it is not "sexual objectification of gadgets" like Mi Band :stuck_out_tongue:

**Comment by danielegobbetti** [comment]
Sexy was an important topic in the pebble media campaigning (as far as I got it from here), see for example https://www.tomsguide.com/us/pebble-time-round-specs-price,news-21624.html .
I see no harm in having it among the topics.
We could add a few of the latest devices as topics, though.

**Comment by LuccoJ** [comment]
> I frankly don't want to research and explain this decision and its implications when I try to show this to others, get them interested in contributing, controlling their data, avoiding sexual objectification of IT, gadgets and software, etc.

Then don't. Because if someone is concerned about all those things when merely seeing a tag, they should either research it themselves if it *really* makes them curious, or maybe, just maybe, ignore it and look at what the project actually does, which is easy enough to figure out.

We don't need a sexual objectification police on every littlest thing.

**Comment by MagicFab** [comment]
@ashimokawa, thanks for the explanation, I didn't know that story about GadgetBridge development but I remember [that incident](https://www.theguardian.com/technology/2016/aug/10/vibrator-phone-app-we-vibe-4-plus-bluetooth-hack). It provides useful context but I would expect more related topics to be used in that case, for example vibrator, privacy, personal data, self-hosted, smart watch, etc. 

@danielegobbetti that's not Pebble, that's a website using that term instead of many other more precise and descriptive terms. They are notorious for that. I can't remember Pebble describing their devices everywhere as "sexy" and objectifying them as being a central part of their marketing efforts. I remember their site being clean and minimalistic, their devices being well designed and getting better at each version.

@LuccoJ ignoring such behavior leads to more and worse instances of it as you may already know. We do need to remain alert to this. I apologize if I can't explain this better, I encourage you to find out more about why this is a problem in technology. IT conferences and their evolving codes of conduct come to mind, as well as many prominent Free software projects.

**Comment by LuccoJ** [comment]
> ignoring such behavior leads to more and worse instances of it

I am seeing no "behavior" here, I'm seeing an accurate tag; I suppose this means there is no risk of it becoming more and worse, because zero multiplied by anything is zero.
