### ISSUE TITLE
amazfit cor: empty "configure alarms" page

### ISSUE THREAD

**Issue by kheberlein** [Freeyourgadget/Gadgetbridge#1251]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
When opening the "configure alarms" page from gadgetbridges main menu I see only an empty page. When pressing "back" I see a toast reading "all alarms disabled". In fact nothing happens to alarms that happen to be enabled on the watch. This is particularly frustrating as amazfit cor's alarm times cannot be set from the watch. In an older version of gadgetbridge this worked as expected.
*In case of a bug, do not forget to attach logs!*
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/2347624/gadgetbridge.log)

#### Your wearable device is:
Amazfit Cor 
FW: 1.2.1.02 (as well as 1.0.7.57)
HW: V0.12.6.1

#### Your android version is:
LineageOS 14.1-20180504-klte

#### Your Gadgetbridge version is:
0.29.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by danielegobbetti** [comment]
I just tested and cannot reproduce your issue. I guess you changed the value "Alarms to reserve for upcoming events" in ``Settings``->``Mi Band / Amazfit settings``. Changing that value to "0" will make all the three alarm slot reappear in the alarms page.

**Comment by kheberlein** [comment]
Thank you very much. That indeed did the trick (my wife now remembers to have played with that setting). Sorry for the inconvenience.

Keep up the great work, I love Gadgetbridge
Greetings from Germany
Konrad

________________________________
Von: Daniele Gobbetti <notifications@github.com>
Gesendet: Dienstag, 4. September 2018 18:42
An: Freeyourgadget/Gadgetbridge
Cc: Konrad Heberlein; Author
Betreff: Re: [Freeyourgadget/Gadgetbridge] [bug] amazfit cor: empty "configure alarms" page (#1251)


I just tested and cannot reproduce your issue. I guess you changed the value "Alarms to reserve for upcoming events" in Settings->Mi Band / Amazfit settings. Changing that value to "0" will make all the three alarm slot reappear in the alarms page.

**Comment by danielegobbetti** [comment]
Thanks for the kind words!
