### ISSUE TITLE
Notifications are pushed to Amazfit Bip in spite of time-planned "do not disturb" being active

### ISSUE THREAD

**Issue by TimH54** [Freeyourgadget/Gadgetbridge#1255]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I want to mute notifications on my Amazfit Bip during the night. So, in "Settings -> Mi Band / Amazfit Settings -> Do not Disturb" I have set up a time-planned "do not disturb" from 23:00 to 8:00. However, even after 23:00 the Amazfit Bip vibrates on incoming notifications. I attach a log that also shows that Gadgetbridge pushes the notification to the Bip - which it should not.

(I am not referring to activating "DND" on the Bip itself. That works, but is not possible for a planned time-range.)

#### Your wearable device is:

Amazfit Bip FW 1.0.2.00, HW 0.11.2.4

#### Your android version is:

Oreo 8.0 (Oneplus 3T OxygenOS)

#### Your Gadgetbridge version is:

0.29.1

[gadgetbridge.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/2356224/gadgetbridge.log.txt)

**Comment by tradej** [comment]
I have the same issue on Nokia 5/Oreo 8.1. It's a big regression for me, coming from Mi Band 2, where it works.

**Comment by danielegobbetti** [comment]
I can confirm the issue. The on/off commands are sent to the amazfit bip but have no effect. I see that the reply to the message is ``10 09 05``, which might be some kind of error message (AFAIK success messages are something like ``10 01``...

**Comment by TimH54** [comment]
Maybe, as a fallback option, if setting DND mode on the watch fails, Gadgetbridge itself could stop forwarding the notifications to the watch while the time-based DND is active? That would actually then work for all devices ...

**Comment by danielegobbetti** [comment]
@TimH54 this option is already available in the general settings :)

**Comment by TimH54** [comment]
> @TimH54 this option is already available in the general settings :)

Really? Am I too blind? I only see the option to not send any notifications when the phone is in DND mode. That doesn't work for me, because my phone is always in DND mode. If there is indeed an option to not send notifications for certain periods of time, then please point me to it, thanks!

**Comment by danielegobbetti** [comment]
@TimH54 when you wrote "while the time-based DND is active" I thought of Android's functionality. What you describe is indeed not possible at the moment.

**Comment by cpfeiffer** [comment]
Superseded by #1706
