### ISSUE TITLE
More alarms request

### ISSUE THREAD

**Issue by fushark** [Freeyourgadget/Gadgetbridge#1262]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Hi!
Thanks for the superb job on this app. I am using it with my MiBand2 at the moment. I use the band mostly away from my phone, so I do need more than 3 alarms that are currently included with the app.  I would like to suggest 5 alarms for the future version or the ability to add more alarm if it is not too much asking.

Thanks for reading!
Cheers!

#### Your wearable device is:
MiBand2
*Please specify model and firmware version if possible*
1.0.1.81
#### Your android version is:
5.1.1
#### Your Gadgetbridge version is:
0.29.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by cpfeiffer** [comment]
Yes, we definitely need to support more alarms. See #462

**Comment by croisez** [comment]
MiBand2 FW1.0.1.81
Android 7

I accidentally clicked on the ZzZz Widget, and now it remains only one alarm configurable in GB.
I searched for a (+) button to add the 2 missing alarms, but no success.
What should I do? Go back and forth to official Mi app to restore the 3 alarms items?

**Comment by ashimokawa** [comment]
Done is master, will be in the next release after 0.31.3
