### ISSUE TITLE
Reconnection issue on MI1S

### ISSUE THREAD

**Issue by gardiol** [Freeyourgadget/Gadgetbridge#1271]
Band: MI1S (it used to happen also with my old MI1A)
Phone: Xiaomi redmi Note 5 (it used to happen also with my old Samsung Note 3)

Situation: band is correctly paired and works great. 

Issue: when phone and band are parted and for any reason connection is lost (for example, if i walk upstairs with phone downstairs) connection will NOT be re-extablished automatically when back in range. I must manually tap on the "connect" notification or open GB and connect the band.

It does happen either with "usb pairing" on or off in the settings.

This has been there forever, i just switch back to Mi Fit app because of this, i did lose notifications and calls and such many times when on GB because of this.

Please, if possible, fix it or, if it is a settings issue, help me understand how to correct this.

I can very easily reproduce this issue any time.

**Comment by Pepe404** [comment]
Same for Amazfit BIP, I tried GB 0.30 and deleted it for the same reason, went back to Mi Fit again.

**Comment by gardiol** [comment]
I had to give up on GB, this long standing issue gas never been into consideration by any Dev.

**Comment by xandro0777** [comment]
Sometimes reconnect works for me but often it doesn't - displaying either a gray "connecting" or waiting for reconnect.

The problem seems to be, when a connection is lost or connection establishment doesn't succeed the connection state isn't cleared?
