### ISSUE TITLE
GB connection disables "lift wrist to view info" feature on Mi Band 3

### ISSUE THREAD

**Issue by tomerrr** [Freeyourgadget/Gadgetbridge#1274]
Once I connect MB3 to GB, its screen doesn't turn on anymore when i lift the wrist 

Mi Band 3 FW: 1.3.0.8
GB ver 0.29.1
Android 8.0 OnePlus3T

**Comment by cpfeiffer** [comment]
There's a setting for this in Mi Band / Amazfit Settings in Gadgetbridge.
