### ISSUE TITLE
MiBand 3: Initial pairing does not work, band is stuck in "pair device first"

### ISSUE THREAD

**Issue by kuleszdl** [Freeyourgadget/Gadgetbridge#1276]
#### Before reporting a bug, please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
Initial pairing of Mi Band 3 does not work for me. I did not install MiFit. MiBand 2 works fine. Steps to reproduce:

- pair the device via Android bluetooth settings (works)
- (device shows up in Gadgetbridge)
- click "connect" in Gadgetbridge

Some users reported the same issue in #1113. As far as I understood that is supposed to be resolved in the current version? Or is this still an issue?

#### Your wearable device is:
Mi Band 3

*Please specify model and firmware version if possible*
EU Version

#### Your android version is:
9.0

#### Your Gadgetbridge version is:
0.30.0

Many thanks!

**Comment by kuleszdl** [comment]
Alright, I got it working. The trick was the following:

- unpair the band in Android settings
- set "use bluetooth pairing" in the Mi Band / Amazfit settings to "no" (as outlined in #1116)
- use the "plus" button in Gadgetbridge to discover the MiBand 3
- pair it.

Would be great if the procedure was documented in the Wiki. Unfortunately, it seems like Github does not support Wiki pull requests.

**Comment by ashimokawa** [comment]
I think we shall never pair any mi and huami devices.

**Comment by kuleszdl** [comment]
@ashimokawa By "pair", you mean pair them via bluetooth in Android? Tbh, I didn't realize before the gadget could be operated without being paired at all.

**Comment by ashimokawa** [comment]
Since I was told mi fit never pairs at Bluetooth level, we should probably also not do it. I have no idea why Bluetooth le device makers have their own pairing at app level

**Comment by joserebelo** [comment]
Mi Fit actually pairs at Bluetooth level in order to use the band for Smart Lock (I think that it indeed does not by default, though).
