### ISSUE TITLE
No good on Nougat (30 fdroid)

### ISSUE THREAD

**Issue by forkoz** [Freeyourgadget/Gadgetbridge#1283]
#### Before reporting a bug, please confirm the following:
- [x ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
New phone, new mi. I see the red fist and then "gadgetbridge has stopped", start again over and over.
I gave it all permissions and rebooted. The notification comes up at startup but taping it produces the same behavior.

If its something on my end, let me know because I can't think of what it is.

#### Your wearable device is:
MiBand 2 - just got it.

#### Your android version is:
Carbon 7.1
#### Your Gadgetbridge version is:
30.0

Log:
09-25 06:11:42.135   586   606 W WindowManager: Failed looking up window
09-25 06:11:42.135   586   606 W WindowManager: java.lang.IllegalArgumentExcepti
on: Requested window android.view.ViewRootImpl$W@b36bfd3 does not exist
09-25 06:11:42.135   586   606 W WindowManager:         at com.android.server.wm
.WindowManagerService.windowForClientLocked(WindowManagerService.java:9496)
09-25 06:11:42.135   586   606 W WindowManager:         at com.android.server.wm
.WindowManagerService.windowForClientLocked(WindowManagerService.java:9487)
09-25 06:11:42.135   586   606 W WindowManager:         at com.android.server.wm
.WindowManagerService.removeWindow(WindowManagerService.java:2403)
09-25 06:11:42.135   586   606 W WindowManager:         at com.android.server.wm
.Session.remove(Session.java:202)
09-25 06:11:42.135   586   606 W WindowManager:         at android.view.ViewRoot
Impl.dispatchDetachedFromWindow(ViewRootImpl.java:3320)
09-25 06:11:42.135   586   606 W WindowManager:         at android.view.ViewRoot
Impl.doDie(ViewRootImpl.java:5954)
09-25 06:11:42.135   586   606 W WindowManager:         at android.view.ViewRoot
Impl$ViewRootHandler.handleMessage(ViewRootImpl.java:3656)
09-25 06:11:42.135   586   606 W WindowManager:         at android.os.Handler.di
spatchMessage(Handler.java:102)
09-25 06:11:42.135   586   606 W WindowManager:         at android.os.Looper.loo
p(Looper.java:154)
09-25 06:11:42.135   586   606 W WindowManager:         at android.os.HandlerThr
ead.run(HandlerThread.java:61)
09-25 06:11:42.135   586   606 W WindowManager:         at com.android.server.Se
rviceThread.run(ServiceThread.java:46)

**Comment by cpfeiffer** [comment]
This is very weird. Do you have {this option](https://stackoverflow.com/a/11476373) enabled in your OS settings?

**Comment by cpfeiffer** [comment]
Or, do you have other exceptions in the log?

**Comment by forkoz** [comment]
I just checked and I do not have the option enabled. I didn't see any other exceptions but I'd have to take a longer logcat rather than just doing cmd >adb shell -> logcat.

On slim rom (android 6.0) with a similar phone it runs but won't connect to the band unless notify and fitness already connected to it which is probably a separate issue.

**Comment by IzzySoft** [comment]
Does this issue still exist for you, @forkoz – or did an update (of either Gadgetbridge or your Android version) solve it? seeing you wanted to provide a longer logcat about a year ago, and that never happened, looks like the problem no longer exists for you and we should close this issue. Should I be wrong, please say so and I reopen.
