### ISSUE TITLE
Translation clarification

### ISSUE THREAD

**Issue by vanous** [Freeyourgadget/Gadgetbridge#1284]
Hi all, thanks for all the work. I have contributed updates to the Czech translation, thank you for merging it. Question: i am trying to figure out what Speed zones are. I tried to translate it correctly, but i am not sure what it should do as on my device (i have Mi 1S), Speed zones screen is always empty. Do i have to do anything to enable it? Thank you for clarification and for the great project.

**Comment by cpfeiffer** [comment]
Thanks for your translations, much appreciated! The speed zones *should* be available for all devices that support activity synchronization and steps/minute, so it should definitely work for the Mi1S.

The chart is not quite self explanatory, so I'll try to explain. It is supposed to show you how much time you spent in various "speed zones", or a little bit more concrete, how many minutes you managed to make 120 per minute, for example.

**Comment by vanous** [comment]
OK, i now have Mi Band 3 and can see what the speed zones do. Mi Band 1S does not behave this way. I still have the 1S so i can get some data into the database for investigation, if you want me.

**Comment by vanous** [comment]
Could someone please pull in updated Czech translation from weblate? It is 100% up to date. Thank you very much!
