### ISSUE TITLE
sometimes i dont get notifications 

### ISSUE THREAD

**Issue by harel1320** [Freeyourgadget/Gadgetbridge#1300]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
sometimes i dont get notifications...

#### Your wearable device is:
Mi band 3
*Please specify model and firmware version if possible*
v1.5.0.2
#### Your android version is:
7.0
#### Your Gadgetbridge version is:
3.0

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by IzzySoft** [comment]
If this issue still exists: can you please check whether your gadget (here: the Mi:Band) has lost its connection when you miss notifications? Can you give any additional context? Without context, it's hard to help.

**Comment by IzzySoft** [comment]
Might be related to #1639 – but without feedback from you, we cannot assist. Should you still have that issue and wish to have dealt with it, let us know. Meanwhile, I'm closing this as stale (assuming "no answer" means you no longer encounter this problem).
