### ISSUE TITLE
Where is Mi Band 3- lift wrist feature?

### ISSUE THREAD

**Issue by dpnkrg** [Freeyourgadget/Gadgetbridge#1303]
#### Your issue is:
*Not able to found lift wrist feature in Mi band 3*
*Where is lift wrist feature, How to enable/disable this feature*

#### 0.30.0

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by joserebelo** [comment]
It's in the "Mi Band / Amazfit Settings" section.

**Comment by dpnkrg** [comment]
Found it.
@joserebelo, how to get response/message back to android device when lift wrist action is triggered on band.

**Comment by joserebelo** [comment]
I don't get what you mean, do you want the app to react when the wrist is lifted? I don't think that is possible, the band does not send such events.

**Comment by selurvedu** [comment]
Is it possible to enable the "Rotate wrist to switch info" option on Mi Band 3?

**Comment by dpnkrg** [comment]
can i get response back of lift wrist to android device?
