### ISSUE TITLE
Mi Band 3: "Find Device" feature does not work properly

### ISSUE THREAD

**Issue by selurvedu** [Freeyourgadget/Gadgetbridge#1306]
#### Before requesting a new feature, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

"Find device" is a feature that helps to find the lost phone. There is a corresponding menu item on Mi Band 3. Unfortunately, it doesn't seem to work — Gadgetbridge detects the "find phone" event and acknowledges it, but the corresponding activity/intent is not shown. Instead, an exception is thrown:

```
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
    ...
    at nodomain.freeyourgadget.gadgetbridge.service.AbstractDeviceSupport.handleGBDeviceEvent(AbstractDeviceSupport.java:177)
    ...
```

https://github.com/Freeyourgadget/Gadgetbridge/blob/ecbfa38214a18a709e9034aac267b9810ec1447f/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/AbstractDeviceSupport.java#L177

Please refer to the attached log file for more info.

#### Your wearable device is:

Mi Band 3 (without NFC) XMSH05HM
HW: V0.18.3.2
FW: 1.5.0.2

#### Your Android version is:

6.0.1 (LineageOS 13)

#### Your Gadgetbridge version is:

0.30.0

**Comment by selurvedu** [comment]
Log file: [log-find_phone.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/2473836/log-find_phone.txt)

**Comment by dpnkrg** [comment]
update your mi band 3 firmware and try again.

**Comment by joserebelo** [comment]
This shouldn't be firmware related. I can't reproduce this on any of my devices, though, but 096069f should fix it.

**Comment by selurvedu** [comment]
@joserebelo, thank you!

2all: sorry for duplicate comments, that was some kind of a glitch on github's side. I wasn't able to post a reply (a warning message saying "please try again later" appeared) even though I tried two times in a row and one more time later, in 30 minutes or so. As I see now, all three of them were posted with a delay (they were not there when I opened the page in another browser before the last attempt).
