### ISSUE TITLE
Documentation on data exportation

### ISSUE THREAD

**Issue by techfarmer** [Freeyourgadget/Gadgetbridge#1307]
1.My issue is that i looked everywhere for documentation on handling of data from my Miband3.We need a detailed,step by step guide for someone (non-developer) that wants to use the Miband data outside of Gadgetbridge.The documentation should be easily accesible and clear on the following : 
a - which files and in which location contain the actual raw data on sleep,heartrate and activity ?is it in the file location indicated under database management?Is it the file in the export location under settings/auto export?....i assumed 
b - what is the above files default format?csv?sqlite3?...i assumed sqlite3
c - can i only open the above file with sqlite3?...which RDBMS tool is advisable to open and browse the data?ive used DBBrowser for SQLLite
d - which table/s contain the deviceID, activity, heartrate and sleepdata ? 
e - Is it the data in the file under settings/Auto Export/Export Location?...It seems obvious but when i access the "miband" file from that default export location in DB Browser for SQLIte (after giving it a .sqlite3 extensionname) there is zero data in any table.This doesnt seem to be documented anywhere or am i looking in all the wrong places?

2.My wearable device is Mi Band 3

3.My android version is 8.0.0

4.My Gadgetbridge version is 0.30.0

*New requests about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by vanous** [comment]
hi,

i am new here too. not an android dev, but i can use a bit of python here and there.

you can get data from the database by exporting it first in the GB app, this will create sqlite file called Gadgedbridge which you can then process in your computer, see example here: https://gist.github.com/vanous/592b0a12fb2596f6c0d960909fb9c9d3

the data in the database is nicely described by column names:

CREATE TABLE IF NOT EXISTS "MI_BAND_ACTIVITY_SAMPLE" 

"TIMESTAMP" INTEGER  NOT NULL ,
"DEVICE_ID" INTEGER  NOT NULL ,
"USER_ID" INTEGER NOT NULL ,
"RAW_INTENSITY" INTEGER NOT NULL ,
"STEPS" INTEGER NOT NULL ,
"RAW_KIND" INTEGER NOT NULL ,
"HEART_RATE" INTEGER NOT NULL ,

**Comment by techfarmer** [comment]
Thank you Vanous - this was helpful

**Comment by dj0001** [comment]
hi,

i am new here too. not an android dev, but i can use a bit of javascript here and there.

you can get data from the database by exporting it first in the GB app, this will create sqlite file called Gadgedbridge which you can then [save as csv](https://dj0001.github.io/miband3-selfie/dbtocsv.htm) in your computer

**Comment by MagicFab** [comment]
I've updated the documentation at https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Developer-Documentation with some more details on CSV export after DB export.

**Comment by IzzySoft** [comment]
Thanks @MagicFab – does that solve your issue so we can close it, @techfarmer?

**Comment by IzzySoft** [comment]
As "no answer" usually means "no problem", I'm closing this now. Yell if I was wrong 😉
