### ISSUE TITLE
huami devices: static auth key allows anyone to connect

### ISSUE THREAD

**Issue by debfx** [Freeyourgadget/Gadgetbridge#1308]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

Gadgetbridge uses a static key to pair with huami devices, see [InitOperation.getSecretKey()](https://github.com/Freeyourgadget/Gadgetbridge/blob/f513dad014b44a61a47bf103d3ec90a407ce6e4e/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/huami/operations/InitOperation.java#L81).
This method name has been chosen somewhat optimistically.

Once such a device is paired with Gadgetbridge anyone else can connect to it without the need to physically press a button on the device. The only restriction is that no other smartphone is actively connected to the device.

To reproduce:
Add the huami device on a second smartphone. Don't press the button on the device when it vibrates. Instead go back to the Gadgetbridge main screen. You will be able to connect to it.

Needless to say that this is a security issue.
I have verified with a Mi Band 3 that changing the key fixes the problem. Ideally Gadgetbridge would generate and store a random key for every device that is added.
Migrating existing users to a random key would be desirable but requires everyone to re-pair the device.

#### Your wearable device is:

Mi Band 3, but probably affects all huami devices

#### Your android version is:

not relevant to this bug

#### Your Gadgetbridge version is:

0.30.0 / git f513dad014b44a61a47bf103d3ec90a407ce6e4e

**Comment by danielegobbetti** [comment]
Do you know if changing the key requires the user to un-pair on the gadget first? Or is it "just" a matter of accepting the pairing with the new key?

**Comment by debfx** [comment]
As far as I can tell the Mi Band 3 doesn't have an un-pair functionality. It just stores the key of the last successful pairing (app sending AUTH_SEND_KEY and the user accepting it on the gadget).

I can confirm that adding the Mi Band 3 in Gadgetbridge works even when it pas paired with a different key before.

**Comment by danielegobbetti** [comment]
great, thanks for checking! Perhaps we might hash the configured username (or more fields of the user infos) and use that as a key.

**Comment by joserebelo** [comment]
Any reason not to use a random key? It seems better from a security perspective, since theoretically I could replicate a user's info on another device and connect to a foreign band, and also because it must be saved somewhere anyway, or changing the user info would require a re-pair.

**Comment by danielegobbetti** [comment]
I was thinking of something that could "survive" the export/import procedure (without adding an extra field to the exported data).

**Comment by ashimokawa** [comment]
I think this one is quite important, but I would need to do some research to implement it.

**Comment by ThomasWaldmann** [comment]
Some ideas:
- read len(key) from cryptographically secure random number generator, store this, use that as key
- kdf = key derivation function. if it takes more than one parameter, you either need to hardcode them (consider security then) or store them.
- use kdf(name | birthdate | ...) as key, hoping these are constant per user. optionally store key. note: not very secret, but better than constant hardcoded key.
- ask for a passphrase, store and use kdf(passphrase) as key. tell the user to remember passphrase well, as it will be required later again.
- maybe do not accept or warn about non-ascii passphrases / kdf input data.

**Comment by ThomasWaldmann** [comment]
Hmm, I tried to reproduce with my Amazfit BIP (1) and could not.

I switched off BT on the original smartphone and tried to discover on another smartphone: the bip did not show up in discovery.

**Comment by ThomasWaldmann** [comment]
Is this issue somehow related to #908 and especially that comment there?:

https://github.com/Freeyourgadget/Gadgetbridge/issues/908#issuecomment-353494651
