### ISSUE TITLE
Vibration support for firmware version >= 1.0.10.14

### ISSUE THREAD

**Issue by danielegobbetti** [Freeyourgadget/Gadgetbridge#131]
Hi all,

after some time, gadgetbrige now support for vibrations with the latest miband firmware. This is not yet published on fdroid, but I'd like anyone who can build the latest version from master (any commit after 18f952250a2fd910f1d8bd354f9dd2bec4175cdd ) to give it a try and report back. The leds on the miband should flash green while the band vibrates. It is possible to have them flashing red using the standard value for HIGH_ALERT. Right now this is not customisable, but it will be before the next release.

I actually find good that the standard BLE services/characteristics are now working on the miband.

**Comment by fignew** [comment]
Vibration now working well for me on 0.6.2 and 1.0.10.14

**Comment by danielegobbetti** [comment]
Thanks @fignew for confirmation, I am closing the issue.
