### ISSUE TITLE
generic notification instead of SMS when device is locked

### ISSUE THREAD

**Issue by sumiacani** [Freeyourgadget/Gadgetbridge#1313]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*If possible, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)! that might help identifying the problem.*

[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/2502354/gadgetbridge.2.log)

My issue is similar to [#994](https://github.com/Freeyourgadget/Gadgetbridge/issues/994) but it only occurs when the device is locked. Basically, when I receive an SMS through a third-party SMS app and the device is locked, a generic notification is pushed to my Mi Band 2 instead of a generic SMS. This does not occur when the device is unlocked. That is, I receive a proper SMS notification on my Mi Band 2 when the device is unlocked. I attempted to fix the issue myself by adding the application to the list in AppNotificationType.java and rebuild the apk but this did not fix the issue. The third-party SMS app is the Persona 5 IM messaging app and the app ID is 

> com.ngreenan.persona5imapp

I attached the logs above. The timestamp where I attempted to send a locked SMS notification is at 00:23:59. An unlocked SMS notification example is at 10:17:59. The blacklisted app can be ignored. It's the app I use to sync to my PC and when I perform actions, GB sends double notifications.

#### Your wearable device is:
Mi Band 2 Firmware 1.0.1.81
*Please specify model and firmware version if possible*

#### Your android version is:
8.1.0

#### Your Gadgetbridge version is:
0.30.0

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by danielegobbetti** [comment]
How are your settings wrt. notification privacy when screen is locked (Android system "Settings" -> "Security" -> "Lockscreen preferences")?

**Comment by sumiacani** [comment]
I have it set to show all notification content. The incorrect notification is only sent for the Persona 5 IM app. Everything else works fine. I have noticed something odd, though. If I blacklist Persona 5 IM app, I get a correct SMS notification. However, if I do that, I don't receive text notifications.

**Comment by sumiacani** [comment]
Well, it took a while but it looks like the newest update (0.32.0) fixes it. Thanks a bunch and I hope you guys continue working on this great app!
