### ISSUE TITLE
Add support for removal of some of the built-in apps (Pebble)

### ISSUE THREAD

**Issue by HalosGhost** [Freeyourgadget/Gadgetbridge#132]
Several of the built-in applications are not needed by everyone. For example, I have no intention of having my PTS be always connected to my phone. As a result, Notifications, Music, Calendar and even a couple others actually are not necessary for my use case.

Other projects have allowed some measure of modifying and recompiling the firmware to be rid of these applications, but they do not support the latest firmwares and are far less simple to use. Having this ability from GB's App Manager would be incredible!

**Comment by ashimokawa** [comment]
Thank you for your suggestion,
unfortunately it is not possible to remove the build-in applications from the pebble without patching the firmware. Also AFAIK the patched firmwares only remove the applications from the menus while they stay on the watch and do not free any byte of memory.
