### ISSUE TITLE
Czech translation missing in 0.31.0

### ISSUE THREAD

**Issue by vanous** [Freeyourgadget/Gadgetbridge#1326]
I have made sure CZ is 100% updated. It didn't unfortunately make it to 0.30 and now in 0.31.0 , CZ is missing completely. Checking by installation from f-droid.

**Comment by vanous** [comment]
Thank you very much for getting back.
I think i have tried all combinations. Normally, my phone is set to EN (US). Here is what i did:
1) set phone to CZ. Set GB to Auto. Quit QB, Start GB. Remains in EN.
2) set GB to Czech. Language now shows "Čeština" (CZ), but rest of interface is EN. Quit GB, start GB - remain the same.
3) set phone back to EN. Go to GB, set language to DE, ES, PL.... all languages → it always switches right away without any issue or GB restart needed.

When i go to GB menu → Change log → it shows Version 0.31.0

I tried getting the logs but anytime i do "share log" the app crashes. Some log lines are there, but nothing in particular about language.

Is there anything else i can try?

**Comment by vanous** [comment]
Here is the log file, if it helps, please. I don't mind HW IDs in there, i hope i haven't missed anything else personal/important...

thank you
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/2567227/gadgetbridge.log)

**Comment by ashimokawa** [comment]
This is fixed now. Thanks for reporting.

This fix will be in 0.31.2 or 0.32.0, whatever is next, but it did not make it into 0.31.1 which was already finalized and is in the fdroid build queue.

**Comment by vanous** [comment]
Nice, thank you very much!

**Comment by vanous** [comment]
Translation updated.

**Comment by ashimokawa** [comment]
Thanks, you don't have to announce translation updates, I  pull them in regularly and always just before a release ;)
