### ISSUE TITLE
GPX export bug (or GPS data reading bug)

### ISSUE THREAD

**Issue by supec** [Freeyourgadget/Gadgetbridge#1328]
Hi,
there is a bug in GPS data reading/export after fresh update of Amazfit BIP (actions like RUNNING. I need it to export it to STRAVA).
MiFit application updated firmware of my watch without asking yesterday.

GPS data seems to be shifted by tens of kilometers (but MIFIT displays the route correctly). 
(route after export is on map below and in TXT/XML file below)

Sometimes the route has correct shape (like on picture), but it is shifted from correct location (marked by blue color) by tens of kilometers.

Is there any solution to this problem? Should I try to return to previous firmware?

Thank You

![amazfit-bip-wrong-gpx](https://user-images.githubusercontent.com/43809413/48299211-5b3c3800-e4ca-11e8-9bd9-006257114f53.JPG)

[gadgetbridge-běh-2018-11-09T14_15_55+01_00.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/2568221/gadgetbridge-beh-2018-11-09T14_15_55%2B01_00.txt)

**Comment by ashimokawa** [comment]
Duplicate. Fixed in master, will be in 0.31.1
See #1324

**Comment by Bipinb183** [comment]
I am facing the same issue
![untitled](https://user-images.githubusercontent.com/46247137/50540539-b250b600-0bb9-11e9-9e27-74e461b51aa5.png)

Mifit is showing map correctly, but the map in gpx file of gadget bridge has moved and showing wrong 90 degrees map with correct shape and wrong location. Plz help, Thank you

**Comment by Bipinb183** [comment]
> I am facing the same issue
> ![untitled](https://user-images.githubusercontent.com/46247137/50540539-b250b600-0bb9-11e9-9e27-74e461b51aa5.png)
> 
> Mifit is showing map correctly, but the map in gpx file of gadget bridge has moved and showing wrong 90 degrees map with correct shape and wrong location. Plz help, Thank you

Update:   Downloaded the new version, its working smooth. Thanks a lot
