### ISSUE TITLE
[ERROR] constant disconnects after update to 0.31.0

### ISSUE THREAD

**Issue by rusty-genius** [Freeyourgadget/Gadgetbridge#1329]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Since the last update I get constant disconnects to my Pebble, even if my smartphone and my watch are directly next to each other

#### Your wearable device is:
Pebble Time Steel v4.3

#### Your android version is:
7.1.2

#### Your Gadgetbridge version is:
0.31.0

#### Log: ####
[20181110_135612547_b3f9_e78a5f03fc.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/2568409/20181110_135612547_b3f9_e78a5f03fc.txt)

**Comment by ashimokawa** [comment]
WTF? How often will I have to answer this?

**Comment by ashimokawa** [comment]
#1327
#1323
