### ISSUE TITLE
No data synced?

### ISSUE THREAD

**Issue by Spittie** [Freeyourgadget/Gadgetbridge#133]
Hi, me again.

Since yesterday afternoon, I don't see any more data coming from my Miband in Gadgetbridge.
A screenshot should explain this better than any words:
https://jii.moe/VyyUH5Vye.jpg

The logs of the last two days: https://jii.moe/EJ0eB54kl.log
The database: https://jii.moe/VJB3Sc4Je
Miband fimware: 1.0.10.11

In the database, everything after 1443540319 has 0 in every field.

I don't know if this is actually a bug in Gadgetbridge or if my Miband is just dying (:/).
Everything else seems fine tho (the band vibrates when I get a notification and show my progress when I do the "arm gesture").

**Comment by danielegobbetti** [comment]
Hi @Spittie , i just tried and the transfer was flawless for me (12 days worth of data).

What I don't like in your logs is the following:

```
21:25:36.728 [Binder_8] DEBUG n.f.g.s.d.m.o.FetchActivityOperation - activity data: length: 20, remaining bytes: 700
21:25:36.741 [Binder_8] DEBUG n.f.g.s.d.m.o.FetchActivityOperation - activity data: length: 20, remaining bytes: 680
21:25:36.758 [Binder_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 0000ff07-0000-1000-8000-00805f9b34fb
21:25:36.759 [Binder_8] DEBUG n.f.g.s.d.m.o.FetchActivityOperation - activity data: length: 20, remaining bytes: 660
21:25:36.783 [Binder_8] DEBUG n.f.g.s.d.m.o.FetchActivityOperation - activity data: length: 20, remaining bytes: 640
21:25:36.805 [Binder_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 0000ff07-0000-1000-8000-00805f9b34fb
21:25:36.806 [Binder_8] DEBUG n.f.g.s.d.m.o.FetchActivityOperation - activity data: length: 20, remaining bytes: 620
21:25:36.822 [Binder_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 0000ff07-0000-1000-8000-00805f9b34fb
21:25:36.823 [Binder_8] DEBUG n.f.g.s.d.m.o.FetchActivityOperation - activity data: length: 20, remaining bytes: 600
21:25:36.839 [Binder_8] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 0000ff07-0000-1000-8000-00805f9b34fb
```

The pattern you see on the last lines is the correct one, the one at the beginning not so much.

Nevertheless according to the log the band sent data until 21:25:
```
21:25:47.891 [Binder_A] INFO  n.f.g.s.d.m.o.FetchActivityOperation - total data to read: 0 len: 0 minute(s)
21:25:47.892 [Binder_A] INFO  n.f.g.s.d.m.o.FetchActivityOperation - TIMESTAMP: 29 Sep 2015 21:25:19 magic byte: 0
```
And if the fetched data was invalid it should be evident from the log.

**Comment by Spittie** [comment]
Seems like it was a band issue. I had the bad idea to try to reboot it, and now it doesn't work anymore :(
Hopefully Amazon will be helpful and change it, as I got it only a bunch of months ago.

**Comment by danielegobbetti** [comment]
Sorry for your band! I am closing the issue.

**Comment by cpfeiffer** [comment]
@Spittie FWIW, I experienced the same problem as you: after rebooting the bad, it wouldn't work *at all* anymore.

I put it into the freezer to empty the battery. After a few days, I took it out and started charging it. After a while the LEDs lit and now it works again. Firmware 1.0.9.14.

**Comment by Spittie** [comment]
@cpfeiffer Thanks for the tip, I tried it with my first faulty band and had no luck myself. For the second one, I think by now the battery should be empty (I left it alone for more than 50 days after all), but it still doesn't seems to charge.

I just got around contacting Amazon, and they said they'll refund my order if I return it. Now I just have to decide if I want to get another MIBand or something more expansive :)

**Comment by cpfeiffer** [comment]
If you don't use it, battery can last for months. I had 60+ days and it wasn't even empty when I charged it.

I had the band 3 days in the freezer and left it in the charger over night. Next morning the 3rd led was blinking, so it was still charging.
