### ISSUE TITLE
UI: move the find device button to the far right to make it less likely to hit it by accident 

### ISSUE THREAD

**Issue by xandro0777** [Freeyourgadget/Gadgetbridge#1330]
too close to the other buttons - and it is quite unpleasant if activated by accident while on your arm.

**Comment by vanous** [comment]
I think this issue was created right around the time when the new activity_controlcenterv2.xml was being used. Is this issue solved now and can it be closed?

thank you

**Comment by xandro0777** [comment]
> I think this issue was created right around the time when the new activity_controlcenterv2.xml was being used. Is this issue solved now and can it be closed?

the issue was created because I happened to hit the "find device" by accident. This is prettyy nasty if someone else wears the device and especially if that person is sleeping. Imho this is still something that should be improved.

At the time I have created the issue it would have been fairly easy to "fix" by moving the "find device" button to the far right.. since than the available space was used for something else so this solution won't work. Maybe require a double tap or confirmation dialog.. possibly optional?

**Comment by xandro0777** [comment]
Yes, I have 0.36. The button is all the way to the right - but as there are several more buttons than a few versions ago all the buttons now fill the entire row on my phone so its closely packed to the other buttons again.

There may well be a substantial improvement on devices with larger screens but nothing noticeable on a smaller phone.
