### ISSUE TITLE
Amazfit Bip - Firmware 1.1.5.04

### ISSUE THREAD

**Issue by FreeTheTech101** [Freeyourgadget/Gadgetbridge#1333]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

Once again confirming that the new firmware (60002) is safe to flash. There does not appear to be any updates to the resources or GPS files this time around though. Tested notifications, calls, and data syncing. I cannot comment on activities though, as I have not yet had the chance to go and do any.

#### Your wearable device is:

Amazfit Bip

#### Your android version is:

9.0

#### Your Gadgetbridge version is:

0.31.0

**Comment by ashimokawa** [comment]
Actually the official GPS firmware is now Mili_dth.gps which is a new version

**Comment by FreeTheTech101** [comment]
Based on the firmware.json file included in the latest APKs, 3.5.4 to 3.5.4.1 both have the same GPS version (15974,e61dd16,126) and firmware version. On the other hand, 3.5.3 (which still uses the old GPS file name) has version 9567,8b05506,0,0,0. 3.5.3. APK version 3.5.3 contains firmware version 1.1.5.02 for the device itself, where 3.5.4 to 3.5.4.1 contain firmware version 1.1.5.04 for the device itself. This would lead me to believe that there is no new GPS version, but I could be wrong.

**Comment by ashimokawa** [comment]
Assuming that 1.1.5.02 used 9567,8b05506,0,0,0 and that 1.1.5.04 used 15974,e61dd16,126, I would say that looking from 1.1.5.02 to 1.1.5.04 there is a new GPS version ;)

Anyway keep in mind that 3.5.4 is newer than 3.5.4.1 and stable MiFit releases have the format x.y.z while betas have x.y.z.X. So x.y.z.X releases lead to the final version x.y.z.
