### ISSUE TITLE
Regression: k9 notifications messed up

### ISSUE THREAD

**Issue by IzzySoft** [Freeyourgadget/Gadgetbridge#1336]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
For about 2 versions now, notifications are messed up. They always contain some useless "x notifications" messages. Example:

1. "5 notifications"
1. "4 notifications"
1. (real notification here)
1. end (no more notifications)

Numbers vary. Sometimes, the highest number indeed matches the number of notifications, if you count in those "false notifications". But the numbers don't always match. Usually those are notifications created by K-9 Mail – but I'm not sure whether it's restricted to those.

Additionally, dismissing a notification on the watch no longer dismisses it on the Android device (like we had it already with #975).

#### Your wearable device is:
Pebble Time Steel with the last firmware

#### Your android version is:
7.1.1 (LOS 14.1 on a BQ Aquaris X5 Plus)

#### Your Gadgetbridge version is:
0.31.1

**Comment by ashimokawa** [comment]
In master, group summaries (X messages) are now ignored, why you still miss emails - I have no idea.
Would need a log :/

**Comment by IzzySoft** [comment]
As I wrote you in chat: I didn't check if there are really notifications lost, ofr if the summaries are simply "nuts". I've sent you an (unsanitized) log to check with. Contains notifications for multiple mail accounts which fired almost all at once (due to the k9 poll intervall; I'm not using IMAP idle as for most accounts checking once per hour is sufficient for me).

Waiting for the next version to check if the issue is gone, and will report back then. Thanks for fixing it that fast!

**Comment by ashimokawa** [comment]
The summary notifications are not generated by us, they come in like that from k9. I have no idea why that are like that. 

Anyway I am closing this since I addressed the problems in master.

**Comment by IzzySoft** [comment]
Thanks again for your quick action, @ashimokawa – domo arigato 😃!
