### ISSUE TITLE
can you adjust the brightness of mi band 2?

### ISSUE THREAD

**Issue by xjtuecho** [Freeyourgadget/Gadgetbridge#1341]
Many Mi band 2 users complain about the display brightness low problem.
The OLED controller  of mi band 2 is SSD1306. It has 256-step brightness control. But there are no interface on the app. can you adjust the brightness of mi band 2 via custom firmware?

**Comment by ashimokawa** [comment]
No.
This is not a custom firmware project.

**Comment by xjtuecho** [comment]
OK. Thank you all the same.
