### ISSUE TITLE
Mi Band 3 NFC - Working packages: 46003 & 7225

### ISSUE THREAD

**Issue by juherr** [Freeyourgadget/Gadgetbridge#1352]
Hi,

I've just flashed to following packages on my Mi Band 3 NFC and the app asked me for notifying you that it is working:
* Firmware 1.6.0.6 - French: 46003
* Resources v46: 7225

Thanks for your hard work 👍

**Comment by ashimokawa** [comment]
Oh cool. Any idea what NFC is for on the band? And what is your hardware revision?

**Comment by juherr** [comment]
Currently, the NFC is only working in China. 
You are supposed to be able to add some transport cards via Mi Fit and the band will replace the rfid card. But the feature is blocked overseas. Maybe Gadgetbridge will be able to unlock the feature.

There is an additional beta feature which allows the simulation of access cards. But this feature is currently blocked too.

HW: V0.20.131.33
Model: XMSH06HM
SKU: MGW4040CN

**Comment by ashimokawa** [comment]
@juherr 
At least I could probably enable the NFC menu I guess.

Can you please report the hardware revision reported by Gadgetbridge (press the three dots in the device card after connecting)

**Comment by wwwjava** [comment]
Mine is the same - fw: 1.6.0.6 and hw: V0.20.131.33. I would like to use it like NFC reader except for paying.

**Comment by juherr** [comment]
@ashimokawa 
> Can you please report the hardware revision

HW: V0.20.131.33

**Comment by wwwjava** [comment]
You mean this? CMIIT ID:2018DP1659

**Comment by OrcaXS** [comment]
HW: V0.20.131.33, FW v1.6.0.10 seems to be working as well.

**Comment by wwwjava** [comment]
Maybe will update from 1.6.0.6 to 1.6.0.10

**Comment by ashimokawa** [comment]
Closing this, I have whitelisted 1.7.0.4 and 1.6.0.6 gives me a different checksum

**Comment by rdorsch** [comment]
Did anybody try the latest FW from Mi Fit 4.0.2 (has a different md5sum here)?

**Comment by vanous** [comment]
Not on the NFC version, but on the normal one, 
https://github.com/Freeyourgadget/Gadgetbridge/commit/d2988f987f6f41b3da8aadbd53a53d86d92cb213
