### ISSUE TITLE
Mi Band 3 firmware whitelist 10023 and 7225

### ISSUE THREAD

**Issue by RyuzakiKK** [Freeyourgadget/Gadgetbridge#1353]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

![photo_2018-12-04_21-46-11](https://user-images.githubusercontent.com/3227973/49471773-09a77480-f80e-11e8-97af-d3aa27cf344c.jpg)
![photo_2018-12-04_21-46-08](https://user-images.githubusercontent.com/3227973/49471774-09a77480-f80e-11e8-831c-186774b9bed3.jpg)
![photo_2018-12-04_21-45-58](https://user-images.githubusercontent.com/3227973/49471775-09a77480-f80e-11e8-86e8-11ece80a4de3.jpg)

I flashed the 2.2.0.12 firmware (fw and res) and it works as expected. No issues so far.

**Comment by ashimokawa** [comment]
Thanks, will whitelist later, also works here
