### ISSUE TITLE
The "Find Phone" activity should ring continuously and turn the screen on

### ISSUE THREAD

**Issue by selurvedu** [Freeyourgadget/Gadgetbridge#1354]
#### Before requesting a new feature, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
When I activate the "Find Phone" feature on my Mi Band 3, my phone emits two really short beeps — one on activation and one on deactivation of the "Find Phone" screen. This also works if you cancel the search on Mi Band. The screen does not light up if it was locked.

Beeps sound exactly like those that you can hear when pressing the Volume Up or Volume Down buttons on the phone.

I think Gadgetbridge should play some kind of continuous ringtone, since one short beep is not much help in finding a lost phone. It would also be nice if GB could turn the screen on, this may help when the phone is in the Do Not Disturb mode and/or all sounds are silenced.

I also noticed that pressing the "Found it" button in GB does not deactivate the search screen on Mi Band.

#### Your wearable device is:

Mi Band 3 (without NFC) XMSH05HM
HW: V0.18.3.2
FW: 1.5.0.2

#### Your Android version is:

6.0.1 (LineageOS 13)

#### Your Gadgetbridge version is:

0.31.3

**Comment by ashimokawa** [comment]
@selurvedu 
> I think Gadgetbridge should play some kind of continuous ringtone, since one short beep is not much help in finding a lost phone.

This is exactly what we do and it works here. We raise the volume, play the default ringtone and lower it again.

> I also noticed that pressing the "Found it" button in GB does not deactivate the search screen on Mi Band.

Yes, that is not yet supported if I remember correctly

**Comment by selurvedu** [comment]
> This is exactly what we do and it works here.

Huh. I wonder why playRingtone() fails for me. I will post back as soon as I find out.

That silently passing `catch` looks quite suspicious, so I will start from there: https://github.com/Freeyourgadget/Gadgetbridge/blob/5644ae592557cbd20b2cc21ef566b96a70e76b06/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/FindPhoneActivity.java#L96-L103

**Comment by selurvedu** [comment]
@ashimokawa, apparently it was a ROM issue. It works correcrlt on an AOSP-based Android Pie ROM.
