### ISSUE TITLE
Not delete devices

### ISSUE THREAD

**Issue by shiggyzam** [Freeyourgadget/Gadgetbridge#1360]
20:12:37.694 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.31.3
20:12:41.939 [main] INFO  n.f.g.d.AbstractDeviceCoordinator - will try to delete device: Mi Band 3
20:12:41.946 [main] INFO  n.f.g.d.AbstractDeviceCoordinator - device to delete not found in db: Device Mi Band 3, CB:36:D7:FB:D4:B5, Nepřipojeno
20:12:45.045 [main] INFO  n.f.g.d.AbstractDeviceCoordinator - will try to delete device: Mi Band 3
20:12:45.049 [main] INFO  n.f.g.d.AbstractDeviceCoordinator - device to delete not found in db: Device Mi Band 3, CB:36:D7:FB:D4:B5, Nepřipojeno
20:12:46.144 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
20:12:46.164 [main] INFO  n.f.g.s.b.BtLEQueue - Attempting to connect to Mi Band 3
20:12:46.167 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Queue Dispatch Thread started.
20:12:46.180 [main] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: CONNECTING
20:12:46.223 [Binder:24635_2] DEBUG n.f.g.s.b.BtLEQueue - connection state change, newState: 2 (success)
20:12:46.224 [Binder:24635_2] INFO  n.f.g.s.b.BtLEQueue - Connected to GATT server.
20:12:46.225 [Binder:24635_2] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: CONNECTED
20:12:46.226 [Binder:24635_2] INFO  n.f.g.s.b.BtLEQueue - Attempting to start service discovery
20:12:46.700 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
20:12:47.222 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
20:12:47.265 [Binder:24635_2] DEBUG n.f.g.s.d.h.a.AmazfitBipSupport - discovered supported service: Generic Access: 00001800-0000-1000-8000-00805f9b34fb
20:12:47.266 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Device Name: 00002a00-0000-1000-8000-00805f9b34fb
20:12:47.267 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Appearance: 00002a01-0000-1000-8000-00805f9b34fb
20:12:47.268 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Peripheral Preferred Connection Parameters: 00002a04-0000-1000-8000-00805f9b34fb
20:12:47.269 [Binder:24635_2] DEBUG n.f.g.s.d.h.a.AmazfitBipSupport - discovered supported service: Generic Attribute: 00001801-0000-1000-8000-00805f9b34fb
20:12:47.270 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Service Changed: 00002a05-0000-1000-8000-00805f9b34fb
20:12:47.271 [Binder:24635_2] DEBUG n.f.g.s.d.h.a.AmazfitBipSupport - discovered supported service: Device Information: 0000180a-0000-1000-8000-00805f9b34fb
20:12:47.272 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Serial Number String: 00002a25-0000-1000-8000-00805f9b34fb
20:12:47.273 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Hardware Revision String: 00002a27-0000-1000-8000-00805f9b34fb
20:12:47.274 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Software Revision String: 00002a28-0000-1000-8000-00805f9b34fb
20:12:47.274 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: System ID: 00002a23-0000-1000-8000-00805f9b34fb
20:12:47.275 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: PnP ID: 00002a50-0000-1000-8000-00805f9b34fb
20:12:47.276 [Binder:24635_2] DEBUG n.f.g.s.d.h.a.AmazfitBipSupport - discovered supported service: (Propr: Xiaomi Weight Service): 00001530-0000-3512-2118-0009af100700
20:12:47.277 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00001531-0000-3512-2118-0009af100700
20:12:47.278 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00001532-0000-3512-2118-0009af100700
20:12:47.279 [Binder:24635_2] DEBUG n.f.g.s.d.h.a.AmazfitBipSupport - discovered supported service: Alert Notification Service: 00001811-0000-1000-8000-00805f9b34fb
20:12:47.280 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: New Alert: 00002a46-0000-1000-8000-00805f9b34fb
20:12:47.281 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Alert Notification Control Point: 00002a44-0000-1000-8000-00805f9b34fb
20:12:47.282 [Binder:24635_2] DEBUG n.f.g.s.d.h.a.AmazfitBipSupport - discovered supported service: Immediate Alert: 00001802-0000-1000-8000-00805f9b34fb
20:12:47.284 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Alert Level: 00002a06-0000-1000-8000-00805f9b34fb
20:12:47.285 [Binder:24635_2] DEBUG n.f.g.s.d.h.a.AmazfitBipSupport - discovered supported service: Heart Rate: 0000180d-0000-1000-8000-00805f9b34fb
20:12:47.286 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Heart Rate Measurement: 00002a37-0000-1000-8000-00805f9b34fb
20:12:47.287 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Heart Rate Control Point: 00002a39-0000-1000-8000-00805f9b34fb
20:12:47.288 [Binder:24635_2] DEBUG n.f.g.s.d.h.a.AmazfitBipSupport - discovered supported service: Unknown Service: 0000fee0-0000-1000-8000-00805f9b34fb
20:12:47.289 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Current Time: 00002a2b-0000-1000-8000-00805f9b34fb
20:12:47.290 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00000001-0000-3512-2118-0009af100700
20:12:47.291 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00000002-0000-3512-2118-0009af100700
20:12:47.292 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00000003-0000-3512-2118-0009af100700
20:12:47.293 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Peripheral Preferred Connection Parameters: 00002a04-0000-1000-8000-00805f9b34fb
20:12:47.295 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00000004-0000-3512-2118-0009af100700
20:12:47.296 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00000005-0000-3512-2118-0009af100700
20:12:47.297 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00000006-0000-3512-2118-0009af100700
20:12:47.298 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00000007-0000-3512-2118-0009af100700
20:12:47.299 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00000008-0000-3512-2118-0009af100700
20:12:47.300 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00000010-0000-3512-2118-0009af100700
20:12:47.301 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00000020-0000-3512-2118-0009af100700
20:12:47.303 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 0000000e-0000-3512-2118-0009af100700
20:12:47.304 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 0000000f-0000-3512-2118-0009af100700
20:12:47.305 [Binder:24635_2] DEBUG n.f.g.s.d.h.a.AmazfitBipSupport - discovered supported service: Unknown Service: 0000fee1-0000-1000-8000-00805f9b34fb
20:12:47.306 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 00000009-0000-3512-2118-0009af100700
20:12:47.307 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 0000fedd-0000-1000-8000-00805f9b34fb
20:12:47.308 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 0000fede-0000-1000-8000-00805f9b34fb
20:12:47.309 [Binder:24635_2] INFO  n.f.g.s.d.h.a.AmazfitBipSupport -     characteristic: Unknown Characteristic: 0000fedf-0000-1000-8000-00805f9b34fb

**Comment by Elwood21** [comment]
Same here with amzfit bip. same log with the error "not found in db"

**Comment by ashimokawa** [comment]
That is because you still have the devices paired in Android settings.
Gadgetbridge unpairs them if Bluetooth is enable else it cannot.

I think we should not display paired devices any more that are not in our database.
@danielegobbetti 
@cpfeiffer 
Objections?

**Comment by danielegobbetti** [comment]
@ashimokawa fine by me

**Comment by shiggyzam** [comment]
Nice. THX. 😃
