### ISSUE TITLE
CRC16 Checksum for MiBand

### ISSUE THREAD

**Issue by vinaynmy** [Freeyourgadget/Gadgetbridge#1362]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Hi, everyone how to generate checksum for the firmware? How does the firmware checksum works for Miband 3? I am trying to upload the firmware from PC, wrote my own python code, but stops at firmware checksum. Somebody please help how does checksum works or how it is generated?

#### Your wearable device is:

MiBand3

**Comment by danielegobbetti** [comment]
please use the search functionality
