### ISSUE TITLE
Not printable characters

### ISSUE THREAD

**Issue by fvasco** [Freeyourgadget/Gadgetbridge#1368]
Some Italian accented vowels are displayed as unknown (a square) characters, ie: à è é ì ò ù

The text is pretty hard to understand, looks like the hangman game (ie: Hell� W�rld).
It is simple translate these characters to printable ones

* `à` -> `a'`
* `è` -> `e'`
* `é` -> `e'`

and so on, or at least remove the accent (à -> a).

I don't know the project but I am able to develop on Java/Kotlin, can I help you?

Finally, this solution can be applied also for emoji (ie: 🙂 -> `:-)`, 😀 -> `:-D`) 

#### Your wearable device is:

Amazfit Bip Watch
FW: 1.1.2.05
HW: V0.11.19.5

#### Your android version is:

Xiaomi Mi A2 Lite, Android One 8.1.0

#### Your Gadgetbridge version is:

0.31.3 is the first entry in the Change Log

**Comment by ashimokawa** [comment]
Turn on transliteration, it does exactly what you want.

**Comment by fvasco** [comment]
Great Scott! 
I missed it in generic configuration.
Please update the wiki adding Italian support, I checked it and it is ok.

Moreover please consider adding a -limited- emoji support.

Thanks1
