### ISSUE TITLE
Amazfit Cor wiki update

### ISSUE THREAD

**Issue by b16r05** [Freeyourgadget/Gadgetbridge#1376]
Amazfit Cor update

Got Amazfit Cor :-)
Hardware version: V0.12.6.1
Came with fw: 1.0.6.65. I wanted to update; I had no idea what the fsck I was doing. 

Flashed com.xiaomi.hm.health_3.5.5-6585_minAPI19(armeabi-v7a)(nodpi)_apkmirror.com
Mili_tempo.fw; fw version: 1.2.7.20
Mili_tempo.res; Resources version: RES 69

GadgetBridge version: latest
LineageOS version: 16

So, my question was whether the Cor is affected by the deep sleep bug [1], just as the Bip, MiBand and others? 

[1] deep sleep detection does not work properly with Gadgetbridge, see https://github.com/Freeyourgadget/Gadgetbridge/issues/686#issuecomment-343773224"???
 
So far, been just one day, after syncing, deep sleep is showing, looks good, but not sure if it is accurate.

**Comment by b16r05** [comment]
Wiki has been updated. Deep sleeps is working as usual, fine, on Mi Band 3.

**Comment by ashimokawa** [comment]
@b16r05 
There is no deep sleep bug, but we miss postprocessing of the data to "correctly" recognize deep sleep. All new Xiaomi/Huami devices only save "hints" or something to the minute data and then it is post-processed. That makes sense when a device is too weak to do it by itself (the pebble does it on-device and only in the morning, when it is sure your sleep session is over)
