### ISSUE TITLE
Pulldown to sync

### ISSUE THREAD

**Issue by utack** [Freeyourgadget/Gadgetbridge#138]
In the main menu with the connected devices the "pulldown" move known from apps like email clients could be used to trigger a sync of all devices.

**Comment by cpfeiffer** [comment]
Right, good idea. There is a libpulltorefresh or something like that, that we might use.

**Comment by cpfeiffer** [comment]
For reference: https://developer.android.com/reference/android/support/v4/widget/SwipeRefreshLayout.html
