### ISSUE TITLE
Pebble Time: Music App Crashes Gadgetbridge on Multiple Actions

### ISSUE THREAD

**Issue by SpecialBomb** [Freeyourgadget/Gadgetbridge#1387]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
When trying to control music on the Pebble music app, using any control, such as skip forward/back a track, and play/pause, causes the Gadgetbridge app to crash. However, volume seems to work fine. The song information also shows up without a problem. When no song is playing, it still crashes Gadgetbridge.

*If possible, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)! that might help identifying the problem.*
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/2734857/gadgetbridge.log)

#### Your wearable device is:
I am using a Pebble Time, with version 4.3 firmware (snowy_dvt hardware)
*Please specify model and firmware version if possible*

#### Your android version is:
Android 8.0.0, Samsung S8
#### Your Gadgetbridge version is:
Gadgetbridge Version 0.31.3

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by IzzySoft** [comment]
You can do so in Android Settings. On Android 7 (I don't have 8, but hope it's in the same place there):

* Go to *Settings › Apps*
* tap the app you need to adjust permissions for
* tap the "permissions" entry
* flip the toggle for the permission you want to change

Just meant as a work-around. GB should ask for this permission if needed – but until that's fixed, the above gets you running :wink:

**Comment by SpecialBomb** [comment]
Well, the problem is that it's not a permission that is listed. I have
already attempted it. I think it only lists permissions that the app
requests.

**Comment by IzzySoft** [comment]
Yes, that's correct. So my assumption that the "initial request" somehow failed was wrong. Thanks for clarification! That's up to "the devs" then.

**Comment by SpecialBomb** [comment]
I could try adding in the request in a custom fork and see if that works.
Then, I can make a pull request and see if the devs merge it. It's super
easy apparently.

**Comment by IzzySoft** [comment]
Funny that I never encountered that issue. It should be present at least starting with Android 6 then. I rarely use my Android to play music – but I'm pretty sure the last time was not longer ago than Android-6 being on my device.

Yes, please try if you can. Not sure if it's relevant, but maybe also add the music app you're using on your Android device. Trying a different one might not be a bad idea either.

**Comment by SpecialBomb** [comment]
I've tried a few, all fail.

**Comment by SpecialBomb** [comment]
Also, where should I start to learn how to build/compile/whatever android
applications so I can attempt this?

**Comment by SpecialBomb** [comment]
okay, I just realized whats happening.

The actual media control permission is only allowed for second and firsy
party apps. This also explains why my pebble was also not recieving
notifications; gadgetbridge is a third party app and cannot read them.

The only way I can get this to work, im assuming, is jailbreaking my phone
so I can allow permissions for any app.

**Comment by SpecialBomb** [comment]
Alright, finally, after installing the unofficial version of gadgetbridge
off the playstore, controling media works. At this point, I'd like to ask
if it's possible to create an official release on the play store so this
can work on most android devices.

**Comment by IzzySoft** [comment]
What does having the app on Playstore to do with it? My device doesn't even have GApps. And we purposly decided against having the app on Play (search the issues, a huge discussion took place on this topic).

**Comment by SpecialBomb** [comment]
I have no idea. I searched the actual permission on the android development
website. It stated that MEDIA_CONTENT_CONTROL can not allow 3rd party apps
to use it. I originally installed it off of the apk file, which is
considered 3rd party. By getting the unofficial version on the playstore,
im guessing theres some kind of certificate proving it to be a second party
app, allowing it to access the permission.

However, I know nothing about android, im pulling all of this out my butt
lol.

Whats interesting though is that the unofficial version crashes when I try
to change the volume. I think its a good sacrifice at the moment lol.

**Comment by IzzySoft** [comment]
Just to clarify: Apps installed from Playstore are also 3rd party apps. 1st party is what's signed with the same key as the ROM, 2nd party would mean other system apps.

According to my permission list, [`MEDIA_CONTENT_CONTROL`](https://android.izzysoft.de/catmin/applists/perms#MEDIA_CONTENT_CONTROL) uses protection level "system" – which fits. So no matter if you install from Play or F-Droid, the app still remains 3rd party. And regardless of where you installed it from, it only can access that permission if it's made a system app.

Apart from that, I don't thing GB would need that permission (unless there's some bug lurking). Whenever I tried – and that's up to Android 7 – I was able to pause/resume or skip via my Pebble Time Steel just fine. And no, I didn't made GB a system app.

So why it works with the unofficial Play version is beyond me. Could you compare the permissions requested by that and the official version? Is there a difference?

**Comment by SpecialBomb** [comment]
From the permission screens, there is no difference...

also when I reinstalled the apk to compare permissions it started working
properly.

I also just realized that I did not allow notification access the first
time I installed, that was dumb of me.

Maybe thats correlated? Ill turn it back off and see if it crashes again.

**Comment by SpecialBomb** [comment]
Hoo boy.

Yeah, that was the cause x.x

Sorry for wasting your time lmao, if anything should be learned here, I
should really stay on my own projects on github, lest developers get
distracted by my ramblings.

**Comment by IzzySoft** [comment]
*LOL* I'm not one of the devs, just another (enthusiast) user. And yeah, no dice without notification access. Though that shouldn't lead to a crash. So after all, you might have discovered a bug.

@ashimokawa @danielegobbetti @cpfeiffer could one of you please check if there's some exception handler missing?

**Comment by SpecialBomb** [comment]
And, I learned a little about android! \o/
