### ISSUE TITLE
Visually clarify the Activity screen is slidable

### ISSUE THREAD

**Issue by utack** [Freeyourgadget/Gadgetbridge#139]
When in the activity screen it is not visible it can slide left and right.
Took me quite a while to find it, probably others too?

**Comment by cpfeiffer** [comment]
Yes, good point. I think I tried using a tabbar for this a long time ago, but it didn't work out back then. I'll have a look again.

**Comment by cpfeiffer** [comment]
This is basically fixed, albeit not perfect. There seems to be a bug in the tabbar that loses the labels when the layout changes (happens when swiping to/from the Live Activity tab). To be fixed.
