### ISSUE TITLE
Database can't be accessed after viewing device alarms with Mi Band 3 on 0.32.0

### ISSUE THREAD

**Issue by AuroraWright** [Freeyourgadget/Gadgetbridge#1390]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*If possible, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)! that might help identifying the problem.*
Going to the (on-device) alarm window and leaving it renders the database inaccessible from the app (syncs never succeed, going to the activity window complains about the database being inaccessible). Only way to fix this is terminating Gadgetbridge. This didn't happen with a self-compiled build from 2 weeks ago (not sure which commit introduced this behavior though). I also tested wiping all Gadgetbridge data and the problem still reoccurs after pairing again.
#### Your wearable device is:
*Please specify model and firmware version if possible*
Mi Band 3

#### Your android version is:
Stock 9.0 (Pixel 2 XL)
#### Your Gadgetbridge version is:
0.32.0 (self-compiled)

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
Were did you get 0.32.0 from?

**Comment by IzzySoft** [comment]
@ashimokawa 

> 0.32.0 (self-compiled)

You've already tagged that :wink:

**Comment by cpfeiffer** [comment]
Can you please name the commit which you compiled? And with "on device alarm window", you mean pressing the little alarm icon on the mi band 3 card in Gadgetbridge's main activity, right? And leaving that activity right away without configuring an alarm?

**Comment by cpfeiffer** [comment]
I found it, thanks for the report!

**Comment by AuroraWright** [comment]
@ashimokawa I compiled the 0.32.0 tag myself
@cpfeiffer it was https://github.com/Freeyourgadget/Gadgetbridge/commit/5b4fd32ac192b6732a6559c9c8ffe8f9b9d137b6 . And yes, you're correct. Just clicking on the alarm icon, going back without doing anything, and clicking on the activity icon shows the "no data" error (followed by "can't access database" after a while)

**Comment by cpfeiffer** [comment]
0.32.1 is already tagged and we're waiting for it to be published. For the time being, don't open the alarms screen to avoid this issue.

**Comment by b16r05** [comment]
Anyone try 0.32.1 yet? Are things back to normal? Database accessible?

**Comment by AuroraWright** [comment]
It is back to normal, for the meantime you can kill Gadgetbridge and avoid opening the alarms window.

**Comment by vanous** [comment]
I had the same issue, (0.32 from f-droid) , after killing gadgedbridge all good and upon opening alarms second time, no issue experienced. But, there was a reason why i went to alarms - for whatever reasons, touch on my MiBand3 didn't work and for example triggering "Find lost device" from the phone resulted in one short vibration of the band and quick "Gadgedbridge" calling message on the band which disappeared immediately. Now all works and i just found this pinned issue. It seems there was something strange happening with updating (today) to 0.32 .
