### ISSUE TITLE
Notifications from Delta Chat is not shown on Mi and Amazfit devices

### ISSUE THREAD

**Issue by MMurzik** [Freeyourgadget/Gadgetbridge#1395]
#### Before opening an issue please confirm the following:
- [X ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Notifications from Delta Chat is not shown neither on Amazfit Bip nor on Mi Band 2, but all Pebble devices show it perfectly when connected to Gadgetbridge.
Delta Chat is FLOSS messenger that works through ordinary e-mail 
https://f-droid.org/app/com.b44t.messenger
https://delta.chat

#### Your android version is:

Android 8.1.0, LineageOS 15.1

#### Your Gadgetbridge version is: 0.32.1

Log says:
22:35:49.207 [main] INFO  n.f.g.e.NotificationListener - Processing notification 1530904327 age: 85 from source com.b44t.messenger with flags: 529
22:35:49.215 [main] INFO  n.f.g.e.NotificationListener - Not forwarding notification, FLAG_GROUP_SUMMARY is set and no wearable action present. Notification flags: 529

Can an option be added to Gadgetbridge to manually "whitelist" all notofications from problematic applications?

**Comment by cpfeiffer** [comment]
That would be very weird. If Gadgetbridge is able to send the notification to Pebble devices, they should arrive just fine on other devices as well. The NotificationListener does not care (or know) which device will receive it. So with your log excerpt "Not forwarding notification" Pebbles wouldn't get anything either.

**Comment by MMurzik** [comment]
Delta Chat developers updated their app, so notifications already worked!
