### ISSUE TITLE
Calendar Notifications not sent by GB

### ISSUE THREAD

**Issue by gadgetguy08** [Freeyourgadget/Gadgetbridge#1397]
#### Before opening an issue please confirm the following:
- [X ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:  Calendar Notifications not sent by GB
*In case of a bug, do not forget to attach logs!*

#### Your wearable device is:
Pebble Time
FW v4.3

*Please specify model and firmware version if possible*

#### Your android version is:
8.1

#### Your Gadgetbridge version is:
0.32.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

ONE calendar notification is received after a reboot or restart of Gadgetbridge, but after that NO calendar notifications are received until the next reboot/restart.

Other notifications (mail, tasker, phone calls, etc.) all notify properly on either Pebble.
Phone receives all calendar notifications properly.

Here are logs illustrating this:   
Timeline: 
16:08 Gadgetbridge re-started
16:10 First calendar notification sent to phone and Pebble
16:14 Next calendar notification sent to phone, not to Pebble
16:15 Next calendar notification sent to phone, not to Pebble

Logcat has these messages about GB:
01-19 16:08:41.938 D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService(12117): Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.add_calendarevent
01-19 16:08:42.068 I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol(12117): BLOBDB: success (token 12108)
01-19 16:10:00.456 I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener(12117): Processing notification 1547932201 age: 1547932200456 from source ws.xsoh.etar with flags: 129
01-19 16:10:00.481 D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService(12117): Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
01-19 16:10:00.887 I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol(12117): BLOBDB: success (token 20377)
01-19 16:14:00.411 I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener(12117): NOT processing notification, already sent newer notifications from this source.
01-19 16:15:00.268 I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener(12117): NOT processing notification, already sent newer notifications from this source.

GB Log shows this:
16:08:41.602 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.delete_calendarevent
16:08:41.677 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - BLOBDB: success (token 30993)
16:08:41.714 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.delete_calendarevent
16:08:41.803 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - BLOBDB: success (token 9483)
16:08:41.825 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.add_calendarevent
16:08:41.933 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - BLOBDB: success (token 42497)
16:08:41.938 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.add_calendarevent
16:08:42.068 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - BLOBDB: success (token 12108)
16:10:00.456 [main] INFO  n.f.g.e.NotificationListener - Processing notification 1547932201 age: 1547932200456 from source ws.xsoh.etar with flags: 129
16:10:00.480 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
16:10:00.887 [Thread-2] INFO  n.f.g.s.d.p.PebbleProtocol - BLOBDB: success (token 20377)
16:14:00.411 [main] INFO  n.f.g.e.NotificationListener - NOT processing notification, already sent newer notifications from this source.
16:15:00.268 [main] INFO  n.f.g.e.NotificationListener - NOT processing notification, already sent newer notifications from this source.

**Comment by danielegobbetti** [comment]
Thanks for the detailed information!

Can you please add the information about the start/end time (and date) of these 3 events? The timestamp of the first one according to the log is ``1547932200456``, which means ``GMT: Saturday, January 19, 2019 9:10:00 PM``, and I am wondering we are picking the wrong timing info from the notification in case of etar. Thanks

**Comment by gadgetguy08** [comment]
Test 1 was scheduled for Jan. 19 at 16:15 - 16:30 EST  (New York time or 21:15 - 21:30 GMT/UTC).
It was set to alarm 5 minutes prior -- 16:10 -- and did on the phone and watch since GB had just been restarted.
I reset the alarm to 1 minute prior -- 16:14 -- which alarmed on the phone but not on the Pebble.
I also added a second event, Test 2 for 16:20 - 16:30 with a 5 minute prior alarm.  That also alarmed on the phone but not on the watch.

**Comment by rajeevn1** [comment]
The same issue happens with google calendar, so this is not specific to etar.

Looking at the age in log of 1547932200456, implies that notification.when is zero.  If notification.when is zero for all calendar events- then the bug will manifest itself by just sending the 1st event to the gadget and filtering out all others because of the less-than-or-equal check for repeat filtering.
