### ISSUE TITLE
Fetch sleep quality and sleep time from the miband directly.

### ISSUE THREAD

**Issue by Haridasan** [Freeyourgadget/Gadgetbridge#1407]
Hi guys,
Mi band is calculating the sleep quality(like Deep sleep, light sleep, REM) and the time slept within the band. Is there a way (like reading a characteristic of band that provides those data) to get that details. If you guys have any idea in this please let me know, waiting for your reply...

**Comment by ashimokawa** [comment]
Those are postprocessed data from mi dit. It is not in the Band.

**Comment by LuccoJ** [comment]
I don't know what you mean by "under which characteristic". Sleep quality and REM times are simply not available in the band. The application Mi Fit calculates them, and we don't know how.

If you simply want to get the sleep times from Gadgetbridge, you can export a SQLite file from Gadgetbridge. You will find a MI_BAND_ACTIVITY_SAMPLE table in it, and the column RAW_KIND will contain various numbers: 0x70 will correspond to sleep, and maybe 0x7b also. The data are sampled once a second, with the column TIMESTAMP providing the Unix time.

More infomation [here](https://github.com/Freeyourgadget/Gadgetbridge/issues/686#issuecomment-399711604) and [here](https://github.com/Freeyourgadget/Gadgetbridge/issues/1030#issue-306265872).
