### ISSUE TITLE
Documentation update New Device Tutorial

### ISSUE THREAD

**Issue by jfgreffier** [Freeyourgadget/Gadgetbridge#1409]
#### Before reporting a bug, please confirm the following:
- [ X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
The New Device Tutorial wiki page needs to be completed for the Discovery part. The manufacturer name seems mandatory.

I have modification suggestion to clarify it.
See repo https://github.com/jfgreffier/Gadgetbridge-wiki
More precisely, my suggesiton are in this commit https://github.com/jfgreffier/Gadgetbridge-wiki/commit/a0aafcfe5f50dfdbd606f85dca6d80884a130947

**Comment by jfgreffier** [comment]
Hi,
I did register on codeberg.org, it seems there are no easy way to edit the wiki.

I created a fork of the wiki repo, you can review the changes and merge it
https://codeberg.org/jfgreffier/Gadgetbridge-wiki.git

**Comment by ashimokawa** [comment]
Wow it really seems to be impossible to enable wiki write access to anyone, but gitea which codeberg runs, will support it soon according to their issue tracker...

**Comment by ashimokawa** [comment]
@jfgreffier 
Can you try again on codeberg.org? It might work now

**Comment by jfgreffier** [comment]
It's done! Thanks!
