### ISSUE TITLE
How to reach device dependent configuration screen

### ISSUE THREAD

**Issue by giwu37** [Freeyourgadget/Gadgetbridge#1411]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
How can I reach the device dependent configuration screen as explained here:
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Configuration#mi-band--amazfit-specific-settings
I only get that once *before* pairing my devices. And pairing them does not work very well - to be honest. But what do I have to do chance e. g. step number later.

#### Your wearable device is:

Mi Band 3 with FW 1.5.0.2 and HW 18.4.3

#### Your android version is:

Android 7.0 on Moto G4

#### Your Gadgetbridge version is:

 #0.32.1

**Comment by giwu37** [comment]
(Sorry for not tagging my issue, haven't found that yet.)

**Comment by Uatschitchun** [comment]
You can reach it from within the settings dialog, just after the privacy settings

**Comment by IzzySoft** [comment]
@giwu37 can we consider this issue solved? You didn't respond to the suggestion given, which suggests you no longer have this problem. If my assumption was wrong, say so in another comment and we can reopen.
