### ISSUE TITLE
PayPal account integration

### ISSUE THREAD

**Issue by bhavitechnologies** [Freeyourgadget/Gadgetbridge#1414]
Hi, 

I'm integrating PayPal account in my Android App. 

Now, we have to test the same with testing mode including the PayPal account so in that case, i think, we will have to use the Sandbox account and when the App is going on play store, It'll PayPal account be used or we'll have to with merchant /business account?

What would be the steps to follow?

**Comment by IzzySoft** [comment]
What does that have to do with Gadgetbridge? GB doesn't even have Internet access, so online stuff won't work. And I don't think we want to have anything to do with Paypal, this being a privacy oriented project.

**Comment by ashimokawa** [comment]
If you release an APP to play store which is based on Gadgetbridge, you have to make it open source also (our license is AGPL).

**Comment by IzzySoft** [comment]
As there is no clarification from OP, I'm assuming this is either no longer an issue or there's nothing to do from our end – or even both. Hence: closed.
