### ISSUE TITLE
Add to wiki, Mi Band 3 works with FW 2.3.0.2. 

### ISSUE THREAD

**Issue by ArmitageShanks** [Freeyourgadget/Gadgetbridge#1420]
I flashed my Mi Band 3 with the fw and rs from Mi Fit 3.5.8 (which I got from APK Mirror) and my firmware got updated to FW 2.3.0.2 and I wanted to add to the wiki that it works, but not sure how to do that so I'm posting here. 

#### Your wearable device is:
Mi Band 3

*Please specify model and firmware version if possible*
FW 2.3.0.2
HW V0.18.4.1 

#### Your android version is: 
8.1

#### Your Gadgetbridge version is:
0.32.1

**Comment by iwismer** [comment]
Also, the hashes are:
5506158003e04f1632e9948774dac559  Mili_wuhan.fw
36639114613677305ccc935234d09ea8  Mili_wuhan.res

What happened to editing the wiki? Has it been disabled?

**Comment by ArmitageShanks** [comment]
> Also, the hashes are:
> 5506158003e04f1632e9948774dac559 Mili_wuhan.fw
> 36639114613677305ccc935234d09ea8 Mili_wuhan.res
> 
> What happened to editing the wiki? Has it been disabled?

Not sure, maybe it's just me who's dumb, but I cant figure out how to edit it.

**Comment by Perrin-the-wolf** [comment]
A new version is working too MiFit 3.5.9 

Your wearable device is:
Mi Band 3

Please specify model and firmware version if possible
FW 2.3.0.6
HW V0.18.4.3

Your android version is:
9.0

Your Gadgetbridge version is:
0.32.3

**Comment by Perrin-the-wolf** [comment]
You can close this issue, the information is online :-)

**Comment by ashimokawa** [comment]
Ok ;)

I put the information about the wiki being on codeberg at the very top of the README, hope that helps
