### ISSUE TITLE
feature request: [Mi Band 3] show heart rate on screen

### ISSUE THREAD

**Issue by beli3ver** [Freeyourgadget/Gadgetbridge#1430]
Hi,

it would be nice, when I start a activity that my screen on the band shows my heart rate.
That will help me with my sports activity.
When I stop the activity the screen becoming normal.
That would be nice.

**Comment by LOLLeela** [comment]
?

On the band itself? I swipe left and it shows my heart rate. That's something the band does not gadget bridge.

**Comment by ashimokawa** [comment]
Gadgetbridge is not a custom firmware project, we do not modify the software on the Band.
