### ISSUE TITLE
Amazfit BIP not visible to GadgetBridge despite reboot of Pixel 3 XL, uninstall/reinstall etc 

### ISSUE THREAD

**Issue by UpBeatnik** [Freeyourgadget/Gadgetbridge#1432]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*If possible, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)! that might help identifying the problem.*

#### Your wearable device is:

*Please specify model and firmware version if possible*

#### Your Gadgetbridge version is:

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by UpBeatnik** [comment]
Amazfit firmware version V1.1.5.12
Phone Model/Hdware:
Pixel 3 XL
Android Version:
9
Android Build #:
PQ1A.190105.004

**Comment by ovz93br43v7** [comment]
@UpBeatnik How do you fix this issue? My Pixel 3 also don't find the Amazfit Bip with GadgetBridge. In the Bluetooth Menu the Amazfit Bip is visible....
Restart doesn't help.
