### ISSUE TITLE
Mi Band 3 can't connect to Mi Fit App after connecting to Gadgetbridge

### ISSUE THREAD

**Issue by nikhilgeo** [Freeyourgadget/Gadgetbridge#1438]
After connecting to Gadgetbridge, I can't now connect to Mi Fit app. The Mi fit app does not see the mi band and it's stuck at connecting. I tried un-paring the band from bluetooth setttings and signing up the mi fit app with new account and connecting again. Nothing works !!!!

Mobile device: Moto g5 plus, Oreo

**Comment by ashimokawa** [comment]
Try to toggle your phone's Bluetooth off and on.

If that does not work, you can try to factory reset you mi band 3 (via menu with new firmware) or in debug screen with Gadgetbridge if not using the latest firmware.

We do not use Mi Fit, so we cannot reproduce the problem.

Anyone else can confirm this issue?

**Comment by nikhilgeo** [comment]
I'm on the latest firmware, the Gadgetbridge show FW: 2.3.0.2

One more observation is after pairing with the Gadgetbridge I can't navigate to any other options or screens in my Mi Band 3. It's just stuck in the default screen that shows date and time.

I went to the debug screen and I reset the mi band 3 and now I'm able to connect to Mi Fit app and also I could now navigate through other screens. 

Thanks for pointing out the reset from debug screen.

**Comment by ashimokawa** [comment]
I have factory reset my mi band 3 on latest firmware and paired it with Gadgetbridge.

I could navigate through all screens ....
