### ISSUE TITLE
[Amazfit Bip] Weather not updating

### ISSUE THREAD

**Issue by newhinton** [Freeyourgadget/Gadgetbridge#1443]
LineageOS 15.1
Gadgetbridge 0.32.3
Amazfit Bip

I am using LineageOS with a self compiled version of the openweathermap provider which can be found on github. (the versions you link in the wiki do not work on 15.1) The provider itself is working, since the clock-app of los is properly displaying the weather. However, it does not seem that gadgetbridge is updating the weather on my bip, because it has no weatherdata whatsoverer ("Couldn't get weather info...")

Do you know a fix, or can you help me debug this?

Openweathermap-repository:
https://github.com/LineageOS/android_packages_apps_OpenWeatherMapProvider

**Comment by ChrisPHL** [comment]
Please have a look at #1484. I think the issue is discussed there.
Short comprehension: Please use "Weather Notification" instead of "OpenWeatherMapProvider".

**Comment by newhinton** [comment]
@ChrisPHL Thank you! That worked indeed!
