### ISSUE TITLE
No reconnect MiBand3

### ISSUE THREAD

**Issue by ElJochos** [Freeyourgadget/Gadgetbridge#1452]
#### Before reporting a bug, please confirm the following:
- [ x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*If possible, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)! that might help identifying the problem.*

If my MiBand3 is not in the range of my smartphone, which is gadgetbridge running on it, there is a disconnect (logic :D). But there is no reconnect. So it's really annoying to reconnect.

#### Your wearable device is:

MiBand3
*Please specify model and firmware version if possible*

#### Your android version is:
9.0

#### Your Gadgetbridge version is:
the latest :)

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by LuccoJ** [comment]
In Settings, do you have "Reconnect automatically" enabled? Even if you do, sometimes I also experience some failures to reconnect, but, just to rule out the easy fixes...

**Comment by ElJochos** [comment]
I tried it with an "enable" and "disable". The same issues.

**Comment by dmig** [comment]
Having same problem with mi band 2. No reconnect before MiFit connects to device.

**Comment by mjanssens** [comment]
I'm having these reconnect issue also for a while, several months
Miband 3: FW 2.3.0.6  HW: V0.18.4.1
Android: lineageos with microg 9.0, build 16.0-20190422-microG-bacon

Tried changing the settings as mentioned above, with no change in behavior
Haven't found what exactly triggers it, after a phone reboot it doesn't reconnect, sometimes is just disconnects (perhaps when out of range)

I'm not really familiar with android code, but willing to test or troubleshoot, just need some guidance

**Comment by atx** [comment]
I noticed the same issue with my Mi Band 2 after upgrading from LineageOS 14 to LineageOS 15. I thought this related to the "battery optimization" per-app setting, but disabling it for GadgetBridge does not help.

**Comment by Nitrooo** [comment]
Same here, I have to restart Bluetooth or reconnect manually to my Mi Band 3. Really annoying.
