### ISSUE TITLE
amazfit bip: unclear firmware upgrade docs

### ISSUE THREAD

**Issue by ThomasWaldmann** [Freeyourgadget/Gadgetbridge#1458]
#### Before reporting a bug, please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Amazfit-Bip-Firmware-Update

Unclear firmware upgrade instructions:

Quoting the wiki:
```
1. Mili_chaohu.fw
2. Mili_chaohu.res (The Bip will tell you when needed)
3. Mili_chaohu.gps or Mili_dth.gps when available
   (his rarely changes, check the table below, if you should update)
```

1. ok, clear.
2. no? not as expected? i flashed the .fw, device rebooted and showed the "broken connection to phone" graphics (watch, phone, red X). i tried re-connecting / re-pairing, but could not get rid of that graphics on the watch. then just flashed the .res and that brought the watch to its normal state.
3. having the word "or" in critical instructions that may brick a device is a bit disturbing. so how does one determine whether one has to flash the one or the other? i had both in the extracted mifit apk assets. also note the typo.

Also a strange effect: when flashing .gps and .res, it seemed that watch and GB were out of sync (one showing still "flashing" while the other already "finished" - success or failure unclear).

#### Your wearable device is:

amazfit bip (1) A1608

- fw 1.1.2.05 (preinstalled)
- -> 1.1.5.12 (from mifit 3.5.8 apk)
- -> 1.1.5.16 (from mifit 3.5.9 apk)

DONE:  I'll do a wiki edit with checksums etc. after testing this a while. It is already clear that neither 1.1.5.12 nor 1.1.5.16 bricks the device, yay. :-)

#### Your android version is:

LineageOS 15.1

#### Your Gadgetbridge version is:

0.32.3

**Comment by ThomasWaldmann** [comment]
Also, considering that the BIP 2 is coming soon(?), the wiki page should make clear that it is for the BIP A1608 model, at least until it has instructions for the BIP 2.

**Comment by ThomasWaldmann** [comment]
Notable: this page suggests a different order of flashing:

https://github.com/amazfitbip/documentation/wiki/Downgrade-and-flashing-of-patched-firmware

So, does it matter? If so, which is correct?

**Comment by ThomasWaldmann** [comment]
Clarifying what I meant with "out of sync" during a flash upgrade:
- gps: 19:13 - 19:18 (phone), - 19:19 (watch, after button+tapping)
- res: 19:20 - 19:24 (watch/phone finished about same time)
- fw:  19:26 - 19:32 (watch/phone finished about same time)

So in the above case, gadgetbridge on the phone finished about a minute before the watch was finished (or did it wait for a tap / button press?).

**Comment by ThomasWaldmann** [comment]
About progress:

The progress bar is shown in android notification dropdown, but not on the installer main screen.

Maybe usability would be better if there was also a progress bar on the installer screen OR at least a hint "you can watch the flashing progress in the notifications".

**Comment by ashimokawa** [comment]
I agree that things can still be improved.

Flashing order should be 1) Firmware 2) Res 3) GPS. I originally suggested otherwise but it became clear that the order above must be the correct one. For example the RES format changed once, so one HAD to flash the .fw file first, in most cases it does not matter if RES is newer than the firmware so I suggested to flash it first back then (new images are just appended to the res)

About Gadgebridge saying "update finished" - well, it should better say "transfer done", In case of GPS the watch flashes after transfer - it should be safe to disconnect Gadgetbridge when the "finished" message appears. The is no transfer done afterwards.

If you want to edit the wiki, head over to https://codeberg.org/Freeyourgadget/Gadgetbridge/ and make a Codeberg account. Github is only a mirror and still hosts the issues/PRs (which we will also move in the next weeks or month, when migration issues were ironed out)

**Comment by ThomasWaldmann** [comment]
Ah, transfer vs. transfer+flashing, that explains it.

Does that mean that for .fw and .res it flashes WHILE transferring? What happens if it gets interrupted somehow?

Yup, already did some edits. Asked myself whether i shall add typical transfer/flashing durations so people are prepared that this is a bit slow.

**Comment by ThomasWaldmann** [comment]
@ashimokawa do you know about the different gps files and how to select them?

I used the mili_dht.gps and it seems to basically work. Had it on while driving and afterwards it showed me a roughly correct track in OSM. Sometimes it was quite off my real route though.

**Comment by ashimokawa** [comment]
@ThomasWaldmann 
Interrupted transfers are not a problem, Nothing will happen. I assume that fw is flashed during the reboot and ressources while transferring. You might end up with empty menus if .res fails but nothing else.

I did so many bad things to my Bip and it seems unbrickable expect you flash that one brick old brick firmware (0.1.0.51)

Regarding GPS:

if you unpack a Mi Fit apk and look at assets/firmwares.json you see which version is recommended for the Bip (currently Mili_dth.gps = 15974,e61dd16,126), normally _dth would indicate a file for the Bip2, but the Bip2 uses Mili_18344.gps now = 18344,eb2f43f,126. It is a mess and Mili_Chaohu.gps is still there even if it is unused). 

I think any .gps file should work, you can try to flash Mili_18344.gps and see if it works better for you.

**Comment by ThomasWaldmann** [comment]
OK, I updated the wiki page about the currently recommended gps file and also the firmwares.json file.

**Comment by ChrisPHL** [comment]
Hey guys,
according to the post [https://github.com/Freeyourgadget/Gadgetbridge/issues/1514#issuecomment-492598878](https://github.com/Freeyourgadget/Gadgetbridge/issues/1514#issuecomment-492598878), I wonder where to put the
`* Flash the appropriate (latin / non-latin) font file (*.ft / *.ft.latin).`
in [https://github.com/Freeyourgadget/Gadgetbridge/wiki/Amazfit-Bip-Firmware-Update#recommended-flashing-order](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Amazfit-Bip-Firmware-Update#recommended-flashing-order).

Any knowledge out there?
Chris

**Comment by IzzySoft** [comment]
I assume this issue can be closed now as solved. If I was wrong, let me know and I reopen.
