### ISSUE TITLE
[bip] whitelist version 49274

### ISSUE THREAD

**Issue by kadamski** [Freeyourgadget/Gadgetbridge#1461]
Hi, I have successfully updated watchfaces on my Amafit Bip with FW 1.1.5.16 (that was installed via MiFit 3.5.9). The application told me to ask for whitelisting version 49274.

**Comment by ashimokawa** [comment]
Is that the latin Version?

**Comment by kadamski** [comment]
@ashimokawa No idea. How to check that? The watch was bought and is being used in Europe (Poland), it originally did not have any Chinese firmware on it, or something.

**Comment by tal33** [comment]
Don't know about 49275 but flashing 1.1.5.16 latin greeted me with "unsupported" firmware by gadgetbridge FW installer but it seems to work (but I reflashed it now with non-latin since latin was spanish and I needed German which I din't manage to switch to)

**Comment by ashimokawa** [comment]
@tal33
Firmware 1.1.5.36 is in German,
It is only available via ota, but linked in a thread here.

**Comment by tal33** [comment]
Thanks might give it a try if I really need German. 
For reference: the thread mentioned is [1514](https://github.com/Freeyourgadget/Gadgetbridge/issues/1514)

**Comment by vanous** [comment]
Perhaps we could also whitelist 1.1.5.24 , which i have now flashed. I have used non latin version. There was no need to update .res. This has actually fixed weather formatting in Weather + missing weather temperature in some watchfaces. I took the firmware from https://amazfitwatchfaces.com/firmware , Firmware v.1.1.5.24 (not latin) / 1.1.5.36 (latin).

**Comment by ashimokawa** [comment]
Yes I tested both, will whitelist

**Comment by ashimokawa** [comment]
I have whitelisted 1.1.5.24, 1.1.5.56 and 1.1.5.36 (latin)
All of them tested by me.
