### ISSUE TITLE
Amazfit Bip music player control 

### ISSUE THREAD

**Issue by emrsmsrli** [Freeyourgadget/Gadgetbridge#1468]
In [FEATURES.md](https://github.com/Freeyourgadget/Gadgetbridge/blob/master/FEATURES.md), it is mentioned that music player control on Amazfit Bip is not supported and not possible to implement. However there are numerous applications on the Play Store that emulate the feature using the side button. Is this kind of feature planned to be implemented?

#### Wearable device is:
Amazfit Bip

**Comment by ffranchina** [comment]
There's the PR #925 that is stuck and we have no news about it. Once the app implements the broadcast of the button's event we can have access to a broad number of different applications. Let's hope someone will look into that sooner or later!

**Comment by ffranchina** [comment]
Updated at #924 :D (spoiler: good news)
I think it's possible to close this issue @ashimokawa :) Thanks for your work!

**Comment by emrsmsrli** [comment]
Thanks for the heads-up! And thanks for the great work.
