### ISSUE TITLE
Support firmware update for Mi Band 1A

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#147]
Firmware update is currently disabled for the Mi Band 1A. We should check for compatible versions and allow this.

**Comment by jtru** [comment]
I'm glad you received the band I sent you, and I already updated the fw on my Mi Band 1A successfully with the new releases since then - thanks for making it happen! :)

This issue can probably be closed.

**Comment by cpfeiffer** [comment]
Thanks for the update, good to know that fw update worked for you too. Did you flash the version that I recommended on the wiki or did you flash a newer version?

I have yet to find the time (and a new mobile ;( ) to fix notifications with the newer 1A firmwares.

**Comment by jtru** [comment]
Ah, sorry - I missed that you actually asked a question here :) Yes, I flashed the recommended firmware image, though while using the band for a few weeks now, I noticed that sleep tracking (and, as a consequence, "smart" alarms) doesn't work with it.

And what's the problem with your mobile, exactly?
