### ISSUE TITLE
MI Band 3 2.3.0.6 Firmware upgrade

### ISSUE THREAD

**Issue by prinz3nroll3** [Freeyourgadget/Gadgetbridge#1475]
Unusable device after trying to flash the latest MI band 3 firmware from the lastest mi fit app 6904 February 27, 2019  , available at apk mirror.

 I ve to install the mi fit app and update to the newest firmware after that I can use Gadget-Bridge again, but I think there is some compatible issue.

**Comment by ArmitageShanks** [comment]
Hm, I had no issues with upgrading to 2.3.0.6 with an apk from APK Mirror. Don't remember which apk it was though, but most likely the same as you since its the same firmware. I'm on Android 9/Pie though. Same GB version, 0.32.4.

**Comment by ashimokawa** [comment]
I also had no problem
