### ISSUE TITLE
[Solved] Amazfit Bip: No notification for incoming call

### ISSUE THREAD

**Issue by tibaultbordeaux** [Freeyourgadget/Gadgetbridge#1477]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Notifications of calendar events do work.
But I do not receive notifications of incoming phone calls.
(Hitting "incoming call" in Debug-Menu shows me a proper notification with the ability to ignore or to hang off)
No app is blacklisted and gadgetbridge has all needed permissions.

#### Your wearable device is:
Amazfit Bip (1), Model A1608
FW 1.1.5.16 (updated following the wiki)

#### Your android version is:
Lineage OS 16

#### Your Gadgetbridge version is:
0.32.4

**Comment by tibaultbordeaux** [comment]
This is what I tried so far:
- re-installed gadgetbridge, just to be sure that all permissions are set
- Updated Lineage OS to the latest nightly

Still no notifications of incoming calls.

btw, I do get notifications of incoming SMS.

Anything I can do to help with investigating this issue?

**Comment by tibaultbordeaux** [comment]
Here is the log:

21:06:44.079 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.32.4
21:06:57.863 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
21:06:57.865 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
21:06:57.874 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
21:06:57.876 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
21:06:57.882 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
21:06:57.883 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
21:07:05.078 [main] INFO  n.f.g.e.NotificationListener - Notification removed: com.android.dialer: call
21:07:05.389 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
21:07:05.390 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
21:07:05.440 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
21:07:05.442 [main] INFO  n.f.g.e.NotificationListener - Ignore notification

**Comment by tibaultbordeaux** [comment]
Here is another log:

08:32:26.824 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.32.4
08:32:36.645 [main] DEBUG n.f.g.e.NotificationListener - got call from: com.android.dialer
08:32:36.647 [main] DEBUG n.f.g.e.NotificationListener - Ignoring non-voip call
08:32:36.664 [main] DEBUG n.f.g.e.NotificationListener - got call from: com.android.dialer
08:32:36.665 [main] DEBUG n.f.g.e.NotificationListener - Ignoring non-voip call
08:32:36.671 [main] DEBUG n.f.g.e.NotificationListener - got call from: com.android.dialer
08:32:36.672 [main] DEBUG n.f.g.e.NotificationListener - Ignoring non-voip call
08:32:43.906 [main] INFO  n.f.g.e.NotificationListener - Notification removed: com.android.dialer: call
08:32:44.196 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
08:32:44.197 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
08:32:44.244 [main] INFO  n.f.g.e.NotificationListener - Ignoring notification, is a system event
08:32:44.245 [main] INFO  n.f.g.e.NotificationListener - Ignore notification

Anybody out there who is able to explain me why GB is "ignoring" and "removing" everything from com.android.dialer ?

Thanks in advance!

Tibault

**Comment by ashimokawa** [comment]
We ignore the notifications because we receive calls by listening to system events instead of scraping notifications. 

I have no idea why it does not work for you. It does work here

**Comment by tibaultbordeaux** [comment]
Thanks, @ashimokawa, for your answer! It led me to search for a solution on my side rather than on your side ... :-)

And here is it:

In Lineage OS there is a thing called "Privacy Guard". You will find it in the options below "Security"  -> "Trust". There you have to click the "More Options Icon" and than "Advanced".

Search for gadgetbridge and click on it.

You will see "Reading call protocol" (or similar)
Tricky thing is: It's neither on "Allowed" nor on "Forbidden" ... It's set on "Always ask".
And this prevents the notification of a incoming call.
Set this option on "Allowed" and you are fine.

Thanks for your great app, your are genius!

**Comment by tibaultbordeaux** [comment]
btw, @ashimokawa , would like to mention this in the wiki. There may be more users of Lineage OS 16 facing this issue in future. Is it ok for you that I`ll add a hint?

**Comment by tibaultbordeaux** [comment]
Done.
https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Incoming-call-notification-on-Lineage-OS
Should be listed under "FAQ!. Could you do this,  @ashimokawa ?

**Comment by ashimokawa** [comment]
@tibaultbordeaux 
Ok, done! You could have done it youself by navigating here:

https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/_Sidebar

(I agree it is counter intuitive)

And thanks for making a codeberg.org account. We are planning to migrate  the issues there also, since you already have an account, we the authorship of your comments in the issue tracker can be preserved. :+1:

**Comment by white-gecko** [comment]
The same issue not only applies to the Amazfit Bip, but also to other devices supported by gardgedbridge, such as Pebble. Could someone with the access right also not this here: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Incoming-call-notification-on-Lineage-OS and reference this here https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble or here https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Getting-Started ?

**Comment by ashimokawa** [comment]
@white-gecko

See readme.md about editing the wiki.

Next Version of gadgetbridge (0.36.2) will ask for the missing permission with a hack on Lineage
