### ISSUE TITLE
unable to install firmware on Amazfit Bip Lite

### ISSUE THREAD

**Issue by FrankK1** [Freeyourgadget/Gadgetbridge#1479]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
If I try to install the firmware files, the FW installer give the feedback "Element cannot be installed". The firmware files are from Mi Fit 3.5.9. I try also the firmware from an older Mi Fit, the same result. 

#### Your wearable device is:
Amazfit Bip Lite ((A1608), FW 1.1.5.04

#### Your android version is:
LineageOS 16.1

#### Your Gadgetbridge version is:
0.32.4

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
Please paste logs, since it works here, it is hard to debug.

**Comment by FrankK1** [comment]
Sorry, I thought I append it.

[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/3076709/gadgetbridge.log)

**Comment by ashimokawa** [comment]
@FrankK1 
can you try to rename the firmware to .fw (if not already) and use a filemanager to chose the file to install? Or did you do that? If now what exactly did you do to intall the firmware?

**Comment by FrankK1** [comment]
I selected the firmware file (Mili_chaohu.fw) in the filemanager, then I get the question to open the file with the "FW/App-Installer" once or always. Then the installer says "connecting to device" if not connected and some seconds later come the message "Element cannot be installed".
It's the same procedure I do several times to update the firmware. The only different thing, I do the update the first time with LineageOS 16.1.

**Comment by ashimokawa** [comment]
@FrankK1
I also tried with LineageOS 16.0 (16.1 does not exist), it works here

**Comment by FrankK1** [comment]
Hi Andreas, you're right, LinOS 16 not 16.1.
I tried the FW update with GB 0.32.4 and another device, a tablet with an ancient Android 7.0 and it works. With my phone the update doesn't work, all other function of GB work fine.

**Comment by FrankK1** [comment]
Issue is solved. 
The reason was my file manager. I found a hint in the description of the Mi Band 3 firmware update. A crosscheck with an other device and the same file manger show also the "Element cannot be installed" message. I think, it would be a good idea, to mention this issue in all firmware update description.
