### ISSUE TITLE
Chart Activity sometimes dies when rotating screen

### ISSUE THREAD

**Issue by ashimokawa** [Freeyourgadget/Gadgetbridge#148]
<pre>
E/AndroidRuntime(22590): FATAL EXCEPTION: main
E/AndroidRuntime(22590): Process: nodomain.freeyourgadget.gadgetbridge, PID: 22590
E/AndroidRuntime(22590): java.lang.NullPointerException: Attempt to read from null array
E/AndroidRuntime(22590):        at com.github.mikephil.charting.renderer.PieChartRenderer.drawDataSet(PieChartRenderer.java:135)
E/AndroidRuntime(22590):        at com.github.mikephil.charting.renderer.PieChartRenderer.drawData(PieChartRenderer.java:122)
E/AndroidRuntime(22590):        at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:119)
E/AndroidRuntime(22590):        at android.view.View.draw(View.java:15247)
E/AndroidRuntime(22590):        at android.view.View.updateDisplayListIfDirty(View.java:14183)
E/AndroidRuntime(22590):        at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(22590):        at android.view.View.draw(View.java:14975)
E/AndroidRuntime(22590):        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(22590):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(22590):        at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime(22590):        at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(22590):        at android.view.View.draw(View.java:14975)
E/AndroidRuntime(22590):        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(22590):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(22590):        at android.view.View.draw(View.java:15250)
E/AndroidRuntime(22590):        at android.support.v4.view.ViewPager.draw(ViewPager.java:2262)
E/AndroidRuntime(22590):        at android.view.View.updateDisplayListIfDirty(View.java:14183)
E/AndroidRuntime(22590):        at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(22590):        at android.view.View.draw(View.java:14975)
E/AndroidRuntime(22590):        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(22590):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(22590):        at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime(22590):        at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(22590):        at android.view.View.draw(View.java:14975)
E/AndroidRuntime(22590):        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(22590):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(22590):        at android.view.View.draw(View.java:15250)
E/AndroidRuntime(22590):        at android.view.View.updateDisplayListIfDirty(View.java:14183)
E/AndroidRuntime(22590):        at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(22590):        at android.view.View.draw(View.java:14975)
E/AndroidRuntime(22590):        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(22590):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(22590):        at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime(22590):        at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(22590):        at android.view.View.draw(View.java:14975)
E/AndroidRuntime(22590):        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(22590):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(22590):        at android.view.View.updateDisplayListIfDirty(View.java:14178)
E/AndroidRuntime(22590):        at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(22590):        at android.view.View.draw(View.java:14975)
E/AndroidRuntime(22590):        at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
E/AndroidRuntime(22590):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
E/AndroidRuntime(22590):        at android.view.View.draw(View.java:15250)
E/AndroidRuntime(22590):        at android.widget.FrameLayout.draw(FrameLayout.java:598)
E/AndroidRuntime(22590):        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2906)
E/AndroidRuntime(22590):        at android.view.View.updateDisplayListIfDirty(View.java:14183)
E/AndroidRuntime(22590):        at android.view.View.getDisplayList(View.java:14205)
E/AndroidRuntime(22590):        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
E/AndroidRuntime(22590):        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
E/AndroidRuntime(22590):        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
E/AndroidRuntime(22590):        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2536)
E/AndroidRuntime(22590):        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
E/AndroidRuntime(22590):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
E/AndroidRuntime(22590):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime(22590):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
E/AndroidRuntime(22590):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(22590):        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(22590):        at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime(22590):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(22590):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(22590):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(22590):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(22590):        at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime(22590):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22590):        at java.lang.reflect.Method.invoke(Method.j
</pre>
(dont know why it stops here)

**Comment by cpfeiffer** [comment]
Do you know of a way to reproduce this? Which is the current chart when this happens? Is the chart already filled with data or not?

I think the bug is in MPAndroidChart, but I need some info how it actually occurs.

**Comment by ashimokawa** [comment]
The chart was filled with data, I do not remember which one it was though.
It happened a couple of times also when pinch zooming, so it seems to be indeed an MPAndroidChart bug.

**Comment by ashimokawa** [comment]
Closing this, since I didn't experience it for a long time, guess since the last MPAndroidChart update.
