### ISSUE TITLE
Blacklist search only filters by package ID

### ISSUE THREAD

**Issue by karottenbaum** [Freeyourgadget/Gadgetbridge#1482]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

The notification blacklist function only searches by package ID, not by display name.
This leads to confusion when the package ID does not contain the display name, e.g. `com.google.intelligence.sense` for "Pixel Ambient Services."

#### Your android version is:

Q (beta 2 patch 1)

#### Your Gadgetbridge version is:

0.32.4 (F-Droid)

**Comment by danielegobbetti** [comment]
The functionality was actually already there, but the comparison was done in the wrong way. It is now fixed in master, thanks for the report!
