### ISSUE TITLE
Need new "Weather Notification" app

### ISSUE THREAD

**Issue by RoadRangerX** [Freeyourgadget/Gadgetbridge#1487]
The "Weather Notification" app seems to be abandoned and only supports degrees Celsius - us users in the US really need degrees Fahrenheit for GadgetBridge to be fully functional for us :-( .

If there was some easy way to switch between GadgetBridge and Mi Fit we could use GadgetBridge just to export data - but GadgetBridge factory resetted my AmazFit Bip when I switched :-( .

**Comment by vanous** [comment]
Setting units to imperial (in gadgedbridge) sets the units in weather on band as well, just tested. Notification on phone is in metrics thought.

**Comment by RoadRangerX** [comment]
My apologies - it did suddenly start working for me in Fahrenheit, not sure what I did to make that happen. Gotta love open source "documentation" LOL. I couldn't find my way back here to update :-/ .

**Comment by vanous** [comment]
Nice :)
