### ISSUE TITLE
Wiki: Pebble updates

### ISSUE THREAD

**Issue by matejdro** [Freeyourgadget/Gadgetbridge#1493]
1. [Getting Started page](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Getting-Started) mentions that Pebble must be paired in Bluetooth settings. This does not seem to be the case anymore (See #1455)

2. [Android Compatibility page](https://github.com/Freeyourgadget/Gadgetbridge/wiki/PebbleKit-Android-App-Compatibility):
     * Sleep as Android works, but it needs stock Pebble app installed (just to detect Pebble support. App does not need to be running)
     * [Notification Center](https://play.google.com/store/apps/details?id=com.matejdro.pebblenotificationcenter&hl=en_US) seems to work fine
     * [PebbleTasker](https://play.google.com/store/apps/details?id=com.kodek.pebbletasker&hl=en) Seems to work fine

(There does not appear to be a way to make PR for a wiki, so I'm reporting updates that way)

**Comment by IzzySoft** [comment]
@ashimokawa as the wiki at Codeberg still points here: which is the place to make changes? I thought that switched to Codeberg already, but the wiki there linking back here confuses me.

**Comment by ashimokawa** [comment]
No idea what you are talking about. Where is a link on codeberg that directs to github?

**Comment by IzzySoft** [comment]
In the footers. Check e.g. [here](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/PebbleKit-Android-App-Compatibility): scroll to the end of the page, then see the links: "Download Donate Homepage Blog **Wiki"** – that last one links to Github. So which one is primary now? If Codeberg, that link should be fixed.

**Comment by matejdro** [comment]
Huh, so project is moving to Codeberg? Maybe a link on the main README on github would help? 

It is kind of confusing now, issues are here, wiki is apparently on both?

**Comment by IzzySoft** [comment]
@matejdro the goal is to move to Codeberg. The move has not yet completed – and won't before the migration is better supported. AFAIK the wiki should have "its primary" at Codeberg already, while issues are dealt with here (and only here until migration is possible) while code is sync'd between both places. @ashimokawa may be able to point out a place tracking the current state.

**Comment by ashimokawa** [comment]
@matejdro 
As @IzzySoft said, wiki and git itself is on codeberg. Both are technically a git repository and have hooks to mirror everything to github. We always push to codeberg. Github is "read only" now. Pull requests and Issues are on github until migration of issues works better. We are experimenting with it. The more people sign up on codeberg, the better the migration will work.

@matejdro 
If you want to fix the wiki, please do on codeberg.org. I already fixed the footer as @IzzySoft pointed out.
I might remove all wiki pages later and put a link to the corresponding codeberg wiki page.

**Comment by matejdro** [comment]
Updated wiki pages on codeberg.org.

**Comment by IzzySoft** [comment]
@ashimokawa alternatively to removing the wiki here, maybe modifying the footer with a pointer to Codeberg and then make the wiki here read-only? Not sure how good an idea that is; I was just thinking of "other sources" pointing here which would only get a 404 otherwise where "some pointer™" would be preferable.

**Comment by matejdro** [comment]
Personally, I think you should replace all data with the link (or delete it outright). Otherwise there would be outdated information on this wiki with tiny link in the footer pointing to the fresh source.

**Comment by ashimokawa** [comment]
@matejdro 
Thanks for editing.

Github wiki *IS* read-only (not editable though github), but it is always up to date when editing on codeberg (there is an automatic trigger).
Nothing is outdated, but to avoid confusion we should probably replace every single wiki page with a link to the new wiki

**Comment by IzzySoft** [comment]
@ashimokawa if you want to do that, and avoid doing it manually: [Is it possible to redirect in Gollum wiki (GitHub wiki) pages?](https://stackoverflow.com/questions/11138802/is-it-possible-to-redirect-in-gollum-wiki-github-wiki-pages) has a recipe (a "tiny little shell script") you could adapt and use.

Unfortunately it seems that a real redirect isn't possible (not for the lack of [being asked for](https://github.com/gollum/gollum/issues/1023)). Though Gollum also supports MediaWiki: the redirects supported by that format are only "internal ones" (stay-on-server). But hey, with that script the new link is included, so it's one additional click. Good compromise I'd say.
