### ISSUE TITLE
Mi Band 3 missing status items

### ISSUE THREAD

**Issue by FrankK1** [Freeyourgadget/Gadgetbridge#1497]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
If I connect the Band with Gadgetbridge, the status show only the items steps and battery level. If I connected with MiFit, then the status show steps, distance, calorie and battery level. After disconnect in MiFit and reconnect to Gadgetbridge, the status show steps and battery level again.

#### Your wearable device is:
Mi Band 3, FW 2.3.0.6, HW 0.18.3.4

#### Your android version is:
LineageOS 16

#### Your Gadgetbridge version is:
0.32.4

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by vanous** [comment]
This is a duplicate of #1398 , you can find solution to your issue there in comments.

**Comment by FrankK1** [comment]
@vanous, after several tries of reset the band, connect/disconnect in Mi Fit and in GB and with 2 devices it works now. I don't know, which action was the ticket. Thanks.
