### ISSUE TITLE
Turn off Bluetooth / airplane mode - Amazfit 

### ISSUE THREAD

**Issue by neno89** [Freeyourgadget/Gadgetbridge#1505]
Hi!!

Regarding the Amazfit Bip, I think many people would want to have the ability to turn off the Bluetooth connection manually, that is to put the watch in airplane mode. Any way I would really like to have this option and would of course donate for this option.

Greetings

Neno

**Comment by ashimokawa** [comment]
@neno89 
This would require modifying the Bip firmware, which is out of scope for this project. We are not a custom firmware project.
