### ISSUE TITLE
Mi Band 3 additional languages

### ISSUE THREAD

**Issue by yarons** [Freeyourgadget/Gadgetbridge#1506]
#### Your issue is:
The list of Mi Band 3 languages is mising some supported available languages (built-in).
According to [MB3Editor](https://mb3editor.azurewebsites.net) the list of languages is:
- Simplified Chinese
- Traditional Chinese
- English
- Spanish
- Russian
- Korean
- French
- German
- Italian
- Polish
- Japanese

These appear in MB3Editor but not in GB: 
+ Indonesian
+ Thai
+ Arabic
+ Vietnamese
+ Portuguese
+ Dutch
+ Turkish
+ Ukrainian

The current list in GB is:
- simplified_chinese
- traditional_chinese
- english
- spanish
- russian
- german
- italian
- french
- polish
- japanese
- korean

#### Your wearable device is:

Mi Band 3 NFC - FW 1.7.0.4

#### Your android version is:
9
#### Your Gadgetbridge version is:
0.32.4

**Comment by yarons** [comment]
This was taked from the 1.7.0.4 firmware as an example of the used languages (extracted using a hex viewer and then recompiled using hex to unicode converter online):

请充值 請加值 - Simplified Chinese
余额低 餘額低- Traditional Chinese
Insufficient funds - English
Fondos insuficientes - Spanish
Недостаточно средств- Russian
잔액 부족- Korean
Fonds insuffisants - French
Unzureichende Geldmittel - German
Dana tdk mencukupi - Indonesian
Brak środków - Polish
Saldo insufficiente - Italian
残高が足りません - Japanese
เงินไม่เพียงพอ - Thai
رصيد غير كافي - Arabic
Không đủ tiền - Vietnamese
Fundos insuficientes - Portuguese
Onvoldoende saldo - Dutch
Yetersiz bakiye - Turkish
Недостатньо коштів - Ukrainian

**Comment by ashimokawa** [comment]
@yarons 
Thanks will do!
