### ISSUE TITLE
How can I contribute to the wiki ?

### ISSUE THREAD

**Issue by MagicFab** [Freeyourgadget/Gadgetbridge#1507]
I contributed to the wiki in the past (#1288) and I'd like to continue this work and make some small additions. It seems I no longer can do that. I couldn't find any information about wiki contributions in the README either.

Can I get access to editing the wiki ? Thanks in advance for considering my request.

**Comment by IzzySoft** [comment]
Where have you looked? The Wiki is now maintained at [Codeberg](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/) (and Github mirrors that).

@ashimokawa maybe adding a prominent note to the main readme? It's not that obvious if you don't know it already.

**Comment by ashimokawa** [comment]
Done.

**Comment by IzzySoft** [comment]
Perfect, thanks!

**Comment by MagicFab** [comment]
Under "contribute" in the README and in the wiki pages itself there was no mention of it.

Adding it to the top of README isn't ideal but welcome, thank you! Is there any reference or information on reasons to go to CodeBerg ?
