### ISSUE TITLE
"Element cannot be installed" with kj fonts

### ISSUE THREAD

**Issue by math-rock** [Freeyourgadget/Gadgetbridge#1508]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

The kj (Korean/Japanese) font file extracted from apk assets can't be installed through Gadgetbridge, and so the band is stuck waiting to finish update. 

I don't get the same error with the .ft font.

Steps I tried:

1. Charge band and pair through Gadgetbridge
2. Download 3.4.7 mi fit apk
3. Rename to .zip extension and pass mili_wuhan .fw and .res files through Gadgetbridge installer intent within Ghost Commander
4. Pair again with band
5. See same update message
6. Try to install font file through installer intent
7. Get "Element cannot be installed" error in Gadgetbridge
8. Extract kj file and retry with AOSP file manager
9. Get same error
6. Repeat steps above with 3.5.7
7. See same update message
8. Try to install through Amaze
10. Same error
11. Try to extract and install through Amaze
12. Same error

#### Your wearable device is:

Mi Band 3
FW: 2.2.0.42
HW: 0.18.3.8

#### Your android version is:

8.1.0

#### Your Gadgetbridge version is:

0.32.4

**Comment by math-rock** [comment]
Update: installing the .ft font didn't fix the hung "connect to app and update" error. Installing the 3.5.7 mi fit apk didn't fix it either.

**Comment by ashimokawa** [comment]
This is fixed in master since a few hours.

**Comment by ashimokawa** [comment]
@math-rock 
With "older" firmwares, you had to set the language to korean or japanese when you had the .ft.kj font installed, and you had to set the language to something else when the .ft font was installed.

At least with the latest 2.3.0.6 firmware after flashing ft.kj I could set the language to other languages as well.

Also there are two version of the .ft.kj file, both labled as version "1" - the one that does not install with Gadgetbridge 0.32.4 is the new one. We plan to  release 0.33.0 on Thursday with the fix.

**Comment by math-rock** [comment]
I tried a debug apk from master, but it can't find the device when scanning. Crossing my fingers for 0.33.0.

**Comment by ashimokawa** [comment]
@math-rock
You have to "forget" the device in Android settings - else you cant find when scanning

**Comment by math-rock** [comment]
Thanks! The kj font installed and my issue is resolved.
