### ISSUE TITLE
Pebble Health Data

### ISSUE THREAD

**Issue by hirenshah** [Freeyourgadget/Gadgetbridge#1509]
#### Before reporting a bug, please confirm the following:
- [YES] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [YES] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [N/A ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I am trying to move away from the original Pebble app because it is causing severe battery drain, and all the Gadget Bridge guides seem to hint at the Pebble Health data being synced.  I can't find anything which confirms what happens to the historic Pebble Health data in the Pebble app. Is it lost if I start using GadgetBridge and remove the original app?  Can it be imported into GadgetBridge?  If it is the latter, how does one do that?

Is v4.3 also the latest firmware available?  Rebble had v4.4.  The link mentioned to check for the latest firmware is obsolete as well:
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Firmware-updates

#### Your wearable device is:
Pebble Time Steel

#### Your android version is:
Android Pie (9.0)

#### Your Gadgetbridge version is:
0.32.4

**Comment by ashimokawa** [comment]
@hirenshah 
Sorry, your previous data will be lost when using Gadgetbridge.

Indeed you are right that last year PebbleOS 4.4-rbl came out! We missed that - and we do not have it either. If I find a download link I will post it here.

It is a hex edited version officially distributed by former Pebble employees.

https://twitter.com/katharineberry/status/1021624455863316480
