### ISSUE TITLE
DISPLAY CURRENT HEART RATE

### ISSUE THREAD

**Issue by raudinasrining24** [Freeyourgadget/Gadgetbridge#1510]
Hello, currently i am developing an apps. i want to display real time heart rate on main menu. but i dont understand how to call enableRealtimeTracking() method since its use fragment activity. i dont understand how to refresh heart rate, so it can be a real time. please respond soon, thank you.

**Comment by ashimokawa** [comment]
@raudinasrining24 
Don't take it personally, but we really do not have the resources to help with unrelated projects that try to extract information from the Gadgetbridge source code.
Our time is limited, we have families and jobs.
