### ISSUE TITLE
[Mi Band 3]Confirming that FW update to 2.3.0.28 from Mi Fit 4.0.0 is working. 

### ISSUE THREAD

**Issue by ArmitageShanks** [Freeyourgadget/Gadgetbridge#1513]
#### Your wearable device is:
Mi Fit 3
HW V0.18.4.1
FW 2.3.0.28

#### Your android version is:
LOS 16/ Android 9

#### Your Gadgetbridge version is:
0.32.4

Mi Fit 4.0.0 is out with apparently a big overhaul. I extracted the fw and rs from it and tried it on my Mi Band 3 and the update went well. I just wanted to report that, but since I cant edit the wiki i didnt know where to put it so i put it here.

**Comment by ashimokawa** [comment]
@ArmitageShanks 
Thanks! This is whitelisted now and in wiki.

Quoting the very top of the README:

> IF YOU WANT TO EDIT THE WIKI, do so on codeberg.org The wiki on github.com is a read-only mirror, as is the git repo itself. Issues and PRs will move to codeberg summer 2019, if you want your issue/PR comments migrated properly, please create a codeberg acount before we will migrate.
