### ISSUE TITLE
Can't pair Xiaomi Band 3 with Gadgetbridge

### ISSUE THREAD

**Issue by corrugated** [Freeyourgadget/Gadgetbridge#1517]
#### Before reporting a bug, please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I got a new Xiaomi Band 3 and failed to pair it with Gadgetbridge.

What I do:
* enable Bluetooth and GPS
* start Gadgetbridge
* press the '+' button
* wait till the band appears and click on it
* "Pair your Mi Band" screen appears but the band never vibrates or blinks and pairing never finishes

What I tried without success:
* wait for a long time
* reboot phone
* reset band to factory defaults
* disable "Enable Bluetooth pairing" in "Mi Band / Amazfit settings"
* pair in Gadgetbridge on another phone

What I tried with success:
* pair the band with Mi Fit (on other phone)

Since the band does work on the other phone with Mi Fit but not with Gadgetbridge I don't think there's a problem with the phone or the band.
Mi Fit also updated the band's firmware, so it should be on the latest version now.

I attached a log when trying to pair the band here: [xiaomi_band_3.log](https://github.com/Freeyourgadget/Gadgetbridge/files/3194184/xiaomi_band_3.log)

It shows:
```05-18 15:53:06.827  9054 10191 E nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Queue Dispatch Thread died: Attempt to invoke virtual method 'boolean nodomain.freeyourgadget.gadgetbridge.service.devices.miband.DeviceInfo.isMili1()' on a null object referencejava.lang.NullPointerException: Attempt to invoke virtual method 'boolean nodomain.freeyourgadget.gadgetbridge.service.devices.miband.DeviceInfo.isMili1()' on a null object reference```
could this be a problem?

#### Your wearable device is:
model: Xiaomi Band 3 (XMSH05HM)
firmware: V2.3.0.28

#### Your android version is:
7.1.2 (Xiaomi Redmi Note 3 with LineageOS)
other phone: 5.1.1 (Sony Xperia Z1 Compact)

#### Your Gadgetbridge version is:
0.33.0 (latest version from f-droid)

**Comment by ashimokawa** [comment]
@corrugated 
Thanks for reporting,
The null pointer issue should not happen in any case!
I was not aware that some new devices can be named "Xiaomi Band 3".
The fix will be in 0.33.1 which we will release really soon

**Comment by corrugated** [comment]
Thanks for your quick response and your fix. I guess it's easiest for me to just wait for the new version.

After unpacking the band I first tried it with Gadgetbridge and had the same problem, so it likely had this name from the beginning. The packaging shows production date as 01/2019, if that is of any help.

**Comment by ashimokawa** [comment]
@corrugated 
Thanks. I would also be interested in your HW revision, we need to collect them somewhere and then clean up the FW update to only allow the correct firmware (it seems newer mi band 3 are "Mili_hankou.fw")

Also we tagged 0.33.1, it should be on f-droid soon (1-2 days usually)

**Comment by corrugated** [comment]
@ashimokawa 
Thanks for your help, it does work now with the new version 🙂
My HW revision is V0.18.4.5
I don't know what the correct firmware is for my band, is this something I can look up somewhere or do I have to find out with try and error?
