### ISSUE TITLE
Some Wiki pages at codeberg.org don't open

### ISSUE THREAD

**Issue by foolsbazar** [Freeyourgadget/Gadgetbridge#1524]
Sorry to report it here but i have no idea where to report this type of issue.
All wiki pages at [https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/_pages](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/_pages) that have a parenthesis in the URL do no work. i.e. Mi Band (1), Mi Band 2 (HMZK) Font Format, Pebble 2 (BTLE) specifics.
From the github mirror they do but, since the official wiki is at codeberg.org, and the github repo is only a mirror of it, i thought it was important to report.

**Comment by ashimokawa** [comment]
Thanks, I will rename them!

**Comment by ashimokawa** [comment]
Done
