### ISSUE TITLE
MiBand3 Please whitelist firmware 2.4.0.12

### ISSUE THREAD

**Issue by vanous** [Freeyourgadget/Gadgetbridge#1530]
Omg, this was my first time i flashed MB3 with GB, worked much better then with official app.

![Screenshot_20190601-213526_Gadgetbridge](https://user-images.githubusercontent.com/3680926/58752821-924d5780-84b5-11e9-8db8-f0cdd6ff3fd7.jpg)

**Comment by ashimokawa** [comment]
Yes, will do. However setting the menu items requires master, latest release wont work...

**Comment by vanous** [comment]
Perfect, thank you. Yes, I have noticed that commit. What if I use the visible item menu now, will timer menu disappear?

**Comment by DazzyWalkman** [comment]
You can have the new timer item on your band, no way to disable it in current GB release though.
