### ISSUE TITLE
Alarm mi band 3 help

### ISSUE THREAD

**Issue by lokk3d** [Freeyourgadget/Gadgetbridge#1532]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Hi, i need to set alarm on my mi band 3. How i can do it? I cannot find how to do this.

#### Your wearable device is:
Mi band 3

#### Your android version is:
8.1

#### Your Gadgetbridge version is:

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
In the main activity in the "Mi Band 3" device card, tap on the alarm clock icon.
