### ISSUE TITLE
Heart Rate Measurement Interval

### ISSUE THREAD

**Issue by zwm1210500550** [Freeyourgadget/Gadgetbridge#1533]
Hi, I am trying to set the heart rate measurement interval to 5 seconds, and what I've found is that the minimum interval is 1 minute.
So I think you would like to teach me how to set the heart rate measurement interval to second level ?  : )

**Comment by ashimokawa** [comment]
You cannot. 1 minute is the minimum interval for standalone hr measurements.

When connected it would be possible by switching on real time hr data measurements. You can swipe to the right "Live Activity"-Tab in the statistics to do that.
