### ISSUE TITLE
Version 0.34.0 not posted to F-Droid.

### ISSUE THREAD

**Issue by ee-gary** [Freeyourgadget/Gadgetbridge#1538]
The latest version (Version 0.34.0) has not posted to F-Droid.

**Comment by ashimokawa** [comment]
Fdroid is a black box to us, we just tag.

**Comment by IzzySoft** [comment]
The last index update at F-Droid was 4 days ago, so it might well be available with the next update. Signing and releasing the index always is a manual step done by Ciaran – so only Ciaran knows when that's to happen, not even we maintainers can tell.

**Comment by ashimokawa** [comment]
https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/When-will-a-new-release-appear-on-f-droid

**Comment by ashimokawa** [comment]
I mean - really, we explained that so many times, over and over and over again, it is hard to keep calm - really.

**Comment by IzzySoft** [comment]
Thanks for bringing that wiki page to attention, @ashimokawa – I just took the freedom to bring it up-to-date :wink:
