### ISSUE TITLE
App contextmenu font color always black for some themes (Flux)

### ISSUE THREAD

**Issue by githtz** [Freeyourgadget/Gadgetbridge#154]
This probably needs some kind of flag to support different design themes?
![asdrasd](https://cloud.githubusercontent.com/assets/15327800/10764742/d6e12f1c-7ccf-11e5-9587-be1f3b14c9dc.jpg)

**Comment by ashimokawa** [comment]
@githtz 
Thanks for reporting. I will look into it.

**Comment by IzzySoft** [comment]
With no more activity for almost 4 years, I assume we can close this. Let me know if I was wrong so I can stand corrected :wink:
