### ISSUE TITLE
Wrong date format in 'Clock' mode for Italian translation

### ISSUE THREAD

**Issue by mfvescovi** [Freeyourgadget/Gadgetbridge#1544]
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### My issue is:
while using Gadgetbridge to control my Mi Band 3 I've noticed that date format in 'Clock' mode is wrongly displayed, as it shows "6/21 Ven" (as per MM/dd format) instead of "21/6 Ven" (in Italy, date format is dd/MM). This issue doesn't show up while using up-to-date Mi Fit application.

#### My wearable device is:
Xiaomi Mi Band 3 (firmware version: 2.4.0.12)

#### My Android version is:
9

#### My Gadgetbridge version installed is:
0.34.0

**Comment by ashimokawa** [comment]
Bluetooth hci dumps are welcome when connecting to mi fit, I haven't found out how to change that yet
