### ISSUE TITLE
Mi Band: Missing progress bar for activity sync

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#155]
Since GB version 0.6.4 the progress bar for the activity sync process in Androids pull-down menu seems to be missing on my device. When I sync, I now only see two "busy" indicator cycles in the apps main menu – both on the Mi Band tab: one on the right (as it has been in GB versions before) and a new one in the middle.
The issue persists in GB 0.6.5.

Mi Band FW version: 1.0.10.14
GB version: 0.6.4/5
I'm using an Samsung Galaxy S3 with Cyanogenmod 11 (Stable).

**Comment by cpfeiffer** [comment]
I just checked the diff between 0.6.3 and 0.6.4 and couldn't find anything that could potentially cause this behavior change. Are you really sure that the progress bar was shown in 0.6.3?

**Comment by 6arms1leg** [comment]
Yes, I'm absolutely sure there was a progress bar in GB 0.6.3.
Maybe it's an issue with my device. But I didn't change anything on my device since then, I only updated GB via F-Droid. 

Thanks for your help!

**Comment by cpfeiffer** [comment]
Can you confirm that this indeed fixes it on KitKat? Will be in 0.6.9.

**Comment by 6arms1leg** [comment]
Sorry for the bad news, but the issue still persists in GB 0.6.9.
I synchronized 7 days of activity data, which took a while, but there is still no progress bar in Android's drop-down menu. Besides installing the new GB version I didn't make any other changes on my device.

**Comment by cpfeiffer** [comment]
Too bad ;-(

Then I need debugging help from someone with a kitkat device. Alternatively I could instrument the code to print lots of debug output for you..

**Comment by ashimokawa** [comment]
I can test pebble stuff on a kitkat device. I will check if  pebble related progress bars are there, but I assume there will be.

**Comment by cpfeiffer** [comment]
Does it have BLE? Then we can test the Mi Band activity sync as well.

**Comment by ashimokawa** [comment]
No, it doesn't.
But I can multi boot kitkat on my nexus 7, which has BLE

**Comment by cpfeiffer** [comment]
@ashimokawa yes, please check whether progress bars in the notification area work. Especially those created with GB#createNotification().

**Comment by IzzySoft** [comment]
Closing this as stale. Should you still fight the issue with recent versions of GB, device, firmware etc. please comment and we can reopen.
