### ISSUE TITLE
Czech language not supported by device, some custom filtering options?

### ISSUE THREAD

**Issue by freed00m** [Freeyourgadget/Gadgetbridge#1558]
#### Before requesting a new feature, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

Some letters are not supported by the device, that issue is persistent on the original firmware even if used with original xiaomi track app.

Letters like "č", "ý" and others are displayed like a questionmark inside a box.

I know it is not technically Gadgedbridge's limitation as you send it correctly in UTF-8 but a Xiaomi's one and it is over a year unfixed by them.

Would it be possible to add ability to customly strip diacritics from notifications? Something similar to the deemojifying but user custom. 

![20190716_152443](https://user-images.githubusercontent.com/9461698/61299402-4bef5600-a7e0-11e9-9a30-618a0c0a850e.jpg)

#### Your wearable device is: Xiaomi Mi band 3

FW 2.4.0.12
HW V0.18.4.1

**Comment by ashimokawa** [comment]
@freed00m 
If you set the language to German, all the characters you posted work.
English does not work :/
Polish and other European languages should also work.
If you can make sense of any of those, you might want to try...

Also you might have to flash Mili_wuhan.ft if you haven't already. If you flash the .kj font you will be forced to use korean or japanese.

**Comment by freed00m** [comment]
@ashimokawa Yes changing the language to German works well.
Shame It's broken for Czech. :O how hard it could be t fix.

I will try to flash Mili wuhan at some point.

**Comment by ashimokawa** [comment]
@freed00m 
There is no Czech support for mi band 3, right?
I someone does a community translation, he should use German as a base not English.
And yes, it is stupid that changing the language changes character sets. :/

**Comment by freed00m** [comment]
@ashimokawa - No I don't think so.
I think there are some community translation already. But I did not touch the FW yet.

**Comment by vanous** [comment]
@freed00m gadgedbridge is 100% translated to Czech. But, unrelated to that, you can simply enable the transliteration feature: _menu → Settings → Language and region settings → Transliteration_ , after that ěščřžýáíéúů... in messages or caller names will no longer be an issue for you.

**Comment by freed00m** [comment]
@vanous Ha, never noticed it was already implemented, was searching in the device options.

**Comment by ashimokawa** [comment]
Per-device settings are new since 0.34.0, 
Transliteration belongs there and will be moved.

**Comment by CornyjK** [comment]
On Mi Band 2 I fixed it by making my own font, but it has some issues too.
