### ISSUE TITLE
Compiler error 0.34.1 R.xml.devicesettings_dateformat

### ISSUE THREAD

**Issue by Lightwars** [Freeyourgadget/Gadgetbridge#1559]
#### Your issue is:
Commit https://github.com/Freeyourgadget/Gadgetbridge/commit/8d50e8ef08cb235116d3a886ec1effc9f9b5182f introduces a compiler error, because devicesettings_dateformat.xml is missing

#### Your Gadgetbridge version is:
0.34.1

**Comment by ashimokawa** [comment]
Thanks, fixed.
Unfortunately travis is quite crappy, and I do not have time to fix it.
