### ISSUE TITLE
Mi Band: Connectivity improvement?

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#156]
After trying most of the firmwares for my Mi Band with the recent GB versions, I noticed some connectivity issues when I closed the app and tried to re-connect my Mi Band again afterwards. It often takes several tries with closing and re-opening GB until I can re-connect. I think (hard to measure) this issue has improved with FW 1.0.10.14, but it's still there.
Do you have the same problem?
Is there any chance, this can be improved or might it be an issue with my device's BT capabilities (Samsung Galaxy S3, Cyanogenmod 11 (stable)) or is it an issue with the Mi Band itself?
Thanks for your help!

**Comment by cpfeiffer** [comment]
Thanks for opening this issue. We do experience the same thing and will find a fix for this.

A small improvement for you: you don't need to quit Gadgetbridge in order to make another connection attempt. You can simply long-press the device item and press "Disconnect" and connect again.

**Comment by cpfeiffer** [comment]
For reference:
- http://stackoverflow.com/questions/27017224/why-the-app-doesnt-reconnect-to-the-ble-device-when-set-autoconnect-to-true-in
- http://stackoverflow.com/questions/24763204/android-ble-automatic-re-connect-after-spontaneous-disconnect

**Comment by 6arms1leg** [comment]
Just a note: I have the impression that it is working better sometimes when you choose "connect new device" from the menu on the start screen during the connection process. I could be wrong though (again, it's hard to measure).

**Comment by jmferrer** [comment]
MiBand has a FW  5.15.10.14 and I have connectivity issues so I cannot use notifications. Is there any FW version that works well with gadgetbridge?

**Comment by cpfeiffer** [comment]
See https://github.com/Freeyourgadget/Gadgetbridge/wiki/MiBand-Firmwares-information

You can upgrade and downgrade firmware with Gadgetbridge, but we do not provide these files.

**Comment by cpfeiffer** [comment]
This should be fixed by now. See #249 for details.
