### ISSUE TITLE
Dead link to pebble 3.12.3 FW

### ISSUE THREAD

**Issue by McPcholkin** [Freeyourgadget/Gadgetbridge#1561]
Hi, I found link to 3.12.3 FW on this page is dead.
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Firmware-updates

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>pebblefw</BucketName>
<RequestId>368CCCEB06046968</RequestId>
<HostId>
AHkWJEBT0c3W2eOfQRQfXlgWP+KPIPL8gdno8oKw01qDrT6mmi/IxU1wKagXjLeW6KKj/PbZZqI=
</HostId>
</Error>
```

**Comment by SDohle** [comment]
I'm looking for the firmwares for the Peble Steel too. But the links to the migration FW 3.8-mig10 and to the FW 3.12.3 are both dead.

Can you reupload the files?

**Comment by IzzySoft** [comment]
@SDohle if you take a look at those links and where they point to you'll notice they were not uploaded by the GB project but by Pebble itself. I'm not sure if their copyright would permit a 3rd party to "reupload" the firmware somewhere. And Pebble obviously won't do so (as the company no longer exists). If Fitbit (who bought them) would do that, I don't know.

Should you happen to find some official sources, they're of course welcome!

**Comment by ashimokawa** [comment]
We should remove the links if they are dead.

**Comment by IzzySoft** [comment]
Unless there's a copy somewhere. Though I couldn't find any yet. Maybe adding a note, interim-wise (like, "these links are currently dead. If you know where the files are available …"). Easier to find a copy if you know the original URL.

**Comment by IzzySoft** [comment]
Bingo, found them: https://github.com/aveao/PebbleArchive/tree/master/Firmware

**Comment by IzzySoft** [comment]
OK, updated the wiki ([at Codeberg](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Pebble-Firmware-updates)) with the links I found (just the ones to the latest version were available at the "backup site").

@ashimokawa please cross-check my edit to make sure everything is fine. I've striked the ones I couldn't replace, and also added a disclaimer on top of the downloads.

@McPcholkin I hope the new links help you. You might wish to wait for @ashimokawa 's confirmation before downloading – but however, do so at your own risk. There's no way to verify those files (unless you happen to have them already from the original location). Thanks for reporting!

**Comment by ashimokawa** [comment]
Would be cool to have Firmware 4.4 - it is real, and done with permission from fitbit

**Comment by IzzySoft** [comment]
Oh, for snowy as well? I thought 4.3 was the last I'd ever see. I have the older ones (4.3 and below) for snowy on my disk, so if it's "legally fine" and someone finds it useful, I could upload them if told where to.

**Comment by McPcholkin** [comment]
@IzzySoft i check MD5 of **Pebble-3.12.3-v2_0.pbz** and it match with my "backup copy"
