### ISSUE TITLE
"Amazfit Band 2" displays no items since 0.34.0 release

### ISSUE THREAD

**Issue by wscherr** [Freeyourgadget/Gadgetbridge#1563]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

Thanks a lot for your work and this nice app!

#### Your issue is:

Since 0.34.0 the band does not display any items (no actual data, no alarm settings, no setup menu, ...) --> on a swipe down on the band, just a black screen is shown. On a swipe up on the band, I can just enable/disable DND. That's it.

I also have a Bip and I noticed that there is a "Display items" in the config menu of the "Amazfit Bip Watch" band. This menu is missing on the "Amazfit Band 2" settings (there is only the "Auth Key" setting, nothing else). I could not find any alternate way to configure (e.g. via the generic setup menu or so and no more clues provided in the Wiki). This seems to be part of the changes made for the 0.34.x versions of the app and seems to be incomplete for the Band 2, as this worked with 0.33.x versions.

When I start the Mi Fit App and connect, the different diplay items are back on the band. So I suppose this missing configuration in the Gadgetbridge app for this type also causes to disable all display items on the band when connecting?

Readout of fitness data, weather update on main screen, date/time settings seems to work normal. Also alarms work, but can't be enabled/disabled on the band directly missing the possibility to select the item.

#### Your wearable device is:

"AMAZFIT Band 2 (Cor2) Smartwatch"

hardwareRevision='V0.21.19.39'
softwareRevision='V0.3.0.44'

This is the latest after installing the Mi Fit application and connecting the band.

#### Your android version is:

6.0.1

#### Your Gadgetbridge version is:

actual 0.34.1 installed via f-droid (but same problem on 0.34.0)

**Comment by thbaumbach** [comment]
I can confirm this, happens on my "AMAZFIT Band 2" too
I have the same hardwareRevision and softwareRevision running

But I tried 0.33.x and it DIDN'T work neither, which is weird 😞
I'm currently using Mi Fit as a replacement.

**Comment by ashimokawa** [comment]
I missed that for the 0.35.1 release :/ Will be in 0.35.2

**Comment by wscherr** [comment]
> 
> #### Before reporting a bug, please confirm the following:
> 
>     * [x]  I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
> 
>     * [x]  I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
> 
>     * [x]  If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)
> 
> 
> Thanks a lot for your work and this nice app!
> #### Your issue is:
> 
> Since 0.34.0 the band does not display any items (no actual data, no alarm settings, no setup menu, ...) --> on a swipe down on the band, just a black screen is shown. On a swipe up on the band, I can just enable/disable DND. That's it.
> 
> I also have a Bip and I noticed that there is a "Display items" in the config menu of the "Amazfit Bip Watch" band. This menu is missing on the "Amazfit Band 2" settings (there is only the "Auth Key" setting, nothing else). I could not find any alternate way to configure (e.g. via the generic setup menu or so and no more clues provided in the Wiki). This seems to be part of the changes made for the 0.34.x versions of the app and seems to be incomplete for the Band 2, as this worked with 0.33.x versions.
> 
> When I start the Mi Fit App and connect, the different diplay items are back on the band. So I suppose this missing configuration in the Gadgetbridge app for this type also causes to disable all display items on the band when connecting?
> 
> Readout of fitness data, weather update on main screen, date/time settings seems to work normal. Also alarms work, but can't be enabled/disabled on the band directly missing the possibility to select the item.
> #### Your wearable device is:
> 
> "AMAZFIT Band 2 (Cor2) Smartwatch"
> 
> hardwareRevision='V0.21.19.39'
> softwareRevision='V0.3.0.44'
> 
> This is the latest after installing the Mi Fit application and connecting the band.
> #### Your android version is:
> 
> 6.0.1
> #### Your Gadgetbridge version is:
> 
> actual 0.34.1 installed via f-droid (but same problem on 0.34.0)



> 
> 
> I missed that for the 0.35.1 release :/ Will be in 0.35.2

Just did the update to 0.35.2, the band shows all items again I have selected in the setup section now visible again. Perfect, thanks a lot for your quick response!
