### ISSUE TITLE
Delete from the app

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#157]
It looks like I can not delete devices from the app.

In addition to that, a Pebble time LE device appeared followed with the same id as the one I already have.

![screenshot_2015-10-30-13-42-14](https://cloud.githubusercontent.com/assets/291750/10845982/6d9cb460-7f0c-11e5-8942-90b098655d94.png)

**Comment by cpfeiffer** [comment]
We should probably ignore the LE version as long as we don't support its protocol.

**Comment by roidelapluie** [comment]
On 04 Nov 14:17, Carsten Pfeiffer wrote:
> We should probably ignore the LE version as long as we don't support its protocol.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Freeyourgadget/Gadgetbridge/issues/157#issuecomment-153886755

Can you then add the 'enhancement' tag to this issue? thanks

-- 
 (o-    Julien Pivotto
 //\    Open-Source Consultant
 V_/_   Inuits - https://www.inuits.eu

**Comment by ashimokawa** [comment]
Why can't you just unpair the Pebble Time LE XYZ? in Androids settings?
We can additionally ignore the LE variant for people who insist in having these paired, for whatever reason.
AFAIK Pebble makes use of LE ONLY on iOS anyway.

**Comment by roidelapluie** [comment]
ooooh okay. This was not obvious for me that I needed to unpair in system settings.
