### ISSUE TITLE
Actvities doesn't synchronize after deleting them

### ISSUE THREAD

**Issue by giupardeb** [Freeyourgadget/Gadgetbridge#1585]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I accidentally deleted all activities from the application. When I try to synchronize all activities, the application doesn't to do it. Inside my amazfit bip I see all the activities.

#### Your wearable device is:

*amazfit bip FW 1.1.5.56*

**Comment by vanous** [comment]
Not sure, just an idea: in the menu of the activities in GB, there is the reset fetch day, try setting it on a date before the activities. But I tried and for me this didn't work unfortunately.

**Comment by giupardeb** [comment]
Unfortunately, your idea didn't work. This is a important bug

**Comment by giupardeb** [comment]
I investigated and discovered that inside /sdcard/Android/data/nodomain.freeyourgadget.gadgetbridge/files/ there are all gpx files of my runs. @vanous Do you have that files?

**Comment by giupardeb** [comment]
`    private void fetchTrackData() {
        if (mGBDevice.isInitialized() && !mGBDevice.isBusy()) {
            GBApplication.deviceService().onFetchRecordedData(RecordedDataTypes.TYPE_GPS_TRACKS);
        } else {
            swipeLayout.setRefreshing(false);
            if (!mGBDevice.isInitialized()) {
                GB.toast(this, getString(R.string.device_not_connected), Toast.LENGTH_SHORT, GB.ERROR);
            }
        }
    }`

I believe that this function must recover the data in the files folder

**Comment by vanous** [comment]
> I investigated and discovered that inside /sdcard/Android/data/nodomain.freeyourgadget.gadgetbridge/files/ there are all gpx files of my runs. @vanous Do you have that files?

yes, i do.

**Comment by giupardeb** [comment]
> ```
>     private void fetchTrackData() {
>         if (mGBDevice.isInitialized() && !mGBDevice.isBusy()) {
>             GBApplication.deviceService().onFetchRecordedData(RecordedDataTypes.TYPE_GPS_TRACKS);
>         } else {
>             swipeLayout.setRefreshing(false);
>             if (!mGBDevice.isInitialized()) {
>                 GB.toast(this, getString(R.string.device_not_connected), Toast.LENGTH_SHORT, GB.ERROR);
>             }
>         }
>     }
> ```
> 
> I believe that this function (inside ActivitySummariesActivity.java) must recover the data in the files folder

@ashimokawa what do you think?

**Comment by vanous** [comment]
I haven't looked at the code right now,  but tested that the exported filed can have zero size, and the export then doesn't work.  Erasing these zero size gpx files worked for me to re-fetch sports activities.

**Comment by ashimokawa** [comment]
@giupardeb 
This is fixed in master and will be in the next release. resetting the fetched date was broken.

**Comment by vanous** [comment]
yay! :+1:

**Comment by giupardeb** [comment]
GOOD!!!
