### ISSUE TITLE
Create a Channel telegram 

### ISSUE THREAD

**Issue by giupardeb** [Freeyourgadget/Gadgetbridge#1586]
I believe to create a channel on telegram allow us to interchange information/FAQ and report issues more efficiently

**Comment by giupardeb** [comment]
A lot project have a related channel. It was an idea

**Comment by IzzySoft** [comment]
Sure, I wasn't COMplaining – just EXplaining why it will be unlikely to happen :wink:

**Comment by JokerGermany** [comment]
Why should the "OpenSource-Fan" Developer use telegram? A walled garden?
XMPP or Matrix, ok, but why telegram?
