### ISSUE TITLE
Update Mi Band 3 wiki: new firmware version

### ISSUE THREAD

**Issue by rffontenelle** [Freeyourgadget/Gadgetbridge#1588]
#### Before reporting a bug, please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

There is a new firmware version, and I would like to update [Mi Band 3 wiki page](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-3-Firmware-Update) but I don't seem to be allowed to do so. Here are the last Mi Fit versions:
 - 4.0.3 - is documented already (I added myself in June)
 - 4.0.5 - same .fw and .res as 4.0.3
 - 4.0.6 - _new_ .fw version `2.4.0.20` with md5sum `e78ca23d38afd0d0ab15778f67a09072`; same .res as 4.0.5
 - 4.0.7 - same .fw and .rew as 4.0.6 

My suggestion is to replace 4.0.3 with 4.0.5 (since it is the same .fw and .res), and include an entry for 4.0.7.

#### Your wearable device is:

Mi Band 3
FW: 2.4.0.20
HW: V0.18.4.3

#### Your android version is:

8.0.0

#### Your Gadgetbridge version is:

0.35.2

**Comment by vanous** [comment]
@rffontenelle excuse me if you know... you must edit wiki on codeberg, not on github ( https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-3-Firmware-Update ). I have now added the notice on wiki home page too.

**Comment by rffontenelle** [comment]
*facepalm* - I totally forgot about it, sorry. Thanks for adding the notice to the wiki home page too.
