### ISSUE TITLE
Mi Band 4: Get rid Alipay from CN version

### ISSUE THREAD

**Issue by ekacahya21** [Freeyourgadget/Gadgetbridge#1595]
Hi, is there any way to get rid alipay feature on Mi Band 4 CN version using Gadgetbridge?

**Comment by IzzySoft** [comment]
Are you using the device with Gadgetbridge – or with some other app? As Gadgetbridge doesn't even have the permission for Internet access, that should mean you *are* rid of the feature (not using a Mi:4, I don't even have an idea what that feature should do).

**Comment by ashimokawa** [comment]
@ekacahya21 
You mean the menu on the band when swiping left or right?
Currently Gadgetbridge cannot disable it but I think it would be possible. Maybe in a later version.

**Comment by ekacahya21** [comment]
Yes, since Alipay is not very useful outside of China, hopefully gadgetbridge can override swipe right/left feature.
But, is it possible to manually update with global firmware instead? because on Mi Fit will automatically update the firmware through OTA

**Comment by ashimokawa** [comment]
@ekacahya21 
I updated my Mi Band 4 NFC CN with the global non-NFC firmware, and that did not change anything. Band is still in only in chinese/english, no other languages. Also Alipay is still there.

And unfortunately, after investigated, I do not think it is possible to disable the menu...

**Comment by FransM** [comment]
I did upgrade a non NFC CN with global software, but that still gives the AliPay menu.
I'm not sure if the lAliPay option is also present if you buy a global device.
(It seems that even after installing the global software the mi band 4 has some settings that give away that it was originally a CN version. E.g. the default language on an upgraded CN device is still chinese whereas the default language in a global device is English)

**Comment by ekacahya21** [comment]
Hi all, thank you for your answers and support. 

Great work for all contributors with Gadgetbridge :)
