### ISSUE TITLE
Mi Band 4 NFC firmware version

### ISSUE THREAD

**Issue by ViBE-HU** [Freeyourgadget/Gadgetbridge#1601]
Hey there. I just noticed that the [list](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-4-Firmware-Update) is not complete. I have an NFC variant and it has version:
- 1.0.5.39 firmware
- v54 resources
- v1 fonts

These are the latest ATM. Since I don't know how to dump it I only know these informations. But I guess the resources are common so it could be the same what the standard variant has before.

**Comment by ashimokawa** [comment]
Even the latest non-NFC Firmware is compatible with the NFC Variant without losing any functionality. 

Split firmwares are a myth so far.

**Comment by ViBE-HU** [comment]
maybe your right. but i'm not sure since updating will stuck if i install v56 resources on 1.0.5.39.

**Comment by ashimokawa** [comment]
I am sure. I did it myself and flashed fw, then res. All with Gadgetbridge.

**Comment by ViBE-HU** [comment]
> 
> 
> I am sure. I did it myself and flashed fw, then res. All with Gadgetbridge.

then could you please help me how can i install the latest firmware and res with it? as far as i understand the version what is available in Google Play is incompatible with the Band 4.

**Comment by ashimokawa** [comment]
@ViBE-HU 
We do not support the "google play version". This is not ours, it is unofficial and usually outdated.
In #1536 you should see a lot of hints about how to get Gadgetbridge running with the official release currently at 0.35.2.
