### ISSUE TITLE
Sleep Button

### ISSUE THREAD

**Issue by eggnog514** [Freeyourgadget/Gadgetbridge#1602]
#### Before requesting a new feature, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*If applicable, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)*

#### Your wearable device is: Mi Band 3, 2.4.0.20

*Please specify model and firmware version if possible*

#### Your Gadgetbridge version is: 0.32.1

I would love to see a Sleep Button just like Battery/Fetch/ Alarms to make viewing sleep quicker.

*New requests about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by vanous** [comment]
Icon Activity? Perhsp your version is too old? Current version is 0.35.2

![Screenshot_20190815-222257_Gadgetbridge_1_1](https://user-images.githubusercontent.com/3680926/63124515-c2cc6a00-bfab-11e9-89ec-46c68267a12b.jpg)

**Comment by eggnog514** [comment]
thank you and the app works fine. i recently downloaded the app from the Play store instead of F-droid so its older but has this chart. i clicked on the chart the first day and didnt see sleep since it didnt backtrack that data then noticed it the second day however i dont believe i used this chart button to access it.

**Comment by vanous** [comment]
Perfect. So all is good now?

**Comment by eggnog514** [comment]
yes sir!

**Comment by vanous** [comment]
Please close this issue then. Cheers :+1:
