### ISSUE TITLE
Mi Band 4 stuck on pairing

### ISSUE THREAD

**Issue by xeals** [Freeyourgadget/Gadgetbridge#1608]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

Attempting to connect to a new Mi Band 4 resulting in endlessly being stuck on the pairing screen after tapping on the device. A Bluetooth connection is established, notifications, etc. push to the device, but it's not added to the device list or database, and the Gadgetbridge status notification is stuck on "connecting". Tested on both an existing install (Mi Band 3 already in database) and fresh install.

[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/3533301/gadgetbridge.log)

#### Your wearable device is:

Mi Band 4, V1.0.5.66.

#### Your android version is:

Lineage OS 16 (20190812).

#### Your Gadgetbridge version is:

0.35.2.

**Comment by IzzySoft** [comment]
Related: #1536 – can you please check there? Especially [this post](https://github.com/Freeyourgadget/Gadgetbridge/issues/1536#issuecomment-517989483) could give you a clue (as you don't mention its content at all).

**Comment by xeals** [comment]
Sorry, I read the wiki so many times and still managed to miss the obvious instructions. Closing as user error.

**Comment by IzzySoft** [comment]
Glad the issue solved for you! And thanks for "cleaning up" 😄

**Comment by fam4r** [comment]
@xeals how did you solve?

**Comment by xeals** [comment]
I wasn't long pressing on the band in the discovery screen to be able to set the auth key.
