### ISSUE TITLE
MiBand 4 Answer/Decline call on phone band keeps vibrating

### ISSUE THREAD

**Issue by buffal0b1ll** [Freeyourgadget/Gadgetbridge#1612]
I used to use MiBand 3 on Gadgetbridge on same device and I can't remember this same behavior.
Phone calls notification set to Short 1.  When incoming call comes in band vibrates.  When angering or dismissing call on phone the band keeps vibrating until you dismiss on the band.
Desired behavior would be to have the band dismiss it's notification when the call is acted upon on the device.
Thanks

**Comment by ashimokawa** [comment]
@buffal0b1ll 
Please do not delete the issue template. It is there for a reason.
So, which android version do you have, did you grant all permissions?

**Comment by tomcat-xx** [comment]
Hello, here requested data for my devices, because having same issue. I granted all permissions.

**Wearable device is:**
Mi Band 4
FW: 1.0.5.55

**Android version is:**
8.0.0

**Gadgetbridge version is:**
0.35.2

**Comment by ashimokawa** [comment]
@tomcat-xx 
Thanks!
I assumed this is some android problem and we do not have the correct permissions to listen for call changes but it turns out that this is a probably a protocol change on the mi band 4. I can reproduce by using the debug menu start call/end call. These work for Mi Band 3 but not for Mi Band 4

**Comment by buffal0b1ll** [comment]
FW 1.0.5.55 (upgraded to 1.0.5.66)
App 0.35.2 (upgraded to 0.36)
Android 9.0
All permissions granted

Same behavior I found when use FIND DEVICE button, dismissing with FOUND IT
on phone doesn't stop the band from vibrating.  Have to manually dismiss
the vibration on the band

--expect crazy typos--

**Comment by tomcat-xx** [comment]
Also fixed now. Thanks. No more touching stop button with nose when starting the call with one hand while other is still vibrating ;-)
