### ISSUE TITLE
Crash when editing notification filter

### ISSUE THREAD

**Issue by Nephiel** [Freeyourgadget/Gadgetbridge#1614]
#### Before reporting a bug, please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

How to reproduce:
Open Gadgetbridge -> Tap hamburguer **menu** on top left -> Tap **Notification blacklist**.
Find any app in the list with **NOTIF** unchecked, and tap the hamburguer **button on the right**.

Expected result: Open notification filter settings for the selected app.

Actual result: either no action, or a crash, returning to main Gadgetbridge activity.

*If possible, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)! that might help identifying the problem.*

Possibly relevant line in logcat:
`AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.constraint.ConstraintLayout" on path
`
#### Your wearable device is:

*Please specify model and firmware version if possible*
Any (reproducible on a clean install with no devices configured)

#### Your android version is:

Android 9

#### Your Gadgetbridge version is:

0.36.0

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by Nephiel** [comment]
I tried applying https://stackoverflow.com/a/54207316 to `activity_notification_filter.xml`.
Fix works for me, filter dialog opens without crashing.

**Comment by ashimokawa** [comment]
@Nephiel 
Thanks! Will apply the fix tonight.
