### ISSUE TITLE
broken wiki link

### ISSUE THREAD

**Issue by FransM** [Freeyourgadget/Gadgetbridge#1615]
At the right hand menu on https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Home there is a link for ReadMe.
This expands to https://codeberg.org/Freeyourgadget/Gadgetbridge/tree/master/README.md but if I click on the link I get a 404.
As I an new with GB I have no clue yet what the link should be, hence this ticket.

**Comment by vanous** [comment]
That link works when the wiki is used here on github.

**Comment by IzzySoft** [comment]
And what would work on Github wouldn't on Codeberg (Gitea uses `src/branch` where Github uses `tree`). With Codeberg being the primary, maybe it should be changed to Codeberg syntax (and to make sure it works when called from Github, using the fully qualified URL)?

**Comment by ashimokawa** [comment]
https://codeberg.org/Freeyourgadget/Gadgetbridge/src/README.md

expands to

https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/README.md

and we can link there

**Comment by ashimokawa** [comment]
Done

**Comment by FransM** [comment]
thanks!
