### ISSUE TITLE
mi band 4 authentication

### ISSUE THREAD

**Issue by FransM** [Freeyourgadget/Gadgetbridge#1617]
Not sure if this is to be reported as an issue but better safe than sorry.

In https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-4 it requires a rooted shell to get the auth key.

As my phone is not rooted I could not use this but
https://www.freemyband.com/
can also be used to retrieve the key. I tried this and it worked for me.

I'm not sure if this should be listed on the page as alternate method.
Or maybe the method applied by freemyband could be incorporated into Gadgetbridge
(Note that I know nothing about freemyband apart from being a happy user).

**Comment by ashimokawa** [comment]
@FransM 
Thank you for pointing that out.
I think it would be okay to link the site when making clear that we do not know whether the apks linked are safe or not and that we no not recommend or support them.

**Comment by FransM** [comment]
Thanks, added this to the wiki:

> On a non rooted phone you may consider using https://www.freemyband.com/ **NOTE that the procedure described there is not encouraged or supported by the Gadgetbridge developers and the devs have no information on that app and whether it is safe to use**

Feel free to rephrase (English is not my native language).

I'm not exactly sure how fetching the auth key is achieved, but I suspect that the original MiFit app is disassembled and modified.

**Comment by FransM** [comment]
updated the wiki 
https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-4#requirements
