### ISSUE TITLE
odd sleep data report

### ISSUE THREAD

**Issue by FransM** [Freeyourgadget/Gadgetbridge#1620]
### I got Gadgetbridge from:
* [x ] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

#### Your issue is:
I noticed something odd today.
Yesterday I woke up at 8.40.
This morning I woke up at 8.16 and checked the "my sleep" tab at 8:25
It told me I slept from 8:25 until 8.16 This looks very odd.
See attached screenshot.

![Screenshot_20190901-082535](https://user-images.githubusercontent.com/1893299/64081581-7ac77a00-cd03-11e9-9a79-bb1b515a1df3.png)

Apparently what happened is that the last part of my sleop of the day before was taken as the start of the sleep.

Maybe we should say that the start of sleep is always after 12.00 mid day (or make this a config item)

#### Your wearable device is:

Mi Band 4 FW 1.0.5.66

#### Your android version is:
7.1.1

#### Your Gadgetbridge version is:
0.36

**Comment by tomcat-xx** [comment]
Same for me. But when I remember right, later same day it was displayed correctly.

But anyway sleep recognition with bands is not really good. For me I think there should be deep sleep phases ... in the night ... as my first recorded one was in the office ;-)

**Comment by FransM** [comment]
I feel issue #1646 fixes the issue as the report does not cause the confusion reported in this ticket. As submitter of the ticket I am closing it.

**Comment by vanous** [comment]
@FransM also, the https://github.com/Freeyourgadget/Gadgetbridge/pull/1677 helps to limit the sleep time a bit. Can you please close this now, i think you forgot about it... :)
cheers

**Comment by FransM** [comment]
Will look at it tomorrow

Groetjes, Frans 
 
  Op za, okt. 12, 2019 om 18:16 schreef vanous<notifications@github.com>:   
@FransM also, the #1677 helps to limit the sleep time a bit. Can you please close this now, i think you forgot about it... :)
cheers

**Comment by FransM** [comment]
Thought I already closed this, not sure why that did not come through. Closing again
