### ISSUE TITLE
skip small sleep times

### ISSUE THREAD

**Issue by FransM** [Freeyourgadget/Gadgetbridge#1621]
Today I noticed my Mi Band 4 recorded a short sleep while I was not sleeping but actually I was just reading the paper at the kitchen table.  I'm not sure if this was related to the way I wore the band, but this shows up as the new sleep end time in "your sleep".
It might be better to filter out sort sleeps (as false reading).
And, if there are more sleep intervals (e.g. an afternoon nap", it may be better to say:
"You slept from xx:xx to yy:yy and from aa:aa to bb:bb"

Your wearable device is:

Mi Band 4 FW 1.0.5.66
Your android version is:

7.1.1
Your Gadgetbridge version is:

0.36

**Comment by tomcat-xx** [comment]
Did you activate "Use heart rate sensor to improve sleep detection"? I have, but cannot say if it helps. But maybe different for different users.

As I wrote in another issue I had my first deep sleep phase in office. Until now this did not happen again with above option activated. And luckily I'm using GB and not Mi Fit with direct connection to my boss through the cloud ;-)

**Comment by maurosandes** [comment]
I have the same problem Mi band 4 FW 1.0.6.16

**Comment by FransM** [comment]
Fix for issue #1646 ignores sleeps < 5 minutes. Seems a fair solution. 
Leaving this open for now as I would like to get feedback if the ignore time should be a configurable option

**Comment by vanous** [comment]
I would close thi,  in my opinion. If the need comes up, open a new issue.

**Comment by IzzySoft** [comment]
I agree with @vanous here, with a slight deviation: if the need arises, we can also reopen this one. Thanks everybody!
