### ISSUE TITLE
No message notified on Amazfit Bip

### ISSUE THREAD

**Issue by fvasco** [Freeyourgadget/Gadgetbridge#1624]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

### I got Gadgetbridge from:
* [x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

#### Your issue is:

I cannot receive notification on my watch, but these are available on the watch's backlog.

Same issue when I test vibration using this app: nothing happen on the watch. However if I inspect the message history on the watch then the test notification is present.

I have unlocked all app block without succes, moreover I tested the watch vibration and it works (when I unlock the scree the watch vibrates).
I updated the watch firmware, in vain.

#### Your wearable device is:

Amazfit Bip, tested with stock version `1.1.2.05`, then with `1.1.5.16`

#### Your android version is:

Android One 9

#### Your Gadgetbridge version is:

0.36.0

**Comment by LuccoJ** [comment]
Is DND mode enabled on the watch?

**Comment by vanous** [comment]
all works well here, on my watch with version 1.1.5.56

**Comment by fvasco** [comment]
> Is DND mode enabled on the watch?

@LuccoJ No, it isn't.
Calls are ignored (no vibrations and notifications), only notification but no vibration for QKSMS and Signal messages.
I set "always" to call notification option, and both "always" and "never" to SMS notification option.

> all works well here, on my watch with version 1.1.5.56

@vanous How I can download that firmware?
I am available for a test.

**Comment by vanous** [comment]
i have used the one from https://amazfitwatchfaces.com/

**Comment by fvasco** [comment]
Currently amazfitwatchfaces does not provide a publicly available download, so I does not perform any update.

I try "Find device" action, nothing happens on watch.

Here is the log:

~~~
08:25:06.725 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.36.0
08:25:11.371 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
08:25:12.980 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.find_device
08:25:12.982 [main] INFO  n.f.g.s.d.h.HuamiSupport - Sending notification to MiBand
08:25:12.983 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 08:25:12: Transaction task: incoming call with 1 actions
08:25:12.985 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 4 settembre, 08:25: WriteAction on characteristic: 00002a46-0000-1000-8000-00805f9b34fb
08:25:12.986 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 00002a46-0000-1000-8000-00805f9b34fb: 0x03 0x01 0x47 0x61 0x64 0x67 0x65 0x74 0x62 0x72 0x69 0x64 0x67 0x65
08:25:13.410 [Binder:4358_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 00002a46-0000-1000-8000-00805f9b34fb (success)
08:25:22.466 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.find_device
08:25:22.468 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 08:25:22: Transaction task: stop notification with 1 actions
08:25:22.470 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 4 settembre, 08:25: WriteAction on characteristic: 00002a06-0000-1000-8000-00805f9b34fb
08:25:22.471 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 00002a06-0000-1000-8000-00805f9b34fb: 0x00
08:25:22.475 [Binder:4358_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 00002a06-0000-1000-8000-00805f9b34fb (success)
08:25:22.737 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.find_device
08:25:22.738 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 08:25:22: Transaction task: stop notification with 1 actions
08:25:22.739 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 4 settembre, 08:25: WriteAction on characteristic: 00002a06-0000-1000-8000-00805f9b34fb
08:25:22.740 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 00002a06-0000-1000-8000-00805f9b34fb: 0x00
08:25:22.742 [Binder:4358_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 00002a06-0000-1000-8000-00805f9b34fb (success)
~~~

Is the second line meaningful?

**Comment by vanous** [comment]
>Currently amazfitwatchfaces does not provide a publicly available download, so I does not perform any update.

i also had to wait for few days...

**Comment by fvasco** [comment]
I fixed the issue.

1. I uninstalled Gadgetbridge
2. I performed a watch factory reset
3. I removed any Bluetooth association (I found it twice)

Now works as expected.

Thanks for support.

**Comment by vanous** [comment]
Great. Btw, the 1.1.5.56 firmware on watchfaces... seems available now again.
