### ISSUE TITLE
Nexus 6, Marshmallow, doesn't connect to mi band (firmware 1.0.11.6)

### ISSUE THREAD

**Issue by Helius** [Freeyourgadget/Gadgetbridge#163]
App was built from git (753286a)
I setted up mac address (got from MeFit) and mi band icon appeared in main screen with status "not connected". I pressed on icon and saw: "connecting" -> "connected" -> "initializing" -> "not connected"

If I can help, feel free to comunicate me!
Thank You.

Logcat after I press on icon:

11-08 19:18:11.299 12363-12363/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
11-08 19:18:11.299 12363-3750/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Thread interrupted
11-08 19:18:11.299 12363-3750/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Queue Dispatch Thread terminated.
11-08 19:18:11.306 12363-12363/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Attempting to connect to MI
11-08 19:18:11.307 12363-4827/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Queue Dispatch Thread started.
11-08 19:18:11.309 12363-12363/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: connect() - device: 88:0F:10:7E:B2:92, auto: false
11-08 19:18:11.310 12363-12363/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: registerApp()
11-08 19:18:11.310 12363-12363/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: registerApp() - UUID=75b54dae-5607-4eae-8079-6a14cb9ce9fe
11-08 19:18:11.311 12363-15944/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: onClientRegistered() - status=0 clientIf=5
11-08 19:18:11.315 12363-12363/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
11-08 19:18:16.376 12363-12379/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=5 device=88:0F:10:7E:B2:92
11-08 19:18:16.376 12363-12379/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state change, newState: 2 (success)
11-08 19:18:16.376 12363-12379/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Connected to GATT server.
11-08 19:18:16.376 12363-12379/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: discoverServices() - device: 88:0F:10:7E:B2:92
11-08 19:18:16.376 12363-12363/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
11-08 19:18:16.377 12363-12379/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Attempting to start service discovery:true
11-08 19:18:17.405 12363-12379/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: onSearchComplete() = Device=88:0F:10:7E:B2:92 Status=0
11-08 19:18:17.405 12363-12379/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to pair MI device...
11-08 19:18:17.405 12363-12379/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Requesting Device Info!
11-08 19:18:17.405 12363-12379/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Writing User Info!
11-08 19:18:17.405 12363-12379/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to set wear location...
11-08 19:18:17.405 12363-12379/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to set Fitness Goal...
11-08 19:18:17.406 12363-12379/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Sending current time to Mi Band: November 8 (8 Nov 2015 13:18:17 GMT)
11-08 19:18:17.406 12363-12379/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Requesting Battery Info!
11-08 19:18:17.406 12363-12379/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: about to add: 19:18:17: Transaction task: Initializing device with 15 actions
11-08 19:18:17.406 12363-4827/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: November 8, 19:18: SetDeviceStateAction on characteristic: (null)
11-08 19:18:17.407 12363-4827/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: November 8, 19:18: WriteAction on characteristic: 0000ff0f-0000-1000-8000-00805f9b34fb
11-08 19:18:17.407 12363-12363/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
11-08 19:18:20.649 12363-12379/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: onClientConnectionState() - status=22 clientIf=5 device=88:0F:10:7E:B2:92
11-08 19:18:20.649 12363-12379/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state change, newState: 0 (failed: 22)
11-08 19:18:20.649 12363-12379/nodomain.freeyourgadget.gadgetbridge W/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state event with error status 22
11-08 19:18:20.649 12363-12379/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Disconnected from GATT server.
11-08 19:18:20.649 12363-12379/nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: internal gatt callback set to null
11-08 19:18:20.649 12363-12379/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Disconnecting BtLEQueue from GATT device
11-08 19:18:20.649 12363-12379/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: cancelOpen() - device: 88:0F:10:7E:B2:92
11-08 19:18:20.649 12363-12363/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
11-08 19:18:20.658 12363-12379/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: close()
11-08 19:18:20.658 12363-12379/nodomain.freeyourgadget.gadgetbridge D/BluetoothGatt: unregisterApp() - mClientIf=5
11-08 19:18:20.713 12363-12363/nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true

**Comment by cpfeiffer** [comment]
Interesting, especially since the report in #159.

Did you properly configure some user info in the preferences (nick name, age, weight, etc.)? Otherwise the Mi Band won't allow us to talk to it.

Or, can you try to pair/unpair the device in Android's BT settings and try the procedure again?

**Comment by Helius** [comment]
Hi,
Thank You for note, I tried to set up nick, age, weight, etc, and now when I tap icon i see:
"not connected"->"initializing" and nothing happened else.
"Activiry", "Sleep" and "Steps" screens are empty ("No data. Synchronize device?")
When I check "Synchronize" i saw toast "Not Connected".
BTW I don't see mi band in bluetooth settings, but MiFit works properly except "SmartLock" feature. SmartLock doesn't work on android 6, it's knowing bug ((.

Logcat after i pressed on icon:
11-09 10:02:04.650  6970  6970 D nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
11-09 10:02:04.666  6970  6970 I nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Attempting to connect to MI
11-09 10:02:04.666  6970  7021 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Queue Dispatch Thread started.
11-09 10:02:04.669  6970  6970 D BluetoothGatt: connect() - device: 88:0F:10:7E:B2:92, auto: false
11-09 10:02:04.669  6970  6970 D BluetoothGatt: registerApp()
11-09 10:02:04.670  6970  6970 D BluetoothGatt: registerApp() - UUID=f9c3e0a3-3f67-4c51-aea0-a7b829ada132
11-09 10:02:04.672  6970  6992 D BluetoothGatt: onClientRegistered() - status=0 clientIf=6
11-09 10:02:04.673  6970  6983 D BluetoothGatt: onClientConnectionState() - status=0 clientIf=6 device=88:0F:10:7E:B2:92
11-09 10:02:04.673  6970  6983 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state change, newState: 2 (success)
11-09 10:02:04.673  6970  6983 I nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Connected to GATT server.
11-09 10:02:04.674  6970  6983 D BluetoothGatt: discoverServices() - device: 88:0F:10:7E:B2:92
11-09 10:02:04.675  6970  6983 I nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Attempting to start service discovery:true
11-09 10:02:04.683  6970  6982 D BluetoothGatt: onSearchComplete() = Device=88:0F:10:7E:B2:92 Status=0
11-09 10:02:04.684  6970  6982 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to pair MI device...
11-09 10:02:04.684  6970  6982 D nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Requesting Device Info!
11-09 10:02:04.690  6970  6970 I nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
11-09 10:02:04.699  6970  6982 D nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Writing User Info!
11-09 10:02:04.700  6970  6982 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to set wear location...
11-09 10:02:04.700  6970  6982 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Attempting to set Fitness Goal...
11-09 10:02:04.709  6970  6970 I nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
11-09 10:02:04.752  6970  6982 I nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Sending current time to Mi Band: November 9 (9 Nov 2015 04:02:04 GMT)
11-09 10:02:04.752  6970  6982 D nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport: Requesting Battery Info!
11-09 10:02:04.753  6970  6982 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: about to add: 10:02:04: Transaction task: Initializing device with 15 actions
11-09 10:02:04.755  6970  7021 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: November 9, 10:02: SetDeviceStateAction on characteristic: (null)
11-09 10:02:04.755  6970  7021 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: November 9, 10:02: WriteAction on characteristic: 0000ff0f-0000-1000-8000-00805f9b34fb
11-09 10:02:04.759  6970  6970 I nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true

**Comment by cpfeiffer** [comment]
I sometimes have the same issue with current master, it keeps in initializing state. If you long press, choose Disconnect and connect again, it should work. It seems to be really picky about how to connect.

**Comment by Helius** [comment]
@cpfeiffer Thanks, but doesn't work for me. Just stuck on "initializing" or return to "not connected"

**Comment by cpfeiffer** [comment]
Too bad. Since you built it yourself, could you do some experiments? In file BtLEQueue.java, from line 159, there is the following code:
```
        boolean result;
        synchronized (mGattMonitor) {
            mBluetoothGatt = remoteDevice.connectGatt(mContext, false, internalGattCallback);
            result = mBluetoothGatt.connect();
        }
```
You could try to change it like this:
1)
```
        boolean result;
        synchronized (mGattMonitor) {
            mBluetoothGatt = remoteDevice.connectGatt(mContext, false, internalGattCallback);
            result = true;
        }
```

or 2)
```
        boolean result;
        synchronized (mGattMonitor) {
            mBluetoothGatt = remoteDevice.connectGatt(mContext, true, internalGattCallback);
            result = true;
        }
```

or 3)
```
        boolean result;
        synchronized (mGattMonitor) {
            mBluetoothGatt = remoteDevice.connectGatt(mContext, true, internalGattCallback);
            result = mBluetoothGatt.connect();
        }
```

and see if you get it to work with any of these variants.

**Comment by Helius** [comment]
I tried all of cases but it doesn't connect. In 1 case there was "Connected", but when I pressed "synchronize", i see toast "Not connected".
I will try to understand what's wrong with my BLE later.
Thank you.
