### ISSUE TITLE
mi band 4 reconnect issue

### ISSUE THREAD

**Issue by FransM** [Freeyourgadget/Gadgetbridge#1632]
Your wearable device is:

Mi Band 4 FW 1.0.5.66
Your android version is:

7.1.1
Your Gadgetbridge version is:

0.36

Description:
At night I leave my phone downstairs, but I still wear the band.
In the morning when I want to check my status the phone says "connecting" but it always fails to connect. If I turn off bluetooth and after a bit of time re-enable it, the phone can connect.
I am not running mi-fit or another mi app.

Attached is a slightly censored log. I replaced some data with the text <removed>
If any of it is useful for the analysis let me know.
Log starts when the phone is trying to connect. THen I disabled BT and re-enabled it.
I truncated the log at a point where the connection was up and running but I have some more logging if needed (and I can reproduce)
[connectlog.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/3592671/connectlog.txt)

**Comment by IzzySoft** [comment]
Probably related: #1452 – can you please check? As Band 2 & 3 are mentioned there, maybe that's a general Mi Band issue.

**Comment by FransM** [comment]
This might be related to #1452. It is definitely different from #1545 
I'm not sure if the above could be merged into 1452, but this one has a log, so it might give info on what is different when reconnecting when BT is already on and reconnecting after BT becomes up.
(first one does not work, second one does)

**Comment by frankpau** [comment]
what exactly did you do to get the band paired to your phone ?
which method of obtaining the auth code did you use ?
is your phone rooted ?
are you using the original phone firmware or are you using lineage os ?

**Comment by FransM** [comment]
I paired the band by using the + button (add new device).
The auth code was retrieved with the apk from www.freemyband.com
(then again authorisation itself is probably not the issue as the initial connection works.
My phone (moto 4g play) is not rooted. It runs official moto software (the latest OTA upgrade) that they distributed.

I compared logs. Below is the section from the log where things start to differ in the faulty and good case. The section below is from the tailure. For more details see log that I uploaded earlier.

08:53:35.897 [Binder:3822_3] DEBUG n.f.g.s.b.BtLEQueue - about to add: 8:53:35 a.m.: Transaction task: Initializing device with 3 actions
08:54:16.566 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
08:54:16.567 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
08:54:16.660 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:54:16.707 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
08:54:34.462 [Binder:3822_3] DEBUG n.f.g.s.b.BtLEQueue - connection state change, newState: 0 (failed: 19)
08:54:34.463 [Binder:3822_3] WARN  n.f.g.s.b.BtLEQueue - connection state event with error status 19
08:54:34.463 [Binder:3822_3] INFO  n.f.g.s.b.BtLEQueue - Disconnected from GATT server.
08:54:34.476 [Binder:3822_3] DEBUG n.f.g.s.b.BtLEQueue - handleDisconnected: 19
08:54:34.477 [Binder:3822_3] DEBUG n.f.g.s.b.BtLEQueue - internal gatt callback set to null
08:54:34.477 [Binder:3822_3] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
08:54:34.478 [Binder:3822_3] DEBUG n.f.g.s.b.BtLEQueue - disconnect()
08:54:34.478 [Binder:3822_3] INFO  n.f.g.s.b.BtLEQueue - Disconnecting BtLEQueue from GATT device
08:54:34.484 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:54:34.483 [Binder:3822_3] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
08:54:34.496 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:54:34.503 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
08:54:34.509 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
08:54:44.185 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.fetch_activity_data
08:54:44.224 [main] INFO  n.f.g.i.GBDevice - Mark device as busy: Operation starting...

**Comment by FransM** [comment]
I did a bit of digging in the source code but I am not really familiar with BtLE or the code, so I could not really find where the error comes from. 
Since the band automatically reconnects if I turn BT off, wait a bit, then turn BT on, it suggests that there is some resetting needed before reconnecting. This reset is done when BT disconnects. (of course this could also be at the BT service side)

**Comment by FransM** [comment]
Question: are there people with a mi band for which this works ok? 
If so please add a note here as it would be an indication that it is related to a specific android version

**Comment by sunsero** [comment]
Mi Band 4 is here also not automatically reconnected after being too far away temporarily. Bluetooth off/on initiates successful reconnection, tapping in Gadgetbridge or the expanded notification from it reconnects it as well. Galaxy S7 with stock Android 8.

**Comment by FransM** [comment]
@sunsero nice addition; I noticed that if I open GB and it says connection I can disconnect by pressing on the connecting message for a bit of time and it will go to disconnected. If I then press againt it goes to connecting and eventually connects.
Seems there is something odd in the initial connect that is cured by this toggling.

**Comment by sunsero** [comment]
Can't wait for this to be available on F-Droid. Thank you very much!
