### ISSUE TITLE
push data to band

### ISSUE THREAD

**Issue by FransM** [Freeyourgadget/Gadgetbridge#1634]
I noticed that the notify & fitness app allows to write a screenshot to the mi band 4.
(I suspect they just send it as a watch face).
What I would want is an easy way to write custom images.
E.g. when navigating to a certain waypoint the phone could write a directional arrow every minute (or when requested with a button press).
Note that this request is for a mechanism (preferably with a plugin) so users can create their own interaction. (e.g. create n images, button press means next, double press or long press means previous)

**Comment by vanous** [comment]
You can upload custom firmware with GB already, so the underlying structure exists. Watchface file creation and pushing it to GB can be a nice project, would you like to contribute?

**Comment by FransM** [comment]
It indeed seems a nice project to me. Then again I am not extremely well versed in Java and Android app development (but of course this is a good opportunity to pick it up), and the next month or so I am a bit low on time.
(side note: is there a GB mailing list? I feel github issues are not really the right place to ask questions, and I am not too sure how active the freenode group is)

**Comment by IzzySoft** [comment]
The freenode channel is rather calm. There's also a Matrix room I've been told (I'm not a Matrix user, so I didn't check that). There's no mailing list I'm aware of.

**Comment by petrvanekrobe** [comment]
I have thought about this quite a bit. We could connect the matrix room with a gateway to IRC but this actually would probably be against current state of mind of the project - the Matrix room is set as End to end encrypted, and this would be a hole into that. But, perhaps if we make the matrix link more visible, we could eliminate some of the "question only" issues. The matrix room does not have any high volume of conversations, there is some occasional chatter. But the decision about putting the link into readme and perhaps wiki first page would be to @ashimokawa

**Comment by vanous** [comment]
tired...
I have thought about this quite a bit. We could connect the matrix room with a gateway to IRC but this actually would probably be against current state of mind of the project - the Matrix room is set as End to end encrypted, and this would be a hole into that. But, perhaps if we make the matrix link more visible, we could eliminate some of the "question only" issues. The matrix room does not have any high volume of conversations, there is some occasional chatter. But the decision about putting the link into readme and perhaps wiki first page would be to @ashimokawa

**Comment by FransM** [comment]
I've been looking into the original suggestion I made. 
I feel that suggestion is not feasible. Using this for semi-interactive purposes (e.g. directions or an arrow to a waypoint) would require updating the firmware often. This takes a lot of time and probably will also cause quite some wear on the flash.

I can still imagine a solution where you have e.g. a dedicated watchface e.g. with icons being arrows. An alternative could be if an analog watchface is possible to use the watch hands to show the direction, but this would require e.g. forcing a fake time onto the band. Not sure if that is feasible.

I'm inclined to close this ticket. Please advise.
