### ISSUE TITLE
gadgetbridge crashes when attempting to open amazfit bip activities 

### ISSUE THREAD

**Issue by camelCaseNick** [Freeyourgadget/Gadgetbridge#1636]
### I got Gadgetbridge from:
* [x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

#### Your issue is:
When trying to open an activity from the activities list for gadgetbridge crashes.

See: https://imgur.com/a/KSB90TI

#### Your wearable device is:
amazfit bip v1.1.5.56

#### Your android version is:
Android 9

#### Your Gadgetbridge version is:
0.36.0

**Comment by petrvanekrobe** [comment]
Most probably I cannot help you very much with this, but perhaps try to provide some evidence/log files, please make sure to read this first: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files

**Comment by vanous** [comment]
Most probably I cannot help you very much with this, but perhaps try to provide some evidence/log files, please make sure to read this first: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files

**Comment by camelCaseNick** [comment]
@vanous , sorry, I did not allow OsmAnd to be opend from a different app (only main intent from home screen). Sorry, for wasting your time with my configuration problems.
