### ISSUE TITLE
Set notification display timeout

### ISSUE THREAD

**Issue by vtolstov** [Freeyourgadget/Gadgetbridge#1642]
Device mi band 2
Android 9

I have read the wiki, and I didn't find a solution to my problem / an answer to my question.
I have searched the issues, and I didn't find a solution to my problem / an answer to my question.

I got Gadgetbridge from:
F-droid

I'm enable notifications for sms messages, bit firstly i have sms notify without any name and number. After that it displays another sms notify with smaller icon size and with name and phone, sometimes it includes message contents. But i notification display timeout is too small, and i dont able to read incoming sms phone number or contact name.

**Comment by IzzySoft** [comment]
Please do not remove the template but rather fill it. There's a reason why it is there – especially these parts:

#### Before reporting a bug, please confirm the following:
- [ ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

### I got Gadgetbridge from:
* [ ] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

#### Your Gadgetbridge version is:

So please fill those gaps so we can help you.

**Comment by vtolstov** [comment]
Sorry, i'm update issue.

**Comment by IzzySoft** [comment]
Thanks! Now someone familiar with the Band can take a look (not me, I have no Band).

**Comment by vanous** [comment]
The delay is about 6 seconds on the MB3 and about the same on the Bip. I don't recall seeing such settings in the official app, so i would think settings is not possible...

**Comment by vanous** [comment]
As this project is about the companion app and not about band firmware, can we now close this ticket?

**Comment by ashimokawa** [comment]
Yes. Please reopen if proof for the feature in the official app.
