### ISSUE TITLE
Device Request: Zeblaze Crystal

### ISSUE THREAD

**Issue by hataiit9x** [Freeyourgadget/Gadgetbridge#1644]
Your issue is:
Cannot connect Zeblaze NEO

Your wearable device is:
Zeblaze NEO. Firmware; 82.02

Your android version is: 9.0
Thanks !

**Comment by IzzySoft** [comment]
This seems to be a duplicate to #1645 with just the title changed. I assume the latter was intended as update. If I was wrong, please say so (and edit accordingly).
