### ISSUE TITLE
Device Request: Amazfit Bip Lite, Model A1915

### ISSUE THREAD

**Issue by slu74** [Freeyourgadget/Gadgetbridge#1648]
#### Before requesting a new feature, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I tried to pair my “Amazfit Bip Lite” model A1915 with my phone. 
I read that Amazfit Bip Lite consisit of different hardware (e.g. removed GPS sensor) and firmware and uses an internal authkey to pair with mifit.
So I used freemyband to obtain the key with the intention to pair my Bip like a MiBand4, which uses also an authkey.
I made my Bip visible, killed mifit and made a bluetooth cache reset. Because Bip doesn’t appear in GB search, I entered the MAC address manually in options menu.
Similar to the pairing procedure of MiBand4 I tried pressing long on “Amazfit Bip Lite” in intention to enter the authkey, but no menu opens.
May I assume, that model A1915 is not supported yet?
Thanks for answers!

*If applicable, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)*

#### Your wearable device is:
- Amazfit Bip Lite
- model A1915
- FW 1.1.6.02

#### Your android version is:
- Android 9

#### Your Gadgetbridge version is:
GB version 0.36.0

*New requests about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by IzzySoft** [comment]
Looks like not yet supported, seeing [here](https://github.com/Freeyourgadget/Gadgetbridge/issues/1554#issuecomment-523698818) – but then it seems it is, see #1479 (though that's an A1608). According to the latter, rather follow the process of the Mi Band 3 (instead of the 4).

Confusion is, as far as I remember, that there are two devices sold by the name "Amazfit BIP Lite": one of them is the real "Lite", the other one is in fact an "Amazfit BIP" (without "Lite", see #920). My guss is the A1608 is the latter, and the A1915 is the former. Note that the first mentioned issue again is about the A1915, and the only other occurrence of that name in our issue tracker here.

Note that our wiki seems to confirm this, explicitly stating support for A1608 only e.g. in [Firmware update](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Amazfit-Bip-Firmware-Update).

**Comment by ashimokawa** [comment]
@slu74 
I will try to blindly support the Bip Lite, thanks for the information.
Are you able to build Gadgetbridge from master?

**Comment by ashimokawa** [comment]
@slu74 
Are you absolutely sure that all, even the initial firmware for bip light require the pairing key to be obtained by xiaomi servers, or is there also a 1.1.5.xx firmware?
Somehow I tend to think that firmware is the same.... At least there are "Bip Lite" specific images in the res for the normal bip

**Comment by ashimokawa** [comment]
@slu74 
Can you build master and try to pair the watch normally? Without using the obtained key...

**Comment by slu74** [comment]
@ashimokawa
What does it mean to built Gadgetbridge from master?
I'm sorry but I'm not a programmer and additionally my english ist a little bit "rusty".
The FW version of my "Bip Lite" is 1.1.6.02.
Before testing GB I tried Notify&Fitness. I was not able to pair the watch without key.

**Comment by ashimokawa** [comment]
@slu74 
Never mind, if you say you could pair without key, then the fix I just did is probably enough.
You can try as soon as Gadgetbridge 0.36.2 is out. Current version is 0.36.1 (appeared yesterday on F-Droid)

**Comment by slu74** [comment]
As I described in the first thread, I tried to pair the watch "normally", but it does'n appear in GB search.
So I entered the Bluetooth address manually in the options menu.
When I tapped short on "Amazfit Bip Lite", GB tried to pair but I got no connection.

**Comment by slu74** [comment]
I will try 0.36.2 and report. Thanks!

**Comment by vanous** [comment]
@slu74 if the building doesn't work for you and you need help building the apk,  ping me, I can make a debug build for you. Of course, much better is if you do it.

**Comment by slu74** [comment]
@vanous 
I see the version 0.36.2 is online but I need your help in building the apk because I have no experience in programming and the necessary tools...

**Comment by IzzySoft** [comment]
@slu74 0.36.2 was just tagged a few hours ago. It will take a few days until it reaches the F-Droid index, then you can update directly. Of course it doesn't hurt learning how to build it from source – but nobody will promise you that's an easy task for beginners (though I'd be glad to learn otherwise: I'm not an Android dev either).

**Comment by qysp** [comment]
Compiled it and even completely removed the name check, no luck so far. Might only be on my end but according to the logs the app could not find any devices whatsoever.

**Comment by ashimokawa** [comment]
@qysp

Did you try to remove the pairing from Android Bluetooth settings?

**Comment by qysp** [comment]
@ashimokawa Oh, I totally forgot to do that. I am now able to find my Amazfit Bip Lite and also bond with it. However, while in my bluetooth settings it says that it is now indeed paired, GB is still stuck at "Pairing with Amazfit Bip Lite: <MAC ADDRESS> (AMAZFITBIP)...".

**Comment by ashimokawa** [comment]
@qysp 
I have no idea since I never used mi fit. Yes, it could be possible.

**Comment by qysp** [comment]
@ashimokawa Does not seem to be the reason. Uninstalled the Mi Fit app completely, did a factory reset on the watch as well as a Bluetooth reset on the phone. Still stuck in "pairing loop" you could say.

**Comment by ashimokawa** [comment]
@qysp 
Since I do not have a Bip Lite: Can you provide logs? Please check for sensitive data or send me directly.

**Comment by qysp** [comment]
@ashimokawa Sure thing! Here is the [gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/3665360/gadgetbridge.log).

**Comment by ashimokawa** [comment]
@gysp
Log stops before it gets interesting...

**Comment by qysp** [comment]
@ashimokawa well, that's the entire log. After having the app try to pair with the watch for quite a while I stopped it.

**Comment by slu74** [comment]
I also made a attempt with 0.36.2 and it behave similar to what @qysp says.
GB finds the Bip Lite but is not able to couple.
Here is my log and I hope you find useful information.
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/3667424/gadgetbridge.log)
BTW: today a new update came for the watch: V1.1.6.30

**Comment by ashimokawa** [comment]
@slu74 
At least you log contained something.
My problem is that I do not have the Bip Lite. I assumed to would be locked down just like the Mi Band 4 (requires to use Mi Fit and dump keys), but then you said you did not need to enter a key in another 3rd party app. Really confusing. I guess I need a Bip Lite to fix it.

**Comment by slu74** [comment]
@ashimokawa 
I think there is a missunderstanding: I have not said, I did not need to enter a key in another 3rd party app. I read that Amazfit Bip Lite uses an internal authkey to pair with mifit.
So I used freemyband to extract the key in view of the fact that the coupling procedure for Bip Lite could be similar to MiBand4, which uses also an authkey.
In recent days I tried "notify & fitness for amazfit" as a test. It takes the key out of the directory which is generated by freemyband - with successfully coupling. So I think the key is essential.
But I don't want to use notify & fitness and hope you can expand GB for Bip Lite.

**Comment by ashimokawa** [comment]
@slu74 
I see, sorry, I  misread it. Will see, maybe @qysp can build after I commit something blindly

**Comment by vanous** [comment]
Wow, so confirmed. Server key paring for the future... sad.

**Comment by ashimokawa** [comment]
can you try to build and the bip-lite-tet (sic!) branch and then input your auth key like on mi band 4?

I think I will make "Bip Lite" an extra device internally. They might not share firmware. But if they do we are screwed. There IS a 1.1.6 firmware for the original bip and it might implement the server pairing also...

**Comment by qysp** [comment]
I compiled and tried it. Nothing changed as far as I can tell though. Here is the [gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/3668048/gadgetbridge.log).

Btw, a friend of mine has the _normal_ version of the Amazfit Bip and already updated to the newest firmware (v1.1.16). He does not have any problems so far.

**Comment by ashimokawa** [comment]
@qysp 
It does look better but still fails, did you enter the auth key you optained from mi fit?
Remember after factory reset this changes, and you have to pair with mi fit again to get a new auth key.

**Comment by qysp** [comment]
I did not enter an auth key. Though when I held down on the discovered device, I could check out the auth key which was filled in. Is this the wrong auth key?

**Comment by ashimokawa** [comment]
@qysp
Yes you need the one obtained from mi fit please read the wiki about it , it seems to be the same like with mi band 4

**Comment by qysp** [comment]
@ashimokawa My bad. I installed the freemyband app and entered the auth key, nothing seems to have changed, waited for like 5 minutes too before stopping the app. Here is the [gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/3671959/gadgetbridge.log).

**Comment by ashimokawa** [comment]
@qysp
The log is cut off and incomplete again.
Did you enter the key with 0x prefixed.and without enter at the end?

**Comment by vanous** [comment]
@qysp please try to follow step by steps this [pairing manual](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Huami-Server-Pairing). make sure to read carefully and proceed as indicated (unpair BT, long press etc...). Thank you

**Comment by qysp** [comment]
@ashimokawa @vanous Reset bluetooth, reinstalled MiFit app and followed the exact steps. Logs are a bit long since I tried it multiple times but I don't wanna delete anything out of it: [gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/3672368/gadgetbridge.log).

**Comment by ashimokawa** [comment]
@qysp 
Assuming you built and tested with the bip-lite-tet branch,
I think now only a bluetooth log helps when pairing with mi fit.

Or someone here can provide us with a Bip for a few hours :)

**Comment by qysp** [comment]
@ashimokawa Yes, I checked out that specific branch. If there is some "easy" way to log the Bluetooth pairing I could try it at least :)

**Comment by slu74** [comment]
@qysp Did you built an APK? Is it possible to send it to me so I can give it a try additionally?

**Comment by ashimokawa** [comment]
@slu74
Can you contact me via mail?

**Comment by slu74** [comment]
@ashimokawa Shure I would like to contact you, but how do I find your email adress?

**Comment by slu74** [comment]
@ashimokawa 
Shure I would like to contact you, but how do I find your email adress?

**Comment by heller390** [comment]
@ashimokawa Tried pairing with 0.36.2 apk . It gets stuck on authenticating forever. I could see the connected though through bt icon. I got 2 keys from extracting the db . Here are the logs though . I could forward more logs if needed.
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/3703493/gadgetbridge.log)

**Comment by ashimokawa** [comment]
@heller390
0.36.2 is not ready for the "already paired usw my mifit keys" method. Also test builds did not work, contact me via mail if you want to have one and see for yourselft. I guess I need the watch and see for myself. Or send me a Bluetooth hci dump when pairing with mi fit via email.

**Comment by heller390** [comment]
@ashimokawa  Do I need to unpair the watch from mifit and collect logs while pairing it again?

**Comment by ashimokawa** [comment]
@heller390
Exactly.

**Comment by heller390** [comment]
> 
> 
> @heller390
> Exactly.


> 
> 
> @heller390
> 0.36.2 is not ready for the "already paired usw my mifit keys" method. Also test builds did not work, contact me via mail if you want to have one and see for yourselft. I guess I need the watch and see for myself. Or send me a Bluetooth hci dump when pairing with mi fit via email.
Ur mail address is not available on github public profile? How should i send the logs to mail then?

**Comment by ashimokawa** [comment]
@heller390

Check out the repo and type git log ;)

**Comment by heller390** [comment]
> @heller390
> Check out the repo and type git log ;)

My bad . Sent the mail with logs attached . Do ping if something more is needed.

**Comment by ashimokawa** [comment]
There is a new branch called bip-lite-test, it might work.

@qysp
Can you build and try?

**Comment by qysp** [comment]
@ashimokawa I'm sorry, had to send the watch back :(

**Comment by vanous** [comment]
Actually,  perhaps walking into a store and trying to pair would be possible... I will try to look around and keep the test branch apk ready...

**Comment by ashimokawa** [comment]
The new pairing scheme is 100% confirmed by now. Mi Fit and registration is necessary as with mi band 4

**Comment by vanous** [comment]
Uh, OK, this is sadly good to know. Any news if same applies to latest Bip update?

**Comment by ashimokawa** [comment]
Reports suggest that it still works after update by no one confirmed that it is still the case after factory reset

**Comment by heller390** [comment]
> Actually, perhaps walking into a store and trying to pair would be possible... I will try to look around and keep the test branch apk ready...

No need of all that hassle. Test build by @ashimokawa pairs and is working .

**Comment by ashimokawa** [comment]
I deleted the test branch, master now works with bip lite thanks @heller390 for testing!

**Comment by MyTimeKill** [comment]
@ashimokawa This is not true. I tested 2 programs, Amazfit Masters and Notify & Fitnes, and they work without keys

**Comment by vanous** [comment]
@MyTimeKill the Bip Lite server based pairing has been verified as per comments above, please read it. It is now supported in Gadgetbridge master (as you said, the one you compiled). I would suggest to perform the pairing procedure as advised if you want Gadgetbridge to be paired with your watch.

**Comment by ashimokawa** [comment]
@MyTimeKill
Then please apply the patch manually that posted in the other issue and retry.

I do not have the watch and need to rely on external information that is contradicting and full of rumors

**Comment by MyTimeKill** [comment]
@ashimokawa Yes, I already built apk with these changes, I will test it soon

**Comment by ashimokawa** [comment]
@MyTimeKill
Keeping my code clean and my phone from propitiatory software I never look at these other tools. If you say they work completely without ever having paired with a modified mi fit, have no root access and do not ask you for mi fit login credentials, then I have no idea yet what they do differently, and without a bip lite in my hands I cannot even experiment with it.

**Comment by vanous** [comment]
Feedback would be nice to have, i have modified the wiki today, to mention that Bip Lite does require the secret key...

**Comment by MyTimeKill** [comment]
Sorry for delay.
I have already said that the watch does not belong to me, so I could not test it myself. I gave this build to a friend and he says that the clock will not be detected by the program. He tried on different phones.

**Comment by slu74** [comment]
Hello,
I can confirm that coupling of Gadgetbridge 0.37.0 works in combination with authkey!
The Amazfit Bip Lite has the latest firmware 1.1.6.32

**Comment by heller390** [comment]
@ashimokawa Whenever i try to record activity with bip connected to gadgetbridge , it stuck in getting gps. Tried with gmaps , osmand , here maps etc but all in vain. Fyi bip lite doesnt have inbuilt gps.

![IMG_20191017_190134](https://user-images.githubusercontent.com/15274500/67013917-87682c00-f111-11e9-9646-41f930d19193.jpg)

**Comment by ashimokawa** [comment]
@heller390 
Yep, we do not support that yet.
The Bip has integrated GPS, the Bip lite which we never had in our hands not.
We could use the Mi Band 4 which has a similar feature to implement it. But we do not have any ETA

**Comment by ashimokawa** [comment]
0.37.1 is out on fdroid. Flash your watchfaces

**Comment by heller390** [comment]
> @heller390
> Yep, we do not support that yet.
> The Bip has integrated GPS, the Bip lite which we never had in our hands not.
> We could use the Mi Band 4 which has a similar feature to implement it. But we do not have any ETA

Don't hesitate to ask for logs if needed!

**Comment by slu74** [comment]
Now that GB is able to pair with Amazfit Bip Lite in combination with the authkey, I think, the issue could be closed. Many thanks to all!
