### ISSUE TITLE
Notification on incoming calls not working

### ISSUE THREAD

**Issue by f4stb00t** [Freeyourgadget/Gadgetbridge#1649]
#### Before reporting a bug, please confirm the following:
- [YES ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question. 
- [YES ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [SURE ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

### I got Gadgetbridge from:
* [X ] F-Droid

#### Your issue is:
Hi,
since I migrated from MIUI to LOS the function to get an alert on the MiBand3 never worked. WIth StockROM it worked without any issue. Everything else like vibration on SMS or Message from other Messenger works as well. 
Can anyone confirm the issue on LOS?
Any Idea how to fix? I tried like everything with the configuration, without any luck.

#### Your wearable device is:

Xiaomi Mi Band 3

**Comment by ashimokawa** [comment]
I have the same problem on Lineage 16, but strangely enough not on all Lineage 16 phones.
This is a permission problem when trying to access the phone state directly, which cannot be fixed since Android 9 is much stricter then previous versions.

I have a workaround locally which uses the android notifications instead of the call state, but that has other problems.

I might commit this as an experimental option, better than nothing.

**Comment by f4stb00t** [comment]
Hello ashimokawa,

this would be really nice if you have a workaround for this. Please commit this. I would test it and send you a feedback here. 

regards

fastboot

**Comment by ashimokawa** [comment]
@f4stb00t 
The next release with ask for the permission on startup on lineage, but you can fix your problem without rebuilding or waiting.

Go to settings, security, trust, privacy, press the three dots menu, select extended, tap on gadgetbridge, allow "read call log".

**Comment by f4stb00t** [comment]
@ashimokawa 

This permission is already granted to gadgetbridge. In other words it does not fix the situation.

**Comment by ashimokawa** [comment]
@f4stb00t 
Did you *really* go all the way though what I wrote or did you just go to permissions and checked for call log permission?

This is something completely different on lineage and very confusing.
