### ISSUE TITLE
Missing specific settings for MiBand 3 in V0.36.0

### ISSUE THREAD

**Issue by SilKaw** [Freeyourgadget/Gadgetbridge#1650]
Hello,
in an earlier version i remember that in Gadgetbridge the list of devices for device specific settings was much longer, there i could setup some features only for the miband 3. In the current version i can't find this menu point. I wanted to set that by turning the wrist the display gets on, set the displayed items,  set the automatic activity recognition, but non of this functions I am able to find now. What is happend? Where are these functions?

**Comment by ashimokawa** [comment]
click the setting icon in the device card in the main activity.
Those settings are now per-device and not per device type.

**Comment by SilKaw** [comment]
Ok, I got it, thanks.
