### ISSUE TITLE
Layout in Database Management screen is broken with German language

### ISSUE THREAD

**Issue by Low012** [Freeyourgadget/Gadgetbridge#1652]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

### I got Gadgetbridge from:
* [x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

#### Your issue is:
The layout of the Database Management screen is broken if the language of the app is set to German. The text is cut off and the "import database" button is not visible. (Phone: Fairphone 2)

Broken layout with German language
![Screenshot_20190924-202638_Gadgetbridge](https://user-images.githubusercontent.com/11596220/65545119-06a08080-df15-11e9-81d9-6631d8a93672.png)

OK layout with English language
![Screenshot_20190924-214146_Gadgetbridge](https://user-images.githubusercontent.com/11596220/65545120-06a08080-df15-11e9-8194-2ace78b65816.png)

#### Your wearable device is:
Amazfit Bip, firmware version V1.1.5.02

#### Your android version is:
LineageOS 16.0 (Android 9)

#### Your Gadgetbridge version is:
0.36.1

**Comment by ashimokawa** [comment]
Android layout is a major PITA, help welcome but enough is enough
Basically I was not able to place two buttons side by side and have them NOT excess screen size if one of them takes more than 50% of the screen.
