### ISSUE TITLE
Mi Band 4 not pairing

### ISSUE THREAD

**Issue by frankpau** [Freeyourgadget/Gadgetbridge#1653]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

### I got Gadgetbridge from:
* [x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

If you got it from Google Play, please note [that version](https://github.com/TaaviE/Gadgetbridge) is unofficial and not supported here; it's also often quite outdated. Please switch to one of the above versions if you can.

#### Your issue is:
i have tried pairing a mi band 4 with now 4 Android devices , all with different Android Versions.
On all devices i have the same behaviour. These are the steps i have taken on all devices:
- Install Mi Fit from freemyband.com
- successfully paired the band and get the key as described from the text file in /sdcard/freemyband
- the key consists of 2 parts: the mac adress of the band and the key.
- unpair the band, uninstall Mi Fit, reboot the android device
- install F-Droid and gadgetbridge from f-droid
- start Gadetbridge and let it search for the band. After finding the band i entered the key i got from freemyband, by selecting the into "Auth Key", in the following ways:
0x<key>
0x<key>@<mac>
<key>
- each time after entering the key i chose the the and the paring starts, but never ends.
- it asks for a lot of access to different services on the android device, which i all allowed.
- i also tried with deactivated bluetooth pairing , to be found in the miband settings in gadetbridge

Could someone , who successfully paired a mi band 4 wit hgadgetbridge the steps i have written down ?
What could be the problem, that the pairing never stops and is not successful ?

#### Your wearable device is:

Mi Band 4 updated to firmware 1.06.<something>

#### Your android version is:
7.1.1
8
9
#### Your Gadgetbridge version is:
0.36 and 0.36.1
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/3657542/gadgetbridge.log)

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by frankpau** [comment]
regardings entering the i tried the follwoing key's:
0xabcderft
0xabcderft@00:00:00:00:00:00(mac adress)
abcderft

**Comment by IzzySoft** [comment]
This is a problem different from #1627 – or the same problem, and you just updated the Band firmware plus Gadgetbridge?

**Comment by ashimokawa** [comment]
I have no clue what the problem might be, it works for me. I also have no idea what you are trying to archive with the @ sign. Documentation is here:

https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-4

And I have no idea why you open two issues for one problem.

**Comment by ashimokawa** [comment]
Please continue in #1627, I already wrote there that your log stops when it gets interesting, and you re-upload the file *again*
