### ISSUE TITLE
Mi Band 4: Vibration not working

### ISSUE THREAD

**Issue by krombel** [Freeyourgadget/Gadgetbridge#1657]
After connecting GadgetBridge with my Mi Band 4 I was able to have a look at some stats and notifications are transfered to my band.

BUT: I just can see the notification but no vibration is triggered.
I already tried setting a different vibration pattern but none of them were working.

Is the support for that not there yet or did I just miss a setting?

I read #1536 so I know support is experimental right now. I just wanted to highlight this situation.

I am running 0.36.1 from F-Droid BTW.

**Comment by ashimokawa** [comment]
@krombel 
It works here - unfortunately.

Mi Band 4 support is quite good, but the fact that one has to register with xiaomi is the reason we will never recommend it. 

Also the vibration patterns in Gadgetbridge only work on Mi Band 1/2, they are ignored by Gadgetbridge.

Did you set any vibration patterns in Mi Fit? (is that possible?, if so, I would like to have bluetooth logs)

Also please double check if you have DND enabled on the band.

**Comment by krombel** [comment]
Ohh. That is weird...
Now as I tried it again it worked... Might be, that there was DND enabled although I checked it...

Closing this then. Thanks for your response (and for your work on this app in the first place :) )
