### ISSUE TITLE
Amazfit bip. Does not flash new fonts

### ISSUE THREAD

**Issue by MyTimeKill** [Freeyourgadget/Gadgetbridge#1659]
Font format updated
(file removed)

**Comment by ashimokawa** [comment]
@MyTimeKill 
Where did you get the font from. It has exactly ONE byte difference. Which Firmware is your Bip?

**Comment by MyTimeKill** [comment]
The font was taken from Mifit, it downloads these files by OTA. I know that changes in one byte do not flash because of this. Current version on bip 1.1.6.30

**Comment by ashimokawa** [comment]
@MyTimeKill 
Is that a Bip Lite?
Never saw that firmware...

**Comment by MyTimeKill** [comment]
Not lite, model  А1608. Just started to update yesterday

**Comment by ashimokawa** [comment]
@MyTimeKill 
I see... I will try to find that version but please do not upload it here
