### ISSUE TITLE
After installation previous data is not displayed

### ISSUE THREAD

**Issue by imendiguren** [Freeyourgadget/Gadgetbridge#1660]
#### Before reporting a bug, please confirm the following:
- [X ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

### I got Gadgetbridge from:
* [x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

If you got it from Google Play, please note [that version](https://github.com/TaaviE/Gadgetbridge) is unofficial and not supported here; it's also often quite outdated. Please switch to one of the above versions if you can.

#### Your issue is:
After installing Gadgetbridge, it will not retrieve previous data. I have alsoMiFit and it displays all data since I bought the watch.

#### Your wearable device is:
Amazfit Bip

#### Your android version is:
PixelExperience
#### Your Gadgetbridge version is:
0.35.2.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by vanous** [comment]
Hi,

this is normal. All your data is with Xiaomi. Thanks to GDPR, you now use the in app export to retrieve your data. Importing is currently not supported in Gadgetbridge, but you could do it manually. All precious data is collated into days, rather then "per minute". You can read a bit [here](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Data-Export-Import-Merging-Processing), but detailed instructions on how to merge previous MiFit data has not been documented yet. There are few tickets here where this is discussed.

**Comment by vanous** [comment]
Actually, here is the original issue in the tracker: https://github.com/Freeyourgadget/Gadgetbridge/issues/252

I would suggest closing this one as it is a duplicate. Do you agree @imendiguren ?

**Comment by imendiguren** [comment]
Sure, thank you very much for the info!
