### ISSUE TITLE
Mi Band 4 OWP weather not syncing

### ISSUE THREAD

**Issue by n8name** [Freeyourgadget/Gadgetbridge#1669]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### I got Gadgetbridge from:
* [x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

#### Your issue is:
After the successful setup of my Mi Band 4 (FW: V1.0.6.16) and Gadgetbridge (0.36.2) with my LOS OnePlus One and the  OpenWeatherProvider (including API and custom location) no weather is synced, although the CLock widget receives updates.
Everything else is working quite good for a WIP device. So thank you for providing this application!

#### Your wearable device is:
Mi Band 4 (FW: V1.0.6.16)

#### Your android version is:
LineageOS 16.0-20190930-microG-bacon (OnePlus One)

#### Your Gadgetbridge version is:
0.36.2

**Comment by ashimokawa** [comment]
Did you speciify the location in Gadgetbridge also?

**Comment by n8name** [comment]
Of course not....
And now I feel really stupid following the guide step by step and completely overlooking the abbreviations (CM/LOS) in the settings.
It works perfectly!

**Comment by ashimokawa** [comment]
@n8name 
Where would you add such a note?

**Comment by n8name** [comment]
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Weather#install-and-configure-openweatherprovider
+ "And finally set the same location in the Gadgetbridge weather settings." Or similar.

**Comment by ashimokawa** [comment]
Does not need to be the same, also it works without clock widget at all.

Volunteers for the wiki?

**Comment by vanous** [comment]
Missed the comment. Wiki edited.
