### ISSUE TITLE
mi band 4 UI text refers to mi band 2

### ISSUE THREAD

**Issue by FransM** [Freeyourgadget/Gadgetbridge#1671]
#### Before reporting a bug, please confirm the following:
- [ x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

### I got Gadgetbridge from:
* [ x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

If you got it from Google Play, please note [that version](https://github.com/TaaviE/Gadgetbridge) is unofficial and not supported here; it's also often quite outdated. Please switch to one of the above versions if you can.

#### Your issue is:
Mi Band 4 shows  mi2_prefs_button_actions_summary in the settings  UI. The text for this message is: " Specify actions on Mi Band 2 button press"
As this is also shown on mi band 4 I suggest to remove the number 2 from the message

#### Your wearable device is:
mi band 4

#### Your Gadgetbridge version is: latest from f-droid, string above is still present in weblate

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by FransM** [comment]
As a followup: I decided to change "Mi Band 2" to just "Mi Band" in the Dutch translation. I do not feel empowered enough to change this in the root text or in other languages.

**Comment by ashimokawa** [comment]
I have no idea what you are talkjng about. That feature IS for the Mi Band 2 only.

To avoid further confusion I am slooooowly migrating everything to per-device settings.

**Comment by FransM** [comment]
Ah ok, I changed it back.
It was my impression that this feature was also applicable for mi band 4  as I got this in the UI of my mi band 4.

What about hiding the settings that are not applicable for the registered device(s) ?

**Comment by IzzySoft** [comment]
They are moved to device-specific settings pages, which still is a WIP – as Andreas just stated:

> To avoid further confusion I am slooooowly migrating everything to per-device settings.
