### ISSUE TITLE
[Amazfit Cor 2] - Swimming lock screen 

### ISSUE THREAD

**Issue by leontino** [Freeyourgadget/Gadgetbridge#1674]
One exercise type is Swimming, I make this, and when I put to make exercise and I start swimming, the water unlock the Amazfit Cor 2 and Pause the exercise. I had swim with Mi band 4 and the unlock to Swimming Exercise is different.

So, you can make a different unlock type to all exercises ?

**Comment by vanous** [comment]
I do not have the Cor 2 but am presuming that this functionality is strictly related to the watch and not the the companion app at all...

**Comment by ashimokawa** [comment]
@leontino 
If this is possible in Mi FIt we could do it. Else not. This is not a custom firmware project, we just do the Android side...

**Comment by leontino** [comment]
Ow ok. Thank your attention guys! I'm sorry too hahaha
