### ISSUE TITLE
Amafit Bip Lite and Firmware

### ISSUE THREAD

**Issue by MyTimeKill** [Freeyourgadget/Gadgetbridge#1678]
Hello. 
I managed to get a given watch from a friend and test it with GadgetBridge. The connection to the clock in the current state does not work, build with the latest commits. I also managed to get the latest firmware versions. I can share with you. Where to send you?

**Comment by ashimokawa** [comment]
Did you extract the keys from mi fit etc?

**Comment by MyTimeKill** [comment]
No, I didn’t get the keys, but I'll try to do it soon

**Comment by MyTimeKill** [comment]
But for example, I know that other programs connect without a key and can flash firmware.

**Comment by vanous** [comment]
@MyTimeKill you need to follow the procedure here: https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Huami-Server-Pairing , without it, Gadgetbridge will not work.

**Comment by MyTimeKill** [comment]
@vanous I have seen that. But in other programs it is implemented without keys and everything works there.

**Comment by vanous** [comment]
Only if you use some cracked apps or rooted phone, or another bands which do not require server based pairing. Mi Band 4 and Amazfit Bip Lite, however, require this and there is no way around.

**Comment by ashimokawa** [comment]
@MyTimeKill 
You really mean without a patched mi fit that dumps the keys? I have no idea why people keep telling me all kinds of rumors.
If you really want to try without keys then go to AmazfitBipLiteSupport.java and change

`    public byte getCryptFlags() {
        return (byte) 0x80;
    }
`
to
`    public byte getCryptFlags() {
        return (byte) 0x80;
    }
`

**Comment by ashimokawa** [comment]
I closed this because we already have #1648 , please continue there

**Comment by MyTimeKill** [comment]
@ashimokawa This is not true. I tested 2 programs, Amazfit Masters and Notify & Fitnes, and they work without keys
