### ISSUE TITLE
Installed Bip firmware on a Bip lite

### ISSUE THREAD

**Issue by surfacetoairmissiles** [Freeyourgadget/Gadgetbridge#1681]
First I want to start by saying I am an absolute fool. 

I have both an Amazfit Bip and an Amazfit Bip Lite, both connected to the same device, I was updating the language files on the Bip and ended up pushing them to the bip lite instead. Quite hilariously this did not brick the device and, after flashing the rest of the firmware it still functions, though now believing itsself to be a standard bip.

It has issues with the physical lack of gps, and the mi fit app makes a fuss when trying to update the a-gps, but the rest seems functional. 

As fun as this little error has been, and as glad as i am that my 2nd watch isnt bricked, i would very much like to restore it to bip lite firmware. After a couple hours digging i haven't been able to locate any version of the bip lite firmware, since it is so new. also since mi fit views the device as a bip, it only tries to download bip firmware. 

I would suggest a sanity check against flashing the bip lite with bip firmware.
Also is there a source for bip lite firmware, so i can flash the device back to stock?

**Comment by ashimokawa** [comment]
How did you do that? Bip Lite support in 0.36.2 was not functional according to testers, after that when switching to the new pairing scheme which involves extracting the key from mi fit, I did prevent firmware flashing the bip lite (in 0.37.0, tagged, not on fdroid yet)

Could it be that you had the bip lite on firmware 1.1.5.xx which possibly did not enforce server side pairing and that is why you could pair it as a bip in 0.36.2?

Please shed some light on the issue

**Comment by surfacetoairmissiles** [comment]
thats most likely the case since it was a fresh out of the box bip lite that i'd had sitting around for a while

**Comment by MyTimeKill** [comment]
@ashimokawa They are flashing with other programs, I have already seen this.

**Comment by ashimokawa** [comment]
So it is still unknown whether initial firmware 1.1.5.xx for the bip lite allows to connect without auth key?

And I still wonder if firmware 1.1.6.xx is unified (bip/bip lite).
@surfacetoairmissiles 
Which version did you flash, was it 1.1.5.xx or 1.1.6.xx?

**Comment by MyTimeKill** [comment]
@ashimokawa resource files are identical on of latin (checksums match), firmware is slightly different. I have already said that other programs are connected without a key and even flashing firmware without any problems.

**Comment by mim0kr0k0dil** [comment]
@ashimokawa, here're the Bip Lite firmware files:

[bip_lite_1.1.6.02_non-latin.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/3728979/bip_lite_1.1.6.02_non-latin.zip)
[bip_lite_1.1.6.32_latin.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/3728981/bip_lite_1.1.6.32_latin.zip)

**Comment by ashimokawa** [comment]
Please do not upload copyrighted material here.
