### ISSUE TITLE
Forget to disconnect, reinstalled application but not connecting with band 

### ISSUE THREAD

**Issue by siddhpuraamitr** [Freeyourgadget/Gadgetbridge#1687]
I got Gadgetbridge from: Google Play Store
I have installed app and connected with my Mi Band 3, every thing is working fine, but I forgot to disconnect my band and I have reinstalled your app, now problem is my band is not founded, even original mi band 3 app is also not finding my Mi Band 3, Please help me to resolve this issue.

**Comment by ashimokawa** [comment]
Remove band from android Bluetooth settings.
Toggle Bluetooth on the phone.
Search for it again in Gadgetbridge

**Comment by siddhpuraamitr** [comment]
thanks for your help
