### ISSUE TITLE
cert for gadgetbridge.org has expired

### ISSUE THREAD

**Issue by jugmac00** [Freeyourgadget/Gadgetbridge#1690]
> Expires On	Tuesday, October 15, 2019 at 12:14:48 PM

This seems to be a regular issue (cf #1402). Maybe use a cronjob?

**Comment by ashimokawa** [comment]
There is a cronjob, probably service restart missing, will check later.

**Comment by ashimokawa** [comment]
Done, service restart was missing. This is done now automatically
