### ISSUE TITLE
Lineage OS: Notifications not working on Amazfit Bip after upgrading LOS

### ISSUE THREAD

**Issue by tibaultbordeaux** [Freeyourgadget/Gadgetbridge#1692]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

### I got Gadgetbridge from:
* [x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

#### Your issue is:
I was using GB on LOS 16 quite succesful (besides reconnection issues).
But after one of the last updates of LOS notifications stopped working.

I reinstalled GB and double-checked all permissions, especially all mentioned in the [wiki](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Incoming-call-notification-on-Lineage-OS)

I even tried to use the official Mi Fit app, but I'm not able to log in there (maybe that's because Google Play Services are missing on my device?)

Any hints?

Thanks in advance

Tibault

#### Your wearable device is:

Amzefit Bip FW 1.1.5.16

#### Your android version is:
LineageOS 16

#### Your Gadgetbridge version is:
0.37.0

**Comment by ashimokawa** [comment]
You mean all notifications? Or call notifications?
Both work here on lineageos 16 build from yesterday.

**Comment by tibaultbordeaux** [comment]
Yes, all notifications ...

**Comment by tibaultbordeaux** [comment]
Log ist full of those lines:

13:56:29.474 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x9a 0x35 0x38 0x20 0x77 0x65 0x65 0x6b 0x64 0x61 0x79 0x20 0x69 0x73 0x20 0x35 0x0d 0x0a 0x5b 0x31
13:56:29.475 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x9b 0x39 0x30 0x38 0x35 0x38 0x37 0x37 0x34 0x5d 0x20 0x73 0x74 0x6f 0x72 0x65 0x20 0x31 0x31 0x32
13:56:29.476 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x9c 0x20 0x30 0x20 0x30 0x20 0x32 0x35 0x35 0x2c 0x20 0x61 0x63 0x63 0x53 0x69 0x7a 0x65 0x3d 0x31
13:56:29.477 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x9d 0x35 0x32 0x37 0x0d 0x0a 0x5b 0x31 0x39 0x30 0x38 0x35 0x38 0x37 0x37 0x35 0x5d 0x20 0x74 0x70
13:56:29.478 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x9e 0x20 0x65 0x76 0x65 0x6e 0x74 0x3d 0x30 0x2c 0x20 0x72 0x65 0x61 0x64 0x3d 0x30 0x2c 0x20 0x64
13:56:29.511 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0x9f 0x69 0x73 0x5f 0x73 0x74 0x61 0x74 0x65 0x3d 0x30 0x0d 0x0a 0x5b 0x31 0x39 0x30 0x38 0x35 0x38
13:56:29.512 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0xa0 0x37 0x38 0x34 0x5d 0x20 0x70 0x72 0x76 0x53 0x74 0x6d 0x33 0x32 0x6c 0x34 0x37 0x36 0x61 0x70
13:56:29.514 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0xa1 0x70 0x54 0x61 0x73 0x6b 0x20 0x6e 0x6f 0x74 0x69 0x66 0x3d 0x34 0x0d 0x0a 0x5b 0x31 0x39 0x30
13:56:29.557 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0xa2 0x38 0x35 0x38 0x37 0x38 0x34 0x5d 0x20 0x42 0x61 0x74 0x74 0x65 0x72 0x79 0x20 0x70 0x65 0x72
13:56:29.559 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0xa3 0x63 0x65 0x6e 0x74 0x20 0x69 0x73 0x20 0x39 0x34 0x20 0x0d 0x0a 0x5b 0x31 0x39 0x30 0x38 0x38
13:56:29.562 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0xa4 0x39 0x35 0x36 0x32 0x5d 0x20 0x5b 0x54 0x49 0x4d 0x45 0x5d 0x20 0x32 0x30 0x31 0x39 0x2d 0x31
13:56:29.563 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0xa5 0x30 0x2d 0x31 0x38 0x20 0x35 0x3a 0x31 0x36 0x3a 0x35 0x38 0x20 0x77 0x65 0x65 0x6b 0x64 0x61
13:56:29.565 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0xa6 0x79 0x20 0x69 0x73 0x20 0x35 0x0d 0x0a 0x5b 0x31 0x39 0x30 0x38 0x38 0x39 0x35 0x36 0x32 0x5d
13:56:29.567 [Binder:2979_5] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000005-0000-3512-2118-0009af100700 value: 0xa7 0x20 0x73 0x74 0x6f 0x72 0x65 0x20 0x31 0x31 0x32 0x20 0x34 0x20 0x30 0x20 0x32 0x35 0x35 0x2c

Look at the timecodes: Every few milliseconds a new message. I found hundreds of them in a log enabled for a few seconds.

**Comment by ashimokawa** [comment]
This is data fetched from the watch "notification" here is a Bluetooth LE term, a way of delivering data.

Are notifications working in the debug menu?

**Comment by tibaultbordeaux** [comment]
No, as far as I see nothing from the debug menu is working.

**Comment by ashimokawa** [comment]
Is your bip in dnd mode?
Swipe up from the watch face and tap on the screen

**Comment by tibaultbordeaux** [comment]
Shame on me!
My watch is in DND mode?!!! (How did it get there ...?)
Sorry, folks, for wasting your time!

Feature request: Notify the user inside of gagdgetbridge: "You gadget is in DND mode. Don't wonder if you do not get any notifications" plus a link to a short instruction on how to disable it.

Thanks @ashimokawa !
