### ISSUE TITLE
Device Request: Amazfit GTS

### ISSUE THREAD

**Issue by nr458h** [Freeyourgadget/Gadgetbridge#1695]
Hi it would be awesome if we could get support for the amazfit gts.

As I'm a complete noob in regards of software I can not provide any further information.

Thanks in advance.

_Gesendet  mit [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by ashimokawa** [comment]
@nr458h 
Yes would be cool but I do not have the device, at least some people who are able to compile the source code into an apk and report back are necessary.

**Comment by weliem** [comment]
I just received mine...

Did a quick check:
- Advertisement name is "Amazfit GTS"
- Same services/characteristics as MiBand4

Will do a HCI snoop to see more details

**Comment by ashimokawa** [comment]
@weliem 
Thanks,
it should be recognized in master, running as a derrived Mi Band 3 so far (I will change that I guess)
Would be good to know:

- hci dump when setting the menu items
- which settings are supported? (I mean things like lift wrist, etc)

**Comment by thot1** [comment]
Hello *, I checked in the changes a few days ago and have been testing the various features ever since. (Some features are not in the repository yet)

What works:
- Export of activities with GPS and HR data
- wearlocation (left/right)
- liftwrist_display
- swipeunlock

Which doesn't work:
- the weather forecast (not correct)
- Notifications (the clock receives these, but only indicates them)

**Comment by ashimokawa** [comment]
@thot1

Please check latest master. I fixed a lot of stuff yesterday. Notifications should work.

Weather is probably your "fault", read the wiki about your options ;)

**Comment by thot1** [comment]
I have seen and tested the changes. You're right, it works well.
So most of the work is done! Cool :-)

**Comment by weliem** [comment]
I am not able to pair my GTS. After it sends the encrypted response I get an error: 0x10 0x83 0x07

**Comment by weliem** [comment]
The GTS doesn't have the server element in the pairing flow, right?

Here is a the flow I see in the snoop log:

- Read 000000200000351221180009af100700
- Receive 0b
- Turn on notify for 000000200000351221180009af100700
- Turn on notify for 000000090000351221180009af100700
- Write 0100 to 000000090000351221180009af100700
- Receive 100181011863c2cce5d159413bed92c4b163c279 from 000000090000351221180009af100700
- Write 820002 to 000000090000351221180009af100700
- Receive 1082012825a93ac207334cbcc91d3e166b6710 from 000000090000351221180009af100700
- Write 83:00:9a:6e:33:16:be:5a:6c:81:50:7e:2b:86:2c:e4:4a:6a to 000000090000351221180009af100700
- Receive 108301 from 000000090000351221180009af100700
- Turn off notify for 000000090000351221180009af100700
...

**Comment by ashimokawa** [comment]
@weliem

AFAIK it has that. 
You need the master branch and enter the key extracted from mitfit (or from the above log ;) )

**Comment by nr458h** [comment]
Hey guys I received my gts today and I would like to ask if you think that we will have a working release (without the need to build it on my own and to get the ID from the anazfit app) soon? 

Because I can't test my gts, as the amazfit app is not working with lineageos oneplus 5t. Is there anything I can do?
would be great - thanks for your effort anyway!

m

**Comment by ashimokawa** [comment]
I will tag a release today

**Comment by ashimokawa** [comment]
@nr458h 
You have to get the key from the amazfit app. There is nothing we can do about that. Apart from that 0.39.0 is tagged and should work with the GTS

**Comment by ashimokawa** [comment]
I am closing this, please report individual issues

**Comment by nr458h** [comment]
many thanks for the fast response. I will have a look at this as soon as the release hits the f-droid store

**Comment by nr458h** [comment]
just for those who don't know that this key-thing is similar to mi band 4.

Please have a look here![here](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Huami-Server-Pairing) on how to pair your gts
