### ISSUE TITLE
[Miband] Sync does not work

### ISSUE THREAD

**Issue by Mikab0** [Freeyourgadget/Gadgetbridge#170]
After making an firmware update the sync does not work. The connection between the app and Miband works. I can set an alarm (vibration after setting), but I cannot sync the tracking data. The App is breaking the connection while it is trying to sync.

**Comment by cpfeiffer** [comment]
Could you please post some now details? Which Kong of mi band do you have, which firmware version and possibly a log of a failed sync.

Also, did it work well with your previous firmware version (which)?

**Comment by Mikab0** [comment]
Sorry, it seems to be my fault. I made new pairing with my miband and the sync started to work after that. Curios that the alarm was working without that.

**Comment by cpfeiffer** [comment]
Alright, thanks for the info. We'll make that more clear to the user.
