### ISSUE TITLE
Colors in statistcs

### ISSUE THREAD

**Issue by keihuli** [Freeyourgadget/Gadgetbridge#1702]
I cannot see a diffrence between orange and green (heart rate and activitiy). It is possible to make a config of the colour or use other colurs like: dark red and green...

#### Before requesting a new feature, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*If applicable, please attach [logs](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files)*

#### Your wearable device is:

*Please specify model and firmware version if possible*

#### Your Gadgetbridge version is:

*New requests about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by vanous** [comment]
@keihuli dark red like this? https://duckduckgo.com/?q=%238B0000&t=ffsb&ia=answer

**Comment by vanous** [comment]
Proposed here: https://github.com/Freeyourgadget/Gadgetbridge/pull/1703

**Comment by keihuli** [comment]
Yes perfect

**Comment by ashimokawa** [comment]
Merged #1703, so will close this, thanks @vanous
