### ISSUE TITLE
Weather not updating on MB4

### ISSUE THREAD

**Issue by lakyljuk** [Freeyourgadget/Gadgetbridge#1704]
I am using LOS 16, with latest Gadgetbridge and MB4. All working except weather. I installed LOS Openweather provider, configured cLock widget to get location automatically and to refresh every 30 minutes. Entered API key. Now I see widget is updating correctly every 30 minutes, location reflects my real location and weather is quite acurate. Thing is, Gadgetbridge cannot get this info and on MB4 is some other city 25 km far away and with old weather data. I tried:
1) restart phone
2) restart MB4
3) unpair / re-pair MB4 with Gadgetbridge
4) unistall and reinstall weather provider
5) change location manually to another city 

Can somebody help with this, so I could get weather on MB4?

**Comment by ashimokawa** [comment]
Did you read #1669? You have to set the location in Gadgetbridge also.

**Comment by lakyljuk** [comment]
I did not, because your guide at https://github.com/Freeyourgadget/Gadgetbridge/wiki/Weather mentions no such thing. It mentions I should install LOS provider and set it to auto localtion or fixed location. So I did that and it is not working. When I do it your way, to set fixed location in GB settings, it will not be auto updating as I change location and I will always have to set it again?

**Comment by ashimokawa** [comment]
@lakyljuk 
It is not my guide, someone wrote it, it is obviously incomplete, I asked for volunteers in #1669, no one did anything. I cannot as a single person with a day job and family do everything.

And yes if you set the location in GB settings it won't auto update.
The location set in cLock and GB are independent, we cannot query the location from cLock afaik.

If you want automatic location, try weather notification. There we get the location from the app. Of course all this could be done better but time and developers are the limiting factor.

**Comment by vanous** [comment]
Wiki edited, you may close this.

**Comment by lakyljuk** [comment]
Thanks, all is working now.
