### ISSUE TITLE
gadgetbridge older version

### ISSUE THREAD

**Issue by bandonm** [Freeyourgadget/Gadgetbridge#1708]
Sorry, I do not speak english and this is a web translation.
My previous search for FDroid, Codeberg, etc. was unfortunately without success.
I need Gadgetbridge versions 0.36.0 and 0.36.1
How do I get them or where can I still download them?
For a hint, I'm very grateful.
greetings

**Comment by ashimokawa** [comment]
https://f-droid.org/archive/nodomain.freeyourgadget.gadgetbridge_155.apk

https://f-droid.org/archive/nodomain.freeyourgadget.gadgetbridge_155.apk

**Comment by bandonm** [comment]
Thanks, for the very fast help.
