### ISSUE TITLE
No weather info on MB4

### ISSUE THREAD

**Issue by FransM** [Freeyourgadget/Gadgetbridge#1719]
#### Before reporting a bug, please confirm the following:
- [ ]x I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

### I got Gadgetbridge from:
* [ x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

If you got it from Google Play, please note [that version](https://github.com/TaaviE/Gadgetbridge) is unofficial and not supported here; it's also often quite outdated. Please switch to one of the above versions if you can.

#### Your issue is:
When I go to the weather Icon it says "Connect to  Mi Fit  to get weather info.
In the app I selected a weather location (CM/LOS).
It used to work before (but not super reliable). I noticed it after upgrading both the FW on the MB4 and upgrading GB

#### Your wearable device is:

Mi Band 4 FW 1.0.6.24 (latest stable installed through Mi Fit)

#### Your Gadgetbridge version is:
0.38 iirc (latest version from F-Droid

**Comment by ashimokawa** [comment]
Thanks. Will update my mi Band 4 this evening

**Comment by ashimokawa** [comment]
@FransM 
I just tested with 1.0.7.04, works here. Very strange, do you use your own api key for the openweathermap lineage os weather provider or a shared one?

**Comment by FransM** [comment]
I'll investigate tommorow.Seems the weather app cannot connect, maybe it lost the key

**Comment by FransM** [comment]
It seems the openweathermap provider did not work.
I got "weather update failed  problem communicating with api"
This was with my own key.

https://bitbucket.org/gelin/weather-notification/issues/48/weather-update-failed-problem suggested to remove my private key and that works (at least for now).

I'm not really sure what the root cause is. I've been running with that key for two months or so, and looking at the log things stopped working on Oct 25.

(btw this is all on Android 7.1 on Motorola, not on lineage, weather provider installed from F-droid.)

Anyway: not a GB issue so closing.
