### ISSUE TITLE
Add some info how to use Mi Fit and Gadgetbridge

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#172]
Maybe add some info popup inside Gadgetbridge, or at least a wiki page, linked from README.md

**Comment by bigretromike** [comment]
From what I see you dont need Mi Fit any more to work with Mi band :+1: 
Is it time to close this one? Or you thinking about leaving data on device when syncing ?

**Comment by cpfeiffer** [comment]
It was never necessary to use Mi Fit -- Gadgetbridge could be used standalone since its birth.

This ticket is just a reminder to document how to use them together *if you want it*.

**Comment by danielegobbetti** [comment]
This looks superseded by info in the wiki: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Compatibility-Issues#mi-fit Please repen if this is not the case.
