### ISSUE TITLE
Amazfit bip doesnt reconect after lost connection

### ISSUE THREAD

**Issue by segalion** [Freeyourgadget/Gadgetbridge#1724]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

### I got Gadgetbridge from:
* [x] F-Droid
* [ ] I built it myself from source code (specify tag / commit)

#### Your issue is:

Gadgetbridge report "Not connected" so no notification is sent. 
Amazfit bip report "Bluetooth connected"

This has been happen in my old Samsung Galaxy S5, and I suppose it was because the bad old blouetooth stack of the phone, but it happens the same in a Xiaomi Mi 9T, so I suppose is a gadgetbridge problem.

#### Your wearable device is:
Amazfit bip with latest firmware (1.1.6.36)

#### Your android version is:
Android 9
#### Your Gadgetbridge version is:
0.38

This is probably the worst problem because if ramdonmly no notification, gadgetbridge is not a posible replacement.

**Comment by ashimokawa** [comment]
Use Mi Fit if you want support

**Comment by vanous** [comment]
@segalion or  @IzzySoft kindly please press the `close` button here . Cheers.

**Comment by ashimokawa** [comment]
Can stay open, I don't care. Will fix the problem when I have time and I feel like it.

I just do not like demanding comments, insults, etc.

Remember users here are not customers! If you find things annoying, fix them, contribute, or use another software then Gadgetbridge, but do not demand spending our free time on one specific issue.

**Comment by segalion** [comment]
Please, sorry @ashimokawa . I dont want to offend at all,  only want to report what I have found, and try to mark the importance of the notifications in this kind of wereables.
I appreciate your great work , and I never demand people work for me. And I undesrtand the crap of internal mysteries of android making harder and harder life for developers.

(A lot ago I made scripts in Automagic to detect disconnections and act over the gui to press button to reconnect again...)

**Comment by vanous** [comment]
>Codeberg-org closed this in c705374 4 hours ago

awesome!
