### ISSUE TITLE
Donations via Librepay possible again, thank you for donating!

### ISSUE THREAD

**Issue by vanous** [Freeyourgadget/Gadgetbridge#1729]
Hi all,

the team has decided to proceed with Librepay again, see copy/paste of the announcement posted in Matrix:

> After more than a year we bit the bullet and re-enbled donations on liberapay by complying with what had to be done to make that work. We were already almost dried up and were unable buy devices we wanted to support. To make Gadgetbridge even better please consider to donate.

>Do not want to push anyone but it was requested over and over again. And supporting new devices without having them is very time consuming ;)

So thank you very much for proceeding if you still consider supporting the project financially! 

<a href="https://liberapay.com/Gadgetbridge/donate" rel="nofollow"><img src="https://camo.githubusercontent.com/ae8af018f80649f3d379eb23dbf59acceaffa24e/68747470733a2f2f6c69626572617061792e636f6d2f6173736574732f776964676574732f646f6e6174652e737667" alt="Donate" data-canonical-src="https://liberapay.com/assets/widgets/donate.svg" style="max-width:100%;"></a>

I think this is a better way to get notification into existing issues which contain people who wanted to donate. Sorry @IzzySoft to spam you few times before, you were in most of them.

#1664 #1504 #1156 https://github.com/Freeyourgadget/Gadgetbridge/issues/112 https://github.com/Freeyourgadget/Gadgetbridge/issues/12 https://github.com/Freeyourgadget/Gadgetbridge/issues/14 https://github.com/Freeyourgadget/Gadgetbridge/issues/53 https://github.com/Freeyourgadget/Gadgetbridge/issues/67 https://github.com/Freeyourgadget/Gadgetbridge/issues/169

**Comment by IzzySoft** [comment]
Yes, I noticed – and simply deleted the notification mails. Thanks for caring!

<sup>PS: still catching up with my mails – just returned froma 2 week vacation.</sup>
