### ISSUE TITLE
Amazfit bip alarm issues (GB 0.39.1)

### ISSUE THREAD

**Issue by tlpwka** [Freeyourgadget/Gadgetbridge#1736]
### I got Gadgetbridge from:
* [ +] F-Droid 0.39.1

#### Your issue is:
Hello, great app! So far I found only an issue with alarms:

- Alarms from mi fit are not visible in gadgetbridge and deleted on sync from bip's.
- If I sync alarms with GB, there is some of them and they cannot be removed (even from mi fit), only one solution I found is reset the watch.
- After syncing alarms with GB, alarm menu in watch switch from 24H to 12H (AM/PM), only reset helped to switch it back.

#### Your wearable device is:

Amazfit bip v.1.1.6.36

#### Your android version is:
Android 9

#### Your Gadgetbridge version is:
0.39.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by vanous** [comment]
Gadgetbridge does not try to maintain anything with Mifit. Quite the opposite - we use Gb exclusively. So if you want to combine things this way, you are a bit on your own.

> Alarms from mi fit are not visible in gadgetbridge and deleted on sync from bip's.

At this point Gb is doing only one way sync of alarms: from app to the watch.

> If I sync alarms with GB, there is some of them and they cannot be removed (even from mi fit), only one solution I found is reset the watch.

There is the "Alarms to reserve for upcoming events", settings in Gb, try that...

> After syncing alarms with GB, alarm menu in watch switch from 24H to 12H (AM/PM), only reset helped to switch it back.

Just tested and my alarms are 24H.
