### ISSUE TITLE
Change the app icon in Pebble to something more user friendly

### ISSUE THREAD

**Issue by SaulNunez** [Freeyourgadget/Gadgetbridge#1737]
#### Your issue is:
On the device card there's several icons related to the functions the app can do to each device. The app icon is a bit strange as it doesn't has any context and Google's Material Design icons description the icon is displayed as copy, users might be confused between the context that icon it's normally seen. It could be changed from copy to something like [this](https://material.io/resources/icons/?search=app&icon=apps&style=baseline). 

I might even recommend text labels for all actions that can be done for all smart devices, it doesn't have room for doubt for anyone who is coming to try Gadgetbridge for the first time.

#### Your wearable device is:
Pebble

#### Your android version is:
9

#### Your Gadgetbridge version is:
0.39.1

![Screenshot_2019-12-01-17-46-49-426_nodomain freeyourgadget gadgetbridge 1](https://user-images.githubusercontent.com/13012976/69923529-dcae9180-1462-11ea-9b0a-45aecda4b12a.jpg)

**Comment by IzzySoft** [comment]
While I agree the app icon isn't that intuitive: could you please include a screenshot of the proposed one here? At least for me, that linked page doesn't work properly (I only see the icon descriptions, but not the icons themselves). Thanks!

**Comment by ashimokawa** [comment]
These are fine. Apache lincense.
Will change the icon

**Comment by vanous** [comment]
@IzzySoft firefox enhanced tracking protection :), same here, see the icon here:

<img src=https://fonts.gstatic.com/s/i/materialicons/apps/v1/24px.svg>

**Comment by IzzySoft** [comment]
@vanous thanks! It's Waterfox Classic here, though – nice to see that Alex even ported that part back (I still have the XUL goodies, while also getting the latest security fixes – cool that!)

And yes, that's clearer to stand for "apps" :smile:

**Comment by ashimokawa** [comment]
Changed in master
