### ISSUE TITLE
Please support sdkversion 18

### ISSUE THREAD

**Issue by abliss** [Freeyourgadget/Gadgetbridge#174]
I have my Nexus 7 pinned at 4.3.1 because of its vastly superior Bluetooth performance versus later versions. It would be great if I could run gadgetbridge on this device too!

**Comment by cpfeiffer** [comment]
Please test and report back :-)

**Comment by cpfeiffer** [comment]
Hold on, needs another change.

**Comment by cpfeiffer** [comment]
Hmm, even though I did not get any compile errors and could even run the build, I think I'm now at a dead end. I ran Analyze -> Inspect Code and it found many many places which won't work on API level 18.

I'm afraid we won't be able to support this, sorry.
