### ISSUE TITLE
Gadgetbridge crashes when not having K-9 Mail's permissions and trying to get mail content

### ISSUE THREAD

**Issue by testman86** [Freeyourgadget/Gadgetbridge#175]
Hi,

I am testing your very nice and usefull app. The possibillity to use pebble without vendor close source app was the reason to buy a Pebble yesterday :)

But after installing K-9 Mail, Gadgetbridge suddenly looses connection to Pebble Classic completely after receiving one e-mail while phones screen off (so notification should be send to Pebble) and needed to be reconnected (in Gadgetbridge) and selected over menu -> connect device -> and tap on device. So no automated reconnect was possible anymore.
When selecting notification while screen on I got a "Gadgetbridge forced close" notification on main screen and I have to restart Gadgetbridge and also reconnect Pebble manually.
I also tried to use "Blacklist Apps" and there selected K-9 mail but phone was still loosing connection completely and needed manual reconnect to pebble if "K-Mail Nofifications" were still selected.
The only thing (but its more a workaround) is to select "K-Mail Nofifications" to "never" and therefore let "Other Notificaitons" let inform you about incoming emails. This is also working flawless.

I hope this log might help you, if you need more information or if I should test other settings please feel free to contact me :)

I am on latest Pebble Firmware (updated from vendors App yesterday evening) and on Android CM12.1 5.1.1 on a Z1 compact. K-Mail version is 5.006

All other notifications are working flawless (also open apps remote etc.). Even reconnecting after coming home and switching bluetooth on on phone, pebble was connected automatically. 

[gadgetbridge.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/44964/gadgetbridge.txt)

**Comment by ashimokawa** [comment]
Thats strange.
According to you log it fails because Gadgetbridge does not have the permission "com.fsck.k9.permission.READ_MESSAGES"

But we request that permission in the Manifest!. And it is working fine here with 5.006.

This might be a stupid guess, but maybe Gadgetbridge has to be installed *after* K-9 Mail to successfully use that permission?

**Comment by ashimokawa** [comment]
@testman86 
You actually can install firmware updates from Gadgetbridge, no need for the vendors app.

**Comment by testman86** [comment]
Yep that solves the issue :) Strange that I always find such bugs :D 

A bit of topic, but how can I install firmware without vendors app? Couldn't find it in menu or somewhere else or an instruction for this.

**Comment by ashimokawa** [comment]
@testman86 
Here is a link which might help you:

http://www.pebbledev.org/wiki/Firmware_Updates/

 I cannot integrate this in Gadgetbridge, because we are not using internet permission (on purpose to be more trustable). I *might* create a small helper Android app when I feel like it.
