### ISSUE TITLE
Unable to reconnect if bluetooth-connection-settings are deleted in phone and Pebble and then reastablish bluetooth connection

### ISSUE THREAD

**Issue by testman86** [Freeyourgadget/Gadgetbridge#177]
Hi, I found another bug.

Unable to reconnect if bluetooth-device (pebble) is deleted in phone and in Pebble phone (as connected-device) is deleted. Then reastablish bluetooth connection (on both devices and accept pairing), Pebble is not found (by Gadgetbride) or if found  (by Gagdetbridge), not able to connect to Pebble. Also somehow Pebble is recognized as MiBand while Gadgetbridge is searching for devices.

The only solution was to delete bluetooth-connection on both devices, then reboot phone, went back to watchface (normal clock) on Pebble (cause if staying in bluetooth connection menu pebble can not be found by phone somehow, but this is a "bug" in the firmware not in Gadgetbridge) and then reinstall Gadgetbridge again and connect like using it the first time.

I got to know this issue cause I connected my Pebble to my tablet were vendor app was running and while I try reconnect to phone this issue occured. But (as described above) even if connection was established once, deleting bluetooth-pairings will lead to be unable to find Pebble with Gadgetbridge again.

Again two logs which might alos help you this time.

[gadgetbridge-1.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/46443/gadgetbridge-1.txt)
[gadgetbridge-2.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/46444/gadgetbridge-2.txt)

**Comment by ashimokawa** [comment]
I can reproduce the Pebble being displayed as Mi after repairing.

When I quit Gadgetbridge (through the menu) and restarted, it displayed correctly as Pebble and then failed to connect once. Just tapping again made it work.
