### ISSUE TITLE
Gadgetbridge crashes when trying to access external data dir

### ISSUE THREAD

**Issue by nathans** [Freeyourgadget/Gadgetbridge#179]
Gadgetbridge 0.6.6 works with my pebble (notifications, etc.), however when I try to open the app manager, the application crashes ("Unfortunately Gadgetbridge has stopped"). Anything that can be done?

Hardware: V3R3
FW: 2.9.1

**Comment by ashimokawa** [comment]
@nathans 
I have the same Pebble Model as you, same FW. For me it works unfortunately.
If you send logs, I will try fix that today.

My guess is that it has to do with the crippled app manager for FW 3.x for which I read in the "pbw-cache" from sd-card. Maybe there an uncaught exception occurs.

**Comment by ashimokawa** [comment]
I tried to reproduce this without success, also looking at the code didn't help.
So I need your logs.

**Comment by nathans** [comment]
Aftern turning on logging and quitting gadgetbridge it now will not start up at all. Unfortunately no logs are present to capture the startup crash.

**Comment by ashimokawa** [comment]
@nathans 
Thank you for testing, in fact that information already helps a bit.

It really seems impossible to open the external data dir on your phone (for writing the logs or reading previously installed .pbw files in the app manager).

you can use still use adb to obtain a log. In the meantime we could make our code more failsafe and disable writing log files /and reading the pbw cache when there is no access to an external data dir. For whatever reason.

@cpfeiffer @danielegobbetti 
Any ideas on this?

**Comment by ashimokawa** [comment]
This is most probably a duplicate of #167, which is already fixed in master.
We will release 0.6.7 on the weekend and I am quite optimistic it will fix the issue for you.

**Comment by nathans** [comment]
OK I'll try 0.6.7 and report back when I know more. Thanks!

**Comment by ashimokawa** [comment]
I just tagged 0.6.7, it will hit f-droid probably tomorrow (we can only wait, f-droid does this automatically).
Please let me know if your problems are fixed with 0.6.7.

**Comment by nathans** [comment]
This is fixed. App manager now works correctly when using 0.6.7. Thanks!
