### ISSUE TITLE
Doesn't work with Pebble 3.8 beta-6 recovery firmware (OG)

### ISSUE THREAD

**Issue by haecker-felix** [Freeyourgadget/Gadgetbridge#181]
The app does connect with my Pebble OG watch, but the app does only says: "initialisiert". The Pebble watch keeps at the setup screen. I have got the update over the Pebble app. But the old app doesnt work with the new firmware.

Nexus 5 Android 6.0
Gadgetbridge 0.6.6 

![img_20151206_101418](https://cloud.githubusercontent.com/assets/6001248/11612622/3b627062-9c02-11e5-9ddf-4ca5529a96a6.jpg)
![screenshot_20151206-101244](https://cloud.githubusercontent.com/assets/6001248/11612623/3b64a6e8-9c02-11e5-94a8-0f32c25fbeb7.png)
![screenshot_20151206-101222](https://cloud.githubusercontent.com/assets/6001248/11612621/3b61f4d4-9c02-11e5-85e0-7fc6d084af7c.png)

**Comment by haecker-felix** [comment]
Daniele Gobbetti says i could flash the real 3.x firmware with this app. How i can do this?

Btw sorry for bad english.

**Comment by haecker-felix** [comment]
I just flashed the 3.8 beta-4 firmware with your app. Now does the watch works :).

**Comment by ashimokawa** [comment]
@haecker-felix 

Before doing anything, press the left button for 5 seconds, it helped me to get out of that screen on my pebble when it arrived (I NEVER used the official app)

If that does not work (which I assume), it seems that you are in recovery mode, that's interesting because I don't know how you got there. Did you flash a "migration firmware" from the official app?

Now to answer your question:
You can flash firmwares by selecting .pbz files in a file manager and chose to open with "FW/App Installer".

I have seen three different 3.8 beta firmwares so far (without flashing any of them):
3.8-beta4 (migration)
3.8-beta4 (normal)
3.8-beta9 (dated 5. December 2015), no normal and migration variant.

If you flashed 3.8-beta6 migration then I would suggest to flash 3.8-beta6 (normal) or if you do not have that file 3.8-beta9.

In any case PROCEED ON YOUR OWN RISK. I don't think you will brick your pebble but I can't guarantee of course.

**Comment by ashimokawa** [comment]
@haecker-felix 
Oh you were faster then me ;)
Could you answer me how you got into that screen you posted?
Did you flash the migration fw?
And you can also flash beta9 from yesterday.

Hint: the url has changed from release-v3 to release-v3.7

**Comment by haecker-felix** [comment]
I've got a watch update over the original pebble app. I think it was the migration firmware. Now I flashed the 3.8-beta4. The watch works fine. 

Oh the beta9 is aviable? Than I flash this :)

**Comment by ashimokawa** [comment]
I closed this because it seems to be a non-issue. Anyway, thanks for reporting here, your input was very valuable to our project.

You can still comment in the closed issue ;)

**Comment by haecker-felix** [comment]
Can you give me the link for the beta-9? Because this link doesnt work:

https://pebblefw.s3.amazonaws.com/pebble/v1_5/rrelease-v3.7/pbz/normal_v1_5_v3.8-beta9.pbz

**Comment by ashimokawa** [comment]
The file is called
Pebble-3.8-beta9-v1_5.pbz

**Comment by haecker-felix** [comment]
Yes i found it.

https://pebblefw.s3.amazonaws.com/pebble/v1_5/release-v3.7/pbz/Pebble-3.8-beta9-v1_5.pbz

**Comment by ashimokawa** [comment]
@haecker-felix 
Good luck.

**Comment by haecker-felix** [comment]
Flashed it successfuly. Work's fine.

**Comment by ashimokawa** [comment]
I also flashed the migration firmware 3.8-beta6 and from there 3.8-beta9
Everything with Gadgetbridge.
In the final result it seems that my recovery also got updated to 3.8-beta6 (seemingly by the migration process)

**Comment by ashimokawa** [comment]
@haecker-felix 
I added this information, please share it to your G+ buddies before they break their watch by trying something stupid ;)
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Firmware-updates

**Comment by haecker-felix** [comment]
Okay. Done.

**Comment by ashimokawa** [comment]
@haecker-felix 
Thanks, but can you point to the wiki directly, not this issue:

https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Firmware-updates

I mean, I know most people wont read and I do not know what happens when flashing 3.x without the migration firmware, so what I did is documented there with some fat warnings. They might end up with a brick and blame us, or blame us that  they cant use the Pebble app anymore.

This is supposed to help people not to lure them to a situation they do not like. And it seems most people love pebble Inc's official app ;)

**Comment by haecker-felix** [comment]
Okay i understand. I found a new bug:

When I load a watchface (pbw) and select it on the watch, your app crash. I think its because my pebble want to load it from the phone (No 8 apps limit)

**Comment by ashimokawa** [comment]
@haecker-felix 
For me this works, in fact basic FW 3.x support in Gadgetbridge since a long time ago.

You can create an issue (with logs please) but please try Gadgetbridge 0.6.7 before,  which just got into f-droid a few moments ago.

**Comment by ashimokawa** [comment]
@haecker-felix 
Also make sure to read #179 and #93

**Comment by haecker-felix** [comment]
Okay I updated to 0.6.7 and reseted my pebble to test it. I can't install ANY pbz or pbw file now. It says:

pbw/pbz is broken or incompatible with your Hardware or Firmware.

**Comment by ashimokawa** [comment]
@haecker-felix 
Thanks really strange, as it works here with FW 3.8-beta9 on OG Pebble.
It seems that you cannot really access the pbw which could also explain the problem with the pbw not being installed.

**Comment by ashimokawa** [comment]
@haecker-felix 
I assume you did not grant the Permissions to access sd card (you have to do it on Android 6.0)
Please check that!

**Comment by haecker-felix** [comment]
The app has now all permissions. 

14:55:37.046 [main] INFO  n.f.g.e.TimeChangeReceiver - Time or Timezone changed, syncing with device: 6. Dezember (6 Dec 2015 13:55:37 GMT), android.intent.action.TIME_SET
14:55:37.049 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.settime
14:55:37.049 [main] INFO  n.f.g.s.d.p.PebbleProtocol - MEZ
14:56:00.843 [main] WARN  n.f.g.d.m.MiBandFWInstallHandler - Firmware has a filename that looks like a Pebble app/firmware.
java.io.IOException: Firmware has a filename that looks like a Pebble app/firmware.
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandFWHelper.<init>(MiBandFWHelper.java:55) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandFWInstallHandler.<init>(MiBandFWInstallHandler.java:29) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandCoordinator.findInstallHandler(MiBandCoordinator.java:62) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.findInstallHandlerFor(FwAppInstallerActivity.java:150) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.onCreate(FwAppInstallerActivity.java:133) ~[na:0.0]
	at android.app.Activity.performCreate(Activity.java:6237) ~[na:0.0]
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) ~[na:0.0]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) ~[na:0.0]
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) ~[na:0.0]
	at android.app.ActivityThread.-wrap11(ActivityThread.java) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5417) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) ~[na:0.0]
14:56:00.875 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
14:56:00.903 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
14:56:00.913 [main] INFO  n.f.g.d.p.PBWReader - got icon id from pebble-app.bin: 4
14:56:00.913 [main] INFO  n.f.g.d.p.PBWReader - got flags from pebble-app.bin: 1
14:56:00.916 [main] INFO  n.f.g.d.p.PBWReader - found file to install: app_resources.pbpack
14:56:00.917 [main] INFO  n.f.g.d.p.PBWReader - found file to install: pebble-app.bin
14:56:11.997 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_appinfo
14:56:12.387 [Thread-75] INFO  n.f.g.s.d.p.PebbleIoThread - unhandled message to endpoint 0 (3 bytes)
14:56:17.120 [main] WARN  n.f.g.d.m.MiBandFWInstallHandler - Firmware has a filename that looks like a Pebble app/firmware.
java.io.IOException: Firmware has a filename that looks like a Pebble app/firmware.
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandFWHelper.<init>(MiBandFWHelper.java:55) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandFWInstallHandler.<init>(MiBandFWInstallHandler.java:29) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.devices.miband.MiBandCoordinator.findInstallHandler(MiBandCoordinator.java:62) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.findInstallHandlerFor(FwAppInstallerActivity.java:150) ~[na:0.0]
	at nodomain.freeyourgadget.gadgetbridge.activities.FwAppInstallerActivity.onCreate(FwAppInstallerActivity.java:133) ~[na:0.0]
	at android.app.Activity.performCreate(Activity.java:6237) ~[na:0.0]
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) ~[na:0.0]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) ~[na:0.0]
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) ~[na:0.0]
	at android.app.ActivityThread.-wrap11(ActivityThread.java) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5417) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) ~[na:0.0]
14:56:17.126 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
14:56:17.166 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
14:56:17.176 [main] INFO  n.f.g.d.p.PBWReader - got icon id from pebble-app.bin: 1
14:56:17.179 [main] INFO  n.f.g.d.p.PBWReader - got flags from pebble-app.bin: 1
14:56:17.180 [main] INFO  n.f.g.d.p.PBWReader - found file to install: app_resources.pbpack
14:56:17.180 [main] INFO  n.f.g.d.p.PBWReader - found file to install: pebble-app.bin

**Comment by ashimokawa** [comment]
Looks good judging from the log. Please install the pbw again and then switch to it using your watch or the app manager

**Comment by haecker-felix** [comment]
I cant install any pbz/pbw with 0.6.7. These watchfaces should work or?

http://pebble-static.s3.amazonaws.com/watchfaces/index.html

With 0.6.6 was this possible (but crashes when the pebble tried to load it).

**Comment by haecker-felix** [comment]
whatever what for a watchface i open (Firmware too!), it says 

pbw/pbz is broken or incompapatible with your Hardware or Firmware.

**Comment by ashimokawa** [comment]
@haecker-felix 
These are for Firmware 1.x!
They are not supposed to work.

**Comment by haecker-felix** [comment]
Oh sorry. Can you send me a link to a valid watchface to test?

**Comment by ashimokawa** [comment]
Bad example but this is the pebble app for Pebble Dialer. Not a watchface but enough to test Gadgetbridge.
https://dl.dropboxusercontent.com/u/6999250/dialer/PebbleDialer.pbw

Also strange that pbz do not work for you anymore, if they are for v1_5 they should work!
(Just tested)

**Comment by haecker-felix** [comment]
Okay
https://github.com/Freeyourgadget/Gadgetbridge/issues/183
