### ISSUE TITLE
Mi Band 1A: notifications don't work at all with firmware 5.15.7.29 and higher

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#184]
Need to find another API to invoke notifications, I'm afraid.

Until then, please use firmware 5.15.7.14.

**Comment by uwehermann** [comment]
Hm, this should probably be re-tested in more detail. I'm running FW 5.15.11.19 on an MI1A (HW: 1A) here, and I am able to get the device to vibrate using the debug / notification buttons. I'm not entirely sure whether it vibrates *correctly* (needs some more testing), but it certainly does vibrate.

Have there been any fixes for this in the meantime maybe?

**Comment by cpfeiffer** [comment]
This might very well be possible. I think newer versions do not support the fine-grained API for controlling the vibration motor anymore. They support the standardized "immediate alert service" API instead, which just has three different kinds of notification levels.

So I guess I'll close this for now, thanks a lot for your feedback!
