### ISSUE TITLE
Connection lost with Pebble Classic over night and reconnection failed

### ISSUE THREAD

**Issue by testman86** [Freeyourgadget/Gadgetbridge#186]
This is the second time that Gadgetbridge is loosing connection to Pebble Classic and is not able to reconnect automatically.

First time was when I was driving with my car (but just got to now it after 2 hours) and I remember I needed a reboot afterwards to get it working (initialized) again (but failed to save log). (And it was with an older version of Gadgetbride 0.6.6)

This time my mobile and pebble where lying on desk next to each other over night (the other nights in same constellation connection stayed initialized). And this time I am on latest version available on F-Droid 0.6.8. But this time just tapping one ore two times on Pebble Classic in Gadgetbridge were enough to get connection working again, so there was a little change in between but not complete solving it. But seems that Gadgetbridge is at least now manually able to reconnect after such a "fail" and no reboot needed anymore.

Here is the log which hopefully might help you 

[gadgetbridge-1.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/56490/gadgetbridge-1.txt)

**Comment by ashimokawa** [comment]
Strange.
Judging from your logs the pebble switches off bluetooth on purpose. Before the socket gets closed, it announces the disconnect via a message to endpoint 18 (system message). I do not decode these yet but it is safe to assume that is is the "I will switch off bluetooth" message. 

<pre>
09:36:30.212 [Thread-58] INFO  n.f.g.s.d.p.PebbleIoThread - unhandled message to endpoint 18 (2 bytes)
09:36:35.137 [Thread-58] INFO  n.f.g.s.d.p.PebbleIoThread - bt socket closed, read return: -1
</pre>

Another strange thing to note: It does this after you you do phone calls. Can you confirm that?
Also what is your firmware version? I assume it is 2.9.1, if not, please update to that version.

**Comment by testman86** [comment]
Hmm, the phone and Pebble Classic were both just laying on my desk (20-40cm
apart from each other) while I was sleeping, so no moving, no (active nor
passive/missed) phone call or anything in between. Also no missed call in the
morning.
Could just be that I got some e-mails, but this also never had any influence on
the connection behaviour of Gadgetbridge (while wearing it or just over night
laying on my desk).

Last time was also "randomly" without phone call before (but I was driving my
car 2 weeks ago). If I am doing phone calls they get announced on the Pebble,
but afterwards Pebble stays initialized in Gadgetbridge. So doing phone calls or
getting phone calls have never made issues/problems.

And yep, I am on latest 2.9.1 firmware.

Maybe there is a "alive" package from phone or Gadgetbridge missing while
bluetooth connection is active and therefore Pebble closes the connection? I
mean I was able by tapping on Pebble (in Gadgetbridge) one or two times to get
connection initialized again. Therefore I assume that bluetooth was still
working and Pebble is recognized as Pebble and not as Mi-Band or anything else
like versions before.
What could be, I also had the problem, that if coming home while taking phone
with me and Pebble stays at home, that I had to switch bluetooth on and off to
connect to Pebble again. 
(But I do not remember if I first tested just tapping on Pebble in Gadgetbridge
or not, but automatically reconnecting was also not working. But from this
behaviour I also missed to save a log. I will check in the afternoon after
coming home again how/if phone will connect to Pebble and will paste the logs.)

**Comment by ashimokawa** [comment]
There a lot more disconnects in your logs, sometimes with successful reconnects.
The ones where the pebble shuts down the connection on purpose always have call state changes just before doing that.

Some more questions:
Do you have the official app installed?
Which phone are you using (maybe you bluetooth is just extremely unstable, I had this also with my old phone and I needed to patch the kernel to work around it :disappointed: )

**Comment by ashimokawa** [comment]
@testman86 
Could you also try to play music once with your default player? ;)
Probably that does not improve the situation but judging from you logs we send a music info with artist,track,album all set to null. Don't think this will mess up pebble protocol states, but who knows...

**Comment by testman86** [comment]
Hmmm, this two/three times (last night and driving car two weeks ago and one
time not able to reconnect after coming home) were the only ones I recognized
that the connection was closed/lost/disconnected. Every other "interupts" you
can see in the log were not recognizeable as a user.
Hmm, as I said, I see incoming calls on my pebble and while calling that I have
a phone call active, and after end of the call just time of day is shown again.

I have not the offical app installed on the device (phone) Pebble is connected
to. Just on my tablet, but the bluetooth-connection-settings are deleted in
pebble and tablet (was just for updating firmware and play around the first
days).

I am using Z1 compact with CM12.1 without GAPPS installed. (And yeah I avoided
to switch to Android 6.0 to have a "stable" phone, also for testing Pebble ^^)

**Comment by testman86** [comment]
Maybe I have to add I use the "official" CM12.1 from Cyanogenmod, not a custom
build or anything :)

**Comment by ashimokawa** [comment]
Okay, then we can rule out RAM problems then. Can you still try to at least once select some music from the CM Music app?

Also a good test would be to use BlueChat from f-droid to connect your tablet to your phone with an RFCOMM connection (same as we use) and see if the connection drops there also. I did that on my old phone and it turned out it was a bluetooth problem, not a Gadgetbridge problem.

And... could you please not quote everything every time when replying per e-mail? It all lands in the Github issue tracker (cleaned up your commets).

**Comment by testman86** [comment]
While you were writing I was testing MusicApp :)

So here is the log. First part was not working cause "wrong" music app was selected, but after selecting "correct" app I was able to pause/resume, skip and control volume with screen on/off of the phone.


[gadgetbridge-2.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/56759/gadgetbridge-2.txt)


(And sorry for quoting too much (was just replying to e-mails I got), I was used to that from the DebianBugTracker cause there everything just runs with quoting and responding to emails (and yeah, I like this "clean" interface here on github more for reporting bugs as well :) )

**Comment by ashimokawa** [comment]
The music idea was just to set the metadata (track, album, artist) one to prevent the "null"s inside the protocol.

But, unfortunately my guess is that there are bluetooth problems with your phone or cm 12.1 for your phone. Mine on 12.1 is stable and has always been. No connection loss at all (only if I move faaar away).
 
Can you connect your pebble with your tablet (using Gadgetbridge) and see if it loses connection over night? You can also set the reconnect attempts to 0 in Settings, and then see if it lasts for the night.
My guess is, unfortunately, that it will be stable on other devices.

**Comment by testman86** [comment]
Mine has also stable connection normally and I can move inside the house and even if I am two floors below where my mobil is on my desk I have connection with my pebble. I was not able to loose connection normally inside the whole house. Or do you mean all the little connection losts before phone calls etc.?

And this was the first time that I loose connection over night, as I said, before it was running flawless. And all settings are more or less default.
I will check this night but I think it should work again, cause no clue why and how to reproduce this behaviour.

And my tablet has a custom cm12.1 install and there I know having bluetooth issues depending on each build sometimes.

**Comment by ashimokawa** [comment]
Well, judging from your logs it is not stable at all, just search for -1
These should not happen at all...
If you set reconnect attempts to 0 you can easily notice whether a connection was lost. And compare that with another device...

**Comment by testman86** [comment]
I got your point, stable for the user cause reconnecting is working most of the times, but not technically stable... (This is also what I meant in last posting)
I will test further and maybe another CM12.1 Update for my Z1 compact will help.

Thanks anyway for you fast replays and usefull hints and tipps!

Or do you have any idea how I could modify bluetooth settings or anything else to improve the situation?

**Comment by ashimokawa** [comment]
Sorry I dont know how you can improve the bluetooth situation.
In some forums people wrote they have problems when wifi and bt is on at the same time with the z1c. Can you rule that out?
Also it might be wise to check the whole logcat (not just gadgetbridge) to see if bluetooth was turned off on the phone due to some system error.
It smells fishy that you needed to reboot your phone before. 
What I also noticed is the fact that during the failed re-connection attempts, all but the first one failed immediately (normally they block for about 5-10 seconds each, when the pebble is not reachable or turned off). That also hints at bluetooth being completely broken for a moment.

**Comment by IzzySoft** [comment]
Closing this as stale.
