### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by official-jkim** [Freeyourgadget/Gadgetbridge#190]
New app icon with Material Design.

![icongb](https://cloud.githubusercontent.com/assets/12594372/11928467/11fdb986-a817-11e5-998c-94386f52a617.png)

Download ![iconGB.svg.png](https://cloud.githubusercontent.com/assets/12594372/11928470/211ad552-a817-11e5-98b9-385bef8cd413.png) and change its extension into '.svg' to download an original SVG file.

**Released under CC BY-NC-SA.**

**Comment by danielegobbetti** [comment]
Hi! I like the style very much! Do you think it's possible to change the wearable with something less pebble-time-steel like?
At the moment Gadgetbridge supports the whole set of pebbles and miband, and we hope to add further devices with help of further devs :)

Thanks for your help!

**Comment by ashimokawa** [comment]
I also like it!
But just like @danielegobbetti I think it is too pebble centric.
Maybe it would be enough to make it a bit shaped like in the original icon, which looks like a smart band with display. My intention was to create something between Pebble and Mi Band.
But then again, it might end up like a Garmin vivosmart.

@cpfeiffer 
Any opinion?

**Comment by cpfeiffer** [comment]
Looks awesome! Maybe could be a little less watch-like, but I really like the style already.

**Comment by halcyonest** [comment]
There you go.

![icongb2](https://cloud.githubusercontent.com/assets/12594372/11975554/9ed449aa-a9b2-11e5-8dd1-f9d34582482c.png)

**Comment by ashimokawa** [comment]
Cool, thanks!
If @cpfeiffer and @danielegobbetti agree, I will merge this today

**Comment by danielegobbetti** [comment]
+1

and thanks a lot!

**Comment by ashimokawa** [comment]
@halcyonest 
For completeness, could you also supply the svg?
I used the png to scale it down for now.

**Comment by cpfeiffer** [comment]
@official-jkim do you still have the svg and could provide it? Otherwise we should close this issue.

**Comment by official-jkim** [comment]
Here is a SVG file.

![iconGB_2.svg.png](https://cloud.githubusercontent.com/assets/12594372/14062741/a39483bc-f3ed-11e5-86e0-14dcb8948f34.png)
