### ISSUE TITLE
allow "universal" manual configuration of pebble watch apps

### ISSUE THREAD

**Issue by danielegobbetti** [Freeyourgadget/Gadgetbridge#191]
For each app in our cache, expose the configuration options exposed in the "appKeys" object inside appinfo.json and create an activity to let the user enter custom values.

I believe a listview could suffice, for each key the user should enter:
- the value type (integer, boolean, string)
- the actual value

**Comment by ashimokawa** [comment]
Good idea, and sounds feasible.

**Comment by danielegobbetti** [comment]
Closing this in favor of #235
