### ISSUE TITLE
Mi Band 1A: Alarms not working

### ISSUE THREAD

**Issue by wincak** [Freeyourgadget/Gadgetbridge#192]
Alarms simply don't seem to work at all on my Mi Band. It's possible to configure them, send to device (with "Alarms sent to device!" shown), but the Mi Band doesn't do anything at the specified time. Is this a known issue?

Mi Band version: HW: 1A FW: 5.15.7.2
Gadgetbridge version: 23.12.2015 (commit: 9f60bf3561de6d0580ff8e577537d39d7a909905)
System: Cyanogenmod 12.1, Nvidia Shield (12.1-20151121)

[gadgetbridge-set-alarm-log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/73168/gadgetbridge-set-alarm-log.txt)

**Comment by cpfeiffer** [comment]
Yes, this is a known issue (bad firmware), see here: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-information

Use 5.15.7.14, this one works.
