### ISSUE TITLE
Reconnection isn't immediately after disconnection - mi band

### ISSUE THREAD

**Issue by zdybo** [Freeyourgadget/Gadgetbridge#193]
It is problem, because in this time (when mi band is disconnected) i'm not getting notifications.
Some times mi band is staying at connected status - not initialized, so it isn't work.

**Comment by cpfeiffer** [comment]
Right, I noticed this as well. We need some kind of timeout for when a connection does not progress any further.

There is a single flag that controls whether lowlevel BLE reconnection is attempted, but setting it to true (as we did in previous versions) leads to connection problems with certain devices. I'm considering making this an option.

**Comment by keverets** [comment]
Part of the problem is that GadgetBridge is showing the status as "Connected", but it's really not connected. An attempt to synchronize with the band shows a toast of "Not Connected". The user doesn't even know that they need to try to reconnect (and the only way I've been able to do so is to "Exit" the app and then start it again).

I've come to see "Connected" as a misnomer, and only a state of "Initialized" shows that it's actually connected.

**Comment by cpfeiffer** [comment]
Yes, "connected" would be better for the user to understand. We use the term "connected" for the lowlevel bluetooth connection being established and "initialized" when the actual application level connection is established (i.e. user info and time sent to the device, etc.).

If you have a better naming for the two states, please tell us :-)

**Comment by cpfeiffer** [comment]
Oh, and the problem with the band staying in "connected" state is improved a lot with current git, to be released today.

It's probably not fixed 100%, because I still experienced it once, but my connection to the band is much more reliable, now.

**Comment by zdybo** [comment]
Oh, thats good. I can't wait ;)
I have suggestion, in polish translation if band is connected and working status could be "Połączony" - connected, now it is "Rozpoczęty" in polish mean -initiated/begun/started.

**Comment by cpfeiffer** [comment]
The connection-issue should now really be fixed for 0.9.1.

**Comment by cpfeiffer** [comment]
I'll open a separate ticket for the connection status names.

**Comment by sumproxy** [comment]
I'm using GB 0.19.2, but I have a reconnect issue when the device goes out of range for a while. [Here](https://gist.github.com/sumproxy/40f50c33b6e019911bbccb05deb1ed83)'s the log file.

**Comment by cpfeiffer** [comment]
@sumproxy The connection should be re-established as soon as notification is received (making the band vibrate). A constant connection is actually not needed at all, exception for maybe the battery notification. But the band has that as well.

Is there any actual problem you experience?

**Comment by cpfeiffer** [comment]
Oh, now I understand -- you're using a custom version from #379. Well, even in that case, the connection should be re-established whenever the next measurement is requested.

**Comment by cpfeiffer** [comment]
From looking at your log, it seems that the implementation does or did an explicit connect, which performs a disconnect first.

Can you tell me a time at which a normal disconnect happened (because you were away from the phone) and where the reconnect did not work?

**Comment by sumproxy** [comment]
@cpfeiffer how about I reproduce the error again (move mi band out of phone's bluetooth range and back) and send you the logs (to make observation period as short as possible)? If so, are there any specific debug messages you want to add to logging?

**Comment by cpfeiffer** [comment]
Yes, please, and please add it to #379 instead of this one (which is closed for over a year). I think there's enough logging in there, so you can start right away.
