### ISSUE TITLE
Don't kill the database that easy

### ISSUE THREAD

**Issue by chrissssss** [Freeyourgadget/Gadgetbridge#197]
It took me one button click overwriting my current database with an 1 month old export. Sadly one month of data is away :-(

Please add some safety switch for importing data in the debug dialog. Please add a dialog like "Do you really want to import your months old database overwriting your current data?" or something like that. 
Or automatically do a backup before overwriting the database.

**Comment by cpfeiffer** [comment]
Good point, we should really add a confirmation dialog *and* make a backup. I'm sorry that you lost your data.

**Comment by cpfeiffer** [comment]
I think that should do it for now. The import and export functionality in the Debug activity is not the intended user interface for activity sharing anyway.

**Comment by cpfeiffer** [comment]
(IOW, we're going to have something better in the future).
