### ISSUE TITLE
Pebble: Support for App specific settings

### ISSUE THREAD

**Issue by Chroonos** [Freeyourgadget/Gadgetbridge#199]
Gadgetbridge currently does not support the settings pages for individual Pebble (Time) WatchApps.
This is the only thing that keeps me away from using Gadgetbridge right now.

**Comment by danielegobbetti** [comment]
the original app/watchface setting pages are unfortunately not an option for gadgetbridge as they are html pages on a variety of servers, and we don't have Internet access permission.

see #191 for a planned workaround.
