### ISSUE TITLE
repeating notfications on low phone battery

### ISSUE THREAD

**Issue by pilpul** [Freeyourgadget/Gadgetbridge#20]
I really like gadgetbridge, works great. There's only one thing that annoys me. As soon as the battery of my phone get's below 15% my pebble vibrates every 10 seconds. Whether or not i dismiss the notification (which will come back) it keeps vibrating.
Any ideas except disabling generic notifications?

**Comment by ashimokawa** [comment]
Thanks, I will filter these out completely for now.
This will be in 0.2.0 which is due this week.

**Comment by ashimokawa** [comment]
Please let me know if we filter out too much now (other non battery notifications that you need but are ignored now)
