### ISSUE TITLE
waiting for reconnect does not work with pebble time

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#200]
when I set reconnect attemps to 0 the phone stays at waiting for reconnect and the connection is never done

pebble time & android 6

**Comment by roidelapluie** [comment]
logs: http://paste.pound-python.org/show/DMnQu16NIeShqYMwzYBK/

**Comment by danielegobbetti** [comment]
well it works for me, but only after a fair amount of time (a couple of minutes).

Could you try putting the pebble in airplane mode (gb should show "waiting for reconnect") then wait at least 5 minutes before turning bt on again on the pebble?

**Comment by wngr** [comment]
I'm experiencing the same issue. The reconnect does never happen.

I tried your instructions, but GadgetBridge won't reconnect - see http://paste.pound-python.org/show/nKywJLzJko3k9H3iY7yE/

**Comment by ashimokawa** [comment]
For me it also works after waiting for >5 minutes.
Also if I leave it in "waiting for reconnect" state overnight.

**Comment by roidelapluie** [comment]
I confirm that it does NOT work for me.

**Comment by cutec-chris** [comment]
For me it also not work. Would be nice if you could restore the old Behavour (0.6.x)

**Comment by ashimokawa** [comment]
There is absolutely no downside to the new behavior even if it does not work.
You can still set the reconnect attempts to whatever value you like and after these reconnection attempts all failed, Gadgetbridge waits for incoming connections.
In this state you can still tap on the device to connect.
Reverting would just display not connected instead waiting for reconnect.

**Comment by roidelapluie** [comment]
No, the old behaviour does not work either for me...

**Comment by roidelapluie** [comment]
I will double check that later

**Comment by ashimokawa** [comment]
You seem right, I will fix that later today

**Comment by roidelapluie** [comment]
Thanks :-)

**Comment by ashimokawa** [comment]
Fixed in git, will be released today or tomorrow

**Comment by roidelapluie** [comment]
Thanks, and congratz to all the team for your 1000th commit
