### ISSUE TITLE
Activity data sync problems with Mi Band 1S

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#205]
From @zimonish's logfile https://github.com/Freeyourgadget/Gadgetbridge/files/76599/gadgetbridge.log.zip of #178 

The sync problems stem from a NullPointerException, which occurs because of this:
```
21:14:01.523 [Binder_2] DEBUG n.f.g.s.d.m.o.FetchActivityOperation - activity data: length: 20, remaining bytes: 23
21:14:01.540 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 0000ff07-0000-1000-8000-00805f9b34fb value:  0x5 0x0 0x0 0xff 0x5 0x0 0x0 0x44 0x5 0x0 0x0 0xff 0x5 0x0 0x0 0x43 0x5 0x0 0x0 0xff
21:14:01.540 [Binder_2] DEBUG n.f.g.s.d.m.o.FetchActivityOperation - activity data: length: 20, remaining bytes: 3
21:14:02.117 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 0000ff07-0000-1000-8000-00805f9b34fb value:  0x5 0x0 0x0 0x42 0x5 0x0 0x0 0xff 0x5 0x0 0x0 0x43 0x5 0x0 0x0 0xff 0x5 0x0 0x0 0x42
21:14:02.119 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - about to add: 21:14:02: Transaction task: send stop sync data with 1 actions
21:14:02.130 [main] ERROR n.f.g.u.GB - error buffering activity data: remaining bytes: 3, received: 20
```

Somehow we get more data than was previously announced, or we get bogus data or something is just wrong. The NPEs are just follow up errors because we do not expect to get notifications and data after that.

**Comment by zimonish** [comment]
When Mi1S succeeds to sync something, seems like every other data point is bogus. See  the images in the new attached zip-file. There is also more recent gadgetbridge.log in the zip-file

BTW, a good price for  Mi1S (if someone needs for testing) can be get from there <19 €/$
http://www.cigabuy.com/Xiaomi-MiBand-1S-Heart-Rate-Sleep-Monitor-Call-Reminder-Pedometer-IP67-p-8286.html?sk=69781948ME
I bought mine from there.

[gadgetbridge_log_and_images.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/80464/gadgetbridge_log_and_images.zip)

**Comment by cpfeiffer** [comment]
Thanks for the log and screenshots -- maybe the data format indeed has changed and we need to adjust the code.
