### ISSUE TITLE
show runnerup track-data on pebble

### ISSUE THREAD

**Issue by kas70** [Freeyourgadget/Gadgetbridge#208]
https://github.com/jonasoreland/runnerup/

**Comment by danielegobbetti** [comment]
related issue on the other project:
https://github.com/jonasoreland/runnerup/issues/98

**Comment by danielegobbetti** [comment]
After looking at the code of the mentioned app, the issue is not app specific, but rather the same as already reported on #130. Hence I'm closing this issue.
