### ISSUE TITLE
How to get apps/watchfaces/firmware to install?

### ISSUE THREAD

**Issue by kas70** [Freeyourgadget/Gadgetbridge#209]

**Comment by ashimokawa** [comment]
Use a filemanager, select a .pbw vor .pbz file and choose to open with Gadgetbridge FW/App installer.

**Comment by kas70** [comment]
Is there any repository for .pbw and .pbz files?

**Comment by danielegobbetti** [comment]
not that we are aware of, further, it's off topic. I'm closing the issue.
