### ISSUE TITLE
MiBand1A Plug

### ISSUE THREAD

**Issue by rellai** [Freeyourgadget/Gadgetbridge#210]
MiBand1A plug and has synchronized 1 times. Next, may no longer be connected.
She finds, connects, but no progress during initialization. correctly identifies version of the device and software version 5.15.11.20
Reinstalling the application and rebooting did not help
LOG:::::

10:02:22.122 [main] INFO  n.f.g.GBApplication - Gadgetbridge version: 0.7.1
10:02:22.255 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being created
10:02:22.256 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
10:02:22.266 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
10:02:23.742 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
10:02:23.757 [main] INFO  n.f.g.s.b.BtLEQueue - Attempting to connect to MI1A
10:02:23.757 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Queue Dispatch Thread started.
10:02:23.776 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
10:02:24.939 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - connection state change, newState: 2 (success)
10:02:24.940 [Binder_3] INFO  n.f.g.s.b.BtLEQueue - Connected to GATT server.
10:02:24.943 [Binder_3] INFO  n.f.g.s.b.BtLEQueue - Attempting to start service discovery:true
10:02:24.947 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
10:02:25.904 [Binder_1] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to pair MI device...
10:02:25.905 [Binder_1] DEBUG n.f.g.s.d.m.MiBandSupport - Requesting Device Info!
10:02:25.910 [Binder_1] DEBUG n.f.g.s.d.m.MiBandSupport - Writing User Info!
10:02:25.911 [Binder_1] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to set wear location...
10:02:25.912 [Binder_1] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to set Fitness Goal...
10:02:25.951 [Binder_1] INFO  n.f.g.s.d.m.MiBandSupport - Sending current time to Mi Band: 20 января (20 Jan 2016 07:02:25 GMT)
10:02:25.952 [Binder_1] DEBUG n.f.g.s.d.m.MiBandSupport - Requesting Battery Info!
10:02:25.953 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - about to add: 10:02:25: Transaction task: Initializing device with 15 actions
10:02:25.961 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 20 января, 10:02: SetDeviceStateAction
10:02:25.962 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 20 января, 10:02: WriteAction on characteristic: 0000ff0f-0000-1000-8000-00805f9b34fb
10:02:25.966 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
10:02:26.044 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 0000ff0f-0000-1000-8000-00805f9b34fb (success)
10:02:26.045 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Successfully paired  MI device
10:02:26.046 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 20 января, 10:02: ReadAction on characteristic: 0000ff01-0000-1000-8000-00805f9b34fb
10:02:26.145 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic read: 0000ff01-0000-1000-8000-00805f9b34fb (success)
10:02:26.148 [Binder_1] WARN  n.f.g.s.d.m.MiBandSupport - Device info: DeviceInfo{deviceId='88DCC94804000044D', profileVersion=33666668, fwVersion=84871956, hwVersion=8, feature=5, appearance=0}
10:02:26.149 [Binder_1] INFO  n.f.g.s.AbstractDeviceSupport - Got event for VERSION_INFO
10:02:26.153 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 20 января, 10:02: ReadAction on characteristic: 00002a00-0000-1000-8000-00805f9b34fb
10:02:26.161 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
10:02:26.295 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - characteristic read: 00002a00-0000-1000-8000-00805f9b34fb (success)
10:02:26.297 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: 20 января, 10:02:  on characteristic: 0000ff04-0000-1000-8000-00805f9b34fb
10:02:26.305 [GadgetBridge GATT Dispatcher] ERROR n.f.g.s.b.BtLEQueue - Queue Dispatch Thread died: src.length=10 srcPos=0 dst.length=20 dstPos=11 length=10
java.lang.ArrayIndexOutOfBoundsException: src.length=10 srcPos=0 dst.length=20 dstPos=11 length=10
at java.lang.System.arraycopy(Native Method) ~[na:0.0]
at nodomain.freeyourgadget.gadgetbridge.devices.miband.UserInfo.getData(UserInfo.java:94) ~[na:0.0]
at nodomain.freeyourgadget.gadgetbridge.service.devices.miband.MiBandSupport$1.run(MiBandSupport.java:212) ~[na:0.0]
at nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue$1.run(BtLEQueue.java:92) ~[na:0.0]
10:02:26.309 [GadgetBridge GATT Dispatcher] INFO  n.f.g.s.b.BtLEQueue - Queue Dispatch Thread terminated.

**Comment by rellai** [comment]
After connect with miband notify v2 --- GadgetBridge correctly connect.....

**Comment by rellai** [comment]
afert time error back %(

**Comment by rellai** [comment]
randomly disconnects..... then very long connects.... I have to press disconnect to connect.... :(

**Comment by rellai** [comment]
There was a problem with the fact that the active compounds with mi band - did not work bluetooth in the car (not transmitted sound). miband deleted from the paired devices. Again, I can no longer connect to it through the application ....

**Comment by danielegobbetti** [comment]
I'm sorry I can't follow you, can you please rephrase?

**Comment by rellai** [comment]
after some time GadGetBrisge disconnected from MI, and when he tries to reconnect with Mi, sometimes infinitely hanging in the status "initialization".

Click to manually disconnected, then connect, then everything turns out.
I think the problem is related to the log, I laid out above

**Comment by odwk** [comment]
Having a similar issue. MiBand1A, firmware version 5.15.11.20. Official app and some others connect and work, but Gadgetbridge doesn't even find the device. After entering manually the address, the app connects to the device but stays stuck in 'initialization'. Never managed to sync successfully.

**Comment by cpfeiffer** [comment]
Can you please try version 0.8.0 and see if it improves the situation?

**Comment by cpfeiffer** [comment]
Closing, please reopen if you still have problems.
