### ISSUE TITLE
Sound transmission does not work with the active compound c gatgetbridge

### ISSUE THREAD

**Issue by rellai** [Freeyourgadget/Gadgetbridge#212]
Add an optional trip by mi band, when connected to other devices (eg a headset). and automatically connect after being disconnected from the headset

**Comment by danielegobbetti** [comment]
I'm sorry I can't follow you, can you please rephrase?

**Comment by cpfeiffer** [comment]
Do you mean you have trouble with other bluetooth connections while Gadgetbridge is connected to your Mi Band? So you'd like to automatically connect and disconnect the Mi Band when a headset is active?

**Comment by rellai** [comment]
Yes, OR whether it is possible to add to the MI "Paired devices"?

When GadGet Bridge connects to the Mi Band - is added to the device in the "Paired devices".
Mi band Notify v2 when pairing - not add to the "Paired devices"
Therefore, Mi band Notify v2 - no problem
And GadGetBridge the active compound with MI --- the sound is not transmitted in the car via bluetooth
