### ISSUE TITLE
Support Android 6 runtime permissions

### ISSUE THREAD

**Issue by chrisperelstein** [Freeyourgadget/Gadgetbridge#219]
Every time I get a new email, a notification on my pebble pops up like this:
![screenshot_20160201-094714](https://cloud.githubusercontent.com/assets/1852243/12738395/4aac7f5a-c92e-11e5-8359-fb5c95b00480.jpg)

I've tried uninstalling and reinstalling (including after wiping data and cache for Gadgetbridge) with the same result. I have a Pebble Time paired with a Samsung Galaxy S5 running Cyanogenmod 13. Here is the log from gadgetbridge:
[gadgetbridge-log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/113357/gadgetbridge-log.txt)

**Comment by chrisperelstein** [comment]
ADB logcat from when an email comes in (hopefully containing everything relevant):
[adb-logcat.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/113371/adb-logcat.txt)

**Comment by ashimokawa** [comment]
@chrisperelstein 
Starting with Android 6 you have to grant permission manually after installation, this includes the "Read Messages" permission, which is actually a custom K9 Permission. Please turn that on through Android Settings. The fastest way is probably dragging the Gadgetbridge from the Launcher (not Homescreen) to the Info icon and then going to "Permissions".

I am 99% sure that is what is causing your problem.
And to prevent these kind of bug reports I have to implement runtime permission request dialogs ASAP. :/

**Comment by chrisperelstein** [comment]
@ashimokawa
Yep that seems to be the case. Right before going to bed, I manually granted the permission through adb with ```adb shell pm grant nodomain.freeyourgadget.gadgetbridge com.fsck.k9.permission.READ_MESSAGES``` and that worked.

**Comment by chrisperelstein** [comment]
I haven't done any Android development yet, but this looks like it may be useful: matejdro/PebbleDialer-Android@ac674622ea1dd83413d6d2825d457c17d11a1dfd. I may give adapting that a shot if no one beats me to it.

**Comment by ashimokawa** [comment]
@chrisperelstein 
Yes, many projects that switched to API 23 implementing runtime permission support, we didn't unfortunately.
If you want to implement it, then please go ahead. But if it is not done by the weekend, I might do it, as I want to have that out fast (to prevent further bug report - this one was not the first)

**Comment by petre2dor** [comment]
I was able to overcome this by enabling read-email permission from app settings. CM13
