### ISSUE TITLE
Gadgetbridge does not announce its pebble health support

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#223]
![screenshot_20160208-063722](https://cloud.githubusercontent.com/assets/291750/12879103/d23ffa50-ce2e-11e5-90a1-8b43a6b1cf17.png)

I know this is experimental in gadgetbridge, but it looks like we do not announce that we support pebble health

**Comment by roidelapluie** [comment]
Closed as it is gone with the 3.9 firmware

**Comment by ashimokawa** [comment]
@roidelapluie 
AFAIK this has nothing to do with 3.8/3.9
You will see this message if Health has not been enabled.
You can enable it via Gadgetbridge in the App Manager. Long press on Health, activate.

**Comment by danielegobbetti** [comment]
What @ashimokawa said. Before officially supporting health we should add some info on the wiki.
