### ISSUE TITLE
Marshmallow requires location permissions for BTLE scanning

### ISSUE THREAD

**Issue by martykan** [Freeyourgadget/Gadgetbridge#224]
The app won't discover my MiBand.
```
nodomain.freeyourgadget.gadgetbridge W/Binder: Caught a RuntimeException from the binder stub implementation.
     java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
          at android.os.Parcel.readException(Parcel.java:1620)
          at android.os.Parcel.readException(Parcel.java:1573)
          at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:772)
          at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onClientRegistered(BluetoothLeScanner.java:324)
          at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:56)
          at android.os.Binder.execTransact(Binder.java:453)
```

**Comment by cpfeiffer** [comment]
Did you switch to another app, so that Gadgetbridge went into background when this happened?

AFAIU, only background scanning needs location permissions. Since we always do this in the foreground, I thought we would be safe.

**Comment by martykan** [comment]
No, it was in foreground and with screen on. I tried multiple times.

I added those permissions to the manifest (+ enabled location in system settings to work around the new dialogs that are required) and it found my MiBand pretty much immediately.

**Comment by martykan** [comment]
Also:

http://stackoverflow.com/questions/33043582/bluetooth-low-energy-startscan-on-android-6-0-does-not-find-devices/33045489

**Comment by Technowix** [comment]
Hey @martykan , I need to connect my Pebble Time on my marshmallow, but I can't find it ! :( could you attach your apk for trying ?

**Comment by ashimokawa** [comment]
You can pair your pebble though android settings.
It should then show up in Gadgetbridge.
If not check if you gave Gadgetbridge all the permissions it wants (especially BT related)

**Comment by Technowix** [comment]
Thank for the reply @ashimokawa !
My Pebble Time show up in my bluetooth pairing page (Both LE and noLE) but when I try to pair it, the pebble vibrate and ask if I want to connect, I press yes but after than.... nothing, and timeout :/
It was working pretty well with Pebble's offical app (for pairing trough the app) but now I try to pair with ONLY gadgetbridge (I have reset the Pebble Time) but the watch don't show up when I'm in gadgetbridge's "discover new devices" ^^"
Sorry for my strange english, that not my native lang ><

**Comment by ashimokawa** [comment]
@Technowix 
If you reset your Pebble you also have to unpair the pebble on the android side, then re-pair, preferably though the Android Bluetooth settings, not Gadgetbridge.

Also, NEVER pair the Pebble LE, it is not used by Android (neither Gadgetbridge nor the official App)
What you describe really smells like an LE pairing attempt (timeout).

**Comment by Technowix** [comment]
Yeah ! It worked ! Thank @ashimokawa ! :)
But after that, in the gadgetbridge interface, I "can" connect to the watch but can't "install" it... (the watch keep telling me to install the pebble app, even after pairing... :/ )

**Comment by ashimokawa** [comment]
@Technowix 
Pebble uses LE for iOS Notifications only. We do not know the Protocol.
What you are seeing on your Pebble is the recovery firmware. You need to install a real firmware (you can do this though Gadgetbridge).

https://pebblefw.s3.amazonaws.com/pebble/snowy_dvt/release-v3.8/pbz/Pebble-3.9.2-snowy_dvt.pbz

Open with Gadgetbridge FW Installer.
If you download this and open though a file manager make sure that you granted the permissions for Gadgetbridge. Please do not open a bug report if it fails but refer to #219

**Comment by danielegobbetti** [comment]
@martykan  can you please check if the [BLE example app by google](https://github.com/googlesamples/android-BluetoothLeGatt) is able to discover the miband on android 6?

**Comment by martykan** [comment]
@danielegobbetti Doesn't work, logcat throws the same error.

**Comment by danielegobbetti** [comment]
For reference:

https://code.google.com/p/android/issues/detail?id=189090&q=ble%20android%206.0&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars

It looks like we should be careful, otherwise we would need the location **service** running as well, beside the coarse location permission.

I still believe we should try to work around this in some other way.

**Comment by ashimokawa** [comment]
I disabled the scanning activity on Android >= 6.0 in git, since it will never work without the permission.

**Comment by zdybo** [comment]
Hi, a have the same problem. Gadgetbridge can't see miband in app. When app moved me to bluetooth settings and i taped to MI1A i gave something like that: Phone cannot communicate with MI1A. I have S6 with Marshmallow. Before i wiped my phone - week after update to 6.0, gadgetbridge worked fine. After wipe i have this problem. What i have to do?

**Comment by danielegobbetti** [comment]
Permission was added (7ef005f6a38e85a6810c9414c828664dfa6c29a5) and the BLE code has much improved since. Closing.
