### ISSUE TITLE
Gadgetbridge not installing on Nexus 5 @ Marshmallow 6.0

### ISSUE THREAD

**Issue by superpsych0** [Freeyourgadget/Gadgetbridge#229]
Trying to install any of the three versions of the app from F-Droid results in "failed to install due to an unkown error" message after clicking the "Install" button after download.

Am on bog-standard 6.0 Google image, rooted, with no exotic stuff running (or even Exposed Framework for that matter, standard kernel, etc).

Hoping to flash Pebble Steel with v3.8-v1.5 firmware to get out of bootloop, but if the app ain't installing... nothing happening.

**Comment by ashimokawa** [comment]
Do you have the official app installed? If so please uninstall it. The pebble time app can coexist with Gadgetbridge but not the original one.

Since you flashed 3.8, the original official non time app is obsolete for you anyway.

**Comment by superpsych0** [comment]
Thanks for your suggestion, that worked.

Now to see about getting my Pebble Steel out of permanent recovery mode...

**Comment by ashimokawa** [comment]
Great, hope it works. If your recovery is not 3.8-prf9 you should flash a migration fw (again).

(See the wiki)
