### ISSUE TITLE
Mi Band 1A connection issue on Marshmallow

### ISSUE THREAD

**Issue by official-jkim** [Freeyourgadget/Gadgetbridge#230]
Initial pairing works, data synchronisation works, but connection process needs to be done two times.

- First try: Connecting -> Initializing -> (doesn't proceed)
- Second try: Connecting -> Initializing -> Initialized -> (everything works)

Also after disconnection, Gadgetbridge doesn't re-connect to Mi Band 1A automatically.

And instead of 
- Connecting -> Initializing -> Initialized

I think 
- Initializing -> Connecting -> Connected

is a better phrasing.

**Comment by Scinawa** [comment]
Same problem. I quote 100% :)

**Comment by cpfeiffer** [comment]
Can you post the firmware you're using? There's a firmware page in the wiki, which lists a version which worked in all respects. And 0.8.0 should have fixed the connections issues.

I'll check connection with 1a on lollipop.

**Comment by Scinawa** [comment]
Mine is 1.0.9.27

**Comment by official-jkim** [comment]
Mine is 5.15.11.19, for Mi Band 1A.

Unlike Wiki documentation, this latest firmware works very well with Gadgetbridge, fetching activity data works, connection works(at least), notification works. Only except for connection issue.

**Comment by cpfeiffer** [comment]
Thanks for the info, did you also test whether alarms work? If alarms work as well, we can update the wiki page and promote your firmware version.

**Comment by official-jkim** [comment]
Alarm works but because of this connection issue, if connection gets unstable it doesn't reconnect so sometimes Alarm doesn't ring.

**Comment by cpfeiffer** [comment]
Alarms are completely independent of a connection. They work fine without any mobile at all. So alarm not ringing could mean that
- the firmware is still buggy
- the device is buggy (loses the correct time, so alarms are off)

**Comment by cpfeiffer** [comment]
@official-jkim  Oh, and can you confirm that you're on 0.8.0?

**Comment by official-jkim** [comment]
Yes I'm using the latest version.

**Comment by cpfeiffer** [comment]
Ok, could you 
- enable logging in Gadgetbridge (Settings, scroll to the bottom)
- restart Gadgetbridge
- ensure that the log is created by having a look with a filemanager in /Android/data/nodomain.freeyourgadget.gadgetbridge/files/ 
- and then perform a connection attempt (which hopefully fails) and provide the log to us?

Thanks!

**Comment by official-jkim** [comment]
There is no such file or folder created. Permission setting is all okay though.

**Comment by official-jkim** [comment]
`08:56:49.671 [main] INFO  n.f.g.GBApplication - Gadgetbridge version: 0.8.0
08:57:07.905 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being created
08:57:07.906 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
08:57:07.914 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
08:57:11.272 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
08:57:11.282 [main] INFO  n.f.g.s.b.BtLEQueue - Attempting to connect to MI
08:57:11.282 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Queue Dispatch Thread started.
08:57:11.292 [main] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: CONNECTING
08:57:11.304 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:11.329 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Current track: <unknown>, Download, 토이 - 오늘 서울은 하루종일 맑음 (Piano)
08:57:11.332 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
08:57:14.117 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - connection state change, newState: 2 (success)
08:57:14.119 [Binder_1] INFO  n.f.g.s.b.BtLEQueue - Connected to GATT server.
08:57:14.127 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: CONNECTED
08:57:14.129 [Binder_1] INFO  n.f.g.s.b.BtLEQueue - Attempting to start service discovery:true
08:57:14.136 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:14.140 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to pair MI device...
08:57:14.141 [Binder_3] DEBUG n.f.g.s.d.m.MiBandSupport - Requesting Device Info!
08:57:14.151 [Binder_3] DEBUG n.f.g.s.d.m.MiBandSupport - Writing User Info!
08:57:14.153 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to set wear location...
08:57:14.154 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to set Fitness Goal...
08:57:14.183 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Sending current time to Mi Band: February 26 (25 Feb 2016 23:57:14 GMT)
08:57:14.184 [Binder_3] DEBUG n.f.g.s.d.m.MiBandSupport - Requesting Battery Info!
08:57:14.185 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - about to add: 8:57:14 AM: Transaction task: Initializing device with 16 actions
08:57:14.190 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: SetDeviceStateAction
08:57:14.191 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: NotifyAction on characteristic: 0000ff03-0000-1000-8000-00805f9b34fb
08:57:14.193 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.TransactionBuilder - use NOTIFICATION
08:57:14.200 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:14.505 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
08:57:14.510 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: WriteAction on characteristic: 0000ff0f-0000-1000-8000-00805f9b34fb
08:57:14.605 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 0000ff0f-0000-1000-8000-00805f9b34fb (success)
08:57:14.608 [Binder_2] INFO  n.f.g.s.d.m.MiBandSupport - Successfully paired  MI device
08:57:14.614 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: ReadAction on characteristic: 0000ff01-0000-1000-8000-00805f9b34fb
08:57:14.751 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic read: 0000ff01-0000-1000-8000-00805f9b34fb (success)
08:57:14.760 [Binder_1] WARN  n.f.g.s.d.m.MiBandSupport - Device info: DeviceInfo{deviceId='C8235CA205000801', profileVersion=33555968, fwVersion=84871955, hwVersion=8, feature=5, appearance=0}
08:57:14.764 [Binder_1] INFO  n.f.g.s.AbstractDeviceSupport - Got event for VERSION_INFO
08:57:14.770 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: ReadAction on characteristic: 00002a00-0000-1000-8000-00805f9b34fb
08:57:14.793 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:14.893 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic read: 00002a00-0000-1000-8000-00805f9b34fb (success)
08:57:14.898 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM:  on characteristic: 0000ff04-0000-1000-8000-00805f9b34fb
08:57:14.993 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 0000ff04-0000-1000-8000-00805f9b34fb (success)
08:57:14.997 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 0000ff03-0000-1000-8000-00805f9b34fb value:  0x5
08:57:14.999 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: CheckAuthenticationNeededAction
08:57:15.000 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Band successfully authenticated
08:57:15.004 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: WriteAction on characteristic: 0000ff05-0000-1000-8000-00805f9b34fb
08:57:15.005 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to pair MI device...
08:57:15.008 [Binder_3] DEBUG n.f.g.s.d.m.MiBandSupport - Requesting Device Info!
08:57:15.010 [Binder_3] DEBUG n.f.g.s.d.m.MiBandSupport - Writing User Info!
08:57:15.013 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to set wear location...
08:57:15.015 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to set Fitness Goal...
08:57:15.020 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Sending current time to Mi Band: February 26 (25 Feb 2016 23:57:15 GMT)
08:57:15.022 [Binder_3] DEBUG n.f.g.s.d.m.MiBandSupport - Requesting Battery Info!
08:57:15.026 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - about to add: 8:57:15 AM: Transaction task: Initialize device with 17 actions
08:57:15.029 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - about to add: 8:57:15 AM: Transaction task: just initializing after authentication with 0 actions
08:57:15.089 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 0000ff05-0000-1000-8000-00805f9b34fb (success)
08:57:15.093 [Binder_2] INFO  n.f.g.s.d.m.MiBandSupport - handleControlPoint write status:0
08:57:15.095 [Binder_2] INFO  n.f.g.s.d.m.MiBandSupport - handleControlPoint WROTE DATA:0x       f
08:57:15.098 [Binder_2] INFO  n.f.g.s.d.m.MiBandSupport - handleControlPoint WROTE DATA:0x       0
08:57:15.104 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: WriteAction on characteristic: 0000ff05-0000-1000-8000-00805f9b34fb
08:57:15.239 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 0000ff05-0000-1000-8000-00805f9b34fb (success)
08:57:15.243 [Binder_1] INFO  n.f.g.s.d.m.MiBandSupport - handleControlPoint write status:0
08:57:15.245 [Binder_1] INFO  n.f.g.s.d.m.MiBandSupport - handleControlPoint WROTE DATA:0x       5
08:57:15.247 [Binder_1] INFO  n.f.g.s.d.m.MiBandSupport - handleControlPoint WROTE DATA:0x       0
08:57:15.249 [Binder_1] INFO  n.f.g.s.d.m.MiBandSupport - handleControlPoint WROTE DATA:0x      88
08:57:15.252 [Binder_1] INFO  n.f.g.s.d.m.MiBandSupport - handleControlPoint WROTE DATA:0x      13
08:57:15.256 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: NotifyAction on characteristic: 0000ff06-0000-1000-8000-00805f9b34fb
08:57:15.262 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.TransactionBuilder - use NOTIFICATION
08:57:15.383 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
08:57:15.389 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: NotifyAction on characteristic: 0000ff07-0000-1000-8000-00805f9b34fb
08:57:15.397 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.TransactionBuilder - use NOTIFICATION
08:57:15.531 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
08:57:15.537 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: NotifyAction on characteristic: 0000ff0c-0000-1000-8000-00805f9b34fb
08:57:15.545 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.TransactionBuilder - use NOTIFICATION
08:57:15.722 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
08:57:15.727 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: NotifyAction on characteristic: 0000ff0e-0000-1000-8000-00805f9b34fb
08:57:15.731 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.TransactionBuilder - use NOTIFICATION
08:57:15.870 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
08:57:15.873 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: WriteAction on characteristic: 0000ff0a-0000-1000-8000-00805f9b34fb
08:57:15.966 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 0000ff0a-0000-1000-8000-00805f9b34fb (success)
08:57:15.971 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: ReadAction on characteristic: 0000ff0c-0000-1000-8000-00805f9b34fb
08:57:16.067 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic read: 0000ff0c-0000-1000-8000-00805f9b34fb (success)
08:57:16.072 [Binder_1] INFO  n.f.g.s.AbstractDeviceSupport - Got BATTERY_INFO device event
08:57:16.077 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: SetDeviceStateAction
08:57:16.081 [GadgetBridge GATT Dispatcher] INFO  n.f.g.s.b.CheckInitializedAction - Aborting device initialization, because already initialized: Device MI, C8:0F:10:23:5C:A2, initialized
08:57:16.085 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: CheckInitializedAction: aborting? true
08:57:16.087 [GadgetBridge GATT Dispatcher] INFO  n.f.g.s.b.CheckInitializedAction - Aborting device initialization, because already initialized: Device MI, C8:0F:10:23:5C:A2, initialized
08:57:16.089 [GadgetBridge GATT Dispatcher] INFO  n.f.g.s.b.a.AbortTransactionAction - Aborting transaction because abort criteria met.
08:57:16.092 [GadgetBridge GATT Dispatcher] INFO  n.f.g.s.b.CheckInitializedAction - Aborting device initialization, because already initialized: Device MI, C8:0F:10:23:5C:A2, initialized
08:57:16.092 [GadgetBridge GATT Dispatcher] ERROR n.f.g.s.b.BtLEQueue - Action returned false: February 26, 8:57 AM: CheckInitializedAction: aborting? true
08:57:16.101 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:16.130 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:18.414 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being destroyed
08:57:18.415 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: false
08:57:18.428 [main] DEBUG n.f.g.s.b.BtLEQueue - disconnect()
08:57:18.429 [main] INFO  n.f.g.s.b.BtLEQueue - Disconnecting BtLEQueue from GATT device
08:57:18.432 [main] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
08:57:18.435 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Thread interrupted
08:57:18.435 [GadgetBridge GATT Dispatcher] INFO  n.f.g.s.b.BtLEQueue - Queue Dispatch Thread terminated.
08:57:26.874 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being created
08:57:26.875 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
08:57:34.995 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
08:57:34.996 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
08:57:36.511 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
08:57:36.513 [main] INFO  n.f.g.s.b.BtLEQueue - Attempting to connect to MI
08:57:36.514 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Queue Dispatch Thread started.
08:57:36.521 [main] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: CONNECTING
08:57:36.522 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:36.550 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
08:57:44.375 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - connection state change, newState: 0 (failed: 133)
08:57:44.379 [Binder_1] WARN  n.f.g.s.b.BtLEQueue - connection state event with error status 133
08:57:44.392 [Binder_1] INFO  n.f.g.s.b.BtLEQueue - Disconnected from GATT server.
08:57:44.395 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - handleDisconnected: 133
08:57:44.397 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - internal gatt callback set to null
08:57:44.398 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
08:57:44.403 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - disconnect()
08:57:44.404 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:44.408 [Binder_1] INFO  n.f.g.s.b.BtLEQueue - Disconnecting BtLEQueue from GATT device
08:57:44.413 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
08:57:44.437 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:46.013 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
08:57:46.014 [main] DEBUG n.f.g.s.b.BtLEQueue - disconnect()
08:57:46.015 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Thread interrupted
08:57:46.016 [GadgetBridge GATT Dispatcher] INFO  n.f.g.s.b.BtLEQueue - Queue Dispatch Thread terminated.
08:57:46.016 [main] INFO  n.f.g.s.b.BtLEQueue - Attempting to connect to MI
08:57:46.017 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Queue Dispatch Thread started.
08:57:46.022 [main] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: CONNECTING
08:57:46.024 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:47.265 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - connection state change, newState: 2 (success)
08:57:47.267 [Binder_1] INFO  n.f.g.s.b.BtLEQueue - Connected to GATT server.
08:57:47.268 [Binder_1] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: CONNECTED
08:57:47.270 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:47.275 [Binder_1] INFO  n.f.g.s.b.BtLEQueue - Attempting to start service discovery:true
08:57:47.287 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to pair MI device...
08:57:47.290 [Binder_3] DEBUG n.f.g.s.d.m.MiBandSupport - Requesting Device Info!
08:57:47.291 [Binder_3] DEBUG n.f.g.s.d.m.MiBandSupport - Writing User Info!
08:57:47.293 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to set wear location...
08:57:47.294 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Attempting to set Fitness Goal...
08:57:47.296 [Binder_3] INFO  n.f.g.s.d.m.MiBandSupport - Sending current time to Mi Band: February 26 (25 Feb 2016 23:57:47 GMT)
08:57:47.297 [Binder_3] DEBUG n.f.g.s.d.m.MiBandSupport - Requesting Battery Info!
08:57:47.298 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - about to add: 8:57:47 AM: Transaction task: Initializing device with 16 actions
08:57:47.300 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: SetDeviceStateAction
08:57:47.302 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: NotifyAction on characteristic: 0000ff03-0000-1000-8000-00805f9b34fb
08:57:47.305 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.TransactionBuilder - use NOTIFICATION
08:57:47.305 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
08:57:47.407 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - descriptor write: 00002902-0000-1000-8000-00805f9b34fb (success)
08:57:47.408 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: February 26, 8:57 AM: WriteAction on characteristic: 0000ff0f-0000-1000-8000-00805f9b34fb
08:57:48.241 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 0000ff03-0000-1000-8000-00805f9b34fb value:  0x8
08:57:48.243 [Binder_2] WARN  n.f.g.s.d.m.MiBandSupport - DATA: 0x 8
08:57:48.482 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 0000ff03-0000-1000-8000-00805f9b34fb value:  0x8
08:57:48.484 [Binder_3] WARN  n.f.g.s.d.m.MiBandSupport - DATA: 0x 8
08:57:56.305 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being destroyed
08:57:56.306 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: false
08:57:56.310 [main] DEBUG n.f.g.s.b.BtLEQueue - disconnect()
08:57:56.311 [main] INFO  n.f.g.s.b.BtLEQueue - Disconnecting BtLEQueue from GATT device
08:57:56.314 [main] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
08:57:56.319 [GadgetBridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Thread interrupted
08:57:56.320 [GadgetBridge GATT Dispatcher] INFO  n.f.g.s.b.BtLEQueue - Queue Dispatch Thread terminated.
09:00:02.280 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being created
09:00:02.282 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
09:00:02.290 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
09:00:04.043 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being destroyed
09:00:04.044 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: false
09:00:05.302 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being created
09:00:05.305 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
09:00:05.310 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
09:00:14.018 [main] DEBUG n.f.g.s.DeviceCommunicationService - DeviceCommunicationService is being destroyed
09:00:14.020 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: false`

**Comment by cpfeiffer** [comment]
From a quick glance, I see that the service is being destroyed, so be wonder that the connection breaks. Communication with your mi looks all good, though. Wondering if this is a marshmallow issue.

**Comment by martykan** [comment]
Same problem here, but on the original version and with the latest firmware.

**Comment by bigretromike** [comment]
Same problem but with 1S

**Comment by cpfeiffer** [comment]
Connection issue is fixed with 89eddb13b025f4ace7e9e0dc7ad39f02b1309963, see #249
Regarding the connection status naming, there is now #266

**Comment by bigretromike** [comment]
Work alot better in 0.9.1 - I can confirm that ! Thanks
