### ISSUE TITLE
[idea] Add preferred sleep length to user preferences and allow quickly adding an alarm accordingly using a widget

### ISSUE THREAD

**Issue by 0nse** [Freeyourgadget/Gadgetbridge#237]
**I would like to be able to set my preferred sleep length (in hours) `n` in the settings:**
 > ![screenshot_20160229-231356](https://cloud.githubusercontent.com/assets/7449611/13411250/65656130-df3c-11e5-9aa3-7b4f6252e7f6.png)

**Then, I would like to add a widget to my home screen:**
 > ![screenshot_20160229-231412](https://cloud.githubusercontent.com/assets/7449611/13411260/7549537c-df3c-11e5-860f-711bdb7b6341.png)

**On pressing it, it would automatically set an alarm to wake me up using the current time `+n`:**
 > ![screenshot_20160229-231419](https://cloud.githubusercontent.com/assets/7449611/13411274/80575c3c-df3c-11e5-98fd-a92f5590716f.png)

**Also, it would add the alarm to the status bar:**
 > ![screenshot_20160229-231446](https://cloud.githubusercontent.com/assets/7449611/13411283/8bc62b5c-df3c-11e5-85df-5c7fac0d80fe.png)

---
If you are interested, I can create a pull request from 3babedf93618da6dcfb8bc347312edc0288c779c. NB: I have not done Android development before. The widget will blindly overwrite the first alarm and clicking the alarm in the status bar does not open GadgetBridge's alarm management activity.

**Comment by cpfeiffer** [comment]
Great idea! I week have a look at your patch in the evening. There is already some code for reserving an alarm (for calendar reminders), btw, maybe you can reuse something there.

**Comment by cpfeiffer** [comment]
Apart from some unrelated code formattings, this looks very good, great job! I commented two things directly on your commit -- if you can address these things, I'd love to get a pull request.

Thanks!
