### ISSUE TITLE
Activity populates dates with no data with identical data

### ISSUE THREAD

**Issue by Samarium151** [Freeyourgadget/Gadgetbridge#238]
If I scroll back prior to the date of instalation of the device each day contains a duplicate of what appears to be the first date's data.  This is on 0.8.0, Pebble time round 3.9.2 android 5.1

![screenshot_2016-03-01-08-27-34](https://cloud.githubusercontent.com/assets/17170947/13433690/d99cf266-df87-11e5-8ea8-83995978786e.png)
![screenshot_2016-03-01-08-32-22](https://cloud.githubusercontent.com/assets/17170947/13433770/3239d7a4-df88-11e5-82a8-ec0df0295557.png)

**Comment by ashimokawa** [comment]
fixed in git, thanks @cpfeiffer
