### ISSUE TITLE
Support for custom path of ActivityDatabase

### ISSUE THREAD

**Issue by envolyse** [Freeyourgadget/Gadgetbridge#241]
I'm using ActivityDatabase to get information about my activity (storing the output of GBActivitySamples into text file and then processing it into an Org file), so usually I need to open file manager on phone, enable root mode, get into the /data/data/*gadgetbridge, copy it into syncthing folder on sdcard and then process it with my script on laptop. What I want is that GadgetBridge could store databases on sdcard or have an option for that, so that you don't need to have an root access for moving database to an sdcard.

**Comment by danielegobbetti** [comment]
you can use the export db button on the debug activity. this copies the db to the external storage under Android/data/nodomain....

I believe you could add that path to syncthing.

In order to export it to other places we would need to have storage access permission.

**Comment by envolyse** [comment]
>you can use the export db button on the debug activity

oh! didn't saw that one. solved then :)
