### ISSUE TITLE
Fetching activity data suddenly doesn't work

### ISSUE THREAD

**Issue by official-jkim** [Freeyourgadget/Gadgetbridge#243]
![1](https://cloud.githubusercontent.com/assets/12594372/13511806/36e1f3e6-e1da-11e5-96d9-1e5c28593af7.jpg)

Mi Band is paired, but Gadgetbridge doesn't fetch activity data from Mi Band and keep spitting this error message. I think this happened when I removed the latest version of Gadgetbridge and then installed an old version. After that, as you see it doesn't work. I re-installed the latest version again, but same result came out. Notification and live activity works well though. Only fetching and drawing activity data graph doesn't work.

It's not an Android Marshmallow issue, because it worked well before. Also it's not a band issue, because this happens to 2 different Mi Bands. Rebooting didn't solve this problem.

**Comment by official-jkim** [comment]
Problem solved. I roll-backed Gadgetbridge to version 0.7.2 then upgraded to 0.7.4 and 0.8.1. Seems uncompatible setting values in older version were preserved and then utilised by newer version and it conflicted with those two different versions. Can we make 'reset all internal settings data to default' feature in debug menu?

**Comment by feclare** [comment]
I did this change to create a database with the missing field:
diff --git a/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/schema/ActivityDBCreationScript.java b/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/schema/ActivityDBCreationScript.java
index 9aa67c8..8d6f6d5 100644
--- a/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/schema/ActivityDBCreationScript.java
+++ b/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/schema/ActivityDBCreationScript.java
@@ -9,6 +9,7 @@ import static nodomain.freeyourgadget.gadgetbridge.database.DBConstants.KEY_PROV
 import static nodomain.freeyourgadget.gadgetbridge.database.DBConstants.KEY_STEPS;
 import static nodomain.freeyourgadget.gadgetbridge.database.DBConstants.KEY_TIMESTAMP;
 import static nodomain.freeyourgadget.gadgetbridge.database.DBConstants.KEY_TYPE;
+import static nodomain.freeyourgadget.gadgetbridge.database.DBConstants.KEY_CUSTOM_SHORT;
 import static nodomain.freeyourgadget.gadgetbridge.database.DBConstants.TABLE_GBACTIVITYSAMPLES;
 
 public class ActivityDBCreationScript {
@@ -19,6 +20,7 @@ public class ActivityDBCreationScript {
                 + KEY_INTENSITY + " SMALLINT,"
                 + KEY_STEPS + " TINYINT,"
                 + KEY_TYPE + " TINYINT,"
+                + KEY_CUSTOM_SHORT + " INT,"
                 + " PRIMARY KEY (" + KEY_TIMESTAMP + "," + KEY_PROVIDER + ") ON CONFLICT REPLACE)" + DBHelper.getWithoutRowId();
         db.execSQL(CREATE_GBACTIVITYSAMPLES_TABLE);
     }

**Comment by cpfeiffer** [comment]
@feclare This should actually not be necessary, because we have a schema upgrade mechanism in place. It looks like there is a bug there, I will investigate.

I think it's an accidental commit in ActivityDatabaseHandler.onUpgrade(), but I'm without the PC right now.

**Comment by cpfeiffer** [comment]
@official-jkim and @feclare I don't see any ovious bug from staring at the code, so, do you have logging enabled by chance, and could share your logfile (either publically or personally)?

I'd love to know how this could happen.

**Comment by official-jkim** [comment]
I can't reproduce it, now it's interacting very well with 0.8.1

**Comment by feclare** [comment]
I did compile a version today with some modification to add the coarse
permission to run on marshmallow(cyanogen 13).

It happened to me also when I removed the database manually.

**Comment by cpfeiffer** [comment]
OK, thanks for the info!

**Comment by danielegobbetti** [comment]
@feclare indeed your patch is needed. I tried a fresh installation and the error is there without. I'm closing this since it's fixed in master. We will release soon.

**Comment by danielegobbetti** [comment]
@feclare I looked in your github page to find a proper way to let the commit to be authored by you, but unfortunately I didn't find any repository of yours and therefore no email address :(
I thanked you in the changelog file.
