### ISSUE TITLE
Scanning forever

### ISSUE THREAD

**Issue by anupam19** [Freeyourgadget/Gadgetbridge#244]
Didn't find mi band : http://www.mi.com/in/miband/
firmware : 5.15.12.10
Help needed

**Comment by cpfeiffer** [comment]
Can you try manually pairing your band with the android Bluetooth dialog? Gadgetbridge should then display and key you connect to it.

**Comment by anupam19** [comment]
I tried but my mobile was unable to find the Mi Band. But nordic NRF master
tool was able to find.

**Comment by cpfeiffer** [comment]
I cannot really help with this. Maybe your mobile does not support Bluetooth 4.0 LE (sometimes called "smart").

If you phone doesn't find it, Gadgetbridge will not be able to use it.

**Comment by cpfeiffer** [comment]
I'm closing it since this is not a Gadgetbridge issue -- feel free to add further comments if you have questions.
