### ISSUE TITLE
Mi Band 1A firmware version 5.15.11.19 information

### ISSUE THREAD

**Issue by official-jkim** [Freeyourgadget/Gadgetbridge#245]
alarms: mostly works (randomly fails)
notifications: mostly works (randomly fails)
activity recognition: works
connection: works
battery life: good
sleep detection: doesn't work (band recognises sleep but not wake-up)
lift and twist wrist to check activity goal progress through LEDs: doesn't work

Downgrading to 5.15.7.14.fw is highly recommended.

**Comment by ashimokawa** [comment]
@official-jkim 
Thank you for the information.
However I removed the file you attached, as we are unfortunately (most likely) not allowed to redistribute firmwares.

**Comment by cpfeiffer** [comment]
Thanks, @official-jkim, I added your information to the wiki.
