### ISSUE TITLE
Power usage is too high (on watch)

### ISSUE THREAD

**Issue by derlaft** [Freeyourgadget/Gadgetbridge#25]
Pebble official app: 7 days of life.

Gadgetbridge: about 3 days of life without recharging.

**Comment by ashimokawa** [comment]
Wow, can anyone confirm?
I do not use Bluetooth 24/7 so I haven't noticed anything yet.
I really have no idea why this could happen. We do not send anything to the watch when idle.
But most of the time the watch sends encrypted analytics(?) data to us which we throw away. But this should also be the case with the official app.

**Comment by ashimokawa** [comment]
@derlaft 
Can you check logcats for anything suspicious from gadgetbridge?
Something like "unhandled message to endpoint ".

**Comment by derlaft** [comment]
OK, but I think I'll able to do it only one week later (travelling).

**Comment by ddagunts** [comment]
It's possible that the watch firmware is persistent in trying to send
"analytics" data, thus wasting the battery.  IE: analytics data is supposed
to be sent once a day IF connected, but if sending fails, retry every 5 min
as long as the watch is connected.

**Comment by ashimokawa** [comment]
@ddagunts 
Actually we get data from the watch more than once a minute. In batches of about 650 bytes IIRC. Sometimes multiple batches are immediately following.

Someone would have to analyze if this also happens with the official app. I have not used it so far.

**Comment by ddagunts** [comment]
Wow, every minute...  Perhaps someone could check if the official app
notifies the watch of network connectivity loss?

1. install official app.
2. pair device.
3. start sniffing bluetooth
4. disable data/WiFi/LTE on device
5. see if app notifies pebble that there is no network available.

You could then replicate the "no network available" command upon bluetooth
connection to Pebble.  I'm a little busy this week so I don't think I'll
get to this, but maybe...


On Thu, Apr 23, 2015 at 2:11 AM, Andreas Shimokawa <notifications@github.com

**Comment by ashimokawa** [comment]
@ddagunts 
How do you know about the rule when data is supposed to be sent from the watch?
All I could research so far is that data is coming from endpoint 6778 and with the official app there are also very small packages send to that endpoint from the phone. I replicated one of these without success. Maybe it is some kind of ACK with a specific ids, and I have to parse these from the incoming data.

**Comment by ashimokawa** [comment]
@derlaft 
Do you have any watchfaces or apps installed that somehow display external data (like weather forecasts)?
It could be that these request data from their .js code counterpart living inside pebble app over and over again. Of course we do not answer to these request.

Or can anyone else confirm higher battery usage with Gadgetbridge?

**Comment by derlaft** [comment]
I have no app/watchfaces installed

**Comment by ddagunts** [comment]
@ashimokawa 
The "rule" was a guess on my part.  I will try looking at this...  Not sure how far I'll get if it's encrypted data since the firmware isn't open-source AFAIK...

**Comment by ashimokawa** [comment]
I added better debug messages. Incoming data comes in a lot of small packages sometimes. For me the small ones contains the payload 0x0002.  If I reply with 0x0002 the pebble closes the Bluetooth connection. If I reply with 0x0001 then nothing happens.

I guess I need to sniff and compare with the original app :(

```
04-25 23:28:02.931    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ datalog to endpoint 6778 (2 bytes)
04-25 23:28:02.931    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 0002
04-25 23:28:03.061    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ datalog to endpoint 6778 (2 bytes)
04-25 23:28:03.061    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 0002
04-25 23:28:03.171    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ datalog to endpoint 6778 (2 bytes)
04-25 23:28:03.171    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 0002
04-25 23:28:03.291    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ datalog to endpoint 6778 (2 bytes)
04-25 23:28:03.291    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 0002
04-25 23:28:03.391    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ datalog to endpoint 6778 (2 bytes)
04-25 23:28:03.391    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 0002
04-25 23:28:03.501    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ datalog to endpoint 6778 (2 bytes)
04-25 23:28:03.501    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 0002
04-25 23:28:03.591    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ datalog to endpoint 6778 (2 bytes)
04-25 23:28:03.591    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 0002
04-25 23:28:03.711    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ datalog to endpoint 6778 (2 bytes)
04-25 23:28:03.711    6994-7208/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 0002
```

**Comment by ashimokawa** [comment]
My Pebble just rebooted itself after a crash, then the datalog packages stopped completely for a few minutes. Then it started again, but only a very few and smaller packages.

The 2-byte packets start with 0x07 as before, the first bigger one with 0x01, the second bigger one with 0x02.

The second byte (2-byte packet and bigger packet) was always 0x65 which could be some kind of handle.

In my post before I had  0xa4, 0xab, 0xcb and others, maybe there where different handles for different datalog packages that could not be delivered.

```
04-26 01:00:19.502  14066-14175/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 01650B73B76ACD654DC29585AAA213320858A1383C5534120000002E00
04-26 01:00:48.751  14066-14175/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ datalog to endpoint 6778 (2 bytes)
04-26 01:00:48.751  14066-14175/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 0765
04-26 01:03:01.500  14066-14175/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ datalog to endpoint 6778 (56 bytes)
04-26 01:03:01.510  14066-14175/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 0265FFFF00000E0B8579010112002A000000CC353C557801000073FC73FD71FC71FC71FC71FC75FD71FC75FD73FC73FD71FC75FD00000000
04-26 01:03:31.880  14066-14175/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ datalog to endpoint 6778 (2 bytes)
04-26 01:03:31.880  14066-14175/nodomain.freeyourgadget.gadgetbridge I/PebbleIoThread﹕ hexdump: 0765
```

**Comment by ashimokawa** [comment]
This could still be a coincidence but seems with the latest commit datalog packets are almost down to zero.
I just reply with 0x85 and the supposed handle when a datalog packet comes in. The first time I did it, I got flooded with datalog packets like there is no tomorrow,  and then,  it stopped.
Hope it will stay like this and it really helps battery.

**Comment by ashimokawa** [comment]
We just tagged 0.3.3 which should appear on f-droid tomorrow.
@derlaft , please report back if it fixes the issue.

**Comment by ashimokawa** [comment]
I'll close this since because I think it is fixed.
Please reopen if you still face this issue.
