### ISSUE TITLE
Inaccurate light/deep sleep detection

### ISSUE THREAD

**Issue by bigretromike** [Freeyourgadget/Gadgetbridge#250]
Im not sure if this is mi band 1s related or not but...
Im using the GB for 2 days now - with few yey and nay...
But in the sleep data I have mine sleep chart reverse with compare to mi fit that I used before flashing phone.
currently i Have 7:26 h sleep, with 6:25 deep sleep and 1:01 light sleep. This been allways the oposite in mi fit - so im not sure if this is reversed or the data from mi band have reverse standard... I doube that I had good night ;-)

**Comment by danielegobbetti** [comment]
see the comment I left in #257

if you have resources related to actimetry algorithms  to recognise deep sleep please post them to #232 or our wiki!

**Comment by bigretromike** [comment]
Like you post, if its inverted it would look ok.
For me its ONLY inverted: 6:39 = 0:54 Light + 5:45 Deep (definityly MY TYPE of Data but inverted) Its looks almost legit as mi-fit app would throw at me, but inverted.

I think you nailed it but need to just invert for mi band 1s !
Im 100% sure of those numbers.

**Comment by bigretromike** [comment]
0.9.0 still have those value inverted

**Comment by danielegobbetti** [comment]
The main issue can be seen here:
https://github.com/KashaMalaga/XiaomiMiBand/blob/4327a2a3853311a3f271f2a92e3762dced5f9559/smali/cn/com/smartdevices/bracelet/l.2.smali#L1545
The deep and shallow sleep values depend upon another variable (I'm reporting the relevant lines here):

Case 1:
```
    invoke-virtual {p1, v2}, Lcom/xiaomi/hm/health/dataprocess/DaySportData$SummaryEntity;->setSleepDeepTime(I)V
    invoke-virtual {p1, v0}, Lcom/xiaomi/hm/health/dataprocess/DaySportData$SummaryEntity;->setSleepShallowTime(I)V
```
Case 2:
```
    invoke-virtual {p1, v0}, Lcom/xiaomi/hm/health/dataprocess/DaySportData$SummaryEntity;->setSleepDeepTime(I)V
    invoke-virtual {p1, v2}, Lcom/xiaomi/hm/health/dataprocess/DaySportData$SummaryEntity;->setSleepShallowTime(I)V
```
As you see the v0 and v2 values are inverted.

As you see, it's not simple to understand what's really going on. That's the reason of the "help wanted" and "research" label.

Another approach would be to add a toggle in the miband settings where the user can choose to invert these two values at will, but that would not solve the issue.

**Comment by bigretromike** [comment]
To be accurate there are 3 cases: on lines 1285, 1547, 1603 
2 of them use v0 and only one use v2. 

I understand that if-ne is checking if p3 and v3 are not null/0.
if they are empty use v2 v0 if they aren't then use v0 v2.

I don't understand much of code but it looks like p3 is related to SportDay (https://github.com/KashaMalaga/XiaomiMiBand/blob/4327a2a3853311a3f271f2a92e3762dced5f9559/smali/cn/com/smartdevices/bracelet/l.2.smali#L224)

v3 looks like its maxcontinuedays (https://github.com/KashaMalaga/XiaomiMiBand/blob/4327a2a3853311a3f271f2a92e3762dced5f9559/smali/cn/com/smartdevices/bracelet/l.2.smali#L250)

So it maybe be related to training day and continuous of those days ? because more you train day by day more you deep sleep (this is just a blind shot)

**Comment by danielegobbetti** [comment]
-- deleted a few comments --

**Comment by computerlyrik** [comment]
Just updated to FW 4.15.12.10
Will report tomorrow about sleep data.
With GB 0.9.1 and FW 4.11 sleep data was indeed inverted.

**Comment by bigretromike** [comment]
sadly FW update to 04.15.12.10 wont flip those, also authors didnt confirm fliping them on 0.9.3 :-) so we will have to wait till they make enought research to flip those values :/ until then i will lie to myself that I have sooo much deep sleep ;-)

**Comment by bigretromike** [comment]
In "Mi Band Settings" I enabled "Use Heartrate Sensor to improve sleep ..." and I see hr on sleep graph for few days, but that didn't helped with inverted values.

**Comment by bigretromike** [comment]
0.11.1 - the data is still inverted, "Use Heartrate Sensor to improve sleep ..." is enabled all the time. It looks like M1S flip those because I dont see anyone that report those "flips" and probably M1S is less popular her anyway.
Its been some time now... Will this be fixed or should m1s owners move out ?

**Comment by cpfeiffer** [comment]
It will get fixed eventually. If there are other people that can confirm that Gadgetbridge displays the opposite of Mi Fit, then we can indeed simply flip those values.

**Comment by rplevka** [comment]
@cpfeiffer I think I can confirm what @bigretromike says - last night i got 4hr 56 min of deep sleep vs. 44 min of light sleep - that is indeed weird and should be inverted.

**Comment by rplevka** [comment]
There's definitely got to be some post processing in place on the APP side of things. The device seems to send you data for individual 'epochs' (every minute) with labeling it with activity type. However, you can't get the real deep sleep just by counting the number of minutes marked as 'deep sleep'. There should be some algorithm that would look for some patterns (e.g. If there were any light sleep epochs in some interval, mark whole interval as Light Sleep).

**Comment by bigretromike** [comment]
To be honest those inverted values are almost tge same as official mi band application, but like i wrote those values are inverted, if we invert those it will look almost as the data from mi fit, so I wouldnt worry much about post processing 

On July 17, 2016 11:31:17 AM GMT+02:00, Roman Plevka <notifications@github.com> wrote:
>There's definitely got to be some post processing in place on the APP
>side of things. The device seems to send you data for individual
>'epochs' (every minute) with labeling it with activity type. However,
>you can't get the real deep sleep just by counting the number of
>minutes marked as 'deep sleep'. There should be some algorithm that
>would look for some patterns (e.g. If there were any light sleep epochs
>in some interval, mark whole interval as Light Sleep).
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Freeyourgadget/Gadgetbridge/issues/250#issuecomment-233173323

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rplevka** [comment]
@bigretromike I checked on the values, but aside the activity type there's also an intensity value (intensity of movement) - for those marked as 'deep sleep' the intensity is very low and for those marked as 'light sleep', the intensity is quite high. That's why I'm not sure whether they're just inverted.

**Comment by bigretromike** [comment]
Im unsure because I dont debug is as hard but for me its clearly that deep sleep is inverted with light sleep, maybe those values are in % where 100% is deep sleep so the deep sleep hours have bigger counter, that im unsure but im sure that mi fit showed me from day one that my deep sleep is usuly less than hour and gb tell me that my light sleep is only less than 1h but me deep sleep is 5-7 h, which is inaccure as hell. 

On July 17, 2016 12:04:40 PM GMT+02:00, Roman Plevka <notifications@github.com> wrote:
>@bigretromike I checked on the values, but aside the activity type
>there's also an intensity value (intensity of movement) - for those
>marked as 'deep sleep' the intensity is very low and for those marked
>as 'light sleep', the intensity is quite high. That's why I'm not sure
>whether they're just inverted.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Freeyourgadget/Gadgetbridge/issues/250#issuecomment-233174470

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rplevka** [comment]
@bigretromike totally, same here. My point was that simply inverting these values won't be right either. It's just a funny correlation that inverted values are closer to the reality. I believe the most of the 'deep sleep' epochs would be simply converted to 'light sleep' if a correct sleep-cycle detection algorithm would be in place. That'd almost look like an inverted DS/LS but still would be different.
Even if I invert the values now, I still see 1+ hour error comparing to my mi fit measurements.

**Comment by bigretromike** [comment]
So i understand you use both app right? Its problem for me because i totaly droped all app and stayed with gb :-) thats why it iritates me that much. But showing friend gb and sayig 'its best fit app and its open source but it invert my data' aint that good for me ;)

On July 17, 2016 12:24:17 PM GMT+02:00, Roman Plevka <notifications@github.com> wrote:
>@bigretromike totally, same here. My point was that simply inverting
>these values won't be right either. It's just a funny correlation that
>inverted values are closer to the reality. I believe the most of the
>'deep sleep' epochs would be simply converted to 'light sleep' if a
>correct sleep-cycle detection algorithm would be in place. That'd
>almost look like an inverted DS/LS but still would be different.
>Even if I invert the values now, I still see 1+ hour error comparing to
>my mi fit measurements.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Freeyourgadget/Gadgetbridge/issues/250#issuecomment-233175160

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cpfeiffer** [comment]
Hehe. I totally agree that we need some improvements here.

As a quick fix, I can indeed invert those values, so that the values are at least a bit more realistic. Are you willing to work with me on getting a better algorithm? You don't even need to hack Gadgetbridge, know Android or Java. A description of an algorithm how to calculate the amounts from the samples you see would already help.

**Comment by cpfeiffer** [comment]
Oh, and comparisons with other apps, including Mi Fit help as well.

**Comment by bigretromike** [comment]
I would have to install mi fit then, but Im fine with helping you. Just say what I need to install, prepare so I will collect data you need. Currently im using GB only,  but if I need mi fit or other app just say.

**Comment by bigretromike** [comment]
Just invert that values :+1:

**Comment by cpfeiffer** [comment]
If you don't have Mi Fit, that's fine. Maybe there are others who have it installed and can share comparisons, e.g. screenshots of their data.

**Comment by rplevka** [comment]
@cpfeiffer for a 3rd night in a row I've been trying to download my sleep data to GB with "keep data on a band" option checked, but when i fire up Mi Fit to sync the data, it says there's none anymore. Is that a bug in GB or am I doing it wrong?

**Comment by cpfeiffer** [comment]
@rplevka For me it does work. Didn't test with Mi Fit, but if I have this option enabled, I can sync twice and get the same samples every time.

Maybe Mi Fit already fetched the data? Or is it simply not available in Mi Fit?

**Comment by rplevka** [comment]
I can confirm, the data stay on the band, however mifit won't pick them up for some reason

**Comment by gadgetguy08** [comment]
Just got a Mi Band 1S. 
FW 4.6.4.22
HR 1.6.1.22
GB 0.13.7

Arm right

Sleep data shows Deep sleep is lighter color and Light sleep darker.  But the "activity" bars are taller for the light bars. Also there were lighter bars at one point when I know I was awake, making me wonder if they are reversed for me.

Attemped to post a screen shot with the Android app..

**Comment by rplevka** [comment]
@gadgetguy08 yes. This is simply caused by the fact that guys felt like switching light and deep sleep types gets more appropriate results when it comes to total light and total deep sleep.
(just read the thread above).
I myself beleive, the values were right, but there was some additional postprocessing which turned some sequences of deep sleep to the light sleep etc. 

so I also believe, we should not really invert the values

**Comment by bigretromike** [comment]
for me current values look ok;
sadly its hard for me to check each version as always I end up wiping those data out of both db and band :/

**Comment by cpfeiffer** [comment]
We're aware that the mobile is not the ideal place to store the data forever. An external storage service is planned and there is also some experimentation code already.
