### ISSUE TITLE
Request: Misfit 3.3 for firmware Pebble 2.9.1

### ISSUE THREAD

**Issue by tecufanujacu** [Freeyourgadget/Gadgetbridge#253]
Is there someone that can share the watchapp for Pebble Misfit 3.3 ?
I have a Pebble Classic with the firmware 2.9.1 and for now I wont update to the firmware 3.x, Misfit 3.3 is the last version compatible with the firmwares 2.x and for this motive I can't use Misfit because on the Pebble Store there is only the version 3.7 compatible with the firmwares 3.x.

I searched Misfit 3.3 everywhere but without success, I also contacted Misfit via email and via Facebook but they wont help.

If someone has the pbw or has installed it please upload it somewhere.
To grab the pbw in case it is installed then you can get it in one of these paths:
/data/data/com.getpebble.android/cache or /data/data
/data/data//com.getpebble.android.basalt/app_apps_cache

I'd like to use Misfit 3.3 with Gadgetbridge on my firmware 2.9.1, please help me.

**Comment by ashimokawa** [comment]
Sorry, I removed the links you provided.
Hope someone can help you!

**Comment by tecufanujacu** [comment]
Just to know, why you removed the links? Have I violated some rule? In this case I'm sorry.
That only was the direct link to the official .pbw of Misfit 3.7 present in the Pebble Store.

**Comment by ashimokawa** [comment]
These were links to the official location but it is not the official way to get them, right ;)
I don't know about pebbles policy on this, so to play safe I would think it is better not to link to pebbles APIs directly.

Alsom the link to the current Misfit does not have anything to do with your problem. You want 3.3 ;)

**Comment by ashimokawa** [comment]
Oh and maybe you should post a way how you can be contaced, maybe someone sends you the file without posting it here (which would not be good I guess)

**Comment by tecufanujacu** [comment]
Ok, then I'm sorry.
Anyway thanks for suggestion, i published my email address in my profile.

I hope that someone will help me.
Thanks in advance.

**Comment by krayon** [comment]
@tecufanujacu I too have the same issue (though stuck on 2.2). If you found one later than 2.2 could you please send it to github20090710qg6m@datapax.com.au , thanks :)
