### ISSUE TITLE
Improve the "discovery_connected_devices_hint" message

### ISSUE THREAD

**Issue by chrisvella** [Freeyourgadget/Gadgetbridge#254]
I believe the message should be changed to notify users that they may need to restart their phone for the device to display, and that they should connect via bluetooth first. Both new mi bands I have attempted to connect via gadget bridge have required these two steps. For a new user it looks like the device is broken.

**Comment by cpfeiffer** [comment]
Turning on bluetooth is indeed necessary. The main activity actually displays a hint about that, IIRC, but the discovery activity lacks that.

We might also pop up a confirmation dialog and enable bluetooth programmatically. Thanks for pointing this out!

**Comment by cpfeiffer** [comment]
Btw, rebooting the mobile should never be necessary. Do you have other bluetooth devices or other apps using bluetooth that might cause such behavior?

**Comment by chrisvella** [comment]
For my mi band and my mi band s I have had to reboot the phone for the device to be recognized in gadgetbridge. Maybe its an issue with my phone... but both times I have thought the device was broken.

**Comment by cpfeiffer** [comment]
Fixed.
