### ISSUE TITLE
Can not connect to Pebble

### ISSUE THREAD

**Issue by TonyBostonTB** [Freeyourgadget/Gadgetbridge#255]
Hey there, 
I paired the pebble with my Sony xperia Z running CM12.1 but I can not connect to pebble from within gadgetbridge. Not sure if  I missed something?
Logfile [gadgetbridge.log.pdf](https://github.com/Freeyourgadget/Gadgetbridge/files/171637/gadgetbridge.log.pdf)

**Comment by TonyBostonTB** [comment]
[gadgetbridge.log.pdf](https://github.com/Freeyourgadget/Gadgetbridge/files/171637/gadgetbridge.log.pdf)

**Comment by ashimokawa** [comment]
Make sure you didn't try to connect to a LE Pebble, that there is no other device (or app) connected to the same Pebble.

**Comment by TonyBostonTB** [comment]
I deleted all devices from the pebble, the Xperia is the only one left. Also deleted the LE one from gadgetbridge. Now it has only "Pebble 779D"

**Comment by TonyBostonTB** [comment]
Okay now it works. I've reset the Pebble. Can connect now but the Pebbles keeps saying that I need to go to pebble.com/apps

**Comment by ashimokawa** [comment]
@TonyBostonTB 
I have no idea why you had to reset your pebble, normally that should not have been necessary.
Anyway, glad you made it run. Closing.
