### ISSUE TITLE
Mi Band firmware won't update

### ISSUE THREAD

**Issue by miguelpenc** [Freeyourgadget/Gadgetbridge#256]
HI,

I have tried to upgrade the firmware of the first Mi Band, after extracting it from the apk. I think it is supposed to be the one named `Mili.fw` but the app keeps saying me 'This firmware is not compatible with the device'. I have no idea of how to debug this. I have tried several firmwares from different apks versions and no one works.

Thanks in advance.

**Comment by cpfeiffer** [comment]
Hi,

maybe you used the wrong *.fw file -- there are different files, one for each Mi Band model. I added some documentation [here](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Update), I hope it will help you.

**Comment by danielegobbetti** [comment]
I'm closing this since fw upgrade of original miband works for other and there was no feedback for a couple of days.

if you are still experiencing problems after verifying that your fw md5 matches one listed on the wiki feel free to reopen it.
