### ISSUE TITLE
Consider using different connection status names

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#266]
The current connection status
* Disconnected
* Connected
* Initializing
* Initialized

are somewhat misleading. Maybe it would be better if we'd switch to a scheme like this:
* Disconnected
* Established
* Initializing
* Connected

Maybe we could even drop "Established", but I think we should keep it.

**Comment by danielegobbetti** [comment]
I believe we could change the terminology, but we should at all costs avoid swapping the order of the terms we are currently using.

I don't believe the current terms are particularly bad, frankly speaking, but I'm no native speaker (far from it).

I also believe we should keep the changes to a minimum, to ease the job of the translators.

For instance we could change "initialized" with "ready" (as in "ready for user interaction"), keeping all the other terms as they are.

**Comment by ashimokawa** [comment]
I removed initializing and initialized completely.
initialized, the final state is now "connected".
previous "connected" and "initializing" are now displayed as "connecting"

not connected -> connecting -> connected
