### ISSUE TITLE
Set alarm on Miband 1A

### ISSUE THREAD

**Issue by tekkeitserktok** [Freeyourgadget/Gadgetbridge#268]
Hello, 

It says on the readme file that you can set alarms on the miband but I don't see any options in order to do this... 

Can you help me ? 

Thanks !

**Comment by cpfeiffer** [comment]
Make a long press on the device, once it is connected and chose "Set Alarms".

Yes, we will improve the ui soon.

**Comment by tekkeitserktok** [comment]
Thank you !
