### ISSUE TITLE
Improve package sorting in blacklist

### ISSUE THREAD

**Issue by noirlab** [Freeyourgadget/Gadgetbridge#275]
This is likely an enhancement on the work already done for #195

Currently, the blacklist is sorted by package name rather than the Apps display name. This means au.com.test.zombies (display name "Zombies") will appear before com.aleph.commander (display name "Commander"). Sorting by display name is more natural.

**Comment by ashimokawa** [comment]
I tried just now,  but with the current approach (comparing ApplicationInfo objects), it makes the list ultra slow because we have to lookup the display name from the package name for each single compare while sorting.

**Comment by ashimokawa** [comment]
`--- a/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/AppBlacklistActivity.java
+++ b/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/AppBlacklistActivity.java
@@ -89,7 +89,7 @@ public class AppBlacklistActivity extends Activity {
 
                         if ((blacklisted1 && blacklisted2) || (!blacklisted1 && !blacklisted2)) {
                             // both blacklisted or both not blacklisted = sort by alphabet
-                            return ai1.packageName.compareTo(ai2.packageName);
+                            return ai1.loadLabel(pm).toString().compareTo(ai2.loadLabel(pm).toString());
                         } else if (blacklisted1) {
                             return -1;
                         } else {
`

This is slow.

**Comment by cpfeiffer** [comment]
You should remember the name somewhere, so that you have to look it up just once.

**Comment by noirlab** [comment]
I made [this commit](https://github.com/noirlab/Gadgetbridge/commit/8d1bf16725ff73835b491b9c8870f941d66abf32) that utilizes a built-in method - [ApplicationInfo.DisplayNameComparator](http://developer.android.com/reference/android/content/pm/ApplicationInfo.DisplayNameComparator.html), it doesn't feel very sluggish to me, but I'm new to the app and my testing wasn't scientific.

The downside is the list is being sorted twice, but it doesn't look like a performance disaster

**Comment by ashimokawa** [comment]
I didn't know about the DisplayNameComparator - nice.
I will have a look.

**Comment by ashimokawa** [comment]
Unfortunately your solutions also kills performance just like mine here. Takes 2 seconds to open the activity and also stalls when scrolling.
S4 Mini LTE

**Comment by ashimokawa** [comment]
Sometimes even 5-6 seconds to open the activity, with only 69 total (including system apps) installed, strange.
