### ISSUE TITLE
How to store user info inside Mi Band?

### ISSUE THREAD

**Issue by AlexanderHryk** [Freeyourgadget/Gadgetbridge#280]
I'm sorry for offtopic but i have a problem with Mi Band that can be solved here (I hope)... For heart rate measuring (Mi Band 1S) is necessary that the 'USER_INFO' characteristic isn't empty. I'm successfully writing user info (username, age, weight etc.) to Mi Band but when the last one disconnects from smartphone then the 'USER_INFO' characteristic erased (original app saves the user info inside Mi Band without necessity to overwrite it every time when Mi Band has been connected). How to write user info to Mi Band that it will be saved inside?

**Comment by cpfeiffer** [comment]
You have to send user info whenever you connect. Gadgetbridge (and probably also Mi Fit) saves these settings in the Android preferences in order to send them after connection.
