### ISSUE TITLE
'Find my phone'

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#282]
It would be cool to have an option 'find my phone' that we could activate as a notification handler. When receiving a notification, or from the nofication list, we could use that to make the phone ring and find it at any moment.

**Comment by danielegobbetti** [comment]
Just to be sure I understood it right:
when the device sends a notification to the pebble, you would like to add an action (on the pebble) that causes the phone to ring in order to locate it. is this correct?

**Comment by roidelapluie** [comment]
Yes. Looks like it would probably be better to have a separate app on the watch to do this. Did we already think about releasing a pebble app as gadgetbridge companion?

**Comment by ashimokawa** [comment]
The Pebble App would be the better solution.

**Comment by danielegobbetti** [comment]
You can do it with the [dashboard](https://github.com/C-D-Lewis/dashboard) pebble app and its android companion. These are now open source and work with Gadgetbridge. I am therefore closing this.

**Comment by IzzySoft** [comment]
@danielegobbetti actually, I'd prefer not to install another app for that simple feature – especially not if I don't need all the other features, and it comes with a bunch of permissions required not needed for the only function I want. We already have "find my Pebble" in GB, so if it's not too complicated to implement the counter-part, I'd rather welcome that.
