### ISSUE TITLE
wrong deep sleep detection

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#284]
I have juste seen a notification on my screen: "deep sleep is only supported with firmware 1.11.

But I should not see it because I have 1.11.1 on my watch.

**Comment by danielegobbetti** [comment]
Do you see deep sleep in the chart?

**Comment by roidelapluie** [comment]
yes

**Comment by danielegobbetti** [comment]
So there is nothing wrong.

**Comment by roidelapluie** [comment]
I should not see the error message.

**Comment by danielegobbetti** [comment]
It's not an error message, what makes you think it is?

**Comment by roidelapluie** [comment]
Because it showed up on my screen. I was not even in Gadgetbridge when I saw it. I would expect that if the formware version is 1.11 then the message does not appear.

**Comment by cpfeiffer** [comment]
It's about firmware 3.11 (and upwards), not 1.11.
