### ISSUE TITLE
Problem with updating mi1s 

### ISSUE THREAD

**Issue by Sanitar2034** [Freeyourgadget/Gadgetbridge#287]
Hi everyone, I try to install firmware 

Model 1S (white LEDs + heart rate sensor): Mili_hr.fw
04.15.12.10 - 24d8b84f8964489b893d1cb4581dc85f

But I get error. See log below 

Hr version shows 0.0.0.0
![screenshot_2016-04-17-02-31-36](https://cloud.githubusercontent.com/assets/18514867/14588232/9fbd3e42-04cc-11e6-82e5-d5bce9dc5640.png)

[gadgetbridge.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/222712/gadgetbridge.log.txt)

**Comment by cpfeiffer** [comment]
Do I understand this right that you are currently having fw version 4.16.3.7 and want to downgrade to 4.5.12.10?
Or did you actually attempt to upgrade or downgrade and it didn't work? Do you have any error message or log?

**Comment by Sanitar2034** [comment]
Yes, you are right. Some days ago I installed original 2.0.0 Google mi fit (automatically updated). And now Hart rate sensor don't work. As you can see,  every app says,  that I have hr version 0.0.0.0. 
I tried to downgrade, install the same software. I have only one error message "problem with sending Metadata" 

I think problem with sending software (or getting it by mi1s). 

![screenshot_2016-04-17-21-25-09](https://cloud.githubusercontent.com/assets/18514867/14589108/e6bc4250-04e2-11e6-8c43-993faaec70f2.png)


Where write "проблема" - message about problem on Russian :)  
Hope you understand my mind) 
About logs - I've already attached it)

**Comment by Sanitar2034** [comment]
![screenshot_2016-04-17-21-33-59](https://cloud.githubusercontent.com/assets/18514867/14589174/494ea38a-04e4-11e6-84f1-14e103268110.png)
[gadgetbridge2.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/222798/gadgetbridge2.log.txt)



I changed system language, think it will be better for you)

**Comment by cpfeiffer** [comment]
Alright, thanks. Don't worry, we'll get it back to a working state, if you are a little patient.

And the heart rate sensor doesn't even work with the original Mi Fit app?

**Comment by Sanitar2034** [comment]
Yes, the heart rate sensor doesn't work with original MI fit (all versions) nor with other apps (gadgetbridge return answer 0, when I try to use sensor)

**Comment by cpfeiffer** [comment]
Too bad that they break the firmware that bad. There is hope that they will fix it themselves with a new version, though.

Looking at your log, I see that the first time you could successfully initiate the hr firmware downgrade, alas the band rejected it when it had received all data. Why it rejected the data, I don't know, maybe there was a transmission error, although I doubt that. Maybe it was because we cannot recognize the current version of the hr firmware (0.0.0.0), but I think the band should reject the update early then, i.e. before sending all the firmware data.

Did Gadgetbridge show the proper hr version initially or did it show 0.0.0.0 right on?

**Comment by Sanitar2034** [comment]
Initially, the original application MI fit  broke the firmware hr. And now it always shown as 0.0.0.0.

Maybe problem in the version of fw? Maybe the band won't update because of bag in this FW version? What if I update FW first and then try to update HR?

**Comment by cpfeiffer** [comment]
If you can build Gadgetbridge yourself, here's a patch:
[patch.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/222842/patch.txt)
With that change, only the Mi Band firmware will be updated, the heart rate firmware will be kept.

**Comment by Sanitar2034** [comment]
Oh, I waste about 11 hours for compiling :( (first time compiling git project on slow pc :) )  I do not use your patch, because it didn't compiling successful. So I just find double updation function  and send first the SW update and then HR. 

So now I downgrade SW version, but HR isn't still update.  I install normal version of gadgetbridge (0.94) and try to update HR first, but there are the same error. 

I attach log file from compiled program, where SW update was successful

**Comment by cpfeiffer** [comment]
Didn't have a look at your log yet, but if the hr firmware still shows 0.0.0.0 (moist likely) the band should reject any update of it.

We first need to find out the actual hr firmware version and encode that into the firmware meta info that we send at the beginning of the update operation.

**Comment by cpfeiffer** [comment]
Downgrade might work if you manually hack the code to return hr firmware version 1.3.76.18 (that's the one you should be running, as seen in your second screenshot). Then the band should not reject the update.

**Comment by cpfeiffer** [comment]
Maybe there is something else wrong, after all. I just wanted to mark your firmware version as not recommended in our wiki, but @6arms1leg already added it a few days ago, and marked it as working fine!

So according to @6arms1leg the band works fine, including heart rate measurement. It looks like your band somehow got broken during the firmware upgrade with Mi Fit..

I actually have similar symptons with a Mi Band 1, where activity tracking is broken. Also the firmware version cannot be recognized anymore and firmware update does not work.

**Comment by Sanitar2034** [comment]
No, my band don't want update HR version to 1.3.76.18. It seems that my band has broken  heart rate sensor. Or maybe inside wires disunited and MI band doesn't see sensor. I think I just buy new MI band and disassembling that.  Anyway HR sensor doesn't work normal.

**Comment by cpfeiffer** [comment]
Comparing to my broken Mi 1, where the fw cannot be recognized or updated, the activity sensor does work (live activity tracking works fine), but downloading the daily activity data fails, all values are 0.

Weird.

**Comment by cpfeiffer** [comment]
So for now I'll close this as wontfix "broken device" (not by Gadgetbridge!), if you have any other input, just comment.

**Comment by ashimokawa** [comment]
@cpfeiffer and me today found another possible cause of the problem. We have one phone that can update the fw and another which cannot. With the same Mi 1S.

So it is worth to try with another phone. Not a solution, but better than nothing.

**Comment by cpfeiffer** [comment]
For completeness, the phone that **could not perform** the firmware update was a Galaxy S4 mini (not neo), and the one that **could perform** the update was a One Plus One.

**Comment by Sanitar2034** [comment]
May be it's a variant. I have samsung galaxy s4 i9506.  But I've tried to install from another device - samsung galaxy note pro (tablet). It couldn't too.  Yesterday I disassembling xiaomi mi band and found that pulse sensor was disconnected (it seems it's happened after MI band fall down from my arm).  Of course I connect and trying now to charge.  May be I broke something, while disassembling :)  So it was hardware problem. 

Xiaomi create good device, but I get bugged one.  They could secured the port much better)

**Comment by ashimokawa** [comment]
I was able to flash the firmware only when enabling the "low-latency mode" (now a dev setting in master).

The phone is a S4 mini LTE (i9195) running cm13

**Comment by allevor** [comment]
Hi.

I have related problem - I can't update HR monitor firmware.
When firmware upgrade status aproximately 95%, Mi band was disconnected and firmware process stay freeze.
Then Mi band don't connect with my phone until i freeze it in refrigirator.
I don't uderstand what's happened...
Any instructions was i saw can't help me.
Maybe my log file below can answer on this question.
Could you help me, plz!

Mi band 1S:
FW: 4.16.4.22
HR: 0.0.0.0
HW: 1S
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1954986/gadgetbridge.log)

**Comment by IzzySoft** [comment]
With the original problem solved, I'm closing this issue.

@allevor if your problem still persists, and you've checked above solution to rule out that's your culprit, please try [a newer firmware](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Update#mi-band-1s-firmwares) (4.16.11.15 is already listed behind that link) and, if needed, open a new issue *referencing this one.* Thanks.
