### ISSUE TITLE
music control with miband

### ISSUE THREAD

**Issue by Lhemamou** [Freeyourgadget/Gadgetbridge#289]
Hi guys,
I am wondering if music control is possible by tapping on the device. It can be a good tool !
I can try to help you on this project if you need one more people :)

Thanks for all your work ! It's really great !

Léo

**Comment by cpfeiffer** [comment]
Hi Léo,

helping hands are most welcome! Feel free to pick any open issue that interests you :-)

For this specific feature request, I will have to disappoint you though: so far there is no possibility to get notified when tapping on the Mi Band. See #63 for a bit of related discussion.

This might change for the anticipated Mi Band 2 and/or the Xiaomi Smart Watch.

**Comment by cpfeiffer** [comment]
I'll close this with wontfix, since sadly it's pretty much impossible to do with current Mi Bands/firmware.
