### ISSUE TITLE
Wiki Refactoring

### ISSUE THREAD

**Issue by rd999** [Freeyourgadget/Gadgetbridge#294]
Hi again. I don't know how much I can contribute but at least I figured out how to create a Sidebar in GitHub Wikis. So I want to start a discussion about the new structure, which is currently the more or less old one too.

Please have a look at the fork at https://github.com/rd999/Gadgetbridge/wiki and post your opinion here. I can move it over when all are happy with it.

In the FAQ section I would then add e.g. a description about Fixed Alarms.
Similar things can be added their too to help users operate the app.

Best regards
rd999

**Comment by cpfeiffer** [comment]
This is great! I always hated the flat structure of the wiki pages, but didn't know how to change that. Excellent idea to provide structure with a custom sidebar.

There's probably a lot of room for improvement regarding the wiki pages. E.g. the "Home" page could hardly be worse :-}

A "Development" section would be good, with the entries "Developer Documentation" and "How to Release".

Thanks a lot!

**Comment by rd999** [comment]
Can someone upload any useful icon that I can put into the sidebar please instead the current one please. Currently I've and absolute link to f-droid in use. But that's not a good approach.
And I don't have git installed and at least web upload is disable for my account.

**Comment by cpfeiffer** [comment]
Great job, thank you very much!

I'll see if we can directly link the icon from the git repository. The wiki is editable for everyone, I'm surprised that image upload is forbidden.

**Comment by danielegobbetti** [comment]
I suggest we move to #322, hence I am closing this. Sorry @rd999 I should have noticed before and do the opposite, but the discussion there moved forward in the meantime.
