### ISSUE TITLE
Alarms on Mi Band 1A

### ISSUE THREAD

**Issue by elroncio** [Freeyourgadget/Gadgetbridge#297]
I can't set any alarm on my Mi Band 1A. (Now I'm from mobile, tomorrow I'll give you more info and a screenshot)

**Comment by cpfeiffer** [comment]
You need to long-press the device item and choose "Set Alarms". Make sure your band is connected before.

Also check the firmware section in the wiki; some firmware versions are buggy and don't support alarms.

**Comment by cpfeiffer** [comment]
Since there's no feedback, I'll close this. If this is still a problem, feel free to add a comment and I'll reopen it.
