### ISSUE TITLE
can't install on CM11 via F-Droid

### ISSUE THREAD

**Issue by droopy4096** [Freeyourgadget/Gadgetbridge#299]
ever since 0.7.x I haven't been able to update my gadgetBridge to any of the new versions. I have uninstalled it from the phone and attempted "fresh" install with no success. I'm getting "Failed to install due to an unknown error"

**Comment by ashimokawa** [comment]
Remove original pebble app.
GB can no longer coexist with the original app (it can with the pebble time app)

**Comment by cpfeiffer** [comment]
Can you provide a logcat of the installation process?

**Comment by cpfeiffer** [comment]
You could also download the apk manually and install it via ‘adb install XXX.apk‘ from a PC. Maybe that makes a difference or gives a clue.

**Comment by droopy4096** [comment]
As per @ashimokawa - I have removed pebble app which has resolved the issue. However it is odd that conflict occurs when original app is frozen with TitaniumBackup.
