### ISSUE TITLE
MI Band: support for firmware update

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#30]
It would be great if it was possible to update the MI firmware with Gadgetbridge.

**Comment by danielegobbetti** [comment]
I forgot to mention the issue in my commit, but there is a [branch](https://github.com/Freeyourgadget/Gadgetbridge/tree/firmware_update) capable of uploading a firmware to the miband.

**It works but its usage is currently highly discouraged to users that are not ready to (potentially) brick their miband!**

**Comment by ashimokawa** [comment]
Merged in master. But still discouraged to use I guess ;)

**Comment by danielegobbetti** [comment]
Feature landed with version 0.4.5

**Comment by 6arms1leg** [comment]
Sorry, if this is a dumb question, but where in the app (I'm using version 0.4.6 right now) can I find this feature?
I have checked all menus and can't find any option for a firmware update...

Thanks for your help!

**Comment by janvonde** [comment]
would be awesome if there could be some firmware files in the repository to switch with as well ;)

**Comment by danielegobbetti** [comment]
@6arms1leg if you open a .fw file from any file manager the firmware update activity should be started.
@janvonde this is not going to happen unless there is a free-as-in-freedom firmware that can be shared by us

**Comment by 6arms1leg** [comment]
Hello @danielegobbetti.

Thanks for your fast reply. Since that feature is quite hidden, I dared to add a [section to the User Documentation in your wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki/User-Documentation). I hope that is OK.

**Comment by danielegobbetti** [comment]
Thanks for doing that. And if you happen to install a non-whitelisted firmware please let us know the number that will be shown by the installer activity, so that we can add it!
--

**Comment by 6arms1leg** [comment]
I would like to try out some other firmwares (and test them with Gadgetbridge), but actually I don't know where to get the firmware files.
Is there a place where I can grab those firmware files for the Mi Band?
BTW, I just noticed that a new app release is out. How long does it usually take until it's available in F-Droid?

**Comment by danielegobbetti** [comment]
Regarding fdroid it usually takes less than one day from the release until the app is updated (the new release is now available btw).

Regarding firmwares as said we can't really share them, the official app comes with a bundled firmware, you might find it in the assets directory after you unpack it.

There are also some other repositories here on github that host copies of the firmware. 

In both cases the firmware is usually a file whose name is mili.fw

HTH

**Comment by 6arms1leg** [comment]
> [...] if you happen to install a non-whitelisted firmware please let us know the number that will be shown by the installer activity, so that we can add it!

OK, I tested some firmwares and [added the information to the wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki/MiBand-Firmwares-information).
The firmware installer works very smoothly. Great job!

**Comment by cpfeiffer** [comment]
Awesome! I guess I'll try one of the 1.10 versions soon.

**Comment by danielegobbetti** [comment]
I forgot to add the row to the template, but if you could also add the number shown by the fw installer activity to the wiki we can Whitelist these firmwares.

If you don't have them available we can reconstruct those with the human readable version, so it's no big deal :)

Thanks a lot for your contribution! 
--

**Comment by 6arms1leg** [comment]
Sorry, totally forgot about that! I added that information to the wiki now, too.

**Comment by chrisvella** [comment]
Do we have a firmware version officially recommended by the project?
@6arms1leg did you find a version that worked best? I know that's a
difficult question to answer.

**Comment by danielegobbetti** [comment]
@6arms1leg thanks! The new firmwares will be whitelisted in the next version of  Gadgetbridge.
@chrisvella I am fairly happy with 1.0.10.11 at the moment.

**Comment by 6arms1leg** [comment]
@chrisvella, I prefer 10.0.10.14. As I wrote in the Wiki:
> Connecting and synchronizing seems to be slightly faster and more reliable than with previous firmware versions.

**Comment by danielegobbetti** [comment]
Hi I just write to let you know that 1.0.10.14 is not vibrating for notifications!

I'm unable to test what doesn't work atm but I read this was a common issue for third party apps when the new fw came out.

I advise to avoid this version if you need the notifications to work (alarms, activity tracking, etc seem to work well with this fw).

**Comment by 6arms1leg** [comment]
@danielegobbetti, thanks for the heads-up!
Sorry, I missed that as I personally don't use the notifications feature. I added a note to the wiki.
