### ISSUE TITLE
No log files are written in Marshmallow

### ISSUE THREAD

**Issue by testman86** [Freeyourgadget/Gadgetbridge#304]
I enabled logs in settings but on sdcard no log files are written. On my z1C with Lollipop everything is working fine (CM12.1).
I closed Gadgetbridge with the close button in the pull down menu and I also tried in Android apps settings and did a force close and then reboot phone but still no logfiles are written. I am using CM13 last Snapshot on a Motorola Nexus 6.
Any hint or idea? Do you need more information about this issue or is it known?

**Comment by cpfeiffer** [comment]
I suppose this is already fixed with #300, although it should be the same problem on Lollipop and Marshmellow. The fix is about to be released with the next version.

**Comment by cpfeiffer** [comment]
(If it's still an issue after the next release, or, if you can build yourself, you can try the fix right now, please reopen.)

**Comment by testman86** [comment]
I can confirm that with 0.9.7 the issue is fixed at least on CM13 Nexus 6.

**Comment by cpfeiffer** [comment]
Thanks for confirming!
