### ISSUE TITLE
Feature request: Implementation of Notification silence times

### ISSUE THREAD

**Issue by DarkSpir** [Freeyourgadget/Gadgetbridge#308]
Hey team,

I get notifications sent to my Miband via various apps. That's fine and intented during the day. But: When somebody sends me eMails during the night, I will get notified and wake up most of the time. I can prevent this when I remember to switch off the notifications in the evening and remember to switch them on again after I wake up.

Can you implement a setting where one can define a "ignore notifications" timeframe? For example monday to friday from 10pm until 6am and saturday/sunday from 10pm until 9am?

**Comment by danielegobbetti** [comment]
Worked on in #306
