### ISSUE TITLE
Completely uninstall apps/watchfaces

### ISSUE THREAD

**Issue by IzzySoft** [Freeyourgadget/Gadgetbridge#309]
When tapping the connected device (a *Pebble Time Steel* in my case), we can uninstall Pebble apps and watchfaces by long-tapping their entry and chose to "uninstall". However, they are still listed in GB – and moreover, from that list it's impossible to tell whether any of those apps/watchfaces is really installed on the watch or just in GB's cache. So may I suggest two things:

1. add another option to "completely remove" an app/watchface (i.e. from the watch *and* GB). This shouldn't be too hard to do: the item then would be uninstalled from the watch and removed from GB cache, so it's no longer listed in any of the two places.
1. Make it visible whether an app/watchface listed in GB is also installed on the device. Now that's not so easy to accomplish (as IMHO there's no way to read installed items from the Pebble), so we might need a work-around. I could think of an additional "property" stored with the cache, let's name it `on_device` here:
    * if an item is installed on the watch, set `on_device=1`
    * if an item is uninstalled via GB, change it to `on_device=0`
    * as some folks might change the status via e.g. the original Pebble app, give them an option to toggle the state here (e.g. a "Mark installed"/"Mark uninstalled" item in the context menu)
    * if `on_device==0`, show the item grayed-out in the list to reflect this
    * to avoid confusion (if you think it would cause any), the entire thing could be made an "opt-in feature" (e.g. via the "dangerous options")

I'd see numer 1 as a "must-have" (we certainly cannot expect users clearing files from the cache manually), and number 2 as a "really nice to have" (the latter as I expect your complaints concerning the difficulties involved ;).

**Comment by ashimokawa** [comment]
I agree on 1 at least ;)
Plus it is not a hard task. Let me close 2 bugs before working on this.

**Comment by IzzySoft** [comment]
@ashimokawa I was pretty sure to find agreement on 1 – and expected 2 to be not taken that easy. Also, it's the more important item of the two :)

Still hoping for 2 to be at least *considered*. It's not an issue if you just install 4-5 items and keep them – but with the list growing and having to "switch out" items (AFAIK there was a limitation on how many items can be installed on a Peppble simultaneously), it would be very helpful to see the "current state".

**Comment by ashimokawa** [comment]
I implemented 1 and 2 for firmware 2.x as we can actually get a list of installed apps there (unfortunately not on firmware 3.x)

Also about 2, your proposal has to be a bit more sophisticated because people might have multiple pebbles, so we need to know on which devices a file had been installed in the past...

Anyway I will close this because actually I did was the issue said and there is #93 which deals about improvements to the app manager on firmware 3.x.

Please continue discussion there ;)

**Comment by IzzySoft** [comment]
Thanks a lot! Last comment on 2 here (as it's lacking the context over there): As it wasn't known before it's implemented, it's clear the state isn't known initially. So existing 3.x users would have to toggle once where needed :) Starting with that, the state could be stored (database) per device. Only tricky thing I see here is if people switch beetween GB and the official app *and doing changes on both ends*.

**Comment by IzzySoft** [comment]
Quick feedback: Complete uninstall works now with todays update (v0.9.8) – thanks a lot! Looks cleaner now :) So consider 1. solved. I'll now copy over 2. to the referenced issue, so it doesn't get lost.
