### ISSUE TITLE
Add support for angelsensor

### ISSUE THREAD

**Issue by ossasens** [Freeyourgadget/Gadgetbridge#310]
The angelsensor band was a crowdsourced device with open specifications. (www.angelsensor.com)

Please, add support for this device.

**Comment by ashimokawa** [comment]
I will review the possibility.
Will get my hands on one of these soon.

**Comment by ashimokawa** [comment]
@ossasens 
Have such a band here now but it seems broken.
Just blinks when in the cradle and makes funny clicking nose. So don't hold your breath for angelsensor support.

**Comment by ossasens** [comment]
give it a second try. mine seems to "hang" sometimes for unknown reasons.

**Comment by ashimokawa** [comment]
@ossasens 
I gave it 20 tries with different power supplies, its just broken. Actually I wasted the whole evening trying to get it working desperately.

The "demo app" shows battery 0% and disconnects in the same instant as the LED goes off.
It does not charge, just flashes. Pressing the button for about 10 seconds lets the leds light up constantly. If I remov it from the "cradle" (its the worst construction I have ever seen in my whole life), power is off, If it let the button go, it starts flashing and clicking like a broken hard disk. Seriously.

**Comment by ossasens** [comment]
Mine is working but seems to be still a bit unstable.If you can add the skeleton of a new device I might be able to start working on the different sensors and possibilities and testing them with my device. But I have tried and I don't know how to add a new device in all your code.

**Comment by cpfeiffer** [comment]
I can do this, maybe on Sunday. You might have a look at the Dev section in the wiki, there's a small overview diagram and the most important classes.

Basically you need a DeviceCoordinator implementation (sorry for the naming), which handles the device specific ui, logic and behavior. And a DeviceSupport implementation which handles the communication part. Choose an appropriate superclass, most probably the BLE one.

And there is a little bit of glue code here and there, especially for the instantiation but it should not be much.

**Comment by danielegobbetti** [comment]
Since this is more in providing support for additional devices, I'm going to close this and kindly invite you to move to #50 . When things get more concrete, a Pull Request specific for the Angel Sensor would of course be more than welcome.
I am closing this issue as WONTFIX as no core dev has a working device to add support.

**Comment by ossasens** [comment]
Well cpfeiffer said he may work on it. If someone can add a basic structure for a new device I can work on it, but i'm not able to work it out from scratch.

**Comment by cpfeiffer** [comment]
Right, I'll do that.

**Comment by cellscape** [comment]
@cpfeiffer any news? I've started tinkering with the code (so far got device connected and battery level present in UI) but was wondering maybe you already have something implemented?

**Comment by cpfeiffer** [comment]
@cellscape sorry, I got absorbed by #349 

Now that this is solved, I can have a look at this. Can I help you with your code? Do you have questions? How do we want to proceed?

**Comment by cellscape** [comment]
Well I have questions because it's my first experience with bluetooth and I'm not an Android developer. I'm currently a bit busy, will push my wip branch later this week. It's really basic though, only device detection, paring and reading some device info and battery. I've also got some raw data from heart sensor but no UI/parsing yet. 

I'm not sure how to proceed further. I don't think I have enough time/experience to fully work on it. Perhaps I could work on it in background mode, learning things in process, asking you about some stuff.

**Comment by cpfeiffer** [comment]
We joined this project just like you do, without knowledge of Android or Bluetooth, so welcome to the club :-)

If you're comfortable to work in your own branch, that's fine. You can send pull requests for changes that you need in Gadgetbridge (I'm sure that this will be the case). And if you have questions or need help, we could have an xmpp/jabber group. Or we could set up a mailinglist.

**Comment by cellscape** [comment]
Took some time to get back to it but I've finally pushed some [commits](/cellscape/Gadgetbridge/tree/angel-sensor).  

Currently it's in very basic state, to play around with. I'm able to successfully pair with device, get battery level and firmware info. Other than that it will also log notifications for heart rate and temperature changes. To enable heart rate readings one have to hold button on band for couple of seconds until device vibrates.

However there is one large issue: reading from Health Journal doesn't work for me. Trying to write to corresponding control point results in error with code 0x9F, [official documentation](http://angelsensor.com/protocols/seraphim-sense/health-journal-service/) says it's some kind of "Generic/unspecified error".

I've tried various opcodes and operators, nothing seem to work, almost always get that error. Exceptions are "Op code not supported" for unsupported opcode and "Client Characteristic Configuration Descriptor improperly configured, either notifications or indications must be on" if I don't enable notifications on corresponding Health Journal characteristics.

It could be that my device is broken but most likely it's just unfinished firmware. Shame. I'll try to write to support but it seems company is pretty much dead. 

Now the question: anyone is still interested in some kind of support for that device? Personally for me it's no use without Health Journal. 

It's still possible to get some readings in real time (heart rate, activity, step counter) but how to use this? Out of my head one could enable real time readings for night and track sleep with heart rate and movement but is it worth it? Battery would discharge pretty fast in such mode so it's not convenient. 

It should be also possible to setup alarms, is anyone interested in that?

**Comment by cellscape** [comment]
Well it's no use currently, only to check battery level or watch something logged. If you merge this now then it will take it's toll to support i.e. when refactoring or adding new interfaces. Not sure it's worth it. 

I'm thinking towards having some activity to show current sensor reading and maybe sleep tracking in real time mode. I'll prepare pull request when it will be at least somehow useful.

**Comment by ashimokawa** [comment]
@cellscape 
There is a "live activity" activity already in Gadgetbridge. You can use that for realtime steps and heartrate.
It is currently used by Mi Band.

**Comment by IzzySoft** [comment]
With Angelsensor [having shut down](https://www.mobihealthnews.com/content/open-source-wearable-angel-shuts-down) in 12/2016, devlopment of [their SDK](https://github.com/AngelSensor/angel-sdk) being stopped at about the same time, their website having disappeared altogether, the device not being that popular, and the last comment here being even older (almost 3 years old), it's IMHO safe to assume there's no(t enough) interest to keep this request open. Should I be mistaken, I stand corrected and reopen the issue.
