### ISSUE TITLE
Pebble Time Steel: no deepsleep data?

### ISSUE THREAD

**Issue by IzzySoft** [Freeyourgadget/Gadgetbridge#312]
I know sleep rhythm varies. But having it recorded for 3 nights now, I'm a bit irritated: GB shows sleep data, yes – but not a single minute of deep sleep cannot be true. The "round graph" explicitly shows the full sleep time as "light sleep" (from the numbers; there's a small light-blue circle embedded nevertheless), and in the "bar graph" I wasn't able to spot "deep sleep bars" either.

Is it just me? Is it the watch not giving those details correctly? Or is it GB not interpreting it correctly? Can anyone confirm this for a *Pebble Time Steel?*

**Comment by danielegobbetti** [comment]
Sorry that you are feeling irritated, but we can't help for that.
The deep sleep data is sent only from firmware 3.11 onwards, before (i.e. firmware 3.10) we only got generic sleep data, we miss the firmware version in your bug report to be sure if this is a bug at all.

I can confirm that this works for pebble time, for pebble time steel we miss the hardware to tell ( *wink* *wink* ).

If you are using fw > 3.11 please check your logs and send the rows containing the string
DATALOG (health - sleep
Check our wiki to understand what's contained and decide if you're willing to share these.

**Comment by IzzySoft** [comment]
OK, sorry for being incomplete: FW is 3.12.

<pre>
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.DatalogSessionHealthSleep( 1197): DATALOG (health - sleep 84 )03001A000100201C000004FA4057002D0000000000000000000003001A000200201C0000CC04415728050000000000000000000003001A000200201C0000300A4157C0120000000000000000000003001A000100201C000098294157D8180000000000000000000003001A000200201C0000B42B4157BC070000000000000000000003001A000100201C000004454157F4290000000000000000000003001A000200201C0000485B4157000F00000000000000000000
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol( 1197): sending NACK (0x86)
[...]
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.DatalogSessionHealthSleep( 1197): DATALOG (health - sleep 84 )03001A000100201C000004FA4057002D0000000000000000000003001A000200201C0000CC04415728050000000000000000000003001A000200201C0000300A4157C0120000000000000000000003001A000100201C000098294157D8180000000000000000000003001A000200201C0000B42B4157BC070000000000000000000003001A000100201C000004454157F4290000000000000000000003001A000200201C0000485B4157000F00000000000000000000
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol( 1197): sending NACK (0x86)
[...]
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.DatalogSessionHealthSleep( 1197): DATALOG (health - sleep 84 )03001A000100201C000004FA4057002D0000000000000000000003001A000200201C0000CC04415728050000000000000000000003001A000200201C0000300A4157C0120000000000000000000003001A000100201C000098294157D8180000000000000000000003001A000200201C0000B42B4157BC070000000000000000000003001A000100201C000004454157F4290000000000000000000003001A000200201C0000485B4157000F00000000000000000000
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol( 1197): sending NACK (0x86)
</pre>

I'm not a dev, but the `NACK` irritates me (I had expected an `ACK` at least once).

And sorry that I cannot donate a PTS to you :)

**Comment by danielegobbetti** [comment]
Thanks for the logs, can you please tell me if you see rows for sleep data with type 83 instead of 84 (that's the old record type with only shallow sleep).
The fact that we NACK the data means we can fix this, so don't be irritated :)
I'll loom at your data later today!

**Comment by IzzySoft** [comment]
Thanks, @danielegobbetti – and I've included *all* lines matching `DATALOG (health - sleep` from logcat. If the full log would help you, please tell me a "private place" so I'll upload it. I've just grepped the log for `sleep 8`, all I can see are those `sleep 84` lines, no 83.

**Comment by danielegobbetti** [comment]
I completely overlooked the fact that firmware 3.12 introduced a new record version for these catalog messages.
Current master can parse these correctly, at least for the sleep-related data.
There are further message content that we don't know how to decode yet, and are discarded. I guess they are related to the running/high activity information that is now displayed in the official app, or it could be nap-time... Time will tell :)

**Comment by IzzySoft** [comment]
Cool, thanks! So in short (just to confirm I got it right): With the next release it should work then (and show shallow *and* deep sleep data)?

BTW: I just found where the Pebble itself shows sleep data (by accident, oops). Full amount of sleep time matches with what GB shows (vaguely remember you asked me somewhere for that ;)

**Comment by danielegobbetti** [comment]
That's the plan 😀

As an added bonus, you should see the data also for some past days, as they were nacked by GB.

**Comment by IzzySoft** [comment]
Amazing! Can't wait to get the update (but no, I won't push for it – it's ready when it's ready :innocent:)

**Comment by ashimokawa** [comment]
Our current plan is to tag this evening (CEST)
If f-droid builds us fast, the update will pop up tomorrow ;)

**Comment by IzzySoft** [comment]
@ashimokawa Yupp, 24h window usually (as with [my repo](https://android.izzysoft.de/repo)). That's great news, thanks!

**Comment by danielegobbetti** [comment]
New version is out on fdroid and everything should be working.

**Comment by IzzySoft** [comment]
@danielegobbetti Yupp, I've updated yesterday. Just wanted to check health data now, but: "Waiting for connection"<sup>**1**</sup>. Had to tap the Pebble entry to connect it again. Which means now it can take a little until last night's data arrive...

As usual, it took a while until the Pebble decided to send the correct package: For the last night, correct data now arrived, and deep sleep turned up! Huray! Thanks a million!

----

<sup>**1**</sup>  ouch, and the Pebble drained by 50% overnight?!? Two bars in 8h? Note: at night, my phone goes to airplane mode and comes back in the morning. So if that drain comes from connection attempts since "network restore", it would mean 50% within less than 4h. I had 3 bars battery when I went to bed, now 1 bar is left (full=4 bars). Might be coincidence, I couldn't find any indicator in the logs. As connection issues are involved here, this part might belong to #296 ?

**Comment by danielegobbetti** [comment]
@IzzySoft if you just started wearing your pebble at night, I highly suggest to turn off the setting that turns backlight on with movements, because it works also at night.

**Comment by IzzySoft** [comment]
@danielegobbetti  yeah, I've already noticed that. But I find that setting quite useful. If you think it might have caused the drain (good point), I wonder why it happened for the first time last night.

Speaking of this: Can those settings be triggered remotely (i.e. could GB do that)? If so, my next question would be for Tasker support. My "bedtime task" (which currently activates silent mode and sends the device into airplane mode) could then also trigger that – as well as maybe telling GB to "sleep" and later to wake up again and reconnect :)

**Comment by danielegobbetti** [comment]
It's highly unlikely, and certainly undocumented :(

**Comment by IzzySoft** [comment]
I was afraid of that. If there's no such setting in the official Pebble app, chances are indeed quite low we could figure it out. Thanks nevertheless, was worth asking for.

As for the issue: I'll fully charge my Pebble before going to bed tonight. Cleaned up some unnecessary stuff from my phone, so I will restart it as well for a "clean state", and connect the Pebble once manually. Then let's see tomorrow morning if the drain repeated. Nevertheless, this rather not belongs here but to the other issue I've linked (reconnection issues) – so we should continue it there :)

**Comment by tecufanujacu** [comment]
I'm using a pebble classic updated at fw 3.12 with misfit 3.7.
I see that Misfit give me the sleep time and the deep sleep time but in GadgetBridge I see only the total sleep time, can be possible to manage these data from misfit?
(A little off topic, can be possible to manage the goals for the steps and for the sleep of Misfit?)

**Comment by ashimokawa** [comment]
@tecufanujacu 
Completely offtopic but:

- The data from Misfit does not contain any information about deep sleep, it seems is is calculated by some unknown algorithm on the pebble (and on misfits servers).

- It is technically possible to send the goals to the pebble, I know how I could implement it but it is not high-priority.
