### ISSUE TITLE
Cooperate with Gliderun

### ISSUE THREAD

**Issue by v1r0x** [Freeyourgadget/Gadgetbridge#313]
A while ago I searched for an alternative to mifit and one of the first apps I found was [gliderun](http://forum.xda-developers.com/android/apps-games/app-gliderun-alpha-t3057985) but I switched to your app. And I'm still happy with this decision, but I think gliderun sometimes had more precise results (not always) and maybe you can learn something from gliderun and vice versa. I think one good app is much better than two good apps which have their benefits and users have to decide which feature they want/have to give up because they can not have all of them.

**Comment by danielegobbetti** [comment]
By a quick look of the link you posted and an online search, I believe gliderun isn't released under a free software license.
Our code is here and we are open to contributions, but I'm closing this issue as wontfix.

**Comment by v1r0x** [comment]
I understand your demand for a free software license, but I couldn't find a license nor a statement against a free license. I just thought that I let you know there are other people working on something and maybe the license "problem" could be fixed if both app devs talk to each other.

**Comment by danielegobbetti** [comment]
@v1r0x I understand your position and appreciate your optimism. If you want, please reach out to the gliderun dev and tell him that we are *very* open to collaboration, as long as it happens in the public and the outcome is free software.
