### ISSUE TITLE
Synchronization on FW 1.0.9.27

### ISSUE THREAD

**Issue by m-altmeyer** [Freeyourgadget/Gadgetbridge#314]
Hey all,
First of all sorry for creating an issue as this request does not relate to a bug in your code but is rather a more general question. I am also trying to read/write data from/to the MiBand since I want to use this tracker for research purposes. I'm currently trying to implement an android service that offers an API to talk to the MiBand. Everything is working fine besides synchronizing. I thought it should somehow work in a similar way as reading the realtime steps and implemented it in the same fashion: I write 0x6 to Charactersitic FF05 (Control Point) to start the sync process. I would expect to get notified on characteristic FF07 but nothing happens. I tried your app and synchronization worked perfectly (you really did a great job with this app), so I was looking at your code but as far as I can say, it seems like you did the same. Is there anything to consider? Do you have any advices for me? I am using FW 1.0.9.27 and the 'old' colorful LED wristband.

As soon as I have finished the implementation of the synchronization process I also want to publish my code on github and make it available for others (I would acknowledge your project of course).

Again, sorry for creating an issue and thank you very much in advance!

**Comment by cpfeiffer** [comment]
Yes, that's basically it. Did you register for notifications on characteristic 0x7?

**Comment by cpfeiffer** [comment]
I'll close this for now, please just add comments when you have/need more info.
