### ISSUE TITLE
[Pebble] Feature request: add support for the fitness tracker UpTempo

### ISSUE THREAD

**Issue by tecufanujacu** [Freeyourgadget/Gadgetbridge#316]
I tested all the fitness tracker available for the Pebble Classic and the more accurate and in continuous development is [UpTempo](https://apps.getpebble.com/en_US/application/556c1dc2e42ea416be0000aa?dev_settings=true&query=uptempo&section=watchapps).

Reading the[ UpTempo's thread](https://forums.pebble.com/t/watchapp-uptempo/15075) in the pebble forum seems that this watchapp is also more accurate than the Pebble Health feature of the Pebble Time.

Can this fitness tracker be supported in GadgetBridge as for Misfit and Morpehuz?

**Comment by ashimokawa** [comment]
@tecufanujacu 
Right now this is not possible because UpTempo does not send data to the phone at all.

But thank you for pointing this out, it could become very interesting in the future because:

- The author said it will be open source
- The author said he is working on an android app.

That mean that it will work without us doing anything, but only if you use his android app.
And it also means we can store the data into Gadgetbridge's database and removing the need for the companion app.

Interesting is also that his code is based on the same code I used for my unreleased and dead Pebble App. This app already could send data to Gadgetbridge but I was not satisfied with the accuracy at all, so I just supported misfit instead.

**Comment by ashimokawa** [comment]
I am marking this as invalid for now, because right now there is nothing we could do even with superpowers ;) Please let us now if there is any progress within UpTempo which allows sending data to the phone - then we will work on it.

**Comment by tecufanujacu** [comment]
Great, I think that the companion app will be available in the near future because its developer [told](https://forums.pebble.com/t/watchapp-uptempo/15075/149?u=womubihujule) that is very active in this period and in effect soon will be available the watchapp version 0.18 to send data.

**Comment by ashimokawa** [comment]
Actually I just checked and the app already transfers some data via datalogging, I have no idea what is inside though. Also it does always display 0 for all data on my pebble, which seems like a bug.

It is best to wait until the source is released, then there is not need to analyze and guess bit patterns.

**Comment by ashimokawa** [comment]
Ok it told me I walked 41m (this is off by about 4000m) and I took 3439 steps, thats off by about 6000.
Right now, this is totally useless to me. I wonder is is a problem with the Pebble Classic.
@danielegobbetti 
Can you test?

**Comment by tecufanujacu** [comment]
@ashimokawa 
Are you testing UpTempo?
Me too I have the pebble classic and this is not a problem but this is how the watchapp works, from the store:
> It is meant to capture major daily activity and disregard insignificant hand movements and such. I advise you let it run for a day and then check back.

To avoid false positive as when writing or when driving(in these case misfit gives me a lot of false positives) the watchapp discards every little movements as when doing few little steps but I can assure that the app is really accurate during a walk or a run.

**Comment by tecufanujacu** [comment]
Just to update, the uptempo's developer the 12 june has released the version 0.19 in which he has improved phone app comunication but for now no companion app has been yet released.

**Comment by ashimokawa** [comment]
@tecufanujacu 
Please let us know when the source code has been released.

**Comment by tecufanujacu** [comment]
@ashimokawa 
Just to know, did you tested the watchapp? What do you think about it?

**Comment by ashimokawa** [comment]
@tecufanujacu 
Honestly, for me it is useless. It shows about 1/3 of my real steps. 
Further that guy violates the GPL. He used source code of On11 which is licensed under the GPL, so he has to release the source code also.
I opened an issue on his issue tracker. This is not only a technical but a legal issue.

**Comment by tecufanujacu** [comment]
Understood.
Anyway I don't think that the source code will be a problem because in the description on the pebble store he said that the app will be open source soon.

**Comment by tecufanujacu** [comment]
If still interested the uptempo's code is now published.

**Comment by tecufanujacu** [comment]
The uptempo's developer also released its android companion app:
https://forums.pebble.com/t/watchapp-uptempo/15075/156?u=womubihujule

The app is really really wonderfull, I advice everyone to test it, unfortunately the android companion app isn't able to communicate with the watchapp via Gadgetbridge.
Is there something that I can to do?

**Comment by ashimokawa** [comment]
@tecufanujacu 
The non-free (yes I have to stress this) companion app should work in 0.17.5 which should show up on f-droid in the next 24-72 hours.
I cannot guarantee that there are no bugs - but it does transfer something now.

**Comment by tecufanujacu** [comment]
@ashimokawa, sorry for the delay.
Why non-free? because not opensource?
Anyway thanks for your work, I'll test everything as soon the new version will be available on Fdroid.

**Comment by ashimokawa** [comment]
@tecufanujacu 
Not free as in freedom. We only use free and open source software. This project would not have existed otherwise ;) - we would just have installed Pebble's and Xiaomi's software.

**Comment by danielegobbetti** [comment]
0.17.5 hit fdroid, please let us know how it works now

**Comment by tecufanujacu** [comment]
@ashimokawa @danielegobbetti 
I'm testing everything from yesterday and for now everything seem to work correctly.
A question, have I to enable also the setting Prematurely ACK PebbleKit?

**Comment by danielegobbetti** [comment]
If it works without "Prematurely ACK" then it's better leaving it off. I'm closing this as everything seems to work, feel free to reopen if needed.

**Comment by danielegobbetti** [comment]
Oh, and please add the app in the wiki, if you can. Thanks! https://github.com/Freeyourgadget/Gadgetbridge/wiki/PebbleKit-Android-App-Compatibility

**Comment by tecufanujacu** [comment]
Just done, thank to you.
