### ISSUE TITLE
[Pebble] Feature request: sync pebble alarm with android alarm 

### ISSUE THREAD

**Issue by tecufanujacu** [Freeyourgadget/Gadgetbridge#317]
Could be possible a feature to sync the stock pebble alarm with the stock android alarm?

**Comment by danielegobbetti** [comment]
Unfortunately it's not possible. It **may** be that some third party alarms pebble app can be set from the phone, but this is not the case for the standard app and I don't know any that does.

**Comment by IzzySoft** [comment]
As for mentioned third party: Take a look at [Alarmist for Pebble](http://www.appbrain.com/app/caller.alarmist) which claims to sync the stock alarm with your Pebble. I've not tried it, but it sounds promising. Minimal permissions (only `SET_ALARMS` and `BIND_NOTIFICATION_LISTENER_SERVICE`). Optionally has a Watchface, too.

**Comment by ashimokawa** [comment]
It does not sync android alarms with pebble alarms. It seems it just sends a notification to the pebble when an alarm goes off (and then let you cancel, snooze from the context menu).

**Comment by IzzySoft** [comment]
Oh – OK, then I misunderstood the description. Sorry if I caused any confusion by that! Speaking about which: It seems that [Sleep as Android](https://play.google.com/store/apps/details?id=com.urbandroid.sleep) can make use of the Pebble to wake you up in a phase of shallow sleep ("Optional Pebble, Android Wear or Galaxy Gear smart watch tracking"). I know that's neither "syncing alerts", but might replace the need :)

**Comment by tecufanujacu** [comment]
I used both, sleep as android and alarmist and I don't like them also because I should install another app on the phone.
Would be great the ability to sync the alarm on the pebble with the alarm for the stock aosp clock on the phone in a similar way as alarmist does.

**Comment by JuhnHoo** [comment]
Hi tecufanujacu 

Can you send me misfit 3.2 PBW file?

I spend a lot of time searching this version to run in my pebble.

Thanks a lot

**Comment by PeterHindes** [comment]
The gadget bridge app could sent alarms to the device AND your wearable. But there is no standard for reading alarms from the stock app.

**Comment by PeterHindes** [comment]
https://developer.android.com/reference/android/provider/AlarmClock.html#ACTION_SHOW_ALARMS
