### ISSUE TITLE
Just gather the data from Mi Band

### ISSUE THREAD

**Issue by robalvsan** [Freeyourgadget/Gadgetbridge#324]
I'm a data scientist who is really interested in getting access to all the data available in the Mi Band. 

Since Xiaomi doesn't provide his users with an official API and I'm not able to extract the data from the band on my own, I've been looking for open source repositories that could help me.
I found this site and I really appreciate all your effort building and sharing this app. But what I only need is the part which involves the reverse engineering to extract the data from the band. 
I have tried to isolate that part of your code but the dependencies are too many. I think that if you could isolate the code involving the communication between the smartphone and the band from the rest of the app, that would help a great amount of data scientists like me, who are interested in analyzing this activity data.

**Comment by danielegobbetti** [comment]
The data in our database is the raw data that we read from the midband, and the database can be exported from within the app. Is the documentation on the data format not sufficient to get a clear understanding of the db contents?

Regarding cooperation with researchers, I'm glad you brought the issue on the table, we reached out to a number of sleep researchers, actigraphy experts, I personally sent tens of mails and got exactly 0 replies. As we would like to add some kind of meaningful analysis on top of the raw data we already have, we would like to know if there are well known algorithms that we can implement.

We provide each user with hers raw data, you have the expertise, let's build something good together! 😁

**Comment by fdcastro** [comment]
This might be pretty obvious because even I found it (and I wasn't even looking for this specifically), but for the sake of "building something good", it might be worth the shot.

I came across this scientific article:

http://www.psycho.hes.kyushu-u.ac.jp/~lab_miura/Kansei/Workshop/proceedings/P-205.pdf

and the authors report such an algorithm based heart rate information. Just thought it might be helpful.

**Comment by danielegobbetti** [comment]
Thanks, I missed this one (I was searching mostly papers about actigraphy, as I don't have a miband 1s).

The list of known papers is available in our wiki https://github.com/Freeyourgadget/Gadgetbridge/wiki/Activity-Analysis in the "Sources" section
