### ISSUE TITLE
Remove notifications from Pebble when read on phone

### ISSUE THREAD

**Issue by nobse** [Freeyourgadget/Gadgetbridge#326]
When I get a message (e.g. in Conversations) on my phone, I also get a notification on my Pebble Time Steel. But if I read the message on the phone, the notification stays on my Pebble and is not automatically removed. I have to remove every message manually on my Pebble. This also happens on a colleagues original Pebble, so I think this is a general issue. According to my colleague, the original Pebble App removes notifications from the Pebble if the message got read on the phone.

**Comment by ashimokawa** [comment]
It is very well possible to implement that quite easily for generic notifications.

But not for conversations. 

We rely on pebblekit notifications for conversations and these cannot be mapped to android notifications.

Conversations will merge chat messages that arrive  in a specific timespan and update the android notifications whereas the pebblekit messages are sent one by one to the pebble.

In the future conversations will have wear support, so we will switch to generic notifications for conversations and the problem could be solved.

**Comment by danielegobbetti** [comment]
Meanwhile the switch happened, so the specific conversations roadblocker is not there anymore.

**Comment by danielegobbetti** [comment]
This is working since a long time (and got broken recently, and was fixed again in #975) so I guess we can close this :)
