### ISSUE TITLE
MI Band: support for discovering MI device

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#33]
The user should be able to scan for MI devices instead of configuring the MAC address in the Debug activity.

**Comment by ashimokawa** [comment]
It would be better if the user could just pair his device

**Comment by danielegobbetti** [comment]
@ashimokawa the two things are related (discovery and pairing). The device should not be paired with the android device by the means of the system utilities (at least in android 4.4.4):
- it is not sufficient (the band is discoverable by the standard utilities until it gets paired with the app) and will remain so even after pairing.
- it creates troubles: I paired the band with the device and had the device shown in the standard bluetooth app, until I removed it I had a lot of issues like bluetooth-sharing-activity FC

Hence pairing in the traditional sense does not apply to BLE devices... that's my experience at least.

**Comment by cpfeiffer** [comment]
Interesting. I for one cannot pair the Mi Band *at all* by regular means. Attempts to do so always time out.

So, we do need to scan for devices and discover Mi Bands by their announced services.

**Comment by ashimokawa** [comment]
Pairing is still the normal procedure for BLE as far as I know.
If the Mi Band behaves strange, it is the device's fault.

**Comment by cpfeiffer** [comment]
Sure but we can't do anything about that.

**Comment by cpfeiffer** [comment]
Not pretty yet, but functional, so I'm closing this for now.
