### ISSUE TITLE
Pebble problems (notifications, firmware update)

### ISSUE THREAD

**Issue by neXyon** [Freeyourgadget/Gadgetbridge#331]
Hi,

I have the original kickstarter pebble, which currently reads:

- Firmware: v2.4.1
- Recovery: v1.5.4
- Hardware: V2R2

I also have the most recent Gadgetbridge Version from F-Droid (0.10.1).

I haven't used my Pebble for a while as you might tell from the firmware version, but I want to use it again mostly for notifications now. But exactly those are not working in this configuration unfortunately.

So I decided to upgrade the firmware and downloaded the two files here: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Firmware-updates#pebble

- 3.x-migration_v1_5_v3.8-mig10.pbz
- Pebble-3.12.1-v1_5.pbz

When I try to open the migration file on the phone, I get the following error:

```
Pebble Firmware v1_5
Hardware revision mismatch!
Unable to install the firmware: it doesn't match your Pebble's hardware revision.
```

Any suggestions/help what I could do? Or is the original kickstarter Pebble not supported anymore? :-/

**Comment by danielegobbetti** [comment]
I don't have the same device you have, and what I am telling you here is an information already available on [this page](http://www.pebbledev.org/wiki/Firmware_Updates/).
For your hardware version, the correct firmware file url should be contained in the JSON file available at the address:
http://pebblefw.s3.amazonaws.com/pebble/ev2_4/release-v3.8/latest.json

The two urls are:
https://pebblefw.s3.amazonaws.com/pebble/ev2_4/release-v3.8/pbz/3.x-migration_ev2_4_v3.8-mig10.pbz
https://pebblefw.s3.amazonaws.com/pebble/ev2_4/release-v3.8/pbz/Pebble-3.12.1-ev2_4.pbz

In case you want to move to the latest available version of the 2.X firmware, this is the url:
https://pebblefw.s3.amazonaws.com/pebble/ev2_4/release-v2/pbz/Pebble-2.9.1-ev2_4.pbz

Gadgetbridge will refuse to install a firmware which is not meant for your hardware (as you already experienced). In case these urls work for you, please let us know and we will update the wiki.

**Comment by neXyon** [comment]
Perfect, that worked, thanks!

For sake of debugging I updated to 2.9.1 (getting a crash message from "simplicity" but it worked anyway). With this firmware gadgetbridge worked again (the stuff in the Debug menu I tried and notifications at least). Then I installed the migration (same crash of "simplicity") and the v3 firmware. All good.

Cheers!
