### ISSUE TITLE
Double tap of refresh gets app stuck

### ISSUE THREAD

**Issue by robin13** [Freeyourgadget/Gadgetbridge#333]
If you double-click on the refresh button (it takes a while to visually register that it is doing something), the first refresh of data from the device succeeds, while the second one fails, and leaves the app locked in a "syncing" state.  Only solution I have found is to force stop the app and restart.

**Comment by cpfeiffer** [comment]
Yes, this needs to be fixed. In the meantime I suggest not to double tap the button ;-)

**Comment by cpfeiffer** [comment]
Fixed.
