### ISSUE TITLE
on version 0.10.1 still getting "waiting for incoming connection"

### ISSUE THREAD

**Issue by testman86** [Freeyourgadget/Gadgetbridge#334]
I am on MM OmniRom on a Nexus 6 and still have from time to time "waiting for incoming connection" and need manuall  tap on my pebble in Gadgetbridge to get working connection again, or toggle bluetooth either on the pebble or on my phone to get an automatic reconnect.
I will also attach all logs from the last weeks so that you can figure out what is happening.
[tmp_5889-logs381335740.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/318588/tmp_5889-logs381335740.zip)

**Comment by ashimokawa** [comment]
We cant fix that.
If you like set connection retries to 10000000000 or so.
It will retry once a minute.

**Comment by IzzySoft** [comment]
@ashimokawa 

> If you like set connection retries to 10000000000 or so.

Worth a try, but I doubt that's an "Allheilmittel". I have the same issue still some days in the morning, and it's unlikely to be the Pebble not being found (I've noticed more than once now the Pebble vibrating at 1am when my Android device switches to airplane mode – with the Android being in my office and me being in bed, so they're not too far apart). If you wish (and I remember the next time that happens), I can check logcat if there's something "clueful" showing up.

@testman86 What I usually do in those cases (faster than opening GB and toggling there) is pulling down QuickSettings, and tapping Bluetooth twice (i.e. toggling it off and back on). A second later, the Pebble showed as "connected".
