### ISSUE TITLE
Mi scale (or other scale-like devices) support?

### ISSUE THREAD

**Issue by perillamint** [Freeyourgadget/Gadgetbridge#339]
Hello, is there any interest supporting Mi scale or other scale-like devices (such as, Nintendo Wii fit balance board)?

I reverse-engineered and documented weight-measuring part of Mi scale protocol (Documentation: https://wiki.gentoo.moe/wiki/Mi-scale). It works like BLE beacon (something like iBeacon or Eddystone).

**Comment by danielegobbetti** [comment]
That's interesting! We are in the middle (well, make it 1/3 :) of a database refactoring. It's a good time to get such a feature request because we can take it into account when remodeling it!

**Comment by danielegobbetti** [comment]
FYI on your page there's a link that points to hgithub instead of github.com
Hgithub seems a rogue / adserving site... (and I visited with js disabled)

**Comment by perillamint** [comment]
Thanks @danielegobbetti. I fixed that link to Github. I made a typo during edit and forgot to fix it on desktop. (I'm currently experiencing some issue with https://github.com/claudioc/jingo and Android firefox compatibility)

**Comment by cpfeiffer** [comment]
Totally agree with Daniele, I'd love to support this. Just need a bit of time or some help :-)

**Comment by cpfeiffer** [comment]
I'm closing this since we already have a similar request here: #510
