### ISSUE TITLE
MI1S can't update firmware.

### ISSUE THREAD

**Issue by unicastbg** [Freeyourgadget/Gadgetbridge#340]
[gadgetbridge.log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/330680/gadgetbridge.log.zip)
The HR firmware can't be updated with Mi Fit, so I've tried this app. Attached the log file, I hope it will help. 
I've tried this on 2 phones, both on Android 4.4.2. The band was firstly paired on Xperia V, Android 4.3.

Best Regards,
Svetoslav

**Comment by cpfeiffer** [comment]
Thanks for the log. For some reason the device does not like the firmware, so it just aborts after receiving all data. You might try to change the option in the settings to use or not use the "low latency mode" for firmware updates.

But I'm afraid that the device is just broken.

**Comment by unicastbg** [comment]
Yeah, I've tried that. Doesn't seem to work. Something very strange that I
noticed is that the band actually upgraded its firmware with the official
Mi Fit app. It happened on startup. And the heart rate sensor works,
although it shows inaccurate readings. And after a few measurements it
stops working. Doing a restart using Gadgetbridge I noticed the band has
reverted to the old firmware version.
So far it looks random to me the time it chooses to update the FW. I'll
keep looking for similarities. Is there any way to split the HR FW from the
entire package? And somehow force push it? I imagine this might be done
with an emulated serial connection over bluetooth. Or not :)
Anyway, thanks a lot for your feedback!

On Tue, Jun 28, 2016 at 10:31 PM, Carsten Pfeiffer <notifications@github.com

**Comment by kornevik** [comment]
I have the same problem. MiFit app fails to update firmware. Following one suggestion on http://en.miui.com/forum.php I also tried to flash MiBand with different version of MiFit (I checked versions 2.1.6 and 2.1.0 and 1.8.711 from http://en.miui.com/thread-110066-1-1.html) but it leads to same results (FW update fails).

Would be grateful for suggestions if someone fixed it.

Band Model: MiBand 1s
FW: 4.15.11.19
HR: 1.3.72.12

Phone: RedMi Note 3
Android: 5.1.1
MIUI: 7.3

**Comment by unicastbg** [comment]
Here's what worked for me.
I used a phone with Android 4.4 and tried flashing the firmware. It failed
with both mifit and gadgetbridge. I then restarted the band and went back
to my everyday Android 4.3 phone. The mifit app tries flashing the new
firmware everytime it starts. And it fails. But at some point, a day later
I noticed that the firmware is now up to date. I've checked that with the
4.4 phone and gadgetbridge. When I tried to measure the heart rate, it
worked the first 3 or 4 times and then stopped working. Restarting the band
brings the firmware to the old one. So I went back to my old 4.3 phone and
gave up for a few days. The firmware was somehow again updated and I left
it like this for about a week. Then I connected again the band to the 4.4
phone, restarted the band and the firmware was the same up to date version.
That was new :) From then on measuring the heart rate always works on
Android 4.4 and doesn't work on 4.3. And restarting the band doesn't make
it revert to an older firmware version.

On Jul 18, 2016 7:00 PM, "Stanislav Vlasov" <notifications@github.com>
wrote:

I have the same problem. MiFit app fails to update firmware. Following one
suggestion on http://en.miui.com/forum.php I also tried to flash MiBand
with different version of MiFit (I checked versions 2.1.6 and 2.1.0 and
1.8.711 from http://en.miui.com/thread-110066-1-1.html) but it leads to
same results (FW update fails).

Would be grateful for suggestions if someone fixed it.

Band Model: MiBand 1s
FW: 4.15.11.19
HR: 1.3.72.12

Phone: RedMi Note 3
Android: 5.1.1
MIUI: 7.3

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Freeyourgadget/Gadgetbridge/issues/340#issuecomment-233373530>,
or mute the thread

**Comment by cpfeiffer** [comment]
I'm marking this an "not a gadgetbridge issue" because this is most likely a problem with either your bands or your mobiles -- most probably an issue with the band.

You could try to do it with a different mobile.

We could also add an option to only flash one firmware at once (hr firmware or band firmware). But this wouldn't change the fact that most probably the band's memory is bad. I've seen too many broken bands already.

**Comment by cpfeiffer** [comment]
And with firmware version 4.15.11.19 you won't have any success in getting any heart rate measurement. The firmware just doesn't do it. It's a mystery to me why they ship bands with a firmware that doesn't work.

**Comment by unicastbg** [comment]
I fully agree with that. If the manufacturer's app can't do it, it's a
hardware issue. My band started working, so can't tell what caused this
bug. Since then Gadgetbridge can flash the firmware.
Having an option to choose which firmware to flash would be great!
I would like to support that with a small donation, if you accept such.
Thanks!

**Comment by kornevik** [comment]
Thanks a lot. Picking up from Svetoslav's advice I tried to flash my MiBand with iPhone's MiFit and it worked! (Updated to FW: 4.16.4.22, HR: 1.3.76.22.) I am not sure if the problem was with band's hardware. Maybe it is android's MiFit app compatibility with some phone models (though my phone is the same brand).

**Comment by danielegobbetti** [comment]
Closing as the issue was solved
