### ISSUE TITLE
Raw logs in debug panel

### ISSUE THREAD

**Issue by robin13** [Freeyourgadget/Gadgetbridge#341]
The mi band seems to have at least 88 codes... I would love to decode them all, but it is difficult to track when I did something unusual. It would be great to be able to read the raw logs after synchronizing to correlate codes with activity type.

**Comment by danielegobbetti** [comment]
We had something similar in mind and we are designing the new database to make this scenario possible.

**Comment by geekpete** [comment]
Output/export a full debug log would be nice to reveal those codes.

**Comment by cpfeiffer** [comment]
IMHO the charts should provide a way to select a region and "do something with it". Like displaying the current activity kinds, exporting the selected samples, and even changing the activity kinds.
