### ISSUE TITLE
Pebble notifications, faces fail

### ISSUE THREAD

**Issue by gadgetguy08** [Freeyourgadget/Gadgetbridge#344]
Uninstalled old Pebble app, installed GB and connected with Classic Pebble on 2.9.1 firmware. 
Debug tests fail for notifications but work for incoming calls. Also old watchfaces remain, new ones won't install.
Log showing incoming call and notification here:
20:53:13.411 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.10.2
20:53:19.227 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.callstate
20:53:23.485 [Thread-51] INFO  n.f.g.s.AbstractDeviceSupport - Got event for CALL_CONTROL
20:54:49.175 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.10.2
20:55:01.384 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
20:55:02.438 [Thread-51] INFO  n.f.g.s.d.p.PebbleIoThread - unhandled message to endpoint 0 (3 bytes)
20:59:23.171 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.10.2
20:59:36.949 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
20:59:38.064 [Thread-51] INFO  n.f.g.s.d.p.PebbleIoThread - unhandled message to endpoint 0 (3 bytes)

I have rebooted watch and phone.

**Comment by ashimokawa** [comment]
Fixed in 0.11.0 now in f-droid
