### ISSUE TITLE
Location issues

### ISSUE THREAD

**Issue by gadgetguy08** [Freeyourgadget/Gadgetbridge#346]
Using acquirr location I get an immediate force close of GB.
I have tried it with gps on, with Gps off and data entered into lat and longitude with same results.
Version 0.11 and firmware 2.9.1.
I have a log cat if needed (not sure how to attach from my phone)

**Comment by ashimokawa** [comment]
@gadgetguy08 
I have no idea why it crashes for you, which Android version do you use?

Anyway. If you prefer for - some reasons - to stay on Firmware 2.9.1 instead of moving to 3.12.1, then this feature will never do anything for you anyway. Firmware 3.x is required for sunrise/sunset pins.

**Comment by danielegobbetti** [comment]
Also important to know is your location provider, read: do you have a stock android version (with gapps) or a custom rom? Do you use one of the microg location providers? Do you use xposed or other system-level mod that may interfere with location?

**Comment by gadgetguy08** [comment]
First, I have upgraded to v3 firmware. The upgrade itself appears to be successful. GB has reconnected and has a different list of installed apps and watchface.  However, the watch is stuck showing an image of downloading apps with pebble.com/apps and the phone id. 
I attempted to reinstall watch faces and apps with no success.  In debug Reboot appears to work - it shows the pebble logo screen and then returns to the download image. 
The only thought I have is to reinstall the pebble app and try loading something unless you have seen this or have another suggestion.

**Comment by ashimokawa** [comment]
Did you READ THE WIKI?

I mean about the migration process.

**Comment by gadgetguy08** [comment]
I did read the wiki.  I just performed the steps again and things are happier.

The acquire location still crashes GB. Note I am only using Gps and it has a good location.
I found this in the log

06-29 13:12:15.032 E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler(15011): Uncaught exception: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object referencejava.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference

**Comment by cpfeiffer** [comment]
I remember to have had something similar, but unfortunately I don't remember the outcome.

The location provider kind or something like that was null.

I don't remember exactly because it was not meant to be used with the devices I have, anyway.

**Comment by ashimokawa** [comment]
I can confilm the issue.
It happens if I set location mode to device only (ie GPS only)

We only have network location permission.
I am using a local gsm database without gapps and it works.

**Comment by pganssle** [comment]
I set my tablet to network only mode and still got the FC, but then I opened another app and allowed it to retrieve my location and that prevented the FC. I'm assuming "acquire location" doesn't go out and request a new location if the old location is null?

**Comment by ashimokawa** [comment]
@pganssle 
You are totally right.
I did not test that properly, and it has to be fixed.

**Comment by ashimokawa** [comment]
Is fixed and will be in release 0.11.1
