### ISSUE TITLE
Ability to manage multiple devices

### ISSUE THREAD

**Issue by robin13** [Freeyourgadget/Gadgetbridge#347]
I got a second Mi Band 1S to help debugging - I want to see the difference between wearing it on arm or around neck, investigate other uses for this low-power miniature sensor / logger.  I noticed though that while I can view both devices in gadgetbridge, they do not have any unique graphs - it seems that all data is written to the database only noting the device type, but not the device address (which the app does know).
Would it be possible to add the device ID to the data stored?

**Comment by cpfeiffer** [comment]
Cool! Yes, in master we already have a separation of activity data per device. It's not completely done yet, bits it's almost there.

Looking very much forward to your findings.

**Comment by cpfeiffer** [comment]
I'm closing this, as this is already done in master (under the #206 umbrella).
