### ISSUE TITLE
Phone battery info won't display

### ISSUE THREAD

**Issue by gadgetguy08** [Freeyourgadget/Gadgetbridge#348]
Trying to use some watch faces that display phone battery status.  After trying several I looked at the logcat and can see that the battery data is being retrieved, but not displayed.
I do see this shortly after the data is retrieved:

06-29 21:16:20.905 D/GpsLocationProvider(2340): receive broadcast intent, action: android.intent.action.BATTERY_CHANGED

Could this be related to my issue #346?
Currently do not have any location data turned on.

**Comment by ashimokawa** [comment]
Not related.
No idea which watchfaces.
Displaying phone battery can only be done with a companion app.
Please create better issues.
