### ISSUE TITLE
Ensure operation after main activity is killed

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#35]
Observation: when killing the main activity by swipng it away in the activity manager, notifications are not reported to the MI Band, even though the MI was properly connected and initialized before. The app settings dialog reports the service to still be running, also there is nothing about the service being killed in the logs, and no onDestroy() being called.

But it appears to be that the service is somehow recreated or something like that.
When I provoke a notification by fetching mails, for example, I get this in the logs:
```
D/ActivityThread(5725): handleBindApplication:nodomain.freeyourgadget.gadgetbridge
D/ActivityThread(5725): setTargetHeapUtilization:0.75
D/ActivityThread(5725): setTargetHeapMinFree:2097152
D/CommunicationService(5725): BluetoothCommunicationService is being created
D/CommunicationService(5725): no intent
´´´

"BluetoothCommunicationService is being created" comes from the onCreate() method, "no intent" from the onStartCommand() method, where the intent argument is null.

Then nothing. No startCommand about the email notification. Even the debugger automatically disconnects at this point.

Any ideas?

**Comment by cpfeiffer** [comment]
Hmm, this might actually be normal behavior when using START_STICKY with the service. Maybe we should just allow the service to auto-connect to the device.

**Comment by cpfeiffer** [comment]
@ashimokawa Can you check what actually happens with your Pebble when you kill the main activity?

**Comment by ashimokawa** [comment]
@cpfeiffer 
I have zero problems on the Pebble when killing the main activity.
This is what I tested right from the beginning. And I also tested it right now. Strange.

**Comment by cpfeiffer** [comment]
I know, but can you check what happens when you kill it? Do you see anything in the logs? Can you verify that the service is still running?

What intent action do you get when you receive a (k9) notification after the main activity has been killed? Is onCreate() being called? I'm wondering if this is an Android bug.

Actually, it is quite possible that the service is being killed e.g. in low memory situations. The problem is that on a notification I do not get the proper notification intent, but just an "empty" intent which only starts the service.

**Comment by ashimokawa** [comment]
Yes, if the service gets killed under memory pressure, then it would behave exactly like that.
But since we set it as a foreground service it will be killed only under extreme conditions.
And that would never happen with your modern device.
I had that ONCE running a device with 392MB usable ram, when opening a huge website.
START_REDELIVER_INTENT instead START_STICKY would deliver the last intent, but that would not help either.

I can check log in about an hour and update this post, but my guess is that they are clean.

**Comment by cpfeiffer** [comment]
It seems that most of my problems arise when starting GB from the ADT debugger.

**Comment by cpfeiffer** [comment]
I'll close this, because my problems apparently came from the app being started by the debugger.
