### ISSUE TITLE
Data import/export

### ISSUE THREAD

**Issue by rplevka** [Freeyourgadget/Gadgetbridge#359]
I'd like to be able to import or export the measured data. I've already have ~5 months-worth data in he original Xiaomi fit app and have it integrated with Google Fit and I'd like to have it imported to GB.
Would be such thing ever possible? It would be fine to be able to import/export some data in a form of a file (some JSON or XML-like exports)

**Comment by rplevka** [comment]
I just discovered the import/export DB in the debug menu. That should do, thanks!

**Comment by cpfeiffer** [comment]
We also have two other open issues: CSV export and sync to an external server. The debug thing is hopefully just a temporary workaround.

We're close to finishing the db refactoring, well have a much better database then.

**Comment by IzzySoft** [comment]
@cpfeiffer Looks like another candidate for our wiki (section FAQ, "Data import/export"). The current one (from the debug menu) could already be explained – a pointer to the CSV issue could be placed as well. Thoughts?
