### ISSUE TITLE
Support for device specific activities

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#36]
Currently there's the pebble-specific app activity that is opened when the Pebble device is tapped.

We should have device specific activities for the MI Band as well, like proposed in https://github.com/Freeyourgadget/Gadgetbridge/issues/15#issuecomment-95626418

@danielegobbetti feel free to open a pull request so that we can start displaying additional information for the MI Band.

**Comment by cpfeiffer** [comment]
Initial code for this is available, see MiBandCoordinator (for the lack of a better class name). Maybe should be renamed to MiBandUISupport or something like that.

**Comment by danielegobbetti** [comment]
Great, I'm studying the "Set alarm" function in the original smali in these days, I hope I can contribute the code soon!

**Comment by cpfeiffer** [comment]
Did you find out which bytes to send in order to set an alarm?
BTW, the earlier/first versions of the original app are less obfuscated than the current versions.

**Comment by danielegobbetti** [comment]
Hi, yes I found it out please see issue #28

**Comment by danielegobbetti** [comment]
I think the more we make progress the more this issue gets critical. I am "overloading" the debug activity with lots of buttons to test the miband specific methods.

My proposal of a separate activity was not really following your directions (in the sense thay it was more quick and dirty ;-) ) but perhaps it's better than nothing. 
Should i rebase my code on the updated master and submit a pull request, or do you prefer a more clean approach (which is out of my reach, currently)?

**Comment by cpfeiffer** [comment]
@danielegobbetti True!

@ashimokawa can you push your prototypical sleep activitiy somewhere? Then we could use that instead of the (Pebble-) App Manager activitiy as a start.

No need to prettify or clean it up, we can do that, too.

**Comment by cpfeiffer** [comment]
@danielegobbetti if @ashimokawa adds his activity, I'll add some glue code to start that when tapping the MI entry in the ControlCenter activity, no need to rebase your stub activity.

**Comment by ashimokawa** [comment]
Did that On Thursday ;)

https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/SleepMonitorActivity.java

**Comment by cpfeiffer** [comment]
Thanks, I'll connect it to the MI tomorrow.

**Comment by danielegobbetti** [comment]
We have several per-device activities and a new control center since quite some time, hence I closed this.
