### ISSUE TITLE
Bonding failed with Mi Bande Pulse

### ISSUE THREAD

**Issue by whitefield** [Freeyourgadget/Gadgetbridge#360]
I have sniffed a succesfull bonding scenario (made with mi fit app)
and a failed scenario (made with gadget bridge)

[MiBandPulse_bondings.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/369095/MiBandPulse_bondings.zip)

I'm tring to do an app to deal with this band and I hope that your code could help me but it's not working as intended so I hope this captures I did could help you in fixing the problem.

To view the captures you should have a look here https://learn.adafruit.com/introducing-the-adafruit-bluefruit-le-sniffer/nordic-nrfsniffer

they have a plugin for wireshark v1.12.x (please don't use v2 as it won't work)

PS:
The bonding with gadgetbridge is failing even if mifit was not installed on my smartphone.
According to mifit ap these are the firmware versions of my band
fw version: 4.16.4.22
cardiac sensor fw version: 1.3.76.22

**Comment by whitefield** [comment]
Here I'm attaching also two screenshot showing the differences I found between the two scenarios
![diff1](https://cloud.githubusercontent.com/assets/12760595/16916600/e88d79d8-4cfd-11e6-822c-e255d79273c4.JPG)
![diff2](https://cloud.githubusercontent.com/assets/12760595/16916602/ebfcdb68-4cfd-11e6-9d4e-910c1b5f51e4.JPG)

Regards!

**Comment by cpfeiffer** [comment]
One thing before I look at your logs (thanks!): which version of Gadgetbridge did you use? Please use 0.11.2 which has fixed exactly such a problem (#349).

**Comment by cpfeiffer** [comment]
Additional hint: with 0.11.2 it is not even necessary to bond the devices. It works just fine without. Don't ask me why they do it that way.

**Comment by whitefield** [comment]
Hi and thanks for your fast response, I was using 0.11.1 (I downloaded it from F droid). Now I will with the version you are mentioning.

**Comment by whitefield** [comment]
Hi, I installed 0.11.2 version but the result is still the same , I have no logs (file is empty even if I have activated the relative option in the settings) and mi band is not pairing. I'm attaching the result of the packet sniffing but it seems that nothing has changed. I understand that if you had your logs maybe it would be easier for you to fix the problem, I'll try to install this app on another phone to check if I'll be able to activate logging there.
[0112failedbinding.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/371000/0112failedbinding.zip)

**Comment by cpfeiffer** [comment]
Your log is probably empty because you mounted the partition in Windows, right? It's most probably not empty, but Windows appears to think it is.

Note that with 0.11.2 you don't need to bond the devices. You can connect without.

**Comment by whitefield** [comment]
Well, I'm using Es File explorer, However, using the Android default App, made me get the log file. I'm attaching it here.
I'm not bonding the device, I'm just using Gadgetbridge to do the work. Please see also the attached screenshots 
[documents-export-2016-07-20.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/373201/documents-export-2016-07-20.zip).

Regards!

**Comment by cpfeiffer** [comment]
The log file simply stops when the connection is being created. What happens if you press the back button and try to connect by tapping on the entry?

**Comment by whitefield** [comment]
Hi, as I said it remains stuck while trying to bonding (no back button available in the app ).
Now if I try to press back button of my phone it goes back to the screen with the devices found after the app scanned searching for a device (so it always shows my mi band pulse),
now

- if I press the mi band again, It remains again stuck while trying to connecting with my device.

- if I press back button (button is available in app this time), it shows an empty list of devices. So my mi band is not added to this list.

**Comment by cpfeiffer** [comment]
Unfortunately your log is incomplete, so I cannot check whether you really use 0.11.2. With 0.11.2 the device you're trying to connect should be remembered (so the list is not empty). Also the symptoms you describe have exactly been fixed in version 0.11.2. If it really is a new problem, I'd like to see a full log. Note that you can also manually enter the mac address in the preferences and then try to connect.

**Comment by whitefield** [comment]
Finally I got it working, but I had to set up the address by myself, automatic procedure got always stuck.
Thank you for your attention. I'll will do other tests to be sure of the procedure so that it will be possible to reproduce exactly the behaviour.
Regards

**Comment by cpfeiffer** [comment]
Very weird. No idea why the band would not connect after scanning, but would if you do not scan prior to connecting.
