### ISSUE TITLE
Document sqlite id's [Enhancement]

### ISSUE THREAD

**Issue by chriscamacho** [Freeyourgadget/Gadgetbridge#361]
Looking at the sqlite export and the source code I have most of it worked out
(I would like to contribute a Java desktop app to visualise the data)

I seem to have types of 17 (activity=1 but whats 16?)

getting the heart rate data doesn't seem straight forward some of it is regularly interleaved with 0 values ??

If one of the developers could take a little time out to document the values and "modes" of storages used in the sqlite export it would be greatly appreciated....

**Comment by cpfeiffer** [comment]
Unfortunately we don't know all activity types either. I'm closing this in favor of #332, even if that is already closed. Note that the db contains raw (i.e. device specific) data. An export functionality (as proposed e.g. in #49) would normalize the data such that it is not device specific anymore.

If you need any help, please yell. We could also add a git repository for your app.
