### ISSUE TITLE
Help with firmware reverse

### ISSUE THREAD

**Issue by elsidoi** [Freeyourgadget/Gadgetbridge#363]
Hello, everyone!
I'm currently in process of reversing Mi Band (1st version) firmware reverse. At very beginning of process.
As i investigated from datasheet band controller doesn't have FLASH memory which can be reprogrammed so after updating band via app all updates are put in RAM which size is huge for embedded devices. 
So that MAY mean that after turning band on (connecting battery) it goes to that part of firmware that waits for phone connecting and firmware upload. After that it works according to received data (i.e. fools you with smart alarm disable etc).
To check this fact we need to disassembly band unsolder battery and then solder it back. I think that we won't find a man who will drop his ten bucks for the not so big chance that this will work.
So we need to find a man who had problem with band, disassembled it and assembled back. I've found several guys on russian forum and asked them. Only one of them answered but he didn't repair his band after that and threw it to trash can. 
All project participants could help me and search for people who can help us with this issue and ask them if they could make band work after desoldering battery. 
Also it will be cool if someone of community has bricked band which can be usefull for future tests.

Sorry for my English, it's not my native language. 
Also i'm not sure it should be posted in Issues, but you have no any working chat like Slack or telegram conference or something. So sorry too.
Ask me anything you are interested, i'll try to answer.

**Comment by danielegobbetti** [comment]
While personally sympathizing with your efforts and wishing for an open firmware for miband (or any other device on earth for that matters 😁) discussing and analyzing the proprietary firmware here may yield to takedown requests for the whole project, hence I'm closing this and kindly ask everyone to not follow up. (Remember, this is not a forum but the space to discuss **gadgetbridge** issues).
