### ISSUE TITLE
Gadgetbridge force close

### ISSUE THREAD

**Issue by rederik79** [Freeyourgadget/Gadgetbridge#368]
Hi guys i have this problem, when try to update the firmware of my mi band 1A the mi fit app can't update the firmware of my mi band. So i have tryed with gadgetbridge but every time i have a force close app. I use the app with a Nexus 5x. 
Any suggestion?
[gadgetbridge.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/391898/gadgetbridge.zip)

**Comment by danielegobbetti** [comment]
I'm from mobile and couldn't look into your log, but can you please ensure that you granted to GB the permission for accessing external storage?

**Comment by rederik79** [comment]
I gived a permission. Tryng again with a phone with android 4.4 but norhing. Force close

**Comment by cpfeiffer** [comment]
Thanks for the log. It looks like they're selling Mi Band 1A devices with a hardvware version '8' which so far we recognize as Mi Band 2. The same thing was reported here: #364 (even though the title is different).

Looks like we need to find something else than the hwVersion to distinguish between the different devices.

Unfortunately your log does not contain a stacktrace of the force close, so I have no idea what actually caused the crash.

**Comment by danielegobbetti** [comment]
#364 is fixed, so I presume this one is fixed as well. Closing.
