### ISSUE TITLE
Privacy mode(s) for pebble

### ISSUE THREAD

**Issue by danielegobbetti** [Freeyourgadget/Gadgetbridge#370]
I believe it would be cool to add some privacy modes to the notifications:
- full privacy: only the notification type is sent to pebble (email, SMS, etc.) The details must be checked on the android device.
- half privacy: prepend an empty "page" to the notification's content. The full details are available on the pebble but one needs to "scroll down" to read them.

**Comment by danielegobbetti** [comment]
Inspiration on this reddit post:
https://m.reddit.com/r/pebble/comments/4vr6xn/is_there_a_way_to_stop_the_watch_from_showing/

**Comment by IzzySoft** [comment]
Sounds good as long as there's a third option – but I'd better not have that named "no privacy", for obvious reasons :laughing: "off" or "privacy mode off" might be better choices. To make it less confusing, another option would be making that setting "multi-level":

> **Privacy mode:**
* [x] off
* [ ] on
    * [ ] full privacy
    * [ ] privacy lite

With the "full/lite" options grayed out unless "on" is checked. And of course it must be radio boxes (no idea how to do those with GH Markdown, so I had to revert to check-boxes) :stuck_out_tongue_winking_eye:

**Comment by ashimokawa** [comment]
Its a nice idea and it, all we have to do is just send line breaks to the pebble to achieve exactly that.

There is only one small problem: Different font sizes. Someone setting the font to not the smallest option would have to scroll more.

**Comment by IzzySoft** [comment]
Wait – I can set the font size? How could I miss that! Well, then for "privacy lite", there could be an input field to specify how many lines to prepend.
