### ISSUE TITLE
switch chart to lineChart when zoomed over some level or aggregate bars

### ISSUE THREAD

**Issue by rplevka** [Freeyourgadget/Gadgetbridge#374]
It would be really great to switch the chart type to something more readable after user zooms out enough (line chart perhaps?). Currently, when the calculated bar width gets under 1px, it sometimes doesn't show it at all and the complete chart looks like it has gaps in it.
Another nice approach would be aggregating the measured values so the same number of bars is displayed (similar to original mi fit app)

**Comment by cpfeiffer** [comment]
I totally agree that the charts have room for improvement :-)

Also see #278

**Comment by danielegobbetti** [comment]
This was fixed quite some time ago!
