### ISSUE TITLE
'Keep activity data on device' no longer has effect for MiBand 1s

### ISSUE THREAD

**Issue by rplevka** [Freeyourgadget/Gadgetbridge#375]
After playing with 'keep activity data on device' option I noticed, it stopped to have an effect and my band keeps all the data no wonder how hard i try to disable that (checking out the option, disconnect/reconnect the band, debug->reboot the band).

rebooting the band actually wipes out the data, but the mi band still don't delete the data after syncing.
I also noticed, there are 2-3 subsequent 'fetching data' dialogs when i sync. I'm not aware of updating anything.
GB: 0.11.2
FW: 4.16.4.22
HR: 1.3.76.22

**Comment by cpfeiffer** [comment]
Thanks, this has already been reported at #367.
