### ISSUE TITLE
Heart rate - dealing with strange values

### ISSUE THREAD

**Issue by ghost** [Freeyourgadget/Gadgetbridge#382]
From time to time the device seems to return the "doubled" heart rate. This might be an error in the measurement or an extra heartbeat which happens ... anyone else seeing this?
This can be relatively safely recognised by comparing current measurement with previous and next ones

Instead of plotting the wrong value it might be better to plot the half value with a special marker showing that something was unusual about this measurement.

**Comment by IzzySoft** [comment]
Might look a bit harsh to simply close this – but it has been 3 years, and OP has even already removed his/her Github account so no feedback is possible. Should someone else still have this problem, please open a new issue. I assume this has already been solved, e.g. with the linked MR.
