### ISSUE TITLE
Can you Stop Vibrations of Mi 2 Band about Battery Full Status with Gadgetbridge?

### ISSUE THREAD

**Issue by sami10007** [Freeyourgadget/Gadgetbridge#384]
I am using Pebble Classic and Mi 2 Band at the same time, with Gadgetbridge and Mi Fit, respectively. However, I find that I cannot control sufficiently Mi 2 Band with the official application so I am thinking a change in the configurations. However, I have not managed to access any settings of battery full notifications/vibrations of the device with Gadgetbridge. 

Related: http://android.stackexchange.com/q/154537/9897

**Comment by ashimokawa** [comment]
There is no MI 2 support in Gadgetbridge yet.

Please stop spamming the Issue tracker.

And please stop editing the wiki with suggestions using the official Pebble app to install firmwares and software.

Gadgetbridge can do both since version 0.2.1
