### ISSUE TITLE
Device name changed (MiBand 1S)

### ISSUE THREAD

**Issue by robin13** [Freeyourgadget/Gadgetbridge#388]
I have two Xiaomi Band 1S devices.  In 0.11.x the device name was taken straight from the name of the device in the bluetooth settings, but now I see the names in bluetooth settings differ (for one of the devices) to that which I see in Gadgetbridge.
Could there be some way to rename the devices in Gadgetbridge, or to have it continue to reflect the name given in the Bluetooth settings?

In Bluetooth settings I have "MI1S 1" and "MI1S 2", in Gadgetbridge I now see "MI1S" and "MI1s 1"

**Comment by ashimokawa** [comment]
The devices should show up as in Bluetooth settings, you should be able to rename the devices as you please there. You can't give them a Gadgetbridge specific alias.

**Comment by cpfeiffer** [comment]
I'm surprised that the names differ that much.Did you add the "1" and "2" in the bluetooth settings or is that done by your android distribution?

As @ashimokawa wrote, if you rename the devices in the bluetooth settings, Gadgetbridge should display them in the same way.

Does the name change when connecting, btw?
