### ISSUE TITLE
Adding Korean translation

### ISSUE THREAD

**Issue by halcyonera** [Freeyourgadget/Gadgetbridge#39]
<resources>
    <string name="app_name">가젯브릿지</string>

    <string name="title_activity_controlcenter">가젯브릿지</string>
    <string name="action_settings">설정</string>
    <string name="action_debug">디버그</string>
    <string name="action_quit">종료</string>
    <string name="action_refresh" >새로고침</string>

    <string name="title_activity_debug">디버그</string>

    
    <string name="title_activity_appmanager">앱 관리자</string>
    <string name="appmananger_app_delete">삭제</string>

    
    <string name="title_activity_appinstaller">앱 설치</string>

    
    <string name="title_activity_settings">설정</string>

    <string name="pref_header_general">일반 설정</string>
    <string name="pref_title_general_autoconnectonbluetooth">블루투스가 켜지면 기기에 접속하기</string>

    <string name="pref_header_datetime">날짜와 시간</string>
    <string name="pref_title_datetime_syctimeonconnect">접속시 시간 동기화하기</string>

    <string name="pref_header_notifications">알림</string>
    <string name="pref_title_notifications_sms">SMS 문자 알림</string>
    <string name="pref_title_notifications_k9mail">K-9 Mail 알림</string>
    <string name="pref_title_notifications_generic">일반적인 알림 지원</string>
    <string name="pref_title_whenscreenon">… 화면이 켜져있을 때도</string>

    <string name="pref_header_development">개발자 옵션</string>
    <string name="pref_title_development_miaddr">Miband 주소</string>
    </resources>

**Comment by ashimokawa** [comment]
Thanks - will merge that ;)
I wanted to redesign the settings soon, hope you are available for updates then.

**Comment by cpfeiffer** [comment]
There are quite a few more strings in the code that need to be made translatable.

**Comment by ashimokawa** [comment]
Yes

**Comment by halcyonera** [comment]
Thanks for this great FOSS app, hope it could support more devices!

**Comment by cpfeiffer** [comment]
@halcyonera Well, yes, the idea is indeed to support more devices. The code is already well prepared for that. It just needs to happen by someone with other devices :-)

**Comment by cpfeiffer** [comment]
BTW, is there a FLOSS fitness tracking software that we could feed with data?

**Comment by ashimokawa** [comment]
Merged, thanks!
I will make more strings translatable, if you have time, please update then ;)

**Comment by ashimokawa** [comment]
needs update

**Comment by cpfeiffer** [comment]
FYI, we can now use transifex for translations, see #46

**Comment by ashimokawa** [comment]
Needs another update for 0.3.5 (to be released soon)

**Comment by halcyonera** [comment]
It's maintained. You can close this issue.

**Comment by ashimokawa** [comment]
Thanks ;)
