### ISSUE TITLE
Support for Miband 2

### ISSUE THREAD

**Issue by Almtesh** [Freeyourgadget/Gadgetbridge#394]
Is there any plan to support the Miband 2 ?

**Comment by PabloCastellano** [comment]
Devs are working on it. See https://github.com/Freeyourgadget/Gadgetbridge/pull/390 and https://github.com/Freeyourgadget/Gadgetbridge/pull/391

**Comment by cpfeiffer** [comment]
Yes, at this very moment :-)

Also see #323

**Comment by Almtesh** [comment]
OK, the search engine is not very efficient on Github.
Is it working now? Do you need debug? Does Gadgetbridge need to have the official app uninstalled? Is there any API on android to get data (current heartbeat and footstep) from band with adb and/or command line?

**Comment by cpfeiffer** [comment]
There is no api -- we're implementing it on top of Bluetooth LE api. There is a ble heart rate profile specification that we need to implement.  Uninstalling or deactivating mifit is probably necessary, yes.

**Comment by cpfeiffer** [comment]
Please add further comments to #323
