### ISSUE TITLE
Duplicate Notifications

### ISSUE THREAD

**Issue by srbaker** [Freeyourgadget/Gadgetbridge#395]
When I get messages on Telegram or Slack, I get two notifications on my Pebble. I don't know if this is reproduced for other apps, but it doesn't appear to happen with K-9 or Twitter.

The hardware is a Pebble Steel with latest firmware, and a Sony Xperia Z5 running whatever Android 5 it came with.

From Gadgetbridge's screen's info on my Pebble:
```
FW: v3.12.1
HW: v2_0
```

I have notifications for SMS and K-9 enabled in "when screen is off" mode. They work fine. In Generic Notification Access, I have Gadgetbridge and KDE Connect selected.

I love the app, thanks for your great work! It's very nice to be able to use my watch without having touched Pebble's proprietary software. Thanks!

**Comment by danielegobbetti** [comment]
Hi @srbaker thanks for the kind words.
Can you please tell if the two notifications show the same icon on the pebble or different ones (e.g. a message in a bottle, a chat bubble)?

If you have adb (developer access) configured on your phone, could you please tell us the "package names" of these two apps? (see [here](http://android.stackexchange.com/questions/28767/view-apps-full-package-name) for a possible approach to use).

**Comment by srbaker** [comment]
The duplicate notifications had the same icon, although I forget which was which.

I've just unpaired, and reinstalled GadgetBridge, and will try adb after I get it running again.

**Comment by srbaker** [comment]
Heya, so I updated to 0.12.2 (I was on 0.12.0, stale F-Droid cache), and re-paired my Pebbled to make sure I could reproduce.

From Telegram the icon is the same in both messages; it looks like a bell.

Notification comes in, I press the middle button, then press it again to dismiss. There's a puff-of-smoke/cloud, and then then it's right on the same notification. When I dismiss a second time, it's gone.

I've also let them pile up to make sure that it's doubling all of them, and it is (at least from Telegram and slack.)

I don't have adb set up just now, but Telegram is version 3.7.0 from F-Droid, if that helps. Slack is some other thing from the Play Store (I try to avoid connecting to Play Store unless absolutely necessary.)

Anything else I can do to help debug this?

**Comment by danielegobbetti** [comment]
@srbaker ok that's interesting, I thought the problem was you were seeing the same notification twice, but insteatd you get the notification a second time after dismissing... 
Can you please make sure that when looking at the first notification and **before** dismissing it, by pressing the down button on the pebble the notification is not there a second time?

If this is the case, it would help if you could temporarily choose to send notification to pebble also when the screen is on, and see what happens on your phone when you press "dismiss".

Further, you could try to generate a notification from within Gadgetbridge debug menu and see if also that notification shows this behavior.

**Comment by srbaker** [comment]
Just did this now:

With no notifications on my phone, my son sends me a Telegram: the notification on my watch has a down arrow, and I can scroll to see two notifications. I have to dismiss them separately.

Also, when I press middle button, and go into "Notifications" two notifications are listed for the same message.

Based on this, it seems pretty clear to me that somehow Telegram is causing my Pebble to get two separate notifications. (My son doesn't have Slack on his phone, so it's harder to test with this, but it's the other app that exhibits this behaviour.)

Generating a notification from within Gadgetbridge debug menu does *not* exhibit this behaviour. Neither does Facebook. I think I was mistaken about K-9 doing this (sorry.)

If you care to test this real time yourself, install Telegram from the F-Droid store, and I'll put my phone number here long enough for you to add me.

Thanks so much for your attention, I really appreciate this. I just noticed that there's a newer version of Telegram on F-Droid. I'm going to upgrade Telegram on my phone. If the problem goes away with the update, I'll close this. If you don't hear from me, assume it persists.

**Comment by danielegobbetti** [comment]
Can you get a logcat? (Don't forget to anonymize phone numbers! Or any other private information). It would be enough if you could capture from when you receive the message and then dismiss the two notifications.

**Comment by srbaker** [comment]
How do I do logcat? I'm pretty new to this.

**Comment by srbaker** [comment]
Ah, I remember this. I'll set up my development environment and carry on. Thanks again!

**Comment by srbaker** [comment]
Okay. I sent a telegram from my Son's phone to mine. Two things arrived on my Pebble, I dismissed them both.

```
I/ValidateNoPeople( 1419): Validating: 0|org.telegram.messenger|10004|null|10270
I/ValidateNoPeople( 1419): Executing: validation for: 0|org.telegram.messenger|10004|null|10270
I/ValidateNoPeople( 1419): Validating: 0|org.telegram.messenger|1|null|10270
I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener(15674): Processing notification from source org.telegram.messenger
I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener(15674): found wearable action: Reply to Raymond Baker  null
D/illumination-service(  602): 'notifications': Color ff00ff00, BrMode 0, OnMS 1000, OffMS 1000, Mode 1
D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService(15674): Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener(15674): Processing notification from source org.telegram.messenger
I/ValidateNoPeople( 1419): final affinity: 0.5
I/ValidateNoPeople( 1419): Executing: validation for: 0|org.telegram.messenger|1|null|10270
I/ValidateNoPeople( 1419): final affinity: 0.5
D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService(15674): Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol(15674): BLOBDB: success (token 53264)
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol(15674): BLOBDB: success (token 33610)
I/MSM-irqbalance(  796): Decided to move IRQ163 from CPU2 to CPU3
I/nodomain.freeyourgadget.gadgetbridge.service.AbstractDeviceSupport(15674): Got NOTIFICATION CONTROL device event
D/illumination-service(  602): 'notifications': Color 00000000, BrMode 0, OnMS 0, OffMS 0, Mode 0
D/TransmitPowerReceiver( 3362): Old PowerLevel: 6, current PowerLevel: 6
D/HeadsetStateMachine(16365): Disconnected process message: 10, size: 0
D/Ulp_jni ( 1419): Location CB invoked
D/skia    ( 4827): --- SkImageDecoder::Factory returned null
I/MSM-irqbalance(  796): Decided to move IRQ57 from CPU2 to CPU0
I/nodomain.freeyourgadget.gadgetbridge.service.AbstractDeviceSupport(15674): Got NOTIFICATION CONTROL device event
W/bt-btif (16365): dm_pm_timer expires
W/bt-btif (16365): dm_pm_timer expires 0
W/bt-btif (16365): proc dm_pm_timer expires
D/Ulp_jni ( 1419): Location CB invoked
```

The two lines with `BLOBDB` correspond to my watch receiving each notification (I think).

Thanks! Hope this helps!

**Comment by danielegobbetti** [comment]
I'm from mobile but from a first look I see two notifications from telegram (one actionable for wear and one not), I may be completely wrong though. Will get back to you when I can take a deeper look (also to telegram source code)

**Comment by danielegobbetti** [comment]
You could do a further test if you don't mind: first go into gadgetbridge settings for pebble and enable untested features. After doing so you'll see a couple of new menu voices, please go into "canned replies" and enter at least one (by tapping an empty line). Then disconnect and reconnect from the pebble and trigger the telegram notification(s) again.

On one of them you should be seeing a new menu voice "reply" when pressing the center button on the pebble. On the second notification the reply menu shouldn't be there... Either this or I am reading your logcat completely 🙃

Please let us know!

**Comment by srbaker** [comment]
Correct! Reply only exists on the second one, consistently.

Does this mean Telegram is erroneously sending two notifications?

Thanks!

**Comment by ashimokawa** [comment]
Stupid idea for a workaround: We could just ignore all Telegram messages without action ;)

**Comment by srbaker** [comment]
Alternative idea: is there a way to compare two consecutive notification bodies, to see if they're the same, and then discard the one without an action? This will make it non-Telegram specific (I'm pretty ure Slack has the same behaviour, I will test today.)

**Comment by danielegobbetti** [comment]
@srbaker by looking at the source code of telegram it looks like it supports "repeating notifications" (every hour or so), do you have that feature enabled? Can you make a test disabling it?

**Comment by srbaker** [comment]
@danielegobbetti I've played with this already, no change. It sends an additional notification if I haven't dismissed the first one, one hour later. I don't recall if it doubled the repeated notification, though. Will that help?

**Comment by danielegobbetti** [comment]
@srbaker It could be that the second notification is scheduled immediately + one hour in the future and the immediate one gets dismissed but we get it nevertheless... It's a shot in the dark but if you could test it would be useful :)

**Comment by srbaker** [comment]
Aha! I will test that when I'm finished my work task. Thanks!

**Comment by srbaker** [comment]
Tested several times with Repeat set to Never. No change in behaviour; I still get two notifications immediately.  I also got two notifications from "Throw" in my car today, which was surprising. :(

**Comment by ashimokawa** [comment]
Can you go in settings and set generic notifications to "also when screen is on" 

Then go to the debug screen and tap "create test notification"

I wonder if your get everything twice...

**Comment by srbaker** [comment]
Test notifications are only once. Sorry, throw was sending slightly different ones. Slack is nort sending dupes, it was a weird usage. 

So, just telegram!

**Comment by ashimokawa** [comment]
@srbaker 
Okay, that might be worked around in the master branch, and you can test this with the next release.

**Comment by srbaker** [comment]
I'll build it over the weekend and test. Thanks!

**Comment by ashimokawa** [comment]
@srbaker 
We have just tagged 0.13.1 which will appear on f-droid soon. Please test and report back.

**Comment by srbaker** [comment]
The workaround fixes it. Thanks a bunch.

This has been an absolutely positive experience. Can I buy you a beer?
