### ISSUE TITLE
xDrip-plus does not get its pebblekit messages acknowledged

### ISSUE THREAD

**Issue by kaindl** [Freeyourgadget/Gadgetbridge#397]
In #130 there was something mentioned about providing content authority for com.getpebble.android.basalt.state, but afaik there is only com.getpebble.android.state implemented?
Was there a reason, it could not be implemented or did just nobody need it/want to implement it?

Failed to find provider info for com.getpebble.android.provider.basalt
I see this message in logcat, when trying to setup the watchface for xdrip+ (https://github.com/jamorham/xDrip-plus). The watchface is working mostly, but not completely.. It seems to use the basalt-provider to check for the type of watch/watchface to decide, what info can be displayed and falls back to the simplest mode without the basalt-provider.

**Comment by danielegobbetti** [comment]
Citing @ashimokawa in the #130 initial posting:

> To make them work, we must become the content authority for com.getpebble.android.state or com.getpebble.android.basalt.state which unfortunately would make Gadgetbridge mutual exclusive with the official Pebble App. While I personally don't care, it might scare off new users wanting to try both.

Since pebble Inc. deprecated the original pebble app (that was the content authority for com.getpebble.android.state ) we took over that without fear of incompatibility. The basalt content provider though is used by the official pebble time app, and we didn't want to become incompatible with that.

Can you be more precise about what is missing? If the issue lies in the watchapp<->gadgetbridge interaction, then the content provider isn't to blame but more likely the limited JS support we have at the moment.
Do you know if the watchface is also Free Software? Could you link its repo?

**Comment by jamorham** [comment]
One of the watch faces concerned repo is here: https://github.com/jamorham/xDrip-Pebble-E

**Comment by danielegobbetti** [comment]
From what I can tell the problem is not in the content provider, it may be that we can work around this issue (I am unsure if some changes could be needed in the xDrip app). Anyway:
We need logs from the xDrip app, especially the lines containing the string ``"receiveData:`` (see the files com/eveningoutpost/dexdrip/UtilityModels/pebble/PebbleDisplay*.java
We need logs from Gadgetbridge, especially the lines containing the string ``"Got action:``

**Comment by kaindl** [comment]
@danielegobbetti thanks for looking into this!
The part of the xDrip-Code, you wanted to see the logs from, is not even activated :( 
Here is a complete snippet of the adb log when triggering the trend-view in xDrip, which would instantly show/hide the trend with the official pebble app. So there are no `receiveData:` lines in the log, but the `Got action:` ones from Gadgetbridge are there ;) 


`09-25 12:34:42.328 13756 13954 D AudioService: Stream muted, skip playback`
`09-25 12:34:42.364  2770  2770 I PebbleWatchSync: STARTING SERVICE PebbleWatchSync`
`09-25 12:34:42.368  2770  2770 E ActivityThread: Failed to find provider info for com.getpebble.android.provider.basalt`
`09-25 12:34:42.421  2770  2770 V PebbleDisplayTrendOld: buildDictionary: slopeOrdinal-4 bgReading-176 now-1625899 bgTime-1474799349 phoneTime-1474799682 getBgDelta--3.2 mg/dl`
`09-25 12:34:42.423  2770  2770 V AlertPlayer: ActiveBgAlert getOnly returning null`
`09-25 12:34:42.453  2770  2770 D PebbleDisplayTrendOld: send download called`
`09-25 12:34:42.453  2770  2770 D PebbleDisplayTrendOld: sendDownload: Sending data to pebble`
`09-25 12:34:42.462 14418 14418 I nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread: Got action: com.getpebble.action.app.SEND`
`09-25 12:34:42.462 14418 14418 I nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread: json string: [{"key":11,"type":"int","length":1,"value":0},{"key":0,"type":"string","length":0,"value":"4"},{"key":5,"type":"string","length":0,"value":"95"},{"key":3,"type":"uint","length":4,"value":1474806882},{"key":4,"type":"string","length":0,"value":"-3.2 mg\/dl"},{"key":1,"type":"string","length":0,"value":"176"},{"key":10,"type":"string","length":0,"value":""},{"key":6,"type":"string","length":0,"value":"Phone"},{"key":2,"type":"uint","length":4,"value":1474806549}]`
`09-25 12:34:42.596 14418 12411 I nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol: got APPLICATIONMESSAGE/LAUNCHER (EP 48)  ACK`

**Comment by kaindl** [comment]
reactivating the pebble support after disabling it completely gave me these lines:
`09-25 14:48:05.458 14418 12411 I nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol: got APPLICATIONMESSAGE PUSH from UUID 51a6140e-92cc-420f-aef6-51b229666742`
`09-25 14:48:05.458 14418 12411 I nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread: Got AppMessage event`
`09-25 14:48:05.459 14418 12411 I nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread: broadcasting to uuid 51a6140e-92cc-420f-aef6-51b229666742 transaction id: 1 JSON: [{"key":1000,"length":4,"type":"uint","value":1000},{"key":1001,"length":1,"type":"uint","value":1},{"key":1002,"length":14,"type":"string","value":"xDrip-Pebble2\u0000"}]`
`09-25 14:48:05.465  2770  2770 D PebbleDisplayTrend: receiveData: transactionId is 1`
`09-25 14:48:05.465  2770  2770 D PebbleDisplayTrend: Received Query. data: 3.`
`09-25 14:48:05.465  2770  2770 D PebbleDisplayTrend: receiveData: pebble_sync_value=1000, pebble_platform=1, pebble_app_version=xDrip-Pebble2��`
`09-25 14:48:05.467 14418 14418 I nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread: Got action: com.getpebble.action.app.ACK`
`09-25 14:48:05.468  2770  2770 E ActivityThread: Failed to find provider info for com.getpebble.android.provider.basalt`
`09-25 14:48:05.475  2770  2770 I PebbleDisplayTrend: sendData: messageInTransit= false, transactionFailed= false, sendStep= 0`

**Comment by ashimokawa** [comment]
The error message can be ignored, pebblekit will first try to use the basalt content provider - if it does not exist it tries the legacy one.

The question is if the legacy one can be used to tell that we have a pebble time - my guess it yes.

Which pebble model do you own? Maybe we just have to fix our model query code.

**Comment by ashimokawa** [comment]
I installed the Software and it seems to work so far.
But of course I just get a no sensor message plus battery %

Can you please (apart from the expected basalt content provider error) say what is expected to work but does not work?

**Comment by kaindl** [comment]
Ok, then this error message is expected :) 
I was confused by some Names in the code.. I found out, it is not looking for the type of my pebble, but rather for the type of the installed watchface, so my assumption, that it is looking for the type of the watch, was wrong, the type of the watchface it does get successfully.
You can't see the thing, that is not working, without data :( there should be a graph with the values of the last x minutes in the upper half, where you only can see no sensor, but it isn't there.. everything else works.

**Comment by kaindl** [comment]
I think, I found the problem..
When I use it with gadgetbridge, I get:
`09-26 12:47:46.187 11963 11963 I PebbleWatchSync: STARTING SERVICE PebbleWatchSync`
`09-26 12:47:46.187 11963 11963 D PebbleDisplayTrend: onStart: Pebble App Version not known.  Sending Version Request`
`09-26 12:47:46.206 11963 11963 I PebbleDisplayTrend: sendData: messageInTransit= false, transactionFailed= false, sendStep= 0`
`09-26 12:47:46.731 11963 11963 V PebbleDisplayTrend: buildDictionary: slopeOrdinal-4 bgReading-105 now-1713083 bgTime-1474886864 phoneTime-1474886866 bgDelta-+1.2 mg/dl`
`09-26 12:47:46.945 11963 11963 D PebbleDisplayTrend: sendDownload: Sending data to pebble`
`09-26 12:47:46.956 10903 10903 I nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread: Got action: com.getpebble.action.app.SEND`
`09-26 12:47:46.956 10903 10903 I nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread: json string: [{"key":11,"type":"int","length":1,"value":0},{"key":0,"type":"string","length":0,"value":"4"},{"key":5,"type":"string","length":0,"value":"94"},{"key":3,"type":"uint","length":4,"value":1474894066},{"key":4,"type":"string","length":0,"value":"+1.2 mg\/dl"},{"key":1,"type":"string","length":0,"value":"105"},{"key":10,"type":"string","length":0,"value":""},{"key":6,"type":"string","length":0,"value":"Phone"},{"key":2,"type":"uint","length":4,"value":1474894064}]`
`09-26 12:47:47.494 10903 23752 I nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol: got APPLICATIONMESSAGE/LAUNCHER (EP 48)  ACK`

So xDrip is sending the data to the watch, gadgetbridge seems to send it, gets an ACK, and thats it.

With the Pebble app xdrip would get the ACK, too, and then goes on, doing the things to show the graph:
`PebbleDisplayTrend: receiveAck: Got an Ack for transactionId`

So the problem seems to be, that gadgetbridge doesn't pass the ACK through to xdrip.

**Comment by ashimokawa** [comment]
We always ack even before the data gets passed to the pebble (it is a hack)

Can you try to launch the watchface manually and then force quit xdrip and launch it while the watchface is running?

**Comment by kaindl** [comment]
Watchface launched, force quitted xdrip+, launched it while watchface was active, all logged with adb logcat. I cleaned up the log of all unrelated stuff.. ACK still doesn't seem to get through to xdrip+.. :(

If the ACK were received by xdrip+, as far as i can see there would be a log-message:
https://github.com/jamorham/xDrip-plus/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/pebble/PebbleDisplayTrend.java#L188L189
called by
https://github.com/jamorham/xDrip-plus/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/pebble/PebbleWatchSync.java#L135L140

[adblog.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/493589/adblog.txt)

**Comment by ashimokawa** [comment]
@kaindl 
You are absolutely correct.
There is no ack being send by Gadgetbridge.
The reason is that for some strange reason the pebblekit message from xdrip comes in with transaction_id = -1, which is not correct according to the pebblekit documentation and source code, so we do not ack that. Weird

**Comment by ashimokawa** [comment]
@kaindl 
Are you able to compile Gadgetbridge for yourself?
If so please remove the check in PebbleIoThread.java in sendAppMessageAck() and try

**Comment by ashimokawa** [comment]
OK, no need to test, it seems to be okay what xDrip does and I have fixed the bug. I expect xDrip to be working in the next release (at least the ack comes through now, so I will close)

**Comment by kaindl** [comment]
Thanks a lot @ashimokawa , just wanted to ask, how to best preserve all settings, because i can't update my selfsigned-version over the f-droid one ;)

**Comment by ashimokawa** [comment]
@kaindl
I think without xposed hacks it is not possible.
The only thing you can easily backup is the appmanager stuff (installed apps, sort order etc)

Just backup the files in /sdcard/Android/data/nodomain.freeyougadget.gadgetbridge/files and restore them (including file ownership)

**Comment by kaindl** [comment]
I did it the easy way: I waited for the release to be in F-Droid ;) tested it, now everything works as expected with xdrip, thanks a lot @ashimokawa @danielegobbetti
