### ISSUE TITLE
Pebble battery runs down faster than with official app

### ISSUE THREAD

**Issue by ec1oud** [Freeyourgadget/Gadgetbridge#399]
Awesome project BTW - now I can do without the Play Store, run only free software on my phone and still get some use out of the Pebble.

But, I notice that the Pebble battery only lasts a day or two now, whereas it could go several days before.  My phone does not have BLE, so it has to use old-style Bluetooth, and that of course makes battery life worse than it could be; but still, GadgetBridge is 2-3x worse than the Pebble app in this regard, so I'm guessing it must be a bit too chatty, communicating too much?

I have the Pebble Time Steel (not the second version).  Also have an original Pebble which I could test, if someone expects that there could be a difference.

**Comment by danielegobbetti** [comment]
Hi, in my experience I get usually a week worth of battery life from my Pebble Time, so I don't think GB is the culprit here.
What could be happening is that you have a watchface (or a background app) that needs internet connectivity (e.g. for weather) and tries over and over again to get new data since we don't allow any network access. 
I am using [timestyle](https://github.com/freakified/TimeStylePebble) as watchface, with week-number, battery and date complications (none of which requires data from the internet). Could you test it and see if the battery life gets better?

**Comment by ec1oud** [comment]
Ah yeah I use FairCircadian.  I wanted to write an open-source version anyway; maybe it doesn't really need Internet access, but it shows weather and sunrise/sunset for the local position.  Is GB supposed to make that kind of data available directly instead of allowing network access to the watchface?

Still though, some watch apps really do need network access.  (Like the public transportation app I wrote, or a weather app that uses a specific source.)  Will you enable that eventually?

What about watch apps that depend on Javascript running on the phone?  Is that supported, or will be?

**Comment by ec1oud** [comment]
Ah now reading issue 302: so the policy is there will never be network access in GB but a companion app could do it.  Fair enough.  So I should have a companion app for yr.no and another for ruter.no, and watch faces/apps need to use those.

**Comment by danielegobbetti** [comment]
See #327 and #302 for the approach we plan to use (and please do search in the open issues next time before asking :) ). About javascript running on the phone, it is currently supported as long as it's the configuration page. We approach/solve the problems as we experience them, so if there's an open source watchface/watchapp that requires JS running on the phone we can study what's needed and try to make it work. The internals of official pebble app are of course not disclosed by Pebble Inc., hence we have to figure out by ourselves what needs to be done.
If you have examples of open source watchapps/faces that need this please open a new issue!

**Comment by danielegobbetti** [comment]
> So I should have a companion app for yr.no and another for ruter.no, and watch faces/apps need to use those.

No, what we meant was that a single gadgetbridge "addon" would allow any watchface to reach the internet. Eventually we could add a whitelist in the addon (that's actually a good idea that I never thought of before :-) ) but the idea is that the watchface/watchapp developer doesn't need to create custom android app.

BTW with a companion android app you can already achieve what you want since GB will allow watchfaces/apps to talk to android apps with the right settings checked, and obviously any installed android app is free to do what the android OS allows it to do, including connecting to a remote server.

**Comment by ashimokawa** [comment]
@ec1oud 
Could it be that you are listing music with your phone?
If the player updates information very often, it could drain the pebble's battery.
I have seen a debug log with a player updating 10 times a second or so.
Can you please check the logs?

**Comment by ec1oud** [comment]
No, not listening to music.  

I think it's really the watchface: if I use TicToc, the log is quiet, whereas with FairCircadian there's this every 10 seconds or so:

`I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol(12769): got APPLICATIONMESSAGE PUSH from UUID 3dac2f14-c93e-4cd3-9425-e5aa90829bb3
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol(12769): dict size is 0, ignoring
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleIoThread(12769): unhandled message to endpoint 48 (19 bytes)`

**Comment by danielegobbetti** [comment]
Ok, I'm closing this issue. Please reopen this one or open a new one if the problem appear again with an open source watchface, so that we can identify the problem and solve it (or fake a solution keeping the watch face quiet :-) )

**Comment by ec1oud** [comment]
FairCircadian was trying to use the net connection way too much.  Switching to Timely makes the battery last more than a week.

But FairCircadian only needs a few bits of info; one of them is sunrise/sunset times.  So, now that GB is pushing timeline pins with that data, is there any Pebble watchapp API which could access them too?  Then I could rewrite something like FairCircadian... at least the "circadian" part.  (Weather data is a different problem.)

**Comment by ashimokawa** [comment]
@ec1oud 
There is almost no API for nothing and most watchapps fetch their data from the internet and push them to watchfaces. Multiple weather apps = multiple fetches. No data sharing.

The easiest way right now would be to natively support FairCircadian and push our data by our own means. I mean if FairCircadian is THAT good :D

**Comment by ec1oud** [comment]
The design is pretty good IMO, but it's closed-source AFAIK.  So if I get around to rewriting something like it, it would be good to come up with the best way to do that.

You guys really put yourselves in a bind by requiring companion apps for all forms of external communication, plus there's the overhead of having to install those.  I understand not wanting to ask for any permissions when installing GB, but if other apps are required to make it useful, and _they_ have to ask for those permissions, the difference is that doing it this way increases bloat and increases the need for inter-app communication, right?  All those companion apps have their own icons cluttering up the apps list.  (But if they also provide useful UI, that's how it has to be.)  But if it has to be that way, then standards need to be established.  It would be a good thing if there were a standard way for apps like GB to request data from weather-providing apps for example, but does such a standard exist?  Should we establish one, just for companions that GadgetBridge knows how to talk to?

A watchface cannot have a choice between several companion apps, right?  Is it up to GB to know how to talk to them, or is it that enabling that one checkbox "Allow 3rd Party Android App Access" enables any watch app to talk to any companion which it already knows about, and that that's the way we want it to be?  When I access weather data on my watch face I'd like it to come from yr.no, so let's say I write an app for that which is a companion to a particular watch face.  Someone else writes a watchface and a companion that uses weather.com.  Any chance that those could ever talk to each other?  We are acting like monolithic apps are evil, and yet it's inconvenient if there is not a single weather app which can talk to all the online weather services, offer the user a choice, and let the watch faces be agnostic about it.  Or else a standard for weather apps to provide weather info to other apps, so that you have a choice of which one to install, instead of a runtime choice.  But standards always manage to leave something out, and also to have unresolvable incompatibilities... so to be successful they have to keep evolving constantly, which increases the workload and yet still limits functionality (relative to the current Pebble "standard" that any data which is accessible on the web is fair game).

You have us on a straight and narrow path which only goes to a few defined places, instead of an agile network of paths which go anywhere we want.  It's analogous to the difference between bluetooth and wifi: defined profiles for defined use cases vs. plain old IP and the recent tendency to turn everything into a web service.  Or, driving a car vs. taking public transportation.  Or 1970's-era land lines controlled by a monopoly vs. the cell phone network.  The majority will always choose more freedom rather than less; and open platforms are always where the innovation comes from.  But I also worry about how we are enabling big brother - that's the point, right?  (But who provides the public transportation? and who provides the Internet? and who tied all the old phone networks together into one, a century ago?)  And even from the set of people who understand what the point might be, most will still have trouble devoting much attention span to re-inventing things in a difficult way, that have already been done in an easier way, just for the sake of standardizing and channelizing the information stream.  Spending personal time to make the present-day machines a little more efficient and less revealing... temporarily, until the landscape shifts and everything gets rewritten again.  (There should be an AI optimizing the machines automatically, but we are writing code ourselves instead of writing the AI, because we don't know how yet, and probably won't trust it even after we know how to write it.  And it's ironic that a platform called "android" is not an AI.  It may seem ludicrous in a couple more decades... unless the present trend continues, that AI can exist only in the cloud, not on our personal devices.  Until recently we thought that we'd be installing AI software on _our_ computers, right?)  So I fear that this approach may be a dead end, ultimately.  And if I get a new phone... well then I will be stuck having the Play Store installed whether I like it or not, which means I might as well install the latest Pebble app again.  Using CyanogenMod (or plain AOSP) without the Play Store installed is what enables this data-hygiene lifestyle.  And that can't be done on the newest phones.

But oh well... maybe I can invest a little time as long as it doesn't turn into a lot of time.  ;-)  Because I'm getting bored with the short list of watch faces that actually work with GB.  My attention span for that is probably a couple of weeks of spare time; then I will start to think there must be something of more long-term value that I should be doing.

**Comment by danielegobbetti** [comment]
@ec1oud there could be a single "internet-enabled" addon app (on the android device) and a whitelist of pebble watchfaces/watchapps that are authorized to talk to this app (and henceforth the internet). BTW that is the idea behind https://github.com/Freeyourgadget/Gadgetbridge/issues/302 that you mentioned earlier.

The fact that a closed source watchapps wants its "few bits of info" from its own web-server/-service is nothing something we can fix, same for the fact that there is no "pebble-official" way to gather this information from the watch itself, despite this information being present. *Anything* we build to workaround these limitations would be ad-hoc and needs support by watchfaces'/watchapps' makers. Support which quite frankly **I** don't expect we are going to have.

What @ashimokawa is proposing is a solution to address the specific needs of specific apps, this is being done already for instance to gather activity data from misfit and morpheuz (the latter being easier as it is open source). The same way we support decoding incoming data from these app, we could encode and send data to other apps. It is also fairly easy to do so, and if you have concrete use-cases of watchapps/watchfaces that you would like GB to talk to, we can guide you and other users could benefit from it.

**Comment by ec1oud** [comment]
The watch app and the companion can both be open source, and so is GB; the only things that have to stay closed so far are the Pebble watch firmware and the Pebble SDK, right?  So we could write a unified info-for-smartwatches service on Android if we like (weather from various sources, sunrise/sunset, location, GPS track, map tiles, timeline pins, etc.) but how would the watch app ask for this info, if we can't extend the Pebble SDK's APIs?  But there was some idea elsewhere like this: watch apps that don't need either companions or JS but just the Pebble app itself (which GB is replacing), or maybe a shared companion.  So I guess there would need to be a standardized set of dictionary keys, since the only way a watch app can request or receive data is in the dictionary format, right?  You can't for example send JSON to the watch directly, you have to make a dictionary with key-value pairs in which all the keys are enum values that have already been defined.  But it seems to me that it could still be done.
