### ISSUE TITLE
idea: support Sony Ericsson LiveView

### ISSUE THREAD

**Issue by ec1oud** [Freeyourgadget/Gadgetbridge#400]
https://en.wikipedia.org/wiki/Sony_Ericsson_LiveView

These are old now, and the battery doesn't last long (so it would be an extreme exercise in optimizing: communicate as little as possible in order to make it last the longest), but it would be interesting to give it another life.  I have a spare available, in case somebody wants to work on it.

**Comment by ec1oud** [comment]
Actually the way it's made is horrible - it's not the slightest bit water-resistant, too bulky, and you have to remove it from the band to charge it (which is inconvenient but should be done as often as possible).  So I didn't try to use it as a watch for very long.  But always figured there should be some use for it, as some sort of auxiliary display which can be left at home connected to a charger all the time.

**Comment by danielegobbetti** [comment]
I see there are [several](https://code.google.com/archive/p/adqmisc/source/default/source) [resources](https://github.com/BurntBrunch/LivelierView) and [alternative](https://github.com/xperimental/OpenLiveView) [firmwares](https://github.com/RobBrownNZ/LiveView-Firmware) are [mentioned](http://forum.xda-developers.com/showthread.php?t=1422106&page=49).
I believe it's feasible to support it, and I'd like to play with it :)
You find my contact info on my GH profile, mind that I can't commit to ETAs for its support though.

**Comment by bademux** [comment]
I can donate one if someone feel want to play with it.

**Comment by danielegobbetti** [comment]
I confirm my availability, you can find my contact info on my profile page.

**Comment by danielegobbetti** [comment]
@bademux thanks for the device! It arrived in my hands yesterday.
Currently I managed to set the time from GB ( \o/ )using https://github.com/xperimental/OpenLiveView as guide.

**Comment by bademux** [comment]
Cool! And happy codding.

**Comment by danielegobbetti** [comment]
Initial basic support in #445 . If someone is compiling from source and wants to switch to that branch, feedback is more than welcome!

**Comment by danielegobbetti** [comment]
#445 is merged to master, so next release will contain basic support for liveview!

**Comment by TomTheDragon** [comment]
How can i connect the LiveView to my phone? Gadgetbridge worked fine with my Teclast H30 but with the LiveView, i keep trying and trying.. but nothing happens. I also tried to reboot my phone multiple times.
