### ISSUE TITLE
Unable to remove device

### ISSUE THREAD

**Issue by rplevka** [Freeyourgadget/Gadgetbridge#401]
tested with Mibands.
I recently discovered some random miband 1s in the area. It has been added (not paired) and obviously a DB record has been created for it.
Now I miss some `remove device` functionality.

**Comment by cpfeiffer** [comment]
Yes, we lack that at the moment. Not only should we remove the device, but also all related information (e.g. samples) upon request..

**Comment by ashimokawa** [comment]
done in 0.13.2 which will be in f-droid soon.
