### ISSUE TITLE
Errors in charts in v0.13.2

### ISSUE THREAD

**Issue by rplevka** [Freeyourgadget/Gadgetbridge#403]
I've noticed the X-axis labels now contain minutes since beginning instead of the absolute date+time.
e.g. "Your Activity and Sleep" apparently displays the last 24-hours of activity, but the X-labels show numbers from 0 to ~1400 (which I believe are minutes).

I've also noticed the "Steps a week" charts do not show any data anymore (i believe this is a regression since v0.13.1)

**Comment by ashimokawa** [comment]
Thanks for reporting - this is an regression indeed

**Comment by cpfeiffer** [comment]
I'm sorry -- we ported to a new, incompatible version of a charting library and that port was not quite read yet. The issues should be fixed, now.
