### ISSUE TITLE
Binding with Mi Band 1A

### ISSUE THREAD

**Issue by cipriansavastre** [Freeyourgadget/Gadgetbridge#404]
Hi guys,

I own a Mi Band 1A device - the one with white leds (firmware 5.15.11.19), and I am writing a test application in c# for windows phone 10.

I am able to read battery info, LE params, step info, send alarm (through default immediate alert characteristic), test it (write 2 to ff0d characteristic) and I was able to register for real time step notification.

However, I am not able to bind or to read user info from it. 

1. For binding (pairing) I am writing 2 to ff0f characteristic, but nothing happens. For comparison, I tried using another windows phone application and when binding the device starts to vibrate, flashes the white leds, and the pair succeeds after tapping the device. How should I achieve the same? Can you please give me some guidance? (note that BLE c# class says that the device is paired and connected to the phone)

2. For reading user info I am reading from ff04 characteristic, but I receive 0 bytes. Could this be related to the fact that the bind/pairing was not successfull?

Sorry that I posted this here, but didn't know how to contact you guys.

Thanks,
-Ciprian

**Comment by danielegobbetti** [comment]
**at the very least** add a link to your repository so that people can help you there (I assume your app is open source/free software). I'm closing this.

**Comment by cipriansavastre** [comment]
@danielegobbetti well, I do not have a repo until now, since all my tests are exploratory for now. Could you please at least point me where I should ask this question?

**Comment by cpfeiffer** [comment]
1) you can capture a Bluetooth dump of the other C# applications to see what they do differently
2) I don't think you can read user info from the device, although I'm not sure about that, I never tried.
