### ISSUE TITLE
Log files not generated

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#406]
I tried to collect some log data on the (failing) connection process for my new Mi Band 2 with Gadgetbridge. I checked "Write Log Files" under "Developer options" on the "Settings" screen, but can't find the log files anywhere on my device.
The [Wiki states](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files) that Gadgedbridge's log files could be found at `/sdcard/Android/data/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge.log`, but I can't find it on that path -- neither on my internal or external storage.
A restart of the App also didn't help.

I have the latest Gadgedbridge version (0.13.3) installed on my HTC One M8 with CM 12.1.

**Comment by cpfeiffer** [comment]
Noooo, not again!! Can you try to get some normal logcat output, either with adb from the PC or with a logcat app on your device? If anything's wrong, it should at least write something to the normal logcat.

**Comment by 6arms1leg** [comment]
Sure I can get some logcat output.
What action exactly do you want me to log?
For now, I attached one logcat log file to my last post on #323.
If you need more, please let me know.

**Comment by cpfeiffer** [comment]
Ideally one where you start up Gadgetbridge or enable logging.

**Comment by 6arms1leg** [comment]
Attached (see end of this post) is a logcat log of starting Gadgedbridge and enabling logging ("Write Log Files").
Strange, seems like Gadgedbridge can't write to my external SD card...

```
10-10 19:21:08.652 I/nodomain.freeyourgadget.gadgetbridge.util.GB( 5773): ignoring non-writable external storage dir: /storage/sdcard1/Android/data/nodomain.freeyourgadget.gadgetbridge/files
10-10 19:21:08.654 I/System.out( 5773): 19:21:08,654 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: GB_LOGFILES_DIR_IS_UNDEFINED/gadgetbridge.log
10-10 19:21:08.655 I/System.out( 5773): 19:21:08,655 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/data/data/nodomain.freeyourgadget.gadgetbridge/files/GB_LOGFILES_DIR_IS_UNDEFINED/gadgetbridge.log]
```

Why isn't it using the internal storage anyway (not all devices have external SD cards)?
File creation on the internal storage doesn't seem to cause any problems though, as Gadgedbridge can create a database backup file there.

[logcat-start_gb_enable_logging.log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/520130/logcat-start_gb_enable_logging.log.zip)

**Comment by cpfeiffer** [comment]
We try really hard to find the best writable storage directory, that is accessible by the user (who is often not root). I changed on thing which hopefully resolves the issue for you.

**Comment by 6arms1leg** [comment]
With the new version of Gadgetbridge, the issue is gone and log files are created on my internal storage as described in the wiki.
Many thanks! :+1:

**Comment by cpfeiffer** [comment]
Thanks for verifying the fix!
