### ISSUE TITLE
K9 Mail empty subject/sender/preview

### ISSUE THREAD

**Issue by ashimokawa** [Freeyourgadget/Gadgetbridge#407]
Seems to be a k9 bug (hopefully)
Opened a bug report here:
https://github.com/k9mail/k-9/issues/1699

**Comment by ashimokawa** [comment]
the NPE seems to be fixed, I still get no messages from k9. Trying to move that to generic support

**Comment by danielegobbetti** [comment]
As we now have both native support and general notifications and both work for me, I am closing this.
