### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by xphnx** [Freeyourgadget/Gadgetbridge#41]
<resources>
    <string name="app_name">Gadgetbridge</string>

    <string name="title_activity_controlcenter">Gadgetbridge</string>
    <string name="action_settings">Ajustes</string>
    <string name="action_debug">Depuración</string>
    <string name="action_quit">Salir</string>
    <string name="action_refresh" >Actualizar</string>

    <string name="title_activity_debug">Depuración</string>

    
    <string name="title_activity_appmanager">Gestor de App</string>
    <string name="appmananger_app_delete">Borrar</string>

    
    <string name="title_activity_appinstaller">Instalador de App</string>

    
    <string name="title_activity_settings">Ajustes</string>

    <string name="pref_header_general">Ajustes generales</string>
    <string name="pref_title_general_autoconnectonbluetooth">Conectar con el dispositivo cuando el bluetooth se encienda</string>

    <string name="pref_header_datetime">Fecha y hora</string>
    <string name="pref_title_datetime_syctimeonconnect">Sincronizar la hora al conectar</string>

    <string name="pref_header_notifications">Notificaciones</string>
    <string name="pref_title_notifications_sms">Notificación para SMS</string>
    <string name="pref_title_notifications_k9mail">Notificación para K9-Mail</string>
    <string name="pref_title_notifications_generic">Soporte para notificaciones genéricas</string>
    <string name="pref_title_whenscreenon">… también cuando la pantalla está encendida</string>

    <string name="pref_header_development">Opciones de desarrollador</string>
    <string name="pref_title_development_miaddr">Dirección de Miband</string>
</resources>

**Comment by ashimokawa** [comment]
Merged, thanks!
I will make more strings translatable, if you have time, please update then ;)

**Comment by ashimokawa** [comment]
needs update

**Comment by ashimokawa** [comment]
Needs another update for 0.3.5 (to be released soon)

**Comment by xphnx** [comment]
Added via Transifex, so I think this can be closed.
