### ISSUE TITLE
[Pebble] Problem after upgrading from 1.x to 3.x

### ISSUE THREAD

**Issue by PabloCastellano** [Freeyourgadget/Gadgetbridge#410]
Hi there.

I discovered Gadgetbridge some weeks ago and I decided to get a Pebble watch (first edition, HW: v1_5).

I'm aware that the [Pebble firmware updates](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Firmware-updates) doesn't say that upgrading from 1.x to 3.x is tested but I decided to give it a try for free software's sake. I have upgraded using **3.x-migration_v1_5_v3.8-mig10.pbz**. Previous firmware version was v1.14.4 and now it is v3.8-prf9.

Apparently the upgrade went well but it doesn't seem to work anymore. I'm new to Pebble and don't still know how it works at all, so I may be missing something. I have deleted my device from Gadgetbridge and added it again. Pairing works but as soon as it gets connected Pebble shows the Recovery screen and I'm not able to do anything.

What should I try next? Is there anything I can test for you the developers? I still don't want to install the official app.

Also, before I just was able to discover one BT device, now I can also see a BT LE device but Gadgetbridge does never connect to it. I also noticed that the new BT LE device has a different MAC address everytime I restart Pebble

**Comment by PabloCastellano** [comment]
Oh, forget about it. I just needed to flash the other firmware.
Now it boots fine. I'll add that I've tested these versions  to the wiki

**Comment by ashimokawa** [comment]
Thanks for editing the wiki, all the information you needed was already there, but I think the important information is more eye caching now after your edit.

What I see a bit problematic it that the table somehow suggests that one migration firmware is bound to one real firmware update which is not the case, it should be possible to go right to 3.12.2 from any migration firmware. Maybe we should just remove the information on <mig10 migration firmwares. I also do not see a reason to suggest anything else then flashing any other 3.x firmware as 3.12.2 on the original pebble models.

**Comment by PabloCastellano** [comment]
@ashimokawa Oh, that's not good then.
In my opinion the instructions weren't very clear. At first sight I didn't see the second step and after the changes I find it better.
About the table of tested firmwares, remove it if you want. I thought the purpose was announcing which firmwares have been tested to work after flashing using Gadgetbridge.
I'm new to Pebble and don't know the differences between 2.x and 3.x firmwares but if you think it doesn't make sense to flash an old version, then clean it a bit too.
