### ISSUE TITLE
MiBand - Low battery level alert

### ISSUE THREAD

**Issue by Alexus230** [Freeyourgadget/Gadgetbridge#411]
MiBand vibrates for every message from Gadgetbridge about low battery level. This vibrations repeated every 1-2 minute.

**Comment by cpfeiffer** [comment]
I'm not sure I understand. You mean, Gadgetbridge makes your Mi Band, which is low on battery, vibrate every 1-2 minutes?

My experience is that the band itself vibrates when it is very low on battery. You can try this by disconnecting from Gadgetbridge. If it still vibrates, it's not Gadgetbridge.

**Comment by Alexus230** [comment]
The problem is that my Gadgetsbridge set for vibrate on every Android notification ("Generic Notifcation" in Settings). And when Gadgetsbridge sees that my battery is 10% or lower it starts open notification every minute (even when i close notification or ignore it), which results vibration by miBand.

BTW, sorry for my English

**Comment by danielegobbetti** [comment]
You could blacklist gadgetbridge itself in the notifications settings :-)

**Comment by cpfeiffer** [comment]
Well, fair enough, we should really ignore our own notifications (except those from the Debug screen).

**Comment by cpfeiffer** [comment]
At least on my device, I can not trigger the notification listener with our own notifications. Can you check if your band vibrates when you create a test notification from the "Debug" screen? (Make sure that it's configured in the preferences to handle notifications "Also when the screen is on".

**Comment by Alexus230** [comment]
@cpfeiffer I have generated test notification from debug screen, and miBand vibrates only one time.

**Comment by 6arms1leg** [comment]
I can confirm this issue. I get exactly the same behavior as @Alexus230 described, when battery is low. If I disconnect my Mi Band (the very first model, FW 1.0.10.14) in Gadgedbridge, the vibrations stop.
