### ISSUE TITLE
Sunrise ?

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#415]
How do we determine the surnise? The watch says in one minute but according to my window it is still dark. And so thinks the Royal Observatory of Belgium http://www.meteo.be/meteo/view/en/123495-Ephemeris+of+sun+and+moon.html

The watch says 7.43 but it should be more 08:14 or so

**Comment by danielegobbetti** [comment]
GB doesn't adjust its location automatically, so maybe it's off by a few degrees (did you enable location while on a trip away from home?). You can go to settings - pebble - acquire location and see if the values for lat and lng change.

**Comment by roidelapluie** [comment]
Thank you; the Latitude and Longitude were set at 0; I was not aware of those settings.

**Comment by roidelapluie** [comment]
Is there a way to force a resend of the sunset and sunrises?

**Comment by IzzySoft** [comment]
@danielegobbetti 

> GB doesn't adjust its location periodically/automatically

Wouldn't it be nice if that were included at least optionally? It might be needed for watch apps anyway. Or should I open a new issue with a feature request on that? When traveling, one easily forgets to adjust that manually, so currently it would already make sense for e.g. Sunset/Sunrise pins.

If omitted for "energy saving reasons", it could be an option turned off by default. I'd think of e.g.

* [ ] auto-update location
    * [x] use COARSE_LOCATION (battery friendly)
    * [ ] use GPS (more accurate, but more battery consuming)
    * update interval: __ hours
* [ ] update on request by watch apps
    * [ ] limit to __ requests per __ (e.g. "5 requests per minute")

"__" could be a manual input (numeric) or a drop-down together with "hours" for useful values, e.g. 30min, 1h, 3h, 6h, 12h, 1d.

BTW: When using UnifiedNLP and e.g. LocalGSMProvider, COARSE_LOCATION would be nothing but a *local* database lookup based on the currently connected cell towers. So for getting the correct sunrise/sunset pins, that's negligible in terms of performance/battery.

**Comment by danielegobbetti** [comment]
I believe we could just listen to the passive location provider, this way we would piggyback any update request made by other apps :-)

Let me rename this issue instead of creating a new one

**Comment by IzzySoft** [comment]
Formidable! Yes, that should suffice for most cases (except for the "special requests made by an app"). Will you move that over, or shall I open a new issue? AFAIK you could also reopen this one and then rename it. Ah, wait, you're not a collaborator or owner either, so you can't...

**Comment by danielegobbetti** [comment]
Next version will contain an additional preference (true by default) that uses the last known location of the device when sending the sunrise and sunset pins.
