### ISSUE TITLE
Mi Band 2 MAC address

### ISSUE THREAD

**Issue by Kamajabu** [Freeyourgadget/Gadgetbridge#416]
Hey, as I undestood it's possible to connect to Mi Band 2 on two levels - application and device.
I was able to do both, connect by MiFit on app lvl, and pair MiBand as bluetooth device in Gadgetbridge. 

I'm trying to read MAC Address of currently connected MiBand. When I got it paired it's pretty simple by using 
`mBluetoothAdapter.getBondedDevices()` 
but problem occurs when I'm trying to do the same when I'm connected only by using MiFit. MiBand isn't displayed in paired devices, so it can't be detected by method mentioned above.

Guy that made Mi Band Tools somehow got it working, any idea how?

Btw. what's weird and also what I'd like to understand is why it's impossible to detect band in GadgetBridge if it's already connected by MiFit, but other way around it doesn't make any problems (firstly connect on GB, then on MiFit, both works like a charm then)?

**Comment by cpfeiffer** [comment]
Interesting. How do you connect to the band via MiFit? Not on Bluetooth level, but by talking to MiFit? Then you probably need some API to ask MiFit for the Mac address.

I suspect that there is a way to get exclusive access to the band, which MiFit probably does and Gadgetbridge does not.

Support for Mi2 in Gadgetbridge is still in its infancies, any help is appreciated :-)

**Comment by Kamajabu** [comment]
Hey,

I create MiFit profile -> Log in -> Go to profile setting -> Add -> Band and it does search for band. If it's not connected with another device it's get authorized and connected exactly the same way it does on Gadgetbridge (asks for confirmation on band by showing finger animation and clicking on func button). 

It seems like band is broadcasting signal "connect to me" which stops when connected by MiFit, so this is why it can't be detected later by GadgetBridge. What is really interesting, is that somehow author of Mi Band Tools got connected to this stream created by Mi Fit and depends on it (his app requires installing and connecting to band by MiFit). But have no freaking idea how he did that.

**Comment by cpfeiffer** [comment]
This "locking" is probably also the reason why Gadgetbridge cannot connect to some bands even when MiFit is not connected at the time.

Would be nice of we found away to
1) do this locking as well
2) unlock locked devices

**Comment by Kamajabu** [comment]
Ok, so I've made some more tests:
- MiBand Tools works on connection made on GadgetBridge (only), even after disconnecting in app  (but connection is kept in "paired" list in system, disconnecting there too results in stopping work of MiBand Tools),
- If device is already detected but disconnected on GB, then it's possible to connect on MiFit and then connect on GB also... 

I have to test it more and look into logs. Weird things happen here.

**Comment by cpfeiffer** [comment]
Interesting findings. So MiBand Tools cannot establish the initial connection itself, but if the band already trusts the mobile (as established through MiFit or GB) it can connect, as long as it knows the MAC address.

Together with your other point, I assume that it is only the MAC address that's needed to connect to the band.

**Comment by Kamajabu** [comment]
> Together with your other point, I assume that it is only the MAC address that's needed to connect to the band.

I confirm. Used RxAndroidBle ( https://github.com/Polidea/RxAndroidBle ) and could post notifications to band on hardcoded MAC address while not being connected by GB nor MiFit.

And I got even more weird behavior. I was trying to find MiBand on GB on samsung S6 - worked like a charm. Then turned on bluetooth and Mi Band Tools (MBT later) on second device (Honor 7) and GB couldn't find Mi Band on S6. Turned off MBT on honor - GB worked again.

What is really weird in it that MBT can't connect on itself, but it's blocking other signals somehow... If I had to guess it catches MAC address but app doesn't have functionality to connects itself. Wondering if this is some problem caused by Mi Band or just mistake of programmer...

I've tested band with MiFit again also. It seems that as we thought, when connected by MiFit (doesn't matter if the same or other mobile phone) GB cannot find it. What is interesting here is how "visibility" returns. It happens almost immediately after I disconnect band on MiFit. Same thing happens when I turn off bluetooth. So i suppose that Mi Band just start to shout its MAC address same moment it lose connection. Question are:
- why RxAndroidBle and other devices cannot see it - EDIT: now it does, it seems that it was also blocked and not fully tested. It cannot make handshake same as BG (with confirmation on miband by clicking func key) but allows to send notifications.
- why MBT blocks it even if its not fully connected.

I have additional question too, is it possible to see UUID addresses and exact bits being written by sniffing bluetooth? I've analyzed HCI snoop in wireshark but it was gibberish for me. As I said before I've put notification on miband by sending Write 0x01 to 00002a06... (without handshake o,0) but I'm curious if by analyzing data sent by MiFit/MBT I can discover what codes are responsible for e.g. twitter icon.

**Comment by cpfeiffer** [comment]
We really need to distinguish the cases of one device (mobile) and two of them.

Only one device can connect to the band at the same time, and while it is connected, no other device should be able to discover it.

Iff however, a second device already knows the MAC address, it could attempt to connect but should be ignored.

In contrast, if only a single device is used, multiple apps could communicate with the band because the band probably cannot distinguish them.

However, if one app is already connected, the band stops advertising, so a second app can only join if it already knows the MAC address.

It may well be possible that multiple apps on the same device can communicate with the band at the same time. Never tested that. I assume that this would be error prone because they wouldn't synchronize their ble communication, which is crucial on android.

With btsnoop you cannot get uuids, just handles. You can get a mapping with gatttool, though.

We can share information about the protocol to save some work.

What are you working on, BTW?

**Comment by cpfeiffer** [comment]
(Going to sleep now, so cannot answer before tomorrow.)

**Comment by Kamajabu** [comment]
Goodnight! (will edit this comment after additional research)

**Comment by cpfeiffer** [comment]
I'm closing this for now. If you have more insights to share or discuss, please do so and I will reopen it.
