### ISSUE TITLE
Heartrate only recorded during sleep

### ISSUE THREAD

**Issue by ragflyer** [Freeyourgadget/Gadgetbridge#417]
I have been using gadgetbridge for a while now but cannot find out why it stops recording heart rate during wake hours.
On live activity screen I see an orange line but it does not flow into the consolidated day view.
The automatic reconnect is activated, Bluetooth is on, still I always have to manually connect and then sync to retrieve data from last night, is this correct behavior?
Kind regards

**Comment by Frozen-byte** [comment]
Same for me, thought this is an intended behavior, isn't is?

**Comment by cpfeiffer** [comment]
Yes, the band itself does it that way and we can't change that. Heart rate measurements at night can be enabled/disabled in the preferences.

We will add repeated measurements during the day, soon.
