### ISSUE TITLE
Pebble: AWReply.apk voice features do not work

### ISSUE THREAD

**Issue by andyb9** [Freeyourgadget/Gadgetbridge#418]
Hi, everyone :)

I'm new here so pls i apologise for any mistakes in etiquette.

With regards to '**voice memo**' or '**reply with voice**' etc - I cant seem to get it to work (using Gadgetbridge on my android phone) and so i investigated and found that for now 'voice reply' can only be used 'for voice reply to sms' on the **_Pebble Time Steel_**.

i then used _this method_ here - https://www.reddit.com/r/pebble/comments/39fgzz/voice_replies_with_tasker_and_companion_app/

with mentioned (on the webpage-link above) watchapp: http://bertderuiter.nl/pebble/AWReply.pbw
and the companion android app: [http://bertderuiter.nl/pebble/AWReply.apk

to test if it will work with 'voice replies to notification' as described in the link above and although it worked when i replied by text or imoji, it failed to sent the 'voice reply' when i try to 'sent voice' with the error message - "**_Dictation is not available_**"

My Question now is - does it not work for me because i am using **_Gadgetbridge_**? as it seems to work for others, according to that link above - so is it because they are using the original pebble app and not Gadgetbridge?

_p.s._

**To those who might say this is not an issue - i think for new users of Gadgetbridge, this is something that they may be confused about and so need to be discussed or explained** :-): 

_note_:-

**I'm using Gadgetbridge v0.11.3 with my 'Pebble Time Steel' current firmware is v4.1.3**
**and android v5.0.1 on my phone & android v5.1.1 on a tablet.**

**Comment by ashimokawa** [comment]
Voice reply is not supported, we list all features of Gadgetbridge and did not list that, so this issue is invalid.

Also it would use internet services. Your voice will be sent somewhere. We won't support that.

But you mention a companion app. That could work. But you say it does not. Have you enabled 3rd party support in Gadgetbridge. If so we could investigate why it does bit work.

**Comment by andyb9** [comment]
@ashimokawa 

dont get more wrong, i am not saying that it should work or asking why it is not working , all i am asking is for clarification as in more like a discussion for clarification sake - 

i.e. **is it because of Gadgetbridge that's why the 'companion app' is not working** with regards to replying to a notification with voice only? 

as the companion app mentioned _is working_ when you choose to reply with emoji or with canned responses.

and re your question as to wether i had enabled 3rd party support in Gadgetbridge - 

Yes i did and that is why the companion app is working when replying to the same notification with emoji as well as working ok when you send a canned response. With canned responses and emoji, it works and the canned response or emoji is accepted and sent to the android companion app and companion app is brought to the fore on the android phone in response to the canned response or emoji.

- however with a reply with voice, it tries to record the voice response (ie you can see the pebble doing so with the recording animaton on the pebble) but then after some seconds it times out with the message 'Dictation not available' showing up for a few secs and then it gives up and goes back to the notification message for you to use canned responses or emoji if you want to.

**Comment by ashimokawa** [comment]
I am not sure why dictation is unavailable.
It might be our fault. If so we can work on it (actually I can't because my pebble classic has no mic)
Is the companion app open source?

To answer your question: We want to fully support android companion apps (aka pebblekit apps)

Everything that does not work is considered a bug.

**Comment by andyb9** [comment]
@ashimokawa 

not sure if the AWreply.apk is opensource - have sent a message to the developer regarding that, will response back as soon as he get back to me.

**Comment by ashimokawa** [comment]
Tried to install the pbw but it is incompatible with the original pebble

The apk has no permissions so I assume they use some google voice APIs and I don't have these either. Do you have the gapps play services etc?

If not that might be the reason.

We need the source to confirm.

**Comment by danielegobbetti** [comment]
It is definitely GB that does not support dictation. The watch wants to open a "dictation session" and that request is ignored by GB. Openening the session is [fairly easy](https://github.com/pebble/libpebble2/blob/53595287477b436c3a03da6689d81055391eb70e/tests/test_voice_protocol.py) but then we would get a raw speex stream and nothing more.

**Comment by ashimokawa** [comment]
So speech to text is handled by the pebble app and not the companion app?

**Comment by danielegobbetti** [comment]
@ashimokawa I think so. I *believe* the companion app only gets access to the transcribed message.

**Comment by andyb9** [comment]
@ashimokawa 

re gapps play sevices 
I dont have gapps play services on my android tablet but have it on my android phone but the android phone is never connected to the internet if that makes a difference but voice reply dont work on both the tablet and on the android phone, whiles canned responses and emoji responses work on both.

**Comment by andyb9** [comment]
@danielegobbetti 

re: _It is definitely GB that does not support dictation_

this may indeed be the reason why it doesnt work, as other pebble apps that i have tried also do not seem to work re voice/dictation and end up giving up with the same error message (Dictation not available) when i try to record any voice just like the AWreply.apk.

**Comment by andyb9** [comment]
@danielegobbetti 

re:
> @ashimokawa I think so. I believe the companion app only gets access to the transcribed message.

so does that means the error message - '**_Dictation not available_**' is sent to the pebble from Gadgetbridge on the android phone or is that message coming from the pebble?

**Comment by danielegobbetti** [comment]
> so does that means the error message - 'Dictation not available' is sent to the pebble from Gadgetbridge on the android phone or is that message coming from the pebble (Pebble Time Steel)?

This is how I understand the documentation:
1 - watch asks to open a "session" to the phone (actually to the official app / GB)
2 - official app confirms the session 
3 - watch sends audio (encoded with the parameter specified in the session)
4 - magic happens and voice becomes text

We do not confirm/open sessions at steps 2, hence the watch shows the error message.

**Comment by andyb9** [comment]
@danielegobbetti 

re:

> We do not confirm/open sessions at steps 2, hence the watch shows the error message.

thanks for that step-by-step logic flow, sure makes sense now :-)

**Comment by andyb9** [comment]
@ashimokawa 

finally got a response from the developer and this was the response -

> "Unfortunately I don't have the source of it anymore due to a harddisk crash a while ago. I can check some of my backups to see if I have a version left somewhere, I'll keep you updated if I find anything."

so bad news on that front for now i guess.

**Comment by ashimokawa** [comment]
Anyway, it will never work because there is no open source offline speech recognition service we could plug into Gadgetbridge.

**Comment by andyb9** [comment]
@ashimokawa 

yeah, i understand, thanks for all your comments and help, i now have a better understanding of Gadgetbridge :-)

**Comment by ashimokawa** [comment]
You are welcome - as soon as there is some speech recognition software out there we could support - we will are eager to do so.

**Comment by cpfeiffer** [comment]
Might have a look at pocketsphinx.

**Comment by IzzySoft** [comment]
Might want to link this to #189 (and yes, @danielegobbetti already mentioned PocketSphinx over there).

**Comment by ashimokawa** [comment]
PocketSphinx is completely useless in my opinion. Its not a dictation system if I am not mistaken.

Maybe it can be trained to distinguish "red" and "blue" with 50% accuracy 😈

I hope someone can prove me wrong though...

**Comment by davidelang** [comment]
could you put in the framework to accept the audio from the watches and then return a canned message that it's not enabled?

That way the changes to then send the audio to some software/service and return those results would be much smaller.

I'd actually love to see several options available, PocketSphinx would be one (even if it's not very accurate), but I think it should also support using the several Internet based services (requiring a configuration change by the user). We now have Google, Amazon, Dragon, Apple, and others who have/use/offer transcription services. I would agree that picking one and becoming dependent on it would be a bad thing, but allowing the users to pick one until a free option is available is not inherently evil.

Even RMS agrees that a mostly free system is better than a proprietary system.

With Pebble being sold, you have a nice window to attract users to an option that doesn't put them at the mercy of Fitbit, make use of it to convert users (and if you wait until Fitbit starts reducing services to start providing an option, it will be too late)

**Comment by danielegobbetti** [comment]
Free Software is mostly about "I can" and "we can" and less about telling people what "*they* could".
Code related to voice has been in libpebble2 for a long long time, there is nothing arcane to figure out. If you feel the need for it, I'll gladly review any PR. Some basic boilerplate code to interpret the opening of a dictation session is already part of pebbleprotocol. Looking forward to your contribution.

**Comment by IzzySoft** [comment]
@davidelang but please note that Gadgetbridge won't add the Internet permission. So if you want to use some 3rd party internet service, you'll have to do that via a 3rd party app. Not that I am/we are opposed to voice support, don't get me wrong :)

**Comment by davidelang** [comment]
@IzzySoft, that's reasonable.

In that case, creating stub functionality that implements that pebble communications side of things would still be useful. Then a separate app could be created (or found) that does the Internet communication side (or does the transcription locally)

I can provide assistance in testing any such code (I have a pebble and pebble time available)

@daniel, there are more ways to contribute to Open Source and Free Software than just writing code. I've contributed some code to projects, but end up spending most of my time answering questions and helping people troubleshoot so that the core developers aren't distracted from writing code :-)

**Comment by danielegobbetti** [comment]
Please refer to #189, closing this.
