### ISSUE TITLE
Configuring pebble watchfaces with keys whose index is zero fails

### ISSUE THREAD

**Issue by tslilc** [Freeyourgadget/Gadgetbridge#419]
Hi all,

I may have misdiagnosed this, but it would seem that whenever a watchface has a configuration option whose key index is zero, gadgetbridge complains that it can't find that key in the cache and fails to send the updated configuration. 

To see this, try the [Squared](https://github.com/lastfuture/Pebble-Time-Watchface-Squared-4.0/) watchface (and note that `large_mode` is the [zeroth key](https://github.com/lastfuture/Pebble-Time-Watchface-Squared-4.0/blob/master/src/pebble-app.js)) or the [Miami Nights Extra](https://apps.getpebble.com/en_US/application/57ee926944581e90d40000d5?section=watchfaces) watchface for which `KEY_DATE_FORMAT` is the zeroth key (AFAICT).

It's hard for me to be sure, but this seems like a really convincing coincidence.

**Comment by ashimokawa** [comment]
Can confirm with squared, thanks for reporting.

**Comment by ashimokawa** [comment]
Fixed, will be in the next release.
Thanks for reporting!

**Comment by tslilc** [comment]
Brilliant, thanks so much for your continued efforts!
