### ISSUE TITLE
Mi Band: Locate Device

### ISSUE THREAD

**Issue by chrisvella** [Freeyourgadget/Gadgetbridge#42]
Would it be possible to implement a feature to assist in finding a missing band? I was thinking a new item under the hamburger menu "Find Lost Band". All it would do is make the band continuously buzz until stopped by the user. 

Thank you for the great app. Really enjoying watching it progress.

**Comment by cpfeiffer** [comment]
Yes, very good idea.

**Comment by cpfeiffer** [comment]
@ashimokawa is this really Mi Band specific? I have an implementation but I didn't deliberately disable it for the Pebble.

**Comment by ashimokawa** [comment]
Now that you mention it - no.
On the Pebble this can be done with simulating incoming call.
And that can be done from the debug menu ;)

If we had our own "Gadgetbridge" watch app running on the pebble, then we could do it without simulating calls.

**Comment by cpfeiffer** [comment]
Ok, then you can add that to PebbleProtocol.encodeFindDevice() :-)

**Comment by chrisvella** [comment]
Works really well. Fantastic work! Gadgetbridge is coming along nicely.

**Comment by cpfeiffer** [comment]
Thanks for the kind words :-)

**Comment by chrisvella** [comment]
Using find your device results in the alarms being opened with the latest master. Not sure if this is appropriate here or with the alarm ticket.

**Comment by danielegobbetti** [comment]
Thanks for the report @chrisvella , it should be now fixed in master through dfea2cbcc1d069ca33e70a54834c24de12b1971e
