### ISSUE TITLE
Documentation is unclear -- What alarms is "reserve alarms" using?

### ISSUE THREAD

**Issue by ShapeShifter499** [Freeyourgadget/Gadgetbridge#424]
In Gadgetbridge settings there is a setting for "Alarms to reserve for upcoming events" what alarms are being used? Are these alarms taken from the calendar app or the clock app?

I'd like to setup a Mi Band 1A for my mom just to remind her of when to take prescriptions. I only need to set up three daily alarms and I want to make sure they still work regardless if the phone is connected or has power. I'm unsure how to preform this setup.

**Comment by ShapeShifter499** [comment]
Ok so I think I get it, if I set "Alarms to reserve for upcoming events" to zero I can then set 3 alarms which is perfect for my current use case. Still not clear where the alarms come from if I set the Alarms to reserve for upcoming events" to a number above zero. 

I would like to also add, do these synced alarms stay on the Mi Band 1A forever?  If the Mi Band 1A runs out of power or is away from the paired phone for a long enough time will the device forget these alarms?

**Comment by danielegobbetti** [comment]
Miband has a limit of three alarms. Gadgetbridge is able to set all three of them. If you choose to reserve some for the calendar event they will not be available in the Gadgetbridge GUI and will be synced to the events in android calendar.

Manually set alarms can have repetition rules, these will be honored by the band itself so no need to be connected. Automatically synchronized alarms (reserved for calendar) are always "one off", even if the android event has repetition rules set. Hope this answers your question.

You are welcome to edit the wiki to clarify the points that weren't clear to you.

**Comment by ShapeShifter499** [comment]
@danielegobbetti So if I set "Alarms to reserve for upcoming events" greater than zero Gadgetbridge will sync whatever alarms or calendar events I have on my phone up to 3 events ahead?

**Comment by ShapeShifter499** [comment]
@danielegobbetti I updated the wiki, let me know how it looks. https://github.com/Freeyourgadget/Gadgetbridge/wiki/Configuration      I also had no idea about the setting "Device time offset in hours (for detecting sleep of shift workers)"  but I figured it out after a search led me to https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandDateConverter.java.   I just copied and pasted the comment about that setting that is found at the bottom of that file.

**Comment by ShapeShifter499** [comment]
Please close this issue if the wiki documentation edit is correct.

**Comment by cpfeiffer** [comment]
Thanks! I clarified a few parts -- hope it's still understandable.

**Comment by ShapeShifter499** [comment]
@cpfeiffer Looks great but could you please clarify one other thing?   When "Alarms to reserve for upcoming events" is set, does Gadgetbridge only get alarms from future calendar events and not from alarms set in the clock app?
