### ISSUE TITLE
Mi Band 2 step count

### ISSUE THREAD

**Issue by misterabdullahAziz** [Freeyourgadget/Gadgetbridge#428]
Hi, 

Hope you are fine. All i need is, I have Mi band 2. But i am not able to get the steps count from my mi band. Please help me if you have done this. 

Thanks

**Comment by cpfeiffer** [comment]
Hi,

we do not support this yet, but it is planned for the near future.

**Comment by misterabdullahAziz** [comment]
Do you know the uuid for steps in mi band 2. 
like can i get the documentation of mi band 2 uuids?

**Comment by cpfeiffer** [comment]
No, I don't think there is any documentation yet. If you have some time, we can work on it to fine out and get it implemented. There are some btsnoops in #323.

**Comment by cpfeiffer** [comment]
This works by now. You need characteristic 00000004-0000-3512-2118-0009af100700 and 5.

**Comment by MarcHeinrich** [comment]
Sorry if i wake something unnecessary but i thought you would get the step count from characteristic 00000007-0000-3512-2118-0009af100700 or am i wrong?

**Comment by MarcHeinrich** [comment]
@cpfeiffer I don't know you have this information but this characteristic (00000007-0000-3512-2118-0009af100700) gives more data then step count depending on the firmware version i suppose, because i tested it with 2 different ones and got different messages.
My Mi Band 2 with firmware 1.0.1.39 got this for example "0C 4C 00 00 00 1F 00 00 00 01 00 00 00"
but my other band with 1.0.0.34 got something like this "00 74 00 00 00"

The fist message is formated this way:
2 Byte step value (here 0c 4c)
4 Byte distance (here 00 00 00 1f)
4 Byte calories(here 00 00 00 01)
The last 3 byte i can't figure out they never changed for me.

**Comment by cpfeiffer** [comment]
@MarcHeinrich Good find!

We can compare these values with those that the band displays, however 31m does not quite match 76 steps, unless they use a dynamic calculation based on the walking/running style.

Something between 50 and 60m would be more sensible for 76 steps.

**Comment by cpfeiffer** [comment]
Also see #640

**Comment by MarcHeinrich** [comment]
@cpfeiffer I checked the value the band displays and read the value from the notify i get when reading 00000007-0000-3512-2118-0009af100700
In my case i got the notify:
0C 51 00 00 00 34 00 00 00 01 00 00 00 
Displayed by the band:
Steps 81 --> 51 in the notify
Distance 52 meter --> 34 in the notify
Calories 1 --> 01 in the notify

It looks like it is just the distance in meter but i agree the first value was too low maybe my user setting were off after a few test and for that reason i got such a short distance.
The values above are with the user settings: male, 170cm Height

In generall i guess this is not the best spot to write this message. Should i have posted this in #640?
Sry i am new to this and i don't know much about the  formal rules.

**Comment by Vebryn** [comment]
Is that mean that we receive additional distance and calories measurements from current list : step count, heart rate, raw_intensity and raw_kind ?

**Comment by MarcHeinrich** [comment]
Yes we get these values with the step count as a part of the notify but like i mentioned before it does not give this information for every firmware version. These vlaues are not stored in the activity data as far as i know but i would need to test this to verify. From my current information we do only get these from the steps notify but that should be enaugh to use them

**Comment by aytunch** [comment]
@MarcHeinrich Thanks for the logs and explanation. Would you help me get real time continuous heart rate info just like you did with the step count values? Which steps do we need to follow?. I found some info about sending x15x01x01 + etc to hrm_ctrl characteristic and then pinging every 12 seconds. Can somebody point the code that does this real time data setup? Thanks.
