### ISSUE TITLE
Pebble 2: reconnect fails on some phones

### ISSUE THREAD

**Issue by ashimokawa** [Freeyourgadget/Gadgetbridge#432]
~~This is a known issue and no effort has been made so far to fix it.~~

Fixed for some, still broken for others.

**Comment by ashimokawa** [comment]
I am closing this because it works for me(tm).
This is far from being good code since it is based on the old BT classing IO Thread and the only communication channel between that and our new BLE code are two piped streams.
Doing this properly would have taken a lot of refactoring and I just want to have that shiny new watch on my wrist working for daily use.

**Comment by pseudotechy** [comment]
@ashimokawa  this worked for me to. I have been running Gadgetbridge all day and haven't had to manually reconnect.  I have done one specific test where I walked away from my phone until it disconnected and it automatically connected with no intervention when I returned in range.

**Comment by pseudotechy** [comment]
I installed the F-Droid release 0.14.0 on 11/22.  Ever since then Gadgetbridge has had an issue where it looses the connection and gets stuck in the "Connecting" status.  The watch shows that it is disconnected. 

I can only get it to sync by force quitting Gadgetbridge.  When I open it again it reconnects perfectly. 

I have a log where I started logging and when I noticed this problem I went through the quit, restart, connect sequence and after a minute stopped logging so the reconnect should be at the end. Let me know if this helpful for you and I can send it.

**Comment by ashimokawa** [comment]
@pseudotechy 
Yes, please send it.
Why did is disconnect? Did you go out of range?
I have fixed a bug in 0.14.2 which caused Gadgetbridge to disconnect when other BLE devices were in use.
Should pop up on f-droid in the next 24 hours or so.

**Comment by IzzySoft** [comment]
@pseudotechy what you describe sounds like what I experience frequently with my Time Steel (not 2). Have you tried just switching Bluetooth off on the Android device, count to 3, and switch it on again? That helps in my case.

**Comment by pseudotechy** [comment]
@ashimokawa - yes it went out of range.   I'm not paired with any other BLE devices. I installed 0.14.2 tonight from F-Droid and it disconnected again when I went outside. I'll send the log that I collected with 0.14.1
@IzzySoft I turned Bluetooth on and off a couple of times and it did allow Gadgetbridge to reconnect. 

I just ran a more controlled test where I confirmed everything was connected. I walked away and walked back.  No connection and stuck at "Connecting".   I cycled Bluetooth and it connected after a few seconds.

**Comment by ashimokawa** [comment]
@pseudotechy 
I also had a non working reconnect yesterday. It works for me most of the time but not always. This will be fixed, of course it can't stay like this.

**Comment by IzzySoft** [comment]
@pseudotechy 

> I cycled Bluetooth and it connected after a few seconds.

Matches my experience with the PTS. Not always needed, though – but if stuck in "waiting for connection", this always helped in my case. Luckily, just happens 2-3 times a week here; usually it reconnects fine even when my Android device comes out of Airplane mode in the morning :)

**Comment by ashimokawa** [comment]
@IzzySoft

LE reconnect is different right now. I think it will retry indefinitely, because the outer code thinks the pebble is connected while the le code is still connecting. So it starts to count from 0 all the time.

This was for the sake of non invasively plugging in le code in the current GB code.

You are welcome to join the LE club with your PTS with the next release, probably 0.14.3 . You won't loose data and can switch back to classic BT easily. ;)

PS: Sorry I edited your post instead of replying with the mobile client :(

**Comment by IzzySoft** [comment]
@ashimokawa no prob, and thanks for the heads-up! I just updated to 0.14.2 (F-Droid took that long to list it). Probably will update the FW tonight (4.2), and then see whether I join the club with 0.14.3. Maybe a Wiki entry is due then, listing the steps needed and the implications – wasn't there something like GB thinks it's a different device then?

**Comment by ashimokawa** [comment]
@IzzySoft 
Exacty that has been fixed in master git and will be in the next release. Pairing an LE Pebble will require you to do it in Gadgetbridge and not in Android settings anyway (we can't fix it, it is how it is). And the big change in git master is now that pairing a LE Pebble will associate it to its parent BT Classic device (required to be added before in Gadgetbridge). You will only see one device in Gadgetbridge then but can switch between LE and Classic connections in Pebble settings.

HOWTO (copy and pasted from the commit log message)

1) Pair you normal Pebble (not necessary if already done), make sure it was connected once
2) Unpair your LE pebble if already paired
3) Switch on "Always prefer BLE" in Pebble Settings
4) Tap on the + in Control Center to add a new device
5) Pair your Pebble-LE XXXX or Pebble Time LE XXXX inside Gadgetbridge's Device Discovery actibity

Now Gadgetbridge will connect to your LE Pebble when tapping on Pebble XXXX if "Always Prefer BLE" option is enabled.
You can easily switch back to classic LE by turning that option off again

**Comment by danielegobbetti** [comment]
Speaking of pebble time watches and LE and reconnect, it happened to me as well to see GB stuck on "connecting". What worked here was to toggle the BT *on the watch* (I have the airplane mode toggle bound to long press of an hardware button). Perhaps you can give it a try on p2 as well

**Comment by pseudotechy** [comment]
@danielegobbetti -  I tried the airplane mode toggle on the watch and it had no affect on Gadgetbridge reconnecting with the P2

@ashimokawa  - I'll try and observe this more today, but it seemed that Gadgetbridge timed out of the "Connecting" mode and went to "Disconnected" after that I tapped to initiate a reconnect and it did successfully.

**Comment by ashimokawa** [comment]
@pseudotechy 
Judging from your logs the service seems to just die. There is no logged disconnect, no reconnect, nothing :(

Maybe Android killed Gadgetbridge (this is not in the logs).

**Comment by pseudotechy** [comment]
@ashimokawa 
In the log file - I did a Force Quit of Gadgetbridge because it wasn't reconnecting.  This would have been just before the reconnect at the end of the file.  I don't know where it disconnected.


Separately - I just confirmed that after an out of range disconnect Gadgetbridge gets stuck on "Connecting" after a while about an hour (I didn't time it) it goes to "Disconnected" as I describe above and allows me to initiate a successful reconnect.  I'll start a log write and try and work through that sequence again.

**Comment by IzzySoft** [comment]
@ashimokawa Do you want to put [those instructions](https://github.com/Freeyourgadget/Gadgetbridge/issues/432#issuecomment-263283512) into the Wiki – or shall we rather wait until it's out and approved by other users?

**Comment by ashimokawa** [comment]
@pseudotechy 
Since this works for me I would indeed be interested in your logs

@IzzySoft 
Minus the spelling mistakes, plus rephrasing it a bit, yes, should be in wiki, but either note that it needs Gadetbridge 0.14.3 or wait until .3 is out. I don't want to wait long, even if this issue remains unresoved - to get more feedback.

**Comment by IzzySoft** [comment]
@ashimokawa OK, waiting until 0.14.3 is available on F-Droid, then checking to add "the facts" to the Wiki. Marked the follow-up on my end :stuck_out_tongue_winking_eye:

**Comment by ashimokawa** [comment]
@pseudotechy 
Thanks for the logs, I think I know what is going on. Unfortunately no fix in 0.14.3 since we had to tag that early due to a Mi regression.

@IzzySoft 
Thanks, looking forward to your wiki update. f-droid became very slow unfortunately. :-1:

**Comment by IzzySoft** [comment]
@ashimokawa indeed it became slow. Almost 1 week behind. If there would be an `.apk` attached to your `releases/` here I'd consider putting that into [my F-Droid compatible repo](https://android.izzysoft.de/repo) for faster updates. Delay there is usually less than 24h. Different signature, I know, but that would be a one-time-action.

**Comment by Almtesh** [comment]
The problem is the same on my Sony Xperia M2 and my mi band 2.

**Comment by ashimokawa** [comment]
I fixed at least one "application not responding" problem **and** a problem that occurred if the first reconnect try did not succeed (in that case it never worked). The timeout on my phone was way to long so that all tests succeeded (I was not patient enough to wait about a minute during tests)

The code will be in 0.14.4 after some tests

@danielegobbetti @pseudotechy Thanks for the logs, they helped a lot!

@Almtesh 
I deleted your comment, because this issue is about the Pebble2 and code wise the bluetooth code is completely unrelated to the Mi bluetooth code.

**Comment by ThatGeoGuy** [comment]
I'm running Gadgetbridge 0.14.2, and am trying to reconnect to my phone (HTC 10, stock ROM) after walking away from my phone. I notice that it will not reconnect automatically, but if I long press the device in Gadgetbridge, hit "Disconnect", and then tap it again to reconnect, it connects within a second or two and everything is good again. I imagine that this may change in 0.14.4 (I'll wait for the FDroid version), but it is annoying in some ways that I have to disconnect / reconnect manually each time I walk away. Not a deal breaker because so far I'm loving how well everything works, but certainly a rough edge 😄 

Is this behaviour what was described above? It seems to match what happened to @pseudotechy, however I didn't have to quit / restart the app, just disconnect the device and reconnect from scratch again.

**Comment by ashimokawa** [comment]
0.14.4 is out on f-droid. Please try.
For me it seems to be very stable. If it is not for you, please report.
BLE is a pain on Android and buggy as hell. I know why pebble chose to not support it on older pebbles. So if it does not work it could be a missing workaround that is present in the official app. I bet they had more than one developer working on that full time for a while...

**Comment by ThatGeoGuy** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Excellent! It seems 0.14.4 fixes the issue. I tested by doing the following:

1. Connect normally
2. Turn Bluetooth off on the pebble in the settings
3. Turn it back on
4. Wait for the watch to reconnect to gadgetbridge

So far, I have not noticed any troubles.

Thanks, and cheers!
- --
Jeremy Steward
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJWBAEBCgBABQJYRYIsORxKZXJlbXkgU3Rld2FyZCAoQm9ybiAxOTkyLTAxLTE0
LCBpbiBHcmVlbmZpZWxkIFBhcmssIFFDKQAKCRACdasEihv39oVpD/oDyWJjpszs
q+U2BcC+C9j+/mNRk/HQAGHdNHbrDs38NRpx7i9HS60eiWGSsGBGxy6l3mOidF5K
LmVHyLW7RWS4SEJOBedz2OpU7vx3qw3h86Csga71xGptfChtjr9na9MrjkVhxwTA
DHsssYDW4O8Fm2KfdARdx9WIAz9/fVTIuUfjAJp4POctyNUGBZzRIKQSiGM8W0Lk
y8lPERlg8oCqHGpPnO3ppoSinoUewZuMRETM54bXwQytje5/7eEQ1U8q2o5da0Vz
jnMNF3hpKc7Lrut3OViSHrc8umI1CELpFxBwvthqoR7IOkDAhMTcJs8HX/Cev+Fb
sUmAr6e2nqC3iRINlJzL08cofbdiRBnpiQvK4wTIYUq3dVqnE2plzJrxhy/pAJi/
N91l1XXd26uBru4wj1bE8FHD02xChio72C39avzDE/bjNw2jfuhWLf8Y8G8mPrOv
fMlLfUMvWYfGIe1HD1S/Mhxw4Q3ESmVIOlMbAba8GOvJUwDapCVrQH/480Qihw1p
jywvBXEd/FBE2j/01u/JiQzvTxBPRkdknr+AegPbzovdzEHRCyLU/kpwGxeNmXl1
mJFYssN/Xnb2B2SHw2xXpV0C80A7WWvuqvhY3XTMivy+FCdfCDNrtfIvvbtqwdak
J5zHzrk3TTl0NRzhttdu58gW0d+Iu4dtYQ==
=lMXu
-----END PGP SIGNATURE-----

**Comment by pseudotechy** [comment]
I updated to 0.14.4 this morning and have run a couple of tests by going out of range.  Once it didn't reconnect, but when I tried to replicate the issue it reconnected. 
Much better then previous versions of Gadgetbridge in terms of reconnect.   I'll keep testing today and report back if I have any problems.

**Comment by itmike** [comment]
I can also confirm that reconnects now seem to work(with 0.14.4). Great job!

**Comment by ashimokawa** [comment]
@itmike 
@pseudotechy 
Thanks for the feedback. :+1: 
I will close this now.

**Comment by tecufanujacu** [comment]
I have a pebble classic and I'm trying to use it via BLE connection, I correctly followed the steps to connect it and everything is ok until i turn off and turn on the smartwatch, then then gadgetbridge isn't able to reconnect to it via BLE.

**Comment by danielegobbetti** [comment]
Can you try doing the following and report if anything changes?

- Start with BT turned on on both watch and pebble
- if you can, launch adb logcat prom the pc and connect the android device
- be sure you are seeing your watchface on the pebble
- tap the pebble in gadgetbridge, it will say "connecting" and the icon will be gray
- in logcat, you'll see a few entries and then nothing else
- go to the Bluetooth menu on the pebble (settings - Bluetooth) do not choose any entry in this menu
- in logcat, you could be seeing that new lines are coming in
- at this point, the icon in gadgetbridge could turn blue (label will still be "connecting" for some seconds)

I have to do this procedure once in a while with my pebble time (logcat is optional, just to understand if something is going on), let me know if it's needed also on your device in which case we could look into it as an actual problem (I thought the BT on my phone had issues).

**Comment by tecufanujacu** [comment]
Just tried with no changes, I took a log and if you want i can send it to you.
I noticed that gadgetbridge fails to reconnect also after that i turn off and on the bluetooh on the pebble, to solve the problem i have to unpair the normal pebble and the BLE and then i have to reconnect them.

**Comment by danielegobbetti** [comment]
Try to unpair and pair only LE: gadgetbridge should show your pebble also when it's unpaired, if it doesn't let us know and wait before proceeding.

**Comment by tecufanujacu** [comment]
Already tried with same behavior.
I noticed that if i use BLE connecting both, normal and LE, on the Pebble I see the name of the paired phone with the wording "LE only".
If instead I connect the pebble with only normal bluetooth or only with LE on the Pebble I see only the name of the paired phone.

**Comment by ashimokawa** [comment]
@tecufanujacu 
I will check on my OG, but I guess it will be the same.

I hacked BLE support to use my Pebble 2 and I enabled it for other devices too for testing.
It seems to work well with Pebble Time running FW 4.3 but not with the OG running 3.12.

Right now I am quite busy with other tasks and getting it to work is not high priority, but help is appreciated! We accept patches ;)

**Comment by tecufanujacu** [comment]
Oh, well.
Unfortunately I don't think to be able to help you in coding but if you need someone to get logs or make some try, I'm here.

**Comment by tecufanujacu** [comment]
Hello, this is not an ETA request, I only would to know if there is any hope to solve this problem and connect also the old Pebble with BLE.
