### ISSUE TITLE
Pebble 2: Connect only works when P2 was paired through the official app or weird workaround had been applied

### ISSUE THREAD

**Issue by ashimokawa** [Freeyourgadget/Gadgetbridge#433]
Weird workaround that works for me when not having paired though the official app:

- patch the source code so that Gadgetbridge will list a non-paired P2
- connect to it
- confirm paring
- ~~toggle BT off and on on P2 and Phone~~
- ~~start a random watchface~~
- ~~tap connect in gadgetbridge~~
- ~~count to six~~
- ~~go the Bluetooth setting on P2~~
- connected!
- now the patch can be reverted because Gadgetbridge knows about the P2 and has it in its database

(yes really - I had to do all of the above)

It was reported to work without this workaround in #413 when having paired through the official app before. ~~So we need to figure out the magic Pebble does.~~

**Comment by ashimokawa** [comment]
Greatly improved at least for me now in master

**Comment by pseudotechy** [comment]
@ashimokawa I did a full reset of my Pebble 2 tonight so I could clear all of the old apps and can not get it paired back to Gadgetbridge.
I was able to pair the Pebble, but Pebble is now stuck on a screen waiting for a confirmation code. I was never prompted for it and there was not a notification in the drawer.   It looks like I'll need to install the official app again to accomplish first pairing


Click (+) 
Pebbel XXXX is recognized and choose to pair
Pop up "Pair with Pebble XXXX Type the pairing code and then press Return of Enter
Allow Pebble 7377 to access your contacts and call history" 

Accept and Pair/Also did not accept and Pair
Pebble asks to confirm
Gadgetbridge shows connected (and displays the FW and HW values)
Pebble is still stuck on a screen that says pebble.com/app
Pebble will not respond to debug messages

Still using the master from a couple nights ago.

**Comment by pseudotechy** [comment]
I installed the official App. It updated the Firmware to v4.2.
The official app never asked me to input a code or do anything special to pair.
I then uninstalled official app and rebooted the phone and watch
On pairing in Gadgetbridge everything happened as expected with no request for a code.

**Comment by ashimokawa** [comment]
@pseudotechy 
You were in a recovery firmware! That firmware can't show notifications, it has one purpose: flash a firmware. And that even works from Gadgetbride! It has not been tested with the Pebble 2 though, and I expect that you will need luck for it to complete due to #434 

So everyhing worked as expected and you also proved that Gadgetbridge can connect to the recovery firmware :+1: 

(When you factory reset a pebble you will end up in recovery and will have to flash a firmware)
Also see our wiki https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Getting-Started
