### ISSUE TITLE
Pebble 2: Installation of firmware or watchapps fails (fuzzy behavour)

### ISSUE THREAD

**Issue by ashimokawa** [Freeyourgadget/Gadgetbridge#434]
cause in unknown, but maybe we have to properly wait until our packets get ACKed instead of sleeping 200ms
:speak_no_evil:

**Comment by pseudotechy** [comment]
I was unable to replicate this.  Do you have a more specific scenario I can attempt? 

I installed 3 apps and 3 watch faces - some were new and some had already been installed via the official app and I was installing them again with Gadgetbridge.   Only one didn't install the first time.  Nothing locked up and I successfully installed it the second time.

**Comment by ashimokawa** [comment]
@pseudotechy 
I don't even think this is related to installing stuff. Installing is just the most stressful operation for the code and most likely to trigger bugs.

I think the situation should be better when dealing with ACKs better. Maybe for 0.14.1 ;)

**Comment by ashimokawa** [comment]
Tested a firmware update on the OG Pebble through LE and it succeeded.
Firmware upgrade on the Pebble 2 however failed.
I noticed that I do not get ACKs for all GATT packages I send on the P2 (not tested with OG), they seem to arrive anyway. Guess I need to do more research on that.

**Comment by ashimokawa** [comment]
I am closing this, because with current workarounds I never had this again.
