### ISSUE TITLE
Mi: Activity data transfer drains phone battery and makes notification drawer unusable

### ISSUE THREAD

**Issue by ashimokawa** [Freeyourgadget/Gadgetbridge#438]
I suspect the progress bar is updated to often

**Comment by 6arms1leg** [comment]
I also noticed that issue on my friends phone (Samsung Galaxy S5, Stock OS). On mine (HTC One m8, CM12.1), however, I don't have that issue.

**Comment by cpfeiffer** [comment]
@ashimokawa Please test and report if this improves the situation for you.

**Comment by ashimokawa** [comment]
No problems anymore. Closing
