### ISSUE TITLE
"Acquire location" doesn't work

### ISSUE THREAD

**Issue by ec1oud** [Freeyourgadget/Gadgetbridge#439]
I'm on a Samsung Galaxy Note N7000 running CM 11-20160815-nightly (CM11 was never fully released for this phone) - Android 4.4.4.  GPS works fine in other apps (e.g. maps.me, osmtracker etc.)  But in the pebble settings section of GB, pressing the "acquire location" button doesn't seem to do anything - lat and lon stayed at 0 and 0, and I don't see the GPS icon showing up in the notification area, like it does when any other app accesses the GPS.  

I worked around it by entering my lat/lon manually.  It didn't seem to affect sunrise/sunset times right away (not sure about that though) so I rebooted.  Then it affected tomorrow's sunrise/sunset times on the timeline, but not today's sunset time.

**Comment by ashimokawa** [comment]
We do not support gps as we do not have the permission.
So you need to enable a network location provider.
Personally I use that one:

https://f-droid.org/wiki/page/org.fitchfamily.android.gsmlocation

It uses an offline database with cell ids.

**Comment by danielegobbetti** [comment]
closing this since I assume it was just a misunderstanding of the supported features and no feedback

**Comment by ec1oud** [comment]
Well I still don't have it working, but maybe the offline database isn't set up right, or something.  I installed it from F-Droid.
