### ISSUE TITLE
Add Fitness Activity

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#44]
The user should be able to
- see and set a daily fitness goal (typicall in steps)
- see how many steps he has gone this day
- optionally see the "live" step count

Ideally there should also be some history fitness graph.

**Comment by halcyonest** [comment]
https://github.com/j4velin/Pedometer

There is an app called 'Pedometer' and it utilises step detection sensor on certain devices to track daily activity and organise it as a graph. Can we implement this kind of thing too? I need fitness activity tracker too.

**Comment by danielegobbetti** [comment]
@halcyonest in fact the data we get for the sleep activity is already containing all the kind of activities, and the code is already in master. There are some things missing until it can be displayed though:

- we are getting raw data, and it needs to be interpreted (pseudocode is available for instance [on XDA](http://forum.xda-developers.com/showpost.php?p=59426362&postcount=95), but I don't know how accurate it is: in this area you could help without being a java coder (the script in that xda thread is basically SQL + javascript, but the JS is kind of obfuscated and uses google services)
- the basic "pedometer" activity that uses the live steps we get from the miband is also something that may be added (the raw data I was mentioning above is far richer in detail, but it's trivial to get the actual steps count from the band)
- the band supports setting goal for the daily number of steps, this is also something that could be worked on with small effort
- probably much more I am forgetting :)

So if you could help either by coding or by contacting the OP of the thread on XDA and asking for human-friendly code, or reconstructing its behavior it would be wonderful!

WRT the pedometer app you posted I think it could be interesting to get inspiration for the UI, thanks!

**Comment by halcyonest** [comment]
I'd help if I could, but sadly I'm still learning... too difficult for me.

https://github.com/Freeyourgadget/Gadgetbridge/issues/47
http://www.ugopiemontese.eu/portfolio-item/openband-android-app/

I think we can use this code and make this feature available first.

**Comment by chrisvella** [comment]
Thats a fork of this: https://github.com/lwis/miband-notifier

**Comment by cpfeiffer** [comment]
@chrisvella fwiw, it actually does communicate directly with the device

**Comment by halcyonest** [comment]
@chrisvella

I'm using both Mi Band and OpenBand app. And as I check,

1. OpenBand does communicate directly with Mi Band.

2. OpenBand doesn't need original Xiaomi app, so OpenBand is a standalone app just like GadgetBridge.

3. OpenBand is different from Mi Band Notifier app which is from same developer.

4. It seems that source code of OpenBand app is not released yet.

So it will be good if we could implement fitness activity tracking feature from OpenBand app.

**Comment by chrisvella** [comment]
My mistake @halcyonest. I assumed miband-notifier used the official app as it does say it needs to be installed (apparently just for pairing). It also confused me that miband-notifier stopped working for when the Xiaomi app was updated.

Is this not the source code? https://github.com/UgoRaffaele/miband-notifier

**Comment by halcyonest** [comment]
My mistake either, There is a source code.

**Comment by cpfeiffer** [comment]
OpenBand by Ugo was initially his own implementation, but then he forked miband-notifier added his own features and named his version OpenBand.

The original Xiaomi app automatically updates itself **and** the firmware of the Mi Band. So if you use Mi Fit, you will always have the latest firmware, which means, that other apps may be broken because they changed the protocol. Which apparently they did, see https://github.com/lwis/miband-notifier/blob/master/README.md

**Comment by UgoRaffaele** [comment]
Hi Guys, I just discovered your app/repo.
Unfortunately I have been very busy at work for months, so I couldn't rewrite OpenBand as I wished. Also, a few firmware upgrades came up and a lot changed from what I quickly saw.

Keep up the good work and happy hacking! Maybe I'll try to contribute to your project in a near future ;)

**Comment by cpfeiffer** [comment]
Hey Ugo,
nice hearing from you again :-) We'd be happy to work together -- there's just so much one can do with these nice little toys. We have collected a long list of issues at https://github.com/Freeyourgadget/Gadgetbridge/issues and every second day a new idea pops up :-)

**Comment by danielegobbetti** [comment]
Closing since 0.4.5 was released
