### ISSUE TITLE
MiBand2 Set Time does not work

### ISSUE THREAD

**Issue by EureEminenz** [Freeyourgadget/Gadgetbridge#441]
Hello,

first I'd like to thank all you guys for your phenomenal work. Today I received my MiBand 2 and everything I need works fine, except setting time. It simply doesn't do that, neither automatically nor through the Button in Debug mode.
Here is a copy of part of the log file after triggering time setting via Debug mode.
`12:15:29.453 [main] INFO n.f.g.s.ServiceDeviceSupport - Ignoring set time because of throttling threshold reached
12:15:29.848 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.settime
12:15:29.850 [main] INFO n.f.g.s.d.m.MiBand2Support - Sending current time to Mi Band: 1. Dezember (1 Dec 2016 11:15:29 GMT)
12:15:29.851 [main] INFO n.f.g.s.d.m.MiBand2Support - Unable to set time -- characteristic not available `

FW is 1.0.0.34 and since FW update is not supported yet I don't know how to update it to verify whether the problem is related to FW.

Thanks

Andreas

**Comment by 6arms1leg** [comment]
I have the same issue with my Mi Band 2 (FW 1.0.0.19) on the latest GB version (0.14.3), but it definitely worked in previous GB versions (time was once set correctly and now has a drift of about 1min).

Here is my log of trying to set the time in the debug screen twice:
```
19:05:37.812 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.14.3
19:05:46.312 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.settime
19:05:46.313 [main] INFO  n.f.g.s.d.m.MiBand2Support - Sending current time to Mi Band: December 1 (1 Dec 2016 18:05:46 GMT)
19:05:46.314 [main] INFO  n.f.g.s.d.m.MiBand2Support - Unable to set time -- characteristic not available
19:05:46.314 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 7:05:46 PM: Transaction task: Set date and time with 0 actions
19:05:53.364 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.settime
19:05:53.368 [main] INFO  n.f.g.s.d.m.MiBand2Support - Sending current time to Mi Band: December 1 (1 Dec 2016 18:05:53 GMT)
19:05:53.371 [main] INFO  n.f.g.s.d.m.MiBand2Support - Unable to set time -- characteristic not available
19:05:53.374 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 7:05:53 PM: Transaction task: Set date and time with 0 actions
```

**Comment by EureEminenz** [comment]
I can confirm it is a specific problem with latest GB version since thanks to 6arms1leg I tried installing an older one (I choosed 0.14.0 since it's the oldest one still in F-Droid) and have been able to set my clock. For me that's fine since now I have accurate time and I assume it's going to drift slowly but nevertheless there seems to be a problem in 0.14.3 which hasen't been there at least in 0.14.0

**Comment by cpfeiffer** [comment]
Thanks, fixed.

**Comment by cpfeiffer** [comment]
(As an explanation: we need to send timestamps to the band in different formats: for the actual time it's with seconds precision, but for requesting activity data from a given time, it's in minutes precision.

Previously we sent both in minutes precision.
