### ISSUE TITLE
please provide a way of viewing debug messages from Pebble apps

### ISSUE THREAD

**Issue by ec1oud** [Freeyourgadget/Gadgetbridge#444]
It's difficult to develop and debug watch apps without being able to read the log messages, e.g.

 APP_LOG(APP_LOG_LEVEL_DEBUG, "my message %d", 42);

The original Pebble Android app just dumps them into the adb log, which is fine for me.  It's just a ring buffer in memory, which is a good thing.  The alternative would be to write a separate log file, but that would contribute to having the flash memory wear out sooner.  The adb log is a noisy one to watch... but I sometimes do adb log | grep whatever to find the log messages of interest, as long as they have a unique prefix.

**Comment by ashimokawa** [comment]
@ec1oud 
Yes totally agree - this is indeed easy to do.
Would a checkbox to enable debug in pebble setting be enough?
(That would be honored on connect only, so turning that on would require to reconnect)

Alternatively it could be a button in debug menu to turn it on on the fly but that would require to extend our internal interfaces.

**Comment by ec1oud** [comment]
It would even be OK if it's always on.

But sure, a checkbox is fine...  or another idea, if you can see the log level when those messages come across bluetooth, maybe offer a choice of which level to enable?  So far I think people typically comment out or disable most log messages before releasing a watch app, to avoid cluttering the log.  But maybe if they could be disabled, it would make more sense to leave some of them in, for the sake of spontaneous troubleshooting in the field.  OTOH they would waste bluetooth bandwidth and battery power, I suppose, so I'm not sure if that's a good practice.  It might be better if there was a way to push the log level as a setting to the watch, so that disabled messages aren't sent across, but that's one of those things that we can't change, I guess.

**Comment by ashimokawa** [comment]
@ec1oud 
You guessed right. We can't change that.
I will add such an option after the next release.

**Comment by ashimokawa** [comment]
Done in master.
Will be in the next release.

**Comment by ashimokawa** [comment]
I will close this as it is working in master and will be in 0.15.0

**Comment by ec1oud** [comment]
Thanks a bunch!  I didn't try building from source, but will look forward to the release.
