### ISSUE TITLE
Mi band 3 firmware update

### ISSUE THREAD

**Issue by iwex** [Freeyourgadget/Gadgetbridge#447]
Hello! Can't update my band.

It shows me "Element cannot be installed"

But this text is from https://github.com/Freeyourgadget/Gadgetbridge/blob/dbe90d7ae3e0bb3d741f72a71980dd7f91182f88/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/pebble/PBWInstallHandler.java#L50

[Mili_pro.fw.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/634121/Mili_pro.fw.zip)

**Comment by ashimokawa** [comment]
closing this

- There is no Mi band 3
- Zip files are for installing pebble apps not firmwares you would have to unpack this
- There is no firmware update support for Mi Band 2 yet

**Comment by ashimokawa** [comment]
see #427

**Comment by iwex** [comment]
Sorry, mi band 2 :)
