### ISSUE TITLE
Display battery status/charging for Mi Band 2

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#449]
Right now, there is no battery(/charging) status indication for the Mi Band 2 in GB. It's a basic but yet important feature, I think. :pray:

**Comment by cpfeiffer** [comment]
Yes, it's totally important, I just don't have an idea yet, how Mi2 does it. If anyone has a btsnoop to share that contains not much more than the battery information communication (and in addition, the reported battery state/extra information), then we could add this easily.

**Comment by cpfeiffer** [comment]
We don't know all things regarding battery information (e.g. how many times the band was charged), but that's good enough for now.

**Comment by 6arms1leg** [comment]
GB is one of my favorite projects on GitHub. The development pace is scary (incredible fast).
Many many thanks! :heart:
