### ISSUE TITLE
Regression - mi1s - steps per minute stays at 0 on Live Activity

### ISSUE THREAD

**Issue by rplevka** [Freeyourgadget/Gadgetbridge#450]
Having Live Activity displayed, I can see the `Total Steps` counter increasing and `Hearth rate` values being fed to the line chart regularly, but the `Steps per Minute` stays at 0 for both charts.

I've seen this working before (unsure of the version) thus this must be a regression

GB ver. 0.14.4
FW: 4.16.4.22
HR: 1.3.76.22
HW: 1S

**Comment by velowander** [comment]
With my MiBand 1S on 0.14.4 I confirm the Steps per minute of 0 during activity.
I noticed this in much of the 13.x series and 14.x.
My daily use version 0.12.2 does not have this issue (or issue #448 for that matter).

Thanks for posting.

**Comment by cpfeiffer** [comment]
Thanks, fixed.
