### ISSUE TITLE
WhatsApp notifications don't work

### ISSUE THREAD

**Issue by valneacsu** [Freeyourgadget/Gadgetbridge#456]
I've recently switched to GB and found that WhatsApp notifications do not work with my Pebble Steel. I tried fiddling with the various options (e.g. enable PebbleKit, Force BTLE, etc) and could not get WhatsApp notifications. Generic notification support is enabled and WhatsApp is not blacklisted. One datapoint is that I am getting notifications from Signal and Gmail.

**Comment by clemens23** [comment]
I can confirm this, i get notifications sometimes from WhatsApp to pebble Classic. I tested sending messages after another, the first with No notification, the second ok, third ok, and so on. After some Minutes doing nothing and starting again, the same, first NO notification and then it works. I find nothing in the logfile for NO. I tested with 6.0 and 14.1 cyanogenmod on a second device.

**Comment by danielegobbetti** [comment]
Next release contains additional log statements that should help us diagnosing this issue. If you're self compiling please pull current master and let us know. Hopefully you will see a
``Not forwarding notification, ...``
line in the logs.

**Comment by clemens23** [comment]
I see this in the log:
15:55:43.422 [Binder_2] INFO  n.f.g.e.NotificationListener - Not forwarding notification, FLAG_GROUP_SUMMARY is set

**Comment by danielegobbetti** [comment]
Thanks for the update, we know where to look now. Let's hope we find a way to fix this without breaking other apps' notifications :-)

**Comment by danielegobbetti** [comment]
@clemens23 it really seems to me we are doing the right thing here: Please see
https://developer.android.com/training/wearables/notifications/stacks.html "Add a Summary Notification" section.
I believe whatsapp may be sending the first message of a group with the flag set and then further updates in the same "group" without the flag. Could you please describe what happens on the android device when receiving notifications (i.e. if and when the "original" notification gets updated?).

**Comment by clemens23** [comment]
Thank you danielegobbetti

This is a logfile from the event.log with the app SysLog. The first WhatsApp sent 17:40 was not notified, the second at 17.42 was notified. I dont know if this helps in any way.  Maybe it is a problem with android/whatsapp



12-17 17:40:01.220 I/notification_enqueue( 2218): [10116,7926,com.whatsapp,1,NULL,0,Notification(pri=1 contentView=null vibrate=[0,750,250,750,250] sound=content://settings/system/notification_sound tick defaults=0x0 flags=0x200 color=0xff075e54 category=msg groupKey=group_key_messages actions=1 vis=PRIVATE publicVersion=Notification(pri=0 contentView=com.whatsapp/0x1090085 vibrate=null sound=null defaults=0x0 flags=0x0 color=0xff075e54 category=msg vis=PRIVATE)),0]

12-17 17:40:01.225 I/notification_alert( 2218): [0|com.whatsapp|1|null|10116,1,0,0]
12-17 17:40:01.238 I/am_pss  ( 2218): [14140,1000,com.android.settings,4167680,3678208]
12-17 17:40:04.207 I/sf_frame_dur(  883): [ColorFade,26,1,0,0,0,0,0]
12-17 17:42:00.849 I/notification_enqueue( 2218): [10116,7926,com.whatsapp,1,<email omitted>,0,Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x8 color=0x00000000 groupKey=group_key_messages vis=PRIVATE),0]

12-17 17:42:00.920 I/notification_enqueue( 2218): [10116,7926,com.whatsapp,1,NULL,0,Notification(pri=1 contentView=null vibrate=[0,750,250,750,250] sound=content://settings/system/notification_sound tick defaults=0x0 flags=0x200 color=0xff075e54 category=msg groupKey=group_key_messages actions=1 vis=PRIVATE publicVersion=Notification(pri=0 contentView=com.whatsapp/0x1090085 vibrate=null sound=null defaults=0x0 flags=0x0 color=0xff075e54 category=msg vis=PRIVATE)),1]
12-17 17:42:00.923 I/notification_alert( 2218): [0|com.whatsapp|1|null|10116,1,0,0]
12-17 17:42:06.577 I/am_pss  ( 2218): [13846,10013,com.android.providers.calendar,3073024,2564096]
12-17 17:42:07.982 I/force_gc( 5553): Binder
12-17 17:42:08.025 I/am_pss  ( 2218): [14059,10014,android.process.acore,5685248,5103616]
12-17 17:42:09.463 I/power_screen_state( 2218): [1,0,0,0]
12-17 17:42:09.463 I/screen_toggled( 2218): 1
12-17 17:42:09.464 I/power_screen_broadcast_send( 2218): 1
12-17 17:42:09.465 I/sysui_histogram( 4852): [note_load,3]
12-17 17:42:09.465 I/notification_panel_revealed( 2218): 3
12-17 17:42:09.469 I/sysui_view_visibility( 2218): [223,0]
12-17 17:42:09.470 I/sysui_histogram( 2218): [dozing_minutes,4]
12-17 17:42:09.473 I/sysui_histogram( 2218): [power_double_tap_interval,54076]
12-17 17:42:09.491 I/device_idle( 2218): [0,screen]
12-17 17:42:09.498 I/device_idle_off_start( 2218): screen
12-17 17:42:09.506 I/device_idle_off_complete( 2218): []
12-17 17:42:09.537 I/notification_cancel_all( 2218): [10044,10585,com.motorola.motodisplay,0,0,64,9,NULL]
12-17 17:42:09.716 I/sf_frame_dur(  883): [AOD,139,6,0,0,1,0,5]
12-17 17:42:09.853 I/power_screen_broadcast_done( 2218): [1,390,1]
12-17 17:42:10.238 I/force_gc( 2218): Binder
12-17 17:42:10.748 I/sysui_lockscreen_gesture( 4852): [1,97,1824]
12-17 17:42:10.904 I/notification_panel_hidden( 2218): []
12-17 17:42:10.905 I/screen_toggled( 4852): 2
12-17 17:42:10.913 I/am_resume_activity( 2218): [0,191750046,55,ginlemon.flowerpro/ginlemon.flower.HomeScreen]
12-17 17:42:10.940 I/notification_expansion( 2218): [0|com.whatsapp|1|null|10116,0,1,129720,10020,0]
12-17 17:42:10.941 I/notification_expansion( 2218): [0|nodomain.freeyourgadget.gadgetbridge|1|null|10201,0,1,2290615,2241867,0]
12-17 17:42:10.941 I/notification_expansion( 2218): [0|nodomain.freeyourgadget.gadgetbridge|1|null|10201,0,0,2290615,2241867,0]

**Comment by danielegobbetti** [comment]
@clemens23 I think the best approach is that we add the full notification flags bitmask to the log message so in the next release we can compare whatsapp and existing (working) apps. If someone reading this is able to self-compile and is using whatsapp please chime in so we don't have to wait a full release cycle!

**Comment by clemens23** [comment]
@danielegobbetti I installed gradle & android sdk, did a git clone and self-compile was ok. So i can test next time.

**Comment by danielegobbetti** [comment]
@clemens23 please try with current master. You should see the usual "Not forwarding notification" message with a number at the end. Please let us know whether this line is followed by another "Processing notification from source ..." line, as the usual behavior of (currently working) apps is to send two notifications, one for the android device and another for the wearable.

**Comment by clemens23** [comment]
@danielegobbetti here is my logfile, edited with ### comments
[gadgetbridge-clemens23-20161218-1526.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/659488/gadgetbridge-clemens23-20161218-1526.txt)

**Comment by danielegobbetti** [comment]
@clemens23 I deferred a check now, hopefully it will work for you. I edited your comment as some phone numbers were visible in the log you attached.

**Comment by danielegobbetti** [comment]
@clemens23 is the thumbs-up meaning it works now? :)

**Comment by clemens23** [comment]
@danielegobbetti wow, just build from source and notifications work like a charme :+1: thank you very much

**Comment by danielegobbetti** [comment]
That's great to hear, it will be in next release hence I'm closing this.
