### ISSUE TITLE
Cannot Downgrade the Firmware on Mi Band 2

### ISSUE THREAD

**Issue by usersanjib** [Freeyourgadget/Gadgetbridge#458]
I am using Mi band 2 with the firmware version 1.0.1.21. I was trying to downgrade it to the firmware version 1.0.0.39. 
When I choose the Mili_pro.fw file from the file explorer it launches the FW/App Installer and it gives a message " Element cannot be installed"

I tried removing the Mi fit Apk completely and cleared the Bluetooth share data and restarted the phone. But no luck to downgrade the firmware. I also verified the MD5 checksum of the fw file so I think I am not missing any steps to follow.

There is no any pairing issue with the Gadgetbridge Apk. Do I need the rooted device to do this ? I was trying it from Redmi Note 3 SnapDragon with Android Version 5.1.1

Looking forward to hearing the solution.

Thank you!

**Comment by gsmtechUK** [comment]
I can confirm I have succesfully downgraded my Mi band 2 from the latest firmware v1.0.1.28 to v1.0.0.39 using Gadgetbridge 0.15.0 from F-Droid . Fantastic work thank you to all invlolved :)
