### ISSUE TITLE
MiBand2 wrong time (possibly because of timezone?)

### ISSUE THREAD

**Issue by maces** [Freeyourgadget/Gadgetbridge#459]
Since I got my MiBand2 the time is behind by fife hours, at least consistently. Searching the issues tracker I found #441 but I think it's not related, because my time offset is consistent.

I started with GB version 0.10.1 and now I am on version 0.15.0.
Firmware version was 1.0.0.19 till today, when I updated to 1.0.0.39, thanks to GB 0.15.0 :).
My timezone is UTC+01:00 at the time of writing its 12:20 but my band shows me 7:20.

During my initial setup the time was once correct. Due to some issues I did pair the band again and the time is of since then. Pairing again did not help. The time stays in sync though, just with the offset.
The activity graphs do show the activity at the right time though. The step counter on the band however is bound to the wrong time, thus starting over during the day.

Setting the time via the debug menu did not work, reconnecting and activating and deactivating the "sync time"-setting did not work either.

Logfile: [gadgetbridge.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/654480/gadgetbridge.txt)

**Comment by cpfeiffer** [comment]
Hm, I need to check this. There are several different formats in which we need to send the date/time to the band -- might very well be that I mixed something up.

It works for me though (at UTC+2 atm.

**Comment by cpfeiffer** [comment]
FWIW, my understanding is that we do send the correct timezone (as per the Bluetooth Current Time Service spec), which is `4` for UTC+1. 

You did not configure a time offset in Gadgetbridge's preferences, did you?

**Comment by maces** [comment]
I did not find this setting, only my language and the toggle to activate time sync. Language is set to Germany and time sync is on.

**Comment by danielegobbetti** [comment]
@maces that setting is immediately below the "use hearth sensor to make sleep recognition better" checkbox in the miband settings. You can find a better description of its usage and ratio [here](https://github.com/Freeyourgadget/Gadgetbridge/pull/321). If you have a value different than 0 that might explain what you are experiencing.

**Comment by maces** [comment]
Oh well, totaly missed that. It's working now. Thanks @cpfeiffer @danielegobbetti
For the record, mine was set to '7' and I set it to '0', now the current hour is shown.
