### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#46]
All strings should be localizable.

Additionally we should use something like Transifex or similar to enable easy localizations.

**Comment by danielegobbetti** [comment]
I can do Italian

**Comment by ashimokawa** [comment]
That would be awesome

**Comment by cpfeiffer** [comment]
We now support translation with transifex, see 
https://www.transifex.com/projects/p/gadgetbridge/resource/strings/

Everyone, drop me a message here if you want me to add you to the translation team.

**Comment by cpfeiffer** [comment]
Oh and more languages are welcome as well -- the current ones were added by default, so I kept those.

**Comment by ashimokawa** [comment]
@cpfeiffer 
You are welcome to maintain this.
I dont like this as it forces me to create another account, cant even see the strings without logging in.

**Comment by cpfeiffer** [comment]
I hope that we can make this public somehow.

But you can reuse your github account with transifex.

**Comment by halcyonera** [comment]
Transifex says I'm not a member of this project. How to fix this?

**Comment by cpfeiffer** [comment]
@halcyonera I've invited you to become a member.

AFAIK transifex users can also request membership on their own.

**Comment by cpfeiffer** [comment]
@joen you're now a member as well -- the next membership requests will be automatically granted

**Comment by danielegobbetti** [comment]
Hi, the italian version is on transifex but it wasn't part of https://github.com/Freeyourgadget/Gadgetbridge/commit/dc6fd8cb61c9f46d9f9d498555ccb46800608b84, do I have to do something special since is a new language?

**Comment by cpfeiffer** [comment]
Thanks for the heads-up and the translations! I need to use 
tx pull -a
to get new languages.

I'm new to transifex, and frankly, I find the web interface rather confusing. I'll see if there's some other, better translation site.

**Comment by danielegobbetti** [comment]
Omnirom uses crowdin: https://crowdin.com/ But I only know the translator side, I have no idea about the integration. (sorry for reopening the issue, but I thought it was worth the reply).

**Comment by cpfeiffer** [comment]
Thanks for the info -- I'll have a look.

(The) one thing I like about transifex is the git-like tool for pushing and pulling translations (tx push/pull).

**Comment by mueller-ma** [comment]
@cpfeiffer According to @ashimokawa Transifex removes translations, when the source string has changed (even when its just a fixed typo). Weblate only marks the translations and shows a diff what changed. They offer free hosting for oss.
![weblate](https://user-images.githubusercontent.com/22525368/29268833-e718e1ac-80ee-11e7-9bb5-0428d77d290b.JPG)
See #762

**Comment by cpfeiffer** [comment]
I've requested hosting at weblate. Let's see how that works out. We've long been considering to move away from proprietary Transifex.

**Comment by mueller-ma** [comment]
Most annoying thing about transifex: 1000 js from external pages

**Comment by cpfeiffer** [comment]
There's Ghostery, ublock origin and others for this task, but this is getting offtopic ;-)

**Comment by mueller-ma** [comment]
Sure there are, you always have to find out which js are needed. Apart from that: You shouldnt use ghostery: https://www.heise.de/newsticker/meldung/Kritik-an-Werbeblocker-Ghostery-1890879.html
