### ISSUE TITLE
Update wiki by info for developers

### ISSUE THREAD

**Issue by rplevka** [Freeyourgadget/Gadgetbridge#461]
I'd like to have some basic info about the code structure, setting up a development environment, etc. for people who would like to contribute. I would personally like to try to implement some features and make  patches for bugs I have identified, but I'm feeling quite lost in the code structure.

**Comment by danielegobbetti** [comment]
Hi! Sure we want to make the life as easy as possible for contributors, from your message I don't understand wether you missed [this page](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Developer-Documentation#important-classes) or if you find it not helpful/confusing. 

The page is linked from the wiki's home page under "Development" -> "Developer documentation".

**Comment by rplevka** [comment]
@danielegobbetti thanks, I missed that page and it looks like exactly what I was after :) thanks
