### ISSUE TITLE
Increase number of alarms

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#462]
It would be great to have more than three alarms. Is it possible (also on the Mi Band's hardware side) to increase the number of alarms (to maybe 5 or 6)? :pray:

**Comment by cpfeiffer** [comment]
Two things: 

1) Mi Band 1 supports only 3 alarms, AFAIK.
2) Mi Band 2 supports more, I think, but I'm not sure about this and I don't know how many.
3) We could thereotically support more alarms than available by sharing the slots (sending the next alarm to the band as soon as one alarm is done). However that would need a connection to the device, so it should be made clear to the user.
4) Are you talking about Mi1 or Mi2?

(So that's 4 things after all ;-)

**Comment by 6arms1leg** [comment]
Thanks for your considerations!

> 1. Mi Band 1 supports only 3 alarms, AFAIK.
> 2. Are you talking about Mi1 or Mi2?

I was generally speaking about all devices that support alarms. Personally, I own an old Mi Band 1 and a Mi Band 2, of which I use the latter.

> Mi Band 2 supports more, I think, but I'm not sure about this and I don't know how many.

Personally, I'm mainly interested in this one. If it supports more alarms it would be great to fully support that feature. On different days, I have to get up at different times, so ideally there would be 7 alarms – one for each day. Because of this limitation, I currently have to re-set the alarms every few days. Also, one additional alarm, for example for cooking/sports/etc., would be great. So all in all, 8 alarms would be perfect (in my opinion). While that many alarms are probably not possible, any additional alarm would be a great improvement (for me).

> 3. We could thereotically support more alarms than available by sharing the slots (sending the next alarm to the band as soon as one alarm is done). However that would need a connection to the device, so it should be made clear to the user.

Well, I thought of that too, but (personally) I wouldn't bother. This method is unreliable. When I have to have my mobile with me anyway for the alarms to work, I can just set them on my mobile as well. The huge advantage of the Mi Band alarms is exactly the fact, that you don't have to have your mobile with you. Think of someone in a natatorium, the cinema or on an airplane...
I think the best way to go is to increase the number of alarms for the Mi Band 2, leaving it for older Mi Bands as it is.

**Comment by cpfeiffer** [comment]
Some feedback:
Mi2 supports up to 10 alarms, AFAIU. We can easily support that, BUT
1) The UI looks a little crowded when we display 10 alarms in a list. We could use the same UI as cLock's alarm widget with the possibility to add and remove alarms.
2) It gets complicated with multiple devices that have different capabilities.
At the moment, the alarms are shared between devices, so I can use the same alarms for Mi1 and Mi2 for example. However Mi1 only supports three, so we should somehow make it clear that only some of them are really shared. Alternatively we could make them non-shared.

**Comment by 6arms1leg** [comment]
Thanks for your considerations!
1. Adding alarms on the fly as needed, like *cLock* does it, is probably the cleanest looking UI implementation.
2. Non-shared alarms might become neccessary someday anyway with different device capabilities (e.g. disabling the smart alarm feature for Mi Band 2 in #471). But for now, wouldn't it be possible to use the shared alarms approach currently in use, implement the *cLock*-style for adding alarms (see 1.) and just limit the number of creatable items(/alarms) in the list for each device?

Well, in the end it's totally your call. You know best what's feasible. Maybe I'm the only one intersted in more than three alarms and it's not even worth the effort for you...

**Comment by cpfeiffer** [comment]
I'd also like to have more than 3 alarms, so that is a reasonable request :-)

**Comment by walkjivefly** [comment]
Mi Fit allows up to 10 alarms on Mi Band 2. Each alarm can be set to repeat Once, Every day, Mon to Fri, or Custom (you choose the days you want). Annoyingly, or usefully, each alarm snoozes 5 times for 10 minutes when you touch the button to acknowledge it.

**Comment by sveissiere** [comment]
I like the MiBand tools app, which allows for multiple repeat alarms with custom icons, but they only work when the band is paired to a phone.  
Has anyone figured out a way to get alarms with custom buzzes and icons to work when the phone is not around?  We are piloting an ADHD attention-training program for kids in the lab and have promising results, but haven't figured out a way to bypass the phone-pairing proble,

**Comment by viniciusmr** [comment]
So, is it ever going to get the 10 possible alarms or was this dropped?

**Comment by gauravsak** [comment]
I need more than even 10 alarms on my mi band 2. Is that possible? Why the restriction of 10 alarms anyway? I am ok with keeping bluetooth paired with the phone.

**Comment by MagicFab** [comment]
AFAIK XWatch supports only one. One way to overcome that would be to update it when more than one is enabled.

**Comment by ashimokawa** [comment]
Done is master, will be in the next release after 0.31.3
