### ISSUE TITLE
App doesn't send any notifications to Pebble 2

### ISSUE THREAD

**Issue by seiferfury** [Freeyourgadget/Gadgetbridge#463]
Tried anything but it doesn't send any notifications at all

Nothing works when I try the debug functions

Music app does work and can control my Spotify app

The 'Find my device...' feature is working initially, but after some time it fails to work again

Should mention my phone is OnePlus 2 A2001 with OOS 3.1, with Pebble 2 HR 4.3 firmware

Attaching the log file

[gadgetbridge.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/658624/gadgetbridge.log.txt)

**Comment by ashimokawa** [comment]
The log file is incomplete it looks like 90% is missing, please provide a proper log file. There is absolutely no connection sequence visible, no LE communication etc.

Also did your device say "connected" in Control center?
And did you pair your Pebble 2 through Gadgetbridge?

**Comment by seiferfury** [comment]
Not sure what you mean since I just uploaded the whole text file. Anyway I did the test again, from unpairing the device and repairing it again, then doing all the functions on the debug window. 
The pebble was reset and nothing's connected to it ( all pairs removed). Tests were done while the pebble is idle and on its watchface screen. I cleared Gadgetbridge's settings to default.

https://gist.github.com/seiferfury/dfe21e2abf840355b6de65b8bac733e1

**Comment by seiferfury** [comment]
And yes the app says connected and I paired through the app

http://m.imgur.com/xhERCjT

**Comment by ashimokawa** [comment]
I will add an option in the next release which will allow limiting the GATT MTU. Maybe that helps.

**Comment by seiferfury** [comment]
One thing I noticed is the log always prints 
` n.f.g.e.NotificationListener - Not forwarding notification, FLAG_ONGOING_EVENT is set` 
When I send a test notification, but nothing is running on in my phone. Is something wrong with my phone? I rooted it but other than that it's the stock OS that's running

**Comment by ashimokawa** [comment]
If you want the "create test notification" to work, you have to enable  the "Also when screen is on" option for generic notifications. 

That button is to test if our notification receiver works properly. The send button on the top of the screen sends notifications directly to the watch.

**Comment by seiferfury** [comment]
Yeah I enabled that checkbox when I noticed the 
`screen seems to be on and settings do not allow this`
log part was showing, but it turned into that `FLAG_ONGOING_EVENT` instead after I enabled it

**Comment by ashimokawa** [comment]
@seiferfury 
I have no idea what is wrong with your setup. And we are mixing two things here, which makes it even more complicated. (deciding if notifications are forwarded to the device and the ability to send notifications to the device). For now you should just use the first send button and not the "create test notification" button.

In 0.15.1 I have added an option to limit the GATT MTU. You can try to lower that to 20 and send a test notification again. If it works try to raise that limit until it fails again.

**Comment by rplevka** [comment]
I'm not getting any notifications either for my miband 1s since `0.15.*`
https://github.com/Freeyourgadget/Gadgetbridge/issues/468

**Comment by seiferfury** [comment]
Unfortunately I've already sold the OP2 since the official app wasn't working either. I thought maybe the problem is with the device itself

**Comment by danielegobbetti** [comment]
Closing this then.
