### ISSUE TITLE
Background javascript for pebble watchapps

### ISSUE THREAD

**Issue by danielegobbetti** [Freeyourgadget/Gadgetbridge#467]
Before #302 or even #327 make sense, we need to keep the android part of each pebble-app alive. Right now we invoke the app javascript when configuring each app but we need to keep it running all the time in the background if we want to support proper android<->watchapp communication.

After scratching our heads around the issue for quite some time, I believe we found a possible working approach and we can start implementing it. The basic idea is this:

1. at each watchapp launch we get notified (thanks to 31122f0b0947bca803ec19e7c580b0b555ea465e)
1. we load the app-provided JS in a webview and trigger the "ready" event
1. we let the js code sit there managing its events and the communication (is some kind of keepalive needed?)
1. goto 1

TODO:
- [x] detach the webview from the current configuration activity and move it to a ~fragment~ singleton class
- [x] ~somehow let the fragment live off-screen, and show it only when needed (i.e. at configuration time)~
- [x] load each watchapp js when they're launched 
- [ ] load watchapp JS even if a handler is present
- [ ] exclude  system watchapps and watchapps/faces that have no js to run from the JS load
- [x] stop the background js when disconnected from watch (consider destroying the webview and recreate it at reconnect)
- [x] implement two-way communication for the webview (we have android->pebble for now)

If there are alternative approaches, or if anyone has experience in letting a webview running in the background on android we would appreciate any input.

**Comment by ec1oud** [comment]
OTOH JS isn't much use without internet and location access.

I wondered about how to start a JS engine too though.  Googled and found stuff like

http://stackoverflow.com/questions/19408245/use-v8-javascript-engine-to-execute-js-lib-without-webview

http://openaphid.github.io/blog/2013/01/17/part-i-how-to-choose-a-javascript-engine-for-ios-and-android-apps/

You'd think if the phone ships with V8, there'd be a way to access it without having to bundle it and without having to use the whole browser.  JavaScript was originally created as a scripting language to interact with Java applets, after all, so it's weird that they wouldn't make it available to Java apps today.

If not, maybe it could be an external dependency: an apk (to be made available on fdroid and others) which just provides a shareable JS interpreter, like the way Ministro provides shareable Qt libraries.  As I understand if multiple apps share libraries like that, the code is shared in memory, just as with normal Linux shared libs.  But it would be best if the browser and GB also shared the JS interpreter's code.

**Comment by ashimokawa** [comment]
I disagree.
We could support accessing the timeline without  Internet access, I.e. without sending everything to the cloud first.

**Comment by ec1oud** [comment]
Yeah, I agree.  I never did understand why they intended the timeline to be strictly a cloud-based thing.

Still, many times JS is written to access web services.  If it's for the purpose of reading data anonymously rather than sending data, it's not even a privacy concern.

**Comment by IzzySoft** [comment]
>  If it's for the purpose of reading data anonymously rather than sending data, it's not even a privacy concern.

I disagree. As soon as the INTERNET permission is involved, it **is** a privacy concern. There's a reason why GB left that out intentionally. And just because of JS being used to access web services doesn't mean it must be used in this way. No, I won't drop in comparisons with use of atomic powers or TNT here, though I'm very tempted (just a minor explosion, please :stuck_out_tongue_winking_eye:)

**Comment by danielegobbetti** [comment]
Guys the topic of letting JS run in the background is complex (well, for me at least) and every time I get a notification from this thread I hope someone added a proper solution or some insights. Not that I don't appreciate the discussion but can we please remain on topic, please? Thanks.

**Comment by sjp4** [comment]
In case you were wondering: the Pebble app uses a background `Webview` to run PebbleKit JS code. This used to require the special "draw over other apps" permission (to attach the `Webview` to a window), but that requirement was removed relatively recently.

There is no `Activity` or `Fragment` - just a `Webview` constructed manually. I didn't write this code, but I think that calling `webView.setWillNotDraw(true)` is an important step in not requiring to add it to a `Window` or other UI element. You'll also have to pretty aggressively clean up the `Webview` after the script has completed (there are several stop/clear/destroy/etc methods to call).

re: the internet/location permissions - I'll be honest; I don't see many uses-cases for PebbleKit JS without those. I appreciate that the idea behind GadgetBridge was to think privacy, but also that there are more people looking to it now just as a general alternative who don't have those concerns. I guess the JS component could be put in another apk and talk over a permission-based AIDL interface to avoid the permissions be added to the main app?

**Comment by danielegobbetti** [comment]
Regarding internet, yes! See #302 and please let us know what you think of the scenarios we outlined there.

Regarding webview, thanks for the pointers! They help a lot.

**Comment by danielegobbetti** [comment]
Progress: I have a background webview running locally. Problem is that clay configuration pages don't work correctly (the dropdowns aren't being displayed when touching them), anyway the basics seem to be there.

**Comment by danielegobbetti** [comment]
Progress: the watchapp [QR Generator](https://apps.getpebble.com/en_US/application/535e84d0af59179a46000088) - [source code](https://github.com/reini1305/qrgenerator) is fully working with only minor workarounds needed (especially related to when and how launch the webview).

**Comment by danielegobbetti** [comment]
Progress: I believe the webview life cycle is now under our control, and it works reliably. Enough to let the bugs/missing parts in our js bridge to be visible.
The main missing part is to relate the messages sent to pebble to an eventual js callback that was set by the watchapp in the webview, and pass the response back.
Apart from that, the branch now contains the logic to reconstruct the openweathermap json using the information we get from the weather app, unfortunately the forecast cannot be fully reconstructed. 
As always help is welcome :-)
