### ISSUE TITLE
miband 1S - notifications + connection are unreliable in 0.15.0

### ISSUE THREAD

**Issue by rplevka** [Freeyourgadget/Gadgetbridge#468]
There's not much more information I could provide here, but the miband connection and notifications functionality got significantly more unreliable in GB 0.15.0.

Right now i'm not even able to receive the test notification.

Could this be caused by https://github.com/Freeyourgadget/Gadgetbridge/issues/469 ?
Right now, everytime i got to sync the data, It starts t odownload 12days (!) of data (and growing)

**Comment by rplevka** [comment]
update: rebooting the band seemed to work, will monitor the band behavior for some time now and update the issue with my further findings

**Comment by cpfeiffer** [comment]
To me this sounds like a deteriorating device. Had my own share of such Mi Bands and we had a few in our issue tracker already.

In any case, if you want us to have a look, please provide a log of e.g.
- disconnections
- notifications not working
- sync problems

**Comment by rajeevn1** [comment]
version 0.15.1 was not working for me too (not a hardware issue).  reverted back to 0.14.4 on f-droid and all is well so far.

**Comment by danielegobbetti** [comment]
Since in version 0.15 we added additional log messages for notifications, can you please check in the logs for messages like "Not forwarding notification"? A reason should follow on each line.

**Comment by rajeevn1** [comment]
adb log of the crash and app log is attached. hope it helps resolve the issue.

[adb.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/671824/adb.txt)
[log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/671825/log.txt)
