### ISSUE TITLE
miband 1S - Fails to delete the downloaded data from the band occasionally

### ISSUE THREAD

**Issue by rplevka** [Freeyourgadget/Gadgetbridge#469]
GB fails to remove the downloaded data from my band quite often, resulting in downloading up to 12 days of redundant data over and over again (this has been happening in older versions as well).
switching 'keep data on the band' on and off does not help at all.
Could this be caused by turning off the bluetooth in the middle of some transaction?

update: rebooting the band seems to help, but not always

**Comment by cpfeiffer** [comment]
Did you get any errors when synchronizing? When an error occurs, we do not acknowledge the received data in the hopes that we will receive it correctly again, later.

If you can share a log, please do so.

**Comment by rplevka** [comment]
This apparently turned out to be android 4.4.2 or my phone issue (cheap EOL prestigio (mtk) phone). It probably had some bug in BT stack/handling as after I switched over to Galaxy S5 mini (with custom 7.1.1 rom) I no longer experienxe these issues (i still own the same band).

I'm more than happy to close this issue. Anyway, I still do own the old phone, so if you'd be interested in debugging this, I can provide you all you'd need (just not the BT logs, since the logging feature seems to be buggy amd does not produce the logfile :D)

**Comment by cpfeiffer** [comment]
Since this issue appears to be related to your phone/OS, I'd indeed close this issue. More interesting would be to fix the logging issue then, so if you can debug this, or at least have a logcat, feel free to open another issue.

**Comment by rplevka** [comment]
sorry, by `logging feature` i actually mean the android `Bluetooth HCI Snoop Log`. No issue with the app logging. Thanks for closing.
