### ISSUE TITLE
Pebble decoding

### ISSUE THREAD

**Issue by wuschLOR** [Freeyourgadget/Gadgetbridge#476]
Hi there as I was reading in the docs the the way pebble generates its data is not clear.

Therefore I wanted to create a simple Rscript, trying to recreate the activity graphs and do some math magic for better graphs and error correction.

After nearly a day of trying to understand the code (by using my 33c3 motivation but I'm not a Android dev) I still couldn't find all the value definitions. Also my graphs look totally different then what is presented to me in the alpha version of the controlcenter.

Is there some place where the thresholds of different values are documented that I'm missing?

**Comment by cpfeiffer** [comment]
Are you copying the sqlite db and operate on that data? If so, have a look at class `PebbleHealthSampleProvider`.
