### ISSUE TITLE
Mi Band 2 Feature Request: Do Not Disturb

### ISSUE THREAD

**Issue by Jojonintendo** [Freeyourgadget/Gadgetbridge#483]
Hi everyone and happy new year!

The "Do Not Disturb" mode of the Mi Fit app would be very useful, especially at night time, so that the screen won't turn on on random movements. 

It has different options: automatic (it detects if we're sleeping by itself), manual (on a set time, I believe 21:00-7:00 by default), and off. There is also the option to deactivate the screen wake by wrist movement, which is the most useful I think.

I provide a btsnoop of activating those options, and a separate one just for the screen wake. Hoping that it's useful. Thank you very much for your work!

[btsnoop_DND.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/679989/btsnoop_DND.zip)

**Comment by Dako300** [comment]
I would love to see this too

**Comment by mueller-ma** [comment]
I have some suggestions how to improve this feature:

1. Set indipendend times for each day of the week
2. Possibility to set "From 22:00 until I am awake"

**Comment by cpfeiffer** [comment]
I think we have enough preferences already :} FWIW, newer devices like the Bip allow you to manually toggle DND mode on the device itself.

**Comment by mueller-ma** [comment]
IMO the current implementation is very useless:
I dont want to be woken up by a notification, so I have to set DND from 22:00 until 11:00 to cover Mo-Fr and weekend at once

**Comment by danielegobbetti** [comment]
AFAIK the DND settings of android allow to set different periods for different days of the week, and gadgetbridge can be set up to respect those settings. Or am I missing something?

**Comment by mueller-ma** [comment]
I usually have my phone always muted
