### ISSUE TITLE
Mi Band 2 Feature Request: Cycle info with wrist movement

### ISSUE THREAD

**Issue by Jojonintendo** [Freeyourgadget/Gadgetbridge#484]
Hi everyone!

Another option that would be cool in my opinion would be to be able to use this option. It allows not only to show the time by raising the wrist, but also to cycle between other screens without touching it, to see steps, battery, etc.

I provide the btsnoop of activating it, hoping it is useful. Thanks for your work!

[btsnoop_hci_rotate_wrist_change_info.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/679991/btsnoop_hci_rotate_wrist_change_info.zip)

**Comment by cpfeiffer** [comment]
Implemented, thanks to @joserebelo
