### ISSUE TITLE
Mi Band 2 Feature Request: Activity reminder & co

### ISSUE THREAD

**Issue by Jojonintendo** [Freeyourgadget/Gadgetbridge#486]
Hi everyone!

I provide the btsnoop of yet another option in the Mi Fit app, which allows the band to tell us we have to move a little after sitting to long. One can also deactivate this option on some hours, for example at work. Thanks for your hard work!

[btsnoop_hci_activity_reminder.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/679995/btsnoop_hci_activity_reminder.zip)

Also, as to not open too many issues for not so relevant options, I provide the btsnoops for activating bluetooth visibility of the band. I don't know if it's really useful for us, but as I saw it today, I took a btsnoop too :D.

[btsnoop_hci_bt_visibility.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/679996/btsnoop_hci_bt_visibility.zip)

**Comment by joserebelo** [comment]
The option for activating the Bluetooth visibility is not working here (not even with the Mi Fit application), tested it on firmware 1.0.1.39 and 1.0.1.50, with the same result: the band will not be visible while connected to the phone, becoming visible when disconnected, no matter the option.

**Comment by cpfeiffer** [comment]
Closing, again thanks to @joserebelo
