### ISSUE TITLE
Pebble: Temperature value customization

### ISSUE THREAD

**Issue by anantshri** [Freeyourgadget/Gadgetbridge#488]
Right now the temperature appears to be stuck to Ferinheight on my Pebble 2. Is it possible to change the temperature type from Ferinheight to Celsius.

**Comment by danielegobbetti** [comment]
Just to be sure, which release are you using? Or do you use current master (self compiled)?
Further, are you referring to a specific watchface or the system app?
In any case, please provide more details and if possible some logs.

**Comment by anantshri** [comment]
Ohk let me try to provide as much details as i can.

1) Gadgedbridge : latest version from F-droid (1.16 i suppose)
2) not exactly any watchface but when i look at weather default app the temperature is in degree F which i want to change to degree C, default pebble app has an option to toggle that.
http://help.getpebble.com/customer/portal/articles/1964842-weather-set-up?b_id=8309

Logs if you can suggest from where i should extract i can provide you those.

**Comment by ashimokawa** [comment]
@anantshri 
Weather is not supported in any release yet but will be in the next one. 
The reason why you see weather at all is that you activated it with the official app.

Starting with the next release you will be able to activate and use weather in Gadgetbridge. You problem will then be gone.

**Comment by anantshri** [comment]
Thanks for the update and awesome work you folks have been doing.
