### ISSUE TITLE
Mi Band 2: Unstable connection

### ISSUE THREAD

**Issue by Jojonintendo** [Freeyourgadget/Gadgetbridge#493]
####Your issue is: The connection to the Mi Band 2 is sometimes unreliable
Here is the GB log of connection lost: [gadgetbridge.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/687059/gadgetbridge.zip)

####Your wearable device is: Mi Band 2, HW: V0.1.3.2, FW: V1.0.1.28

####Your android version is: CyanogenMod 13.0, Snapshot from 20-08-2016. Phone is Xiaomi Redmi Note 3 Pro (Snapdragon version).

Hi everyone!

Sometimes the connection of the device is lost. Sometimes it can connect itself again, but sometimes I must manually click on it (and it usually takes several retries). Overall it's pretty reliable, but once or twice a day this happens. I hope the log is useful and not too big. Thanks for your support and hard work!

**Comment by Jojonintendo** [comment]
After some days of use, I think that disabling the option to connect automatically when bluetooth turns on makes the connection stronger. I still have the "reconnect automatically" though. The only thing that often makes the band disconnect is when manually syncing activity data.

**Comment by Jojonintendo** [comment]
After a few days with Nougat on my phone, I must say that the connection is rock-solid. I'm not sure what that means (maybe my previous firmware in Marshmallow was bad?), but it seems to work very well now.

**Comment by danielegobbetti** [comment]
Closing this since issue is solved :-)
