### ISSUE TITLE
Any option to stop on call initiation

### ISSUE THREAD

**Issue by anantshri** [Freeyourgadget/Gadgetbridge#494]
Pebble latest version.
Gadgetbridge Latest version.

Current status : when a call is initiated watch vibrates. when a call is incomming watch vibrates

Expected status: When call is initiated (outgoing) no vibration. when call is incomming vibrate.

is there an option to do that. or is this something that's planned. Can't find a workaround.

**Comment by danielegobbetti** [comment]
Please specify the version. Latest version doesn't really help (could be latest as in released, as in latest master commit, as in ...).
Anyway as far as I know that's a pebble feature: it vibrates on call start. Does it work differently with the official app? If it does, does the watch show the "ongoing call" screen during a call when you initiate it?

**Comment by IzzySoft** [comment]
I cannot remember my *Pebble Time Steel* vibrated on outgoing calls. Watch settings also only mention vibrations on incoming calls. So in addition to Daniel's question: please also specify what Pebble it is :)

**Comment by anantshri** [comment]
GadgedBridge Latest as in latest release (0.16.0)
Pebble 2 with HR Monitor.

Default app never vibrated on outgoing call but Gadgedbridge does.
Can't remember for sure about the ongoing call screen on official app.

**Comment by ashimokawa** [comment]
@anantshri 
I have always been fully aware of the problem and I know the cause.
It affects Pebble 2 and maybe other Pebbles when using LE.

Actually there is no outgoing call display, so as a hack we send an "incoming call" command and right after a "start call" command.

Now with LE, I wait 0.5s after each complete propocol chunk, and that is what makes the Pebble vibrate for about that period of time.

Fixing this would need a proper LE implementation - but even then it might vibrate for 0.2 seconds or so. My motivation dropped on making LE perfect after Pebble went out of business and it became clear that the P2 will be the only device relying on that code.

However I will finish that at some time. Meanwhile we could make this an option (disable outgoing call display)

**Comment by anantshri** [comment]
Thanks @ashimokawa for the clarification. I suppose even if we don't work on this feature anymore if there is an option present to stop this code that would be good enough. So if someone likes it keep it running otherwise just disable it.
