### ISSUE TITLE
PebbleKit data logging API doesn't work

### ISSUE THREAD

**Issue by tecufanujacu** [Freeyourgadget/Gadgetbridge#497]
I have a Pebble classic, in the past I tried using the watchface [TCW](https://apps.getpebble.com/en_US/application/52fe1d0d3085a0848d000231?dev_settings=true&native=false&query=tcw&section=watchfaces) with its companion app with no success, in the last days I tried using the watchapp [upTempo](https://apps.getpebble.com/en_US/application/556c1dc2e42ea416be0000aa?dev_settings=true&native=false&query=uptempo&section=watchapps) with same result, no success.

Obviously in both the cases I enabled in GadgetBridge the setting: "Allow 3d Party Android App Access" but the watchapps aren't able to communicate with their companion apps.

**Comment by ashimokawa** [comment]
Just tested Ventoo. Works.
Do you have the official pebble app also installed? If so that could be your problem

**Comment by ashimokawa** [comment]
@tecufanujacu 
I can't find an upTempo companion app

**Comment by tecufanujacu** [comment]
@ashimokawa 
No, I don't have installed the official pebble app, I uninstalled it almost an year ago, from when I started using GadgetBridge.
You can download the upTempo companion app [here](https://dropfile.to/wYSS2S0), thanks to look in it.

I reported this issue also in the upTempo issues [#2](https://github.com/vssh/pebble-upTempo/issues/2).

**Comment by ashimokawa** [comment]
@tecufanujacu 
I cant say anything about TCW because the app no longer exists.
Since "Dialer for Pebble" and "Ventoo" work well but upTempo does not I will rename this Issue.

The reason upTempo does not work because they use the datalogging PebbleKit API which we do not support yet.
At least I have a testing environment yet, thanks to upTempo.

**Comment by tecufanujacu** [comment]
Oh, well, I understood.
About TCW in the past I already temporarly uploaded the apk in the issue #302, anyway if it can help I relink everything. I hope in the future we will be able to use TCW with GadgetBridge because it with its companion app are really wonderful, I think that some feature of the companion app could greatly be integrated in GadgetBridge.

About TCW:
- [TCW watchapp](https://apps.getpebble.com/en_US/application/52fe1d0d3085a0848d000231?dev_settings=true&query=tcw&section=watchfaces)
- [TCW watchapp source code](https://github.com/alexsum/TCW)
- [TCW android companion app](https://dropfile.to/RpG1ujT)
- [TCW android companion app source code](https://github.com/alexsum/TCWAndroid)

About upTempo now the watchapp source code is [here](https://github.com/vssh/pebble-upTempo) available and probably in the future also the companion app will be open source as [here](https://www.reddit.com/r/pebble/comments/5h6f16/uptempo_companion_app/daxx2ke/) indicated.

@ashimokawa , a question, do you think that could be upTempo be integrated in GadgetBridge as happened for Misfit? ( #316, sorry If I re-ask also here.)

**Comment by ashimokawa** [comment]
The apk link is dead

**Comment by tecufanujacu** [comment]
Sorry, I made some error, it is now ok.
[tcw.apk](https://dropfile.to/kVNAESd)

**Comment by ashimokawa** [comment]
@tecufanujacu
OK I tried tcw and fixed a bug in our PebbleKit implementation.

But before, some things already seemed to work. I had some spinning waiting indicator and random battery levels displayed in the tcw android app.

That does no longer happen and will be in the upcoming GB 

Can you please explain what did not work for you in tcw?

**Comment by tecufanujacu** [comment]
If I correctly remember no one of these features was working:
- the ability to sync the watchapp with a local calendar on android
- the ability to lock the phone when the watch loses the bluetooth connection with android
- the ability to watch the phone's battery status
- the ability to watch missed calls, sms and email icon in the watchface
- the ability to receive on the watch notifications from selected app from the phone
- also the watchapp FindPhone installable from the companion app isn't working

**Comment by ashimokawa** [comment]
@tecufanujacu 

I installed the apk on a tablet without internet access (Given the permission I would not recommend anyone installing that apk on any important device). I could not test all features on that device:

> the ability to sync the watchapp with a local calendar on android

Did not test

> the ability to lock the phone when the watch loses the bluetooth connection with android

did not test

> the ability to watch the phone's battery status

worked

> the ability to watch missed calls, sms and email icon in the watchface

tested only for the email icon, worked.

> the ability to receive on the watch notifications from selected app from the phone

did not test

> also the watchapp FindPhone installable from the companion app isn't working

It did not work, but in the logs I noticed that TCW Android could not load its "ringtone", communication worked.

**Comment by tecufanujacu** [comment]
@ashimokawa 
Sorry for the long delay, I have been really busy.
Anyway I don't use TCW from a lot of time, If this can help you I can retest everything in the next days.
As always, thanks for your work.

**Comment by danielegobbetti** [comment]
I'm closing this as the released version contains the fixes mentioned. Please reopen if you are still affected.

**Comment by ashimokawa** [comment]
Reopened because as the title says this is about missing datalog support in our pebblekit implementation
