### ISSUE TITLE
Step count deviation between Mi Band 2 and GB

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#499]
As discussed in #477, some users observed a deviation between the step counters on the Mi Band 2 itself and the displayed value in GB.
Since #478 was fixed, that deviation became much smaller and rarer. However, it still happens sometimes – [it is assumed that it is somehow connected to reaching the step goal (reportedly 10,000 steps)](https://github.com/Freeyourgadget/Gadgetbridge/issues/477#issuecomment-271149890).
It does not seem to be FW related, as it happens on a device with FW v1.0.0.39 (me) and v1.0.1.28 (as @Jojonintendo reported).

**Comment by Jojonintendo** [comment]
I'm not sure it is related to the step goal, since mine was set to 6000 at the time (I know I'm lazy, but I'm realistic :p). The day I noticed the deviation, I was at around 14000 steps, and only aprox. 20 steps deviation on the band. That's only about 0,05% of error, maybe I'm wrong, but I think that the margin of error is too low to notice under a very high step count (around 10000). But it would be nice to investigate further, out of curiosity.

**Comment by bluuub** [comment]
I can not reproduced this after the update to GB version 0.16. My step goal is 10000 and band and app are still in sync. Will keep an eye on this though. 
You are sure that you did not compare after you walked a few steps (20 is like going to the bathroom or kitchen)? Synchronizing does not sync the most recent values but some value to a given time. Therefore the app can lag behind the band (at least mine does). This is usually only one minute or so in my case. Just pointing this out maybe you moved shorty before syncing and comparing the values. In that case everything might be okay after all.

**Comment by Jojonintendo** [comment]
@bluuub I didn't know that syncing data would not sync everything, so it could actually be that I didn't wait enough to see. I know I made sure not to move while comparing, but I didn't wait 2-3 mins to sync. I'm sure we can test some more.

**Comment by bluuub** [comment]
Sure :-) 
I will definitely report it here if I face deviations. Until now however (~3 days) everything worked fine and both values were perfectly in sync (except the little lag described above of course).

**Comment by 6arms1leg** [comment]
> I didn't know that syncing data would not sync everything, so it could actually be that I didn't wait enough to see. I know I made sure not to move while comparing, but I didn't wait 2-3 mins to sync.

Same here. I will keep that in mind in my next tests...

**Comment by walkjivefly** [comment]
I've been using self-built 0.16 since about 22 December and self built 0.17 for the last few days. I haven't seen a single step count mismatch after sync in all that time. Not saying it doesn't happen, this is just fyi.

**Comment by 6arms1leg** [comment]
Actually, I don't have that issue anymore either. I remember it happened to me only when I was way above 10.000 steps – but lately I rarely reach such high values.
Since it is/was really a minor issue and I can't reproduce it anymore, feel free to close this one (and label it as a "non-issue"). The issue tracker is overflowing right now anyway and there are more important issues to work on. We could reopen it , if it becomes a problem again... (if that's OK with you)

**Comment by Jojonintendo** [comment]
I couldn't find any deviation on my end either. I rarely see such high values anyway, but it is always in perfect sync (if you wait a little before syncing, as said above).

**Comment by bluuub** [comment]
Same here. I think this is really related to waiting long enough with syncing after moving (see my post above). I ckecked multiple times (daily steps are around 10-12k) and never faced any deviations. Closing this issue would be appropriate imo.

**Comment by 6arms1leg** [comment]
@danielegobbetti, could you please label this as a "non-issue"?
And sorry for the noise... :see_no_evil:

**Comment by cpfeiffer** [comment]
Thanks for the feedback and for closing this :-)
