### ISSUE TITLE
PebbleNotificationCenter

### ISSUE THREAD

**Issue by giuliovale** [Freeyourgadget/Gadgetbridge#502]
Any possibility to use https://github.com/matejdro/PebbleNotificationCenter-Android for notification ?

**Comment by ashimokawa** [comment]
Did you try it?
Did you enable 3rd party android app support in Gadgetbridge?

**Comment by giuliovale** [comment]
Uau work!
I have to disable access to notification inside Android for Gadgetbridge and Notification Center work.
Thanks
