### ISSUE TITLE
Cannot install some pbw/pbz with Gadgedbridge but official app works

### ISSUE THREAD

**Issue by ConniShiva** [Freeyourgadget/Gadgetbridge#505]
####Your issue is:
Hi,
i have a new pebble and tried to make it work with GB.
Connection went fine, but when it came to flashing the initial firmware GB said my pbz was broken.
So I redownloaded an retried (directly from downloader/filemanager) but gave up and initialized the watch using my GF phone.
Then i tried installing some pbw back on my phone using GB and only a few worked. figured it might be real compatiblity so i didnt investigate further.
But then retried the original app for something else and was able to successfully install the app GB said was damaged/incompatible. Another app was installable via both apps, so its not my mobile/filemanager/setup.

the app/watchface that only is installabe via official app is:
https://apps.getpebble.com/en_US/application/52997231129af73409000033?section=watchfaces

and the app that works either way is:
https://apps.getpebble.com/en_US/application/5678a623bdb5f02ca2000054?query=info%2520timer&section=watchapps

not sure if apps/watchfaces make a difference, new to all this. Not sure what the Log settings do, so without further assistance i cannot add these

####Your wearable device is:
Pebble time round FW 4.3

####Your android version is:
6.0.1 (november security patches)
GB 0.16 fdroid

**Comment by danielegobbetti** [comment]
Can you try sharing the pbz/pbw (using the android share feature) to gadgetbridge? The feature was added lately and since I suspect the problem lies in accessing the file it could help.

In any case, without logs we cannot really do much. What kind of instructions do you need in order to get them?

**Comment by ashimokawa** [comment]
I can confirm the issue.

**Comment by danielegobbetti** [comment]
You mean with pbw or with pbz as well?
