### ISSUE TITLE
Glance is crashing GadgetBridge on Refresh data

### ISSUE THREAD

**Issue by ya-isakov** [Freeyourgadget/Gadgetbridge#506]
####Your issue is:
Here is a traceback https://nopaste.me/view/0b411566

####Your wearable device is:
Pebble Steel

####Your android version is:
LG G3 5.0

**Comment by ashimokawa** [comment]
@ya-isakov 
A logcat (or the log file if you have logging enabled in Gadgetbridge) would have been better, then I could have a look at the encoded JSON and see why our decoding fails.

Anyway in 0.17.1 (tagged, soon on f-droid) there is a chance that I fixed it blindly.

**Comment by ya-isakov** [comment]
Sorry, I've missed few lines from my previous logcat, here is a more complete output:
https://nopaste.me/view/4fe388af

**Comment by ya-isakov** [comment]
I've built 0.17.1 myself, and now Glance is working, so thank you a lot for fixing this!
