### ISSUE TITLE
Square Watchface has 'CfgKeyWeatherError' when changing settings

### ISSUE THREAD

**Issue by jgkamat** [Freeyourgadget/Gadgetbridge#507]
Not sure if this is a gadgetbridge issue or an issue with square, the watchface I am using:
####Your issue is:
When I try to configure square, I get an error in the keys that gadetbridge is sending to the device.

When using the stock square watchface (5.6), everything works prefectly, including weather now! However, once I push the broken configuraiton, I get warnings for the weather data on the watchface, but everything else works fine. The screenshots below will help make a lot more sense. Logs of me configuring the device are attached.

![screenshot_20170118-153440](https://cloud.githubusercontent.com/assets/4349709/22082073/3e649f5e-dd94-11e6-8fed-716afb3bbb39.png)
![screenshot_20170118-153444](https://cloud.githubusercontent.com/assets/4349709/22082075/3e66acb8-dd94-11e6-99ab-2fd6e61405a3.png)
![screenshot_20170118-153451](https://cloud.githubusercontent.com/assets/4349709/22082074/3e64bc8c-dd94-11e6-8d51-50b4b2a03d67.png)
![screenshot_20170118-153455](https://cloud.githubusercontent.com/assets/4349709/22082072/3e6309dc-dd94-11e6-9714-d8071e120fe7.png)

Logs (not 100% sure I did this right, I can try again if you think something is wrong. I got these logs through alogcat):
```
I/ActivityManager( 5175): START u0 {cmp=nodomain.freeyourgadget.gadgetbridge/.activities.ExternalPebbleJSActivity (has extras)} from uid 10485 on display 0
D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService( 6770): Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.startapp
I/ActivityManager( 5175): Displayed nodomain.freeyourgadget.gadgetbridge/.activities.ExternalPebbleJSActivity: +71ms
I/chromium( 6770): [INFO:CONSOLE(260)] "PebbleKit JS Ready!", source: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/pbw-cache/cb332373-4ee5-4c5c-8912-4f62af2d756c_config.js (260)
I/chromium( 6770): [INFO:CONSOLE(188)] "Getting weather", source: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/pbw-cache/cb332373-4ee5-4c5c-8912-4f62af2d756c_config.js (188)
I/chromium( 6770): [INFO:CONSOLE(200)] "Showing configuration page", source: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/pbw-cache/cb332373-4ee5-4c5c-8912-4f62af2d756c_config.js (200)
I/chromium( 6770): [INFO:CONSOLE(168)] "Error requesting location! No manual location entered.", source: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/pbw-cache/cb332373-4ee5-4c5c-8912-4f62af2d756c_config.js (168)
E/nodomain.freeyourgadget.gadgetbridge.util.GB( 6770): Uncaught TypeError: Cannot read property 'hide' of undefined
V/NotificationService( 5175): notifications are disabled by AppOps for nodomain.freeyourgadget.gadgetbridge
E/NotificationService( 5175): Suppressing toast from package nodomain.freeyourgadget.gadgetbridge by user request.
I/chromium( 6770): [INFO:CONSOLE(260)] "PebbleKit JS Ready!", source: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/pbw-cache/cb332373-4ee5-4c5c-8912-4f62af2d756c_config.js (260)
I/chromium( 6770): [INFO:CONSOLE(188)] "Getting weather", source: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/pbw-cache/cb332373-4ee5-4c5c-8912-4f62af2d756c_config.js (188)
I/chromium( 6770): [INFO:CONSOLE(211)] "Configuration page returned: {"CfgKeyWeatherMode":{"value":"1"},"CfgKeyUseCelsius":{"value":true},"CfgKeyWeatherLocation":{"value":""},"CfgKeyLanguage":{"value":"0"},"CfgKeyEuropeanDate":{"value":false},"CfgKeyHourlyVibe":{"value":false},"CfgKeyVibeOnDisconnect":{"value":true},"CfgKeyVibeOnConnect":{"value":true},"CfgKeyInvertColours":{"value":false},"CfgKeyShowSeconds":{"value":false},"CfgKeyMiddleBarMode":{"value":"1"}}", source: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/pbw-cache/cb332373-4ee5-4c5c-8912-4f62af2d756c_config.js (211)
I/chromium( 6770): [INFO:CONSOLE(219)] "Lang is 0", source: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/pbw-cache/cb332373-4ee5-4c5c-8912-4f62af2d756c_config.js (219)
I/chromium( 6770): [INFO:CONSOLE(223)] "Location is ", source: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/pbw-cache/cb332373-4ee5-4c5c-8912-4f62af2d756c_config.js (223)
I/chromium( 6770): [INFO:CONSOLE(168)] "Error requesting location! No manual location entered.", source: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/pbw-cache/cb332373-4ee5-4c5c-8912-4f62af2d756c_config.js (168)
D/nodomain.freeyourgadget.gadgetbridge.activities.ExternalPebbleJSActivity( 6770): from WEBVIEW: {"CfgKeyWeatherError":"error"}
I/nodomain.freeyourgadget.gadgetbridge.activities.ExternalPebbleJSActivity( 6770): {"10003":"error"}
D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService( 6770): Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.app_configure
I/nodomain.freeyourgadget.gadgetbridge.service.devices.pebble.PebbleProtocol( 6770): got APPLICATIONMESSAGE/LAUNCHER (EP 48)  ACK
```

####Your wearable device is:
Pebble v1_5, FW: 3.12.3

####Your android version is:
Cyanogenmod 13

Let me know if I can provide any other information. Thanks so much for creating this app! without it I would have never bought a pebble :smile:

**Comment by jgkamat** [comment]
One more thing, these are my location settings (I think there are some location errors in the logs). I think it seems configured correctly (It's getting my location just fine).
![screenshot_20170118-154332](https://cloud.githubusercontent.com/assets/4349709/22082236/ecaabdfa-dd94-11e6-9d44-ad83d424676e.png)

**Comment by jgkamat** [comment]
Oh, I'm an idiot. 

For anyone running into this, you need to set your location in the configuration page of square itself. I'm not sure why the GPS function is not working for square though (it says that it should on the configuration page). 

To any dev's looking at this, can you try to figure out why that autolocation feature isn't working (I don't know anything about pebble/android development). If you think that gadgetbridge can't fix this, go ahead and close this issue.

Thanks again for all your hard work! :smile: :tada:

**Comment by danielegobbetti** [comment]
I'm glad you got it working! Your issue, while not a bug, means we need to enhance our documentation and/or the feedback a user is seeing so thanks for reporting this with such details!

**Comment by jgkamat** [comment]
Going to close this since I don't think there's much gadgetbridge can do. If you think this should be reopened, feel free to reopen it! :smile:
