### ISSUE TITLE
Documentation of firmware version related issues

### ISSUE THREAD

**Issue by blinkenlight** [Freeyourgadget/Gadgetbridge#508]
Please consider adding a few words to the Readme (to the "known issues" of Mi bands or wherever else you see fit) about the incompatibility of GB with certain firmware versions and the resulting need to check what one actually has - I consider myself reasonably tech savvy yet I was going nuts for quite a while before I completely accidentally stumbled upon the firmware section of the wiki which finally explained very neatly that my newly acquired Mi-1S with its original out-of-the-box 4.15.11.19 firmware is in fact well known to just half-work. Popping up a warning about detected unsupported firmware versions in the app itself would be even nicer of course but not vital - I did read the general Readme, but there was nothing in there about some versions of the same device being incompatible...

**Comment by danielegobbetti** [comment]
Would you mind making a proposal for the readme?  Feel free to open a pull request as well! I agree that the warning inside the app would also be a good idea

**Comment by 6arms1leg** [comment]
> Would you mind making a proposal for the readme? Feel free to open a pull request as well!

Hope that's OK.

**Comment by cpfeiffer** [comment]
Yes, thank you! I totally agree with @blinkenlight though -- I always wanted to add a warning directly in Gadgetbridge about the problematic default firmware.

So I'll keep this issue open for this.

**Comment by IzzySoft** [comment]
As this is part of the firmware specific pages for Mi Bands [1](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Information), [2](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-2-Firmware-Update), [3](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-3-Firmware-Update) and [4](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-4-Firmware-Update) now (see the "known issues" column in the resp. firmware listings), I'm closing this now. Thanks for all who contributed!
