### ISSUE TITLE
Regression: WatchApp data fails?

### ISSUE THREAD

**Issue by IzzySoft** [Freeyourgadget/Gadgetbridge#509]
#### Your issue is:
I'm using *Locus Map Pro* with the [Locus - addon pebble](http://www.appbrain.com/app/com.gilisztaturmixgmail.locus_addon_pebble) and the [corresponding WatchApp](https://apps.getpebble.com/en_US/application/5781754a6c21044501000f25?section=watchapps&section=watchapps&dev_settings=true&hardware=basalt&is_browser=true&platform=android). When last tried (around GB 0.15), it worked fine. Neither Locus nor the addon nor the WatchApp were updated since then, but GB was. Now when I wanted to use it again yesterday, it failed:

* Locus can start the WatchApp fine
* The WatchApp also can start Locus fine
* after being started, the WatchApp hangs with the message "Waiting for a connection to Locus Map". Forever.

Getting a Logcat is hard currently, especially due to the weather: until I'm back inside again (half frozen), the logs are almost flushed out of the ring buffer… But I can of course "try blind" if that helps.

#### Your wearable device is:
Pebble Time Steel, FW 4.2

#### Your android version is:
5.1.1 (CyanogenMod 12.1)

#### Your Gadgetbridge version is:
0.17

Remark: @ashimokawa seems to have an idea already… hopefully ;)

**Comment by ashimokawa** [comment]
@IzzySoft 
I had the same problem "waiting for a connection to Locus Map" when I tried the apk on my test device (which can be temporarily infected with proprietary crap behind a firewall) with older GB Versions but it was easier to to get a reply from the Android App there (by mashing the up button).

I could add a config option to restore the old behavior - but it would not be the proper fix.

I have no idea why some PebbleKit apps refuse to send data to us (or we fail to receive them) and spend already countless hours on that.

**Comment by IzzySoft** [comment]
I never had that issue with previous versions of GB – though it took me a while to figure out how to correctly configure the different pages to show the details I needed. And while that option admittedly would not be the proper fix, it would be an acceptable work-around until a proper fix is found :)

**Comment by danielegobbetti** [comment]
@IzzySoft the version with the workaround hit fdroid lately. Can you please check if the workaround works in your use-case?

**Comment by IzzySoft** [comment]
@danielegobbetti Sure. I've just updated and will check ASAP and report then.

**Comment by IzzySoft** [comment]
Unfortunately, it's not fixed. With the new "premature ACK" unchecked, the Pebble keeps displaying "waiting for connection to Locus". With the option checked (and the watch reconnected), the Pebble screen simply stays blank.

**Comment by danielegobbetti** [comment]
Is this still the case in the release currently out?

**Comment by danielegobbetti** [comment]
Closing this for now, please reopen if appropriate

**Comment by IzzySoft** [comment]
Sorry for being late: Yes, it's fixed. And got nothing to do with the "premature ACK", apparently.
