### ISSUE TITLE
Xiaomi Mi Band 2 pairing issue with GadgetBridge

### ISSUE THREAD

**Issue by phoenix31121** [Freeyourgadget/Gadgetbridge#514]
Issue: The Mi Band 2 doesn't pair with GadgetBridge, but works flawlessly with the Mi Fit app.
Device: Xiaomi Mi Band 2 (on the latest 1.0.1.29 as well as 1.0.0.39)
Phone: Galaxy S5 rooted stock 6.0.1 (Security patch level Oct 1, 2016)

Details: 
I was trying to pair my Band 2 with GB because the latest Mi Fit app updated the firmware the latest 1.0.1.29 which broke the heart rate sensor. I tried GB on two S5's which i had with the same result of not getting paired.
GB discovers the Band 2 and does the pairing in the bluetooth pair in settings, but doesn't authenticate. It just goes on trying to connect when restarting the process, or it shows "connecting" then back to "not connected" after a few seconds if it was already discovered.
After going through the forum, i noticed some posts mentioned where people had successful connections with phones like HTC one, which i suspected was on either android 5.0 or 6.0 (as of official specs)
So, i tried to connect my band with GB on the 2015 J5 which was running stock 5.1 and it connected to the band without hiccups, and downgraded the firmware.
Im not sure but could it be a compatibility issue of GB with android MM? I attached both the log files as referenced by @6arms1leg.

[btsnoop_hci.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/720891/btsnoop_hci.zip)
[gadgetbridge.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/720892/gadgetbridge.zip)

**Comment by cpfeiffer** [comment]
I have seen other connection problems with Galaxy devices (it was an S7, IIRC). Connection also failed with Mi Fit, but a later version fixed that.

The gadgetbridge.log only displays as sudden disconnect right after the connection was established. The hcidump unfortunately contains too little data. Try enabling the capturing right before pressing the item to connect to your band and disable it again when that failed.

Did you have Location (GPS or network) enabled during the discovery process? That's needed on MM.

**Comment by phoenix31121** [comment]
Hello @cpfeiffer, yes i put location service on high accuracy mode just to be sure gps only mode wasnt the cause. 
Through disvovery mode it finds the device, I clicked on the name, accept dummy variables, and it gives a pop up saying creating bond.
Waited 10 minutes to pair in discovery mode and then pressed back to the main page and tapped the device name where it says not connected, changes to connecting briefly and back to not connected.
I attached the new logs here.
[gb bt log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/725517/gb.bt.log.zip)

**Comment by cpfeiffer** [comment]
Thanks for the logs. Unfortunately I have no idea what's happening here. The moment we try to register for notifications on the "authenticate" characteristic, it just drops the connection.

As  you said, it worked with with Gadgetbridge on another phone, your suspicion of some compatibility issue is probably correct.

Do you happen to know whether your band is paired on the bluetooth level by Mi Fit. Or does it connect to your band without pairing?

I've seen some problems with pairing and connecting to paired devices, and I've seen Mi Fit talking to unpaired devices.

**Comment by cpfeiffer** [comment]
Related to #512

**Comment by phoenix31121** [comment]
Hi @cpfeiffer, yes, gb worked perfectly on the galaxy j5 i tried on. Discovered, then paired within a few seconds. 

Im not sure about the bluetooth lever pair through mi fit. When the band is unpaired it shows up in bt settings. When i try to pair the band through mi fit, but before pressing on the band when it vibrates, it disappears from the bt settings. 

But when i tried to pair through gb it doesnt disappear, but it shows as if its connected in bt settings with a gear button which when pressed shows unpair and rename device.

I did unpair the band from the mi app and unstalled it before trying with gb. The 2nd s5 and j5 werent mine so i never installed mi fit on them, only gb. 

Does it make a difference if the s5 i have is the international exynos variant? Im not sure about the j5 (sd or exynos)

**Comment by cpfeiffer** [comment]
So it looks like Mi Fit does not pair the band on bt level (as it's not visible in Android's bt settings), while Gadgetbridge does that.

I will try connecting without pairing.

**Comment by cpfeiffer** [comment]
The next release will have an option in the Mi Band preferences to disable the BT pairing. Please uncheck the optoin, unpair your device in Android's BT settings, and invoke device discovery from Gadgetbridge to perform a "fresh connect".

Hope this helps.

**Comment by phoenix31121** [comment]
Hi @cpfeiffer, 
I have my fingers crossed for now. The next release with this option will be 17.3?
Thanks for all the effort you put into this.

**Comment by cpfeiffer** [comment]
0.17.3 is available in f-droid, please try the new option and report if this fixes the issue.

**Comment by phoenix31121** [comment]
Hi @cpfeiffer
Im happy to say that the band got paired after unchecking the bt pair option.
Thank you so much!

**Comment by cpfeiffer** [comment]
Cool, thanks for the feedback :-)
