### ISSUE TITLE
excessive notifications

### ISSUE THREAD

**Issue by ec1oud** [Freeyourgadget/Gadgetbridge#516]
#### Your issue is:
K9 mail is having trouble with the certificate on my mail server.  I tell it to accept the cert, and then next time it checks mail, it complains again.  It seems I can't fix that cert problem directly (the mail server is not one I administrate myself - that's the root cause), but it keeps sending useless notifications to my watch every few minutes.  So I had to blacklist K9mail.

![screenshot_20170123-083908](https://cloud.githubusercontent.com/assets/2946740/22198320/558ac972-e156-11e6-937d-34a03ffba803.png)

I have some birthdays in my calendar.  The watch is notifying me about those periodically too.  I have to keep dismissing the notifications over and over, and it's really annoying.  I ask for one notification two days before the birthday, and instead it's notifying me repeatedly all day long that my sister's birthday is in 2 days, starting early in the morning.  And yet it's not showing up in the timeline at all.  Birthdays (at least important ones) would be mainly useful in the timeline, and probably the best time to get a notification is when I get up in the morning and put the watch on (or start moving around, if I was wearing it to bed, which I never do.)  It's possible to use vector magnitude counts to detect when the user is active.  (I've been experimenting with that in my weather app: I have the watch face learning on which days I'm active at which times, by storing VMC vectors persistently, and then asking the phone to fetch the weather in advance.  So when I'm active I have updated weather, and when I'm not, there's no point in wasting bandwidth on it.)

What these have in common is that they never need to occur more than once per day.  The calendar event is an all-day event.  And I don't particularly need to be nagged about my email provider's certificates at all, but even if I did, once a day would be enough.

Back when I was running the official Pebble app, every time I took a trip I'd be notified several times too: once from the calendar, once because there was a timeline pin provided by the travel app, and I'm not sure from where else.  It was impossible to forget about a flight, but one or two notifications at specific intervals before the flight would be enough.  It would even be better if it could silence the notifications after detecting that I'm already at the airport, but leave the flight details in the timeline.

So I think GB needs to have a feature to limit the frequency of notifications based on type and topic.  Of course knowing that a new notification is about the same topic as a previous one, when they come from multiple sources, is the hard part (maybe need to identify that the text similarity is over a certain threshold, so it must be about the same topic), but in the case of the present problems, K9mail and Calendar are the sources, so it's pretty easy: the text is identical each time, and the source is the same too.

You can't depend on such bugs being fixed in the apps, especially when apps have a different model of what notifications are for (if they are just refreshing the Android notification, that doesn't necessarily disturb me - it just sits there taking up space in the pull-down notifications window).  GB sends them to the watch, so it needs to somehow be smart about which ones I really need.  The watch (and GB) is there to provide a useful service, not to be an annoyance.  Timely notifications are one of the main reasons to have a smartwatch.  If I have to turn off all notifications because they are only an annoyance, it makes me wonder: why am I wearing a smartwatch at all?

#### Your wearable device is:
Pebble Time Steel firmware 4.2

#### Your android version is:
4.4.4 Kitkat - Cyanogenmod on a Galaxy Note N7000; no GApps, only free software installed via F-Droid

#### Your Gadgetbridge version is:
0.17.0

**Comment by danielegobbetti** [comment]
Can you please search in the logs the rows mentioning the notification flags? Perhaps we can identify them this way.

**Comment by ashimokawa** [comment]
How about asking K9 developers to add and "ignore certificate errors" option for the "brave"
I see this totally misplaced here

**Comment by danielegobbetti** [comment]
No feedback, closing. Please reopen once you can provide the requested info.
