### ISSUE TITLE
Pebble App Manager - Installer

### ISSUE THREAD

**Issue by Avamander** [Freeyourgadget/Gadgetbridge#520]
Could you please make it possible for one to open Gadgetbridge, then open the installed system apps menu and through a menu option or similar, allow the installation of a .pbw file (with Android's file selector), the current way (of opening the file) seems more of an additional bonus, not fully featured function.

**Comment by danielegobbetti** [comment]
Hello, "a menu or something similar" is not actionable. If you have a clear idea please provide a mockup (even better a design, even better a patch to the layout/menu file) and reopen the issue.

**Comment by IzzySoft** [comment]
@danielegobbetti What @Avamander probably meant was having a menu item which calls up a file selector to pick a `.pbw` from. Seen similar things in other apps as well. If not as a menu item, a button would do as well. Even that crazy "hovering +" which is so typically used with "material design". And I agree: the app manager would be the most logical place to look if you want to install a new app :blush:

**Comment by Avamander** [comment]
Actually menus are pretty clearly defined https://developer.android.com/guide/topics/ui/menus.html. Floating action button would look okay if the rest of the UI was material not holo. Thus would require bigger changes than adding a three-dot menu would.

**Comment by ashimokawa** [comment]
There is a PR for this. I never merged it though.
I will have a look at it.

**Comment by danielegobbetti** [comment]
The mentioned pr is #247 

I see a number of problems that are not addressed neither there nor here:
- we have three tabs (cached pbw, apps, faces), where do we put the menu/the FAB?
- if we put the menu/FAB in the apps/faces fragment, what should happen if I choose "Install new face" and then choose the pbw of an app? (Please note that we get the info of what kind of pbw it is only **after** the user chose it)
- if we put the menu/FAB in the cache fragment, should it only be copied in the cache or directly installed? 
- what do we do to adress the fact that we support android from version 19 and onwards, hence a number of versions without android storage framework?

That's what I mean when I say "non actionable".

**Comment by Avamander** [comment]
1. All of them, the overflow/three-dot menu is on the title/action bar
2. The menu option should be "Install .pbw"
4. If the storage framework is missing, open file explorer and long toast "Select .pbw"
