### ISSUE TITLE
UI speedup

### ISSUE THREAD

**Issue by Avamander** [Freeyourgadget/Gadgetbridge#521]
Opening this issue to mention that the user interface might need some rework due to it's occasional sluggishness. Overall the app behaves well in terms of speed but this would now be a good place to discuss possible methods how to make it faster and maybe share any knowledge that might help speeding up the app. (Profiling results, slow functions/calls and so on)

**Comment by danielegobbetti** [comment]
Please use the issue template and report which part of the app feel "sluggish" on your device.
Closing
