### ISSUE TITLE
Transliterate Caller Name

### ISSUE THREAD

**Issue by jpbarraca** [Freeyourgadget/Gadgetbridge#522]
Caller name is not transliterated as the notifications text is.
This is a problem for devices with reduced charset support such as the HPlus devices.

@ivanovlev

**Comment by ashimokawa** [comment]
This could be fixed by #513 
But the testcase is broken, that is why I didnt merge it

**Comment by ivanovlev** [comment]
Hmm, looks like GBDeviceService.**onSetCallState** dont have callSpec.name, it's null and will found later, by DeviceCommunicationService.**getContactDisplayNameByNumber**

**Comment by cpfeiffer** [comment]
IMHO the device communication service should not perform such things. As we still want to centralize it, we have to do it on "the other side", i.e. GBDeviceService. So, either put the functionality into a helper class or directly into GBDeviceService.

**Comment by ivanovlev** [comment]
Ok, I get around to it tomorrow evening

**Comment by cpfeiffer** [comment]
Should be fixed, thanks @ivanovlev!

**Comment by jpbarraca** [comment]
Thanks!
