### ISSUE TITLE
Mi Band 1S keeps vibrating and HR lighting after I woke up

### ISSUE THREAD

**Issue by bkt** [Freeyourgadget/Gadgetbridge#526]
I just installed gadget bridge (I dont have mi fit app), and just set one alarm for waking up.

When I woke up I took off the band, and it kept vibrating and HR lighting. I tried disabling alarms, and disconecting bluetooth but it kept vibrating every now and then and HR lighting. Now I am at work and probably the band it is still vibrating and HR lighting¿?¿?

I want to "turn off" the band after waking up, since I am not using it during the day.

By the way, the smart alarm did not work, It woke me up at exactly the time I set.

FW: 4.15.12.10 Mi Band + 1.3.74.64 HR

**Comment by b16r05** [comment]
New to github, hope I am doing this right. Not sure how to add labels, which IMHO should be: bug, Mi Band 1S, Mi Band 2.

My problem is the same as OP. I have 2 Mi Band 2 devices. One is worn all the time. The other, is worn throughout the day, but not at night while sleeping. 

Problem occurs as OP described above... possibly vibrating, but the HR light comes on when not worn. Seen it when it is lying in the bathroom... ON... OFF... ON... OFF at night!

Not sure smart (or any) alarms are set at all. Obviously the band with the problem discharges at a faster rate than the one without any issues.  Never used Mi app with it... started use with GB : )

Device: Mi Band 2 | FW: V1.0.1.28 | HW: V0.1.3.2 | GB: 0.17.2

**Comment by walkjivefly** [comment]
Do you have any notifications enabled? Although they're only a possible vibration cause if BT is connected...

Do you have HR assist for sleep detection turned on? That could explain the HR light coming on periodically.

**Comment by b16r05** [comment]
Ah... HR assist is switched on for one of the bands and is not being used while sleeping... that could explain HR light activity. I am going to turn it off and give it a few days... charging both devices to 100% battery and see what it shows in a few days. 

Yes, notifications are enabled for some items, but Bluetooth remains off, until I am ready to sync (both devices)... so I will hold off looking into it at the moment.

**Comment by cpfeiffer** [comment]
1) The hr measurements are the sleep assist feature as @walkjivefly already mentioned
2) You have to dismiss the alarm on the band, otherwise it will return repeatedly

I'm pretty sure this is unrelated to Gadgetbridge, since this will happen even when Bluetooth is off. Otherwise, feel free to reopen the issue.
