### ISSUE TITLE
Generic Notification Vibration Too Long - MiBand

### ISSUE THREAD

**Issue by chrisvella** [Freeyourgadget/Gadgetbridge#53]
Generic notifications send 6 vibrations to my miband. For a single notification (i.e. a conversations message) its a too much. Could the vibration duration be changed to 1-3? A variable option would be even better.

Thank you for the wonderful application. Still looking for a way to donate :)

**Comment by cpfeiffer** [comment]
Yes, we want that, see #37 and #29.

It's actually quite easy to do, the code is all prepared for that. Someone would just have to implement https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/miband/MiBandSupport.java#L63 properly and then call that from https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/miband/MiBandSupport.java#L130

It's one of the more easy tasks, so I deliberately left open for a while for someone who wants to get involved :-)

**Comment by chrisvella** [comment]
Sadly my experience in Java is extremely limited. When I get time I might have a go at it.

Thank you for the app so far.

**Comment by ashimokawa** [comment]
I have a lot of Pebble TODOS but if I am in the mood for an easy task I might take it.

**Comment by cpfeiffer** [comment]
@chrisvella yes, don't worry, eventually we'll get to it :-)

**Comment by ashimokawa** [comment]
Added preferences, still unused
