### ISSUE TITLE
GB dont automatically reconnect After MiBand 1 come back  in range 

### ISSUE THREAD

**Issue by siSSSou** [Freeyourgadget/Gadgetbridge#530]
#### Your issue is:
GB dont automatically reconnect After MiBand 1 come back  in range.
Is there à Way to set intervals for GB to try to reconnect ?

**Comment by cpfeiffer** [comment]
"Last version" doesn't really help, so I assume 0.17.3.

Have you enabled automatic reconnection in the preferences?

**Comment by siSSSou** [comment]
This is version 0.17.3 indeed.
Automatic reconnection is enabled, but I have to manually reconnect everytime.

**Comment by cpfeiffer** [comment]
What does Gadgetbridge show as device status? "Waiting for reconnect" or "Disconnected"? Can you attach a log?

**Comment by siSSSou** [comment]
Device status is "Disconnected"

Here is a logfile for 1.devive connected, 2.then device is out of range, 3. device is back in range but doesn't reconnect and 4. device is manually reconnected at the end :
[gadgetbridge.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/737388/gadgetbridge.txt)

**Comment by cpfeiffer** [comment]
The log confirms the behavior:
> 23:15:15.179 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
23:15:15.189 [Binder_2] INFO  n.f.g.s.b.BtLEQueue - Enabling automatic ble reconnect...
23:15:15.197 [Binder_2] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: WAITING_FOR_RECONNECT
23:15:15.260 [Binder_3] DEBUG n.f.g.s.b.BtLEQueue - connection state change, newState: 0 (failed: 133)

Maybe you device's BT stack does not like the immediate reconnection attempt.

**Comment by ivanovlev** [comment]
Hmm, me too. Hplus (zeband), reconect is on. 

Connected device, status "connected". Then i put it to microwave, close door, device was lost (status "disconnected"). Then i open microwave door, put device near phone - zero results - after 5 minutes still "disconnected"

**Comment by bigretromike** [comment]
Mi Band 1S, wont rarely reconnect. Usually it does but not always. LineageOS (Android 7.1.1)

**Comment by jpbarraca** [comment]
HPlus also doesn't reconnect as often as expected.

**Comment by cpfeiffer** [comment]
No wonder it won't reconnect, at least in @ivanovlev's case. When disconnected, it receives the status `0`, which used to mean "regular disconnect", e.g. when manually disconnecting.

When disconnecting due to other reasons (e.g. out of range), the status used to be non-zero, so that's when we enabled re-connection.

Looks like we need to find a different way to distinguish manual and unwanted disconnects.

**Comment by lazarosfs** [comment]
I have solved this in mi band2.
I dont know if same problem for others please test.
have a look at https://github.com/Freeyourgadget/Gadgetbridge/issues/564
