### ISSUE TITLE
Displaying information on band chosen by the user

### ISSUE THREAD

**Issue by yash-bhavsar** [Freeyourgadget/Gadgetbridge#531]
I am trying to build a new app based on GB. Currently am working on the feature that MiFit has, option for the user to choose the information he wants to see on the band like calories, distance, steps, battery level, pulse rate. By default, the band displays steps pulse rate and time.

I have already changed the miband_preferences.XML file and accordingly have made changes in the project, but I don't know which service to use and what commands to pass to make it work.  
For the datetime feature, GB uses UUID_CHARACTERISTIC_3_CONFIGURATION service and DATEFORMAT_TIME, DATEFORMAT_DATE_TIME commands. In the same way for my feature, I tried to use the same service with different commands but wasn't successful. If anybody knows how to solve this issue please help.

**Comment by danielegobbetti** [comment]
Cool that you're working on your own app, please open an issue in the issue tracker of your project.
