### ISSUE TITLE
Missing vibration when Alarmclock triggers

### ISSUE THREAD

**Issue by Frozen-byte** [Freeyourgadget/Gadgetbridge#538]
#### Your issue is:
When my Alarmclock begins to ring, the Smartwatch stays quiet even if it's connected via bluetooth!

#### Your wearable device is:
MiBand 1S

*Please specify model and firmware version if possible*
FW:4.16.4.22

#### Your android version is:
7.0

#### Your Gadgetbridge version is:
0.17.3

**Comment by cpfeiffer** [comment]
This is unrelated to Mi Band, I think -- we simply do not get an event when an alarm goes on. Looking for a way to get that.

Which ROM do you have (in case it has a custom alarm clock)?

**Comment by Frozen-byte** [comment]
My apk is the default from Nougat 7.0; I guess.
Using a OnePlus3 with Oxygen OS v4.0.2
App Info: Clock v4.1.0

**Comment by cpfeiffer** [comment]
Thanks -- the new version 0.17.4 contains the changes. If this does not work on your device, please comment/reopen this issue. Thanks!
