### ISSUE TITLE
HPlus: Time sync broken

### ISSUE THREAD

**Issue by ivanovlev** [Freeyourgadget/Gadgetbridge#539]
Zeband Zeblade

PR 532 breaks time sync. After reset device always show 8:20 AM. Time synchronization does not work.

I just wanted to test the alarm clock ...

@jpbarraca

**Comment by jpbarraca** [comment]
Strange...  Mine seems to be ok. I will try to look at it today.
Alarm are simple (just set a recurrent time) but they are working.

**Comment by jpbarraca** [comment]
@ivanovlev can you confirm the issue is solved?

**Comment by ivanovlev** [comment]
Confirm. All good
