### ISSUE TITLE
Provide shortcut zoom and pan buttons on "Your Activity and Sleep" and "Your Sleep" screens.

### ISSUE THREAD

**Issue by walkjivefly** [Freeyourgadget/Gadgetbridge#547]
#### Your issue is:
On a small screen (eg: 5" phone) it is very difficult to zoom into the charts and once zoomed to scroll them left and right. Providing zoom and pan buttons would make the charts more useful.

#### Your wearable device is:
Mi Band 2

#### Your android version is:
5.1.1

#### Your Gadgetbridge version is:
0.17.3

I'm happy to try to implement this. I might even manage to do so before more capable people resolve [#301](https://github.com/Freeyourgadget/Gadgetbridge/issues/301), [#374](https://github.com/Freeyourgadget/Gadgetbridge/issues/374) etc.

**Comment by danielegobbetti** [comment]
You are welcome to try implementing this on your own! Do not hesitate to ask if you have questions :-)

**Comment by cpfeiffer** [comment]
BTW, it is sometimes easier to pan by first swiping a little bit up and then to the left or right.

**Comment by walkjivefly** [comment]
It also seems easier to zoom if you press really hard on the screen with one finger before adding a second finger and spreading apart. I'm sure it's not really, just seems that way.

I got my dev tree into a mess by trying to have 2 branches for issue-547 and issue-496 and switching between them. I don't know git anywhere near well enough for that to not end with me in a right mucking fuddle. 

This one is currently hindered by my limited Java knowledge and a scoping problem. I've been too busy with other stuff to put in the effort to learn how to do properly what I'm trying to do.

**Comment by danielegobbetti** [comment]
We added an option to disable swiping on the screens and zooming is definitely usable now. Closing this.
