### ISSUE TITLE
Sundown and sunrise information

### ISSUE THREAD

**Issue by Avamander** [Freeyourgadget/Gadgetbridge#549]
When the sundown and sunrise information is synced with the Pebble timeline on some days it's totally off. Neither does GadgetBridge notify me of any errors in fetching the data. 

For example today it said sundown was 20:17 but it actually was 16:53. 

Please advise how and if I need to provide more details.

Pebble Time 4.3 (snowy_dvt)
Android 4.4.4 (LG D605)
GadgetBridge 0.7.12

**Comment by danielegobbetti** [comment]
Please check in the settings screen and let us know what longitude and latitude are shown there.

> Neither does GadgetBridge notify me of any errors in fetching the data.

what do you mean with this?

**Comment by Avamander** [comment]
I assumed it fetches the sunrise-sundown information from some internet source.

It says the location is 0, 0 at the moment for some reason, though it showed the right sundown-sunrise information most of the time. Is the location that "keep location updated" option fetches forgotten after a while thus resulting in defaulting to 0, 0 and displaying the wrong data?

**Comment by danielegobbetti** [comment]
> I assumed it fetches the sunrise-sundown information from some internet source.

No, all calculations are done locally (Gadgetbridge doesn't have internet access)

> Is the location that "keep location updated" option fetches forgotten after a while thus resulting in defaulting to 0, 0 and displaying the wrong data?

No.

Please tap "acquire location" once and your current position will be shown in the settings.

The position stored in the settings is used directly if "keep location updated" is not selected.
If you do select "keep location updated", Gadgetbridge tries to fetch your current position when it's needed, and will use the fallback if it fails to do so (we rely on the passive location provider).

You are welcome to add this information to our wiki so future users will not have the same problems you experienced. Thanks. I am closing this issue.

**Comment by Avamander** [comment]
Just saying that the "acquire location" button does not work because approx. location is disabled (by me) and broken (by Google) on my system. Should I create an issue about adding exact location support to the "acquire location" button? That's also why I forgot to change it from 0,0 and enabled "keep location updated".

**Comment by IzzySoft** [comment]
@danielegobbetti could that field be manually editable for such cases?

@Avamander you might wish to try UnifiedNLP (available at F-Droid). I use the entire microG stack (which has UnifiedNLP built-in) and am quite happy with it.

**Comment by ashimokawa** [comment]
@IzzySoft 
It is editable

**Comment by IzzySoft** [comment]
@ashimokawa OK. Just wondered whether that might not be the case for Avamander :) So as a work-around, he cound manually enter a location then.

**Comment by Avamander** [comment]
Yeah I did now, thanks for the help.
