### ISSUE TITLE
E-mail text no longer displayed on pebble

### ISSUE THREAD

**Issue by jkehne** [Freeyourgadget/Gadgetbridge#552]
#### Your issue is:
Since the last update, when I receive an e-mail, my Pebble only displays the account the mail was received in, plus the number of unread mails. Before the update, it would display the first few lines of text. This change removes **all** value from e-mail notifications.
I  believe f35e3e460d44c4cb8dd44969a79ddd9eccfba316 is the cause, so unless this is some kind of configuration error on my end, please revert. If the error is on my end, any help with fixing it is appreciated.

#### Your wearable device is:
Pebble classic, HW 1.5, FW 3.12.3

#### Your android version is:
6.0.1 (CM 13)

#### Your Gadgetbridge version is:
0.17.4

**Comment by ashimokawa** [comment]
@rplevka 
That is strange. We extensively tested K-9 before removing special support. I did testing with both CM13 and CM 14.1. And it worked well for me even today.

Do you have the latest K-9 version from f-droid? Or some fork?

**Comment by IzzySoft** [comment]
I may add CM 12.1 here. Works fine still. K-9 from F-Droid in my case.

**Comment by jkehne** [comment]
I have K-9 version 5.203 from F-Droid. Also, all other notifications are working fine.
If there is anything I can do to help with debugging or testing, just tell me what you need.

**Comment by danielegobbetti** [comment]
Do you by chance have the google wear app installed?

**Comment by jkehne** [comment]
No. No other google apps either for that matter.

**Comment by danielegobbetti** [comment]
In k9, which option is selected under settings -> notifications -> "lock-screen notifications"?

**Comment by jkehne** [comment]
I figured it out :)
I tried the setting you mentioned before I posted the bug report, and it had no effect on the problem. But, digging through the settings on the train this morning, I found that K-9 has **two** settings about lock screen notifications. The other one is under "Datenschutz" (in German, should be something like "privacy" in English). Apparently, the one you mentioned *hides* the email text from the lock screen, while the one I found this morning makes K-9 not write the email's subject line and content in the notification in the first place if the screen is locked. And of course, Gadgetbridge only sees what's in the notification, which in that case is nothing. After changing that second setting to never hide anything, thinks are working as expected again. I'm not sure what the default setting for that option is, but I don't recall changing it.
Anyway, problem solved for me, so I'm closing this.

**Comment by ashimokawa** [comment]
Glad you found out ;)
With the old method it would have worked but we opted to remove it for countless reasons. Good that we do not have to revert ;)

**Comment by danielegobbetti** [comment]
@jkehne FYI if you set the lockscreen privacy at the system level the notification content will NOT be shown for privacy sensitive apps (like k9) but Gadgetbridge will be able to forward their content to your device.

**Comment by jkehne** [comment]
@danielegobbetti With notifications -> lock-screen notifications, it works as well. I have currently set that to show only the number of unread emails on the lock screen, and notifications on my Pebble still work fine.
