### ISSUE TITLE
Detect Tap in Miband

### ISSUE THREAD

**Issue by pablogupi** [Freeyourgadget/Gadgetbridge#556]
Following a DMCA takedown notice, we agreed upon removing this content from our issue tracker. 
The counter notice is available here:
https://github.com/github/dmca/blob/master/2017/2017-06-20-MiBandTools-Counter-Notice.md

**Comment by cpfeiffer** [comment]
I didn't find a way to do this yet. There might be a way, possibly with a special firmware, because I once saw a "My Band", apparently a customized Mi Band which had the feature to take a photo with the mobile by shaking the band.

**Comment by yonixw** [comment]
Examples (not special firmware) 
* https://play.google.com/store/apps/details?id=xtracer.miband2funcbutton&rdid=xtracer.miband2funcbutton
* https://play.google.com/store/apps/details?id=hu.tiborsosdevs.mibandage

**Comment by yonixw** [comment]
More info : http://help.mibandtools.com/knowledge_base/topics/can-you-control-button-or-tapping-on-mi-band


And i quote:

> Mi Band 2 - this is (partially) possible and already implemented in Mi Band Tools since version 2.4.0 in semi-active mode - what this means is that our implementation in Mi Band Tools offers you a dismiss ongoing notification pattern by tapping the bracelet or dismiss / snooze ongoing alarm by tapping the button or even automatically mute the incoming call together with stopping the bracelet vibrations by pressing the button. We've implemented this feature in the most battery efficient manner since we're not listening 24/7 for the button action but only at the time frame when we're also sending vibration signals into the bracelet. Thanks to this, our implementation of this feature has literally zero impact on the battery of your bracelet and mobile phone (unlike other "competitive" applications you can find on the Play Store). Read below to learn more.

>It's important to note that this feature can never be implemented battery efficiently and stably enough to be used at all time. The thing is that without an hardware "passive" notification support, the mobile phone can not be passively notified about the button press event. What this means is that this feature can be only implementable in "active" mode - and if you would want to listen to the button for any action (e.g. to control music), your mobile phone would have to ask the bracelet every ~2-3 seconds whether the button was pressed or not.

>What this basically means that your mobile phone would never be able to go into the sleep state. Your mobile phone would have to be waken up every few seconds, which would drain the phone battery extremely quickly (literally in few hours). Since number one priority for Mi Band Tools is stability and battery efficiency and we don't want to drain your phone battery in half a day (like the "competitive" button control applications on the store does), we're not planning to implement music control or anything similar that we don't find useful - we are focused on features that are reasonable and can be implemented effectively - that's why we do offer you battery efficient dismiss and snooze features by tapping the button since version 2.4.0.

**Comment by Krashband** [comment]
Tap UUID is 00000010-0000-3512-2118-0009af100700

**Comment by cpfeiffer** [comment]
@Krashband Cool, thanks, that works. The quote from miband-tools is apparently bogus (or outdated). The band simply notifies us when the button is pressed, no need for any polling.

**Comment by cpfeiffer** [comment]
So, what shall we control with by tapping the band?

**Comment by yonixw** [comment]
sorry for the missinformation 🤕

**Comment by Krashband** [comment]
E.G. detect one, two or three touches and use to skip music track or send intent to Tasker. Like MiBand 2 Func Button App

**Comment by rgh36167** [comment]
could it be used to emulate Bluetooth media buttons events? That way a wide range of apps could be controlled.

Maybe even a Bluetooth keyboard could be done by translating Morse code.

**Comment by Frozen-byte** [comment]
Make it smart:
SimpleTap:  Pause/Start/AcceptCall
DoubleTap: Skip/Next/RejectCall/SnoozeAlarm

I am not sure if the single Tap on the MiBand may have false positives (when you are shaking your Hands i.E)

**Comment by cpfeiffer** [comment]
Shaking the band will not cause a button event (just tried).

**Comment by cpfeiffer** [comment]
@rgh36167 Do I get this right that Bluetooth media button events are Android-events that will be posted to a particular application that registered for such an event (e.g. a media player)?

So we could use this as some kind of abstract API for controlling music players (or maybe other apps that handle such events)?

**Comment by cpfeiffer** [comment]
@yonixw no worries, your comment still helped!

**Comment by rgh36167** [comment]
@cpfeifer this is how blluetooth buttons work and it would seem that you can easily generate such events at least in some Andorid versions: http://stackoverflow.com/questions/34176085/can-any-application-broadcast-intent-with-action-name-android-intent-action-med

However there is a new API since Android 4.0 so I am not sure if it still works and how. There also is  
https://developer.android.com/reference/android/support/v4/media/session/MediaButtonReceiver.html#buildMediaButtonPendingIntent%28android.content.Context,%20android.content.ComponentName,%20long%29

**Comment by rplevka** [comment]
@cpfeiffer is this planned to get implemented?
I'd make the action configurable. Personally, i'd like to be able to dismiss the notification by tapping the band.
here's my use case:
i have a phone laying on my desk while working and get many notifications, mostly e-mail ones. Since I have a RGB notification light with ability to setup custom colors for custom app notifications, I can distinguish the type of the notification by simply looking at my phone with screen off.
I usually get the gmail notifications, which i'm okay with ignoring and dismissing them. This could be simply done by tapping my band.

**Comment by rgh36167** [comment]
fyi, termux is looking to implement listening to such events
 https://github.com/termux/termux-api/issues/61

**Comment by mueller-ma** [comment]
Without any info what this was about I think you can close it

**Comment by cpfeiffer** [comment]
Right.
