### ISSUE TITLE
Feature request: Please add sleep bar chart showing last 7 days of sleep

### ISSUE THREAD

**Issue by girlwithnoname** [Freeyourgadget/Gadgetbridge#557]
#### Your issue is:
Please add a sleep chart which shows at least the last 7 days of sleep in a bar chart like the step chart already does. A weekly average value would also be cool to have.

#### Your wearable device is:
Mi band 2
Pebble time steel

#### Your android version is:
7.1.1

#### Your Gadgetbridge version is:
17.4

**Comment by ashimokawa** [comment]
@girlwithnoname 
Absolutely agree
