### ISSUE TITLE
Music Boss not functional

### ISSUE THREAD

**Issue by Miq1** [Freeyourgadget/Gadgetbridge#559]
#### Your issue is:
The Music Boss media control app seems not to work. Installation through Gadgetbridge is possible, but the app has no control over the player on the phone. When starting the app, the currently played media is displayed, but without cover art. Neither button triggers any action on the player.
Same behaviour if the watch app was installed with the Music Boss companion app.

The standard Pebble music app is fully functional.

#### Your wearable device is:
Pebble

*Please specify model and firmware version if possible*
Tiem Steel, V4.3

#### Your android version is:
7.0

#### Your Gadgetbridge version is:
0.17.4

**Comment by ashimokawa** [comment]
Did you enable 3rd Party support in Pebble settings on Gadgetbridges side?

**Comment by Miq1** [comment]
Hi Andreas,

No, third party support was not activated and after doing so it works.
Sorry bothering you ;-)

Ciao, Michael


Am 19.02.2017 11:07 nachm. schrieb "Andreas Shimokawa" <
notifications@github.com>:

Did you enable 3rd Party support in Pebble settings on Gadgetbridges side?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Freeyourgadget/Gadgetbridge/issues/559#issuecomment-280953391>,
or mute the thread
