### ISSUE TITLE
How can Delete miband2 out of gadgetbride 

### ISSUE THREAD

**Issue by Hellboy1983** [Freeyourgadget/Gadgetbridge#563]
#### Your issue is:
When I connect my miband-2 to gadgetbridge and then I can not use my miband-2 to connect to mifit on my new iphone ? The issue is mifit notice that "was used by other user" how can I delete my miband out of gadgetbridge ???
#### Your wearable device is: miband 2

*Please specify model and firmware version if possible*

Phone : xiaomi Mi-5 with miUI 8
Miband 2 : firmware V1.0.0.53 , hardware : V0.1.3.2

**Comment by ashimokawa** [comment]
@Hellboy1983 
Long-press on the device -> delete

**Comment by cpfeiffer** [comment]
@Hellboy1983 What's happening when Mi Fit complains about this? Does it not allow you to use your Mi Band then?

**Comment by danielegobbetti** [comment]
Closing as no further feedback has been provided hence I consider the issue solved.
