### ISSUE TITLE
MiBand: Locate device in a room

### ISSUE THREAD

**Issue by Baggerfahrer** [Freeyourgadget/Gadgetbridge#565]
#### Your issue is:
Is it possible to locate a MiBand2 within a room/ house? I mean to use the bluetooth mac adress & signal strenth of the miband and to locate this device (e.g. with a triangular location setting)
This feature is not specified on this app but more a general question for bluetooth.

#### Your wearable device is:
MiBand2

#### Your android version is:
Android 6

#### Your Gadgetbridge version is:
the newest one

**Comment by cpfeiffer** [comment]
Did you try long pressing the item and select "Locate device"? Not quite your approach, but maybe still a solutionm

**Comment by Baggerfahrer** [comment]
Thanks for the answer. This is not what im looking for. I want to know if its possible to locate this device in a room e.g. with triangulation and show the position on a map. Not quite specific for this project here but more A General bluetooth question.

**Comment by danielegobbetti** [comment]
Keywords for a search engine:
Bluetooth rssi triangulation

I found a couple of papers and other resources.

Closing this because it's really really really off topic.
