### ISSUE TITLE
Ring the phone from Pebble

### ISSUE THREAD

**Issue by gianlucapir** [Freeyourgadget/Gadgetbridge#567]
#### Your issue is:
*In case of a bug, do not forget to attach logs!*

#### Your wearable device is:

*Please specify model and firmware version if possible*

**Comment by gianlucapir** [comment]
Hello everyone, I tried to install on my pebble steel time the application 'Find my phone' I also downloaded on my phone, the app worked but with Pebble Gadgetbridge does not work, you know another similar app to download it both conpatibile with Gadgetbridge. Thank you! Sorry for my English, but use a translator Pebble time steel fw 4.3 Galaxy S7 Android 6.1

**Comment by ashimokawa** [comment]
Did you enable 3rd party support in pebble settings in Gadgetbridge?

**Comment by gianlucapir** [comment]
Yes, I have already enabled

**Comment by gianlucapir** [comment]
I solved, I found a compatible app that works thanks and sorry

**Comment by IzzySoft** [comment]
@gianlucapir Mind to mention the working app as well, for others in a similar situation? Links would be nice then, too (for both, the failing and the working app). Thanks in advance!

**Comment by ashimokawa** [comment]
I still want to have that in Gadgetbridge itself since I spent a lit of time searching for my phone

**Comment by gianlucapir** [comment]
L'app that works is:
RingMyPhone
https://apps.getpebble.com/en_US/application/52ed9b199755252f26000005?dev_settings=true&query=find%2520my%2520phone&section=watchapps

https://play.google.com/store/apps/details?id=com.darkrockstudios.apps.ringmyphone&hl=it
