### ISSUE TITLE
Android Calendar is not synchronized to Pebble calendar.

### ISSUE THREAD

**Issue by Bluescreen2001** [Freeyourgadget/Gadgetbridge#572]
#### Your issue is:
Maybe I simply don't see how to configure this. I get calendar notifications on my Pebble but the calendar entries are not transferred to my Pebble. The calendar is empty. The original Pebble App tranfers the next few calendar entries to the Pebble and I can watch them by pressing the up/down Buttons on the Pebble from the watchface display. 

Is there a way to see the next few calendar entries on the Pebble somehow.

#### Your wearable device is:
Pebble Classic

#### Your android version is:
5.1

#### Your Gadgetbridge version is:
0.17.5

**Comment by danielegobbetti** [comment]
The feature just landed in master and will be in the next release. See #98.
