### ISSUE TITLE
Mi Band 2: 12/24 hour clock setting

### ISSUE THREAD

**Issue by wYhyzByH** [Freeyourgadget/Gadgetbridge#573]
#### My issue is:
The Band is showing time in 12 hour mode, so currently 7:12 instead of 19:12.
In the original app there is a setting to change it (see e.g. https://www.youtube.com/watch?v=6lxj2P_7UPs).
Could you add a switch for setting this property to your app as well, please?

Changing display from "time" to "time and date" is working (both ways). Time is accurate. Language is set to German. I did not find any other way to change this mode.

#### My wearable device is:
Mi Band 2
FW 1.0.1.34
HW 0.1.3.2

#### My android version is:
Android 7.0

#### My Gadgetbridge version is:
0.17.5 (latest in F-Droid)

**Comment by cpfeiffer** [comment]
Thanks for your report. Could you provide a btsnoop for toggling 12/24 hour mode?

**Comment by yarons** [comment]
I'm trying to find this option in the Android version, none can be found, I'm using the latest version from here (2.3.0): http://en.miui.com/thread-377985-1-1.html with this FW:1.0.1.39.

**Comment by wYhyzByH** [comment]
Attached you can find the btsnoop.
[btsnoop_hci-20170303.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/816766/btsnoop_hci-20170303.zip)

To reproduce you have to install the Mi Fit app, set the time format in the android settings to 12/24 h mode and sync the band with the Mi Fit app.

As the band was automatically switched to 24h mode on first connect with the Mi Fit app, I did perform the following steps during BTsnooping:

1. change Android settings to 12h format
2. sync in the Mi Fit App
3. change Android settings to 24h format
4. sync in the Mi Fit App

Each time I checked that the band did change the display accordingly (which it did).

I did take a look at the file in Wireshark but I can't tell you more on what really went on. BT analysis is out of my scope.

**Comment by cpfeiffer** [comment]
Thanks for the log, it works. Will be in the upcoming 0.18.0 release.
