### ISSUE TITLE
Documentation to start contribution

### ISSUE THREAD

**Issue by Saurabh3012** [Freeyourgadget/Gadgetbridge#575]
Hi Team,

This project is a great initiative to save people the trouble to depend on the closed-source apps and allows people save their privacy.

I want to understand the project, just couldn't find where to start.

Is there a documentation available?

If not, I can contribute that documentation while understanding the project.

**Comment by cpfeiffer** [comment]
Hi, welcome to the club :-)

Please have a look at the wiki, for example
- https://github.com/Freeyourgadget/Gadgetbridge/wiki/Developer-Documentation
- https://github.com/Freeyourgadget/Gadgetbridge/wiki/New-Device-Tutorial

Further documentation is also in the wiki.
