### ISSUE TITLE
Some btsnoop from Mi Band Tools

### ISSUE THREAD

**Issue by yarons** [Freeyourgadget/Gadgetbridge#576]
#### Your wearable device is:

Mi Band 2, FW: 1.0.1.39, HW:0.1.3.2
Mi Fit: 2.3.0

#### Your android version is:
7.1.1
#### Your Gadgetbridge version is:
0.17.5

I was using Mi Band Tools and logged the requests for the 2 first icons (Envelope and 3 dot inside a chat bubble), here are the hexdumps of both snoops, if these are good I'll do it for the rest of the icons:
#### Envelope
```
0000000 62 74 73 6e 6f 6f 70 00 00 00 00 01 00 00 03 ea
0000010 00 00 00 0f 00 00 00 0f 00 00 00 00 00 00 00 00
0000020 00 dc dc 0d da e6 ca 31 02 04 00 0a 00 06 00 04
0000030 00 12 1f 00 01 01 00 00 00 00 08 00 00 00 08 00
0000040 00 00 03 00 00 00 00 00 dc dc 0d da e7 8f 5e 04
0000050 13 05 01 04 00 01 00 00 00 00 0a 00 00 00 0a 00
0000060 00 00 01 00 00 00 00 00 dc dc 0d da e8 7f be 02
0000070 04 20 05 00 01 00 04 00 13 00 00 00 14 00 00 00
0000080 14 00 00 00 00 00 00 00 00 00 dc dc 0d da e9 2d
0000090 e7 02 04 00 0f 00 0b 00 04 00 52 3a 00 27 00 31
00000a0 00 00 00 f4 01 00 00 00 08 00 00 00 08 00 00 00
00000b0 03 00 00 00 00 00 dc dc 0d da e9 6e 9c 04 13 05
00000c0 01 04 00 01 00
00000c5
```
#### 3 Dot Bubble:
```
0000000 62 74 73 6e 6f 6f 70 00 00 00 00 01 00 00 03 ea
0000010 00 00 00 0f 00 00 00 0f 00 00 00 00 00 00 00 00
0000020 00 dc dc 0d dc 7a 13 8b 02 04 00 0a 00 06 00 04
0000030 00 12 1f 00 05 01 00 00 00 00 08 00 00 00 08 00
0000040 00 00 03 00 00 00 00 00 dc dc 0d dc 7a 60 f4 04
0000050 13 05 01 04 00 01 00 00 00 00 0a 00 00 00 0a 00
0000060 00 00 01 00 00 00 00 00 dc dc 0d dc 7b 4f 59 02
0000070 04 20 05 00 01 00 04 00 13 00 00 00 14 00 00 00
0000080 14 00 00 00 00 00 00 00 00 00 dc dc 0d dc 7b f8
0000090 18 02 04 00 0f 00 0b 00 04 00 52 3a 00 27 00 31
00000a0 00 00 00 f4 01 00 00 00 08 00 00 00 08 00 00 00
00000b0 03 00 00 00 00 00 dc dc 0d dc 7c 40 7e 04 13 05
00000c0 01 04 00 01 00 00 00 00 0f 00 00 00 0f 00 00 00
00000d0 01 00 00 00 00 00 dc dc 0d dc 89 57 22 02 04 20
00000e0 0a 00 06 00 04 00 1b 43 00 01 43 00 00 00 00 19
00000f0 00 00 00 19 00 00 00 01 00 00 00 00 00 dc dc 0d
0000100 dc 89 5a b1 02 04 20 14 00 10 00 04 00 1b 46 00
0000110 0c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0000120 0c 00 00 00 0c 00 00 00 00 00 00 00 00 00 dc dc
0000130 0d dc 89 8d 0f 02 04 00 07 00 03 00 04 00 0a 43
0000140 00 00 00 00 08 00 00 00 08 00 00 00 03 00 00 00
0000150 00 00 dc dc 0d dc 8a 47 1b 04 13 05 01 04 00 01
0000160 00 00 00 00 1e 00 00 00 1e 00 00 00 01 00 00 00
0000170 00 00 dc dc 0d dc 8b 33 d6 02 04 20 19 00 15 00
0000180 04 00 0b 0f 43 00 e1 07 02 1c 0b 0f 1b 08 e1 07
0000190 02 1c 0c 06 01 08 64
0000197
```

**Comment by timoc** [comment]
I have an issue open with some tooling that may help reverse engineer the protocol, perhaps you can help discuss a btsnoop plugin?
https://github.com/netzob/netzob/issues/54

**Comment by cpfeiffer** [comment]
The hex dump is not very helpful to us, sorry. If you have a btsnoop, we can have a look at it, though.

**Comment by cpfeiffer** [comment]
I think I do know how to get different notification icons though, so no further dumps needed.

**Comment by yarons** [comment]
Is that good enough? Sorry for the hassle.

[envelope_ico.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/819201/envelope_ico.txt)
[3dotmessage_ico.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/819202/3dotmessage_ico.txt)

**Comment by cpfeiffer** [comment]
These are the easy ones :-) There are further icons, but I haven't understood how to reproduceably display them.

**Comment by yarons** [comment]
Which one of the following are we talking about?
![photo_2017-03-12_01-12-58](https://cloud.githubusercontent.com/assets/406826/23827675/299d5eac-06c1-11e7-8dd7-4d895688432b.jpg)

**Comment by cpfeiffer** [comment]
Never mind, I figured it out, meanwhile.

**Comment by Noiwex** [comment]
that czech company really is salty
