### ISSUE TITLE
Connection and notification issues with zeband and Gadgetbridge 0.17.5

### ISSUE THREAD

**Issue by albertsal** [Freeyourgadget/Gadgetbridge#579]
#### Your issue is:

with the new version will not receive notifications and often the application has trouble connecting

#### Your wearable device is:

zeband v2.44

#### Your android version is:
6.0.1

#### Your Gadgetbridge version is:
 0.17.5

**Comment by jpbarraca** [comment]
What problems exist? Can you enable the development log and post the file?
