### ISSUE TITLE
Connecting multiple devices to a single app

### ISSUE THREAD

**Issue by viggyprabhu** [Freeyourgadget/Gadgetbridge#591]
#### Your issue is:
*In case of a bug, do not forget to attach logs!*

I want to connect multiple MI Bands with a single device. Does GadgetBridge support the same. My interest is to extract data from each of the device to import it into a Google Fit kind of application. 
In case, this requires forking the project with minor modifications, I would willing to do the same. Can someone please guide me on the same.

#### Your wearable device is:
MI Band 2
*Please specify model and firmware version if possible*
FW: v1.0.1.34
HW: V0.1.3.2

#### Your android version is:
5.1.1

#### Your Gadgetbridge version is:
0.17.5

**Comment by cpfeiffer** [comment]
We do not support this yet, but we would be happy if you can add support for that. Please head over to #305 :-)

**Comment by cpfeiffer** [comment]
Or did you mean multiple devices in general, but *not* at the same time? In that case, yes, just add as many as you want.

**Comment by viggyprabhu** [comment]
Thanks for such a quick reply. I meant multiple devices one after the other. Currently MI FIT only supports collecting data from one device per Android phone. As per [this comment](https://github.com/Freeyourgadget/Gadgetbridge/issues/305#issuecomment-219798461), it seems this is possible. Could you just confirm it?

**Comment by cpfeiffer** [comment]
Yes, you can have as many devices as you want. You can only connect one via Bluetooth at the same time, though.
