### ISSUE TITLE
MiBand 2: Firmware Version 1.0.1.39 MD5sum missmatch

### ISSUE THREAD

**Issue by wYhyzByH** [Freeyourgadget/Gadgetbridge#592]
Hello
I was offered today to download the Mi Fit App Version 2.3.0 from Google Play. It included a new firmware file for the miband 2 with md5sum 470641716d9e63115b839cb38eaafce7.
When installing, the GB installer shows firmware 3929.
After installation GB shows the firmware to be version 1.0.1.39.

This differs from what is documented in the [Wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Information). Can you double check, please? My results are persistent.

Regarding functionality everything seems to be fine so far. Steps are counted, activity is recorded and heart rate (live monitor) works as well.
Thanks!

**Comment by wYhyzByH** [comment]
Sorry, my fault. 1.0.1.39 is not documented, but 1.0.0.39 is next to 1.0.1.34, which confused me.
I'll update the tables accordingly, if this is OK for you.

**Comment by cpfeiffer** [comment]
Help improving the documentation is always welcome, thanks!

I also opened #593 because the update experience really needs to improve.
