### ISSUE TITLE
Sleep Time doesn't match real sleep time

### ISSUE THREAD

**Issue by selfus** [Freeyourgadget/Gadgetbridge#594]

**Comment by danielegobbetti** [comment]
There's nothing we can do regarding how good (or bad) the gadgets record our activities. What you could try to do is changing the firmware (see the wiki that contains some observations about the available/tested versions).
I'm closing this issue.

**Comment by selfus** [comment]
I moved from MiFit, the official app, to GadgetBridge, and this is only an issue with the new app, so I think it is not firmware related.

**Comment by rplevka** [comment]
@selfus this has already been discussed in a different issue. looks like MiFit does some additional postprocessing for the actual sleep duration.
I noticed miband stops reporting an activity as sleep at 7 AM almost every time. Gadgetbridge just displays the raw data from the band, as it reported it.

**Comment by selfus** [comment]
Thanks. 
Still would be cool some postprocessing from GB
