### ISSUE TITLE
Characteristic XML

### ISSUE THREAD

**Issue by MarcHeinrich** [Freeyourgadget/Gadgetbridge#596]
#### Your issue is:
I want to add some characteristics into my app but i can't find the GATT XML files where it's written which data i get from each charactersitic

for example for the Mi Band 1 the battery characteristic 0xff0c would get me something like this 
Byte[0] --> level in%
Byte[1-6] --> year (should plus 2000) -month-day-hour-minute-second
Byte[7-8] --> charge times
Byte[9] --> status (1 = Battery low, 2 = Battery charging, 3 = Battery full (charging), 4 = Not charging)

#### Your wearable device is:

Mi Band 1 and 2

#### Your android version is:
4.4

Thanks in advance

**Comment by MarcHeinrich** [comment]
can you pls tell me why is this information not availabel or do i simply not get it?

**Comment by danielegobbetti** [comment]
We don't use XML to store/document which data comes from which Characteristic.If you need this information for other apps you have to either search the code base (e.g [this search](https://github.com/Freeyourgadget/Gadgetbridge/search?utf8=%E2%9C%93&q=UUID) ) or understand how the [code is organized](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Developer-Documentation). 
Further, personally, I find irritating mentioning "my app" without a name / link to its **source** repository. We do everything in the open including writing documentation - as you can see above - and such questions are an unnecessary additional burden (the wiki is there and github allows for quick searches in the source code). Nothing personal but that's the way I see it.

**Comment by MarcHeinrich** [comment]
Thank you for this comment.
I am new to this so i dont know always how to do things right i apologize for that.
As for the XML files i tought i missed something obvious because i saw the bluetooth standard which is in this format so i assumed it would be this way.

Thanks again for your time.
