### ISSUE TITLE
Pebble going into SOS / Recovery mode

### ISSUE THREAD

**Issue by chaseadam** [Freeyourgadget/Gadgetbridge#597]
#### Your issue is:
I have experienced the SOS mode on my Pebble original this a handful of times which requires recovery
http://help.getpebble.com/customer/portal/articles/2002603-sos-screen?b_id=8309
This never occurred with the production app.

When in this mode, GadgetBridge reports the watch as connected and allows me to connect/disconnect

Using the Obsidian Watchface (switched to it when i switched to gadgetbridge).

I get quite a few notifications from K-9 throughout the day.

I did not have HCI snooping on, but have it on now. Logs attached.
[gadgetbridge.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/845558/gadgetbridge.log.txt)

#### Your wearable device is:
Pebble 301WH
FW: v3.8-prf9
HW: v1_5

#### Your android version is:
7.1.1 Copperhead OS on Nexus 5X

#### Your Gadgetbridge version is:
0.17.5

**Comment by danielegobbetti** [comment]
It is likely the watchface (or a watchapp) that is crashing. Three crashes will make the pebble reboot to recovery. 
Can you please try switching back to the same watchface you were using with the official app and see if it helps?

**Comment by chaseadam** [comment]
Will do and report back. I also performed a full factory reset of the watch.

**Comment by danielegobbetti** [comment]
Any news?

**Comment by chaseadam** [comment]
All clear so far, we can probably close this. Might investigate Obsidian code and see what might be crashing, but lower priority than other things such as https://github.com/Freeyourgadget/Gadgetbridge/issues/98
