### ISSUE TITLE
Replicating PebbleKit Android

### ISSUE THREAD

**Issue by C-D-Lewis** [Freeyourgadget/Gadgetbridge#599]
Hi GadgetBridge team,

I develop the popular Dashboard app ([relevant source](https://github.com/C-D-Lewis/dashboard/blob/master/android/DashboardRedux/src/main/AndroidManifest.xml#L82)), that uses the PebbleKit Android Intent action and other Intent services provided locally by the Pebble app to interact with Android apps from Pebble apps, and vice versa. 

I have had a couple of users asking me if I will support GadgetBridge, and I think only more will do so in the next few months/weeks. 

I'm thinking if you guys publish a similar Intent action I can listen to/push to, then I will be able to integrate without too much trouble. Thoughts?

**Comment by danielegobbetti** [comment]
Dashboard works for me without any change. The users are possibly not enabling pebblekit support in gadgetbridge. :-)

**Comment by C-D-Lewis** [comment]
Thanks for the reply, and glad to hear of the transparent support. I will feed this back to the user.
