### ISSUE TITLE
Sleep tracking stats

### ISSUE THREAD

**Issue by doylefermi** [Freeyourgadget/Gadgetbridge#601]
**Issue**
There seems to be a mistake in the sleep time recorded (may be its recorded correctly, but the graph plotted displays wrong values) and few corrections for the sleep page as well.

Sleep stats for Night 16-17 March 2016
![screenshot_2017-03-17-06-44-47](https://cloud.githubusercontent.com/assets/8755940/24025124/93cb568c-0ade-11e7-9e3e-bdc7c54a15cc.png)
It shows Deep Sleep 1hr 29mins and Light Sleep 58mins.
However the stats collected by Mi Fit app seems to be correct as you can see the below screenshot.
![screenshot_2017-03-17-06-45-18](https://cloud.githubusercontent.com/assets/8755940/24025139/ae2051fe-0ade-11e7-911b-e046251cd87e.png)

What does the green color indicate in the graph drawn? Does it indicate activity (if yes, specifying that would be great). Also it shows light sleep after 23:01(zoomed in a lot, its difficult to scroll through that graph because it slides easily to the next page) even though I slept at around 22:45. But that seems to be a very small difference. But its awesome to note that while Mi Fit app didnt track sleep after I slept again for the same day at around 05:45, the Gadgetbridge app shows correct values. But the total time for Deep sleep seems to be wrong when compared to the Light sleep values.

**Device Details**
Wearable Device: Mi Band 2
FW: 1.0.1.39
HW: v0.1.3.2
Android Version: 4.4.4
Gadgetbridge version: 0.18.0

**Comment by danielegobbetti** [comment]
Probably all the "isolated" green bars between the two sleep periods are guessed as sleep time by the official app. Gadgetbridge does not apply any heuristic and shows the data as is.
Your example is good because we do worse than the heuristic during the night but better after 4 am :-)

We are collecting resources and scientific papers in our wiki with the aim of implementing a sensible algorithm, but I'm afraid it will take some time. If you have resources or ideas or algorithms to share, you are very welcome to do so!

**Comment by doylefermi** [comment]
Is this the same in the case of other devices? Mi Band 1 and Pebble?

**Comment by danielegobbetti** [comment]
The data format is different in some cases (e.g. Pebble sends time ranges with an "activity type" attached) but we don't do any post processing in any case at the moment.

**Comment by ashimokawa** [comment]
Pebble does a all postprocessing on the watch so we do not need to do anything. The MI is much simpler and would need postprocessing but that is hidden inside the closed source app.

**Comment by 6arms1leg** [comment]
Just for reference: #442.

**Comment by danielegobbetti** [comment]
True, I'm closing this as duplicate, let's move the discussion over there!
