### ISSUE TITLE
GB crash on Mi Band Settings page

### ISSUE THREAD

**Issue by wYhyzByH** [Freeyourgadget/Gadgetbridge#603]
Hi

I just installed the new Version 0.18. Thank you for the great work done!

But I found two severe issues, that make Gadgetbridge crash reproducably:
1. Going into setting -> Mi Band Settings
2. Selecting  either "Chat" or "Social Networks" (both have the same issue)
3. clicking on "Test" cashes the app.

#### Your wearable device is:
Mi Band 2
FW: 1.0.1.39 + corresponding font packages
HW: v0.1.3.2

My android version is: Android 7.0

My Gadgetbridge version is: 0.18.0

**Comment by cpfeiffer** [comment]
Thanks for the report, it's fixed for 0.18.2.
