### ISSUE TITLE
Weekly graphs show all the same data with 0.18.0

### ISSUE THREAD

**Issue by IzzySoft** [Freeyourgadget/Gadgetbridge#604]
#### Your issue is:
Since the update to 0.18.0, weekly stats show the same data for each day – that is, the data of the actual day for all 7 days:

![weeklysteps](https://cloud.githubusercontent.com/assets/6781438/24072176/1ec64c06-0be3-11e7-8e94-091be8088d1b.jpg) ![weeklysleep](https://cloud.githubusercontent.com/assets/6781438/24072177/2604e19e-0be3-11e7-933f-7fdf3e390885.jpg)

This started with the update to 0.18.0. I've waited one day to see if there might be a re-calculation after retrieving new data, but the issue remained. Yesterday it was the data from yesterday, today it's the data from today.

Note: The weekly stats for steps (which already was available in the previous versions) *did* work correctly before the update.

#### Your wearable device is:

Pebble Time Steel, FW 4.2

#### Your android version is:

CyanogenMod 12.1 (Android 5.1.1)

#### Your Gadgetbridge version is:

v0.18.0

**Comment by IzzySoft** [comment]
Copying over from the duplicate #605 to have the facts in one place:

@6arms1leg has different devices (Mi:Band and HTC phone), so the issue is not restricted to my combination. What we both have in common is running **_CM12.1/Android 5.1.1 with GB 0.18_**. So the issue might be related to the Android version (it works with 7.1.1 as @ashimokawa already checked, so it might be some changes pre-Nougat or pre-MM).

**Comment by 6arms1leg** [comment]
> So the issue might be related to the Android version [...]

A friend (Mi Band 1, Samsung Galaxy S5, Stock OS – 6.0.1) has the same issue. So it's not only CM.

**Comment by ashimokawa** [comment]
Confirmed and fixed. Will be in 0.18.3.
This affected Android 6 and EVEN OLDER versions. :smiling_imp:
