### ISSUE TITLE
Weekly charts display the same value for each day

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#605]
Since the major upgrade to GB version 0.18.0, both weekly charts (sleep and steps) display the same value for each day of the week. This happens on my device (Mi Band 2, HTC one m8, CM 12.1) and a friend's device (Mi Band 1, Samsung Galaxy S5, Stock OS).
Great work by the way, I really enjoy the features of newer GB versions!

**Comment by 6arms1leg** [comment]
Doublicate of #604. Sorry, @IzzySoft was faster.

**Comment by IzzySoft** [comment]
Yeah :) But thanks for confirmation! So:

1. I'm not the only one
1. It's not only the Pebble time steel
1. the clue might be CM12.1 which we both have in common.

As it works for Andreas on Android 7.1.1, it could be a pre-MM thingy. He's just checking that.

**Comment by 6arms1leg** [comment]
> 3. the clue might be CM12.1 which we both have in common.

A friend (Mi Band 1, Samsung Galaxy S5, Stock OS – 6.0.1) has the same issue. So it's not only CM.

**Comment by jonzl** [comment]
I can confirum this issue on a non rooted Android 5.1 device

**Comment by cpfeiffer** [comment]
Please add your comments to #604 only.
