### ISSUE TITLE
unable to install latest gadgetbride with my phone: asus zenfone 2 (asus_zen00ED) with android 6.0.1

### ISSUE THREAD

**Issue by khhoof** [Freeyourgadget/Gadgetbridge#606]
#### Your issue is:
*In case of a bug, do not forget to attach logs!*

#### Your wearable device is:

*Please specify model and firmware version if possible*

**Comment by ashimokawa** [comment]
@khhoof 
A bit more info would be helpful

- Is this a new install or an upgrade?
- Where did you get the version you had before?
- Where did you get the one you are trying to install?

Also a logcat could help (there could be more information about *why* it failed)

**Comment by danielegobbetti** [comment]
closing as "no feedback". Feel free to reopen by providing the requested info.
