### ISSUE TITLE
Discovering device on 7.1.1

### ISSUE THREAD

**Issue by bigretromike** [Freeyourgadget/Gadgetbridge#608]
#### Your issue is:
When using clean (flashed) phone with no other application for band it is impossible to add new device. I can hit discovery many times and it wont show my band. But going to system Bluetooth in android menu and adding device (for first time there) make GB able to see device and parry/auth with it without problems. This isn't critical error but still, for someone that don't know this, it looks like GB isn't capable to discover band or the band is broken

#### Your wearable device is:
Mi Band 1S

#### Your android version is:
LineageOS 14.1 (Android 7.1.1)

#### Your Gadgetbridge version is:
0.18 (f-droid)

**Comment by cpfeiffer** [comment]
Probably a dumb question, but did you enable "location" (e.g. GPS) before starting the discovery? And did you grant the necessary permissions to Gadgetbridge?

**Comment by rplevka** [comment]
I've hit this as well few days ago, after I flashed 7.1.1 ROM. I might have rejected the location access to GB though..

**Comment by bigretromike** [comment]
@cpfeiffer I did not enable location while running it, but I did gave him permission for it.

I'm 100% sure that GB asked for location permission and I grande it, I'm less sure about having turn off location.

**Comment by jpbarraca** [comment]
I also have this problem. With location enabled, I try to discover devices, and for a few milliseconds the spinner appears, but it rapidly disappears and the process stops.

**Comment by cpfeiffer** [comment]
Interesting. Can you provide logfiles? I tried with CM14.1 and had so such problem.

You really need to enable location and give all requested permissions.

**Comment by jpbarraca** [comment]
I found that when I enable the option to write a development log, no log is created.
Attached is the logcat output of all apps during the time it takes to enter the activity and click the add button.
[bt-scan-debug.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/887720/bt-scan-debug.txt)

**Comment by cpfeiffer** [comment]
Sigh. Logging. I've spent too much time on this. We even have a (working) testcase that dynamically toggles logging.

Please try enabling logging. If no logfile is created when you e.g. connect to your device, kill Gadgetbridge and restart it. If you still don't get a logfile then, there's something else broken (plesae provide an adb log, if possible).

**Comment by cpfeiffer** [comment]
But about your current log:

> 04-01 15:28:08.268 1267-1897/? W/BluetoothPlatformImp: in broadcastAllDevicesRemoved, systemui cannot allowed to send broadcast!
> 04-01 15:28:08.271 789-789/? I/SendBroadcastPermission: action:android.bluetooth.device.action.DISAPPEARED, mPermissionType:0

Could it be some kind of permission problem?

**Comment by chaolue** [comment]
@cpfeiffer Firstly huge thank you for this project.

I have a mi band 2 and LineageOS 14.1 (7.1.1) and I had similar issues getting my band connected until... I went to the 'Settings / Location / ... (menu) / Scanning' and turned on 'Bluetooth scanning'

Hope this helps @bigretromike @jpbarraca

**Comment by jpbarraca** [comment]
@chaolue Same behaviour here after enabling bluetooth scanning.
@cpfeiffer All permissions are granted to GB and I can actually see Mi Band or other devices appear. So the scan seems to be working.

This is the behaviour I am seeing:
![7af56da930](https://cloud.githubusercontent.com/assets/497717/24652862/5a7fc5ba-192b-11e7-87a7-f78e816d63f0.gif)

**Comment by cpfeiffer** [comment]
@jpbarraca can you try reverting 1cadb692fe5ce12a9c4a5099ea236ef5e9c39574 and check if this fixes the problem?

**Comment by 6arms1leg** [comment]
I also have this issue on my new phone, but for me it's quite a bit more severe: When I try to add a new device the discovery process immediately and completely freezes my device. In that state, only a soft reset (pressing the power button for ~10s, forcing a reboot) brings the phone back to life.

I tried all above mentioned advices (enabling Location, direct Bluetooth pairing, etc.), but unfortunately none of them help.

I have this issue with: Lenovo Moto Z, LineageOS 14.1 Nightly (Android 7.1.2), Gadgetbridge 0.19.1, Mi Band 2

**Comment by bigretromike** [comment]
Remember that the problem can have it roots in unstable LineageOS build. LineageOS is still Nightly - that could also be the problem when phone freeze just like that.

**Comment by 6arms1leg** [comment]
Sure, but given that others here reported to have a similar issue with the device discovery, there is a good chance that this is related. Additionally, device discovery and pairing works flawlessly with the original Mi Fit app.

**Comment by cpfeiffer** [comment]
Did you try disabling privacy guard for Gadgetbridge? That one is known to cause hangs/reboots during discovery (independent of the CM/LN version).

**Comment by 6arms1leg** [comment]
@cpfeiffer, you made my day! That totally did the trick. After disabling privacy guard for Gadgetbridge it worked perfectly. Many many thanks! I spent hours yesterday, trying all sorts of things to pair the band.
I was about to add this tip to the documentation when I discovered that you even already mention this in the README on the projects main page – oh man ... sorry for the noise! :speak_no_evil: :hear_no_evil: :see_no_evil:

**Comment by cpfeiffer** [comment]
Ah well, sorry that you wasted time with this. The place where this hint needs to go is the discovery screen. Unfortunately there are already so many hints, that there's little space left. Maybe we can just display a link "Not discovered?" that will open a separate dialog displaying the hints.

**Comment by 6arms1leg** [comment]
> Ah well, sorry that you wasted time with this. The place where this hint needs to go is the discovery screen.

@cpfeiffer, no, this *really* is on me. No excuses: This hint actually *is* on the discovery screen, too. I was just too stunned that my new phone froze just like that, that I didn't really noticed the small print at the bottom of the screen.
It was all there. That the hints on the discovery screen aren't very eye-catching might be true though, but IMO there are certainly more important issues ...

> Maybe we can just display a link "Not discovered?" that will open a separate dialog displaying the hints.

While that might make for a cleaner look, it wouldn't be much helpful in the frozen phone scenario, since you can't access the link anymore. IMO, displaying the troubleshooting hints directly (as it is now) is a practical and nice solution.

**Comment by hcgraf** [comment]
Sorry to revive this old issue...
I'm seeing the exactly same issue as in @jpbarraca 's video (Wheel spinning very briefly, button reverts nearly instantly).

Huawei P9 Lite with un-rooted stock-rom, android 7.0.
All permissions granted to GB.

I'm happy to help debugging...

Regards
Hagen

**Comment by bigretromike** [comment]
im fine with results
