### ISSUE TITLE
HPLUS 3BEE

### ISSUE THREAD

**Issue by TomLaw1967** [Freeyourgadget/Gadgetbridge#609]
Hello.
I have an HPLUS 3BEE. On my UMI Plus (Android 7) band when it loses connectivity, I can force it to reconnect. After reconnecting I have a problem that I can not update the data when the band was not connected.
I have another band: MiBand - there are no problems here.
Is there a chance to diagnose why this is happening with HPLUS 3BEE?
Regards
Tomasz

**Comment by cpfeiffer** [comment]
Could you enable logging and provide the logfile so that we have a chance to see what's going oin?

**Comment by jpbarraca** [comment]
Is this a Zeband?

**Comment by TomLaw1967** [comment]
Yeah, this is Zeband

**Comment by jpbarraca** [comment]
As @cpfeiffer said, can you provide a logfile? You can enable this in the preferences.

**Comment by cpfeiffer** [comment]
Closing this since no answer. Please comment or reopen if needed.
