### ISSUE TITLE
Need to sync twice to get all Mi Band 2 activity data

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#611]
To sync all data from my Mi Band 2 I (most of the time) have to sync twice: Atfer the first sync, not all data is received, leaving the last hours in the activity graph empty. Only a second sync process fetches all activity data and fills the graph completely. Do others experience the same issue?
I have a Mi Band 2 with latest FW (v. 1.0.1.39), latest GB on F-Droid (v. 0.18.0) and a HTC One M8 with CM 12.1.

Here is a GB log of the problem (after the first sync completed not all data was fetched, so I synced again to fetch the rest):
[gadgetbridge.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/859822/gadgetbridge.log.txt)
The log looks normal though.

**Comment by cpfeiffer** [comment]
Yes, I noticed this, too! I assume this came in with newer firmware versions. Thanks for the log, will try to fix this.

**Comment by walkjivefly** [comment]
I've been seeing this too with 0.18(.5) and FW 1.0.1.34. I don't think it happened when I was running 0.16.x or 0.17.x.

**Comment by cpfeiffer** [comment]
For some reason I was unable to reproduce this recently. Need to find a pattern when this happens.

**Comment by 6arms1leg** [comment]
Regarding a pattern: I think it only happens when I sync from the main menu and immediately switch to the graph view before the sync process has finished. That way, I don't only need to sync twice, but I can repeat the procedure indefinitely without any data being synced. The data is always synced when I wait for ~2s or more – no need to sync twice then. Can anybody confirm this?

**Comment by ashimokawa** [comment]
Data is synced.
Caching is the problem.
You can kill the charts activity by swiping it away from the android activity list. And then start charts again.

I am aware of the problem and will invalidate caches after syncing

**Comment by cpfeiffer** [comment]
@ashimokawa want to open another issue for the cache invalidation thing?
