### ISSUE TITLE
Smart alarm cannot be disabled if device does not support them

### ISSUE THREAD

**Issue by DocLM** [Freeyourgadget/Gadgetbridge#612]
First alarm for mi band 2 is always a smart alarm and cannot change its type.

Device: Mi Band 2 v1.0.1.39
Android: Nexus 4 with LineageOS 7.1.1
Gadgetbridge: v0.18.0

![screenshot_20170323-161133](https://cloud.githubusercontent.com/assets/2318483/24254814/1ef53318-0fe4-11e7-8c8f-3b5a52f5d03b.png)
![screenshot_20170323-161141](https://cloud.githubusercontent.com/assets/2318483/24254816/1f216df2-0fe4-11e7-994a-2cc1a64e9df1.png)

**Comment by danielegobbetti** [comment]
It's probably due to a change in 0.18. Can you please test if by rotating the device in landscape mode you get to see the controls? They should be to the right of the clock

**Comment by cpfeiffer** [comment]
I think this is just  a visual glitch. We do not support smart alarms for mi2 at all, so the label is just wrong.

**Comment by DocLM** [comment]
@danielegobbetti I tested it but this is the result
![screenshot_20170326-101014](https://cloud.githubusercontent.com/assets/2318483/24330720/177d4970-1225-11e7-9c64-8689e35ec462.png)

**Comment by danielegobbetti** [comment]
I changed the title to reflect the actual bug. It is now fixed on master. The graphic glitch is a widespread android issue. :( (see https://github.com/vikramkakkar/SublimePicker/issues/27#issuecomment-216005832)
