### ISSUE TITLE
Icons for Pebble Notifications

### ISSUE THREAD

**Issue by LeoColomb** [Freeyourgadget/Gadgetbridge#613]
Hi!
I aim to propose a pull request to use a little bit more [icons](https://github.com/Freeyourgadget/Gadgetbridge/blob/e392fbfd800dc326aee2ac49e122a41ab223ab05/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/pebble/PebbleIconID.java) for app notifications on the Pebble.
I just have some concerns about the following comment: [`if you add any more constants, update all clients as well`](https://github.com/Freeyourgadget/Gadgetbridge/blob/e392fbfd800dc326aee2ac49e122a41ab223ab05/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/NotificationType.java#L40).
What does it means exactly? Add all [apps that use the new constant](https://github.com/Freeyourgadget/Gadgetbridge/blob/da9742fd67ebc6328e65f7b7ff6ec47dd7c82e22/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java#L33-L77)? Or update each "gadget" client?

Thx! 🎆

**Comment by cpfeiffer** [comment]
Cool, looking forward to that!

If you add more constants (e.g. for osmand, kontalk, or other notification sources), then you need to make sure that all clients (those classes that reference the constants) also handle the new constants.

There is another gotcha though (see the 'TODO' above the very first constant). The Pebble Icon IDs do not belong to the device independent `NotificationType` enum at all. This was not noticed by code review, I guess.

So, if you're brave enough, you might have a look at removing the Pebble Icon from the `NotificationType`. It belongs into Pebble specific code, somewhere in class `PebbleSupport` or `PebbleProtocol`, I suppose.

**Comment by danielegobbetti** [comment]
Closing this. If you need further information please post here, otherwise: looking forward to the PR! 👍 Thanks
