### ISSUE TITLE
Buttons in device view is to small

### ISSUE THREAD

**Issue by bigretromike** [Freeyourgadget/Gadgetbridge#615]
#### Your issue is:
When trying to click on "Data" my wife has problem. The button is to small end she end up hitting non-clickable arena and get message about "hold long to disconnect". Shes trying her best, but somehow those buttons are to small and the nails don't help with them ;-). Could those get a little bigger ?

**Comment by danielegobbetti** [comment]
Wow can you please tell the phone model (and a screenshot, please). I find the buttons quite large already but I'm on a small device :-)

**Comment by ashimokawa** [comment]
On my 4.3" s4 mini running lineage 14.1 I press these buttons confidentially with my thumb 🤔

**Comment by bigretromike** [comment]
![screenshot_20170325-173545](https://cloud.githubusercontent.com/assets/6052025/24324173/aafee342-1181-11e7-9ba1-2da14ac97510.png)

There is plenty of space there :-) they could scale or something.

To be honest, now I missed it also. 

ps: also I found out that auto-reconnect is not working :-) maybe it have intervals to try to connect. But that is another issue.

**Comment by danielegobbetti** [comment]
Are you sure that you did not change the screen density (dpi) on your phone? According to the specs it should have the same resolution and screen size of the Nexus 5X (hence the same density) but the icons there are a bit bigger according to the emulator.

**Comment by danielegobbetti** [comment]
Looking better at your screenshot, it seems to me that the action icons are the same size of the back/home/recent symbols in the bottom (system wide) bar, so I don't think there's nothing wrong in our implementation.

**Comment by bigretromike** [comment]
imo, the "bar" icon could gain additional 1 bar more, and that would probably fix our issue, or make it the last button so there is 50% less chance to miss click. 
But that is mine (and my wife) opinion. Please close if this is no-go. 

Btw, system bar icons have BIG hit box, which make them easier to hit, so you dont have to target the image of the icon directly.

**Comment by danielegobbetti** [comment]
Good point about the "hit box", I removed some pixels from each icon margin and added some padding instead. This should make the "hit box" bigger without enlarging the icons, which would be a problem on smaller string. Next release (0.18.4) will contain the fix. With this change I consider the issue closed, but please reopen it if you have better ideas.

**Comment by bigretromike** [comment]
Thanks you very much for not ignoring the issue.

**Comment by bigretromike** [comment]
Thanks for update, definitely now its far better !

**Comment by danielegobbetti** [comment]
Thanks for confirming that the fix helps :)
