### ISSUE TITLE
Logging works but produces an additional empty *.zip file

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#617]
Logging in GB works, but since a few versions back (not sure when it started), when logging is turned on, an additional empty *.zip file is created next to the correct *.log file. Not really important, but still a bug. Anyone else experiencing this issue?

In case, you want to investigate, here is an example of the two log files (one correct *.log + the empty *.zip) created for #611:
[gadgetbridge.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/870133/gadgetbridge.log.txt)
[gadgetbridge-2017-03-18.0.log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/870134/gadgetbridge-2017-03-18.0.log.zip)

I'm using GB 0.18.0 with a Mi Band 2 on CM 12.1
Feel free to close this issue, as it's really not that important.

**Comment by cpfeiffer** [comment]
This is due to log rotation. It really shouldn't create an empty zip, but OTOH, we indeed have more important issues, so since you agree with me, I'll close this.

I'm happy that dynamically toggling logging works at all (cost me many hairs).
