### ISSUE TITLE
Exported DB file does not have any data of the MI Band2 steps or sleep activities

### ISSUE THREAD

**Issue by viggyprabhu** [Freeyourgadget/Gadgetbridge#623]
I exported the DB and opened the sqlite file using Sqlite Browser on my Ubuntu laptop. I see data about the MI Band settings, user data etc. However, I dont see any table about MI Band steps activity or sleep hours, etc. Isnt this data also exported from DB. I need to access this data. 

#### Your wearable device is:
MI Band 2
*Please specify model and firmware version if possible*
FW: v1.0.1.34
HW: V0.1.3.2

#### Your android version is:
5.1.1

#### Your Gadgetbridge version is:
0.17.5

**Comment by danielegobbetti** [comment]
Do you see something on the graphs within the app?

**Comment by viggyprabhu** [comment]
Yes, app works fine and I can see all the data.

**Comment by danielegobbetti** [comment]
Then I'm wondering if the export you access is the one that gets updated or not (because of the issue you reported in #622). Graphs are drawn from database data so they must be there.

**Comment by viggyprabhu** [comment]
Thanks for such quick responses. Is there someway, I can try to debug this issue on my phone. I have just uploaded the sqlite db file [here](http://viggy.in/Downloads/Gadgetbridge.db) which was exported, in case you want to look at it.

**Comment by viggyprabhu** [comment]
Sorry to say that it was my mistake. I was trying to look at the sqlite database using sqlitebrowser but now when I tried to run it using sqlite3 command line, it is displaying all the data in the MI_BAND_ACTIVITY_SAMPLE table. Please mark this as not a bug. Extremely sorry for not having tried it more extensively before filing a bug.
