### ISSUE TITLE
Unable to activate Pebble Health.

### ISSUE THREAD

**Issue by ShapeShifter499** [Freeyourgadget/Gadgetbridge#624]
I factory restored my Pebble Time and used Gadgetbridge to flash the latest firmware in order to get out of "Factory Mode". My Pebble is constantly displaying the following message whenever I try to get steps or sleep data.  

```
This app requires Pebble Health to work. Enable Health in the Pebble mobile app to continue.
```

Shouldn't Gadgetbridge be emulating the Pebble Health service including initialization? 

#### Your issue is:
Unable to activate Pebble Health.

#### Your wearable device is:
Pebble Time
Firmware v4.3

#### Your android version is:
LineageOS 14.1

#### Your Gadgetbridge version is:
V0.18.3

**Comment by danielegobbetti** [comment]
You have to go to app management and activate health.
And please read the wiki before opening issues, as this is very well documented.

**Comment by IzzySoft** [comment]
The [corresponding section in our Wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-System-Apps#health-not-for-pebble-classic-and-steel) was even updated last night :innocent:

> To activate the Health app, open the „Application Manager“ in Gadgetbridge (second icon in the first screenshot below), long-press the „Health“ entry, and select „Activate“.

**Comment by ShapeShifter499** [comment]
Uh my apologies, I was long holding the app just to see if that triggered any settings even before reading the wiki and it was just allowing me to reorder it. Maybe I was twitching my finger or whatnot.  It's working now.
