### ISSUE TITLE
Zeband doesn't show sleep

### ISSUE THREAD

**Issue by girlwithnoname** [Freeyourgadget/Gadgetbridge#625]
#### Your issue is:
I'm just testing GB with Zeband. All works fine but sleep isn't displayed, neither in the activity chart nor in the sleep charts. Is this a known issue?

#### Your wearable device is:

Zeband
Firmware 2.4.1

#### Your android version is:

Lineageos, 7.1.1

#### Your Gadgetbridge version is:
18.3

**Comment by jpbarraca** [comment]
Can you provide a log file so that we can debug the issue?

**Comment by danielegobbetti** [comment]
@jpbarraca could 11b48e7a1a7e14e245340e620679fe6ac4f19482 be the solution? It wasn't part of 0.18.3

**Comment by girlwithnoname** [comment]
I built it from source and it didn't work. I'll try to provide a log at the weekend, since I don't think I'll find the time before then.

**Comment by jpbarraca** [comment]
@danielegobbetti That patch will make the sleep periods visible in the activity chart. However, the sleep totals per day were always available in the other panels.

**Comment by girlwithnoname** [comment]
For now please ignore this. I'll test it with a second phone on the weekend, since I noticed that the problem might be outside from GB. I'll report back.

**Comment by girlwithnoname** [comment]
Well, it looks like the band is faulty. Sorry for that.
