### ISSUE TITLE
Request for device: razer nabu (x?)

### ISSUE THREAD

**Issue by thypon** [Freeyourgadget/Gadgetbridge#626]
No one reversed the protocol yet.

**Comment by danielegobbetti** [comment]
Please check:

https://github.com/Freeyourgadget/Gadgetbridge/wiki/Support-for-a-new-Device

I'm closing this, feel free to reopen once the needed information is available.

**Comment by thypon** [comment]
I'll cite the document you linked me:

_When requesting support for a new device, please add the label "request for device" to it. If you found documentation or even a specification about the protocol, please reference it. Such documentation very much increases the probability of supporting the device in question with Gadgetbridge._

- [X] Request for device (in the issue title)
- [X] Check for documentation and cite (there is no known spec for the protocol)
