### ISSUE TITLE
Pebble automatic reconnection

### ISSUE THREAD

**Issue by gianlucapir** [Freeyourgadget/Gadgetbridge#627]
Hello parts before all I wanted to thank you for the great work you do I, used already for some time Gadgetbridge, and is a fantastic application.
I wanted to ask the infinite option on the "reconnection attempts" because I happen to leave the phone away from the watch for more than an hour and the reconnection does not happen automatically every time I have to remember to make the connection manually.
I already set up the voice of 9999
I have a Galaxy S7 with Nougat and Pebble time stell.
Thank you.

Salve, inanzi tutto volevo ringraziarvi per il gran lavoro che fate ho, utilizzo già da diverso tempo Gadgetbridge, ed è un applicazione fantastica.
Volevo chiedere l'opzione infinito sulla voce "tentativi di riconnessione", perchè mi capita di lasciare il telefono lontano dall'orologio per più di un ora e la riconessione non avviene in automatico ogni volta mi devo ricordare di effettuare la connessione manualmente. 
Ho già impostato la voce su 9999
io ho un Galaxy S7 con Nougat e un Pebble time stell.
Grazie.

**Comment by IzzySoft** [comment]
This seems a frequently reappearing issue. Related: #186 #200 #296 ( #432 ). Can you please check with those issues and see if one of them gives you a helpful pointer?

Sidenote: I experience the very same with my Pebble Time Steel. Bluetooth on my Android device is turned of overnight and switched back on in the morning automatically, usually with the Pebble being ~5m away. Sometimes the reconnect happens automatically, other days not. Sometimes as soon as I bring both devices near to each other (or a few minutes later), sometimes even while being apart. Works more often if they come together within the first 60min of BT being switched on, but even that is no guarantee.

Usually, if it doesn't happen automatically, toggling BT off and on again does the job. There was only 1 time within the past year that I had to toggle twice.
