### ISSUE TITLE
"Sleep a week" charts have no legend

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#632]
The newly introduced "Sleep a week" charts are a great feature, but they are missing a legend. For the similar "Steps a week" charts this wasn't necessary because they displayed only one item.
Maybe you could just add the same labeling used in the "Your sleep" pie chart? :pray: 
Thanks a lot for your consideration!

**Comment by IzzySoft** [comment]
While on it: I'm curious what the gray segment in the circle on top of the "weekly bars" is supposed to represent :stuck_out_tongue:

**Comment by ashimokawa** [comment]
I am aware of the issue and I want to fix it before the next release.

The gray area is the lack of sleep. If your goal is 8h but you only slept 4 you will see half of the circle in gray.

**Comment by IzzySoft** [comment]
And I take it the circle reflects the average of the week displayed?

**Comment by ashimokawa** [comment]
Last day 12:00 to current day 12:00

**Comment by ashimokawa** [comment]
Fixed in master, I also removed the gray segment from the pie chart to avoid confusion.

**Comment by IzzySoft** [comment]
> I also removed the gray segment from the pie chart to avoid confusion.

Oops. Good that you mention it. I just wanted to update the Wiki. Besides, I see no harm in that gray segment, just the opposite: good to know if one has a „sleep deficit“ – daily as well as weekly based. As soon as there's a legend present, I neither see how that could confuse anyone (exxcept maybe illiterates or those suddenly having their language switched to e.g. Chinese, that is).
