### ISSUE TITLE
Mi band 1a disconnect and unpair

### ISSUE THREAD

**Issue by dvdobrovolskiy** [Freeyourgadget/Gadgetbridge#633]
Mi band 1a
FW 5.16.4.22

Disconnect then app in background. From time to time mi band start asking for pairing again with light and vibration. If I confirm pairing by touching band it pairs but still app show disconnected band

(reconnect automatically is on)

**Comment by cpfeiffer** [comment]
I'm pretty that Gadgetbridge is not the reason for the pairing requests, but if you provide a log file, we can find out.

Disconnecting Gadgetbridge means "don't do anything with the device". We never try to talk to the device before the user manually connects again.

**Comment by cpfeiffer** [comment]
No feedback, closing.
