### ISSUE TITLE
Downloading data from main menu prevent graph from being refreshed

### ISSUE THREAD

**Issue by bigretromike** [Freeyourgadget/Gadgetbridge#634]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
When leaving data on device (to make it download longer) and hiting refresh button on main window, then entering into graphs by button and looking at "Your Activity and Sleep" when data finish to download the graph isin't updated, it get update only when I hit "refresh" - but then "Refresh" download that data once again so i end up waiting twice the time (initial download, and second after "refresh")

#### Your wearable device is:
Mi Band 1S

#### Your android version is:
LineageOS14.1 (Android 7.1.1)

#### Your Gadgetbridge version is:
0.18.4

**Comment by danielegobbetti** [comment]
I suspect this and #611 are related

**Comment by bigretromike** [comment]
I can confirm that this is fix now (as in 0.19.1)
