### ISSUE TITLE
Pebble Time Round - pbz is broken

### ISSUE THREAD

**Issue by mhoelzle** [Freeyourgadget/Gadgetbridge#635]
Unable to install firmware, pebble still in 'pebble.com/app'-screen.

Firmware selected:
https://pebblefw.s3.amazonaws.com/pebble/spalding/release-v3.8/pbz/Pebble-4.3-spalding.pbz

Start with Total Commander -> Open with -> FW/App Installer
Start with 'Files' -> FW/App Installer
Select File in 'App Manager'

Android 7.1.1 / LineageOS 14.1-20170306
Pebble Round FW v3.2-prf5 / HW: spalding
Gadgetbridge 0.17.5 (from F-Droid)

pbw/pbz is broken or incompatible with your Hardware or Firmware.

**Comment by ashimokawa** [comment]
This is fixed since Gadgetbridge 0.18.1 (see CHANGELOG.md)
Is there a reason why you are using 0.17.5 instead of 0.18.4?

**Comment by mhoelzle** [comment]
0.17.5 is the current version in F-Droid, that is the reason.

**Comment by mhoelzle** [comment]
Sorry, error in F-Droid. After reinstall I see 0.18.4. Will try with the new version. Thanks for your quick response.
