### ISSUE TITLE
Awareness of Notification Center for Pebble

### ISSUE THREAD

**Issue by ywum7fhv0skqh07h** [Freeyourgadget/Gadgetbridge#649]
#### Issue
I was having trouble getting any third party applications to send through notifications to my Pebble (OG) (Notification access was enabled, Third party notifications enabled in app, experimental PebbleKit enabled. I was receiving SMS).

I remembered that I used to use an app called Notification Center for Pebble which is a free software notification overhaul for the pebble. It has stacks of options and functionality, including support for the nonfree app "tasker". I was wondering if Gadgetbridge was aware of this project and whether there would be benefit in porting some features over, links are below. Note that I do not run Google Play Services and Gadgetbridge is installed through F-Droid. Notification Center for Pebble was installed via [Yalp Store](https://github.com/yeriomin/YalpStore) which alerted me that Google Play Services are used by the app, the nature of which I do not know.

Notification Center for Pebble:
[Source Code (GPLv3)](https://github.com/matejdro/PebbleNotificationCenter-Android).
[Documentation](https://docs.google.com/document/d/1P6OUhs91ESYrHAC-O5Axz81HSTFuNjQei-4URxmcSIA/pub).
[Google Play Store](https://play.google.com/store/apps/details?id=com.matejdro.pebblenotificationcenter).

#### My hardware and software
* Pebble OG, firmware 3.12.3

#### Your android version is:
* Lineage OS 14.1 (Android 7.1.1), 20170323-NIGHTLY-peregrine
* Gadgetbridge 0.18.4 (F-Droid).

**Comment by danielegobbetti** [comment]
I'm not sure I understand your proposal, would you like to have some features that are part of "Notification Center" ported to Gadgetbridge (if so, which ones?) or are there some funcitonalities that are not working when using "Notification Center" with Gadgetbridge instead of the official app?

**Comment by cpfeiffer** [comment]
Closing due to lack of feedback. Feel free to comment or reopen, though.
