### ISSUE TITLE
Pebble: Installation fails if app/watchface is already installed on the pebble(no way to update without deleting app before)

### ISSUE THREAD

**Issue by ashimokawa** [Freeyourgadget/Gadgetbridge#65]
We could solve this by either
1) always deleting the app by its uuid before installing it
2) check if it is possible to install the same (updated) app in the same slot as the old version was installed to

**Comment by xphnx** [comment]
Probably not related, but I have same issue recently with my app https://gitlab.com/fdroid/fdroiddata/merge_requests/805

**Comment by ashimokawa** [comment]
@xphnx 
No this is not related, this bug is about installing a Pebble app or watchface.

**Comment by ashimokawa** [comment]
Tried to install the same (updated) app in the same slot as the old version was installed to.
Did not work :(
