### ISSUE TITLE
Sleep not detected correctly

### ISSUE THREAD

**Issue by RyuzakiKK** [Freeyourgadget/Gadgetbridge#650]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
Sleep is not detected at all by GB, but installing the Mi fit app it is correctly recorded.
I also tried enabling the heart rate to improve sleep.

![screenshot_20170412-094420](https://cloud.githubusercontent.com/assets/3227973/24947327/ae08dc1c-1f66-11e7-9b7b-7decf4a15de8.png)
![screenshot_20170412-094452](https://cloud.githubusercontent.com/assets/3227973/24947329/b145a496-1f66-11e7-85c4-67ff35b03ec9.png)

#### Your wearable device is:

Mi Band 2, fw V1.0.1.47

#### Your android version is:

Android 7.1.1

#### Your Gadgetbridge version is:

0.18.4

**Comment by danielegobbetti** [comment]
Just to be absolutely sure that this is not a visual glitch, if you swipe to the right to go the sleep chart what does the pie chart on the top half of the screen show?

**Comment by cpfeiffer** [comment]
Another question: do you run Gadgetbridge and Mi Fit concurrently? Maybe Mi Fit changes the activity type after analysis and Gadgetbridge does not recognize that as sleep? Could you share a log file, or an excerpt of a synchronization with Gadgetbridge?

**Comment by RyuzakiKK** [comment]
@danielegobbetti it is not a visual glitch, also the sleep screen is at 0 min.

@cpfeiffer I did not run them concurrently. I received my mi band few days ago, and after a fw upgrade with the mi fit app, I removed the band from the app and uninstalled mi fit.
Then I installed only GB.

Then three consecutive nights passed without sleep recorded, so I installed again the Mi fit app to check if the problem was GB or my band.
So only now I have both installed, but the problem was there ever before.

This is a log of few minutes ago, if you need the one with the sleep data sync I can provide it tomorrow.
https://ptpb.pw/GUus

**Comment by cpfeiffer** [comment]
@RyuzakiKK Yeah, we would need a log that contains sleep data. I didn't try firmware 1.0.1.47 yet, so that might also be a reason.

**Comment by RyuzakiKK** [comment]
ok, tomorrow I'll upload it (first I need to sleep :D )

**Comment by RyuzakiKK** [comment]
This is the sleep sync log.
[gadgetbridge sleep.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/918748/gadgetbridge.sleep.zip)

**Comment by userxtool** [comment]
Same issue here. With 1.0.1.3.9 sleep is tracked. With 1.0.1.4.7 not.

**Comment by userxtool** [comment]
Gadetbridge 0.18.4   Android 6.01

**Comment by Vebryn** [comment]
Have you notice other broken functionalities ?

**Comment by cpfeiffer** [comment]
@userxtool thanks for confirming this. We'll have a look at how to deal with this unless this will be fixed in another firmware update.

In the meantime, I suggest not using firmware 1.0.1.47.

**Comment by Jojonintendo** [comment]
I have the same problem, even with latest 1.0.1.50. Tomorrow I will provide sleep logs.

**Comment by Jojonintendo** [comment]
OK, now I provide a btsnoop and a GB log, because I didn't know which would be useful.

[report.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/983323/report.zip)

**Comment by userxtool** [comment]
Hi @all tested firmware 1.0.1.50 same issue with sleep tracking. Back to 1.0.1.39 sleep tracking ok.

Android 6.01
Gadetbridge 0.19.1

**Comment by cpfeiffer** [comment]
Thanks for the logs! It looks like they provide completely different values now:
```
0x50
0x59
0x5a
0x60
0x01
0x70
0x7a
0x7b
```
The most prominent of them are `0x50` and `0x70`, so these are proably light and deep sleep. To prove this, it would be helpful to have a complete log for a sleep and the corresponding values that Mi Fit shows. Otherwise I will just guess :-)

**Comment by Jojonintendo** [comment]
I just tried installing Mi Fit to see the sleep chart from tonight, and somehow it just removed the sleep data. Even GB can't get it, there is a blank space where sleep data should be.

I will test again tomorrow ^^'

**Comment by Vebryn** [comment]
Did you read #232 ? It talks about sleep calculation.

**Comment by Roxxor91** [comment]
Great that the issues are back up!
So here comes the data(Syncing in the morning with MiFit after sleeping):
[sync_sleep_with_mifit.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/1146890/sync_sleep_with_mifit.log.txt)
In Bed for: 5h40min
Deep sleep 1h01min
Light sleep: 4h39min
Fell asleep: 00:32
Woke up: 06:14
Time awake: 2min

**Comment by al1b** [comment]
I have the same problem, sleep data are not available at all.

**Comment by Vebryn** [comment]
MiBand associates an id on recognized activities. A lot of ids has changed in 1.0.1.50 version. An issue is open with new association: #686

**Comment by Roxxor91** [comment]
Actually the bug reports are kind of duplicates. This bug here is included in 686. Some mod should close this actually.

**Comment by cpfeiffer** [comment]
Alright, closing in favor of #686
