### ISSUE TITLE
HPlus (Zeband): Telegram notifications

### ISSUE THREAD

**Issue by anawim** [Freeyourgadget/Gadgetbridge#656]
Totally newbie so I'm not sure if it's just me or there's no way to receive notifications for Telegram messages and calls with Gadgetbridge on Zeband?

**Comment by jpbarraca** [comment]
If telegram displays an Android notification, GadgetBridge should catch it.

**Comment by anawim** [comment]
Uhm, I'm asking because phone gets notifications but Zeband doesn't, not even sure what should happen on the band: vibration, Telegram icon displayed, Telegram message displayed?

**Comment by jpbarraca** [comment]
If the notification text is displayed in Android and GadgetBridge is configured to show generic notifications, you should see a message icon and then the text. The Zeband will vibrate twice (icon and text).

If you see no Android notification or if GadgetBridge is not configured to display generic messages, nothing will happen.

**Comment by cpfeiffer** [comment]
You can use the Debug screen to test notifications. Make sure that "Also when screen is on" is checked in the preferences.  If it really doesn't work, please post a log file (see the wiki how to create it).

**Comment by danielegobbetti** [comment]
Closed this as no feedback, please reopen if needed.

**Comment by anawim** [comment]
It took me some time as the Zeband is not on my wrist. The problem is the erratic behaviour: notifications don't arrive on the Zeband because it's frequently disconnected from the app and there is no way to reconnect but reboot. Also there is a problem with old notifications that are sent again until they are not read on the device.

**Comment by jpbarraca** [comment]
This should be fixed in version 0.19.1

**Comment by anawim** [comment]
You mean disconnections or repeated notifications or both?

**Comment by jpbarraca** [comment]
Before version 0.19.1 the connectivity with HPlus devices was not that good. It became even worst after version 0.18.3-4 and this was fixed in version 0.19.1. Currently, as far as I can test, the connectivity is very very good (small number of disconnections and automatic reconnection is working). This can potentially fix any repeated notification issue that you might be experiencing.
