### ISSUE TITLE
Mi Band 2 firmware 1.0.1.47

### ISSUE THREAD

**Issue by Vebryn** [Freeyourgadget/Gadgetbridge#658]
Hello,

I just received my Mi Band 2. I upgrade its old 1.0.0.39 firmware into 1.0.0.53. When I tried to upgrade into 1.0.1.47 version, GB told me that this version isn't whitelisted.

New version was added 12 days ago on [(https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Update)].

Have anyone tested this version ? Any issue ?

#### Your Gadgetbridge version is: 0.18.5

**Comment by Vebryn** [comment]
#650 sleep detection seems broken

**Comment by cpfeiffer** [comment]
I'll close this one in favor of #650. Please add further information to the wiki page at https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Information.
