### ISSUE TITLE
Mi Band 2 alarms explanations

### ISSUE THREAD

**Issue by Vebryn** [Freeyourgadget/Gadgetbridge#659]
Hello,

I reserve 1 alarm to notifications. I'm able to set 2 manual alarms. I set first one to 10AM. My device rang properly at 10AM. I touch its button to stop it. 10 minutes later, device rang again. I touch button again, it stops again. 10 minutes later, same behaviour. I finished by starting GB to disable alarm.

Is touching button only a snooze ? How to disable an alarm after it rang ?

I'v read about Smart Alarm. Is this a smart alarm ?

Best regards.

**Comment by walkjivefly** [comment]
In my experience touching the button only snoozes the alarm. It will keep ringing every 10 minutes for up to 1 hour. How many times it will snooze seems to be random to me. I haven't worked out if there is a particular touch pattern which silences the alarm versus simply snoozes it. If anyone has a definitive answer to this I'd like to hear it too.

Smart alarms are supposed to fire at a point in your sleep cycle close to the desired alarm time which will cause the least amount of stress as you wake. AFAIK this is a function of the device firmware and in my experience it does nothing; the alarm simply fires at the programmed time.

**Comment by Vebryn** [comment]
It's not really practical! According many forums, alarms stop when device detects movement. I'm going to check this tomorow morning.

**Comment by cpfeiffer** [comment]
In any case this is a feature (or bug) of the Mi Band 2 firmware. I think this used to happen with earlier firmware versions, but not with the current recommended version in our wiki.

**Comment by Vebryn** [comment]
Indeed, movement disables current alarm.

Smart alarms have been removed from Mi Fit application : http://en.miui.com/thread-267378-1-1.html

**Comment by ioangogo** [comment]
To silence the alarm you hold the button down and 3 dashes will progressivly show on the screen, it will then show a crossed out clock when the alarm has been silenced

**Comment by walkjivefly** [comment]
@ioangogo which FW version is that with? I'm still running 1.0.1.34 and your suggestion doesn't work there. If I really want to shut an alarm up I cancel it from GB.

**Comment by mueller-ma** [comment]
@ioangogo @walkjivefly I have 1.0.1.50 and it works
