### ISSUE TITLE
Can't initialize pebble time steel after factory reset

### ISSUE THREAD

**Issue by hugochinchilla** [Freeyourgadget/Gadgetbridge#665]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
After performing a factory reset i'm stuck at the pebble's recovery screen.

If I long-press enter button  I get this text on screen under the image: `v3.0.3-prf` 

Tried to follow steps described the wiki guide: **[Getting Started](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Getting-Started)**

The device is paired, if I tap on the device in gadget's bridge app it says `Connecting` and goes back to `Disconnected`.

#### Your wearable device is:

Pebble Time Round after factory reset, no firmware.
Last firmware used was `4.3`
`v3.0.3-prf` on recovery screen after long-press on central button

#### Your android version is:

6.0.1

#### Your Gadgetbridge version is:

Custom build from `feature-calendar-sync`

**Comment by ashimokawa** [comment]
Have you enabled "always prefer ble"? If so, please turn it off 
You can also try to forget the pairing in android BT settings and then do the pairing again from there - then connect from Gadgetbridge.

I think it is normal that you have to repair in recovery but I am not sure.

**Comment by danielegobbetti** [comment]
Closing for lack of feedback, please reopen if necessary
