### ISSUE TITLE
Zeband swim activity

### ISSUE THREAD

**Issue by anawim** [Freeyourgadget/Gadgetbridge#669]
am I missing something or there is really no support for swim in GadgetBridge?

**Comment by jpbarraca** [comment]
I have no idea how to get that information. Sorry.
Never saw a message reporting Swim activity.

**Comment by anawim** [comment]
Do you mean the data is just presented on the Zeband screen and never passed to the phone?

**Comment by jpbarraca** [comment]
AFAIK, that is correct.

**Comment by anawim** [comment]
First of all a question: does the swimming activity appear in your app in form of steps?
OK it's possible no message is sent form swim data even if it's weird, but still if you know the algorithm (based on answer from first question it could be reversed engineered) they use to compute strokes and calories and get just the start and end time we could get the data displayed DURING swim on the band AND history AFTER on the phone

**Comment by jpbarraca** [comment]
As far as I could test Swimming activity is not sent to the App, even if in the form of steps.
Just tested and the Step count seems to remain constant when swimming mode is on.
No other message was sent by the zeband.
