### ISSUE TITLE
Notifications on watch in chinese

### ISSUE THREAD

**Issue by 1140921** [Freeyourgadget/Gadgetbridge#670]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
Notifications in device appear to be in Chinese application in English language

#### Your wearable device is:
Zeband z plus

*Please specify model and firmware version if possible*

#### Your android version is:
5.0.2

#### Your Gadgetbridge version is:

0.18.5

**Comment by danielegobbetti** [comment]
Duplicate #630
