### ISSUE TITLE
Connection problems with Pebble classic and BLE

### ISSUE THREAD

**Issue by tecufanujacu** [Freeyourgadget/Gadgetbridge#677]
Pebble classic with Android 6 and Gadgedbridge 0.19.1, I'm able to connect it via BLE but only the first time, after this the pebble isn't more able to connect to the phone the further times.

After a reboot of the phone I noticed that in Gadgedbridge I have this:
![gb](https://cloud.githubusercontent.com/assets/17774082/25728947/6a9b3cda-3132-11e7-8a59-a49d840db855.jpg)

Is this normal?

**Comment by ashimokawa** [comment]
I will disable BLE for classic

Cant fix that
