### ISSUE TITLE
'Select all' in notification customisation list

### ISSUE THREAD

**Issue by p-friedrich** [Freeyourgadget/Gadgetbridge#679]
I have lots of apps that can send notifications, but want only a few of these on my watch. A 'Select all' function in the notification customisation list would make it easier to block all apps and allow a few afterwards. An alternative to that would be a whitelist approach (#366). Currently I have to select all apps manually, which takes considerable effort.

**Comment by danielegobbetti** [comment]
I checked the material design specs and I did not found a mention of a "select all" interaction.
My idea would be to add a (fictional) element at the top of the list that toggles all the checkboxes. The problems I see are:
- performances (in case of huuuuge app lists)
- what should happen when this element is selected and some app are checked: should it toggle the selection? Just always select everything?

**Comment by p-friedrich** [comment]
Thanks for your considerations. Maybe the option to change from a blacklist to a whitelist for all the notifications would be clearer? I assume this would be more work.
