### ISSUE TITLE
Please integrate "Push to Pebble"

### ISSUE THREAD

**Issue by admiralzeech** [Freeyourgadget/Gadgetbridge#688]
Hi, thanks for developing Gadgetbridge!

I must say, the "killer app" for me on my Pebble watch is the app "Push to Pebble", which allows you to use the Android share functionality to send any arbitrary text to your watch as a notification.

It's so useful for shopping lists, information when doing repairs at work, etc.

Sadly the app was some sort of tech demo and isn't being maintained anymore, and only works with the original legacy Pebble App.

The source code is here:
https://github.com/MohammadAG/Push-to-Pebble

I notice Gadgetbridge​already has an entry in the share menu, for installing apps/firmware.

I would be extremely grateful if you could add another share entry for sending an item as a notification, just like Push to Pebble.

Thanks!

**Comment by danielegobbetti** [comment]
Please try to enable "Untested functionalities " in Gadgetbridge Pebble settings and restart Gadgetbridge. I see no reason why this app shouldn't work with current Gadgetbridge *if* that option is enabled.

**Comment by admiralzeech** [comment]
Thanks for your reply. Didn't seem to work. Here is what I did:

* Install Push to Pebble.
* Enable Untested Features
* Select Quit from GB menu and launch again.
* Go to Google Keep and send an item via Push to Pebble.
* Nothing happens. No error message either.

* Turned on log files
* Restart GB
* Tried Push to Pebble again.
* Nothing happens. Went to log file location in Android/Data etc, but no log file there. Only .Watch files and a watch screenshot I made.

* Tried receiving a test message from hangouts. 
* Watch did not respond.
* Noticed the "also when screen is on" setting, turned it on 
* Another test message in hangouts. Watch correctly displays notification now.

* Tried Push to Pebble again. Still nothing.
* Checked for log file. No log file.

I'm using v.0.19.1 from fdroid. I notice there's a new version released today, should I try it?

Is there any other debugging I can do?


I still hope you will agree to integrate this functionality. Push to Pebble is abandoned and I don't even know if it's available on the store anymore - it doesn't come up in searches, I had to reinstall from my app history. It's a simple but really useful feature.

**Comment by admiralzeech** [comment]
I installed the latest version and I get log files now. Push to Pebble still doesn't work though.

I couldn't see anything obviously relevant to Push to Pebble when browsing the log. Let me know if you want me to cut paste the log contents or upload the file somewhere for you.

**Comment by ashimokawa** [comment]
Did you enable 3rd party app access?

**Comment by admiralzeech** [comment]
I had not, in the tests above. I just tried it now and restarted GB. Push to Pebble still doesnt do anything.

**Comment by admiralzeech** [comment]
I mentioned it in my original post, but I should clarify.

In the past, when they switched everyone to the new Pebble Time app, Push to Pebble stopped working. I had to leave the original Pebble app installed (but not connected) to make it work.

So maybe there is something in the Push to Pebble code that is specifically targeting the original Pebble app?

**Comment by ashimokawa** [comment]
@admiralzeech 
Not directy, but indirectly.
The App you mentioned is build with a very old version of PebbleKit which is unsupported.
It would be relatively easy to just rebuild it with a later version.

Anyway I will have a brief look why this fails exactly.

**Comment by admiralzeech** [comment]
Thanks. If it's convenient for you and easy to do, could you please compile the app such that it works again, and upload to fdroid for preservation?

**Comment by ashimokawa** [comment]
@admiralzeech 
I think it should actually work if you set "pebble notifications" in settings to "always".
The problem seems to be that notifications wont be forwarded when the screen is on.

Please try that and report back.

**Comment by admiralzeech** [comment]
It works! Thank you.

I went back and turned off "3rd Party App Access" and "Untested functionalities", and it still works.  So it was just the Pebble Notifications setting.

Anyways, thanks again for your help.  But I still feel that being able to manipulate the screen of your watch is just a fundamental feature as the health and step tracking.  It would be very useful to be able to generically "Share" anything to GadgetBridge and have it display on your watch's screen - text, images, videos even!  I hope you will consider it a feature request for the future.
