### ISSUE TITLE
Wrong timezone in pebble Morpheuz sync

### ISSUE THREAD

**Issue by derlaft** [Freeyourgadget/Gadgetbridge#689]
I live in UTC+3 timezone. In activity view, time that is displayed is UTC.

For example, I started to sleep at 21:30 and stopped at 7:00, but times that are displayed are different.

![screenshot_20170513-081059](https://cloud.githubusercontent.com/assets/852606/26022693/0025cf04-37b4-11e7-8bf7-6ef1191d6224.png)

My pebble device is pebble 1 steel (v2.0), android is 7.0, gadgetbridge is 0.19.2

**Comment by ashimokawa** [comment]
Which Firmware Version and morpheuz Version do you use?

**Comment by derlaft** [comment]
Morpheus 4.8

Firmware 3.12.3

**Comment by ashimokawa** [comment]
Thanks. I will have a look tonight

**Comment by derlaft** [comment]
No, Thank you
