### ISSUE TITLE
Bluetooth cypher

### ISSUE THREAD

**Issue by Almtesh** [Freeyourgadget/Gadgetbridge#690]
Hello,
I have just a question about the BLE connection.
My girlfriend just stupidly sent me her Facebook logins through SMS, and the SMS are automaticly displayed on my miband 2, so that mean it was transmited through BLE from the phone to the miband.
Is there any cypher or the data was sent clearly?
Thanks.

**Comment by ashimokawa** [comment]
@Almtesh 
AFAIK, the BLE connection to the Mi Band 2 is always encrypted.

@cpfeiffer 
Can you confirm?

**Comment by cpfeiffer** [comment]
If your device is paired, a BLE connection is always encrypted AFAIK. Samsung devices have problems with pairing though, so people with such devices probably have an unecnrypted connection.

If you create a btsnoop dump, you should be able to see the starting of encryption process.

**Comment by Almtesh** [comment]
OK, thanks a lot.
