### ISSUE TITLE
After updating to Nougat, the gadget does not connect after rebooting

### ISSUE THREAD

**Issue by gianlucapir** [Freeyourgadget/Gadgetbridge#693]
Hi, with the upgrade to Nougat on my Samsung Galaxy S7 connected to the Pebble time steel and my wife's Samsung Galaxy S6 connected to a Pebble time we both have the same problem-that is, just turn off the cellphone when rebooting the connection with the pebble Automatically it is necessary to manually connect it to the application, I have already enabled all the automatic connection options in the app but nothing. Before Nougat worked regularly but now no, the problem only occurs when the cellphone is restarted.
You know how I can fix thanks
Gadgetbridge 0.19.2

**Comment by danielegobbetti** [comment]
Just to make sure I understand your issue:
- Gadgetbridge is connected to the watch
- you reboot your android phone
- the android device turns on, bluetooth is on and gadgetbridge starts automatically
- the watch does not connect automatically
- after you tap the watch in the control center it connects

Is that correct?

**Comment by gianlucapir** [comment]
That's right, exactly

**Comment by razzintown** [comment]
Same for me, exactly as described by danielegobbetti. 
Nexus 6P, Android 7.1.2, Pebble 2+HR (and Pebble Time, Pebble Time Steel).

**Comment by fraganciag** [comment]
Good morning, I also have the same problem on Galaxy S6 updated to Android 7.0 with Gadgetbridge 0.19.2.
I take the opportunity to thank you for the great work you have done and that you do

**Comment by Emidio** [comment]
Hello. Same here, Note 3 on LineageOS 7.1.2 . Thanks from me too for keeping our Pebbles alive.

**Comment by danielegobbetti** [comment]
After some testing I believe that android N sends the events in a different order then previous versions. This is possibly related to the new booted-but-not-unlocked-yet status.
One possible solution is the one proposed in #737, see there for the discussion.
Another approach is to call the connect() event instead of start() on boot, but this has the effect of showing toasts (Bluetooth is disabled).
Anyway, once #737 is merged the problem will be solved, otherwise we know what to do anyway :-)

**Comment by yaomtc** [comment]
As expected, the same happens on Oreo as well, with my Moto X4.

**Comment by rbarat** [comment]
Problem description:

Gadgetbridge is connected to the watch
Reboot my android phone
Phone turns on, Bluetooth is on and Gadgetbridge starts automatically
The watch does not connect automatically
After I tap the watch in the control center, it connects
My wearable device is: Amazfit Bip watch
My phone is: Xiaomi Redmi Note 3 SE (Kate)
My ROM is: Android Oreo - Nitrogen ROM
My Gadgetbridge version is: 0.25.5.5

**Comment by momo42** [comment]
I can confirm the exact same behavior with Xiaomi Redmi Note 3 SE (Kate), LineageOS 14.1 (Android N) and Mi Band 2 on 2 separate phones and Mi Bands (me and my wife).
