### ISSUE TITLE
[Feature Request] Add other calendars

### ISSUE THREAD

**Issue by bluuub** [Freeyourgadget/Gadgetbridge#694]
#### Before opening an issue please confirm the following:
- [ x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
It would be nice to see other calendars supported besides the AOSP calendar. 
Specifically I would enjoy having support for com.simplemobiletools.calendar (available on fdroid). Since I am no Android developer I cannot estimate the effort needed to implement this.

#### Your wearable device is:

Pebble 2 HR

#### Your android version is:

7.1.2

#### Your Gadgetbridge version is:

0.19.2

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
I guess this is not possible since (at least at the first look) the app you mention does not seem to support reading the calendar events from another app.

The AOSP calendar also works offline with the "offline calendar" from f-droid. Maybe you want to give it a try.

**Comment by bluuub** [comment]
Thanks for looking into it!

The thing is I am on CopperheadOS. I actually don't have the AOSP calendar installed, preinstalled calendar app is "Etar" + Offline Calendars.

In fdroid I could get org.sufficientlysecure.standalonecalendar, which seems to be a fork of the AOSP calendar. It should be easy to add that one since it is basically the same as the official AOSP app? I don't know about Etar. Apart from the material design it seems to offer pretty similar functionality to the AOSP Cal.

**Comment by danielegobbetti** [comment]
I'm closing this as it looks to me that your issue is solved. Feel free to correct me if wrong.

**Comment by bluuub** [comment]
Yeah, solved. Sorry forgot to close it :)

Thanks for your time.
