### ISSUE TITLE
[Pebble Steel] Debug works, actual notifications not

### ISSUE THREAD

**Issue by TheFes** [Freeyourgadget/Gadgetbridge#697]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
*In case of a bug, do not forget to attach logs!*

#### Your wearable device is:
Pebble Steel
FW v3.12.3
HW: v2.0

#### Your android version is:
Android O DP

#### Your Gadgetbridge version is:
0.19.2

I have some troubles setting up Gadgetbridge.
Since I updated to Android O DP, the Pebble app is not working anymore. So I went looking and found that Gadgetbridge could be a solution.
I installed the app, and connected my phone.

In debug everything is working properly. All test notifications and test calls work.

But if I make a call to my phone, or send an SMS, mail or whatsapp message to my device, nothing happens. I can see a notification on my lock scrreen, but nothing happens on my Pebble.

I must be doing something wrong, but I have no idea what..

**Comment by TheFes** [comment]
For testing purposes I did the following
14:00 - Restarted phone
14:01 - Phone restarted
14:02 - Reconnected to Pebble Steel in app _(had to do this manuall, while automatic connect is enabled)_
14:03 - Used find my device function in app _(works fine, so connection with pebble is okay)_
14:04 - Sent test WhatsApp message from debug menu in app _(received correctly on pebble)_
14:05 - Made a call to the phone on which Gadgetbridge is installed _(call on phone is received, but nothing on pebble)_
14:06 - Sent an e-mail to the gmail account on the phone _(received on phone, nothing on pebble)_
14:07 - Sent a WhatsApp message to the phone _(received on phone, nothing on pebble)_
14:08 - Read the WhatsApp message on web.whatsapp.com _(which dismisses it on the phone)_
14:09 - Manual dismissed the mail notification on the phone
14:10 - Sent test Telegram message from debug menu in app _(received correctly on pebble)_
14:11 - Used find my device function in app _(works fine, so connection with pebble is still okay)_

The full log of all those events is attached.
For some reason the only thing which appears in the log is the startup, there was no update to the log after 14:04, and no update of any of the tests I performed.
[gadgetbridge.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/1014160/gadgetbridge.log.txt)

**Comment by TheFes** [comment]
To be as complete as possible, I have added screenshots of my current settings
![screenshot_20170519-152657](https://cloud.githubusercontent.com/assets/28803438/26249824/492222cc-3ca8-11e7-92ab-2c5bed154255.png)
![screenshot_20170519-152707](https://cloud.githubusercontent.com/assets/28803438/26249828/492816aa-3ca8-11e7-924a-467370d5bd6c.png)
![screenshot_20170519-152712](https://cloud.githubusercontent.com/assets/28803438/26249829/492a35fc-3ca8-11e7-9396-c474a167482b.png)
![screenshot_20170519-152718](https://cloud.githubusercontent.com/assets/28803438/26249826/4923959e-3ca8-11e7-94cb-71d1af2c2f3a.png)
![screenshot_20170519-152730](https://cloud.githubusercontent.com/assets/28803438/26249827/49265dba-3ca8-11e7-8d25-b745e62a178e.png)
![screenshot_20170519-152736](https://cloud.githubusercontent.com/assets/28803438/26249825/492268f4-3ca8-11e7-8292-e67eae5e3737.png)
![screenshot_20170519-152744](https://cloud.githubusercontent.com/assets/28803438/26249830/4935086a-3ca8-11e7-8992-297d028a6df0.png)

**Comment by danielegobbetti** [comment]
I'm fairly sure it has something to do with the new [notification channels](https://developer.android.com/preview/features/notification-channels.html) I'll have a look at your logs. If you could in the meantime experiment with the settings on the android side and/or the ADB logs (again on the system side, rather than on Gadgetbridge side), we could find the issue.

**Comment by danielegobbetti** [comment]
Please uncheck the "do not disturb" setting to make sure it doesn't influence the test.

Regarding the missing logs, the logs are flushed after some time, please try again (some) of the tests and then disconnect/quit from GB: this should force a flush of the logfile to disk.

**Comment by danielegobbetti** [comment]
Please also uncheck the "autoremove dismissed notifications" entry.

**Comment by TheFes** [comment]
Some time after I posted my issue I started receiving notifications, but not all of them. So it was not really stable.
I wanted to check your replies yesterday, and change the settings like you asked, but I could not connect to my pebble anymore. So I forgot it on both my phone and my pebble, and since then I am unable to pair. In some cases the pin code notification is shown on my phone, but then there is a mismatch with the code on the pebble. In other cases the notification is not shown at all on my phone.
I will try to reconnect, and as soon as that works I will change the settings and provide further logging.

**Comment by danielegobbetti** [comment]
You could try toggling BT/rebooting the android device. In my experience it's better to do it after forgetting paired devices.

**Comment by TheFes** [comment]
Finally was able to reconnect.
The problem indeed seems to be the "Do not disturb" mode. With DND on, I don't get notifications on my Pebble, when I disable it, I do get the notifications.
But basically I can use DND because I have this pebble. When I leave home, it automatically enables DND so I only get notifications on my pebble and no sounds or vibration on my phone.
It used to work with the pebble app and Android N, but know it does not work.
I don't know if that is because of Gadgetbridge or Android O, since I can not use the Pebble app on Android O (which is the reason I am trying Gadgetbridge now)

Happy to provide logging. I can do some tests with DND on and off if needed. In case you need ADB logging, please let me know how I can generate those (please note my phone is not rooted)

Thanks

**Comment by TheFes** [comment]
Extra comment.. I am quite sure I have received notifications through Gadgetbridge last week with DND active. Tasker automatically enables DND for me when I am leaving home, and disables it when I'm home.
I did receive notifications on my pebble while I was not at home, but not all the time.

So I think it works good with DND off, and with DND on it does not work all the time.

**Comment by danielegobbetti** [comment]
@TheFes I meant to uncheck the "respect DnD mode" within GadgetBridge (see your second screenshot), not to disable DnD on the android device.

I guess you did receive notifications from contacts that are configured to "skip" DnD mode either because whitelisted or because of other settings.

**Comment by TheFes** [comment]
Ah thanks, I disabled that.
It seems to be working now, stupid of me that I missed that setting though..
I will check if it works stable now. Thanks for your help!
