### ISSUE TITLE
Android notification actions are not available in Pebble notification actions (Android Wear Notifications)

### ISSUE THREAD

**Issue by gayprogrammer** [Freeyourgadget/Gadgetbridge#705]
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
*In case of a bug, do not forget to attach logs!*

#### Your wearable device is:
Pebble 2+HR

#### Your android version is:
7.1.2

#### Your Gadgetbridge version is:
0.19.2

Android actionable notifications are not showing in Pebble notification actions. If I recall correctly, the closed source Pebble app requires the Android Wear app to be installed, and calls this "[Android Wear Notifications](https://blog.getpebble.com/2014/12/16/ad-23/)". Android documentation just calls these [Notification actions](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Actions).

For example when I receive a notification of a new email from the Gmail app:
Actions shown in the Android notification:
```
Archive
Reply
```
Actions shown in the Pebble notification:
```
Dismiss
Open on phone
Mute Gmail
----
Start Quiet Time
```

Can GB support sending notification actions to the Pebble and respond to them?

**Comment by danielegobbetti** [comment]
Please enable untested features in the pebble settings. Gadgetbridge **does not** need android wear for it to work (many apps like k-9 mail and conversations or signal work without) but it *might* be that gmail does, this is up to you to test.

I believe this should be added to the wiki, since the question is often. Please consider adding a short paragraph.

**Comment by razzintown** [comment]
I enabled untested features in the pebble settings yesterday. Notifications have stopped working. I have rebooted both the Pebble and the phone.

**Comment by hackoder** [comment]
Is this feature working for anyone? I have untested features enabled, but I still get the regular options (dismiss, open, mute etc) in k9 and signal.

**Comment by danielegobbetti** [comment]
Please review your configuration to ensure that:

- untested features are enabled
- you entered at least one message as canned reply (the option only appears after enabling untested features)

If it still does not work than send logs as it's definitely working good since a long time.

**Comment by hackoder** [comment]
My bad; the 'reply' option works, but other options (mark read, or delete) don't show up in the menu. Are those options supposed to work as well?

**Comment by kapone89** [comment]
Same for me. Reply option only. Other actions missing. Tested with facebook messenger and textra.

My devices:
* Pebble Time
* Android 6.0.1

**Comment by dnastase** [comment]
So, for the record, do the "delete" and/or "mark read" actions exist ? or they're not implemented ?

**Comment by danielegobbetti** [comment]
@dnastase we don't support these actions. I actually have no idea how to do it, since the "reply" action is somehow standard, but I can't find a "delete" or "mark as read" standard action in the android documentation.

**Comment by kapone89** [comment]
@danielegobbetti You can add custom notification actions to the notification
https://developer.android.com/training/notify-user/build-notification

So you won't find "mark as read" in the documentation. You have to look for custom actions list.

**Comment by danielegobbetti** [comment]
@kapone89 don't be patronizing, please.
We know already very well **where** we have to look. We are doing so already. 

I just don't have any idea **what** to search for. That's why I say that we need either standardized actions, or a reliable proxy for other actions' types.
For instance we use the presence of a remote input attached to a notification as a proxy to consider that "reply" action is available.

If you have suggestions or other strategies please share them. The boundary conditions are:
- we cannot regex the notification actions (unless you provide a regex that works for every language)
- we cannot hardcode source package identifiers and action IDs (since these might change with every app release)

**Comment by kapone89** [comment]
@danielegobbetti Sorry, I didn't mean that.

Maybe you should talk to the author of `Notification Center for Pebble`? It's already implemented there.

**Comment by dnastase** [comment]
Ok, so I have made the Delete and Archive work for Gmail. I mean, there is nothing tied to these actions and Gmail per se, but that's the only use case scenario for me and what I tested with.
Not sure how well the implementation fits other aspects that I might miss ( @danielegobbetti brought up some points that I'm not sure I understand) but at least we know it's doable.

**Comment by danielegobbetti** [comment]
@dnastase very cool! Do you plan to create a PR with your changes or do you prefer to describe what you did before?

**Comment by dnastase** [comment]
Probably the best would be if you see the changes. Obviously my knowledge of the GB code base is very shallow as I only laid my eyes on it a week ago so my choice of an implementation might not be the best. But either if you agree or see a better way it would be easy to transfer the changes.
Would it be ok maybe to fork the GB on github and commit there ? or you have another suggestion ?

**Comment by danielegobbetti** [comment]
Sure, go ahead! Will happily review

**Comment by dnastase** [comment]
Here you go: https://github.com/dnastase/Gadgetbridge/tree/wearact (I created a branch).
Please note that:
- I have LOTS of logs in there; pls ignore those 
- I have some of the master code commented out (eg: other actions, etc); pls ignore that
- I also have my changes from when I was debugging my watch disconnects; I left them bc you may find some that are giving you an improvement idea 
- the new actions can be probably be merged into the existing reply action mechanism so as to reduce code duplication (I just wanted to see it work)

Of course, I'm available for any questions you may have.

**Comment by dnastase** [comment]
On a different note: I don't see "mark as read" action being available in the list of actions that come with a Gmail notification. Is it one of the options when original Pebble android app is installed ?

**Comment by danielegobbetti** [comment]
@dnastase as far as I can see in your code from a brief look it seems like you are pushing the notification actions "as is" to the pebble, and the watch displays their title and sends back their "id" when they are selected. Am I right?

If this is the case that doesn't indeed need parsing and is generic.

That would also mean that any action that is not present in the original notification will not be present in your array, so perhaps this explains the missing "mark as read".

**Comment by danielegobbetti** [comment]
@dnastase I used your code as a basis to implement the feature. It is available in current master, if you could  test and report if it works for you I'd be grateful.

**Comment by danielegobbetti** [comment]
0.31 was tagged, contains the fixes and will be available soon. Closing.
