### ISSUE TITLE
Zeband anomaly

### ISSUE THREAD

**Issue by albertsal** [Freeyourgadget/Gadgetbridge#706]
#### Before opening an issue please confirm the following:
- [ ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
From the latest version I noticed an abnormal behavior of zeband. Zeband initially receives messages and synchronizes the data correctly, but after a while zeband seems to block the bluetooth because I can no longer connect. At 00 the values ​​are not reset if i try to turn off or reset the band enters into a single freeze state and i can unlock it only when the battery is discharged .... when recharging the battery repeats the described behavior. Now i'm using hplus and this anomaly does not seem to occur, i guess it may be a gb problem

#### Your wearable device is:

zeband

#### Your android version is:
7

#### Your Gadgetbridge version is:
0.19.2

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by jpbarraca** [comment]
Can you send a log? I cannot reproduce the problem.

I only had two freezes with my zeband:
- Enabling and disabling swimming mode can sometimes freeze the band.
- After leaving it charging for 2 days I had to send a factory reset for it to work properly.

The hplus application frequently sends a reset command when it detects problems with the band, but GB will never do this. Maybe we have to introduce this behaviour.

**Comment by albertsal** [comment]
Ok reinstall gb and generate log ...
In my personal version I removed

Builder.write (ctrlCharacteristic, new byte [] {HPlusConstants.CMD_SET_INCOMING_MESSAGE, HPlusConstants.ARG_INCOMING_MESSAGE})

By hplusSupport
Can the freeze derive from this?

**Comment by jpbarraca** [comment]
I doubt it.
That instruction will just trigger the Message Icon.

**Comment by jpbarraca** [comment]
Is this still happening in the latest version?

**Comment by albertsal** [comment]
I try

**Comment by ashimokawa** [comment]
@albertsal 
I added a direct link to the latest release inside the README since the f-droid app is broken right now.

**Comment by albertsal** [comment]
ok i try this version for 3/4 day

**Comment by albertsal** [comment]
This version seems to be no problem. I have received many messages is the device never stuck
