### ISSUE TITLE
Mi Band 2 Firmware Downgrade

### ISSUE THREAD

**Issue by AsiqRulz** [Freeyourgadget/Gadgetbridge#708]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
Heart rate monitor is not working, I have to wear the band the opposite side of the wrist to check the HR.Mi Band 2 is updated to the latest firmware V1.0.1.50. I want to downgrade it to V 1.0.1.39. I am not able to downgrade it to any version. I went through all the threads but unfortunately couldn't find a solution.

**Comment by Vebryn** [comment]
Hi,

I understand that HRM was working with a previous firmware version. Does your band displaying a cross when acquiring HR ?

**Comment by walkjivefly** [comment]
If you consistently get a HR reading from the inside of your wrist but not the outside then you probably just have (too) hairy arms.

My Mi Band 2 simply stopped measuring HR after about 4 months :-(
