### ISSUE TITLE
Some new icons [suggestion]

### ISSUE THREAD

**Issue by xphnx** [Freeyourgadget/Gadgetbridge#723]
I have made a few new icons for you to study the possibility of incorporating them into the app. I do not make a merge request because you can add the ones that look better to you independently. Of course I can do the necessary retouching

# **HPlus icon**
![device_hplus](https://user-images.githubusercontent.com/4024412/28364493-f2b257d8-6c84-11e7-9801-f56f5e9b197f.png)
![device_hplus_disabled](https://user-images.githubusercontent.com/4024412/28364496-f41802d0-6c84-11e7-81d3-23a702d77ddd.png)
I think this way it fits better to the symbology used with other devices. I have done a search of images to see how the device in question is, I guess I have found the right one. It could be that, as the supported devices increase, difficulties arise in representing devices that may be very similar to each other in terms of their silhouette.

# **Lovetoy icon**
![lovetoy](https://user-images.githubusercontent.com/4024412/28364633-9868ebec-6c85-11e7-9833-094501070e71.png)
![lovetoy_disabled](https://user-images.githubusercontent.com/4024412/28364636-995379a0-6c85-11e7-877c-19411b903cf9.png)

To better align the sizes and adjust it to the general scheme

# **Default device icon**

![default](https://user-images.githubusercontent.com/4024412/28364667-bb089fee-6c85-11e7-9963-ae04b73fd0d3.png)
![default_disabled](https://user-images.githubusercontent.com/4024412/28364668-bc797542-6c85-11e7-91d4-66f60afcae19.png)

I am not fully sure if this icon is better than the launcher icon. I try to represent a generic device...

# **Battery notification icon**

![batery](https://user-images.githubusercontent.com/4024412/28364741-24651e90-6c86-11e7-84a8-aceeb6a00207.png)
![batery2](https://user-images.githubusercontent.com/4024412/28364743-2558a6a0-6c86-11e7-8d87-44458144855d.png)

Same, not sure if it fits better than the actual one. 2 options. Could the icons used right now confused with the battery icon of the Android device itself?

# **Notification icon**

![notification](https://user-images.githubusercontent.com/4024412/28364915-d5e739e6-6c86-11e7-913f-4e849a93deb1.png)
![notification_disabled](https://user-images.githubusercontent.com/4024412/28364919-d70395e0-6c86-11e7-9c50-c5268e1fc136.png)

I think probably a simpler icon fits better with the general iconography of the Android design. It has occurred to me to use the image of a generic device. The disabled line, fits the material design guidelines. Maybe it could be mistaken with a battery icon?

Download svgs: [nuevos_iconos.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1158888/nuevos_iconos.zip)
*Ray and heart icons reused from Google Material Design iconography (CC BY-SA 4.0)
 ** Sorry I didnt notice the notification icons cant be seen with the default white background of Github (I use custom CSS for a dark background ;( )

**Comment by jpbarraca** [comment]
Great 👍 
I think the battery icon could be related to a battery, and not power.

**Comment by ashimokawa** [comment]
Thanks, I used them except for battery and notification icon (I like the fist and what @jpbarraca said) ;)
