### ISSUE TITLE
Won't connect to OG Pebble(s) on Blackberry KeyONE with Nougat 7.1.1

### ISSUE THREAD

**Issue by qn4** [Freeyourgadget/Gadgetbridge#726]
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
For the past month since I've had my new phone, Gadgetbridge seems unable to connect to any of my Pebble watches: pairing via Android's Bluetooth manager or Gadgetbridge, with default Gadgetbridge settings or otherwise, and under any conditions I throw at it, I've included a non-exhaustive list of such conditions at the bottom of this post. The icon that normally turns blue never does, even for a moment, and the list goes from "connecting" back to "not connected" anywhere from a few seconds after being tapped to under a half-second. On the GB device pairing screen, GB seems to not catch the event when the pebble completes pairing with the phone (which seems to be successful) and continues to sit indefinitely as if the pairing has not yet completed. Logs are attached for the first Pebble in the list below.

Official Pebble Apps (Time for v3.x watches, "old version" for the v2.9 watch) connect and function without issue on the same phone (well, aside from wiping and re-sorting my apps each time...)

In the below log, I followed these steps on a fresh install, default settings with logging turned on:
1. Attempted to connect the already-paired Pebble a few times in Gadgetbridge
2. Removed pairing via the 'trash can' in Gadgetbridge
3. Unpaired watch from watch firmware
4. Rebooted both devices
5. Started the add device wizard in Gadgetbridge with Pebble in Bluetooth screen
6. Two devices showed up: the LE and non-LE IDs for my xxA7 watch.
7. I selected the non-LE device
8. Pairing requests show up on phone & watch, with matching numbers
9. I accept on phone first, wait two seconds, then accept on watch
10. Screen stays on the "A pairing dialog is expected to..." page.
11. I wait for ~5 minutes with that screen still up and no further interaction.
12. Nothing appears in notification drawer. Screen had been set not to time out.
13. Tap 'back' a few times to get back to Gadgetbridge device list
14. 'New' xxA7 device is paired and recognized as Pebble
15. Tried tapping xxA7 a few more times with space between taps.
16. GB displays 'not connected' -> 'connecting' -> 'not connected'
My watchface (Timely 2.6) normally vibrates when watch connects/disconnects. This does not trigger.

Note that my other two watches are off or in airplane mode for the extent of the logging, and only one ("xx6B") remains in the paired list in the phone. No other devices are paired. Battery is removed from previous phone.
[gadgetbridge_censored.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/1168435/gadgetbridge_censored.log.txt)

The lines at the end seem to be present in every log I take; the following seems suspicious?
`INFO` n.f.g.e.BluetoothConnectReceiver - won't connect to 00:xx:xx:xx:xx:A7(Pebble xxA7)

This one also occurs consistently. Once or twice I'm pretty sure I've seen it paired with an identical line with mostly/all zeros for the UUID, but this hasn't happened for a while. If that might be helpful, I'll keep an eye out for it and update with a comment on the exact line if I see it again. Somehow this UUID strikes me as... odd? Google searches for it don't seem to bring up anything meaningful.
`DEBUG` n.f.g.a.DiscoveryActivity -   supports uuid: ffcacade-afde-cade-defa-cade00000000

#### Your wearable device is:
I've tested with my three Pebbles:
- Pebble OG running stock Firmware v3.12.3, hardware V3R1 ("xxA7" in the attached logs)
- Pebble Steel OG running stock Firmware v3.12.3, hardware 102V1 ("xx6B")
- Pebble OG running pebblebits-modified Firmware 2.9.1-bits, hardware V3R3 ("xxD9")

As the third Pebble is understandably not a 'typical'/supported software configuration, I've done all my testing on the first watch and duplicated almost all of it on the second, with the third only as an occasional reference.

#### Your android version is:
Blackberry KeyONE (CDMA variant, model BBB100-3) running Android Nougat 7.1.1. Current (AAL093) software image. Never rooted.

#### Your Gadgetbridge version is:
0.19.4, but same issue is present on 0.19.3 and each of several versions tried from F-Droid as far back as 0.13.9 (each tried after a full uninstall, reboot, fresh install). Same versions work fine with all the same Pebbles on my previous phone running Android 4.4.4, and have worked on that phone for the year or so I've been using Gadgetbridge. I've also run each Pebble (briefly!) via Gadgetbridge on my work phone, a Galaxy S4 running Android 5.0.1. That phone has Bluetooth disabled at all other times.

#### My non-exhaustive list of things tried:
- Connect through Gadgetbridge and Android device-add wizards
- Keep connection from Official Pebble install/pairing
- All three aforementioned watches
- Several versions of Gadgetbridge as far back as 0.13.9 (known working from when I started using GB on previous phone)
- Disabled 'battery optimization' for Gadgetbridge
- Attempted with and without Android Wear app installed
- Tried re-pairing on previous phone (worked)
- Performed a factory reset on OG Pebble "xxA7"
- Waiting for shorter and/or extended periods of time at different steps during pairing/connecting steps (e.g. for Bluetooth scan to complete and sit for a minute before selecting Pebble, waiting before pairing pebble on phone and/or watch)
- Approving pairing request on phone or pebble first, and varying amount of time before & between approving pairing request.
- Tried during my lunch break at work in case of problematic Bluetooth interference at home
- With and without DNS66 VPN 'server' enabled
- With Blackberry's "DTEK" security/privacy event logging software on & off (to the extent permitted)
- With all permissions in Android allowed, both as they are requested and preemptively, right after a fresh app install.
- Pairing of watch with no other known Bluetooth devices, or existing (pebble/headset/etc) devices already paired.
- Numerous reboots and GB reinstalls between different tests.
- Different GB settings configurations; usually stock with only logging enabled, if anything.
- Official Pebble apps are always removed, then phone rebooted before installing Gadgetbridge

#### Things I haven't tried:
- Factory reset of phone (I'd really rather not, but can if I absolutely, positively must...)
- Other Android 7.1.1 phones (I don't have any)

I'm really at a loss here... has anyone else had success with Gadgetbridge on an Android-equipped Blackberry phone, Android Nougat 7.1.1, or some combination the two? These seem to be the only variables I can isolate. Thanks in advance for any input...

**Comment by ashimokawa** [comment]
I haven't looked at the log yet but...

I am using Lineage 14.1 on two Phones (Android 7.1.2 and 7.1.1 before) and I have zero problems connecting them to my OG Pebble...

**Comment by ashimokawa** [comment]
@qn4 
Can you please try to forgot the pebble on your phone and the phone on your pebble.
Then pair through android settings and not Gadgetbridge.
After having paired connect trough the main activity. And send a log from that attempt.

**Comment by qn4** [comment]
Thanks @ashimokawa 
For this log, I forgot the pairing of Pebble xxA7 (and all other devices) on my phone, then from the Bluetooth screen of the Pebble, and power cycled both devices. I paired the Pebble through Android Settings; the devices paired without issue. After that, I opened up Gadgetbridge. Pebble xxA7 was listed, not connected in the main activity. Tapped the listing, briefly stated "connecting", then "not connected" again. I repeated this a few times. The 'watch' icon never turned blue as it does on my other phones.

[gadgetbridge_7-24_censored.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/1171611/gadgetbridge_7-24_censored.log.txt)

Possibly relevant: After copying the log to external storage for eventual upload here, I tried connecting with the pebble in airplane mode vs. with Bluetooth enabled. The 'connecting' phase seems to take a variable amount of time in either mode, but takes a longer time when the watch isn't 'there'. Definitely about twice as long on average (several seconds) when the Pebble is in airplane mode across about 10 attempts each way. I gather this means the Pebble's presence is affecting Gadgetbridge in some way?

**Comment by amatayamada** [comment]
I'm having the exact same issue (pairing, listed, not connecting in GB) on Oneplus 3T/LineageOS-14.1-20170608-NIGHTLY-oneplus3 with Mi Band 2. If I can provide any helpful logs, please tell me which ones.

**Comment by ashimokawa** [comment]
@qn4 
I had a look at your log but unfortunately the stacktrace is not logged to the log file.
You could obtain a logcat with adb while trying to connect, then you will see the stacktrace.

Another option is to build current master yourself or wait for the next version, then a failed connection attempt will write a full stacktrace in the log and we know more.

I have some ideas for workarounds - but first let me see the stacktrace if you have it.

**Comment by qn4** [comment]
I built the current master and have attached the logs... there are definitely a few new lines, but I may have goofed something up, too. I'll have my USB C cable to try adb tomorrow if this isn't sufficient.
[gadgetbridge.log_8-11-17.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/1219425/gadgetbridge.log_8-11-17.txt)

For what it's worth, I did perform a factory reset on the phone a few days ago and installed FDroid and then Gadgetbridge before adjusting any settings or installing anything else. Same results as before, but it was worth a try.

**Comment by ashimokawa** [comment]
@qn4 

In PebbleIOThread.java can you please make a small change and test?

mBtSocket = btDevice.createRfcommSocketToServiceRecord(uuids[0].getUuid());

to

mBtSocket = btDevice.createRfcommSocketToServiceRecord(UUID.fromString("00001101-0000-1000-8000-00805f9b34fb"));

**Comment by qn4** [comment]
@ashimokawa That seems to have done the trick! I needed to accept some auto-suggestion/fix regarding the "UUID" part to get it to compile, but my Pebble Steel on 3.12.3 and OG Pebble on 2.9.1 both connected without issue this time and responded properly to debug notification tests! Thank you!
Is there anything specific I should test to verify that everything else is still working as it should be?

**Comment by ashimokawa** [comment]
@qn4

Thanks for testing, I will commit a fix before the 1.20.0 release.

Since pebble inc is dead, we can expect to have it working with the hardcoded uuud forever. 👍
