### ISSUE TITLE
Settings do not apply without restart

### ISSUE THREAD

**Issue by lazarosfs** [Freeyourgadget/Gadgetbridge#731]
For some reason my changes do not seem to immediatelly apply.
I need to quit GB and clear recent to get the new settings.

I tested different settings in Mi band settings activity, like number of repetitions etc.
printing the settings before notification shows that remain the same unless quit and restart.
Does anyone else experience this?

**Comment by joserebelo** [comment]
Do you have a log? You can get it by enabling the option to write log file in the Settings or by a normal logcat. And what do you mean by printing the settings before notification?

**Comment by lazarosfs** [comment]
Will create log for you. I mean I put a LOG.debug("Printing chat repetition count"+...); in NotificationListener before the GBApplication.deviceService().onNotification(notificationSpec); and recompile to see the values in logcat on runtime and they are the same until I quit and restart GB.
No log right now but will produce one.

**Comment by joserebelo** [comment]
Oh, sorry, I misinterpreted your issue, a log might actually not be needed. I will try to reproduce this later.

**Comment by cpfeiffer** [comment]
This could happen if the UI and the service were in separate processes, but this is not what we do. Maybe MIUI overrides this?

**Comment by lazarosfs** [comment]
Hmm, although it did happen a lot of times right now I am unable to verify it and it might be a bug on my own build. Lets close the issue for now please
