### ISSUE TITLE
Setting language/ language character support

### ISSUE THREAD

**Issue by lazarosfs** [Freeyourgadget/Gadgetbridge#733]
I still believe that setting a language other than system default is a bad idea.
To me v0.19.4 version still has problems setting locale.
If I change lang to anything else I am unable to return to system default.
Returning from Settings->database Management usually gets me to German or Spanish lang without me having chosen this.

Does anyone else have problem with this?
I am testing v0.19.4 on Android 6.0.1 Miui 8.2.4 Rom on Redmi 4 Prime, mi band 2 fw 1.0.53

**Comment by cpfeiffer** [comment]
I'm not sure what you're referring to. We don't set any language, and in particular not for the Mi Band 2.

What is your actual problem?

**Comment by lazarosfs** [comment]
I am referring to general option of the app language.
There is an option to set the Ui language.
This does not work right ro me.
If I choose anything else than System default I get different random translations in some activities.
I also found some actions not working if you set a language that there is no available translation.
For example setting my mobile to Greek ui, has a result of notifications without text to my mi band 2.

**Comment by cpfeiffer** [comment]
I've never tried that. I don't think my ROM actually has the possibility to set a custom language/locale per app.

For sure you would need to reboot or kill and restart Gadgetbridge after changing the language.
Do you have problems when sending Greek characters or Latin characters to the band?

The character encoding should still be UTF-8 even if you change the language to Greek. If you need some help debugging this, just say so. You could dump the system properties, for a start.

**Comment by danielegobbetti** [comment]
@cpfeiffer I believe the reported problem is related to our own language switcher (in the preferences), not to specific ROM/android version functionality.

**Comment by cpfeiffer** [comment]
I didn't know we have one :open_mouth: How about moving it to the Debug screen? I don't think this is supposed to be a general user setting.

**Comment by IzzySoft** [comment]
Why not? It's helpful more often than you would think. Consider a device for which we might have an incomplete localisation. Instead of a mess with mingled terms, the user might prefer a consistent one in some other language – without changing that for the entire system. Had that for me with several apps.

**Comment by cpfeiffer** [comment]
OK,  the language is only really applied when you open a "GBActivity", e.g. the charts.

**Comment by cpfeiffer** [comment]
Fixed.
