### ISSUE TITLE
Choose from which calendars to display events

### ISSUE THREAD

**Issue by phenx-de** [Freeyourgadget/Gadgetbridge#736]
#### Before opening an issue please confirm the following:
- [ X ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ X ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
I use multiple calendars within Google Calendar, e.g. Work, Personal, Family, ...

In the original Pebble App I could choose which of those should be synchronized to the Pebble. In Gadgetbridge, I can not find such an option. Is it planned to implement this feature?

#### Your wearable device is:
Pebble 2

#### Your android version is:
Android 8 DP 4

#### Your Gadgetbridge version is:
0.19.2

**Comment by IzzySoft** [comment]
Not limited to Google calendars (eg. DAVDroid also supports syncing multiple calendars). Should default to "ALL" – but I can see the usefulness of "blacklisting" (or "whitelisting") specific calendars, though I don't need it myself currently.

**Comment by ShapeShifter499** [comment]
I would love to see a feature like this
