### ISSUE TITLE
Disconnect Bluetooth on MiBand2 side

### ISSUE THREAD

**Issue by RuiBandarra** [Freeyourgadget/Gadgetbridge#738]
I would find it useful to have an option to enable and disable the bluetooth and the heart rate sensor light on the back, on the Mi Band2.

the reason for this is that there is increasing evidence that bluetooth, wifi, and even the kind of lights mi band2 uses, may pose a health risk , especially if being subject to it 24/7.

Additionally this would increase battery life on the device.

**Comment by walkjivefly** [comment]
Maybe you should sit quietly in a darkened Faraday cage, just to be on the safe side.

Seriously, how do you propose to disable, and later re-enable the bluetooth on the Mi Band 2? 

Do you have a reference to peer reviewed documentation on the adverse health effects of green LEDs? If you are afraid the heart rate sensor light is going to kill you you could use a Mi Band instead. If you keep your dangerous Mi Band 2 you can disable heart rate sensor sleep detection assist if you want to. 

The battery life on my Mi Band 2 is generally in excess of 1 month on a single charge. How much more battery life do you want?

Watch our for all the tricksy EM fields from your phone, computer, tablet, fluorescent lights, microwave, TV, car, next door neighbours, broadcast TV and radio stations, ...

**Comment by cpfeiffer** [comment]
Indeed, we can't disable Bluetooth on the Mi Band 2, since we would not be able to turn it on again. You can disable the heart rate readings during sleep though.

Apart from that, I don't think we can do anything here.

**Comment by RuiBandarra** [comment]
@walkjivefly , i know it may be hard for you to understand, but there are many people looking for this feature. Regarding the effects of EMF on health, you can go on pubmed and search it for yourself before replying without any knowledge. Github is not the place to post peer reviewed studies.

If you would disable the bluetooth you have many sensors on the miband that would be useful for later re-enabling it. If you cant do it then thats another story.

**Comment by cpfeiffer** [comment]
Well, it is an interesting idea, but our only way to control the band is Bluetooth communication. So the reactivation of BT on the band would have to be controlled by the band's firmware.

If you find out how disable and enable Bluetooth on the band, we can certainly implement this in Gadgetbridge.
