### ISSUE TITLE
Add location of the debug log file to readme

### ISSUE THREAD

**Issue by chrisvella** [Freeyourgadget/Gadgetbridge#74]
Hi

Trying to debug why my mi band is no longer connecting to gadget bridge. It appears the file location has changed or I have done something weird to my device. Having the location in the readme would be really useful.

**Comment by ashimokawa** [comment]
Just before 0.4.0 I have changed the preference key from logging, so has been been turned off for everybody...
The reason was that the preference key was in strings.xml and people started to translate it, which results in a preference key which depended on the users language, which was not good.

**Comment by chrisvella** [comment]
Oh okay. So we have to compile the app from source to get a log? Any steps on how to re-enable it for debugging purposes?

**Comment by ashimokawa** [comment]
No, I just tested 0.4.0 from f-droid. Logging works.
You have to turn on logging from the settings.
And then make sure to restart Gadgetbridge. (You can force quit from the android settings it you want to be 100% sure).
After that you will find logs in

/sdcard/Android/data/nodomain.freeyourgadget.gadgetbridge/files/gadgetbridge.log

I will add that to the README later.

**Comment by chrisvella** [comment]
hmmm must be just my device. That's where I found the logs before... but now the folder is gone. Will have to investigate.

**Comment by cpfeiffer** [comment]
Does the directory still exist? Is it empty or is the old logfile still available?

Does it connect again? Do you use the MiFit app, which may have updated your Mi Band's firmware such that it is now incompatible with Gadgetbridge?

**Comment by cpfeiffer** [comment]
I updated README.md with instructions to access the logfile, so I'm closing this issue.

Can you create a new issue with your actual problem (if it persists)? Thanks :-)

**Comment by chrisvella** [comment]
I discovered the cause of the issue. I couldn't connect to my device because it had some conflict with my list of already paired devices. No idea why this occurred, but the fix was simplying removing my mi band from paired Bluetooth devices and starting the process again. Then the folder and log file appeared.
