### ISSUE TITLE
Textual notifications not working on 1.0.1.39 (Wiki mistake)

### ISSUE THREAD

**Issue by ogbaba** [Freeyourgadget/Gadgetbridge#740]
#### Your wearable device is:
Mi band 2 fw 1.0.1.39 hw V0.1.3.2
#### Your android version is:
7.0
#### Your Gadgetbridge version is:
0.19.4

Hello ! I looked up in the wiki and found this : 

> Note: For text and special icon notifications you need to have firmware version >=1.0.1.28 and the corresponding font files (Mili_pro.ft and Mili_pro.ft.en) installed.

I also looked up the compatibility between firmware and Gadgetbridge features, my Mi Band 2 is supposed to support text notifications on this firmware version and I ticked the box in the settings to enable textual notifications but my Mi Band 2 only displays icons when I get a notification.
Is it supposed to work ?
I installed the .ft file.

Thank you.

UPDATE it is working on firmware 1.0.1.34 so the wiki is wrong about firmware compatibility I believe it should be fixed

**Comment by cpfeiffer** [comment]
It does work with 1.0.1.39, and with some help we will find out why it does not work for you.

Can you play a bit with the Debug screen and send notifications with different types to your band? If you find out which ones do not work, you could send us a log file that captured exactly the non-working notifications. If indeed none of them work, a log with just one attempt is sufficient.

Did you install the .ft file or the .ft.en? You need the .ft.en file for latin characters, I suppose.

**Comment by ogbaba** [comment]
Hello, I tried both the .ft file and the .ft.en and nothing worked on 1.0.1.39 version, I will try that version again and give you a log.

**Comment by ogbaba** [comment]
That is weird, I can't happen to reproduce it… am on 1.0.1.39 firmware now and it seems to be working fine…

**Comment by cpfeiffer** [comment]
Maybe the band needed a reboot and maybe something else got mixed up. Feel free to reopen it when you get issues again, but I'm pretty sure it will keep working :-)

**Comment by ogbaba** [comment]
Yes by the way I remember it wouldn't reboot then.
