### ISSUE TITLE
mi band 2. can't track sleep monitoring

### ISSUE THREAD

**Issue by mikhakhaldea** [Freeyourgadget/Gadgetbridge#743]
Dear All. I have problem with sleep monitor on my mi band 2. my mi band 2 can't recognition sleep automaticly as before. I use firmware 1.0.1.50 and hardware version V0.1.132. Any here have same problem with me? Thanks for your time. 

Android 4.4.2
Gadgetbridge 0.19.4

**Comment by mikhakhaldea** [comment]
Sleep monitor always shown 0 minutes. But HR monitor is detect like as sleep.

**Comment by dannytaylor** [comment]
[Per the wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Information) you'll need to downgrade to firmware 1.0.1.39 for sleep detection.

**Comment by mikhakhaldea** [comment]
Ok. Thank you. I will close this issue
