### ISSUE TITLE
Add a toggle "blacklist all" button

### ISSUE THREAD

**Issue by ogbaba** [Freeyourgadget/Gadgetbridge#745]
Hello, I think it would be good to add a buton to toggle blacklist for all the applications in the blacklist activity since sometimes one may want to enable just a few apps notifications.
It would be less painfull than ticking all the boxes one by one.
Thanks !

**Comment by danielegobbetti** [comment]
#679
Please use the search functionality.

**Comment by ogbaba** [comment]
oh sorry i forgot to check
