### ISSUE TITLE
mi band2: feedback firmware 1.0.1.50

### ISSUE THREAD

**Issue by giupardeb** [Freeyourgadget/Gadgetbridge#746]
Hello everybody, I would like it to be known that I have installed the firmware 1.0.1.50 version, and I can say that it seems working now. :-)

**Comment by Raybuntu** [comment]
+1 I have the same although I haven't checked sleep detection yet. Have you @giupardeb?

**Comment by shatteringlass** [comment]
I have been running 1.0.1.50 for a couple of weeks now, and I do get HR monitoring during sleep, so the activity is correctly detected. Anyways, I don't have any sleep tracking, so there must be something wrong with light sleep/deep sleep decoding in Gadgetbridge.

**Comment by giupardeb** [comment]
@Raybuntu last night I tested sleep detection and it didn't work..

**Comment by joserebelo** [comment]
Activity types aren't correctly detected by Gadgetbridge with firmware 1.0.1.50, check #650 and #686.

The rest does indeed seem to work fine, afaik.

**Comment by Hkrusse** [comment]
Hi, can anyone tell me where can i donwload this firmware for manually upgrade? Can use mi fit.... Lost phone....

**Comment by shatteringlass** [comment]
@Hkrusse just have a look at [this wiki page](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Mi-Band-Firmware-Update), you should be good to go then.

**Comment by Hkrusse** [comment]
Thanks for quick reply, but i already followed that procedure, but the best firmware that i get was 1.0.0.53.... my mili_pro.fw file went to 1.0.0.39.... 
If i get the latestest firm, even without mi fit i could get more of mi band 2....
With this i don't have, text, not even all icons...

**Comment by shatteringlass** [comment]
@Hkrusse this is really not the place for troubleshooting. I followed the same instructions as you, and got the fw files working. Just stick to the wiki page. Or, if you prefer, use the tools provided by flycodepl/mi-band-firmware-analyse to automagically get the latest app and fw files.

**Comment by cpfeiffer** [comment]
Thanks for the info -- someone even add it to the wiki already :+1: 

Now we need to get sleep detection working with that version!
