### ISSUE TITLE
Feature request: set custom vibration for pebble

### ISSUE THREAD

**Issue by djvantri** [Freeyourgadget/Gadgetbridge#747]
Set custom vibration intensity and duration for notifications 

#### Your wearable device is:
Original pebble v3r2
V 3.12.3

#### Your android version is:
Android 7.0
#### Your Gadgetbridge version is:
0.19.4

**Comment by danielegobbetti** [comment]
I don't think it's possible to override what's being set on the watch itself. Is it an option in the official app?

**Comment by djvantri** [comment]
Sorry I guess I assumed it could be an option. I never saw it in the official app, only notification centre for pebble seems to allow it.

**Comment by danielegobbetti** [comment]
I guess that in this case the watchapp takes care of the notifications. Is the watchapp open source? If this is the case we could offer an option to send notification to it instead of the standard pebble handler.

**Comment by ashimokawa** [comment]
It is - but then again its companion app might work as is and can be used. 

https://github.com/matejdro/PebbleNotificationCenter-Watchapp

**Comment by danielegobbetti** [comment]
Alright, I'm closing this.
