### ISSUE TITLE
Bug background service Gadgetbridge is killed on xiaomi smartphone

### ISSUE THREAD

**Issue by giupardeb** [Freeyourgadget/Gadgetbridge#748]
Sometimes background service Gadgetbridge is killed and I'm forced to re-open application and add the mi band again.

**Comment by lazarosfs** [comment]
You have to exclude gadgetbridge from the battery saver from the system->battery menu and the permissions->autostart menu.
Please do both and reboot twice. 
Gadgetbridge must be able to autostart on reboot (if the option on gb's menu is checked)

**Comment by giupardeb** [comment]
Ok I will follow your step and i will inform you.

**Comment by giupardeb** [comment]
@lazarosfs I follow your step, now Gadgetbridge autostarts on boot, but there is a problem:
if I get away from the smartphone, the mi band disconnects and when I try to connect it again, it doesn't work. I'm forced to re-add the mi band again.

**Comment by lazarosfs** [comment]
giupardeb please see issue #564. At the last posts I have a test version, try it and let me know.
You will have to uninstall first. Also check the battery saver and the autostart aigain after installing it.

**Comment by giupardeb** [comment]
@lazarosfs Hi I have installed a test version of gadgetbridge, but the problem persists, also I am not be able to re-add mi band.

**Comment by giupardeb** [comment]
@lazarosfs With the new version of Gadgetbridge 0.20.1 the bug is fixed! Now if I get away from the smartphone, the mi band disconnects and when I try to connect it again, it works!

**Comment by dbrgn** [comment]
On Xiaomi phones it also helps to pull down the app entry in the app switcher and then to enable the lock icon in the upper right corner.
