### ISSUE TITLE
Transifex strings outdated

### ISSUE THREAD

**Issue by mueller-ma** [Freeyourgadget/Gadgetbridge#749]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I wanted to translate some new strings, but transifex say to the english ones:  "Resource last updated by Carsten Pfeiffer 2 months, 2 weeks ago"

Can you upload the new strings?

**Comment by ashimokawa** [comment]
I think there are no newer strings

**Comment by mueller-ma** [comment]
23 days ago: https://github.com/Freeyourgadget/Gadgetbridge/commit/f7abe2d4a35b142ba78f509f528d87bb5db1eaaa#diff-01dafb3fd0217441330103cfc8300094

**Comment by cpfeiffer** [comment]
Thanks! Apparently the auto-update got stuck while the repository was down. I now tried to make it auto-update again, but the transifex web interface is often weird and inconsistent, so I'm not sure if that worked.

I'll keep this issue open until we know that it works.

**Comment by ashimokawa** [comment]
It worked!
