### ISSUE TITLE
Disconnect option available for unconnected devices.

### ISSUE THREAD

**Issue by chrisvella** [Freeyourgadget/Gadgetbridge#75]
Really minor issue.
I have noticed the disconnect option is available for unconnected devices.
I assume the issue also affects the pebble. Definitely visible for my mi band.

**Comment by cpfeiffer** [comment]
Yeah, good point. The "Fetch activity data" should also be unavailable when disconnected.

**Comment by cpfeiffer** [comment]
I'm actually not 100% sure about the disconnect option. Sometimes the activity and the service do not quite agree about being connected or not. And then it helps disconnecting the (already apparently disconnected) item.

I'm still looking for a proper fix of course, but I don't quite understand it yet. Maybe it's the underlying BT stack that's stuck or the BtLEQueue is somehow broken.

Disposing the MiBandSupport instance (and the queue) by performing "Disconnect" does help, though.

**Comment by ashimokawa** [comment]
@cpfeiffer 
Sorry, I was not aware that this can happen.
While the problem persists, you can just easily change the code, so that the option does not get removed in case of Mi Band. With the Pebble I never had such problems, so I guess it is safe to remove it in case of the Pebble.
