### ISSUE TITLE
"Smart Alarms" with MiBand 1

### ISSUE THREAD

**Issue by shyguy80** [Freeyourgadget/Gadgetbridge#750]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I can't set "Smart Alarms" in Gadgetbridge. It detected my old "Smart Alarms" (which i set up in the official app) but i can't find an option to create an "Smart Alarm" from within Gadgetbridge.

By the way: The firmware version "01.00.10.14" which is recommended in the wiki, shows as untested in the process of updating/downgrading the firmware with Gadgetbridge.. Is there a better or more compatible firmware-Version?

#### Your wearable device is:
Xiaomi MiBand 1 - Firmware 01.00.10.14

#### Your android version is:
LineageOS 14.1 - Android 7.1.2

#### Your Gadgetbridge version is:
0.19.4 from F-Droid

**Comment by cpfeiffer** [comment]
When editing an alarm, there should be a small checkbox "smart wakeup". If that isn't visible, that would be a bug.

Firmware 1.0.10.14 is not actually recommended by us. The wiki says that there are some issues with vibrations, which is the reason why this version is not "whitelisted" in Gadgetbridge.

1.0.10.11 OTOH works fine.

**Comment by bademux** [comment]
Looks like Gadgetbrige bug
the same symptoms for MiBand1S (4.16.4.22 Mi Band + 1.3.76.22 HR):
Old Alerts are shown wich "Smart Checkbox", but updating alarm hides checkbox
