### ISSUE TITLE
FR: More icons on mi band 2

### ISSUE THREAD

**Issue by mueller-ma** [Freeyourgadget/Gadgetbridge#755]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I think it is not possible to upload new notification icons to the mi band, but I haven't found any information about this. Can someone confirm this?

**Comment by cpfeiffer** [comment]
I don't know of a way to do this either. I suppose they are hardcoded in the firmware files, so you might want to have a look at hacking this :-) Feel free to reopen this issue if anybody has new information!

**Comment by mueller-ma** [comment]
I have downloaded a properity mi band app and there I can select icons for each app:

- Chat
- Penguin
- Mi chat
- FB
- Twitter
- Mi Fit
- Snapchat
- Whatsapp
- Eye
- Some chinese symbole
- Amazfit
- Instagram
- Momo
- Qianniu
- Alibaba
- Aliplay
- Qzone
- Some chinese symbole
- Some chinese symbole
- Dingding
- Calendar
- FB Messenger
- Viber
- Line
- Telegram
- KakaoTalk
- Skype
- VK
- Pokemon Go
- Hangouts
- Mi
- Lucky Money
- App
- Email
- Message
- Message with heart
- Call

**Comment by mueller-ma** [comment]
@cpfeiffer I cannot reopen. A selection for the displayed icon for each app would be a great feature
