### ISSUE TITLE
Pebble 2 keeps vibrating after a call is accepted on the phone

### ISSUE THREAD

**Issue by anmith** [Freeyourgadget/Gadgetbridge#756]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
When accepting a call on the phone, the Pebble keeps vibrating

#### Your wearable device is:
Pebble 2 SE, Firmware v4.3

#### Your android version is:
Android 7.1.2

#### Your Gadgetbridge version is:
0.19.4

**Comment by ashimokawa** [comment]
Can you send a log file (look if it contains personal data before sending)?
Also make sure you granted all permissions.
Which Android version is that exactly?
It works with my Pebble2 on Lineage OS 14.1 (7.1.2)

**Comment by anmith** [comment]
Hi,
it's stock Android 7.1.2 on a Nexus 5X, Patch Level August 2017

I think it has something to do with a notification being there while the call is active as the Pebble stops vibrating immediately if I cancel the call instead of accepting it.

I'll see that I send a log asap.

**Comment by danielegobbetti** [comment]
Is it a normal call accepted through the system dialer or are you using some messaging system and/or another dialer? I'm on aosp (7.1.2) and I don't have this issue.

**Comment by ashimokawa** [comment]
Just for clarification. Detecting the call state is not done though notifications in Gadgetbridge. It tracks the phone state and should normally recognize that the call has been taken. Stock Android on a Nexus is pretty much AOSP - and Lineage also works. Very strange bug indeed.

**Comment by anmith** [comment]
I'm using the "normal" Google dialer which comes with the OS. 

Played around yesterday, the problem is reproducable:

I call my mobile:
1) if I decline the call, the Pebble stops vibrating at the same moment the call is declined
2) if I accept the call, the Pebble keeps vibrating (didn't test how long this would be but at least several seconds until I hung up. Pebble also kept vibrating after hanging up.

I turned on the logging in Gadgetbridge, called my mobile, accepted the call, hung up and deactivated the logging. Hopefully the attachment will help.
[gadgetbridge.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1220328/gadgetbridge.zip)

**Comment by anmith** [comment]
Did an update to Android 8.0.0 yesterday, first call this morning worked like expected - so the problem is solved.
