### ISSUE TITLE
Clay configuration is broken with Chromium 60 Webview 

### ISSUE THREAD

**Issue by ashimokawa** [Freeyourgadget/Gadgetbridge#758]
Clay (local javascript configuration framework for Pebble Apps) reloads a data url - this is forbidden in a top frame since Chromium 60

https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM

A possible solution is to wrap things in an iframe at our side

**Comment by danielegobbetti** [comment]
Will look into it ASAP
