### ISSUE TITLE
Provide screenshots from other apps?

### ISSUE THREAD

**Issue by mueller-ma** [Freeyourgadget/Gadgetbridge#760]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I downloaded a other third party mi band app and got some good ideas I want to share. I dont want to cause a second DMCA so it is allowed to share screenshots?

**Comment by cpfeiffer** [comment]
Thanks for asking! If it's too hard to explain the feature, then you might share the image via some other site.
