### ISSUE TITLE
Suggestion for donation version in Google Play

### ISSUE THREAD

**Issue by DavisNT** [Freeyourgadget/Gadgetbridge#761]
I understand that Gadgetbridge is a free (as in "free speech") software and Google Play is a proprietary platform. 
However I would like to suggest putting Gadgetbridge on Google Play as a paid software. 
This will most likely: 

1. Allow Gadgetbridge users to make a small donation (the price in Google Play) in a very easy way.
2. Make Gadgetbridge available to many non-technical users (who don't know how to use F-Droid). This however might backfire in beginner-level questions and even bad reviews (e.g. "says that I need to install something called firmware on my Mi Band, does not work"). 

There are some projects that are already using this approach. I assume that one of the most popular is BetterBatteryStats ([Google Play link](https://play.google.com/store/apps/details?id=com.asksven.betterbatterystats), [XDA Developers forum link with free downloads](https://forum.xda-developers.com/showthread.php?t=1179809)).

**Comment by IzzySoft** [comment]
That's already discussed in #480 (which you might have missed). Please see there for details :wink:

**Comment by cpfeiffer** [comment]
Thanks for the suggestion, and thanks @IzzySoft for referencing the existing ticket :-)
