### ISSUE TITLE
[Feature Request] Ask disabling battery optimizations at first launch

### ISSUE THREAD

**Issue by ardaozkal** [Freeyourgadget/Gadgetbridge#763]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*

On Android devices over 6.0, battery optimizations kill the app when screen is locked. This can be disabled manually, or the app can request it ([see this stack question for how](https://stackoverflow.com/questions/31154128/set-specific-app-to-ignore-optimization-by-code-in-android-m)).

The option to disable it manually is hidden pretty deeply in android settings:

![screenshot_2017-08-13-17-27-46](https://user-images.githubusercontent.com/6755762/29250623-570714ee-804e-11e7-991c-1f7de1e2f9f1.png)

I think that asking user to disable at first launch would be a good option, because as seen above, it is pretty easy to miss, and as it can be pretty annoying to have the app get killed everytime the phone is locked.

#### Your wearable device is:

*Please specify model and firmware version if possible*

Pebble Time, v4.3.

#### Your android version is:
6.0 (EMUI 4.1.2)

#### Your Gadgetbridge version is:
0.19.4 (F-Droid version)

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
Here on Android 7.1.2 it does not happen, maybe on EMUI only?
And can you confirm it does not happen with battery optimization disabled?

**Comment by ardaozkal** [comment]
> Here on Android 7.1.2 it does not happen, maybe on EMUI only?
Not sure, possibly. The OS kills a ton of stuff randomly.

> And can you confirm it does not happen with battery optimization disabled?
I had the app get killed continuously without it disabled, but I'll test again.

**Comment by ardaozkal** [comment]
Very weirdly, I CNR. Closing this issue, sorry.
