### ISSUE TITLE
Enable Bluetooth Connection Status for Tasker Automation

### ISSUE THREAD

**Issue by clyso** [Freeyourgadget/Gadgetbridge#764]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I would like to do following:
Whenever my Phone is connected to Pebble Time I want to enable "Do Not Disturb" so that the Phone does not make any sounds while receiving a call, notification, etc. When the Pebble gets disconnected from the Phone I want to disable "Do Not Disturb" again so I can hear when I received a call, etc.
To achieve this I wanted to use Tasker. In Tasker I can enable "Do Not Disturb" while Phone is connected to specific Bluetooth Device. When the Pebble is connected via Gadgetbridge the Bluetooth Settings in the Phone say "not connected". So Tasker cannot "see" that the Phone is connected to the Pebble.
Is there any Possibility to enable Tasker to "see" the connection status?

#### Your wearable device is:

Pebble Time - latest FW (4.3)

#### Your android version is:
latest Lineage OS 14.1
#### Your Gadgetbridge version is:
latest (0.19.4)

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by IzzySoft** [comment]
Related: #742 #744

**Comment by clyso** [comment]
It works if you select the Bluetooth "Address" of the Pebble instead of the "Name" in Tasker (latest version)

**Comment by IzzySoft** [comment]
Good to know – thanks! I might start using that. Now I'd just need a plugin so Tasker can tell GB to send some notification to the Pebble ;)
