### ISSUE TITLE
Mi Band 2 “not connected” After Firmware Downgrade

### ISSUE THREAD

**Issue by aryayush** [Freeyourgadget/Gadgetbridge#772]
#### Before opening an issue please confirm the following:
- [Y] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [Y] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [Y] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
The heart rate sensor on my brand new Mi Band 2 simply would not work, so I was following the instructions on [this XDA thread](https://forum.xda-developers.com/general/accessories/miband2-hr-measurement-update-downgrade-t3546342) to downgrade its firmware in order to fix it. I unpaired the band from Mi Fit, uninstalled it, installed Gadgetbridge and flashed “Mili_pro_53.fw” to get it onto the older firmware. This went smoothly—the HR sensor was now working fine and the band was connected to Gadgetbridge. I should have stopped there.

However, the linked instructions said that I should flash “Mili_pro 2.2.1.fw” next, so that is what I did. After the firmware installation, the band and its HR sensor are still working fine, but it showing up in Gadgetbridge as “not connected”. It is also showing up in the Bluetooth settings screen as unpaired.

I have tried tapping on it in Gadgetbridge to get it to connect, re-pairing and deleting it, but none of it has worked. Uninstalling Gadgetbridge and installing Mi Fit 2.2.1 and trying to pair it with it is also failing. The band simply won’t vibrate when on the pairing screen. I’ve uninstalled Mi Fit and reinstalled Gadgetbridge and it still says the band is not connected.

Is there any way for me to get out of this mess? If I could just get the Mi Band 2 to fully disconnect from my phone and pair it with it again, it should work, but how do I go about achieving that? Please help.

#### Your wearable device is:
Xiaomi Mi Band 1.0.0.39

#### Your android version is:
6.0.1

#### Your Gadgetbridge version is:
0.19.4

**Comment by cpfeiffer** [comment]
Some hints and things you could try:
- always make sure, that only one of Gadgetbridge Mi Fit is installed, not both.
- there is an option in Gadgetbridge's settings to connect to the band with pariing or without pairing. You should try both.
- try to connect from a different phone or tablet
- make the battery run out, recharge and try again

You can make the battery run out faster by putting it into a freezer (no kidding).
