### ISSUE TITLE
Icon for Changelog in navigation

### ISSUE THREAD

**Issue by mueller-ma** [Freeyourgadget/Gadgetbridge#775]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your FR is:
It looks odd that the changelog entry in the nav drawer doesnt have an icon. I looked for icons and found several that might suit:

- https://github.com/google/material-design-icons/blob/master/communication/ios/ic_chat.imageset/ic_chat_3x.png
- https://github.com/google/material-design-icons/blob/master/editor/svg/production/ic_format_align_justify_48px.svg
- https://github.com/google/material-design-icons/blob/master/editor/svg/design/ic_format_align_left_48px.svg
- https://github.com/google/material-design-icons/blob/master/image/drawable-mdpi/ic_dehaze_black_48dp.png
- https://github.com/google/material-design-icons/blob/master/action/1x_web/ic_assignment_black_48dp.png

#### Your Gadgetbridge version is:
0.20.0

**Comment by danielegobbetti** [comment]
Thanks for the proposals... I am unsure if they could be understood at first sight though (the "chat" one is the one I prefer, but it misses the "what's new" vibe, at least in my opinion).

I couldn't find something better though, perhaps you have some ideas / proposals that convey this meaning?

**Comment by ashimokawa** [comment]
@danielegobbetti 
how about the one liberario uses?

https://github.com/grote/Transportr/blob/master/res/drawable/ic_action_changelog.xml

I did not check the license yet

**Comment by danielegobbetti** [comment]
How about this one?
https://thenounproject.com/term/change/975525/

**Comment by mueller-ma** [comment]
Doesnt look very material IMO
