### ISSUE TITLE
Pebble Time

### ISSUE THREAD

**Issue by zackp30** [Freeyourgadget/Gadgetbridge#78]
Sorry to be that guy but:

I'm aware of the Pebble Time will be available for preorder tomorrow, and was curious if you knew if gadgetbridge ewould require an update at all for the new watch. I hope to get one soon and was also wondering that, if it does need updates, you want me to test the update out if you don't want a Time.

**Comment by ashimokawa** [comment]
duplicate of #24 ? 

You should read that, and feel invited to test. ;)

**Comment by zackp30** [comment]
ah, sorry, somehow I didn't see that. Thanks!
