### ISSUE TITLE
Application language

### ISSUE THREAD

**Issue by ecneb85** [Freeyourgadget/Gadgetbridge#787]
#### Before opening an issue please confirm the following:
- [x ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Application language changes to phone language when phone is rotated.
Steps to reproduce:
1. Choose some language which differs from phone language in GB application.
2. Rotate phone from portrait to landscape

#### Your android version is:
7.0 (Samsung S6)
#### Your Gadgetbridge version is:
0.20.1
------------------------------------------------------------
**Possible solution:**

You can make class which extends Application. 
There you can override one method which gets called everytime you change configuration (example when screen orientation gets changed).
Something like:
```
public class MyApplication extends Application {
     @Override
     public void onConfigurationChanged(Configuration newConfig) {         
                  super.onConfigurationChanged(newConfig);
                  setLocale();}
      private void setLocale() {
                     Locale locale = new Locale("fa_IR");         
                     Locale.setDefault(locale);         
                     Configuration config = new Configuration();         
                     config.locale = locale;         
                      getBaseContext().getResources().updateConfiguration(config,               
                             getBaseContext().getResources().getDisplayMetrics());     
       } 
}
```
And dont forget to declare it in the manifest: 
`example of Application classIn AndroidManifest.xml:<application     android:name="com.blaablaa.bumbam.MyApplication"     ...`

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
Yes I also noticed that problem.
I think it arised after changes from @cpfeiffer in 12f9386fac93b947c9e32a1e3908e40813cc7a2e
