### ISSUE TITLE
messaging menu only partially translated on pebble

### ISSUE THREAD

**Issue by fajabird** [Freeyourgadget/Gadgetbridge#789]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I have installed my pebble 2 hr via the latest (0.20.2) gadgetbridge app including firmware and german language pack from scratch (may be not relevant). When I receive a message on my pebble (e.g. signal / email / sms) and enter the context menu on the pebble (e.g. to replay to this message) I have noticed that only part of it is translated (see screenshots).

Steps to reproduce:
1. factory reset pebble 2 hr
2. pair pebble to phone using gadgetbridge
3. flash firmware
4. flash language pack
5. send message to phone (e.g. signal)
6. upon receiving the notification on the pebble open context menu (e.g. in order to reply)

#### Your wearable device is:

Pebble 2 HR with 
firmware: Pebble-4.3-silk.pbz
german language pack: Vzq58DE-de_DE.pbl

#### Your android version is:
7.1.2 (linageos)

#### Your Gadgetbridge version is:
0.20.2

**Comment by fajabird** [comment]
![img_20170901_132751](https://user-images.githubusercontent.com/1955116/29968838-c6ea29ee-8f1d-11e7-8e76-46401f8e74c5.jpg)
![img_20170901_132804](https://user-images.githubusercontent.com/1955116/29968839-c883c24c-8f1d-11e7-8033-cb94884195de.jpg)

**Comment by fajabird** [comment]
![44968](https://user-images.githubusercontent.com/1955116/29969395-3b7f9486-8f20-11e7-8581-833cfac04aa2.jpg)
![44969](https://user-images.githubusercontent.com/1955116/29969400-3e0692cc-8f20-11e7-8de0-b5c6362af201.jpg)

**Comment by ashimokawa** [comment]
@fajabird 
True, we always send "Mute" and "Reply" strings to the pebble, these come from us, the rest from the German language pack in the firmware. 

There is one reason I did not do that yet. The firmware on the watch is in english but I use Gadgetbridge in German. In that case it would be mixed for me ;)
