### ISSUE TITLE
Gadgetbridge crashes on screenshot on Android 8.0

### ISSUE THREAD

**Issue by anmith** [Freeyourgadget/Gadgetbridge#790]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
When trying to take a screenshot of the Pebble using Gadgetbridge, the app crashes

This must have been introduced with one ot the latest updates, with 0.19.4 which I have been using for quite some time, the app didn't crash

#### Your wearable device is:
Pebble 2

#### Your android version is:
8.0.0

#### Your Gadgetbridge version is:
0.20.2

**Comment by danielegobbetti** [comment]
Were you already on android 8 the last time the function was working?

**Comment by cpfeiffer** [comment]
If you can, please provide a logcat, which should contain a stacktrace (unless someone ignored exceptions).

**Comment by anmith** [comment]
@danielegobbetti 
Checked the screenshots still on the device: they are from August 21, so it should have been Android 7.1.2

While looking to the folder I noticed Gadgetbridge is taking & saving the screenshot before crashing.

@cpfeiffer 
You're not talking about the internal Gadgetbridge log function? Google pointed me to https://developer.android.com/studio/command-line/logcat.html when searching for "logcat". Is this right?

**Comment by cpfeiffer** [comment]
@anmith Sorry for being terse. You can either post a Gadgetbridge logfile (see https://github.com/Freeyourgadget/Gadgetbridge/wiki/Log-Files), or the output of the logcat command that you found via Google.

**Comment by danielegobbetti** [comment]
If the file is saved, it's possibly a crash when accessing the bitmap to create the sharing notification. It could be Oreo needs some changes. A log would be most useful, but please try if gadgetbridge also crashes if you create a notification from the debug menu. Thanks!

**Comment by ashimokawa** [comment]
I can confirm this using the pebble emulator and android emulator running oreo.

**Comment by ashimokawa** [comment]
09-03 13:39:52.223 15488-16751/nodomain.freeyourgadget.gadgetbridge E/nodomain.freeyourgadget.gadgetbridge.LoggingExceptionHandler: Uncaught exception: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/screenshot_20170903-013952.bmp exposed beyond app through ClipData.Item.getUri()android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/nodomain.freeyourgadget.gadgetbridge/files/screenshot_20170903-013952.bmp exposed beyond app through ClipData.Item.getUri()

**Comment by ashimokawa** [comment]
This seems to be a possible fix:

https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by anmith** [comment]
@danielegobbetti, @ashimokawa 
Wow, you guys are really fast - solved the problem while I was enoying a sunny sunday afternoon! :-)

Did try the test notification, no crash.

Thanks for the incredible work!

**Comment by ashimokawa** [comment]
@anmith 
As long as we can reproduce we are fast! ;)
