### ISSUE TITLE
Gadgetbridge get killed because of RuntimeException

### ISSUE THREAD

**Issue by azuwis** [Freeyourgadget/Gadgetbridge#794]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Gadgetbridge get killed because of RuntimeException, logs:

    09-04 08:08:50.181  4326  4326 E AndroidRuntime: FATAL EXCEPTION: main
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: Process: nodomain.freeyourgadget.gadgetbridge, PID: 4326
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: java.lang.RuntimeException: Unable to start service nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService@2213d62 with Intent { act=nodomain.freeyourgadget.gadgetbridge.devices.action.settime cmp=nodomain.freeyourgadget.gadgetbridge/.service.DeviceCommunicationService }: java.lang.IllegalStateException: This builder had already been queued. You must not reuse it.
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3368)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: Caused by: java.lang.IllegalStateException: This builder had already been queued. You must not reuse it.
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at nodomain.freeyourgadget.gadgetbridge.service.btle.TransactionBuilder.queue(TransactionBuilder.java:104)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at nodomain.freeyourgadget.gadgetbridge.service.devices.miband2.MiBand2Support.onSetTime(MiBand2Support.java:557)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at nodomain.freeyourgadget.gadgetbridge.service.ServiceDeviceSupport.onSetTime(ServiceDeviceSupport.java:165)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService.onStartCommand(DeviceCommunicationService.java:444)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3351)
    09-04 08:08:50.181  4326  4326 E AndroidRuntime: 	... 8 more

After this, bluetooth is disconnected, and never reconnect again, like https://github.com/Freeyourgadget/Gadgetbridge/issues/564

#### Your wearable device is:
Amazfit Bip, firmware 0.0.7.90

#### Your android version is:
Android 7.1.2, LineageOS 14.1

#### Your Gadgetbridge version is:
0.20.2-22-gcfc31069 (git describe --tags)

**Comment by ashimokawa** [comment]
@azuwis 
Can you reproduce this, or does this happen randomly?

**Comment by cpfeiffer** [comment]
Thanks a lot for your report! Strange that this never occurred before.

**Comment by azuwis** [comment]
@ashimokawa Happen randomly.

After disabling `Sync time` in settings, it didn't happen in 24 hours.

I'll try the version in git head, and report later.
