### ISSUE TITLE
Long message(> 44 bytes) make amazfit bip disconnect on firmware 0.0.8.74

### ISSUE THREAD

**Issue by azuwis** [Freeyourgadget/Gadgetbridge#797]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
After upgrade firmware from 0.0.7.90 to 0.0.8.74, long message does not work, step to reproduce:

1) Upgrade firmware to 0.0.8.74
2) Connect Amazfit Bip
3) Send message with length longer than 15 chars from debug menu(will make total message length > 44 bytes)
4) The message does not appear on the wearable, after several seconds, bluetooth disconnect and reconnect

If change `profile.setMaxLength(255)` to `profile.setMaxLength(44)` in file AmazfitBipSupport.java, the problem does not happen, but this make the wearable rarely useful.

Tried firmware 0.0.7.90/0.0.8.10/0.0.8.20/0.0.8.32/0.0.8.74, only 0.0.7.90 and 0.0.8.10 worked with long message.

PS: Is there a way to downgrade firmware to 0.0.7.90?

Logs:

    09-06 10:04:37.610 17650 17650 D nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
    09-06 10:04:37.613 17650 17650 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: about to add: 10:04:37: Transaction task: new notification with 1 actions
    09-06 10:04:37.615 17650 19502 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: About to run action: September 6, 10:04: WriteAction on characteristic: 00002a46-0000-1000-8000-00805f9b34fb
    09-06 10:04:37.618 17650 19502 D nodomain.freeyourgadget.gadgetbridge.service.btle.actions.WriteAction: writing to characteristic: 00002a46-0000-1000-8000-00805f9b34fb: 0xfa 0x 1 0x b 0x54 0x65 0x73 0x74 0x35 0x35 0x35 0x32 0x35 0x35 0x32 0x35 0x35 0x35 0x35 0x35 0x36 0x35 0x35 0x35 0x36 0x35 0x35 0x35 0x 0 0x54 0x65 0x73 0x74 0x35 0x35 0x35 0x32 0x35 0x35 0x32 0x35 0x35 0x35 0x35 0x35 0x36 0x35 0x35 0x35
    09-06 10:05:07.630 17650 19572 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic write: 00002a46-0000-1000-8000-00805f9b34fb (failed: 133)
    09-06 10:05:07.634 17650 19572 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: failed btle action, aborting transaction: 00002a46-0000-1000-8000-00805f9b34fb (failed: 133)
    09-06 10:05:07.648 17650 17664 D BluetoothGatt: onClientConnectionState() - status=22 clientIf=5 device=XX:XX:XX:XX:XX
    09-06 10:05:07.650 17650 17664 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state change, newState: 0 (failed: 22)
    09-06 10:05:07.650 17650 17664 W nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state event with error status 22
    09-06 10:05:07.651 17650 17664 I nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Disconnected from GATT server.
    09-06 10:05:07.651 17650 17664 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: handleDisconnected: 22
    09-06 10:05:07.652 17650 17664 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: internal gatt callback set to null
    09-06 10:05:07.652 17650 17664 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: new device connection state: NOT_CONNECTED
    09-06 10:05:07.653 17650 17664 I nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Enabling automatic ble reconnect...
    09-06 10:05:07.665 17650 17664 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: new device connection state: WAITING_FOR_RECONNECT
    09-06 10:05:07.985 17650 17650 I nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
    09-06 10:05:08.203 17650 17650 I nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Setting broadcast receivers to: true
    09-06 10:05:10.433 17650 17650 I nodomain.freeyourgadget.gadgetbridge.externalevents.BluetoothConnectReceiver: got connection attempt
    09-06 10:05:10.434 17650 17650 I nodomain.freeyourgadget.gadgetbridge.externalevents.BluetoothConnectReceiver: will connect to Amazfit Bip Watch
    09-06 10:05:10.435 17650 17664 D BluetoothGatt: onClientConnectionState() - status=0 clientIf=5 device=XX:XX:XX:XX:XX
    09-06 10:05:10.435 17650 17664 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: connection state change, newState: 2 (success)
    09-06 10:05:10.436 17650 17664 I nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: Connected to GATT server.
    09-06 10:05:10.436 17650 17664 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: new device connection state: CONNECTED

#### Your wearable device is:
Amazfit Bip, firmware 0.0.8.74

#### Your android version is:
Android 7.1.2, Linageos 14.1

#### Your Gadgetbridge version is:
0.21.0 (git describe --tags)

**Comment by ashimokawa** [comment]
@azuwis 
I cannot reproduce the problem, it seems to work here.

Also there is no way to downgrade to 0.0.7.90 as there is no such firmware file.

You can try to call requestMTU(512) - I did that in some local branch and the bip set the mtu to 256 then. I did not use the code in the end because the bip always seems to have set the mtu to 256 anyway (net payload 253).

please try if it helps to use requestMTU() and report back!

https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#requestMtu(int)

**Comment by azuwis** [comment]
@ashimokawa How do I call the requestMTU()? I'm not familiar with Bluetooth coding, or Android coding at all.

**Comment by azuwis** [comment]
Tried using version from FDroid, clearing data of com.android.bluetooth, turning off/on bluetooth, rebooting phone. No luck, the problem always reproducible for me.

My Phone is Xiaomi Mi 4C (libra).

I didn't upgrade gps firmware, since the version is the same. But I don't think it's related to the problem.

**Comment by azuwis** [comment]
I believe it's a hardware related problem, after trying Mi Fit app, long message also make Mi Fit app disconnecting.

@ashimokawa Do you upgrade the firmware using Mi Fit or Gadgetbridge?

**Comment by ashimokawa** [comment]
@azuwis 
I updated with Gadgetbridge and never ran Mi Fit. I did two updates. First to .74 and today to .88 without problems.

V0.0.8.88 is said to be distributed via Mi Fit OTA. That also means the .fw and .res files are not in any apk.

**Comment by azuwis** [comment]
Tried using Gadgetbridge with Nexus 4, which worked with long message. So it seems to be a capability problem.

@ashimokawa Where can I find the 0.0.8.88 firmware? I'd like to try.

**Comment by ashimokawa** [comment]
@azuwis 
Sorry I don't think is legal to redistribute the firmware and I do not know a download location for the untranslated firmware,,,

**Comment by ashimokawa** [comment]
@azuwis 
Mifit 3.0.7 is out , including the .88 firmware - now you can get it ;)

**Comment by azuwis** [comment]
@ashimokawa Thanks for the info, but I've already return the device. I'll just close this issue, it seems nobody else encountered the some problem here.
