### ISSUE TITLE
Call notification not removed on hangup

### ISSUE THREAD

**Issue by shtrom** [Freeyourgadget/Gadgetbridge#799]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
When the phone rings, a notification is pushed to the watch. When picking up, the notification starts counting the time. ✅ 

When hanging up, the notification stays up on the watch, and keeps counting the time until I dismiss it. ❌ 

#### Your wearable device is:
Pebble Steel, FW 3.12.3

#### Your android version is:
LineageOS 14, Android 7.1.2

#### Your Gadgetbridge version is:
0.20.2

**Comment by ashimokawa** [comment]
@shtrom 
This was reported before IIRC.
I am using Lineage 14.1 myself and it works here.
Does this happen every time?

**Comment by shtrom** [comment]
Ah, didn't find any prior bug. Yeah, it happens consistently.

**Comment by ashimokawa** [comment]
Sorry it was a similar issue, the opposite of your problem #756 

I really have no idea why this can happen, as I wrote on the other issue, we do not rely on notifications but track the phone state. 

You report that if you take the call it works, if you hangup not. This is very weird, I have no idea why we can detect the one and not the other.

Did you accept all runtime permissions for Gadgetbridge?

**Comment by danielegobbetti** [comment]
Few questions:
1. Is gadgetbridge still connected when you hang up? 
1. Are you on a "normal" phone call issued through the system dialer?
1. Are you using a BT headset (could be related to 1.)?

**Comment by shtrom** [comment]
On Fri 08 Sep 2017 at 12:06:59 +0000, Andreas Shimokawa wrote:
> You report that if you take the call it works, if you hangup not. This is very weird, I have no idea why we can detect the one and not the other.

It starts counting the time, yeah. Then it doesn't stop (:

> Did you accept all runtime permissions for Gadgetbridge?

I just checked, and yes: both the normal App permissions (Telephone is
granted), as well as in Privacy Guard (Read call log, and Call phone are
both unconditionally allowed; though it reckons they were Never used).
Oh, and Privacy guard is actually disabled for Gadgetbridge anyway.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by shtrom** [comment]
On Fri 08 Sep 2017 at 13:23:00 +0000, Daniele Gobbetti wrote:
> 1. Is gadgetbridge still connected when you hang up? 

Yes.

> 1. Are you on a "normal" phone call issued through the system dialer?

Yes. Received from the mobile network.

HA! That said, I have the FRITZ!Fon app running, which hooks into the
system dialer to hook my phone into my home router's SIP system.

I'll do a quick trial with that app off.

> 1. Are you using a BT headset (could be related to 1.)?

I have one paired, but not used nor in range.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by shtrom** [comment]
> HA! That said, I have the FRITZ!Fon app running, which hooks into the system dialer to hook my phone into my home router's SIP system. I'll do a quick trial with that app off.

Ok, I did a few trials, and got more interesting results.
1. It doesn't matter whether the FRITZ!Fon app is on or (completely) off
2. It doesn't matter whether the other party or I hang up: the notification stays on and counting
3. In one case, i picked up (perhaps too quickly), and the watch kept notifying that somebody was ringing and vibrating, rather than than showing the time elapsed on the call

Here's a logcat of my trials (I did 4 or 5 trials, so it's best read from the end).

[gadgetbridge_call_notification_logcat.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/1289704/gadgetbridge_call_notification_logcat.txt)

**Comment by danielegobbetti** [comment]
It is most definitely a permission problem, this is what happens on my phone when it rings and I refuse the call:
```
nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.callstate
nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener: Ignoring notification, is a system event
nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener: Ignoring notification, is a system event
nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener: Ignoring notification, is a system event
nodomain.freeyourgadget.gadgetbridge D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService: Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.callstate
nodomain.freeyourgadget.gadgetbridge I/nodomain.freeyourgadget.gadgetbridge.externalevents.NotificationListener: Ignoring notification, is a system event
```

In your log instead this happens:
```
nodomain.freeyourgadget.gadgetbridge/u0a88} (pid=3250, uid=10088) requires android.permission.READ_PRIVILEGED_PHONE_STATE due to sender android (uid 1000)
D/nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationService( 3250): Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.callstate
```

I am on android 7.1.2 as well (AOSP, though) so I guess it's either some kind of Lineage OS oddity, or it depends on the fact that I had installed Gadgetbridge before upgrading to 7.1.2 and it has inherited old permissions...

**Comment by ashimokawa** [comment]
Strange thing is I also get the same permission denied message on Lineage - but it works anyway!

**Comment by danielegobbetti** [comment]
I suspect the intent we get might be partial or altered by some privacy setting. Are you both using official releases of lineage? I guess unofficial builds might behave differently...

**Comment by shtrom** [comment]
A nightly from 2017-08-22. I checked the permissions, and can't see anything obvious. I disabled then re-enabled the standard telephone permission, we'll see.

**Comment by cpfeiffer** [comment]
Does this still happen?

**Comment by shtrom** [comment]
I'm not in a position to test this at the moment, but I've seen a few updates of GadgetBridge. I should be able to check in a couple of weeks.
-- 
Olivier Mehani <shtrom@ssji.net>
Sent from my mobile, please excuse my brevity.

**Comment by shtrom** [comment]
Yup, this still happens with GB 0.21.6

**Comment by danielegobbetti** [comment]
Is there a difference if you answer the call by swiping in the "real" phone application versus accepting the call from the notification?

**Comment by shtrom** [comment]
Hum, I can only accept the call from the real application (full screen notification with contact name and picture). The watch notification only allows to hang up without answering.

**Comment by danielegobbetti** [comment]
I meant the android notification that appears when you're doing something else on the phone and receive a call

**Comment by shtrom** [comment]
Yup, same from the Android notification: the notification on the watch doesn't clear after hanging up; also, when picking up too quick, the watch keeps vibrating and notifying of an incoming call.

This is with 0.21.6.

**Comment by lennartgoosens** [comment]
Experiencing exactly the same problem with Gadgetbridge 0.26.1 and an original Pebble v1_5 (the one with screws on the back, running Firmware v3.12.3) on LineageOS 14.1-20180419-NIGHTLY-i9100 (Android 7.1.2). In other words: everything is the newest of the newest, except the hardware.

Connected through Bluetooth, not Bluetooth LE as far as I can tell. I tried switching on "Use for: Contact sharing" in under Bluetooth > Paired devices, but it made no difference whatsoever.

As far as I can see from Settings > Apps > GadgetBridge >Permissions, the app has every permission it could wish for. Interestingly, I always have to manually connect to the Pebble every time I reboot my phone. Could this be a related issue?

**Comment by shtrom** [comment]
Ha! I can confirm this fixed my issue! Cheers!
