### ISSUE TITLE
k9mail header/body mixup

### ISSUE THREAD

**Issue by asmw** [Freeyourgadget/Gadgetbridge#8]
I received two mail notifications from different addresses, but on my pebble the same sender was shown.

The mails were all pulled from my server after my quiet time was over in the morning, so the notifications appeared very close to each other.

Might be a similar issue to the other k9-related bug.

**Comment by ashimokawa** [comment]
Thanks for reporting, should be fixed.

**Comment by asmw** [comment]
Thanks for the quick fix
