### ISSUE TITLE
Rotating android device brings gadgetbridge to foreground

### ISSUE THREAD

**Issue by danielegobbetti** [Freeyourgadget/Gadgetbridge#802]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Since a few days rotating the android device brings gadgetbridge to foreground, no matter what the currently running application is.
It might be related to the language switcher thing. I suggest we get rid of this functionality.

#### Your wearable device is:

N/A

#### Your android version is:

7.1.2

#### Your Gadgetbridge version is:

Current master

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
I suspect 699c17624a428f51825eb93d8b10c805cd910f59
