### ISSUE TITLE
How to download old version

### ISSUE THREAD

**Issue by kowalski215** [Freeyourgadget/Gadgetbridge#804]
Hi everyone.
I've just installed the newest version of gadgetbridge for my zeblaze plus but I still have the problem which I submitted few months ago: the wearable doesn't re-connect when first goes out of range (so calls are not notified on Zeblaze).
Is it possible to have the apk for version 0.18.5 (which was the last one working). I've deleted it from my smartphone and I'm not able to get it back anymore. Thanks again for your work

g

**Comment by mueller-ma** [comment]
You can download old builds from fdroid

**Comment by IzzySoft** [comment]
@mueller-ma have fun finding that special version, which meanwhile has been moved to the archive :)

v0.18.5 should be this one: https://f-droid.org/archive/nodomain.freeyourgadget.gadgetbridge_92.apk

**Comment by kowalski215** [comment]
Thanks @mueller-ma anywhay for your help :)
@IzzySoft thanks for the dl link! Awesome

**Comment by IzzySoft** [comment]
@kowalski215 glad to help :wink:
