### ISSUE TITLE
Adapt activity graph to different sample intervals

### ISSUE THREAD

**Issue by protomors** [Freeyourgadget/Gadgetbridge#808]
It is related to https://github.com/Freeyourgadget/Gadgetbridge/issues/301 but instead of complete overhaul I need only one change in activity graph. The problem is that now it is optimized for devices like Mi Band that store activity data for each individual minute. But now I am working on support for device NO.1 F1 that stores step count for each hour and sleep data are separated by 15 minutes intervals. And now it looks like this on activity graph
![screenshot_20170909-215607](https://user-images.githubusercontent.com/2123101/30243249-67c451c8-95ae-11e7-9d70-2ab9699e7ee5.png)
This thin lines are hard to see on a phone screen. Would look nicer if they were as wide as interval between samples. Than it will look more like bar graph which is appropriate for this device.

I probably could change this myself but am not sure about best way to make it generalized to work with any interval.

**Comment by protomors** [comment]
I looked into the code and found where bar width is set. It is in the file AbstractChartFragment.java
`barData.setBarWidth(200f);`
When I change parameter to "3000f" steps data looks just like I want. But sleep data starts to overlap because it has different interval.
![screenshot_20170909-224630](https://user-images.githubusercontent.com/2123101/30243447-361eb498-95b2-11e7-9ce7-a98f647decff.png)
Is there even a way to set different width for each sample it this chart library? Maybe what I want is impossible to implement right now,

**Comment by cpfeiffer** [comment]
Yeah, this is going to be tricky. Maybe we have to think about whether we really want a bar chart here.

We could use a line chart, filled with the activity colors below the line. Not sure if we can persuade mpandroidchart to do that.

Or, we need to configure (or patch?) mpandroidchart to create bars of different widths, possibly even without any space between them.

**Comment by protomors** [comment]
Another (a little hackish) way to achieve this would be to draw a needed number of 1 minute bars with the same height for each sample.

**Comment by dandamdan** [comment]
You could use smaller intervals for the activities. Maybe use the step-counter 4 times in a row and simulate 15-minute intervals and then increase the bar-width.
That way you would have and evenly distributed amount of bars and you could use a single bar-width.

I havent looked much into your code now maybe this is possible.

**Comment by danielegobbetti** [comment]
I believe the barchart could be swapped with a linechart, at that point the effect would be similar to what @protomors wants to achieve. 
It is not an immediate change, but that way we could also achieve an effect similar to https://github.com/PhilJay/MPAndroidChart/issues/1922

**Comment by protomors** [comment]
@danielegobbetti Thank you. I will try it out soon.
