### ISSUE TITLE
Allow Automatic Notification Colors on Pebble

### ISSUE THREAD

**Issue by KazWolfe** [Freeyourgadget/Gadgetbridge#815]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:

Related to #120. The Pebble native firmware/app will tailor the background color of notifications by the app color, failing back to red if one can't be found. See an example from Discord:

![Pebble Demo](https://user-images.githubusercontent.com/5192145/30411700-72da2256-98c7-11e7-871f-eb4ebbe0aa1d.png)

Note that the Pebble Time (running from the native Android Pebble app) has a light blue app from Discord, while the Gadgetbridge version has the generic red color.

It appears though that the Pebble client has method to get the app icon for each app posting notifications. From this, it pulls the dominant icon color and then uses that in the background.

It would be nice if Pebble devices through Gadgetbridge integrated the same behavior - namely, allowing all apps to use custom background colors unless a manual color already exists for the app. If the icon color can't be retrieved, the system can use the generic red.

#### Your wearable device is:

Pebble Time (`snowy`), version 4.3. Applies to all Pebble Times

*Please specify model and firmware version if possible*

#### Your android version is:

Android 7.0.0

#### Your Gadgetbridge version is:

v0.20.0

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
@KazWolfe 
Thanks! I was not aware of this feature since I never used the official app.

I also edited your text and removed the reference to the "class" file. If we implement that we have to be legally safe and do that on our own and not look at the pebble (compliled) class file.

**Comment by KazWolfe** [comment]
Noted, my bad.

Either way, still a cool feature to implement.

**Comment by danielegobbetti** [comment]
I found [this](https://stackoverflow.com/questions/17985500/how-can-i-get-the-applications-icon-from-the-package-name) to get the icon from the package name and [this](https://stackoverflow.com/questions/8471236/finding-the-dominant-color-of-an-image-in-an-android-drawable) to extract the dominant color from a drawable.

**Comment by KazWolfe** [comment]
Alright, sweet!

I'd guess the next part would be convert whatever RGB value we get into the
closest six bit color that the Pebble can display.

I'm not sure what Pebble did, but something like this looks promising:
https://forums.pebble.com/t/closest-color-tool/14114

There's also an online implementation of something similar here:
http://computingvoyage.com/982/color-bit-depth-reducer/

I guess we can try sticking in known app icons and seeing what the result
is (and if it matches).

I'm not sure how the Pebble dealt with cases where solid black or white
were the dominant color. I'll see if I can do some tests on my own watch,
unless someone else wants to.

**Comment by ashimokawa** [comment]
@KazWolfe 
FYI, pebble uses a linear RGB222 palette (64 colors), it can be converted quite easily without using the constants we have. Black and white should also be an option - why not.

Also no one of us uses any proprietary apps, so please go ahead with testing the official pebble app ;)

**Comment by KazWolfe** [comment]
From my tests, it looks like the flow is the following from the official pebble app:

1. Get the icon from the app that sent the notification.
2. Extract the primary color from the app - it *looks* like Pebble is using the Swatch method that @danielegobbetti mentioned. I think it's pulling the vibrant color, but I haven't been able to prove this just yet.
3. Convert the vibrant color to a Pebble color code, and send to the app.

If it can't get the icon in step 1, it uses `PebbleColor.IslamicGreen` (the default for SMS - this should probably be fixed in the `NotificationType` code, but eh. This is actually the same behavior you have on iOS if I remember correctly from my iOS days.

If it can't get a vibrant color in step 3, it will instead substitute in that generic red. I'm not sure if this is a hardcoded value or the app pulls it from somewhere though.

**Comment by KazWolfe** [comment]
Commited to my own fork - it seems to work great:

![image](https://user-images.githubusercontent.com/5192145/30466441-b360c692-9992-11e7-81ab-b379a599fb41.png)

Tests added, and the implementation seems to be healthy enough to work without noticeable delay or lag.

Implementation is as below:

1. Get notification, and check if it belongs to a known custom app. If so, use custom app settings.
2. Grab app icon, and grab primary vibrant color. Convert to RGB222, and use for notification. 
2.1. If icon could not be retrieved, use SMS default. (Decision made as per tests with Pebble)
2.2. If primary color could not be retrieved, `#AA0000` (`PebbleColor.DarkAppleCandyRed`) is used (as per Pebble tests).

I was thinking of making it so "generic" icons would inherit colors as well (using the default when one could not be guessed), but we have no way of telling the type of app (yet) so this doesn't seem like the best idea at the moment. Good thing to keep in mind for the future, though.
