### ISSUE TITLE
Mi Band 2: Firmware update notification doesn't get dismissed

### ISSUE THREAD

**Issue by joserebelo** [Freeyourgadget/Gadgetbridge#821]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
The "Firmware update in progress" notification doesn't get dismissed when the process ends, have to force close Gadgetbridge to dismiss it (both on success and failure).

Related to #271, but it is a bug / bit more pressing problem. Couldn't capture logs, can do it if needed.

#### Your wearable device is:
Mi Band 2
FW: 1.0.1.53
HW: V0.1.3.2

#### Your android version is:
7.1.2

#### Your Gadgetbridge version is:
Built from latest master, 6ec1555

**Comment by ashimokawa** [comment]
Confirmed with Amazfit Bip for the main firmware. Other flashable binaries (gps/res/cep/alm) not affected

**Comment by joserebelo** [comment]
The notification doesn't get dismissed [when a firmware was installed and the band is rebooted](https://github.com/Freeyourgadget/Gadgetbridge/blob/c91e14f6449a5cbcba3ae146997c524e9b0e986b/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/operations/UpdateFirmwareOperation.java#L137), and we might not be receiving the `MiBand2Service.COMMAND_FIRMWARE_REBOOT` notification that would trigger the notification update.

Couldn't we update the install notification anyway when receiving `MiBand2Service.COMMAND_FIRMWARE_CHECKSUM`, or is there any reason to waiting for the reboot notification? Also, the notification should probably be updated in the switch's default / exception catch.

**Comment by cpfeiffer** [comment]
Thanks for the report! We didn't get the change event for the reboot command, because it was sent with a different transaction where we had no listener on.

**Comment by joserebelo** [comment]
@cpfeiffer shouldn't the notification also be marked as not ongoing / the message changed when the update fails? I've had a firmware update fail and the notification got stuck.
