### ISSUE TITLE
Alarms on Bip 

### ISSUE THREAD

**Issue by heartlandzf** [Freeyourgadget/Gadgetbridge#826]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I can see only 3 of my 8 alarms on Amazfit Bip, I can't add others, and it looks like they have been disabled

#### Your wearable device is:
Amazfit Bip on different fw versions 

#### Your android version is:
Nougat

#### Your Gadgetbridge version is:
0.21.1

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by cpfeiffer** [comment]
Yes, we need to fix that. See #462
