### ISSUE TITLE
"unable to find preference key: mi_try_generic_phone, trying the vibration won't work" toast appears twice when opening Mi band / bip settings since 0.21.2

### ISSUE THREAD

**Issue by phunkular** [Freeyourgadget/Gadgetbridge#830]
Mi band 2 / Hw 0.1.3.2 / Fw 1.0.1.39

Miui 9 / Android 6.0.1

I am 90% sure this started on version 0.21.2 of gadgetbridge (if not, 0.21.1)

So recently I have noticed this toast appearing in the miband / bip settings page. I'm not sure what it means or if there's anything actually wrong. The toast flashes twice each time.

Thanks

**Comment by ogbaba** [comment]
I also get this message. i am running miui 8.2, android 7.0 on a MI5

**Comment by thomas-soutif** [comment]
I have this message too, i am running on android 4.4.4

**Comment by ashimokawa** [comment]
This happens for everyone, not critical but annoying.

**Comment by patricia93sousa** [comment]
Same problem with Nexus 5x Android 7.1.1
