### ISSUE TITLE
Amazfit Bip: Auto-switch language on connect

### ISSUE THREAD

**Issue by soyxan** [Freeyourgadget/Gadgetbridge#832]
I am wondering what means this entry on the changelog:

```
Version 0.21.3
Amazfit Bip: Auto-switch language on connect (English, Simplified Chinese, Traditional Chinese), requires FW 0.0.9.14+
```

Does it have any relation with the Amazfit BIP interface being translated to english language (instead of chinese)?

Thanks!

**Comment by ashimokawa** [comment]
Yes.
BIP interface will be in english when you have fw >=0.0.9.14 and connect with Gadgetbridge >=0.21.3

(Unless your phone is set it to Chinese)

**Comment by soyxan** [comment]
After connecting my Amazfit BIP with Mi Fit, the firmware has upgraded to 0.0.8.74. How can I force to update to the last firmware in order to be able to change the language?

**Comment by soyxan** [comment]
I have update Mi Fit to 3.1.0 version and the Amazfit BIP FW was updated to 0.0.9.14. After the update I unlinked from Mi Fit and then linked to Gadgetbrdge and the interface language was changed to English automatically.
The problem is that when I link again with Mi Fit the language is changed to chinese. Is there anyway to avoid this?

**Comment by danielegobbetti** [comment]
You should file a bug to Mifit, if you have problems using Mifit.
