### ISSUE TITLE
Mi Band 2 get notifications with vibration about charging.

### ISSUE THREAD

**Issue by volnes** [Freeyourgadget/Gadgetbridge#841]
#### Your issue is:
Mi Band 2 get messages and vibrate when phone on charge.
Happens every time when battery percentage is up.

#### Your wearable device is:

Mi Band 2
FW: v1.0.1.53
HW: v0.1.3.2

#### Your android version is:
6.0.1
#### Your Gadgetbridge version is:
0.21.5

**Comment by ashimokawa** [comment]
This is not AOSP and not Lineage, right?

You can see in the log which package name this comes from and then blacklist it yourself in gadgetbridge settings.

**Comment by cpfeiffer** [comment]
We would need a log of this, otherwise we don't know how to ignore the notification.
