### ISSUE TITLE
Non generic Email notifications not working with Amazfit Bip

### ISSUE THREAD

**Issue by frizzo99** [Freeyourgadget/Gadgetbridge#844]
Email notifications are not working with my Amazfit Bip.  All other notifications work fine.  Using the Debug option doesn't work as well.  I'm using Gmail and Outlook.

Here is my log:
09:58:02.377 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.21.5
09:58:05.962 [main] WARN  n.f.g.u.GB - Unable to find preference key: mi_try_generic_phone, trying the vibration won't work
09:58:05.965 [main] WARN  n.f.g.u.GB - Unable to find preference key: mi_try_generic_phone, trying the vibration won't work
09:58:05.968 [main] ERROR n.f.g.a.AbstractSettingsActivity - Unknown preference key: mi_vibration_count_generic_phone, unable to display value.
09:58:05.969 [main] ERROR n.f.g.a.AbstractSettingsActivity - Unknown preference key: mi_vibration_count_generic_alarm_clock, unable to display value.
09:58:17.623 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.notification
09:58:17.624 [main] DEBUG n.f.g.s.b.BtLEQueue - about to add: 9:58:17 AM: Transaction task: new notification with 1 actions
09:58:17.626 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - About to run action: October 15, 9:58 AM: WriteAction on characteristic: 00002a46-0000-1000-8000-00805f9b34fb
09:58:17.627 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.a.WriteAction - writing to characteristic: 00002a46-0000-1000-8000-00805f9b34fb: 0xfa 0x 1 0x22 0x 0
09:58:18.337 [Binder:10316_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic write: 00002a46-0000-1000-8000-00805f9b34fb (success)

#### Your android version is:
8.0.0

#### Your Gadgetbridge version is:
0.21.5

BIP FW: 0.0.9.14

**Comment by ashimokawa** [comment]
Confirmed

**Comment by frizzo99** [comment]
You guys are amazing.  I can't believe how fast this was fixed.  When will the updated apk be available?

Thanks!

**Comment by ashimokawa** [comment]
@frizzo99 
We released 0.21.6 - that means we created a tag, now F-Droid will build us.
But we have no influence on the process (could take some days). It is really beyond our control.

**Comment by frizzo99** [comment]
Thanks :)

**Comment by ashimokawa** [comment]
Gadgetbridge 0.21.6 is available now via f-droid

**Comment by frizzo99** [comment]
Thanks

**Comment by frizzo99** [comment]
I tried this version and everything works except Outlook notifications.  It
works in the debug but I don't get notifications when it appears on my
phone.  Gmail works fine.

On Oct 18, 2017 4:45 PM, "Andreas Shimokawa" <notifications@github.com>
wrote:

Gadgetbridge 0.21.6 is available now via f-droid

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Freeyourgadget/Gadgetbridge/issues/844#issuecomment-337722325>,
or mute the thread
