### ISSUE TITLE
Garbage on screen

### ISSUE THREAD

**Issue by legioner0** [Freeyourgadget/Gadgetbridge#845]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
On the activity screen after changing the tab sometimes there is garbage at the top of the screen. Here is example (garbage has small size, so I highlighted it):
![screenshot_2017-10-18-00-31-50-220_nodomain freeyourgadget gadgetbridge](https://user-images.githubusercontent.com/9307340/31683391-18993610-b3a7-11e7-9135-153a0d0b1f28.png)
Sometimes this garbage disappear after less than one second, sometimes it's "stable" as on screenshot

#### Your wearable device is:
Makibes F69

#### Your android version is:
6.0
#### Your Gadgetbridge version is:
0.21.5

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by legioner0** [comment]
Damn! =) I found this "feature" on my Xiaomi Remdi Note4 with latest firmware.

**Comment by danielegobbetti** [comment]
Closing this
