### ISSUE TITLE
No connection to Mi Band 2 after latest firmware update from Mi Fit 3.1.0

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#847]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I felt brave and did a firmware update to the newest firmware shipped with Mi Fit 3.1.0. After the firmware update finished (successsfully), Gadgetbridge wasn't (and still isn't) able to connect again.

Here is a Gadgetbridge log and a BT snoop of the failing connection process:
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1400009/gadgetbridge.log)
[btsnoop_hci.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1400011/btsnoop_hci.log)

#### Your wearable device is:
Mi Band 2, ~~unknown new firmware from Mi Fit 3.1.0~~ firmware 1.0.1.54 from Mi Fit 3.1.0

#### Your android version is:
5.1.1 (CM12.1)

#### Your Gadgetbridge version is:
0.21.6

**EDIT:** See section "Your wearable device is"

**Comment by ashimokawa** [comment]
Try to unpair in Android settings and then repair in gadget bridge (+ icon).

**Comment by 6arms1leg** [comment]
That did the trick, many thanks!
The new FW v. 1.0.1.54 works great – I added my findings to the wiki.
I also tested the FW on other devices and all had this issue. Maybe we should add a note about the solution you provided somewhere in the wiki?

**Comment by ashimokawa** [comment]
That was just from my experience with the Bip after the update that was in the same mifit 3.1.0.

Would be cool if we could automate the process somehow

**Comment by 6arms1leg** [comment]
Yes, to automate the process would certainly be the better solution. I leave it to you then.
Should we reopen this issue or do you want to create a new one (or just keep it in mind without an issue attached to it)?
