### ISSUE TITLE
Cannot set new alarms on Mi Band 2

### ISSUE THREAD

**Issue by MichaelLorenzen** [Freeyourgadget/Gadgetbridge#848]
#### Your issue is:
I managed to delete all alarms on my Mi Band 2: I can't set any new ones with Gadgetbridge because there is no option to do so in the GUI

#### Your wearable device is:
Mi Band 2, FW 1.0.1.50

#### Your android version is:
5.1.1

#### Your Gadgetbridge version is:
0.21.6

**Comment by danielegobbetti** [comment]
The functionality is there, you just have to tap the "alarm clock" icon in the control center.
Please add the description to our wiki (with a screenshot, if possible) to prevent other users having your issue. Thanks!

**Comment by MichaelLorenzen** [comment]
All I See is an empty list without any button to add a new timer:


Am 20. Oktober 2017 12:24:21 MESZ schrieb Daniele Gobbetti <notifications@github.com>:
>The functionality is there, you just have to tap the "alarm clock" icon
>in the control center.
>Please add the description to our wiki (with a screenshot, if possible)
>to prevent other users having your issue. Thanks!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Freeyourgadget/Gadgetbridge/issues/848#issuecomment-338168462

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by danielegobbetti** [comment]
I believe you reserved all three slots for upcoming calendar events? (It's in the general settings page)

**Comment by MichaelLorenzen** [comment]
Yes, I see: If I reduce the reserved slots to 1 there are two timer slots back in control center.

Thanks for pointing this out.

Are there any hints or best practices on how to edit the wiki?
