### ISSUE TITLE
android.text.format.Time is deprecated

### ISSUE THREAD

**Issue by frankFic** [Freeyourgadget/Gadgetbridge#849]
Hi, 

I noticed that the deprecated [android.text.format.Time](https://developer.android.com/reference/android/text/format/Time.html#parse(java.lang.String)) is still in use in [CalendarEvents.java](https://github.com/Freeyourgadget/Gadgetbridge/blob/8cce2d1362f64fc8e6a323284b7dc7a81432643c/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/CalendarEvents.java#L92). Though, you may have already noticed this.
If you would like a pull request, I may try to submit one later.

**Comment by danielegobbetti** [comment]
Don't forget that the app runs on API>=19, so be sure to test on older android if you want to work on this.

**Comment by danielegobbetti** [comment]
Closing this, feel free to issue a PR but mind what I wrote previously. Thanks!
