### ISSUE TITLE
Synchronize system alarms to device

### ISSUE THREAD

**Issue by chrisvella** [Freeyourgadget/Gadgetbridge#85]
I would like to request the ability to synchronize system alarms with device.

I picture it working something like this. Gadgetbridge would detect a change in the system alarms, or check at regular intervals. These values would then be stored in the gadgetbridge database and the next three alarms would be sent to the device. The system time would have to be compared with the device time, and the next three alarms would be updated.

However I see a number of potential issues with the implementation:
* For the miband, if more than three alarms are configured in gadgetbridge over a short amount of time, there should be some way of verifying that the later alarms have been sent to the device, replacing the ones that have passed. It would be good to minimize users not receiving updated alarms on their band, because the device is out of range at the wrong time. Another potential option would be modifying the gadgetbridge notification/creating a new notification, to alert the user alarms are not current.
* Synchronizing of the system time with the device time may have to be forced?

I think the ability to send alarms to the device, and connection with system alarms should be separate. This would be useful if users are sleeping next to someone, and they only want their device to vibrate, rather than the phone and device.

Thanks

**Comment by danielegobbetti** [comment]
I think a way to address this is to allow the user to "reserve" a number of alarms for automatic sync. This means that they would not be configurable using the GB interface. A user could choose how many of the three available alarms to reserve for this feature.

All the problematics you outlined are indeed valid and not trivial to address as well! It seems a simple feature but in fact is pretty complex.

**Comment by ashimokawa** [comment]
I really do not get the point of all this. Why would anyone with a smart wearable with alarm capability want the Phone's alarm to go off also? I mean, that would happen if we synchronize alarms, right?

**Comment by chrisvella** [comment]
@ashimokawa I would like both the band and the phones alarm to go off at the same time because I am a heavy sleeper, and both are more likely to wake me up. The second reason is the phone's alarm acts as a fall over if the band doesn't sync the alarm. I very cautiously use the miband alarm for this reason.

Another potential benefit could be snoozing the phones alarm with the miband/pebble... if that's possible?

**Comment by ashimokawa** [comment]
@chrisvella 
Now I understand ;)
Snoozing from the pebble should be possible if we build that into our own watchapp.
For the MiBand we could do that by temporarily switching to raw acceleration data and analyze that.

**Comment by danielegobbetti** [comment]
Support for Android calendar events has been added with the latest commits on master (not yet released).

Syncing events is much more robust than alarms, because we can get from the Android calendars the events for the next days and overwrite whatever we sent earlier. The user can choose how many alarms slot on the band should be dedicated to Android events, default is none.

I am closing this issue as wontfix, but please feel free to add further comments.

**Comment by chrisvella** [comment]
Thank you for adding this. Seems like an even better implementation than
the original idea.
