### ISSUE TITLE
Outlook Notifications not working with Amazfit Bip

### ISSUE THREAD

**Issue by frizzo99** [Freeyourgadget/Gadgetbridge#851]
Outlook notifications are not working with the Amazfit Bip.  If I use the Debug in the GadgetBridge application it works fine for Outlook, but when the actual notification appears on my phone it looks like Gadgetbridge doesn't detect it.  Also, Gmail works fine.  I tried generating a log but its always 0kb.

#### Your wearable device is:

Amazfit Bip with FW 0.0.9.14

#### Your android version is:
8.0.0 

#### Your Gadgetbridge version is:
0.21.6

Outlook version: 2.2.44(233)

**Comment by ashimokawa** [comment]
We would need logs at least since no one of us uses Outlook (or any other proprietary software on the phone)

**Comment by frizzo99** [comment]
Was able to get a log this time.

https://pastebin.com/fWEYLHBK

Thanks

**Comment by ashimokawa** [comment]
@frizzo99 
The log does not contain any incoming notification at all.
Did outlook create one?

**Comment by frizzo99** [comment]
I did get an Outlook notification on my phone.  I can try to generate another log.

**Comment by ashimokawa** [comment]
@frizzo99 
the screen has to be off - or you have to enable the option so send notifications even when the screen is off.

**Comment by frizzo99** [comment]
My screen was off when I got notifications.  I created a new log file below.  But I don't think it logged again.  The timestamp on the log file only gets updated when I re-launch the gadgetbridge app.  If the app is running the timestamp doesn't change.  So in this case it probably won't catch the notification.

https://pastebin.com/Qe79mNqg

Sorry to bother you.

**Comment by ashimokawa** [comment]
@frizzo99 
Please quit Gadgetbridge via the "Quit" menu item in the main activity drawer to flush log files.

**Comment by frizzo99** [comment]
I did Quit GadgetBridge multiple times.  And noticed the log files timestamp doesn't change when I'm sending notifications.  What else can I do?

**Comment by frizzo99** [comment]
One more try.  
https://pastebin.com/NLz7J70D

**Comment by danielegobbetti** [comment]
There is nothing about anything resembling outlook application even in your last log. 
The only thing I can think of is that the package name of the outlook application is different on your phone for some reason.
Can you please try to execute this command: ``adb shell 'pm list packages -f '``. It should list every app that you have on your phone. Please search for possible candidates (packages with microsoft or outlook in the name) and list them here.

**Comment by frizzo99** [comment]
Thanks Daniele for getting back to me.  This is the only package I could find with Microsoft or Outlook in it:
package:/data/app/com.microsoft.office.outlook-G-x4z2OhSfQp8kqsqu8quQ==/base.apk=com.microsoft.office.outlook

**Comment by ashimokawa** [comment]
@frizzo99 
"com.microsoft.office.outlook" does not even appear in your logs.
And that is exactly why we have no idea how we should help you.
Normally even if we fail to parse or ignore notifications, we should at least get the package name in our log.

So unless there is some secret android feature that can hide notification from notification listeners (like gadgetbridge is), I honestly have no idea.

**Comment by frizzo99** [comment]
Crap....the log doesn't log when the issue occurs.  Not sure how to capture
it in the logs.  The log only logs on startup then stops.

**Comment by danielegobbetti** [comment]
Perhaps you can try letting an ``adb logcat`` running on your PC and getting a notification?

**Comment by frizzo99** [comment]
Here is the logcat log:
https://pastebin.com/XXiiRc0s

I see this message "Sending new mail notification for 1 messages", but nothing to do with outlook or microsoft.  All I did was enable logcat then sent an email to my outlook account.  I see the notification on my phone, but my Bip doesn't pick i up.

Thanks

**Comment by ashimokawa** [comment]
@frizzo99 
The log does not contain anything Gadgetbridge related.
Please start Gadgetbridge. Receive an email vie Outlook. Force close Gadgetbridge via settings. Obtain the log.

**Comment by joserebelo** [comment]
There will be no info in the logs anyway. The notification is being ignored in `NotificationListener.shouldIgnoreNotification(Notification notification)` because it is marked as LocalOnly. This ignores it silently without any information being written to the log (should probably add some logging here).

**Comment by danielegobbetti** [comment]
That is good to know. Thanks @joserebelo!
I'm closing this as there is nothing we can do about it.

**Comment by frizzo99** [comment]
How does the Mi Fit app do it then?  Also if it can't be fixed can I use
Gadgetbridge and Mi Fit at the same time?  I really like how messages are
grouped together.  Especially for Whatsapp.

**Comment by joserebelo** [comment]
@frizzo99 Mi Fit probably ignores the LocalOnly flag altogether. It _can_ be "fixed", we could ignore that flag as well on Gadgetbridge (even if only for Outlook) but that would violate Android's specification, so I understand why @danielegobbetti might not want to do that.

**Comment by frizzo99** [comment]
Can I run both apps together? Mi fit and Gadgetbridge?

**Comment by walkjivefly** [comment]
In the wiki it is not recommended to do so, but I've been running both concurrently for nearly a year without any obvious problems.

**Comment by danielegobbetti** [comment]
We are just following the best practices in [the documentation](https://developer.android.com/reference/android/app/Notification.html#FLAG_LOCAL_ONLY):
> FLAG_LOCAL_ONLY [...] should be set if this notification is relevant to the current device only and it is not recommended that it bridge to other devices.

I would suggest you contact the authors of the app that is emitting the notification and ask them the reason of this behavior, as it is something an app does explicitly.

**Comment by frizzo99** [comment]
Thanks Daniele.  I will contact Microsoft.  What should they be using instead of FLAG_LOCAL_ONLY?

**Comment by danielegobbetti** [comment]
One option is to use nothing at all, notifications are then handled normally.

Another option is to add wearable actions to the notification, this allows for instance to reply (from supported devices like pebble) or mark message as read, etc.

It's really up to each app developer to choose where the notifications for the app should go and how "smart" to make them, based on the peculiarities of the app. There is no universal approach.

**Comment by frizzo99** [comment]
Thanks again :)  You guys do great work.

I'll contact Microsoft.

**Comment by frizzo99** [comment]
I contacted Microsoft, but they wouldn't tell me why they do this.  So I'm using Mi Fit app for Outlook notifications and GadgetBridge for all other notifications.  Would have been better to just use one app but oh well.  Thanks for all your hard work.

**Comment by ashimokawa** [comment]
I think it is okay to work around around this bug just like we could do with wechat. We are discussing our policy regarding this.

**Comment by frizzo99** [comment]
That would be fantastic

**Comment by ashimokawa** [comment]
@frizzo99 
Can you test with Gadgetbridge 0.22.4 which is out on f-droid?

**Comment by frizzo99** [comment]
I'll try it tomorrow and get back to you.  The Outlook app can actually use
other email accounts such as Gmail.

**Comment by frizzo99** [comment]
It works! You guys are awesome! Thank you very much!!!!
