### ISSUE TITLE
Periodic empty notification, text = "Searching..."

### ISSUE THREAD

**Issue by superpsych0** [Freeyourgadget/Gadgetbridge#852]
Device: Pebble Steel
Firmware: 3.12.3
Phone: Samsung Galaxy S7
Android Version: 7.0
Gadgetbridge: latest

After pairing with my phone, I get an empty notification on my Pebble every half an hour, with the text "Searching..."

I can dismiss it, and I figure it's the phone's BT software doing a handshake or something like that... it's only mildly annoying but I would like a resolution if there is one available :+1:

**Comment by IzzySoft** [comment]
First thing coming to my mind (can at least serve as a work-around until a final solution is available): Blacklist the app causing this. You can do so from GB's [Configuration page](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Configuration). If you don't know which app exactly is behind it, it might involve some try-and-err, of course :wink:

**Comment by danielegobbetti** [comment]
The "mute" option on the pebble should blacklist the emitting application.

**Comment by IzzySoft** [comment]
Oh, sure – completely forgot about that. No try-and-err needed, not even scrolling the list of apps – just wait max 30min until the next notification pops up, then mute it :+1:

**Comment by danielegobbetti** [comment]
I'm closing this, if for any reason the suggested solutions do not work, please let us know.

**Comment by superpsych0** [comment]
Sorry I missed the conversation folks, had notification emails going to spam for some reason.

Thanks for the suggestions, will try the 'Mute' option first and then look for the offending app and circle back here.

**Comment by superpsych0** [comment]
All right, so I've received the first "Searching..." notification, muted it and half an hour later... BAM one more.

Just dismissed that one now, will add another comment after I've figured out which app is sending it out (if possible via the phone).

**Comment by superpsych0** [comment]
Okay, and now another notification, chose "open on phone" with the phone unlocked and nothing happened other than the notification being dismissed from my Pebble.

I guess I'll look into looking at the list of apps to blacklist, but I'm not even sure which one it might be...

**Comment by danielegobbetti** [comment]
You should find one blacklisted app in the list (the one you muted).
If it happens regularly, please send logs.
