### ISSUE TITLE
Scrolling graphs moves to next tab.

### ISSUE THREAD

**Issue by forkoz** [Freeyourgadget/Gadgetbridge#860]
#### Your issue is:
I zoom the graph and try to scroll left/right or up and down but instead the whole tab moves.

#### Your wearable device is:
Miband 1S

#### Your android version is:
6.0.1
#### Your Gadgetbridge version is:
22 from fdroid

The areas where you can grab and move time or scale are really hard to find on a small screen device. I have to constantly stop it from flipping over to the next page or refreshing when I'm just trying to scroll. I can't even read data such as HR when it is zoomed out.

We're going to scroll a lot more then we are going to page flip so this is a big downer right now unless you can suggest an external program to process the exported data.

Suggestion: enlarge the areas for scrolling or just confine the page flip to the top where the tabs are.

**Comment by ashimokawa** [comment]
@forkoz 
I also think we have to turn the flip gesture off completely.
