### ISSUE TITLE
Automatic Bluetooth on/off control

### ISSUE THREAD

**Issue by phunkular** [Freeyourgadget/Gadgetbridge#861]
Gadgetbridge manages to turn Bluetooth on automatically when scanning for new devices but not when you just open the app.

It would be useful to have gadget bridge turn on Bluetooth automatically when opening the app. An option to turn off Bluetooth automatically when exiting the app would also be welcome,

thanks

**Comment by danielegobbetti** [comment]
There is already an open discussion in a PR (not merged) : #737

**Comment by phunkular** [comment]
Sorry I missed it (just looked through all the issues but didn't see it). Seems pretty complex but if there's the option to offer more of a choice to users then I'm all for it... There are loads of features I don't use in gadgetbridge but there's nothing wrong with having them there.
