### ISSUE TITLE
[1s] Sleep per week not populating

### ISSUE THREAD

**Issue by forkoz** [Freeyourgadget/Gadgetbridge#865]
#### Your issue is:
Sleep per week not populating.

#### Your wearable device is:
Mi Band 1s

#### Your android version is:
6.0.1
#### Your Gadgetbridge version is:
22..1

**I've noticed that even though the data is there, the sleep per week graph is not populating. I don't know if its the times I'm falling asleep but I only have one bar on the graph.**
![nov1-2](https://user-images.githubusercontent.com/12354546/32375592-3126d1da-c070-11e7-852f-105426f5920e.png)
![nov2-3](https://user-images.githubusercontent.com/12354546/32375594-33b7f654-c070-11e7-84e9-1a2ad46c08af.png)

**vs N&F sleep a week... yes there is a day in there where I had to clear the GB db for it to sync. I exported it but to import it now wouldn't work I think. It would kill the data afterwards, no? Since GB doesn't concatenate imports/exports?**
**IMAGE REMOVED**

**Must say I'm impressed with the data interpretation of this app vs others. It is correctly detecting a lower amount of deep sleep and the time I'm going to bed. Other apps I've tried seem to lie to you on just how much sleep your getting. What's missing though is point data on the screen, i.e time fell asleep, time woke up and maybe average, low, high heart rate stats. Maybe that's a bit OT, but you could shrink the circle and add some boxes. Circle is huge.**

**IMAGE REMOVED**

**Comment by IzzySoft** [comment]
This is probably not specific to the Mi:Band. I haven't watched it closely, but to me it looks as if the "sleep per week" rather presents "sleep of past 24h" or something similar: it always closely matched the sleep time of the previous day whenever I took a look at it.

**Comment by forkoz** [comment]
Yes, I did notice that now. I had a bar there yesterday too. But never 2 bars and when I flip back I get nothing as shown.

**Comment by danielegobbetti** [comment]
I removed images from other apps and am closing this issue.

**WE DO PROVIDE A ISSUE TEMPLATE WITH CHECKBOXES TO CHECK FOR A REASON!**

**Comment by forkoz** [comment]
ok, I think I fixed it.
