### ISSUE TITLE
[support Teclast H10] Added support with single line fix

### ISSUE THREAD

**Issue by newfla** [Freeyourgadget/Gadgetbridge#867]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
(Teclast H10 is a teclast H30 without cardio sensor and gadgetbridge has no support for h30 cardio sensor)
Discovery of device fails due to line 66 in ...\devices\jyou\TeclastH30Coordinator. 
Change in <if (name != null && (name.startsWith("TECLAST_H30")|| name.startsWith("TECLAST_H10"))) >
solved the issue. Notification, vibration and battery info work.
It's my first time on github so excuse me if I opened an issue instead of pull_request (maybe?)

#### Your wearable device is:
TECLAST H10 1.2.7

#### Your android version is:
7.1.2

#### Your Gadgetbridge version is:
0.22.2

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
@newfla 
Sure you can make a pull request, that would preserve your name as the author of the commit, if you don't care I can make the change for you as described.
