### ISSUE TITLE
Seemingly random crashes in last two updates (Pebble Time)

### ISSUE THREAD

**Issue by gappleto97** [Freeyourgadget/Gadgetbridge#868]
Every few hours it just crashes the entire app. There's no notifications coming in at many of these times, so I dont know what could cause it.

If you direct me to where the logs are stored, I'd be happy to attach here.

**Comment by danielegobbetti** [comment]
Did you enable the experimental background JavaScript execution?

**Comment by gappleto97** [comment]
I changed no options. It is not enabled.

**Comment by danielegobbetti** [comment]
Thanks for confirming. The logs are located on ``/sdcard/Android/data/nodomain.freeyourgadget.org/files``. Remember to check the corresponding option in the settings.

**Comment by ashimokawa** [comment]
@gappleto97 
We are still waiting for the log, could you share it? Unfortunately I see no crashes here...

**Comment by ashimokawa** [comment]
@gappleto97 
Should be fixed in master and 0.22.4, just tagged, takes a while for F-Droid to pick up and build

**Comment by IzzySoft** [comment]
@ashimokawa glad to read! Just wanted to chime in, as I now can confirm those crashes on my end. Until Sunday I was completely unsure, as my device froze once a day (so I rather had other sources in mind). After a clean install (complete wipe of everything and flashing a new ROM), GB had crashed at least 3 times now – which I only noticed much later, when a notification chimed on the device but did not reach my Pebble. Will wait for the new release to pop up on F-Droid (which might take some days: no updates of their index within the last week).

**Comment by ashimokawa** [comment]
0.22.4 is out on f-droid, please test if this resolves your crash

**Comment by gappleto97** [comment]
Just got the update. I'll let you know if it crashes again.
