### ISSUE TITLE
MiBand 2 keeps trying to sync with the same timstamp - never finishes - syncing stopped - maybe daytime saving related

### ISSUE THREAD

**Issue by marius-cornescu** [Freeyourgadget/Gadgetbridge#869]
#### Before opening an issue please confirm the following:
- [x ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Gadgetbridge version is: 0.22.1

When I sync the band, it keeps on saying "synchronizing 29 October, 00:28" but new data has not been added since.

This date is the date when the daytime saving went into effect in my country, but also a date when I traveled between timezones.

In the log I see that:
`12:20:01.627 [Binder:3308_1] INFO  n.f.g.s.d.m.o.FetchActivityOperation - Mi2 activity data: last sample timestamp: 29 October, 00:28
12:20:01.628 [Binder:3308_1] INFO  n.f.g.s.d.m.o.FetchActivityOperation - Doing another fetch since last sync timestamp is still too old: 29 October, 00:28`

And it repeats this, until the 5 limit is hit from '**FetchActivityOperation:needsAnotherFetch()**', but I can't figure out why this date would be always the '**startTimestamp**' read in '**AbstractFetchOperation:handleActivityMetadata()**'. 
Maybe the band does not get notified that the data was synced? However, I don't see any new data after that date in the application.

This is the log:
[2017_11_05-gadgetbridge-01.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1444055/2017_11_05-gadgetbridge-01.log)

**Comment by ashimokawa** [comment]
I guess it has to do with how we convert timestamps to Calender objects and back, plus that the chunk your Mi Band tries to transfer is only one hour long. 

So when we do something wrong there it could be that just the 1 hour offset and the 1 hour that has to be transferred from the band just add up to 0 and we are stuck.

It could also be a problem because you are trying to fetch data from summer time during winter time and we do not handle that correctly.

Anyway I will investigate further, thanks for providing the log!

**Comment by ashimokawa** [comment]
@marius-cornescu 
If you are able to build master yourself, please apply a58e3f6 there and test.

**Comment by walkjivefly** [comment]
@ashimokawa Just an observation: I had a similar problem syncing data from a MiBand2 two times earlier this year. Both happened when I changed timezones; one was a 6 hour shift, one only 1 hour. I can't remember the details now but I kludged it by hardcoding a start time in the transfer function and forcing it to lose some data in the process. After doing the force sync I switched back to whatever was the standard GB at the time (about 0.19.3 iirc) and it behaved fine thereafter. Interestingly I didn't experience the problem on my third timezone shift of the year (another 6 hours) but I can't remember what, if anything, I did differently on the first sync after the timezone change.

**Comment by marius-cornescu** [comment]
@ashimokawa, I haven't built a dev environment for this, yet ... just pulled the code ...

**Comment by cpfeiffer** [comment]
The issue here is indeed the timezone travel.

We ask for all activity samples since a given timestamp in UTC+1 and get back a timestamp that is *earlier* than our given timestamp, but in UTC+2.

I think we don't handle the timezone here, so we just use the "too" early timestamp and end up not progressing.

**Comment by phunkular** [comment]
same as https://github.com/Freeyourgadget/Gadgetbridge/issues/827 no?

**Comment by ashimokawa** [comment]
@phunkular 
@marius-cornescu 
I just tagged 0.22.3, please give it a try when it appears on F-Droid, or build yourself

**Comment by ashimokawa** [comment]
@phunkular 
@marius-cornescu 
It is finally on F-Droid, please try and report back.

**Comment by marius-cornescu** [comment]
Hi @ashimokawa , 
it's looking good. After the upgrade, I was able to get the data from the band.

I also tried to build the app myself, but I got a dependency issue. Now, after updating to latest master, assembleRelease goes much further, but still errors because of missing translation ...
 What would be the best channel to ask for help/info about build?

**Comment by ashimokawa** [comment]
@marius-cornescu 
Just ignore the error should be fine - at least I thought so.
You shoud try assembleDebug in any case, makes installing the resulting apk much easier.

Anyway I will close this issue since it seems to work. 👍
