### ISSUE TITLE
Mi Band 2 problems with Firmwares

### ISSUE THREAD

**Issue by idHUBERTH** [Freeyourgadget/Gadgetbridge#873]
#### Before opening an issue please confirm the following:
- [x ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
My Mi Band 2 have V1.0.1.53 firmware and I can't update it with Mi Fit, so I tried to update it with Gadget Bridge with V1.0.1.54 and V1.0.1.53 from assics folder in Mi Fit apk. Gadget Bridge told me that this version is verified but It didn't worked. It's just going to 99% and Fail - in app and on Mi Band 2, it told me that there is problem with framework transfer.  Custom Firmwares aren't working too. Only  mili_pro_tph_indian.fw i mili_pro_tph.fw are working but they are updating to V1.0.1.53, what Can I do? Why I can't update it? 

#### Your wearable device is:

Mi Band 2 V1.0.1.53

#### Your android version is:
5.0.2 and 6 (MIUI)
#### Your Gadgetbridge version is:
0.22.2
###
LOG:
I just don't have it because there weren't log, it just told me that there is problem with framework transfering.

**Comment by ashimokawa** [comment]
@idHUBERTH 
This is not a bug. The latest firmware for the "tph" variant of the Mi Band 2 (which you appear to have) is V1.0.1.53. There is no .54 release for that band.

I agree that Gadgetbridge should detect the models better, but when we started there was only one model and we do not have access to any special variant like yours, so it is unlikely to happen.

**Comment by ashimokawa** [comment]
@idHUBERTH 
Can you tell the HW Version displayed in Gadgetbridge for your tph model?
