### ISSUE TITLE
Mi Band 2 doesn't receive ANY notifications or signals

### ISSUE THREAD

**Issue by timonoj** [Freeyourgadget/Gadgetbridge#874]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*
My Mi Band 2 connects a bit weird already from the beginning: When pairing, it stays connected for the rest of the time. After a reboot, it's disconnected and never connects, unless forced repeatedly to do so. However no notifications are sent in any case. Even the Find Lost Device does nothing. However it does sync the data, and the Live Activity window does update in real time. The sync button also downloads the steps and sleep data.
Debug window doesn't work at all. Not a single option does seem to have any reaction from the band.

Any help is welcome. Thanks a lot!

#### Your wearable device is:
Mi Band 2. (FW 1.0.1.54, HW V0.1.3.2)
*Please specify model and firmware version if possible*

#### Your android version is:
Android 7.0 on a Galaxy S7 SM-G930FD. Device language is English, so no special characters/fonts involved.
#### Your Gadgetbridge version is:
0.22.2

Attaching log:
[gadgetbridge.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/1450097/gadgetbridge.log.txt)

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by timonoj** [comment]
Update: Well, what do you know...I just left the thing for the day. Today the notification buzzes woke me up. For some reason it started working overnight. Debug page also seems to work now. Now I'm afraid to reboot my phone and losing it again :)
I still cannot customize the notifications though. It's always two strong buzzes regardless the notification "tone" selected.

**Comment by danielegobbetti** [comment]
Could it be that you're band has some hardware issue?

**Comment by timonoj** [comment]
Uhh I don't think so, this only happens with Gadget Bridge. Mi Fit app does sync notifications without effort. 

EDIT: OMG. I'm an idiot. I thought I had disabled the do not disturb section. But I had forgotten the Mi Band dedicated options. I made a huge typo there...Used a DND of 11.40AM until 8.30AM instead of 23.30. I don't even know what to say. Case closed, I feel a bit dumber. Thanks!
