### ISSUE TITLE
Time is shown in wrong regional format (AM/PM instead of 24hr)

### ISSUE THREAD

**Issue by phunkular** [Freeyourgadget/Gadgetbridge#875]
Hello, not a big one but thought I'd mention it anyway.

My phone is set to 24hour clock but the toasts in the app are shown in AM and PM. For example: whenever you sync data with mi band.

thanks

**Comment by phunkular** [comment]
wontfix?

**Comment by ashimokawa** [comment]
@phunkular 
I guess you removed the issue template which led to a immediate close
