### ISSUE TITLE
Miband 2 - FW 1.0.1.54 does not reconnect!

### ISSUE THREAD

**Issue by Jonnire** [Freeyourgadget/Gadgetbridge#878]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I am able to register my miband 2 in Gadgetbridge and fetch all the data of it as well as use it without problems, but once I was in flight mode or somehow else disconnected my miband, it does not reconnect.
The only solution I found so far is to delete the miband 2 and add it again, which is obviously pretty annoying. 
I deactivated "Enable bluetooth pairing" too as it did not connect with it being enabled.
I will attach my log file and hope that it can be of some help.

They appeared to have found a similar issue:
https://github.com/Freeyourgadget/Gadgetbridge/issues/859
#### Your wearable device is:
MiBand 2 on FW 1.0.1.54

#### Your android version is:
7.0
#### Your Gadgetbridge version is:
0.22.2 (downloaded of F-Droid)

Log File:
21:05:42.276 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.22.2
21:05:46.324 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
21:05:46.326 [main] INFO  n.f.g.s.b.BtLEQueue - Attempting to connect to MI Band 2
21:05:46.326 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Queue Dispatch Thread started.
21:05:46.332 [main] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: CONNECTING
21:05:46.360 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
21:05:46.381 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got metadata changed intent, but nothing changed, ignoring.
21:05:46.382 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got state changed intent, but not enough has changed, ignoring.
21:05:46.382 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got metadata changed intent, but nothing changed, ignoring.
21:05:46.382 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got state changed intent, but not enough has changed, ignoring.
21:06:13.346 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Update Music Info: Hozier / Take Me To Church / Take Me To Church
21:06:13.348 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Update Music State: state=1, position= 216
21:06:13.351 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:13.352 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got metadata changed intent, but nothing changed, ignoring.
21:06:13.353 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Update Music State: state=0, position= 216
21:06:13.356 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:13.357 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:13.677 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:13.678 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:13.678 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:13.678 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:13.698 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:13.698 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:13.699 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:13.699 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:13.700 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:13.700 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:14.086 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:14.087 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:14.597 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got metadata changed intent, but nothing changed, ignoring.
21:06:14.598 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got state changed intent, but not enough has changed, ignoring.
21:06:14.726 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:14.726 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:14.766 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:14.767 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:15.275 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Update Music Info: Andreas Bourani / Hey / Auf uns
21:06:15.278 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Update Music State: state=0, position= 1
21:06:15.279 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got metadata changed intent, but nothing changed, ignoring.
21:06:15.279 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got state changed intent, but not enough has changed, ignoring.
21:06:15.279 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:15.280 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:15.403 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:15.404 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:15.439 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:15.440 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:15.472 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:15.473 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:15.494 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:15.495 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:15.551 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:15.551 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:15.603 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:15.603 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:15.712 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:15.713 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:15.728 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:15.729 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:16.345 [Binder:16728_3] DEBUG n.f.g.s.b.BtLEQueue - connection state change, newState: 0 (failed: 133)
21:06:16.345 [Binder:16728_3] WARN  n.f.g.s.b.BtLEQueue - connection state event with error status 133
21:06:16.345 [Binder:16728_3] INFO  n.f.g.s.b.BtLEQueue - Disconnected from GATT server.
21:06:16.345 [Binder:16728_3] DEBUG n.f.g.s.b.BtLEQueue - handleDisconnected: 133
21:06:16.345 [Binder:16728_3] DEBUG n.f.g.s.b.BtLEQueue - internal gatt callback set to null
21:06:16.345 [Binder:16728_3] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
21:06:16.345 [Binder:16728_3] DEBUG n.f.g.s.b.BtLEQueue - disconnect()
21:06:16.346 [Binder:16728_3] INFO  n.f.g.s.b.BtLEQueue - Disconnecting BtLEQueue from GATT device
21:06:16.348 [Binder:16728_3] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
21:06:16.396 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
21:06:16.433 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
21:06:16.491 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:16.492 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:16.492 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:06:16.492 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:06:18.352 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
21:06:18.353 [main] DEBUG n.f.g.s.b.BtLEQueue - disconnect()
21:06:18.354 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Thread interrupted
21:06:18.354 [Gadgetbridge GATT Dispatcher] INFO  n.f.g.s.b.BtLEQueue - Queue Dispatch Thread terminated.
21:06:18.357 [main] INFO  n.f.g.s.b.BtLEQueue - Attempting to connect to MI Band 2
21:06:18.357 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Queue Dispatch Thread started.
21:06:18.365 [main] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: CONNECTING
21:06:18.439 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
21:06:48.374 [Binder:16728_2] DEBUG n.f.g.s.b.BtLEQueue - connection state change, newState: 0 (failed: 133)
21:06:48.375 [Binder:16728_2] WARN  n.f.g.s.b.BtLEQueue - connection state event with error status 133
21:06:48.376 [Binder:16728_2] INFO  n.f.g.s.b.BtLEQueue - Disconnected from GATT server.
21:06:48.377 [Binder:16728_2] DEBUG n.f.g.s.b.BtLEQueue - handleDisconnected: 133
21:06:48.377 [Binder:16728_2] DEBUG n.f.g.s.b.BtLEQueue - internal gatt callback set to null
21:06:48.378 [Binder:16728_2] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
21:06:48.379 [Binder:16728_2] DEBUG n.f.g.s.b.BtLEQueue - disconnect()
21:06:48.382 [Binder:16728_2] INFO  n.f.g.s.b.BtLEQueue - Disconnecting BtLEQueue from GATT device
21:06:48.389 [Binder:16728_2] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
21:06:48.456 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
21:06:48.548 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
21:07:39.997 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
21:07:39.998 [main] DEBUG n.f.g.s.b.BtLEQueue - disconnect()
21:07:39.998 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Thread interrupted
21:07:39.998 [Gadgetbridge GATT Dispatcher] INFO  n.f.g.s.b.BtLEQueue - Queue Dispatch Thread terminated.
21:07:40.003 [main] INFO  n.f.g.s.b.BtLEQueue - Attempting to connect to MI Band 2
21:07:40.003 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Queue Dispatch Thread started.
21:07:40.012 [main] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: CONNECTING
21:07:40.084 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
21:08:10.023 [Binder:16728_1] DEBUG n.f.g.s.b.BtLEQueue - connection state change, newState: 0 (failed: 133)
21:08:10.024 [Binder:16728_1] WARN  n.f.g.s.b.BtLEQueue - connection state event with error status 133
21:08:10.025 [Binder:16728_1] INFO  n.f.g.s.b.BtLEQueue - Disconnected from GATT server.
21:08:10.025 [Binder:16728_1] DEBUG n.f.g.s.b.BtLEQueue - handleDisconnected: 133
21:08:10.025 [Binder:16728_1] DEBUG n.f.g.s.b.BtLEQueue - internal gatt callback set to null
21:08:10.026 [Binder:16728_1] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
21:08:10.029 [Binder:16728_1] DEBUG n.f.g.s.b.BtLEQueue - disconnect()
21:08:10.030 [Binder:16728_1] INFO  n.f.g.s.b.BtLEQueue - Disconnecting BtLEQueue from GATT device
21:08:10.038 [Binder:16728_1] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: NOT_CONNECTED
21:08:10.109 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
21:08:10.188 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
21:10:15.048 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Update Music Info: Namika / Nador / Lieblingsmensch
21:10:15.053 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got state changed intent, but not enough has changed, ignoring.
21:10:15.053 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got metadata changed intent, but nothing changed, ignoring.
21:10:15.053 [main] INFO  n.f.g.e.MusicPlaybackReceiver - Got state changed intent, but not enough has changed, ignoring.
21:10:15.053 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:10:15.234 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:10:15.235 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:10:15.270 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:10:15.270 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:10:15.330 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:10:15.331 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:10:15.331 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:10:15.332 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:10:15.417 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:10:15.417 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:10:15.434 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicinfo
21:10:15.435 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.setmusicstate
21:34:40.660 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.connect
21:34:40.661 [main] DEBUG n.f.g.s.b.BtLEQueue - disconnect()
21:34:40.661 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Thread interrupted
21:34:40.661 [Gadgetbridge GATT Dispatcher] INFO  n.f.g.s.b.BtLEQueue - Queue Dispatch Thread terminated.
21:34:40.663 [main] INFO  n.f.g.s.b.BtLEQueue - Attempting to connect to MI Band 2
21:34:40.663 [Gadgetbridge GATT Dispatcher] DEBUG n.f.g.s.b.BtLEQueue - Queue Dispatch Thread started.
21:34:40.669 [main] DEBUG n.f.g.s.b.BtLEQueue - new device connection state: CONNECTING
21:34:40.704 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true

**Comment by ashimokawa** [comment]
You should re-activate the "enable bluetooth pairing" checkbox, delete the Mi Band from Android settings (not Gadgetbridge), then press the + button in Gadgetbridge and pair.

This happens to everyone after updating to .54

**Comment by HennesTheSecond** [comment]
Would you please test, if auto reconnect works for you after that?
After deleting and pressing the (+) Button in Gadgetbridge my Mi Band 2 connects again but auto reconnect doesn't work. This means, I have to manually reconnect my Mi Band 2 almost every time my Phone was off or out of range. I'm note the only one with this issue - see https://github.com/Freeyourgadget/Gadgetbridge/issues/859 :-(

**Comment by ashimokawa** [comment]
@HennesTheSecond 
Auto re-connect does not work reliably for me, it never did. Although only recently got a Mi Band 2 for testing and have no experience with older firmwares.

**Comment by HennesTheSecond** [comment]
auto reconnect definitely worked in spring 2017

**Comment by Jonnire** [comment]
@ashimokawa 
I reinstalled Gadgetbridge and unpaired my miband 2 in my android bluetooth settings.
Then I tried to add my band, with all settings left unchanged (I just filled an alias in), and when Gadgetbridge was trying to pair, it is pairing with it, but it was never actually connecting.
When I rotate my phone while Gadgetbridge is trying to connect it says that is already bonded, but still trying to connect.
My miband came up in my bluetooth settings again as a paired device and came up in Gadgetbridge as "not connected".
I then manually tried to connect and *surprise*, it actually worked.
I also witched to flight mode and back multiple times and went out of range once and so far it is reconnecting without any problems.
I will update after a couple days of testing to close this.

**Comment by tradej** [comment]
My Band 2 sometimes does not reconnect after the phone has been out of range. It connects immediately when I press the card in GadgetBridge. I don't think it's ever disconnected when the phone stays in range.

My log: https://paste.fedoraproject.org/paste/8ef7kgkQPQrYrvrK5T1KpA

**Comment by Jonnire** [comment]
@tradej 
It is still working for me!
I have "connect to device when Bluetooth turned on" and "reconnect automatically" turned on in the settings though and it works fine even when I go out of range.
