### ISSUE TITLE
Quiet mode/night mode

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#88]
It should be possible to disable device vibrations during a configurable "quiet period".

How to enable and configure this is open for discussion.

Options:
1. A big "Quiet, please" button in the UI, that will prevent any notifications to be sent to the device
2. A configuration option to specify multiple quiet periods (start and end times, possibly with day of week)
3. Integrate with Android profiles. The user would have to reuse or create a "Quiet" profile for which he will be able to disable notifications to the device. There are other tools that allow for automatic profile selection based on certain events, including time.

Today it is already possible to use the profile mechanism to disable Bluetooth which will disable Gadgetbridge entirely.

**Comment by danielegobbetti** [comment]
Isn't this the same as disconnecting from the device?

**Comment by chrisvella** [comment]
Are there still plans to work on this? I get disturbed in the morning when my band starts vibrating.

**Comment by cpfeiffer** [comment]
I still haven't made up my mind about which of the options to choose. Turning off Bluetooth at night, e.g. using a profile or the Interruptions preferences in Lollipop, is not an option for you?

What would you prefer?

**Comment by chrisvella** [comment]
Turning off Bluetooth is definitely an option. I will give that a go for the time being. I guess it kinda makes this idea more of a aesthetic feature.

Personally I don't like the idea of defining "quiet hours". My sleeping pattern is very variable. 

I really like your idea of a sleep button I can click in the app before bed, then click off in the morning. The simplicity is really appealing.

The advantage of this over simply turning off Bluetooth would be keeping smart unlock enabled, maintain a connection between the phone and other Bluetooth devices, less risk of the device failing to reconnect, keeping the ability to easily change a gadgetbridge alarm through the night. 

Apologies if any of these are invalid. I'm not really familiar with Bluetooth devices (my only experience is with my miband).

**Comment by danielegobbetti** [comment]
Fyi you can long press the miband and choose "disconnect".
That would keep bt devices connected and even smartlock active, probably, since it only impacts the connection between miband and gadgetbridge.

Hth
--

**Comment by shtrom** [comment]
:+1:

It would be good to be able to set a schedule (say midnight to 8am) during which no notification is forwarded to the watch.

The point of the schedule is not too have to disconnect/unpair the watch everynight.

**Comment by shtrom** [comment]
Ok, ignore my previous comment. I misunderstood the request, and the firmware already does what I described just fine.

**Comment by danielegobbetti** [comment]
See #306 for the integration with android "do not disturb" feature.

**Comment by cpfeiffer** [comment]
Indeed, even though it's only for devices running Marshmellow or later, this is IMHO the best solution.
