### ISSUE TITLE
Gadgetbridge 0.22.3 force close after connecting. Miband2

### ISSUE THREAD

**Issue by mikhakhaldea** [Freeyourgadget/Gadgetbridge#886]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

Your issue is:

I was update my gadgetbridge Application from earlier version 0.21.x and run smothly on my phone and then after upgrade to 0.22.3 gadget bridge force close after connecting. 

My app log is here : https://pastebin.com/XDR2VxT8

Your wearable device is:

Miband2

hardwareRevision='V0.1.3.2'  softwareRevision='V1.0.1.53'

Your android version is:

4.4.2

Your Gadgetbridge version is:

0.22.3

**Comment by ashimokawa** [comment]
@mikhakhaldea 
I did not see any crash in the logs :(

Anyone else here with access to Android 4.4 and a Mi Band 2 who could test?

**Comment by mikhakhaldea** [comment]
this is the screenshoot, gadgetbridge was connect, battery status is loaded and force close after few second.


![index](https://user-images.githubusercontent.com/29059738/32980272-d7c35f3c-cc95-11e7-8831-bccd4b385fa6.jpeg)

**Comment by ashimokawa** [comment]
Can you connect a USB cable and run "adb logcat"?

**Comment by mikhakhaldea** [comment]
@ashimokawa here is my huge logcat https://pastebin.com/LhheuNiw anyway. thx for your attention

**Comment by ashimokawa** [comment]
@mikhakhaldea 
Thanks! That helps.
It seems to be this change in Gadgetbridge 0.22.0
"Add some quick action buttons to Gadgetbridge's notification"

This seems to be incompatible with Android 4.4 :/

@danielegobbetti 
Can you test?

**Comment by danielegobbetti** [comment]
Will do

**Comment by mikhakhaldea** [comment]
Ok. I will close this issue. I hope will be fixed in next version. Thank you.

**Comment by ashimokawa** [comment]
@mikhakhaldea 
Please don't close issues that are not fixed ;)

**Comment by supervillus** [comment]
Hello,
seems to be the same problem here with a tolino tab 8 an Android 4.4.4
Is this failure fixed in >0.22.4?
Miband Firmware is 1.0.1.39/Gadgetbridge is 0.22.4
Is there ny older Verssion, that will work?

Regards

**Comment by ashimokawa** [comment]
Not yet released. Fixed in master.
