### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by alanbcohen** [Freeyourgadget/Gadgetbridge#888]
#### Before opening an issue please confirm the following:
- [ ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*

#### Your wearable device is:

*Please specify model and firmware version if possible*

#### Your Gadgetbridge version is:

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by alanbcohen** [comment]
Device name SAMSUNG-SM-J320A
Model number SAMSUNG-SM-J320A
Android version 7.1.1
Unknown sources allowed
Pebble LE Bluetooth on
Gadgetbridge previously installed; reported upgrade install not working; uninstalled to reinstall
Install button in install dialogue no response

**Comment by alanbcohen** [comment]
Same problem with Newpipe

**Comment by IzzySoft** [comment]
@alanbcohen Any guess what the template in your initial post is for? As you've not filled in the blanks, you risk this issue being closed immediately. I strongly suggest you edit your initial post accordingly.

**Comment by alanbcohen** [comment]
Device name SAMSUNG-SM-J320A
Model number SAMSUNG-SM-J320A
Android version 7.1.1
Unknown sources allowed
Pebble LE Bluetooth on
Gadgetbridge previously installed; reported upgrade install not working; uninstalled to reinstall
Install button in install dialogue no response

**Comment by alanbcohen** [comment]
No option to edit OP. Does not identify requiered template; requested information included in OP. Repeated here with apparant template.
Your issue is:
Install button not working on upgrade or new install. Same problem with newpipe app. May be installer.

Your wearable device is: Pebble LE

Please specify model and firmware version if possible
Device name SAMSUNG-SM-J320A
Model number SAMSUNG-SM-J320A

Your android version is: 7.1.1

Your Gadgetbridge version is: last 2 upgrades, including today.
Unknown sources allowed.
Also posted to fdroid email, twice. No response

**Comment by ashimokawa** [comment]
Are you trying to report an fdroid client bug?

Download and install the apk manually here:

https://f-droid.org/repo/nodomain.freeyourgadget.gadgetbridge_112.apk

**Comment by alanbcohen** [comment]
Copied from comments on issue tracker.

No option to edit OP. Does not identify requiered template; requested
information included in OP. Repeated here with apparant template.
Your issue is:
Install button not working on upgrade or new install. Same problem with
newpipe app. May be installer.

Your wearable device is: Pebble LE

Please specify model and firmware version if possible
Device name SAMSUNG-SM-J320A
Model number SAMSUNG-SM-J320A

Your android version is: 7.1.1

Your Gadgetbridge version is: last 2 upgrades, including today.
Unknown sources allowed.
Also posted to fdroid email, twice. No response

**Comment by alanbcohen** [comment]
Andreas,
Already tried that with both gadgebridge and newpipe. Other downloads via
google play working fine. Just tried to install Amazon Appstore app.
Identical installer dialog; not working either.

**Comment by cpfeiffer** [comment]
If you get an error message of the installer, please post it here.

If you install packages from different sources (e.g. you first installed an apk that "someone" compiled himself and posted it to some forum/website), you cannot simply update it to the "official" version from f-droid. If that is the case, first uninstall your previous version and then install the version from f-droid.

If you never ever installed Gadgetbridge and it still fails without an error message, I'm afraid we can't help you.

**Comment by alanbcohen** [comment]
The original install of both gadgetbridge and newpipe were from the earlier
pre-1.0 version of fdroid. The earlier attempts to upgrade both apps were
from fdroid 1.0.1. There were no in-between installs/upgrades. After the
failed upgrades; the apps were uninstalled. And the re-installs were
attempted using fdroid -sourced versions.

**Comment by ashimokawa** [comment]
@alanbcohen 
The Android build-in Install Dialog can really take a good while before the install button gets clickable, maybe you were to impatient?
