### ISSUE TITLE
Can't hide Gadgetbridge notification

### ISSUE THREAD

**Issue by MissingNoIOI** [Freeyourgadget/Gadgetbridge#890]
I can't hide the Gadgetbridge notification anylonger after the latest update for my phone. I've got an Huawei Mate 9 with Emui 5.0 aka Android 7.0, after I installed update B197, which consists only of security patches acccording to the changelog, the notification can't be hidden anymore, the configuration option doesn't make a difference.  
The same problem also appears with the official Pebble app, there I can't hide it anymore either

**Comment by danielegobbetti** [comment]
It's possible your OS does not allow to hide notifications anymore, as it happens also to other apps. I highly doubt we can do anything about it, hence I'm closing this.

If you find some API or documented way to hide notifications on your OS please *share them here* and feel free to reopen this issue.
