### ISSUE TITLE
Problem updating firmware (Mi Band 2)

### ISSUE THREAD

**Issue by 21prods** [Freeyourgadget/Gadgetbridge#892]
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

Issue is: I cannot upgrade or downgrade the firmware of a my Mi Band 2. Every time I try it seems everything is working and at the last moment it states there's been an error.
*In case of a bug, do not forget to attach logs!*

Wearable device is: Mi Band 2
FW: 1.0.1.52
HW: V0.16.2.2

Android version is: 7.1.2 (LOS 14.1)

Gadgetbridge version is: 0.22.4

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by danielegobbetti** [comment]
Did you try toggling the slow latency option in the settings?

**Comment by ashimokawa** [comment]
I think it might be the wrong firmwares you are trying to flash (there are many mi band 2 variants)

**Comment by 21prods** [comment]
Wrong firmwares? Should I extract other firmwares from the apk?

I even tried to upgrade through the Mi Fit app but I don't know how to do it. In fact it just informs me on which firmware version I am.

**Comment by 21prods** [comment]
@danielegobbetti Yes, I tried it but same result.
