### ISSUE TITLE
Problem updating firmware (Mi Band 2)

### ISSUE THREAD

**Issue by 21prods** [Freeyourgadget/Gadgetbridge#893]
I have read the wiki, and I didn't find a solution to my problem / an answer to my question.

 I have searched the issues, and I didn't find a solution to my problem / an answer to my question.

 If you upload an image or other content, please make sure you have read and understood the github policies and terms of services

Issue is: I cannot upgrade or downgrade the firmware of a my Mi Band 2. Every time I try it seems everything is working and at the last moment it states there's been an error.

(I'm trying to attach the log butI can't do it from my phone, I'll try it later from a desktop)

Wearable device is: Mi Band 2
FW: 1.0.1.52
HW: V0.16.2.2

Android version is: 7.1.2 (LOS 14.1)

Gadgetbridge version is: 0.22.4

**Comment by 21prods** [comment]
Yes, I tried slow latency but it still didn't work.

**Comment by ashimokawa** [comment]
#873 
Duplicate probably. Not every Mi Band 2 model (too many to mention) has the latest firmware.

**Comment by 21prods** [comment]
That's it, it's a question of selecting the right file. I "upgraded" to the Indian variant so I lost HR functionality but then I managed to upgrade to the correct FW and I recovered it.

**Comment by ashimokawa** [comment]
Out of interest - what is the correct Version?

**Comment by 21prods** [comment]
Not quite sure because I was trying different firmwares stressed because I had lost the HR functionality.

Anyway, I'm almost sure it got to grips with mili_pro_tph.fw (the other option is mili_pro_tph_as7000.fw).

I hope this proves helpful, sorry I cannot be more precise.
