### ISSUE TITLE
"Show info on wrist move"

### ISSUE THREAD

**Issue by MicheleSondrio** [Freeyourgadget/Gadgetbridge#896]
After reconnecting settings about the "Show info on wrist move" are lost. I always have "disabled", after gadgetbridge reconnects setting is still on "disabled", but on every wrist move the Bip turns the backlight on.
(I have Italian locale on Mi Fit and I'm not sure about the correct translation)

**Comment by danielegobbetti** [comment]
Please use the issue template when opening an issue.
Please consider that using at the same time Gadgetbridge and other apps that interact with the wearable is not recommended as in this case we cannot reproduce, investigate or solve interoperability issues.

Feel free to open a new issue considering the points above.
