### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by zikalify** [Freeyourgadget/Gadgetbridge#9]
Option to launch gadgetbridge on system boot.

**Comment by aol-nnov** [comment]
IMHO, starting it when bluetooth is enabled makes more sense rather than starting it on system boot.

**Comment by ashimokawa** [comment]
Will be done this week, thank you for your suggestions.

**Comment by 927589452** [comment]
It would be a really cool option to still start on system boot, as gadgetbridge does not start, when the system is started with BT enabled.
