### ISSUE TITLE
Caller ID status on Mi Band 2 FW: 1.0.1.53 ?

### ISSUE THREAD

**Issue by nnadd** [Freeyourgadget/Gadgetbridge#900]
Device: Mi Band 2
FW: 1.0.1.53
HW: V0.9.3.4
Device HTC One M7: Android 5.0.2

Question in the title, what's the status on Caller ID/Name in the MI Band 2? 
No matter what setting I change in the "Call Privacy Mode" under Settings, I always only get the generic call icon.

Also, great piece of software, I wouldn't even touch a smartwatch without a open source way to use it.

**Comment by ashimokawa** [comment]
Did you flash a font?

**Comment by nnadd** [comment]
Yes, works now.

**Comment by ashimokawa** [comment]
Good ;)
I think we can close that.
