### ISSUE TITLE
Can't grant permissions on CopperheadOS / German

### ISSUE THREAD

**Issue by neuhaus** [Freeyourgadget/Gadgetbridge#901]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I installed the app from F-Droid on a Nexus 5X running Copperhead OS (Oreo based), configured to German.

The app requests several permissions. I am unable to grant them (see attached screenshot).

#### Your wearable device is:

Mi 1s

*Please specify model and firmware version if possible*

#### Your android version is:
Android 8.0.0

#### Your Gadgetbridge version is:
0.22.4

Here is a picture that shows the screen:

![gadgetbridge](https://user-images.githubusercontent.com/631764/33499589-c5528a86-d6d5-11e7-874f-c90d1d7f54f7.jpg)

As you can see there are no GUI elements that will let me grant or reject the requested permission(s).

**Comment by danielegobbetti** [comment]
Can you try rotating the screen to workaround the issue?

**Comment by neuhaus** [comment]
I tried, it didn't help

**Comment by ashimokawa** [comment]
@neuhaus 
Can you go to Android Settings->Apps and set the permissions manually?

**Comment by neuhaus** [comment]
Thanks @ashimokawa that workaround works for me!

**Comment by ashimokawa** [comment]
@neuhaus 
Did you see this problem ever see this in any other app?
I don't think we have any control over that dialog...

**Comment by neuhaus** [comment]
No, but I will consciously check to make sure.

**Comment by nonbinary** [comment]
I run English copperhead on a nexus 5x, and can grant permissions. Translation-specific error?

**Comment by danielegobbetti** [comment]
I will then close this issue. @neuhaus, please add this information/workaround to our wiki. Thanks!
