### ISSUE TITLE
Amazfit Bip weather problem

### ISSUE THREAD

**Issue by Black-Sunlight** [Freeyourgadget/Gadgetbridge#905]
Hello, on Amazfit Bip firmware 0.0.9.40+ there is the problem with transfer weather data (weather notification program) through GadgetBridge to Bip, there is min\max temp., current temp. and image, image and min\max transfers perfectly but current temp. don't transfers at all, can you please fix this till 0.22.5 release?
Android 7.0

**Comment by ashimokawa** [comment]
@Black-Sunlight 
0.22.5 has already been tagged, so it will be in the release after that
