### ISSUE TITLE
Small translation issues

### ISSUE THREAD

**Issue by Black-Sunlight** [Freeyourgadget/Gadgetbridge#906]
Can you please remove redundant line breaks from [values-ru/strings.xml](https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/res/values-ru/strings.xml)

Current version on some displays drags "Install" button (firmware install and etc.) down behind the visible border.

**Comment by danielegobbetti** [comment]
See https://hosted.weblate.org/projects/freeyourgadget/gadgetbridge/ru/
