### ISSUE TITLE
Amazfit bip: no whole day HR

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#907]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:

The Whole Day HR Rate feature is not working on my amazfit. It does not check my heart rate every minute.

#### Your wearable device is:

Amazfit bip 0.0.9.40

#### Your android version is:

8.0.0

#### Your Gadgetbridge version is:

0.22.4

**Comment by ashimokawa** [comment]
So.. How often does it check?

**Comment by roidelapluie** [comment]
Mmh now it looks normal. It checks every minute. But the watchface is not updated accordingly

**Comment by ashimokawa** [comment]
@roidelapluie 
About the watchface, yes, that is true, I dont know why the watchface only shows manual measurements ("status" menu on bip), not our fault I think.

Also, when you change the hr measurement option you have to reconnect.

I will close this, if mitfit updates the watchface, then please open a new issue.
