### ISSUE TITLE
Unable to upgrade firmware on Miband 2

### ISSUE THREAD

**Issue by JanKrAppel** [Freeyourgadget/Gadgetbridge#912]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
Updating the firmware from the on-device firmware it got delivered with, 1.0.1.52, to the version recommended in the Wiki, 1.0.1.54, fails when sending the firmware metadata after the transfer seems to complete (judging by the progress bar in the notification area). 

I've activated the logging option in the app settings, and restarted the app, but a log is not being saved. I'm happy to provide any additional info if needed.

#### Your wearable device is:
Miband 2, firmware version 1.0.1.52

#### Your android version is:
5.1

#### Your Gadgetbridge version is:
0.22.5

**Comment by ashimokawa** [comment]
There are multiple Mi Band 2 variants , which need a special firmware. Unfortunately we do not distinguish them properly.

If you unpack a mifit apk and look into assets , you will see various Mili_pro* files. The _i variant for example is the mi band hrx without hr.

I will have a look at the options later today and give you a guess which might be the one you need

**Comment by JanKrAppel** [comment]
How do I find out which variant I have? It's an ordinary looking Miband 2, with a heartrate monitor. In Gadgetbridge, it says FW 1.0.1.52, HW V0.16.2.2

**Comment by JanKrAppel** [comment]
Update: I deactivated the low latency option in the device settings that was said to help with firmware updates, it didn't fix the issue though.

**Comment by ashimokawa** [comment]
@JanKrAppel 

It should be one of these:

Mili_pro_tph_as7000.fw
Mili_pro_tph.fw
Mili_pro_tph_indian.fw

**You should not flash, unless you are willing to risk your band for the sake of experimenting.** The as7000 variant should be a different HR sensor.

When @cpfeiffer started Mi Band 2 support there was only one Variant, and all these new ones were not taken care of (yet).

HW V0.16.2.2 is definitely a hint. Mine is different.

**Comment by JanKrAppel** [comment]
Thanks for the warning. Sorry, I'm not willing to risk bricking it. I'll gladly provide what information I can though, if it helps development.

**Comment by ashimokawa** [comment]
According to this information:

https://4pda.ru/forum/index.php?showtopic=844807&st=1180#entry67230872

Your should flash:

Mili_pro_tph_as7000.fw

** I cannot guarantee that this is correct, flashing the firmware is always at your own risk.**

That being said I dont _believe_ that it will brick, just I cannot guarantee

**Comment by JanKrAppel** [comment]
Well, it didn't brick. The firmware update completed successfully, but the firmware version is unchanged. I took the firmware files from version 3.1.0-3195 of the apk, as is suggested in the wiki to obtain FW 1.0.1.54. According to your link, FW 1.0.1.67 should be released by now, so the question now is: How do I find out what the version of a firmware file is without flashing it? Then I could go through the rest of the apk files...

**Comment by ashimokawa** [comment]
Version .67 is in Mifit 3.1.9 iirc

The Firmware Version is stored as a string inside the .fw file. But there is no fixed offset and no alignment for it.

We already parse these for unknown files for Amazfit Bip and cor. I plan to add that for mi band 2 as well

**Comment by JanKrAppel** [comment]
Do I break functionality with Gadgetbridge if I flash .67?

**Comment by ashimokawa** [comment]
No, it should work with .67

**Comment by JanKrAppel** [comment]
After flashing .67, I had to delete and repair the device in Gadgetbridge, but everything seems to be working now. I'm closing this now, but if you still need data for development, I'll be glad to help.

**Comment by ashimokawa** [comment]
@JanKrAppel 

After flashing some firmware version you have to unpair the device in android settings and pair again by tapping the + button in Gadgetbridge

**No need to delete the device, you can keep your data ;)**

**Comment by JanKrAppel** [comment]
Too late, unfortunately. I didn't lose any data anyway, when I synced, all the data got redownloaded from the device. I only had one day to begin with.

Thanks for all your help!

Am 18. Dezember 2017 22:18:04 MEZ schrieb Andreas Shimokawa <notifications@github.com>:
>@JanKrAppel 
>
>After flashing some firmware version you have to unpair the device in
>android settings and pair again by tapping the + button in Gadgetbridge
>
>**No need to delete the device, you can keep your data ;)**

-- 
Fail spectacularly, and don't forget to take notes.

XMPP: jan@janappel.info
