### ISSUE TITLE
mi band 1 sync fails

### ISSUE THREAD

**Issue by kaefert** [Freeyourgadget/Gadgetbridge#915]
#### Your issue is:
I connected my Mi Band 1 (colored leds) to Gadgetbridge running on my Samsung Galaxy S5 SM-G900F (FW: NJH47F).
When syncing data it fails with the message "error buffering activity data: remaining bytes: 3, recieved: 4" in a toast. The statistics pages remain empty.
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1578577/gadgetbridge.log)

#### Your wearable device is:
Mi Band 1 (Colored LEDs) HW: 1, FW: 1.0.15.0

#### Your android version is:
7.1.2 (LineageOS 14.1.20171214-NIGHTLY-klte)

#### Your Gadgetbridge version is:
0.22.5

**Comment by ashimokawa** [comment]
Similar problem with Mi Band 1S fw  4.16.11.15

9 expecting 8.

**Comment by ashimokawa** [comment]
@cpfeiffer 
Are you willing to investigate?

**Comment by ashimokawa** [comment]
Should be fixed in master, needs testing

**Comment by kaefert** [comment]
I'm willing to test, but I need instructions how to build an apk after checking out master. The latest release on FDroid is older than your commit, so I guess it does not yet contain the fix. (last FDroid Version = 0.23.0 from 2017-12-24, your referenced commit dc51714 from 2017-12-28)

**Comment by ashimokawa** [comment]
Latest code is on fdroid

**Comment by kaefert** [comment]
ah perfect! I updated through fdroid and tried syncing again. no error visible. Have to check again in a few hours because I just synced with the original mi fit app and probably because of that there was no data to download.
attached my current gadgetbridge logfile: 
[gadgetbridge_2018-01-04_1032.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1602936/gadgetbridge_2018-01-04_1032.log)
