### ISSUE TITLE
Notification duration 

### ISSUE THREAD

**Issue by SLAP0** [Freeyourgadget/Gadgetbridge#918]
Device: Mi Band 2
FW: 1.0.1.69
HW: V0.9.3.4
Gadgetbridge 0.22.5
Phone: Android 6.0

After some time of trial and error I finally got my Mi Band to show text messages from WhatsApp but I have a few problems to which I haven't found any answers. They might not be implemented at all. 

When I get a WhatsApp message only half the message is shown on my Mi Band. Is it possible to increase the notification duration to show the whole message? Is it also possible to increase or decrease the speed of the text? Would it also be possible to show the last message again - at the push of the Mi Band button?

Thank you very much for your assistance.

**Comment by winterpgz** [comment]
+1
----
The notification duration on Mi Band2 is too short, I can hardly finish the half of the message before it goes off

**Comment by ashimokawa** [comment]
Not possible.
If you have proof that it works in mi fit, reopen.
