### ISSUE TITLE
Button actions on Amazfit BIP?

### ISSUE THREAD

**Issue by janos-pd** [Freeyourgadget/Gadgetbridge#924]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I tried to activate button actions for a BIP but it didn't seem work. (no vibration on the device and no debug logs by GB) Not sure if it's supposed to work at all with that device and firmware. 
Could someone please tell me how support for button actions on BIP can be made working?
Thanks.

#### Your wearable device is:
Amazfit BIP
V0.0.9.40

#### Your android version is:
7.0

#### Your Gadgetbridge version is:
0.23.0

**Comment by ashimokawa** [comment]
Not supported.
But could be easily enabled

**Comment by janos-pd** [comment]
Do you mean that  it's not supported by GB, but supported by the device?
I'll check the code, let's see if i can understand how it works for the MI Band

**Comment by janos-pd** [comment]
Updated my pull request with an extra confirmation feature. See #925

**Comment by bestlibre** [comment]
Any news on this one ? I would also like to use the amazfit bip button to trigger action on my phone.

**Comment by ffranchina** [comment]
Is there any news about the action button on BIP device? It's one of the most essential feature of the device.
Can someone, please, update us about the process of making it work? It would be great to help to get the things done! :D

**Comment by robertio** [comment]
Hi, 
Im also interested on this feature. 
I tried to use this intent from tasker, with intent received event profile, but does not worksed.
see the relevant logs from GB: 
`
12:04:12.462 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.34.1
12:04:39.762 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
12:04:39.763 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
12:04:39.844 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
12:04:39.888 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
12:04:43.751 [Binder:5013_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000010-0000-3512-2118-0009af100700 value: 0x04
12:04:43.755 [Binder:5013_1] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000010-0000-3512-2118-0009af100700
12:04:43.760 [Binder:5013_1] INFO  n.f.g.s.d.h.HuamiSupport - button pressed
12:04:44.144 [Binder:5013_3] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000010-0000-3512-2118-0009af100700 value: 0x04
12:04:44.146 [Binder:5013_3] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000010-0000-3512-2118-0009af100700
12:04:44.148 [Binder:5013_3] INFO  n.f.g.s.d.h.HuamiSupport - button pressed
12:04:44.530 [Binder:5013_2] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000010-0000-3512-2118-0009af100700 value: 0x04
12:04:44.534 [Binder:5013_2] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000010-0000-3512-2118-0009af100700
12:04:44.538 [Binder:5013_2] INFO  n.f.g.s.d.h.HuamiSupport - button pressed
12:04:44.918 [Binder:5013_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000010-0000-3512-2118-0009af100700 value: 0x04
12:04:44.923 [Binder:5013_1] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000010-0000-3512-2118-0009af100700
12:04:44.925 [Binder:5013_1] INFO  n.f.g.s.d.h.HuamiSupport - button pressed
12:04:52.021 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
12:04:52.021 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
12:04:52.116 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
12:04:52.170 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
12:18:09.127 [main] INFO  n.f.g.Logging - Gadgetbridge version: 0.34.1
12:18:15.850 [Binder:5013_2] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000010-0000-3512-2118-0009af100700 value: 0x04
12:18:15.855 [Binder:5013_2] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000010-0000-3512-2118-0009af100700
12:18:15.859 [Binder:5013_2] INFO  n.f.g.s.d.h.HuamiSupport - button pressed
12:18:16.238 [Binder:5013_3] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000010-0000-3512-2118-0009af100700 value: 0x04
12:18:16.240 [Binder:5013_3] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000010-0000-3512-2118-0009af100700
12:18:16.241 [Binder:5013_3] INFO  n.f.g.s.d.h.HuamiSupport - button pressed
12:18:16.629 [Binder:5013_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000010-0000-3512-2118-0009af100700 value: 0x04
12:18:16.633 [Binder:5013_1] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000010-0000-3512-2118-0009af100700
12:18:16.636 [Binder:5013_1] INFO  n.f.g.s.d.h.HuamiSupport - button pressed
12:18:18.577 [Binder:5013_2] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000010-0000-3512-2118-0009af100700 value: 0x04
12:18:18.580 [Binder:5013_2] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000010-0000-3512-2118-0009af100700
12:18:18.583 [Binder:5013_2] INFO  n.f.g.s.d.h.HuamiSupport - button pressed
12:18:18.967 [Binder:5013_3] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000010-0000-3512-2118-0009af100700 value: 0x04
12:18:18.971 [Binder:5013_3] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000010-0000-3512-2118-0009af100700
12:18:18.974 [Binder:5013_3] INFO  n.f.g.s.d.h.HuamiSupport - button pressed
12:18:18.981 [Binder:5013_3] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000010-0000-3512-2118-0009af100700 value: 0x04
12:18:18.985 [Binder:5013_3] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000010-0000-3512-2118-0009af100700
12:18:18.988 [Binder:5013_3] INFO  n.f.g.s.d.h.HuamiSupport - button pressed
12:18:19.358 [Binder:5013_1] DEBUG n.f.g.s.b.BtLEQueue - characteristic changed: 00000010-0000-3512-2118-0009af100700 value: 0x04
12:18:19.361 [Binder:5013_1] INFO  n.f.g.s.d.h.o.InitOperation - Unhandled characteristic changed: 00000010-0000-3512-2118-0009af100700
12:18:19.365 [Binder:5013_1] INFO  n.f.g.s.d.h.HuamiSupport - button pressed
12:18:47.920 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.start
12:18:47.921 [main] DEBUG n.f.g.s.DeviceCommunicationService - Service startcommand: nodomain.freeyourgadget.gadgetbridge.devices.action.request_deviceinfo
12:18:48.029 [main] INFO  n.f.g.s.DeviceCommunicationService - Setting broadcast receivers to: true
12:18:48.081 [main] INFO  n.f.g.e.NotificationListener - Ignore notification
`

and see the relevant logs from Tasker:
22-07-2019 M: 12.18.02#b#M: added launch intent: nodomain.freeyourgadget.gadgetbridge
22-07-2019 M: 12.18.02.837#b#M: process inbox, size 1 startID: -1 ecode 9997
22-07-2019 TaskerContext: 12.18.02#b#TaskerContext: checkMatch: nodomain.freeyourgadget.gadgetbridge wantApp: true
22-07-2019 TaskerContext: 12.18.02#b#TaskerContext: checkMatch: nodomain.freeyourgadget.gadgetbridge wantApp: true
22-07-2019 TaskerContext: 12.18.02#b#TaskerContext: checkMatch: nodomain.freeyourgadget.gadgetbridge wantApp: true
22-07-2019 TaskerContext: 12.18.02#b#TaskerContext: checkMatch: nodomain.freeyourgadget.gadgetbridge wantApp: true
22-07-2019 TaskerContext: 12.18.02#b#TaskerContext: checkMatch: nodomain.freeyourgadget.gadgetbridge wantApp: true
22-07-2019 NLI: 12.18.02#m#NLI: tickerText: Amazfit Bip Watch - Connected: Battery 32%


Is there any progress on BIP button pressed event sending to other app?

Best regards,
Robert

**Comment by diaasami** [comment]
I believe this was just added in the version 0.39.1, I tried it and I think it works. 
![Screenshot_20191126-111742_Gadgetbridge](https://user-images.githubusercontent.com/4257328/69620977-85618900-103e-11ea-803c-fa30f0a2de34.jpg)

**Comment by ashimokawa** [comment]
@diaasami
Correct
