### ISSUE TITLE
Request for Android 4.3 support 

### ISSUE THREAD

**Issue by oioenukc** [Freeyourgadget/Gadgetbridge#926]
HI, guyz!
I am trying to use my Peebble 2 with Blackberry Passport.
Original Peebble app for Android just not functional on connecting
to watches endlessly without succsses.
Is it possible to add Android 4.3 support (such version is on BBOS 10 Android enviroment).

Thank you!

,

**Comment by cpfeiffer** [comment]
We use many Java 7 features and don't have the resources to change and maintain Java 6 source compatibility, sorry.
