### ISSUE TITLE
Vibrate Mi Band 2

### ISSUE THREAD

**Issue by JuanEsail** [Freeyourgadget/Gadgetbridge#928]
#### Before opening an issue please confirm the following:
- [Y] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [Y] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [Y] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
question

#### Your wearable device is 
Mi Band 2

#### Your android version is: 
Android 7.0.0

#### Your Gadgetbridge version is: last.

I´m developing an app to connect to my Mi Band 2. Using this Opens Source project I have got connect and pair to my Mi Band 2. But I can´t get vibrate my Mi Band 2. Please help to get that. 

The code I use to vibrate:
 

```
void startVibrate() {
        BluetoothGattCharacteristic bchar = bluetoothGatt.getService(UUIDs.IMMEDIATE_ALERT_SERVICE).getCharacteristic(UUIDs.ALERT_LEVEL_CHARACTERISTIC);
        bchar.setValue(new byte[]{2});

        if (!bluetoothGatt.writeCharacteristic(bchar)) {
            Toast.makeText(this, "Failed start vibrate", Toast.LENGTH_LONG).show();
        }

        startVibrateService();
    }
```

    void startVibrateService() {
        BluetoothGattCharacteristic bchar = bluetoothGatt.getService(UUIDs.ALERT_NOTIFICATION_SERVICE).getCharacteristic(UUIDs.NEW_ALERT_CHARACTERISTIC);
        bchar.setValue(new byte[]{2});

        if (!bluetoothGatt.writeCharacteristic(bchar)) {
            Toast.makeText(this, "Failed start vibrate", Toast.LENGTH_LONG).show();
        }

    }

And the corresponding UUIDs:

![image](https://user-images.githubusercontent.com/30147204/34561765-d9dea4b8-f14b-11e7-8850-929e4a8cab27.png)

And the Log console show that error: **I/HwPointEventFilter: do not support AFT because of no config**

But I have got some Mi Band 2 data like heart rate, and other info about the band.

**Comment by abelduran1** [comment]
I have the same problem!  I use this:

    private void alertNotification() {
        variableService = bluetoothGatt.getService(UUIDs.ALERT_NOTIFICATION_SERVICE);
        try {
            for (BluetoothGattCharacteristic characteristic : variableService.getCharacteristics()) {
                bluetoothGatt.setCharacteristicNotification(characteristic, true);
                bluetoothGatt.readCharacteristic(characteristic);
                synchronized (object) {
                    object.wait(2000);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void immediateAlert() {
        variableService = bluetoothGatt.getService(UUIDs.IMMEDIATE_ALERT_SERVICE);
        try {
            for (BluetoothGattCharacteristic characteristic : variableService.getCharacteristics()) {
                bluetoothGatt.setCharacteristicNotification(characteristic, true);
                bluetoothGatt.readCharacteristic(characteristic);
                synchronized (object) {
                    object.wait(2000);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


But I don´t get make vibration.
