### ISSUE TITLE
Gadgetbridge for linux (LIBREM 5)

### ISSUE THREAD

**Issue by pichu66** [Freeyourgadget/Gadgetbridge#931]
Hi, 
In your goal to protect user's privacy , do you plan to release a Gadgetbridge version for the upcoming smartphone "Librem 5" who run Linux OS?
Thanks for your hard work!

**Comment by ashimokawa** [comment]
@pichu66 

Personally, I would like to ditch Android for a real free alternative. But after the totally unbelievably crappy Ubuntu Touch, which actually made me buy a compatible device, I have very very little faith in such a product. If it succeeds (which I highly doubt but still hope), I will buy it. But I won't pre-order anything.

That being said, porting Gadgetbridge to GNU/Linux will be impossible, so it would have to be a complete rewrite. One way of re-using at least *some* code would be if we port Gadgetbridge to Kotlin and Kotlin/Native would become something useful.

But let's first see if the Librem 5 will be built at all. ;)
