### ISSUE TITLE
Long Press Mi Band 2

### ISSUE THREAD

**Issue by abelduran1** [Freeyourgadget/Gadgetbridge#932]
#### Before opening an issue please confirm the following:
- [Yes] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [Yes] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [Yes] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*

#### Your wearable device is: Mi Band 2

I´m developing a software that connect with Mi Band 2 in Android. ¿How can I detect a long press? I actually detect a short press but not a long. I haven't found it in gadgetbridge app.

Thanks in advance.

**Comment by vanous** [comment]
Hello, if you haven't found this in Gadgetbridge, then you probably have to look at some other places, sorry for not being able to help. Please consider closing this issue if your question has been answered, thank you.

**Comment by abelduran1** [comment]
Okay, I'm going to close this issue. But I haven´t found a solution. The alternative is maybe use a double press.
