### ISSUE TITLE
Error upload watchface file to xiaomi bip 

### ISSUE THREAD

**Issue by bdfy** [Freeyourgadget/Gadgetbridge#934]
I  use  xiaomi bip and try to upload binary file ( custom watchface ) and see error:
`[ : element cannot be installed.]`
Version 0.23.2. 
Downgrade to version 0.23.1  solves this problem

http://s000.tinyupload.com/index.php?file_id=02281535921549711161

**Comment by ashimokawa** [comment]
Works for me

**Comment by bdfy** [comment]
Work for last version from git

**Comment by ashimokawa** [comment]
There is no change in latest git. I guess your bip was disconnected when you tried 0.23.2

**Comment by fajabird** [comment]
I would like to reopen this ticket. I'm on GB 0.34, connection is stable as I can install all parts of the firmware (.fw, .res, ...) but as soon I select a watchface file (.bin) I get the error message "element cannot be installed". I use the stock LineageOS 16 file browser.

**Comment by ashimokawa** [comment]
Can you send a link to that watchface?

**Comment by fajabird** [comment]
Sure: https://amazfitwatchfaces.com/do/dl?dir=bin&file=marat_s_v12-20448-72c5d6f6f8.bin&dt=10&wid=24180&d=bip

**Comment by fajabird** [comment]
If above does not work use this: https://amazfitwatchfaces.com/bip/view/24180
and select download, that choose latest file (at bottom, v12)

**Comment by ashimokawa** [comment]
Works for me :(

Lineage 16.0 , stock file Browser.

**Comment by fajabird** [comment]
So what do I wrong? Firmware updates do work. Is there a way to See a debug low indicating the root cause?

**Comment by fajabird** [comment]
May I ask how you downloaded the bin file? Browser or app (which)?

**Comment by fajabird** [comment]
Downloading the bin files with a Browser caused the issue for me. Using an APP I was able to flash them. Thank you very much for your support.

**Comment by imagoiq** [comment]
I got the same issue using Firefox Preview, but it was working with Chrome on Android 8
