### ISSUE TITLE
No scrolling for alarm settings

### ISSUE THREAD

**Issue by ejiek** [Freeyourgadget/Gadgetbridge#935]
#### Your issue is:
I'm using rather old phone with small display (320x480). It's not possible to change days of the alarm on this screen coz of lack of scrolling.

![image](https://user-images.githubusercontent.com/7649041/34654628-7ea2a6fa-f40f-11e7-9dd5-5b8ee9f60a5b.png)

#### Your wearable device is:
Mi Band 1S
Firmware 4.16.11.15

#### Your android version is:
5.1.1 (LineageOS 12.1.1)

#### Your Gadgetbridge version is:
0.23.2

**Comment by ejiek** [comment]
Thanks for the fix attempt. I'll try to build and test it in a couple of days.

**Comment by ejiek** [comment]
update. I'm having troubles building this app locally. Mostly due to the lack of time during exams. This way I'm still interested in this issue and invistigating my build problems every day but just for 10 minus. There will be more free time after this week.

**Comment by danielegobbetti** [comment]
@ejiek the current release on f-droid contains the fix, hence you can try to simply upgrade instead of self compile.

**Comment by ejiek** [comment]
@danielegobbetti doesn't work with 0.24.1 =\

**Comment by ashimokawa** [comment]
@ejiek 
Ok thanks for testing, I will test this in an emulator then

**Comment by ejiek** [comment]
@ashimokawa mb it's also possible to test in 'split screen' mode if your device supports it.

**Comment by danielegobbetti** [comment]
@ejiek Thanks for the idea. It allowed me to fix this.
Next version should allow scrolling on small screens. If this is not the case feel free to reopen this issue!

**Comment by ejiek** [comment]
Fix approved! Works for me now =]

Thanks for the work!
