### ISSUE TITLE
MiBand 2 works fine with FW 1.0.1.69

### ISSUE THREAD

**Issue by eRaz3r** [Freeyourgadget/Gadgetbridge#939]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I upgraded to the FW 1.0.1.69 from the MiFit-App 3.2.4-3216 on my MiBand 2 (HW V.0.9.3.4) yesterday. Everything is working good, there are no issues i recognized.

#### Your wearable device is:
MiBand 2 (HW V.0.9.3.4)

#### Your android version is:
7.1.1

#### Your Gadgetbridge version is:
0.23.2

**Comment by IzzySoft** [comment]
So your issue here is that everything works and you have no issues? I wish I had that issue more often :wink:

**Comment by ashimokawa** [comment]
@IzzySoft 
You mean background js not working for you? Or something else 😛

**Comment by eRaz3r** [comment]
In Gadgetbridge-App there were an ask for information about working firmware. So I submit that this firmware worked for me. In App the FW is in Status "not tested" and I think it can be marked as tested. Thats all. If there were a "send a message" function in the App, i had use this.

**Comment by ashimokawa** [comment]
I got that and marked it as tested.

**Comment by IzzySoft** [comment]
@ashimokawa Nothing personal like that – but as you ask: yes, amongst other things, and not all related to GB :rofl:

@eRaz3r I vaguely remember that. So your results are definitely appreciated – it's just confusing when reported as "issue". Would have better be a comment on that specific issue :wink: But I see Andreas interpreted it correctly as an "request to add this FW added to the whitelist" :innocent::+1:

**Comment by eRaz3r** [comment]
@IzzySoft Everything is okay. I only want to share my reasons with you 😉 

@ashimokawa Thank you
