### ISSUE TITLE
telephony required?

### ISSUE THREAD

**Issue by leonaard** [Freeyourgadget/Gadgetbridge#94]
F-droid on my wifi-only tablet shows the app as unavailable because it requires `android.hardware.telephony`, but it works fine if i force the installation.

**Comment by ashimokawa** [comment]
It's an f-droid bug or shortcoming.
We have to request that permission since we want to be able to reject calls with the pebble.
It is optional and works perfectly on a tablet with wifi-only, but I don't know if there is a way to specify it in our f-droid metadata file.

**Comment by ashimokawa** [comment]
Maybe I spoke to fast.
I set android.hardware.telephony to not required in the manifest.
Hope it helps. We will see after 0.5.1(tagged today) hits f-droid.

**Comment by ashimokawa** [comment]
Fixed in commit ba6bdad0
Shipped in 0.5.1.
Thanks for reporting.
