### ISSUE TITLE
Holds wake lock (miband 2)

### ISSUE THREAD

**Issue by nehz** [Freeyourgadget/Gadgetbridge#941]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [ ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
Gadgetbridge seems to hold wake lock if the device is connected. Disconnecting manually seems to remove the lock.
Connect to device when Bluetooth is available is off
Reconnect automatically is off

#### Your wearable device is:
Miband 2

HW: 0.1.3.3
FW: 1.0.1.39

#### Your android version is:
5.1

#### Your Gadgetbridge version is:
0.23.2

**Comment by ashimokawa** [comment]
@nehz 
Is this any different with Mifit?
I am not sure if this is beyond our control or not - at least this is not anything we do intentional.

**Comment by nehz** [comment]
Seems to be ok with Mifit

**Comment by cpfeiffer** [comment]
How did you find out about the wake locks? We don't deliberately hold any wake locks at all. See https://stackoverflow.com/questions/5780280/how-can-i-see-which-wakelocks-are-active for debugging this.

**Comment by nehz** [comment]
Ok cool good to now ... I think it might be related to the generic notifications, but I'll debug it myself for now and reopen it if I find it related to Gadgetbridge
