### ISSUE TITLE
Mi Band: Changing the wear location in the options menu has no effect

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#95]
First of all, I want to thank you for this awesome app. I really appreciate the great work you are doing here! Being a person that is always concerned about privacy, I can't use the original app. So finding this app on f-droid made my day.

I wear the Mi Band on my right arm, so I changed the wear location to "right" in the options menu. Unfortunately, this change doesn't take effect.
I can confirm this, because the Mi gesture (turning the wrist) with the Mi Band on the right arm does not show my activity status (LEDs flashing), while it still responds to the gesture when wearing it on the left arm.

Thanks for your help!

Gadgetbridge v: 0.4.6 (also tried 0.4.5)
Mi Band FW: 1.0.9.3

**Comment by danielegobbetti** [comment]
Hi @6arms1leg thanks for reporting this bug. It should be closed in the next release.

**Comment by 6arms1leg** [comment]
Hey @danielegobbetti!

Wow, that was fast! :runner: Thank you!
