### ISSUE TITLE
Feature: Installing watch faces (from amazfitwatchfaces.com) from within the app

### ISSUE THREAD

**Issue by clemens68** [Freeyourgadget/Gadgetbridge#956]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
There are so many cool watch faces, mainly at https://amazfitwatchfaces.com/. Although you can install watchfaces from there and then launching GB it is still "hassle"...
It would be nice if adding/installing watchfaces was integrated into GB.

As this feature does exist for pebble-watches I guess there is an API/SPI for fetching and/or installing wachfaces?

#### Your wearable device is:
Amazfit Bip, Fw 0.1.0.51

#### Your Gadgetbridge version is:
0.24.1

**Comment by danielegobbetti** [comment]
Gadgetbridge doesn't have internet access, hence it cannot access any website, be it for downloading watchfaces or uploading data.

FYI the procedure to install a pebble watchface/watchapp is exactly the same that you are using, namely download the file externally and then open it with gadgetbridge to flash/send it to the watch.

**Comment by clemens68** [comment]
Thx for the reply and clarification!
