### ISSUE TITLE
Force close when trying to change "Export interval"

### ISSUE THREAD

**Issue by clemens68** [Freeyourgadget/Gadgetbridge#958]
#### Before opening an issue please confirm the following:
- [X] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*When I try to change the "Export interval" in the settings and press "Ok" the GB app does a force close*

#### Your wearable device is:
Amazfit Bip

*Please specify model and firmware version if possible*
0.1.0.66

#### Your android version is:
Oreo, PixelExperience (on Xiaomi Redmi Note 4X)

#### Your Gadgetbridge version is:
0.24.1

**Comment by cpfeiffer** [comment]
Thanks for the report, this is already fixed in master for the next release.
