### ISSUE TITLE
Mi Band: Add "neck" as a wear location option

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#96]
Hello again!

I would be nice, if it was possible to select "neck" as wear location for the Mi Band in the options menu.
Many thanks for this wonderful app!

**Comment by danielegobbetti** [comment]
Hello @6arms1leg , this would require blindly guessing the values to send to the band to set nech as wear location, if you know the value or can think of a test to see if the wear location was received correctly then we can certainly implement this!

**Comment by 6arms1leg** [comment]
Oh OK. Sorry, I wasn't aware of this. I thought the Mi Band protocol and its values were completely reverse-engineered...
Unfortunately, I don't know the value and there also isn't any progress indication feature for the neck wear location, so to test it might be difficult.
If I can think of a way to fetch the value for the "neck" option, I will let you know.

**Comment by danielegobbetti** [comment]
I'm closing this issue for now, please reopen it in case of news :)
