### ISSUE TITLE
Add process of installing miband2 fonts to main README

### ISSUE THREAD

**Issue by NotAFile** [Freeyourgadget/Gadgetbridge#967]
After using GadgetBridge with the Miband2, I was dissapointed that it didn't seem to support text messages.

But no, it turns out that the firmware just contains no fonts by default! The process of obtaining and installing those fonts should probably be documented on the main page and in the wiki.

**Comment by cpfeiffer** [comment]
Added it to the README, also thanks for adding this to the wiki. I had only documented it in the issue back then.
