### ISSUE TITLE
Crashes when changing database export interval 

### ISSUE THREAD

**Issue by nate2014jatc** [Freeyourgadget/Gadgetbridge#968]
#### Before opening an issue please confirm the following:
- [ ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*
Crashes when changing database export interval #### Your wearable device is:

*Please specify model and firmware version if possible*
Pebble 2 HR on FW:v4.3
#### Your android version is:
7.1.2
#### Your Gadgetbridge version is:
0.24.1
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1683899/gadgetbridge.log)

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by NotAFile** [comment]
This is already fixed in #953!

**Comment by nate2014jatc** [comment]
My bad, only checked active issues.

Any idea when it'll be pushes to the F-Droid? 

On January 31, 2018 7:16:11 PM MST, NotAFile <notifications@github.com> wrote:
>This is already fixed in #953!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Freeyourgadget/Gadgetbridge/issues/968#issuecomment-362136429

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cpfeiffer** [comment]
According to this page https://f-droid.org/wiki/page/nodomain.freeyourgadget.gadgetbridge it's already built and just need to be published by f-droid.

**Comment by ashimokawa** [comment]
@nate2014jatc 
0.24.2 is out on f-droid now.
