### ISSUE TITLE
Pebble 2 updates to 100% then fails the update.

### ISSUE THREAD

**Issue by qchroman** [Freeyourgadget/Gadgetbridge#971]
#### Before opening an issue please confirm the following:
- [x ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I've bought Pebble 2 from ebay. Yes yes, I know, it's 2018 outside, but watch looks great and I wanted to try it. I couldn't get past the update from the factory stage with official so I tried flashing https://pebblefw.s3.amazonaws.com/pebble/silk/release-v3.8/pbz/Pebble-4.3-silk.pbz using Gadgetbridge. Unfortunately - no luck. I gets to 100% and then shows update failed.

I attached logs and information about the device from Gadgetbridge.

#### Your wearable device is:
Pebble 2, v4.0.1-prf6, silk

#### Your android version is:
Android is 7.0 running on Samsung S6

#### Your Gadgetbridge version is:
0.24.1
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1687216/gadgetbridge.log)
![screenshot_20180201-230052](https://user-images.githubusercontent.com/2488410/35703413-98abe734-07a4-11e8-8d08-484653ed8b36.png)

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
@qchroman 
The Pebble2 is a great device, even in 2018. 👍 

You said you could not flash with the official app, did the update also go to 100% and then fail? Or was there another problem.

When the update fails, does Gadgetbridge say "failed", or only the watch? Is the log you posted complete to the very end? It seems to just stop. And I might miss the interesting part.

**Comment by qchroman** [comment]
I hope to enjoy them with your help :)

With official app the update goes up to 50% and then fails. When I used Gadgetbridge it showed me that the following. Not in the app though.

![screenshot_20180202-002309](https://user-images.githubusercontent.com/2488410/35706732-8d732886-07af-11e8-83b6-fc8a4be89c8e.png)
[gadgetbridge (1).log](https://github.com/Freeyourgadget/Gadgetbridge/files/1687447/gadgetbridge.1.log)

Log seems truncated, I will try with logcat tomorrow. Or, if you have instructions, please, let me know.

Thank you very much for blazing fast response!

BR

**Comment by ashimokawa** [comment]
@qchroman 
The firmware update consists of two parts. Firmware and "resources", I guess the first part is 50% and the second also. We however count this as two files being installed. That is why it fails at 100% on Gadgetbridge.

You can try to lower the MTU in pebble settings in Gadgetbridge to a very low one (23), the update will take much much longer then but might succeed. 

The worst case could be that your watch is broken, maybe you can try the initial fw installation on another phone of a friend to rule out that possibility?

**Comment by qchroman** [comment]
I will try with two more phones I have an see if results will be different. Currently, with my S6 I tried every option from 20 - 30 and it didn't change anything. If you need any information, please, let me know.

Will try with S7 and A3 (2017) next.

BR

**Comment by qchroman** [comment]
Tried on S7 Edge, same problem, even with MTU set to 23. No update through original app as well.
[gadgetbridge-2018-02-02.0.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1689124/gadgetbridge-2018-02-02.0.log)

I think this item may be doomed to be just a piece of plastic.

**Comment by ashimokawa** [comment]
@qchroman 
Sorry to hear that, did you buy that used from a bad person, or was it brand new?

**Comment by qchroman** [comment]
Bad person :) ... no, I don't thinks. Not sure he knew that this issue existed. He's going to exchange for another unit. Will try with that.

Thank you for your help @ashimokawa !

**Comment by ashimokawa** [comment]
Closng this, because it obviously was a hardware fault
