### ISSUE TITLE
Canned responses not showing on pebble time

### ISSUE THREAD

**Issue by nighthawk321** [Freeyourgadget/Gadgetbridge#974]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is: The canned message section on the app doesn't allow for the canned messages to be updated on the watch. When I get a text message, the alert on the watch only allows dismissing the message and open on watch.
*In case of a bug, do not forget to attach logs!*

#### Your wearable device is: Kickstarter pebbletime (snowy4), firmware version 4.3 
*Please specify model and firmware version if possible*

#### Your Gadgetbridge version is:  0.24.2

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
Enable untested features
