### ISSUE TITLE
Fails to discover a "Q8" watch (HPlus device)

### ISSUE THREAD

**Issue by dgm3333** [Freeyourgadget/Gadgetbridge#978]
Fails to discover a "Q8" watch (HPlus device)
Wondering if I can do anything to force discovery and bonding (eg manually enter the BLE address)?
I've read the https://github.com/Freeyourgadget/Gadgetbridge/wiki/New-Device-Tutorial page, but don't really understand it, and wouldn't know where to start building Gadgetbridge from scratch...

BLE Scanner instantly discovers it (as Q82543)
"HPlus Watch" App on android bonds immediately

GadgetBridge just spins it's scanning icon indefinitely and never discovers the watch.
I've tried various different phone configs and it doesn't seem to matter if the watch is bonded to the phone or not), nor whether HPlus is uninstalled/installed/running/bonded.

cpu: Nordic nRF51822 
firmware: q8 81bf2543 v3.52
Android version: 7.0
Gadgetbridge version: 0.24.2

https://www.banggood.com/Q8-IP68-Blood-Pressure-Heart-Rate-Monitor-Fitness-Tracker-Smart-Wristband-Bracelet-For-iOS-Android-p-1178495.html

**Comment by cpfeiffer** [comment]
We detect many devices by their Bluetooth device name. So we don't automatically support compatible, but differently named devices. I intend to change that.

**Comment by tiparega** [comment]
Hello. I added the code for "Q8..." names and tested it and it works for me. I attach the patch. Tell me if I should do it in another way.

[Added_support_for_Q8_devices.patch.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/2020484/Added_support_for_Q8_devices.patch.zip)

**Comment by ashimokawa** [comment]
Closed by merging #1101
