### ISSUE TITLE
Current temperature not synchronized with amazfit bip

### ISSUE THREAD

**Issue by netmen5** [Freeyourgadget/Gadgetbridge#980]
Current temperature doen't sync with Amazfit Bip.
I getting min and max temperature but using Mi fit also i getting current temp. This is needed for custom watch faces:
https://amazfitwatchfaces.com/bip/view/?id=828

#### Your wearable device is:
Amazfit Bip

Android version is: 7.1.1
Your Gadgetbridge version is: Current

**Comment by ashimokawa** [comment]
@netmen5 
The current temperature is synced by Gadgetbridge. If it is not up-to-date then the Bip will ignore it.

To have Gadgetbridge update the weather you have to have "Weather Notification" installed, or if you are in LineageOS or Omnirom, you can use their weather providers.

**Comment by ashimokawa** [comment]
Also see #995

**Comment by danielegobbetti** [comment]
Closing as the functionality seems to work for multiple users and there was no feedback in a month.

**Comment by Pepe404** [comment]
I confirm this issue, current temperature not displayed (on the watchface, that supports it), only min/max. LG G2, Lineage 15.1, Weather Notification.
