### ISSUE TITLE
Amazfit bip connect app to retry

### ISSUE THREAD

**Issue by bilbo1966** [Freeyourgadget/Gadgetbridge#983]
A few days ago I installed a watchface on my watch. At the end of the clock it was hung up and left with the message "Connect APP to retry".
Since then I've only been able to connect through Gadgetbridge, I try to reinstall the firmware and RES file but I get an error when I finish installing the firmware.
Attached I send the log that generates me gadgetbridge.
I've also noticed that from the application I can do a "Heart rate test", but I can't do "Reboot".

Can someone help me?
Oh, thank you.

Translated with www.DeepL.com/Translator
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1707193/gadgetbridge.log)
[gadgetbridge-2018-02-08.0.log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1707194/gadgetbridge-2018-02-08.0.log.zip)
[gadgetbridge-2018-02-08.1.log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1707195/gadgetbridge-2018-02-08.1.log.zip)
[gadgetbridge-2018-02-08.2.log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1707196/gadgetbridge-2018-02-08.2.log.zip)
[gadgetbridge-2018-02-08.3.log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1707197/gadgetbridge-2018-02-08.3.log.zip)
[gadgetbridge-2018-02-08.4.log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1707198/gadgetbridge-2018-02-08.4.log.zip)
[gadgetbridge-2018-02-08.5.log.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/1707199/gadgetbridge-2018-02-08.5.log.zip)

Mi android versión es 6.0
My device Amazfit Bip

**Comment by TaaviE** [comment]
Can you provide your GadgetBridge version number?

**Comment by ashimokawa** [comment]
Please try to flash the fw and then the res file. I also get this "retry" screen sometimes after flashing the fw and then after flashing res it just goes away.

Which firmware version do you have?
If you have  0.1.0.66 or greater and told gadget bridge to switch to Spanish you also need to flash the Latin font

**Comment by bilbo1966** [comment]
In this moment 0.24.2, but I've tried several versions.
    En jueves, 8 de febrero de 2018 15:07:09 CET, Taavi <notifications@github.com> escribió:  
 
 
Can you provide your GadgetBridge version number?

**Comment by bilbo1966** [comment]
I have the 0.10.43 version. Sometimes I try first the fw file and others with res, both ways fails.
Around 30 days the clock was fine, but the other day fails with the watchface installation.
During the time the clock worked, it was in Spanish.


    En jueves, 8 de febrero de 2018 16:54:03 CET, Andreas Shimokawa <notifications@github.com> escribió:  
 
 
Please try to flash the fw and then the res file. I also get this "retry" screen sometimes after flashing the fw and then after flashing res it just goes away.

Which firmware version do you have?
If you have 0.1.0.66 or greater and told gadget bridge to switch to Spanish you also need to flash the Latin font

**Comment by ashimokawa** [comment]
@bilbo1966 
If you have version 0.1.0.43, there was no Spanish inside that firmware. Did you flash an unofficial translation from a forum?

The first non beta firmware which has Spanish is 0.1.0.70 from Mi Fit 3.2.7, maybe you want to try that? Also note that you have to match the firmware and res file exactly, you cannot flash a later firmware with an old res.

**Comment by bilbo1966** [comment]
@ashimokawa 
I installed a Spanish-language firmware for a telegram forum.
I've tried several versions of My fit, when I link them the clock asks me to accept, that's when the connection is blocked, the mobile tells me that it can't be linked. Restart the Bluetooth and try again.
I have already deleted the Bluetooth data, restarted the mobile phone, etc. and still give the same error.
I tried the latest version of my Google Play MyFit (3.2.7) and the latest version of APK mirror (3.2.8) and with both I get the same error.
The only program that connects the Gadgetbridge.

**Comment by danielegobbetti** [comment]
I'm sorry to be *that* guy, but you just can't expect to: 
1. run an unofficial firmware taken from some random source
1. use the official app, having issues with it
1. get support about the issues you are having with the official app from a third party project

Our recommendation has always been in our wiki and our blog:
1. do not run unknown/untrusted binaries taken from the internet
1. do not run Gadgetbridge and the official app side-by-side, as there might be unexpected consequences

First thing you have to do in my opinion, is to decide whether you want to use the official app or Gadgetbridge (as @ashimokawa already told, the official firmware contains spanish language, so you can probably use only the official app and call it a day)

Then you have to reach a "stable" situation: 
1. update gadgetbridge to the latest version from fdroid
1. get an updated **officially released, stable** firmware, res and gps 
1. follow the instructions on our wiki to flash them to your watch
1. at this point you can uninstall Gadgetbridge and use the official app, if you prefer, or uninstall the official app and keep only Gadgetbridge installed

I'm closing this issue as it is not related to the project at all, but feel free to add further comments if you have trouble following the steps above
