### ISSUE TITLE
Amazfit Cor firmware 1.0.6.76 testing confirmation

### ISSUE THREAD

**Issue by opokhvalit** [Freeyourgadget/Gadgetbridge#984]
short report: I downgraded firmware on my Amazfit Cor via Gadgetbridge from 1.0.7.23 to 1.0.6.76 (which was extracted from official Mi Fit 3.2.6) succesfully. So, you can mark firmware 1.0.6.76 as 'tested'

**Comment by danielegobbetti** [comment]
Can you please provide the numbers shown on the installer screen?

**Comment by opokhvalit** [comment]
sure.
1. Firmware update:
firmware 1.0.6.76, version number for developers: 54213
2. Resources update:
Res 48, version number for developers: 64977
PS. I repeat downgrade two days ago (new Mi Fit had updated firmware, but it has some bugs), and flashing procedure was successful second time without problems

**Comment by opokhvalit** [comment]
Ah, sorry, I forgot provide version of gadgetbridge
It is 0.24.2

**Comment by danielegobbetti** [comment]
Thanks! It will be whitelisted in the next release.
