### ISSUE TITLE
Amazfit BIP and problem with transliteration

### ISSUE THREAD

**Issue by tomurbanowicz** [Freeyourgadget/Gadgetbridge#987]
Please add "Ł" and "ł" to transliterate in GadgetBridge, becouse that letters are not added to transliterate

I sent to my watch that string:
ĄĆĘŁŃÓŚŹŻąćęłńóśźż

and I received:
ACE?NOSZZace?noszz

![trans](https://user-images.githubusercontent.com/31843138/36059912-99afe266-0e3e-11e8-8fb0-640a726a00b2.jpg)

#### Your wearable device is:
Amazfit BIP

#### Your android version is:
Android 7.0

#### Your Gadgetbridge version is:
0.24.4

**Comment by danielegobbetti** [comment]
Would it be ok translating to L and l, or should something else be used?

**Comment by tomurbanowicz** [comment]
"L" and "l" it is OK


Pozdrawiam,
---
Tomasz Urbanowicz
http://www.urbanowicz.net.pl
http://blog.urbanowicz.net.pl
http://www.facebook.com/foto.urbanowicz
tel. 733 222 733

2018-02-10 9:49 GMT+01:00 Daniele Gobbetti <notifications@github.com>:
