### ISSUE TITLE
SSL certificate for blog.freeyourgadget.org expired

### ISSUE THREAD

**Issue by Findus23** [Freeyourgadget/Gadgetbridge#988]
Sorry, this issue is unrelated to the software (great work BTW), but rather the website https://blog.freeyourgadget.org/

The SSL certificate just expired. As you are using Let's Encrypt I'd recommend to set up a cronjob.

And [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=blog.freeyourgadget.org&hideResults=on) seems to complain about the DHparam es it is only 1024 bit long which is considered insecure. Simply create a longer one:
```
openssl dhparam -out dhparams.pem 2048
```

**Comment by danielegobbetti** [comment]
Thanks for the heads up. The certificate is renewed and I'll look into generating custom dhparam (even though that's just a blog ;-) )

**Comment by danielegobbetti** [comment]
FYI we deployed the custom dhparam.

**Comment by Findus23** [comment]
And no more warnings on https://www.ssllabs.com/ssltest/analyze.html?d=blog.freeyourgadget.org&hideResults=on 
👍

**Comment by Findus23** [comment]
@danielegobbetti I don't want to open a new issue and clutter the tracker with unrelated issues, so I'll post here:
https://blog.freeyourgadget.org doesn't load for me and seem down in general.

**Comment by danielegobbetti** [comment]
Thank for the heads up.looking into this

**Comment by danielegobbetti** [comment]
Should be back on, thanks again.

**Comment by Findus23** [comment]
@danielegobbetti,
Hi, just a quick reminder that the certificate expired again.

**Comment by Findus23** [comment]
@danielegobbetti Just another reminder that the SSL cert expired again :)

**Comment by Findus23** [comment]
And the same reminder as always :)

**Comment by IzzySoft** [comment]
Must be hard to set up a Cron job for that. Wonder what I did wrong that it works so smoothly with my sites :rofl:
