### ISSUE TITLE
Consistent color scheme

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#99]
Hello,

in the current release (0.4.6) the initial start screen is white/red, whereas the other activity/sleep/steps screens are on a dark background.
Switching from the dark screens back to the bright start screen (and the other way around) is quite unpleasant for the eyes – especially in low light conditions (e.g. at night). So I would like to suggest the feature of a consistent color scheme, with all screens having the same background color.
Personally, I would prefer a dark color scheme, because it's easier on the eyes (especially in low light conditions) and integrates better with the standard Android theme.

Again, many thanks for this great app!

**Comment by ashimokawa** [comment]
Yes you are right, I already experimented with dark colors, and I think it should be switchable by the user.

**Comment by cpfeiffer** [comment]
Totally agree, the Activity charts are work in progress and the coloring is going to get fixed eventually.

Help appreciated :-)

**Comment by 6arms1leg** [comment]
Nice, thanks a lot!
@ashimokawa, you said you already experimented with dark colors. So there will be a dark theme at some point? Personally, I'd prefer dark colors...
Anyway, thanks for your work!

**Comment by ashimokawa** [comment]
@6arms1leg , yes we will add a dark theme.
Actually I wanted to do it weeks ago, but then something bad happened. Now it brings back bad memories when I think of it, so postponed it ;)
(true story)
