### ISSUE TITLE
Autoexport: unable to select destination

### ISSUE THREAD

**Issue by Almtesh** [Freeyourgadget/Gadgetbridge#993]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
When I select path to auto-export, it shows me that no app can execute this action (see 
[screenshot](https://user-images.githubusercontent.com/8816946/36217694-791442be-11b2-11e8-985c-c75cd090be24.png)).
Amaze is my file explorer.

#### Your wearable device is:

Mi Band 2, firmware 1.0.1.39

#### Your android version is:

Android 5.1.1 "Cheap Sony" edition

#### Your Gadgetbridge version is:

0.24.5

**Comment by cpfeiffer** [comment]
Can you create a logfile and provide that (or an excerpt of it)?

**Comment by Almtesh** [comment]
I'm not sure of what I'm doing, so say me if this [log](https://github.com/Freeyourgadget/Gadgetbridge/files/1726014/Gadgetbridge.log) is usefull.

**Comment by Almtesh** [comment]
Showing the whole log, the exact log seems to be that:
```
I/ActivityManager(  893): START u0 {act=android.intent.action.CHOOSER cmp=android/com.android.internal.app.ChooserActivity (has extras)} from uid 10057 on display 0
V/WindowManager(  893): addAppToken: AppWindowToken{1a8b3c48 token=Token{5c486eb ActivityRecord{24ad9a3a u0 android/com.android.internal.app.ChooserActivity t9686}}} to stack=1 task=9686 at 2
V/WindowManager(  893): Adding window Window{ae93692 u0 android/com.android.internal.app.ChooserActivity} at 8 of 15 (after Window{1b5e0891 u0 nodomain.freeyourgadget.gadgetbridge/nodomain.freeyourgadget.gadgetbridge.activities.SettingsActivity})
```

**Comment by cpfeiffer** [comment]
Unfortunately the log does not show many hints. I think we need to revise our strategy to select the export file.

/cc @maufl help :-)
Maybe there is a way to get an outputstream to the URI so that we don't have to create a `File` for it. If we want to display more than just the DISPLAY_NAME (e.g. the file path), we could display the uri itself, which might be human-readable, even if a little more techie.

**Comment by Almtesh** [comment]
I agree, a path is more something I know how to handle than a error message in a transparent window.
What do you generate when you perform a auto-export? A file in a directory? I don't think you can select a directory with a file picker…

**Comment by maufl** [comment]
Well, to open a writable file, I used the Android Storage Framework. More specifically, I fire an `ACTION_CREATE_DOCUMENT` Intent. The Amaze file explorer does not seem to handle this Intent, however, there should be a build in system app that handles it. I guess this is not the case?

We thought about not going through the Storage Framework at all. But then we will need to include a custom file picker in Gadgetbridge and we would only be able to pick files located on the SD card, and not for example in Google Drive. I think this would increase the complexity in Gadgetbridge without providing more features and while doing the file access in a not Android way.

I'm not really an Android developer however, so I might be wrong.

**Comment by Almtesh** [comment]
I can't tell you, I only know `open ()` to write a file.  
I don't even know what application could handle a `ACTION_CREATE_DOCUMENT` Intent and I'm not really sure of what is a Intent…

**Comment by cpfeiffer** [comment]
I took some time to read up on this, here's what I gathered:
- we seem to be using the storage access framework properly :+1:
- we use the Uri together with the contentresolver to export the database :+1:
- only for display purposes do we try to convert the Uri to a file :+1:

AFAIK the file manager (here: Amaze) does not implement the `ACTION_CREATE_DOCUMENT`. That's the job of the respective `DocumentsProvider` (see https://developer.android.com/reference/android/content/Intent.html#ACTION_CREATE_DOCUMENT). So maybe something in the interaction between the system and Amaze is wrong.

@Almtesh Can you try what happens if you set a different file manager to be your default? If that works, then we should file a bug over here: https://github.com/TeamAmaze/AmazeFileManager/issues

**Comment by maufl** [comment]
The key point from the `ACTION_CREATE_DOCUMENT` documentation you link: 

Activity Action: Allow the user to create a new document. When invoked, **the system** will display the various DocumentsProvider instances installed on the device, letting the user navigate through them.

So, usually Android has a build in Activity that shows you all the document providers and also has a build in document provider for the content of the SD card. I'm confused as to why this seems not to be the case for @Almtesh.

**Comment by Almtesh** [comment]
Is there any app on F-droid that could handle this intent?
Anyone can tell me which base app handle this on his device?

**Comment by maufl** [comment]
I think it is the `com.android.documentsui` app, the default file manager of Android.
I found [this](https://www.reddit.com/r/AndroidQuestions/comments/6ze57i/what_is_comandroiddocumentsui_used_for_exactly/) explanation on Reddit. I don't know how to get it though, as it should be built into Android.

**Comment by ildar** [comment]
stumbled on this too. Is problem confirmed by devs?

**Comment by Almtesh** [comment]
No, it is not, you miss the `com.android.documentsui` like me. I reinstalled it and my problem is solved.

**Comment by ildar** [comment]
Please elaborate. You can't simply "reinstall" it, it's the system app.
Reddit didn't shed a light either.

**Comment by ildar** [comment]
Ah! reread the OP description and found that my issue is a bit different.
Yes, you need this system app active to choose the path. No more questions,
thanks.
