### ISSUE TITLE
Kontalk: generic notification instead of instant messaging

### ISSUE THREAD

**Issue by Almtesh** [Freeyourgadget/Gadgetbridge#994]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:

When I have a notification from Kontalk, my band shows the generic notification instead of the instant messaging one (and the message in the notification is not displayed).
I don't know how it is managed and if it is GB's reponsability to know Kontalk is a messaging app…

#### Your wearable device is:

Mi Band 2, firmware 1.0.1.39

#### Your android version is:

Android 5.1.1 "Cheap Sony" edition

#### Your Gadgetbridge version is:

0.24.5

**Comment by NotAFile** [comment]
Can you find for the full app id (the one with the dots) of the application? If you have that you or someone else can add it easily.

**Comment by Almtesh** [comment]
I think this is `org.kontalk`, according to this [F-droid page](https://f-droid.org/packages/org.kontalk/).
Like I said earlier, I don't know this language, so I don't know where find the place where this string must be put. I will try to code for Android, but I'm not there for now…

**Comment by Almtesh** [comment]
Thanks a lot @danielegobbetti.
