### ISSUE TITLE
Weather information wit Amazfit

### ISSUE THREAD

**Issue by schiessle** [Freeyourgadget/Gadgetbridge#995]
I wonder how to get weather information on my Amazfit. Does it only works with CyanogenMod/LineageOS? I use CarbonROM on my mobile phone and I'm a little bit lost what I should add to the location to make it work... if it works at all in this combination.

**Comment by ashimokawa** [comment]
Yes, it works using weather notification from f-droid 
After configuration, you have to enable the gadgetbridge fake skin in weather notification settings.

Then when weather notification updates, whether will also be sent to your bip.

We need to put that into the wiki properly. It is somewhere in the pebble section...

**Comment by schiessle** [comment]
Thanks, works nicely... 😃
