### ISSUE TITLE
Turn off Osmand notifications on Pebble 

### ISSUE THREAD

**Issue by amichaclar** [Freeyourgadget/Gadgetbridge#996]
Didn't see this previously posted so I thought I'd bring it up. 

I love the notifications that Gadgetbridge pulls from Osmand, but sometimes I'd like to be able to turn them off. Can this be added as a toggle in the settings? 

Thanks guys.

**Comment by danielegobbetti** [comment]
You can blacklist an application from the settings already (and toggle the blacklisting at will).

**Comment by amichaclar** [comment]
I already have the application blacklisted in the blacklist settings but I still receive the direction notifications. Is there something I'm missing? I thought integration with Osmand was a specific Gadgetbridge feature.

**Comment by danielegobbetti** [comment]
I see. I will look into this in the next days. In order to reproduce the issue, please give us some info: 
- do you have the "pebblekit" setting enabled in Gadgetbridge pebble options?
- Which version of Osmand are you using (from F-Droid, homebuilt, other)? 
- Do you have any special "pebble-related" plugin installed in F-droid?

**Comment by TaaviE** [comment]
Please provide your gadgetbridge app version too, just in case.

**Comment by amichaclar** [comment]
Thanks, friends! 

- I do have pebble kit enabled under "general settings". Could that be the cause? 
- I'm using Osmand from F-droid, currently the latest version 2.8.2 
- I don't currently have any other pebble related apps installed. 
- my GB version is the latest from F-droid, 0.24.5.

**Comment by danielegobbetti** [comment]
Yes osmand has a basic integration for pebble watches that uses pebblekit messages. It should only send navigation directions though (and only if you enable voice output for them within osmand IIRC).

**Comment by amichaclar** [comment]
Nothing stood out to me in the Osmand settings, but I could be overlooking something. 
I shall try disabling pebble kit and see if it yields what I desire. Will doing so break anything else? 
Forgive my ignorance by the way, I'm just an average user.

**Comment by amichaclar** [comment]
Nothing stood out to me in the Osmand settings, but I could be overlooking something. 
I shall try disabling pebble kit and see if it yields what I desire. Will doing so break anything else? 
Forgive my ignorance by the way, I'm just an average user.

**Comment by danielegobbetti** [comment]
If you don't have other application interacting with your pebble you will not lose any functionality. Please remember to disconnect and connect again after toggling the pebblekit setting.

**Comment by amichaclar** [comment]
I will test it out when I can and see how it goes.

If possible in the future a toggle for Osmand specifically would be awesome, but I understand this is not likely a high priority. 

Thank you for your help!

**Comment by danielegobbetti** [comment]
I don't know how selectively we can be on these message, I believe this could be done but I don't think it's high priority. Let us know if disabling pebblekit helps you (it should).

**Comment by 0mark** [comment]
The Notifications from Osmand are incredible annoying, although i think that depends on the Roads. In Hamburg (Germany) i get notifications often every few seconds, and then usually two or three in a row. I cant bear it and have to enable silent mode (and miss all important notifications).
I think disabling Voice in Osmand disabled notifications (i have to check that, i disabled voice yesterday the first time (could not find a way to lower the volume separately), and wondered why i did not have to enable silent mode as usual).

**Comment by danielegobbetti** [comment]
Can you check/confirm that disabling pebblekit support within gadgetbridge stops the notifications?

**Comment by 0mark** [comment]
Oh, wait, sorry, i totally messed that all up. I had "Pepple Notifications" set to "If the screen is off" (in Gadgetbridge). That's what caused the effect (i have it always on when using navigation). Disabling voice and/or sound in Osmand doesn't do anything. Or at least, i guess. I am a bit confused now :)
