### ISSUE TITLE
Black Screen -.-

### ISSUE THREAD

**Issue by llmdev** [Freeyourgadget/Gadgetbridge#998]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*In case of a bug, do not forget to attach logs!*

When updating my firmware it turned off and the screen always black, I can not turn on the screen, but it shows that the device is active bluetooth, I did not use it for 1 day my amazfit, this error is irreversible? is it possible to recover usb flash?
#### Your wearable device is:
Amazfit Bip Watch
*Please specify model and firmware version if possible*

#### Your android version is:
Android 8 OnePLus 5
#### Your Gadgetbridge version is:

Last

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by ashimokawa** [comment]
Which Firmware did the watch have before and which one did you try to flash?

Can you still connect to your watch with Gadgetbridge?

If you can connect what is the firmware gadgetbridge shows?

When you press the button does the watch vibrate?

**Comment by llmdev** [comment]
What firmware did the watch have before and which did you try to blink?

Version was 1.0.8

Can you still connect to your watch with Gadgetbridge?
I can not connect because it is not possible to press ok to pair

If you can connect what does the gadgetbridge firmware show?
I can not because I tried to reconnect = (

When you press the button, does the clock vibrate?

No

**Comment by llmdev** [comment]
[IMG](https://sslmovilesdualsim-2834.kxcdn.com/data/attachments/306/306178-fceba666bf1f32b88df526dbe7e5dc53.jpg)


It was with this picture, then it hung up .. I followed the order of the files correctly, first the fw, then the res .. Ai was locked and then erased ..

Sorry for my english I'm using a translator

**Comment by llmdev** [comment]
ChaoHu_9.14_eng_by_mauro_beta3.fw
ChaoHu_9.14_eng_by_mauro_beta3.res

Files brick my watch

**Comment by ashimokawa** [comment]
@llmdev 

If you try to pair in Gadgetbridge (plus icon) does the watch vibrate? If so, you could try to blindly touch the bottom left or right corner of the screen (I don't remember if the accept on screen button is left or right)

Also, why did you try to install "ChaoHu_9.14_eng_by_mauro_beta3.fw"? That is some random unofficial and totally unnecessary firmware. All new official firmwares are already in English. The correct way would have been to extract the firmware from an offical Mi Fit apk.

And also someone else reported that his watch bricked after trying to flash the firmware. you mentioned

See here:

http://tefov.blogspot.de/2017/11/amazfit-bip-update-english-firmware_25.html

**Comment by llmdev** [comment]
It seems that the total software of amazfit beep has disappeared, and it is possible to flash by usb? How do you solve this or has it become rubbish? (I.e.

**Comment by llmdev** [comment]
I tried several times to click on the side of the screen, it is matching and never ends ..

**Comment by llmdev** [comment]
Ha no vibrate =(

**Comment by danielegobbetti** [comment]
@llmdev I'm sorry but it really looks like you bricked your device. :(

We stated this many times already. One should **not** flash random files downloaded from the internet on gadgets. That's why we keep a list of whitelisted/supported firmwares and that's why Gadgetbridge displays a **big fat warning** that any other file is unsupported/unchecked.

**Comment by ashimokawa** [comment]
Just for completeness. I just took a brand new "English Version" Bip with Firmware 0.0.8.95 out of the sealed box and flashed to official 0.1.0.86 without problems. No brick.

**Comment by BGTecu** [comment]
I have the same problem. One week ago start showing some strange bars in the screen. That was for ~5 days. During those 5 days the scrin have some short random moments when the screen work perfectly. But from yesterday just turn black and not more ...  I am desperate. Anyone know why that happen? Any solution?
